# This file configures the latexmk command you can use to compile
# the pdf version of the blueprint
$pdf_mode = 1;
$pdflatex = 'xelatex -synctex=1';
@default_files = ('print.tex');
my $tenkz_root = $ENV{'TENKZ_ROOT'} // '../../.deps/tenkz';
$ENV{'TEXINPUTS'} =
  "$tenkz_root/tex/tenkz//:"
  . ($ENV{'TEXINPUTS'} // '');
