# This file configures the latexmk command you can use to compile
# the pdf version of the blueprint
$pdf_mode = 1;
$pdflatex = 'xelatex -synctex=1';
@default_files = ('print.tex');
$ENV{'TEXINPUTS'} =
  '../../.deps/tenkz/tex/tenkz//:'
  . ($ENV{'TEXINPUTS'} // '');
