/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.Symmetry.MPOSymmetry.MixedEndpointSupport
import TNLean.MPS.ParentHamiltonian.GroundSpaceMapContinuity
import TNLean.Algebra.ListOfFn

/-!
# Extended boundary maps at every chain length

For a word of length `N`, the extended product is
`Aⁱ¹ W Aⁱ² W ⋯ W Aⁱᴺ`: the final occurrence of `W` is omitted.
The associated boundary map sends `X` to the coefficients
`tr[Aⁱ¹ W Aⁱ² W ⋯ W Aⁱᴺ X]`.

If the letters of `A` span the full matrix algebra and `W` is nonzero,
the extended products span the full matrix algebra at every positive
length. The induction uses the two-sided ideal generated by `W`; no
invertibility or nonvanishing power of `W` is required. Consequently,
the boundary maps are injective and their supports have dimension `D²`.
A continuous family of such boundary maps has continuous orthogonal
support projectors.

Applied to the mixed endpoint tensor of Garre-Rubio–Lootens–Molnár,
arXiv:2203.12563, Section 5, lines 1687–1692, this gives the extended
`N`-site supports through both endpoints. This file concerns their ranks
and continuity; equality with an open-chain Hamiltonian kernel is a
separate assertion.
-/

open scoped Matrix

namespace MPSTensor
namespace MPOSymmetry

variable {d D D₀ D₁ : ℕ}

/-- Multiplying an injective family and any spanning family through a
nonzero matrix again gives a spanning family. This is the induction step
for the extended supports in arXiv:2203.12563, Section 5, line 1690. -/
theorem span_range_mul_nonzero_mul_of_span_eq_top
    {ι : Type*} (A : MPSTensor d D) (hA : Kraus.IsInjective A)
    (B : ι → Matrix (Fin D) (Fin D) ℂ)
    (hB : Submodule.span ℂ (Set.range B) = ⊤)
    (W : Matrix (Fin D) (Fin D) ℂ) (hW : W ≠ 0) :
    Submodule.span ℂ (Set.range fun p : Fin d × ι => A p.1 * W * B p.2) = ⊤ := by
  let S := Submodule.span ℂ
    (Set.range fun p : Fin d × ι => A p.1 * W * B p.2)
  have hspan := span_range_evalWord_mul_nonzero_mul_evalWord_eq_top
    (Kraus.isNBlkInjective_one_of_isInjective hA) hW
  apply top_unique
  rw [← hspan]
  apply Submodule.span_le.mpr
  rintro _ ⟨⟨u, v⟩, rfl⟩
  have hv : Kraus.evalWord A (List.ofFn v) ∈ Submodule.span ℂ (Set.range B) := by
    rw [hB]
    exact Submodule.mem_top
  change Kraus.evalWord A (List.ofFn u) * W * Kraus.evalWord A (List.ofFn v) ∈ S
  suffices hmul : ∀ M ∈ Submodule.span ℂ (Set.range B),
      Kraus.evalWord A (List.ofFn u) * W * M ∈ S from hmul _ hv
  intro M hM
  induction hM using Submodule.span_induction with
  | mem M hM =>
      obtain ⟨j, rfl⟩ := hM
      simpa [List.ofFn_succ, Kraus.evalWord] using
        (Submodule.subset_span ⟨(u 0, j), rfl⟩ : A (u 0) * W * B j ∈ S)
  | zero => simp
  | add M N _ _ hM hN =>
      simpa only [Matrix.mul_add] using S.add_mem hM hN
  | smul c M _ hM =>
      simpa only [Matrix.mul_smul] using S.smul_mem c hM

/-- Evaluate the extended product, omitting the final inserted matrix.
For a nonempty word this is `Aⁱ¹ W Aⁱ² ⋯ W Aⁱᴺ`.
Source: arXiv:2203.12563, Section 5, lines 1687–1692. -/
def insertedEvalWord (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ) :
    List (Fin d) → Matrix (Fin D) (Fin D) ℂ
  | [] => 1
  | i :: w => A i * Kraus.evalWord (fun j => W * A j) w

@[simp]
theorem insertedEvalWord_nil (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ) :
    insertedEvalWord A W [] = 1 := rfl

@[simp]
theorem insertedEvalWord_singleton
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ) (i : Fin d) :
    insertedEvalWord A W [i] = A i := by
  simp [insertedEvalWord]

/-- Peel off the first site of a nontrivial extended product.
Source: arXiv:2203.12563, Section 5, line 1690. -/
theorem insertedEvalWord_cons_of_ne_nil
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ)
    (i : Fin d) {w : List (Fin d)} (hw : w ≠ []) :
    insertedEvalWord A W (i :: w) = A i * W * insertedEvalWord A W w := by
  cases w with
  | nil => exact (hw rfl).elim
  | cons j w => simp [insertedEvalWord, Kraus.evalWord, Matrix.mul_assoc]

/-- Peel off the last site of a nontrivial extended product.
Source: arXiv:2203.12563, Section 5, line 1690. -/
theorem insertedEvalWord_append_singleton
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ)
    {w : List (Fin d)} (hw : w ≠ []) (j : Fin d) :
    insertedEvalWord A W (w ++ [j]) = insertedEvalWord A W w * W * A j := by
  cases w with
  | nil => exact (hw rfl).elim
  | cons i w =>
      simp [insertedEvalWord, Kraus.evalWord_append, Kraus.evalWord, Matrix.mul_assoc]

/-- First-site recursion for an extended word with a positive-length tail.
Source: arXiv:2203.12563, Section 5, line 1690. -/
theorem insertedEvalWord_ofFn_cons
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ)
    {L : ℕ} (hL : 0 < L) (i : Fin d) (σ : Cfg d L) :
    insertedEvalWord A W (List.ofFn (Fin.cons i σ)) =
      A i * W * insertedEvalWord A W (List.ofFn σ) := by
  rw [List.ofFn_cons, insertedEvalWord_cons_of_ne_nil A W i]
  exact mt List.ofFn_eq_nil_iff.mp (Nat.ne_of_gt hL)

/-- Last-site recursion for an extended word with a positive-length prefix.
Source: arXiv:2203.12563, Section 5, line 1690. -/
theorem insertedEvalWord_ofFn_snoc
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ)
    {L : ℕ} (hL : 0 < L) (σ : Cfg d L) (j : Fin d) :
    insertedEvalWord A W (List.ofFn (Fin.snoc σ j)) =
      insertedEvalWord A W (List.ofFn σ) * W * A j := by
  rw [List.ofFn_snoc, insertedEvalWord_append_singleton A W]
  exact mt List.ofFn_eq_nil_iff.mp (Nat.ne_of_gt hL)

/-- Every positive-length extended product family spans the full bond
algebra. Singular and even nilpotent insertions are allowed, since an
independent spanning tensor letter separates consecutive insertions.
Source: arXiv:2203.12563, Section 5, line 1690, extended to finite windows. -/
theorem span_range_insertedEvalWord_eq_top
    (A : MPSTensor d D) (hA : Kraus.IsInjective A)
    (W : Matrix (Fin D) (Fin D) ℂ) (hW : W ≠ 0)
    {N : ℕ} (hN : 0 < N) :
    Submodule.span ℂ
      (Set.range fun σ : Cfg d N => insertedEvalWord A W (List.ofFn σ)) = ⊤ := by
  suffices h : ∀ n : ℕ, Submodule.span ℂ
      (Set.range fun σ : Cfg d (n + 1) => insertedEvalWord A W (List.ofFn σ)) = ⊤ by
    obtain ⟨n, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hN)
    exact h n
  intro n
  induction n with
  | zero =>
      apply top_unique
      rw [← hA]
      apply Submodule.span_le.mpr
      rintro _ ⟨i, rfl⟩
      exact Submodule.subset_span ⟨fun _ => i, by simp [List.ofFn_succ]⟩
  | succ n ih =>
      have hspan := span_range_mul_nonzero_mul_of_span_eq_top A hA
        (fun σ : Cfg d (n + 1) => insertedEvalWord A W (List.ofFn σ)) ih W hW
      apply top_unique
      rw [← hspan]
      apply Submodule.span_le.mpr
      rintro _ ⟨⟨i, σ⟩, rfl⟩
      refine Submodule.subset_span ⟨Fin.cons i σ, ?_⟩
      exact insertedEvalWord_ofFn_cons A W (Nat.succ_pos n) i σ

/-- Vanishing of every extended trace coefficient forces the boundary
matrix to vanish. Source: arXiv:2203.12563, Section 5, line 1690. -/
theorem eq_zero_of_inserted_word_trace_eq_zero
    (A : MPSTensor d D) (hA : Kraus.IsInjective A)
    (W X : Matrix (Fin D) (Fin D) ℂ) (hW : W ≠ 0)
    {N : ℕ} (hN : 0 < N)
    (hX : ∀ σ : Cfg d N, Matrix.trace (insertedEvalWord A W (List.ofFn σ) * X) = 0) :
    X = 0 := by
  let φ : Matrix (Fin D) (Fin D) ℂ →ₗ[ℂ] ℂ :=
    (Matrix.traceLinearMap (Fin D) ℂ ℂ).comp (LinearMap.mulRight ℂ X)
  have hφ : φ = 0 := by
    apply LinearMap.ext_on_range
      (v := fun σ : Cfg d N => insertedEvalWord A W (List.ofFn σ))
      (hv := span_range_insertedEvalWord_eq_top A hA W hW hN)
    intro σ
    simpa [φ, Matrix.traceLinearMap_apply] using hX σ
  apply (Matrix.ext_iff_trace_mul_left (A := X) (B := 0)).2
  intro M
  simpa [φ, Matrix.traceLinearMap_apply] using congrArg (fun f => f M) hφ

/-- The extended boundary map in coefficient-space coordinates.
Source: arXiv:2203.12563, Section 5, lines 1687–1692. -/
noncomputable def insertedGroundSpaceMap
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ) (N : ℕ) :
    Matrix (Fin D) (Fin D) ℂ →ₗ[ℂ] NSiteSpace d N where
  toFun X σ := Matrix.trace (insertedEvalWord A W (List.ofFn σ) * X)
  map_add' X Y := by
    ext σ
    simp [Matrix.mul_add, Matrix.trace_add]
  map_smul' c X := by
    ext σ
    simp [Matrix.trace_smul]

@[simp]
theorem insertedGroundSpaceMap_apply
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ) (N : ℕ)
    (X : Matrix (Fin D) (Fin D) ℂ) (σ : Cfg d N) :
    insertedGroundSpaceMap A W N X σ =
      Matrix.trace (insertedEvalWord A W (List.ofFn σ) * X) := rfl

/-- At one site the extended map is the usual boundary map and does not
depend on the insertion. Source: arXiv:2203.12563, Section 5, line 1690. -/
@[simp]
theorem insertedGroundSpaceMap_one
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ) :
    insertedGroundSpaceMap A W 1 = groundSpaceMap A 1 := by
  ext X σ
  simp [List.ofFn_succ, Kraus.evalWord]

/-- Injectivity of the extended coefficient map, including the one-site
overlap used in the three-site intersection argument.
Source: arXiv:2203.12563, Section 5, lines 1690–1692. -/
theorem insertedGroundSpaceMap_injective
    (A : MPSTensor d D) (hA : Kraus.IsInjective A)
    (W : Matrix (Fin D) (Fin D) ℂ) (hW : W ≠ 0)
    {N : ℕ} (hN : 0 < N) :
    Function.Injective (insertedGroundSpaceMap A W N) := by
  refine (injective_iff_map_eq_zero (insertedGroundSpaceMap A W N)).2 fun X hX => ?_
  apply eq_zero_of_inserted_word_trace_eq_zero A hA W X hW hN
  intro σ
  exact congrFun hX σ

/-- Fixing the first site multiplies the boundary matrix on the right.
Source: arXiv:2203.12563, Section 5, lines 1690–1692. -/
theorem insertedGroundSpaceMap_cons
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ)
    {L : ℕ} (hL : 0 < L) (X : Matrix (Fin D) (Fin D) ℂ)
    (i : Fin d) (σ : Cfg d L) :
    insertedGroundSpaceMap A W (L + 1) X (Fin.cons i σ) =
      insertedGroundSpaceMap A W L (X * A i * W) σ := by
  simp only [insertedGroundSpaceMap_apply, insertedEvalWord_ofFn_cons A W hL]
  simpa only [Matrix.mul_assoc] using
    (Matrix.trace_mul_cycle' (insertedEvalWord A W (List.ofFn σ)) X (A i * W)).symm

/-- Fixing the last site multiplies the boundary matrix on the left.
Source: arXiv:2203.12563, Section 5, lines 1690–1692. -/
theorem insertedGroundSpaceMap_snoc
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ)
    {L : ℕ} (hL : 0 < L) (X : Matrix (Fin D) (Fin D) ℂ)
    (σ : Cfg d L) (j : Fin d) :
    insertedGroundSpaceMap A W (L + 1) X (Fin.snoc σ j) =
      insertedGroundSpaceMap A W L (W * A j * X) σ := by
  simp only [insertedGroundSpaceMap_apply, insertedEvalWord_ofFn_snoc A W hL,
    Matrix.mul_assoc]

/-- The extended `N`-site boundary map, with the final insertion omitted:
`X ↦ (tr[Aⁱ¹ W Aⁱ² ⋯ W Aⁱᴺ X])`.
Source: arXiv:2203.12563, Section 5, lines 1687–1692. -/
noncomputable def insertedBoundaryMap
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ) (N : ℕ) :
    EuclideanSpace ℂ (Fin D × Fin D) →L[ℂ] EuclideanSpace ℂ (Cfg d N) :=
  LinearMap.toContinuousLinearMap
    { toFun := fun v => WithLp.toLp 2 (fun σ =>
        Matrix.trace (insertedEvalWord A W (List.ofFn σ) *
          Matrix.of (fun a b => v (a, b))))
      map_add' := by
        intro v w
        apply PiLp.ext
        intro σ
        change Matrix.trace (insertedEvalWord A W (List.ofFn σ) *
          (Matrix.of (fun a b => v (a, b)) + Matrix.of (fun a b => w (a, b)))) = _
        simp only [Matrix.mul_add, Matrix.trace_add]
        rfl
      map_smul' := by
        intro c v
        apply PiLp.ext
        intro σ
        change Matrix.trace (insertedEvalWord A W (List.ofFn σ) *
          (c • Matrix.of (fun a b => v (a, b)))) = _
        simp only [Matrix.mul_smul, Matrix.trace_smul]
        rfl }

@[simp]
theorem insertedBoundaryMap_apply
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ) (N : ℕ)
    (v : EuclideanSpace ℂ (Fin D × Fin D)) (σ : Cfg d N) :
    insertedBoundaryMap A W N v σ =
      Matrix.trace (insertedEvalWord A W (List.ofFn σ) *
        Matrix.of (fun a b => v (a, b))) := rfl

/-- The Euclidean extended support is the coefficient-space support under
the standard change of coordinates.
Source: arXiv:2203.12563, Section 5, line 1690. -/
theorem mem_range_insertedBoundaryMap_iff
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ) (N : ℕ)
    (v : EuclideanSpace ℂ (Cfg d N)) :
    v ∈ (insertedBoundaryMap A W N).range ↔
      WithLp.linearEquiv 2 ℂ (NSiteSpace d N) v ∈ (insertedGroundSpaceMap A W N).range := by
  constructor
  · rintro ⟨X, rfl⟩
    exact ⟨Matrix.of (fun a b => X (a, b)), rfl⟩
  · rintro ⟨X, hX⟩
    refine ⟨WithLp.toLp 2 (fun p : Fin D × Fin D => X p.1 p.2), ?_⟩
    apply PiLp.ext
    intro σ
    exact congrFun hX σ

/-- The two-site case agrees with the extended local boundary map.
Source: arXiv:2203.12563, Section 5, line 1690. -/
@[simp]
theorem insertedBoundaryMap_two
    (A : MPSTensor d D) (W : Matrix (Fin D) (Fin D) ℂ) :
    insertedBoundaryMap A W 2 = insertedTwoSiteMap A W := by
  ext v σ
  simp [insertedEvalWord, List.ofFn_succ, Kraus.evalWord, Matrix.mul_assoc]

/-- The extended boundary map is injective at every positive length.
Source: arXiv:2203.12563, Section 5, line 1690, finite-window version. -/
theorem insertedBoundaryMap_injective
    (A : MPSTensor d D) (hA : Kraus.IsInjective A)
    (W : Matrix (Fin D) (Fin D) ℂ) (hW : W ≠ 0)
    {N : ℕ} (hN : 0 < N) :
    Function.Injective (insertedBoundaryMap A W N) := by
  refine (injective_iff_map_eq_zero (insertedBoundaryMap A W N)).2 fun v hv => ?_
  have hzero : Matrix.of (fun a b => v (a, b)) = (0 : Matrix (Fin D) (Fin D) ℂ) := by
    apply eq_zero_of_inserted_word_trace_eq_zero A hA W _ hW hN
    intro σ
    simpa using congrArg (fun z : EuclideanSpace ℂ (Cfg d N) => z σ) hv
  apply PiLp.ext
  rintro ⟨a, b⟩
  exact congrArg (fun M : Matrix (Fin D) (Fin D) ℂ => M a b) hzero

/-- The extended support has its full boundary dimension at every positive
length. Source: arXiv:2203.12563, Section 5, line 1690. -/
theorem finrank_range_insertedBoundaryMap
    (A : MPSTensor d D) (hA : Kraus.IsInjective A)
    (W : Matrix (Fin D) (Fin D) ℂ) (hW : W ≠ 0)
    {N : ℕ} (hN : 0 < N) :
    Module.finrank ℂ (insertedBoundaryMap A W N).range = D * D := by
  rw [LinearMap.finrank_range_of_inj (insertedBoundaryMap_injective A hA W hW hN)]
  simp

/-- Extended word products vary continuously with both the tensor and the
insertion. Source: arXiv:2203.12563, Section 5, lines 1687–1692. -/
theorem continuous_insertedEvalWord_family
    {X : Type*} [TopologicalSpace X]
    (A : X → MPSTensor d D) (hA : Continuous A)
    (W : X → Matrix (Fin D) (Fin D) ℂ) (hW : Continuous W)
    (w : List (Fin d)) :
    Continuous fun x => insertedEvalWord (A x) (W x) w := by
  cases w with
  | nil => simpa only [insertedEvalWord_nil] using
      (continuous_const : Continuous fun _ : X => (1 : Matrix (Fin D) (Fin D) ℂ))
  | cons i w =>
      have hWA : Continuous fun x => (fun j => W x * A x j) :=
        continuous_pi fun j => hW.matrix_mul ((continuous_apply j).comp hA)
      exact ((continuous_apply i).comp hA).matrix_mul
        (continuous_evalWord_family (fun x j => W x * A x j) hWA w)

/-- The extended boundary maps form an operator-norm continuous family.
Source: arXiv:2203.12563, Section 5, lines 1687–1692. -/
theorem continuous_insertedBoundaryMap_family
    {X : Type*} [TopologicalSpace X]
    (A : X → MPSTensor d D) (hA : Continuous A)
    (W : X → Matrix (Fin D) (Fin D) ℂ) (hW : Continuous W) (N : ℕ) :
    Continuous fun x => insertedBoundaryMap (A x) (W x) N := by
  apply continuous_clm_apply.2
  intro v
  apply (EuclideanSpace.equiv (Cfg d N) ℂ).symm.continuous.comp
  apply continuous_pi
  intro σ
  exact ((continuous_insertedEvalWord_family A hA W hW (List.ofFn σ)).matrix_mul
    continuous_const).matrix_trace

/-- The extended support projectors vary continuously whenever the letters
remain injective and the insertion remains nonzero.
Source: arXiv:2203.12563, Section 5, line 1690. -/
theorem continuous_range_insertedBoundaryMap_starProjection
    {X : Type*} [TopologicalSpace X]
    (A : X → MPSTensor d D) (hA : Continuous A)
    (W : X → Matrix (Fin D) (Fin D) ℂ) (hW : Continuous W)
    (hInj : ∀ x, Kraus.IsInjective (A x)) (hne : ∀ x, W x ≠ 0)
    {N : ℕ} (hN : 0 < N) :
    Continuous fun x => (insertedBoundaryMap (A x) (W x) N).range.starProjection := by
  exact continuous_iff_continuousAt.mpr fun x =>
    ContinuousLinearMap.continuousAt_range_starProjection_of_injective
      (fun y => insertedBoundaryMap (A y) (W y) N)
      (continuous_insertedBoundaryMap_family A hA W hW N).continuousAt
      (insertedBoundaryMap_injective (A x) (hInj x) (W x) (hne x) hN)

/-- The actual extended boundary map of the arbitrary mixed endpoint
interpolation is injective at every positive chain length, including both
endpoints. Source: arXiv:2203.12563, Section 5, lines 1687–1692. -/
theorem mixedEndpoint_insertedBoundaryMap_injective
    (A₀ : MPSTensor (D₀ * D₀) D₀) (A₁ : MPSTensor (D₁ * D₁) D₁)
    (h₀ : Kraus.IsInjective A₀) (h₁ : Kraus.IsInjective A₁)
    (hD₀ : 0 < D₀) (hD₁ : 0 < D₁) (γ : ℝ)
    {N : ℕ} (hN : 0 < N) :
    Function.Injective (insertedBoundaryMap (mixedEndpointBase A₀ A₁)
      (bondInterpolationMatrix D₀ D₁ γ) N) :=
  insertedBoundaryMap_injective _ (isInjective_mixedEndpointBase A₀ A₁ h₀ h₁) _
    (bondInterpolationMatrix_ne_zero hD₀ hD₁ γ) hN

/-- The extended mixed endpoint support has dimension `(D₀ + D₁)²` at every
positive chain length. All real parameters are permitted, so in particular
the whole closed interpolation interval is covered.
Source: arXiv:2203.12563, Section 5, lines 1687–1692. -/
theorem finrank_mixedEndpoint_extendedBoundarySupport
    (A₀ : MPSTensor (D₀ * D₀) D₀) (A₁ : MPSTensor (D₁ * D₁) D₁)
    (h₀ : Kraus.IsInjective A₀) (h₁ : Kraus.IsInjective A₁)
    (hD₀ : 0 < D₀) (hD₁ : 0 < D₁) (γ : ℝ)
    {N : ℕ} (hN : 0 < N) :
    Module.finrank ℂ (insertedBoundaryMap (mixedEndpointBase A₀ A₁)
      (bondInterpolationMatrix D₀ D₁ γ) N).range = (D₀ + D₁) * (D₀ + D₁) :=
  finrank_range_insertedBoundaryMap _ (isInjective_mixedEndpointBase A₀ A₁ h₀ h₁) _
    (bondInterpolationMatrix_ne_zero hD₀ hD₁ γ) hN

/-- The actual extended mixed endpoint boundary maps vary continuously
through both endpoints at every fixed chain length.
Source: arXiv:2203.12563, Section 5, lines 1687–1692. -/
theorem continuous_mixedEndpoint_insertedBoundaryMap
    (A₀ : MPSTensor (D₀ * D₀) D₀) (A₁ : MPSTensor (D₁ * D₁) D₁) (N : ℕ) :
    Continuous fun γ : ℝ => insertedBoundaryMap (mixedEndpointBase A₀ A₁)
      (bondInterpolationMatrix D₀ D₁ γ) N :=
  continuous_insertedBoundaryMap_family (fun _ => mixedEndpointBase A₀ A₁)
    continuous_const _ (continuous_bondInterpolationMatrix D₀ D₁) N

/-- Orthogonal projection onto the extended mixed endpoint support is
continuous at every positive chain length, including at the endpoints.
The constant-rank assertion is derived from the endpoint tensors.
Source: arXiv:2203.12563, Section 5, lines 1687–1692. -/
theorem continuous_mixedEndpoint_extendedBoundarySupport_starProjection
    (A₀ : MPSTensor (D₀ * D₀) D₀) (A₁ : MPSTensor (D₁ * D₁) D₁)
    (h₀ : Kraus.IsInjective A₀) (h₁ : Kraus.IsInjective A₁)
    (hD₀ : 0 < D₀) (hD₁ : 0 < D₁) {N : ℕ} (hN : 0 < N) :
    Continuous fun γ : ℝ => (insertedBoundaryMap (mixedEndpointBase A₀ A₁)
      (bondInterpolationMatrix D₀ D₁ γ) N).range.starProjection :=
  continuous_range_insertedBoundaryMap_starProjection
    (fun _ => mixedEndpointBase A₀ A₁) continuous_const _
    (continuous_bondInterpolationMatrix D₀ D₁)
    (fun _ => isInjective_mixedEndpointBase A₀ A₁ h₀ h₁)
    (bondInterpolationMatrix_ne_zero hD₀ hD₁) hN

end MPOSymmetry
end MPSTensor
