import TNLean.MPS.Defs

import Batteries.Data.Fin

/-!
# Non-translation-invariant MPS chains

This file introduces the fixed-length periodic-chain version of an MPS tensor:
site-dependent local tensors, their ordered matrix product coefficient, the
corresponding equality notion at fixed chain length, and the cyclic gauge
relation used by the algebraic fundamental-theorem route.
-/

open scoped Matrix

/-- A non-translation-invariant MPS chain with physical dimension `d`, bond
dimension `D`, and `n` sites. -/
abbrev MPSChainTensor (d D n : ℕ) := Fin n → MPSTensor d D

namespace MPSChainTensor

variable {d D n : ℕ}

/-- Ordered matrix product along a periodic chain. -/
def eval (A : MPSChainTensor d D n) (σ : Fin n → Fin d) :
    Matrix (Fin D) (Fin D) ℂ :=
  Fin.prod fun k => A k (σ k)

/-- The coefficient of the basis configuration `σ`, obtained by tracing the
ordered product of the selected local matrices. -/
def coeff (A : MPSChainTensor d D n) (σ : Fin n → Fin d) : ℂ :=
  Matrix.trace (eval A σ)

/-- Two non-TI chains generate the same state at the fixed system size `n`. -/
def SameState (A B : MPSChainTensor d D n) : Prop :=
  ∀ σ : Fin n → Fin d, coeff A σ = coeff B σ

/-- Every local tensor in the chain is injective. -/
def IsInjective (A : MPSChainTensor d D n) : Prop :=
  ∀ k : Fin n, MPSTensor.IsInjective (A k)

/-- Cyclic successor on `Fin n`, sending the last site back to `0`. -/
def cyclicSucc : Fin n → Fin n
  | ⟨i, hi⟩ =>
      match n with
      | 0 => False.elim (Nat.not_lt_zero _ hi)
      | m + 1 => ⟨(i + 1) % (m + 1), Nat.mod_lt _ (Nat.succ_pos _)⟩

@[simp] lemma cyclicSucc_val (k : Fin (n + 1)) :
    (cyclicSucc k).val = (k.val + 1) % (n + 1) := rfl

/-- Cyclic gauge equivalence on a periodic chain:
`Bₖ^σ = Zₖ Aₖ^σ Zₖ₊₁⁻¹`, where the successor is taken modulo `n`. -/
def GaugeEquiv (A B : MPSChainTensor d D n) : Prop :=
  ∃ Z : Fin n → GL (Fin D) ℂ, ∀ k : Fin n, ∀ i : Fin d,
    B k i = (Z k : Matrix (Fin D) (Fin D) ℂ) * A k i *
      (((Z (cyclicSucc k))⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)

@[simp] lemma eval_zero (A : MPSChainTensor d D 0) (σ : Fin 0 → Fin d) :
    eval A σ = 1 := by
  simp [eval]

@[simp] lemma eval_succ (A : MPSChainTensor d D (n + 1)) (σ : Fin (n + 1) → Fin d) :
    eval A σ = A 0 (σ 0) * eval (fun k => A k.succ) (fun k => σ k.succ) := by
  -- `Fin.prod_succ` splits off the first factor in the ordered product.
  simpa [eval] using Fin.prod_succ (fun k : Fin (n + 1) => A k (σ k))

@[simp] lemma coeff_eq (A : MPSChainTensor d D n) (σ : Fin n → Fin d) :
    coeff A σ = Matrix.trace (eval A σ) := rfl

theorem SameState.refl (A : MPSChainTensor d D n) : SameState A A := by
  intro σ
  rfl

theorem SameState.symm {A B : MPSChainTensor d D n} (h : SameState A B) :
    SameState B A := by
  intro σ
  exact (h σ).symm

theorem SameState.trans {A B C : MPSChainTensor d D n}
    (hAB : SameState A B) (hBC : SameState B C) :
    SameState A C := by
  intro σ
  exact (hAB σ).trans (hBC σ)

/-- `SameState` is an equivalence relation. -/
instance instEquivalenceSameState : Equivalence (SameState (d := d) (D := D) (n := n)) where
  refl := SameState.refl
  symm := SameState.symm
  trans := SameState.trans

theorem GaugeEquiv.refl (A : MPSChainTensor d D n) : GaugeEquiv A A := by
  refine ⟨fun _ => 1, ?_⟩
  intro k i
  simp

theorem GaugeEquiv.symm {A B : MPSChainTensor d D n} (h : GaugeEquiv A B) :
    GaugeEquiv B A := by
  obtain ⟨Z, hZ⟩ := h
  refine ⟨fun k => (Z k)⁻¹, ?_⟩
  intro k i
  rw [hZ k i]
  simp [Matrix.mul_assoc]

theorem GaugeEquiv.trans {A B C : MPSChainTensor d D n}
    (hAB : GaugeEquiv A B) (hBC : GaugeEquiv B C) :
    GaugeEquiv A C := by
  obtain ⟨Z, hZ⟩ := hAB
  obtain ⟨Y, hY⟩ := hBC
  refine ⟨fun k => Y k * Z k, ?_⟩
  intro k i
  rw [hY k i, hZ k i]
  simp [Matrix.mul_assoc, mul_inv_rev]

/-- `GaugeEquiv` is an equivalence relation. -/
instance instEquivalenceGaugeEquiv : Equivalence (GaugeEquiv (d := d) (D := D) (n := n)) where
  refl := GaugeEquiv.refl
  symm := GaugeEquiv.symm
  trans := GaugeEquiv.trans

end MPSChainTensor

/-- Alias for the fixed-length periodic-chain coefficient. -/
abbrev mpsChainCoeff := @MPSChainTensor.coeff

/-- Alias for equality of the states generated by two fixed-length periodic
chains. -/
abbrev SameChainState := @MPSChainTensor.SameState

/-- Alias for chainwise injectivity. -/
abbrev IsInjectiveChain := @MPSChainTensor.IsInjective

/-- Alias for cyclic gauge equivalence of periodic chains. -/
abbrev ChainGaugeEquiv := @MPSChainTensor.GaugeEquiv
