#!/usr/bin/env python3
"""Exact Rep(A4) Clebsch-Gordan and associator calculation.

This script uses the tetrahedral triplet representation generated by
s = diag(1,-1,-1), t e_i = e_{i+1} cyclically.  It constructs the seven
left- and right-associated isometric embeddings V -> V^tensor3, computes
the normalized Hilbert-Schmidt overlap F = W_R^* W_L, and derives the
commutator with diag(1,1,1,p^2,pq,pq,q^2).

Run from the repository root:
    python3 docs/audits/rfp_intrinsic/checks/a4_associator.py
Requires SymPy. Source: docs/audits/rfp_intrinsic/a4_associator.tex.
"""
import sympy as sp

I = sp.I
sqrt = sp.sqrt
omega = sp.exp(2*sp.pi*I/3).expand(complex=True)
omega = sp.simplify(-sp.Rational(1,2) + I*sqrt(3)/2)

# Tensor coordinate: pair (i,j) -> 3*i+j; triple (i,j,k) -> 9*i+3*j+k.
def pair(i,j): return 3*i+j
def triple(i,j,k): return 9*i+3*j+k

# C_chi: C -> V tensor V, columns as 9x1 matrices.
C0 = sp.zeros(9,1)
Cp = sp.zeros(9,1)
Cm = sp.zeros(9,1)
for i,c in enumerate([1,1,1]): C0[pair(i,i),0] = c/sqrt(3)
for i,c in enumerate([1,omega**2,omega]): Cp[pair(i,i),0] = sp.simplify(c/sqrt(3))
for i,c in enumerate([1,omega,omega**2]): Cm[pair(i,i),0] = sp.simplify(c/sqrt(3))

# Cs,Ca: V -> V tensor V.
Cs = sp.zeros(9,3); Ca = sp.zeros(9,3)
cyc = [(1,2),(2,0),(0,1)]
for k,(i,j) in enumerate(cyc):
    Cs[pair(i,j),k] = 1/sqrt(2); Cs[pair(j,i),k] = 1/sqrt(2)
    Ca[pair(i,j),k] = 1/sqrt(2); Ca[pair(j,i),k] = -1/sqrt(2)

# J_chi: V -> chi tensor V or V tensor chi, after identifying 1D tensor V with V.
J0 = sp.eye(3)
Jp = sp.diag(1,omega,omega**2)
Jm = sp.diag(1,omega**2,omega)

# Compose singlet left/right paths.
def left_singlet(C,J):
    W=sp.zeros(27,3)
    for out in range(3):
        for k in range(3):
            coeffJ=J[k,out]
            for i in range(3):
                for j in range(3):
                    W[triple(i,j,k),out] += C[pair(i,j),0]*coeffJ
    return sp.simplify(W)

def right_singlet(C,J):
    W=sp.zeros(27,3)
    for out in range(3):
        for i in range(3):
            coeffJ=J[i,out]
            for j in range(3):
                for k in range(3):
                    W[triple(i,j,k),out] += coeffJ*C[pair(j,k),0]
    return sp.simplify(W)

# Compose triplet paths: x is inner pair channel, y is outer fusion channel.
def left_triplet(Cx,Cy):
    W=sp.zeros(27,3)
    for out in range(3):
        for m in range(3):
            for k in range(3):
                coeffY=Cy[pair(m,k),out]
                for i in range(3):
                    for j in range(3):
                        W[triple(i,j,k),out] += Cx[pair(i,j),m]*coeffY
    return sp.simplify(W)

def right_triplet(Cx,Cy):
    W=sp.zeros(27,3)
    for out in range(3):
        for i in range(3):
            for m in range(3):
                coeffY=Cy[pair(i,m),out]
                for j in range(3):
                    for k in range(3):
                        W[triple(i,j,k),out] += coeffY*Cx[pair(j,k),m]
    return sp.simplify(W)

# Channel order: 1,1',1'',ss,sa,as,aa; triplet label is inner then outer.
WL = [left_singlet(C0,J0), left_singlet(Cp,Jp), left_singlet(Cm,Jm),
      left_triplet(Cs,Cs), left_triplet(Cs,Ca), left_triplet(Ca,Cs), left_triplet(Ca,Ca)]
WR = [right_singlet(C0,J0), right_singlet(Cp,Jp), right_singlet(Cm,Jm),
      right_triplet(Cs,Cs), right_triplet(Cs,Ca), right_triplet(Ca,Cs), right_triplet(Ca,Ca)]

# Check each isometry and orthogonality in normalized Hilbert-Schmidt metric.
def hs(A,B): return sp.simplify(sp.trace(A.conjugate().T*B)/3)
GL=sp.Matrix([[hs(a,b) for b in WL] for a in WL])
GR=sp.Matrix([[hs(a,b) for b in WR] for a in WR])
F=sp.simplify(sp.Matrix([[hs(a,b) for b in WL] for a in WR]))

# Exact representation and intertwiner checks.
s = sp.diag(1,-1,-1)
t = sp.Matrix([[0,0,1],[1,0,0],[0,1,0]])
assert s**2 == sp.eye(3) and t**3 == sp.eye(3) and (s*t)**3 == sp.eye(3)
for W in WL + WR:
    for g in (s,t):
        assert sp.simplify(sp.kronecker_product(g,g,g)*W-W*g) == sp.zeros(27,3)
for family in (WL,WR):
    for i,A in enumerate(family):
        for j,B in enumerate(family):
            target = sp.eye(3) if i == j else sp.zeros(3,3)
            assert sp.simplify(A.conjugate().T*B-target) == sp.zeros(3,3)
assert sp.simplify(sp.Matrix.hstack(*WL)-sp.Matrix.hstack(*WR)*sp.kronecker_product(F,sp.eye(3))) == sp.zeros(27,21)

p,q=sp.symbols('p q', complex=True)
Lam=sp.diag(1,1,1,p**2,p*q,p*q,q**2)
Comm=sp.simplify(F*Lam-Lam*F)

print('omega =',omega)
print('G_L ='); sp.print_latex(GL); print(GL)
print('G_R ='); sp.print_latex(GR); print(GR)
print('F ='); sp.print_latex(F); print(F)
print('F^*F ='); print(sp.simplify(F.conjugate().T*F))
print('commutator ='); sp.print_latex(Comm); print(Comm)
print('Nonzero commutator entries factored:')
for i in range(7):
    for j in range(7):
        x=sp.factor(Comm[i,j], extension=I*sqrt(3))
        if x != 0:
            print((i+1,j+1), x)
