/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.Examples.GHZ
import TNLean.MPS.Overlap.Basic
import Mathlib.LinearAlgebra.Matrix.Permutation

/-!
# GHZ: the `d`-level GHZ tensor

**Source.** Cirac, Pérez-García, Schuch, Verstraete 2021 (arXiv:2011.12127), Appendix A,
"The GHZ state", `Papers/2011.12127/TN-Review-main.tex` lines 2338–2345: the GHZ state
$\sum_{i=0}^{d-1}\lvert i,i,\dots,i\rangle$ on a `d`-level system is an MPS with
$A^i_{\alpha\beta}=\delta_{i=\alpha=\beta}$.
Review: arXiv:2011.12127, Appendix A, "The GHZ state".

**Formalized here.** The review's tensor for every physical dimension `d` (bond dimension
`D = d`), and the claim that its periodic vector is the unnormalized GHZ state
$\sum_i\lvert i,\dots,i\rangle$. The identity holds at every chain length, including the
empty chain, where both sides equal `d`.

## Main definitions

* `MPSTensor.ghzTensorD` : the review's tensor $A^i_{\alpha\beta}=\delta_{i=\alpha=\beta}$
* `MPSTensor.ghzStateD` : the unnormalized GHZ state $\sum_i\lvert i,\dots,i\rangle$
* `MPSTensor.ghzCyclicShiftAction` : the on-site $\mathbb Z_d$ representation by the
  cyclic shift of the physical basis

## Main results

* `MPSTensor.mpv_ghzTensorD` : the periodic vector of `ghzTensorD d` is `ghzStateD d N`
* `MPSTensor.ghzTensorD_two` : bridge, `ghzTensorD 2 = ghzTensor`
* `MPSTensor.ghzTensorD_transferMap` : the transfer map extracts the diagonal
* `MPSTensor.ghzTensorD_isTransferIdempotent` : the transfer map is idempotent
* `MPSTensor.ghzTensorD_not_isInjective` : the tensor is not injective for `2 ≤ d`
* `MPSTensor.ghzTensorD_isOnSiteSymmetric_perm` : on-site symmetry under every permutation
  of the physical basis
* `MPSTensor.ghzTensorD_isOnSiteSymmetric_cyclic` : on-site $\mathbb Z_d$ cyclic-shift
  symmetry

## References

- [arXiv:2011.12127](https://arxiv.org/abs/2011.12127) -- Cirac, Pérez-García, Schuch,
  Verstraete, *Matrix product states and projected entangled pair states: Concepts,
  symmetries, theorems*
-/

open scoped Matrix BigOperators
open Matrix

namespace MPSTensor

variable {d : ℕ}

/-- Source: arXiv:2011.12127, `Papers/2011.12127/TN-Review-main.tex` lines 2338–2345.
The GHZ tensor on a `d`-level system, with bond dimension `d` and entries
$A^i_{\alpha\beta}=\delta_{i=\alpha=\beta}$. -/
def ghzTensorD (d : ℕ) : MPSTensor d d :=
  fun i => Matrix.of fun α β => if i = α ∧ α = β then 1 else 0

/-- Source: arXiv:2011.12127, lines 2344–2345. The entries of the GHZ tensor. -/
@[simp] lemma ghzTensorD_apply (i α β : Fin d) :
    ghzTensorD d i α β = if i = α ∧ α = β then 1 else 0 := rfl

/-- Each matrix of the GHZ tensor is the diagonal matrix unit $\lvert i\rangle\langle i\rvert$. -/
lemma ghzTensorD_eq_diagonal (i : Fin d) :
    ghzTensorD d i = Matrix.diagonal (Pi.single i 1) := by
  ext α β
  by_cases h : α = β
  · subst h; by_cases hi : i = α
    · subst hi; simp
    · simp [hi, Ne.symm hi]
  · simp [h]

/-- Bridge: for `d = 2` the review's tensor is the repository's `ghzTensor`, so every
result proved for `ghzTensor` applies to it. -/
theorem ghzTensorD_two : ghzTensorD 2 = ghzTensor := by
  funext i
  rw [ghzTensorD_eq_diagonal, ghzTensor_apply]

/-- Source: arXiv:2011.12127, lines 2340–2343. The unnormalized GHZ state
$\sum_{i=0}^{d-1}\lvert i,i,\dots,i\rangle$ on `N` sites, as a function on configurations. -/
def ghzStateD (d N : ℕ) : Cfg d N → ℂ :=
  fun σ => ∑ i : Fin d, if ∀ n, σ n = i then 1 else 0

/-- A word of the GHZ tensor evaluates to the diagonal matrix recording, at each bond
index `x`, whether every letter equals `x`. -/
lemma ghzTensorD_evalWord {N : ℕ} (σ : Fin N → Fin d) :
    Kraus.evalWord (ghzTensorD d) (List.ofFn σ) =
      Matrix.diagonal (fun x => ∏ n, if σ n = x then (1 : ℂ) else 0) := by
  induction N with
  | zero => simp [Matrix.diagonal_one]
  | succ N ih =>
    rw [List.ofFn_succ, Kraus.evalWord_cons, ghzTensorD_eq_diagonal, ih,
      Matrix.diagonal_mul_diagonal]
    congr 1
    funext x
    simp [Fin.prod_univ_succ, Pi.single_apply, eq_comm]

/-- Source: arXiv:2011.12127, lines 2338–2345. The GHZ state is the MPS generated by the
review's tensor: its periodic coefficients are those of $\sum_i\lvert i,\dots,i\rangle$,
at every chain length `N`. -/
theorem mpv_ghzTensorD {N : ℕ} (σ : Cfg d N) : mpv (ghzTensorD d) σ = ghzStateD d N σ := by
  rw [mpv, coeff, ghzTensorD_evalWord, Matrix.trace_diagonal, ghzStateD]
  simp only [Fintype.prod_boole]
  congr 1
  funext x
  congr 1

/-! ### Transfer map and renormalization fixed point -/

/-- Project result: the transfer map of the GHZ tensor extracts the diagonal. -/
theorem ghzTensorD_transferMap (X : Matrix (Fin d) (Fin d) ℂ) :
    Kraus.transferMap (ghzTensorD d) X = Matrix.diagonal (fun i => X i i) := by
  rw [Kraus.transferMap_apply]
  ext α β
  simp only [ghzTensorD_eq_diagonal, Matrix.sum_apply, Matrix.diagonal_mul,
    Matrix.mul_diagonal, Matrix.diagonal_conjTranspose, Matrix.diagonal_apply, Pi.star_apply,
    Pi.single_apply]
  by_cases h : α = β
  · subst h; simp
  · simp [h]

/-- Project result: the transfer map of the GHZ tensor is idempotent, so the tensor is a
renormalization fixed point. -/
theorem ghzTensorD_isTransferIdempotent : IsTransferIdempotent (ghzTensorD d) := by
  refine LinearMap.ext fun X => ?_
  simp only [LinearMap.comp_apply, ghzTensorD_transferMap, Matrix.diagonal_apply_eq]

/-! ### Non-injectivity -/

/-- Project result: for `2 ≤ d` the GHZ tensor is not injective, since every matrix
$A^i$ vanishes off the diagonal. -/
theorem ghzTensorD_not_isInjective (hd : 2 ≤ d) : ¬ Kraus.IsInjective (ghzTensorD d) := by
  exact Kraus.not_isInjective_of_linearMap
    (Matrix.entryLinearMap ℂ ℂ (⟨0, by omega⟩ : Fin d) ⟨1, by omega⟩)
    (fun i => by simp [ghzTensorD_eq_diagonal])
    (Matrix.of fun _ _ => (1 : ℂ)) (by simp)

/-! ### On-site symmetry -/

/-- The GHZ state is invariant under relabelling the physical basis by a permutation. -/
lemma ghzStateD_perm {N : ℕ} (π : Equiv.Perm (Fin d)) (σ : Cfg d N) :
    ghzStateD d N (fun n => π (σ n)) = ghzStateD d N σ := by
  simp only [ghzStateD]
  rw [← Equiv.sum_comp π]
  simp [π.injective.eq_iff]

/-- Project result: the GHZ tensor is on-site symmetric under the permutation
representation of the symmetric group on the physical basis. -/
theorem ghzTensorD_isOnSiteSymmetric_perm :
    IsOnSiteSymmetric (ghzTensorD d) (Matrix.permMatrixHom (n := Fin d) (R := ℂ)) := by
  intro π N σ
  have htw : twistedTensor (ghzTensorD d) (Matrix.permMatrixHom (n := Fin d) (R := ℂ)) π =
      Kraus.reindexPhysical (π⁻¹ : Equiv.Perm (Fin d)) (ghzTensorD d) := by
    funext i
    simp [twistedTensor, Kraus.reindexPhysical, PEquiv.toMatrix_apply, Equiv.toPEquiv_apply,
      ite_smul]
  rw [htw, mpv_reindexPhysical, mpv_ghzTensorD, mpv_ghzTensorD, ghzStateD_perm]

/-- The on-site $\mathbb Z_d$ representation by the cyclic shift of the physical basis:
the generator acts by the permutation matrix of $i\mapsto i+1$ (inverse convention of
`Matrix.permMatrixHom`). -/
def ghzCyclicShiftAction (d : ℕ) [NeZero d] :
    Multiplicative (Fin d) →* Matrix (Fin d) (Fin d) ℂ :=
  (Matrix.permMatrixHom (n := Fin d) (R := ℂ)).comp
    (AddMonoidHom.toMultiplicativeLeft (AddAction.toPermHom (Fin d) (Fin d)))

/-- Project result: the GHZ tensor is on-site symmetric under the cyclic group
$\mathbb Z_d$ acting by cyclic shifts of the physical basis. -/
theorem ghzTensorD_isOnSiteSymmetric_cyclic [NeZero d] :
    IsOnSiteSymmetric (ghzTensorD d) (ghzCyclicShiftAction d) :=
  fun _ => ghzTensorD_isOnSiteSymmetric_perm _

end MPSTensor
