/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.ScalarThreeCocycleGroupCohomology
import TNLean.MPS.Examples.CZX.CZXAnomalyClass
import TNLean.MPS.Examples.KleinSymmetry
import TNLean.MPS.MPDO.BondOneOperator
import TNLean.MPS.Symmetry.MPOSymmetry.AssociatorComap
import TNLean.MPS.Symmetry.MPOSymmetry.AssociatorToolkit

/-!
# The anomaly of the printed Klein symmetry

The tensors for the operators printed in arXiv:2203.12563, Section 6,
`Papers/2203.12563/REsubmission.tex` lines 1884–1886, form a normal representation.
Its restriction to the subgroup generated by `ab` is exactly the decorated CZX
family. Consequently its cyclic anomaly invariant at `ab` is `-1`, independently
of the fusion tensors. A normalized representative has `ω(ab,ab,ab) = -1`, as
stated in the source.

**Scope restriction (sign at `ab`):** the source states that `ω(ab,ab,ab) = -1` is the only
nontrivial diagonal value. This module proves the sign at `ab` but not the values `+1` at
`a` and `b`.
Documented in `docs/paper-gaps/glm23_klein_printed_anomaly_scope.tex`.
-/

noncomputable section

open CZXCompression MPOTensor TNLean.Algebra

namespace KleinSymmetry

/-- The diagonal tensor is normal: flipping the input permutes its word alphabet.
Source: arXiv:2203.12563, line 1884. -/
theorem tensorA_isNormal : Kraus.IsNormal tensorA.toMPSTensor := by
  obtain ⟨n, hn, h⟩ := czxDecoratedMPS_isNormal
  refine ⟨n, hn, ?_⟩
  apply top_unique
  rw [← h]
  apply Submodule.span_le.mpr
  rintro _ ⟨w, rfl⟩
  apply Submodule.subset_span
  refine ⟨fun i ↦ finProdFinEquiv ((w i).divNat, (w i).modNat.rev), ?_⟩
  simp only [MPSTensor.evalWord_ofFn_eq_prod]
  congr 1
  congr 1
  funext i
  generalize w i = a
  fin_cases a <;> rfl

/-- Bond dimension for the printed Klein tensors (arXiv:2203.12563, line 1884). -/
def printedBond (g : Multiplicative (ZMod 2 × ZMod 2)) : ℕ :=
  if g.toAdd.1 = 0 then 1 else 2

/-- The identity, spin-flip, diagonal, and decorated CZX tensors
for arXiv:2203.12563, line 1884. -/
def printedTensor (g : Multiplicative (ZMod 2 × ZMod 2)) : MPOTensor 2 (printedBond g) := by
  unfold printedBond
  split
  · exact if g.toAdd.2 = 0 then idTensor 2 else tensorB
  · exact if g.toAdd.2 = 0 then tensorA else czxDecoratedTensor

/-- The printed family as group-indexed tensors (arXiv:2203.12563, line 1884). -/
def printedFamily : GroupFamily (Multiplicative (ZMod 2 × ZMod 2)) 2 where
  bondDim := printedBond
  bondDim_pos g := by unfold printedBond; split <;> norm_num
  tensor := printedTensor

/-- Each tensor represents the printed operator (arXiv:2203.12563, line 1884). -/
theorem mpo_printedFamily (g : Multiplicative (ZMod 2 × ZMod 2)) (N : ℕ) [NeZero N] :
    mpo (printedFamily.tensor g) N = operator N g := by
  revert g
  refine Multiplicative.forall_zmod_two_prod ?_ ?_ ?_ ?_
  · change mpo (idTensor 2) N = _
    simp [operator, mpo_idTensor]
  · change mpo tensorB N = _
    simp [operator, mpo_tensorB, ZMod.val_one]
  · change mpo tensorA N = _
    simp [operator, mpo_tensorA, ZMod.val_one]
  · change mpo czxDecoratedTensor N = _
    simp [operator, ← generatorA_mul_generatorB, ZMod.val_one]

/-- The printed tensors are a normal representation (arXiv:2203.12563, line 1884). -/
theorem printedFamily_isNormalRepresentation : printedFamily.IsNormalRepresentation where
  isNormal := by
    refine Multiplicative.forall_zmod_two_prod ?_ ?_ ?_ ?_
    · exact idTensor_isNormal
    · exact isNormal_of_bondOne tensorB 0 1 (by simp [tensorB, idTensor])
    · exact tensorA_isNormal
    · exact czxDecoratedMPS_isNormal
  operator_mul g h N hN := by
    have : NeZero N := ⟨Nat.ne_of_gt hN⟩
    simp only [mpo_printedFamily, operator_mul]

/-- The inclusion of the diagonal order-two subgroup. -/
def diagonalHom : Multiplicative (ZMod 2) →* Multiplicative (ZMod 2 × ZMod 2) where
  toFun g := Multiplicative.ofAdd (g.toAdd, g.toAdd)
  map_one' := rfl
  map_mul' _ _ := rfl

/-- On the diagonal subgroup the tensors are exactly those of decorated CZX. -/
theorem printedFamily_comap_diagonal : printedFamily.comap diagonalHom = czxFamily := by
  apply GroupFamily.ext_of_heq
  · funext g
    revert g
    exact Multiplicative.forall_zmod_two rfl rfl
  · exact Multiplicative.forall_zmod_two HEq.rfl HEq.rfl

/-- The printed symmetry has cyclic anomaly invariant `-1` at `ab`,
as in arXiv:2203.12563, line 1884. -/
theorem cyclicInvariant_omega_printedFamily (fd : printedFamily.FusionData) :
    ScalarThreeCochain.cyclicInvariant fd.omega (Multiplicative.ofAdd (1, 1)) 2 = -1 := by
  change ScalarThreeCochain.cyclicInvariant fd.omega (diagonalHom czxGen) 2 = -1
  rw [GroupFamily.FusionData.cyclicInvariant_omega_map_of_comap_eq fd diagonalHom
    printedFamily_isNormalRepresentation printedFamily_comap_diagonal czxFusionData
    czxGen_pow_two]
  exact cyclicInvariant_czxFusionData

/-- The printed symmetry has a nontrivial anomaly (arXiv:2203.12563, line 1884). -/
theorem not_isTrivialGaugeClass_omega_printedFamily (fd : printedFamily.FusionData) :
    ¬ ScalarThreeCochain.IsTrivialGaugeClass fd.omega := by
  apply ScalarThreeCochain.not_isTrivialGaugeClass_of_cyclicInvariant_ne_one
    (g := Multiplicative.ofAdd ((1, 1) : ZMod 2 × ZMod 2)) (n := 2) (by decide)
  rw [cyclicInvariant_omega_printedFamily]
  intro h
  have := congrArg Units.val h
  norm_num at this

/-- Every fusion choice admits a normalized representative with the printed diagonal sign
`ω(ab,ab,ab) = -1` (arXiv:2203.12563, line 1884). -/
theorem exists_normalized_omega_printedFamily (fd : printedFamily.FusionData) :
    ∃ ν : ScalarThreeCochain (Multiplicative (ZMod 2 × ZMod 2)),
      ScalarThreeCochain.IsCocycle ν ∧ ScalarThreeCochain.IsNormalized ν ∧
      ScalarThreeCochain.CohomologousTo ν fd.omega ∧
      ν (Multiplicative.ofAdd (1, 1)) (Multiplicative.ofAdd (1, 1))
        (Multiplicative.ofAdd (1, 1)) = -1 := by
  obtain ⟨ν, hv, hn, he⟩ := ScalarThreeCochain.exists_isNormalized_cohomologousTo
    (fd.isCocycle_omega printedFamily_isNormalRepresentation)
  refine ⟨ν, hv, hn, he, ?_⟩
  have hc := he.cyclicInvariant_eq
    (g := Multiplicative.ofAdd ((1, 1) : ZMod 2 × ZMod 2)) (n := 2) (by decide)
  rw [cyclicInvariant_omega_printedFamily] at hc
  simpa [ScalarThreeCochain.cyclicInvariant, Finset.prod_range_succ, hn.2.1] using hc

/-- The anomaly class of the printed symmetry in Mathlib's `H³(ℤ₂ × ℤ₂, ℂˣ)` is nonzero
for every choice of fusion tensors (arXiv:2203.12563, line 1884). -/
theorem anomalyClass_omega_printedFamily_ne_zero (fd : printedFamily.FusionData) :
    ScalarThreeCochain.anomalyClass
      ⟨fd.omega, fd.isCocycle_omega printedFamily_isNormalRepresentation⟩ ≠ 0 := fun h ↦
  not_isTrivialGaugeClass_omega_printedFamily fd
    ((ScalarThreeCochain.isTrivialGaugeClass_iff_anomalyClass_eq_zero _).2 h)

end KleinSymmetry
