/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.ParentHamiltonian.Defs
import Mathlib.Tactic

/-!
# Product-pair bridge for commuting parent Hamiltonians

This file packages the bridge between the Appendix B structural form
`A i = X * diag(Λ) * U i * X⁻¹` and the nearest-neighbor commutativity statement
needed in `TNLean/MPS/ParentHamiltonian/Commuting.lean`.

At the current stage of the library, the `NSiteSpace` API does not yet encode
explicit tensor-product support/locality data, while `IsNNCPH` is defined
*downstream* in `ParentHamiltonian/Commuting.lean`. To keep the dependency
direction suitable for the eventual proof of `rfp_implies_nncph`, this file does
not import `Commuting.lean`. Instead it does two things:

1. It defines the even-chain product-pair state generated by repeating a fixed
   two-site amplitude.
2. It packages the locality/independence input for nearest-neighbor parent
   projectors as an abstract witness on the full chain space, and proves from
   that witness the unfolded commutativity statement for the two-site local
   terms.

Once the full Appendix B decomposition is extracted, the intended downstream use
is:

* build a `ProductPairBridge A` witness from the structural data;
* apply `ProductPairBridge.commuting_twoSite_localTerms`;
* unfold `IsNNCPH` in `ParentHamiltonian/Commuting.lean`.

TODO(tensor-product-locality): replace the abstract commutation witness for the
full-chain endomorphisms by genuine support-locality statements once
`NSiteSpace` carries the required tensor-product factorization API.
-/

open scoped BigOperators

namespace MPSTensor

variable {d D : ℕ}

/-- Extract the `p`-th adjacent two-site block from a configuration on `2N`
sites. -/
def productPairWindow (N : ℕ) (σ : Cfg d (2 * N)) (p : Fin N) : Cfg d 2 :=
  fun j => σ ⟨2 * p.val + j.val, by
    have hp : p.val < N := p.isLt
    have hj : j.val < 2 := j.isLt
    omega⟩

@[simp] lemma productPairWindow_apply (N : ℕ) (σ : Cfg d (2 * N)) (p : Fin N)
    (j : Fin 2) :
    productPairWindow N σ p j = σ ⟨2 * p.val + j.val, by
      have hp : p.val < N := p.isLt
      have hj : j.val < 2 := j.isLt
      omega⟩ := rfl

/-- The even-chain state obtained by repeating a fixed two-site amplitude on
adjacent pairs.

When the two-site amplitude is the maximally entangled pair, this is the
product-of-entangled-pairs state appearing in Appendix B. We keep the two-site
amplitude abstract here; the eventual structural-form bridge will instantiate it
with the maximally entangled pair transported through the relevant physical
basis change. -/
def productPairState (ψ₂ : NSiteSpace d 2) (N : ℕ) : NSiteSpace d (2 * N) :=
  fun σ => ∏ p : Fin N, ψ₂ (productPairWindow N σ p)

@[simp] lemma productPairState_zero (ψ₂ : NSiteSpace d 2) :
    productPairState ψ₂ 0 = fun _ => (1 : ℂ) := by
  funext σ
  simp [productPairState]

/-- An MPS tensor has product-pair MPVs when every even-length coefficient
function factors as a repeated copy of one fixed two-site amplitude.

Odd chain lengths are deliberately omitted from this definition: the product
pairing ansatz naturally lives on even chains, and the commuting-parent bridge
below only needs the two-site local structure. -/
def HasProductPairMPV (A : MPSTensor d D) : Prop :=
  ∃ ψ₂ : NSiteSpace d 2, ∀ N (σ : Cfg d (2 * N)),
    mpv A σ = productPairState ψ₂ N σ

theorem HasProductPairMPV.exists_twoSiteAmplitude {A : MPSTensor d D}
    (hA : HasProductPairMPV A) :
    ∃ ψ₂ : NSiteSpace d 2, ∀ N (σ : Cfg d (2 * N)),
      mpv A σ = productPairState ψ₂ N σ :=
  hA

/-- Witness that the nearest-neighbor local terms of `A` are the local
projectors coming from independent product-pair bonds on an `N`-site chain.

Because the current parent-Hamiltonian API does not yet carry tensor-product
support data on `NSiteSpace d N`, the witness is recorded directly as a family
of endomorphisms on the full chain space. -/
structure HasProductPairLocalProjectors (A : MPSTensor d D) (N : ℕ) where
  proj : Fin N → NSiteSpace d N →ₗ[ℂ] NSiteSpace d N
  hidem : ∀ i, proj i * proj i = proj i
  hlocal : ∀ i, localTerm A 2 N i = proj i
  hcomm : ∀ i j, proj i * proj j = proj j * proj i

theorem HasProductPairLocalProjectors.localTerm_idempotent
    {A : MPSTensor d D} {N : ℕ}
    (hPair : HasProductPairLocalProjectors A N) (i : Fin N) :
    localTerm A 2 N i * localTerm A 2 N i = localTerm A 2 N i := by
  rw [hPair.hlocal i, hPair.hidem i]

/-- The abstract product-pair locality witness implies commutativity of the
nearest-neighbor parent-Hamiltonian local terms.

This is exactly the body of `IsCommutingParentHam A 2 N` after unfolding the
definition in `ParentHamiltonian/Commuting.lean`. -/
theorem HasProductPairLocalProjectors.commuting_twoSite_localTerms
    {A : MPSTensor d D} {N : ℕ}
    (hPair : HasProductPairLocalProjectors A N) :
    ∀ i j : Fin N,
      localTerm A 2 N i * localTerm A 2 N j =
        localTerm A 2 N j * localTerm A 2 N i := by
  intro i j
  rw [hPair.hlocal i, hPair.hlocal j]
  exact hPair.hcomm i j

/-- Complete bridge data for a tensor whose MPVs are products of two-site pairs
and whose nearest-neighbor parent projectors are induced by independent bond
projectors on every finite chain. -/
structure ProductPairBridge (A : MPSTensor d D) where
  pairAmplitude : NSiteSpace d 2
  hmpv : ∀ N (σ : Cfg d (2 * N)),
    mpv A σ = productPairState pairAmplitude N σ
  localProjectors : ∀ N, HasProductPairLocalProjectors A N

theorem ProductPairBridge.mpv_eq_productPairState {A : MPSTensor d D}
    (hBridge : ProductPairBridge A) :
    ∀ N (σ : Cfg d (2 * N)),
      mpv A σ = productPairState hBridge.pairAmplitude N σ :=
  hBridge.hmpv

theorem ProductPairBridge.hasProductPairMPV {A : MPSTensor d D}
    (hBridge : ProductPairBridge A) :
    HasProductPairMPV A :=
  ⟨hBridge.pairAmplitude, hBridge.hmpv⟩

/-- The bridge data yields the unfolded `IsNNCPH` conclusion: all two-site local
terms commute on every finite chain.

Since `IsNNCPH` is defined downstream in `ParentHamiltonian/Commuting.lean`, we
state the commutation relation directly here to keep the dependency direction
suitable for the eventual `rfp_implies_nncph` proof. -/
theorem ProductPairBridge.commuting_twoSite_localTerms
    {A : MPSTensor d D} (hBridge : ProductPairBridge A) (N : ℕ) :
    ∀ i j : Fin N,
      localTerm A 2 N i * localTerm A 2 N j =
        localTerm A 2 N j * localTerm A 2 N i :=
  (hBridge.localProjectors N).commuting_twoSite_localTerms

theorem ProductPairBridge.localTerm_idempotent
    {A : MPSTensor d D} (hBridge : ProductPairBridge A) (N : ℕ) (i : Fin N) :
    localTerm A 2 N i * localTerm A 2 N i = localTerm A 2 N i :=
  (hBridge.localProjectors N).localTerm_idempotent i

end MPSTensor
