/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.ParentHamiltonian.Defs
import TNLean.MPS.RFP.StructuralFull
import Mathlib.Data.Fin.Basic

/-!
# Product-pair structural connection for commuting parent Hamiltonians

This file records the connection between the Appendix B structural form
`A i = X * diag(Λ) * U i * X⁻¹` and the nearest-neighbor commutativity statement
needed in `TNLean/MPS/ParentHamiltonian/Commuting.lean`.

At the current stage of the library, the `NSiteSpace` API does not yet encode
explicit tensor-product support/locality data, while `IsNNCPH` is defined
*downstream* in `ParentHamiltonian/Commuting.lean`. To keep the dependency
direction suitable for the eventual proof of `rfp_implies_nncph`, this file does
not import `Commuting.lean`. Instead it does three things:

1. It defines the even-chain product-pair state generated by repeating a fixed
   two-site amplitude.
2. It records the locality/independence input for nearest-neighbor parent
   projectors as an abstract witness on the full chain space, and proves from
   that witness the unfolded commutativity statement for the two-site local
   terms.
3. It bundles the already-proved Appendix B structural data, removes the
   harmless gauge matrices from coefficient calculations, and names the remaining
   chain-space extraction needed to turn that structural data into a
   `ProductPairBridge`.

The intended downstream use is:

* obtain `AppendixBStructuralData A` from `rfp_nt_structural_full`;
* build `AppendixBProductPairExtraction` for that structural witness;
* apply `ProductPairBridge.commuting_twoSite_localTerms`;
* unfold `IsNNCPH` in `ParentHamiltonian/Commuting.lean`.

TODO(tensor-product-locality): replace the abstract commutation witness for the
full-chain endomorphisms by genuine support-locality statements once
`NSiteSpace` carries the required tensor-product factorization API.
-/

open scoped Matrix BigOperators

namespace MPSTensor

variable {d D : ℕ}

/-- Extract the `p`-th adjacent two-site block from a configuration on `2N`
sites. -/
def productPairWindow (N : ℕ) (σ : Cfg d (2 * N)) (p : Fin N) : Cfg d 2 :=
  fun j => σ ⟨2 * p.val + j.val, by
    have hp : p.val < N := p.isLt
    have hj : j.val < 2 := j.isLt
    omega⟩

@[simp] lemma productPairWindow_apply (N : ℕ) (σ : Cfg d (2 * N)) (p : Fin N)
    (j : Fin 2) :
    productPairWindow N σ p j = σ ⟨2 * p.val + j.val, by
      have hp : p.val < N := p.isLt
      have hj : j.val < 2 := j.isLt
      omega⟩ := rfl

/-- On one pair, the product-pair window is the whole two-site configuration. -/
@[simp] theorem productPairWindow_one (σ : Cfg d (2 * 1)) :
    productPairWindow 1 σ 0 = σ := by
  funext j
  simp [productPairWindow]

/-- The even-chain state obtained by repeating a fixed two-site amplitude on
adjacent pairs.

When the two-site amplitude is the maximally entangled pair, this is the
product-of-entangled-pairs state appearing in Appendix B. We keep the two-site
amplitude abstract here; the eventual structural-form construction will
instantiate it with the maximally entangled pair transported through the relevant
physical basis change. -/
def productPairState (ψ₂ : NSiteSpace d 2) (N : ℕ) : NSiteSpace d (2 * N) :=
  fun σ => ∏ p : Fin N, ψ₂ (productPairWindow N σ p)

@[simp] lemma productPairState_zero (ψ₂ : NSiteSpace d 2) :
    productPairState ψ₂ 0 = fun _ => (1 : ℂ) := by
  funext σ
  simp [productPairState]

/-- On a single pair, the product-pair state is the original two-site amplitude. -/
@[simp] theorem productPairState_one (ψ₂ : NSiteSpace d 2) (σ : Cfg d (2 * 1)) :
    productPairState ψ₂ 1 σ = ψ₂ σ := by
  simp [productPairState]

/-- An MPS tensor has product-pair MPVs when every even-length coefficient
function factors as a repeated copy of one fixed two-site amplitude.

Odd chain lengths are deliberately omitted from this definition: the product
pairing ansatz naturally lives on even chains, and the commuting-parent
construction below only needs the two-site local structure. -/
def HasProductPairMPV (A : MPSTensor d D) : Prop :=
  ∃ ψ₂ : NSiteSpace d 2, ∀ N (σ : Cfg d (2 * N)),
    mpv A σ = productPairState ψ₂ N σ

theorem HasProductPairMPV.exists_twoSiteAmplitude {A : MPSTensor d D}
    (hA : HasProductPairMPV A) :
    ∃ ψ₂ : NSiteSpace d 2, ∀ N (σ : Cfg d (2 * N)),
      mpv A σ = productPairState ψ₂ N σ :=
  hA

/-- Witness that the nearest-neighbor local terms of `A` are the local
projectors coming from independent product-pair bonds on an `N`-site chain.

Because the current parent-Hamiltonian API does not yet carry tensor-product
support data on `NSiteSpace d N`, the witness is recorded directly as a family
of endomorphisms on the full chain space. -/
structure HasProductPairLocalProjectors (A : MPSTensor d D) (N : ℕ) where
  proj : Fin N → NSiteSpace d N →ₗ[ℂ] NSiteSpace d N
  hidem : ∀ i, proj i * proj i = proj i
  hlocal : ∀ i, localTerm A 2 N i = proj i
  hcomm : ∀ i j, proj i * proj j = proj j * proj i

theorem HasProductPairLocalProjectors.localTerm_idempotent
    {A : MPSTensor d D} {N : ℕ}
    (hPair : HasProductPairLocalProjectors A N) (i : Fin N) :
    localTerm A 2 N i * localTerm A 2 N i = localTerm A 2 N i := by
  rw [hPair.hlocal i, hPair.hidem i]

/-- The abstract product-pair locality witness implies commutativity of the
nearest-neighbor parent-Hamiltonian local terms.

This is exactly the body of `IsCommutingParentHam A 2 N` after unfolding the
definition in `ParentHamiltonian/Commuting.lean`. -/
theorem HasProductPairLocalProjectors.commuting_twoSite_localTerms
    {A : MPSTensor d D} {N : ℕ}
    (hPair : HasProductPairLocalProjectors A N) :
    ∀ i j : Fin N,
      localTerm A 2 N i * localTerm A 2 N j =
        localTerm A 2 N j * localTerm A 2 N i := by
  intro i j
  rw [hPair.hlocal i, hPair.hlocal j]
  exact hPair.hcomm i j

/-- Complete `ProductPairBridge` data for a tensor whose MPVs are products of
two-site pairs and whose nearest-neighbor parent projectors are induced by
independent bond projectors on every finite chain. -/
structure ProductPairBridge (A : MPSTensor d D) where
  pairAmplitude : NSiteSpace d 2
  hmpv : ∀ N (σ : Cfg d (2 * N)),
    mpv A σ = productPairState pairAmplitude N σ
  localProjectors : ∀ N, HasProductPairLocalProjectors A N

theorem ProductPairBridge.mpv_eq_productPairState {A : MPSTensor d D}
    (hBridge : ProductPairBridge A) :
    ∀ N (σ : Cfg d (2 * N)),
      mpv A σ = productPairState hBridge.pairAmplitude N σ :=
  hBridge.hmpv

theorem ProductPairBridge.hasProductPairMPV {A : MPSTensor d D}
    (hBridge : ProductPairBridge A) :
    HasProductPairMPV A :=
  ⟨hBridge.pairAmplitude, hBridge.hmpv⟩

/-- The `ProductPairBridge` witness yields the unfolded `IsNNCPH` conclusion:
all two-site local terms commute on every finite chain.

Since `IsNNCPH` is defined downstream in `ParentHamiltonian/Commuting.lean`, we
state the commutation relation directly here to keep the dependency direction
suitable for the eventual `rfp_implies_nncph` proof. -/
theorem ProductPairBridge.commuting_twoSite_localTerms
    {A : MPSTensor d D} (hBridge : ProductPairBridge A) (N : ℕ) :
    ∀ i j : Fin N,
      localTerm A 2 N i * localTerm A 2 N j =
        localTerm A 2 N j * localTerm A 2 N i :=
  (hBridge.localProjectors N).commuting_twoSite_localTerms

theorem ProductPairBridge.localTerm_idempotent
    {A : MPSTensor d D} (hBridge : ProductPairBridge A) (N : ℕ) (i : Fin N) :
    localTerm A 2 N i * localTerm A 2 N i = localTerm A 2 N i :=
  (hBridge.localProjectors N).localTerm_idempotent i

/-! ### Appendix B structural data as the upstream input -/

/-- Bundled form of the Appendix B structural decomposition
`A i = X * diag(Λ) * U i * X⁻¹`.

The theorem `rfp_nt_structural_full` proves existence of this data from the
RFP, normality, and left-canonical hypotheses.  We keep it as a structure so
that the remaining chain-space extraction step for `RFP ⟹ NNCPH` has a compact
hypothesis surface. -/
structure AppendixBStructuralData (A : MPSTensor d D) where
  /-- The virtual-bond change of basis. -/
  X : Matrix (Fin D) (Fin D) ℂ
  /-- Positive diagonal weights. -/
  Λ : Fin D → ℝ
  /-- The residual left-canonical tensor family. -/
  U : MPSTensor d D
  /-- The change-of-basis matrix is invertible. -/
  hX_det : X.det ≠ 0
  /-- The diagonal weights are strictly positive. -/
  hΛ_pos : ∀ k, 0 < Λ k
  /-- The residual tensor is left-canonical. -/
  hU_left : ∑ i : Fin d, (U i)ᴴ * U i = 1
  /-- The original tensor has the Appendix B structural form. -/
  hA_eq : ∀ i, A i = X * Matrix.diagonal (fun k => (Λ k : ℂ)) * U i * X⁻¹

/-- The proved structural form gives nonempty bundled Appendix B structural data. -/
theorem AppendixBStructuralData.exists_ofRFP (A : MPSTensor d D) [NeZero D]
    (hNT : IsNormal A) (hRFP : IsRFP A)
    (hLeft : ∑ i : Fin d, (A i)ᴴ * A i = 1) :
    Nonempty (AppendixBStructuralData A) := by
  classical
  obtain ⟨X, Λ, U, hX_det, hΛ_pos, hU_left, hA_eq⟩ :=
    rfp_nt_structural_full A hNT hRFP hLeft
  exact ⟨
    { X := X
      Λ := Λ
      U := U
      hX_det := hX_det
      hΛ_pos := hΛ_pos
      hU_left := hU_left
      hA_eq := hA_eq }⟩

/-- Extract the bundled Appendix B structural data from the proved structural
form theorem.

This is a noncomputable definition only because it chooses a witness from the
nonempty type produced by `AppendixBStructuralData.exists_ofRFP`; it introduces
no new assumptions or trusted constants. -/
noncomputable def AppendixBStructuralData.ofRFP (A : MPSTensor d D) [NeZero D]
    (hNT : IsNormal A) (hRFP : IsRFP A)
    (hLeft : ∑ i : Fin d, (A i)ᴴ * A i = 1) :
    AppendixBStructuralData A :=
  Classical.choice (AppendixBStructuralData.exists_ofRFP A hNT hRFP hLeft)

/-- The two-site amplitude canonically read from a chosen Appendix B structural
witness.

The key point is that this amplitude depends on the chosen decomposition
`X, Λ, U`; an extraction witness must factor even-chain MPVs through this
particular structural amplitude, not through an unrelated two-site vector. -/
noncomputable def AppendixBStructuralData.twoSiteAmplitude {A : MPSTensor d D}
    (hStruct : AppendixBStructuralData A) : NSiteSpace d 2 :=
  let L : Matrix (Fin D) (Fin D) ℂ :=
    Matrix.diagonal fun k => (hStruct.Λ k : ℂ)
  fun σ =>
    Matrix.trace
      ((hStruct.X * L * hStruct.U (σ 0) * hStruct.X⁻¹) *
        (hStruct.X * L * hStruct.U (σ 1) * hStruct.X⁻¹))

/-- The gauge-removed tensor `Λ U_i` associated to a chosen Appendix B witness.

The structural equality says that `A` is a similarity transform of this tensor.
Separating it out lets the remaining even-chain coefficient calculation ignore the
basis-change matrices `X` and `X⁻¹`. -/
noncomputable def AppendixBStructuralData.coreTensor {A : MPSTensor d D}
    (hStruct : AppendixBStructuralData A) : MPSTensor d D :=
  fun i => Matrix.diagonal (fun k => (hStruct.Λ k : ℂ)) * hStruct.U i

@[simp] theorem AppendixBStructuralData.coreTensor_apply {A : MPSTensor d D}
    (hStruct : AppendixBStructuralData A) (i : Fin d) :
    hStruct.coreTensor i = Matrix.diagonal (fun k => (hStruct.Λ k : ℂ)) * hStruct.U i :=
  rfl

/-- The original tensor is gauge equivalent to its gauge-removed Appendix B core. -/
theorem AppendixBStructuralData.gaugeEquiv_coreTensor {A : MPSTensor d D}
    (hStruct : AppendixBStructuralData A) :
    GaugeEquiv hStruct.coreTensor A := by
  let Xg : GL (Fin D) ℂ := Matrix.GeneralLinearGroup.mkOfDetNeZero hStruct.X hStruct.hX_det
  refine ⟨Xg, ?_⟩
  intro i
  simp [Xg, AppendixBStructuralData.coreTensor, hStruct.hA_eq i, Matrix.mul_assoc]

/-- The Appendix B basis change does not change any MPV coefficient. -/
theorem AppendixBStructuralData.mpv_eq_coreTensor {A : MPSTensor d D}
    (hStruct : AppendixBStructuralData A) {N : ℕ} (σ : Cfg d N) :
    mpv A σ = mpv hStruct.coreTensor σ :=
  (GaugeEquiv.sameMPV hStruct.gaugeEquiv_coreTensor N σ).symm

/-- The structural two-site amplitude is exactly the two-site MPV coefficient. -/
theorem AppendixBStructuralData.twoSiteAmplitude_eq_mpv {A : MPSTensor d D}
    (hStruct : AppendixBStructuralData A) (σ : Cfg d 2) :
    hStruct.twoSiteAmplitude σ = mpv A σ := by
  simp [mpv, coeff, AppendixBStructuralData.twoSiteAmplitude, hStruct.hA_eq,
    evalWord, List.ofFn_succ, List.ofFn_zero]

/-- Equivalently, the structural two-site amplitude is the two-site coefficient of
`Λ U_i`. -/
theorem AppendixBStructuralData.twoSiteAmplitude_eq_coreTensor_mpv {A : MPSTensor d D}
    (hStruct : AppendixBStructuralData A) (σ : Cfg d 2) :
    hStruct.twoSiteAmplitude σ = mpv hStruct.coreTensor σ := by
  rw [hStruct.twoSiteAmplitude_eq_mpv σ, hStruct.mpv_eq_coreTensor σ]

/-- The length-two case of the requested even-chain factorization is automatic
from the definition of the structural two-site amplitude. -/
theorem AppendixBStructuralData.mpv_eq_productPairState_one {A : MPSTensor d D}
    (hStruct : AppendixBStructuralData A) (σ : Cfg d (2 * 1)) :
    mpv A σ = productPairState hStruct.twoSiteAmplitude 1 σ := by
  rw [productPairState_one, hStruct.twoSiteAmplitude_eq_mpv]

/-- The remaining chain-space extraction needed after Appendix B.

For a fixed structural witness, this records the two facts that are still not
produced internally by `rfp_nt_structural_full`: the even-chain MPV must be a
repeated copy of the two-site amplitude determined by that same witness, and the
nearest-neighbor parent projectors on each finite chain must be identified with a
commuting product-pair family. -/
structure AppendixBProductPairExtraction {A : MPSTensor d D}
    (hStruct : AppendixBStructuralData A) where
  /-- Even-chain coefficient factorization through the structural two-site amplitude. -/
  hmpv : ∀ N (σ : Cfg d (2 * N)),
    mpv A σ = productPairState hStruct.twoSiteAmplitude N σ
  /-- Local product-pair projectors realizing the nearest-neighbor parent terms. -/
  localProjectors : ∀ N, HasProductPairLocalProjectors A N

/-- Construct the MPV part of the extraction after removing the Appendix B gauge.

This reduces the coefficient bookkeeping to the core tensor `Λ U_i`; the local
projector data remains a separate chain-space input. -/
noncomputable def AppendixBProductPairExtraction.ofCoreTensorFactorization
    {A : MPSTensor d D} {hStruct : AppendixBStructuralData A}
    (hCore : ∀ N (σ : Cfg d (2 * N)),
      mpv hStruct.coreTensor σ = productPairState hStruct.twoSiteAmplitude N σ)
    (hProj : ∀ N, HasProductPairLocalProjectors A N) :
    AppendixBProductPairExtraction hStruct where
  hmpv := by
    intro N σ
    rw [hStruct.mpv_eq_coreTensor σ]
    exact hCore N σ
  localProjectors := hProj

/-- Chain-space extraction data yields the established `ProductPairBridge` witness. -/
noncomputable def AppendixBProductPairExtraction.toProductPairBridge
    {A : MPSTensor d D} {hStruct : AppendixBStructuralData A}
    (hExtract : AppendixBProductPairExtraction hStruct) :
    ProductPairBridge A where
  pairAmplitude := hStruct.twoSiteAmplitude
  hmpv := hExtract.hmpv
  localProjectors := hExtract.localProjectors

/-- Chain-space extraction data gives the unfolded nearest-neighbor commutation
statement on every finite chain. -/
theorem AppendixBProductPairExtraction.commuting_twoSite_localTerms
    {A : MPSTensor d D} {hStruct : AppendixBStructuralData A}
    (hExtract : AppendixBProductPairExtraction hStruct) (N : ℕ) :
    ∀ i j : Fin N,
      localTerm A 2 N i * localTerm A 2 N j =
        localTerm A 2 N j * localTerm A 2 N i :=
  hExtract.toProductPairBridge.commuting_twoSite_localTerms N

/-- Conditional internal replacement for the forward Theorem 3.10 route:
RFP plus the proved Appendix B structural theorem implies the unfolded NNCPH
commutation statement as soon as the remaining chain-space product-pair
extraction is supplied for the resulting structural witness.

This theorem deliberately stops short of claiming the full Beigi-independent
`rfp_implies_nncph`: the missing input is exactly
`AppendixBProductPairExtraction` for the structural data produced by
`AppendixBStructuralData.ofRFP`. -/
theorem commuting_twoSite_localTerms_of_rfp_of_appendixBExtraction
    (A : MPSTensor d D) [NeZero D]
    (hNT : IsNormal A) (hRFP : IsRFP A)
    (hLeft : ∑ i : Fin d, (A i)ᴴ * A i = 1)
    (hExtract : AppendixBProductPairExtraction
      (AppendixBStructuralData.ofRFP A hNT hRFP hLeft))
    (N : ℕ) :
    ∀ i j : Fin N,
      localTerm A 2 N i * localTerm A 2 N j =
        localTerm A 2 N j * localTerm A 2 N i :=
  hExtract.commuting_twoSite_localTerms N

end MPSTensor
