/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.RFP.Defs
import TNLean.MPS.Core.CPPrimitive
import TNLean.MPS.BNT.Construction
import TNLean.MPS.Irreducible.FormII
import TNLean.Spectral.QuantitativeGap

/-!
# Structural form of RFP tensors

This file states the structural characterisation theorems for MPS tensors
that are renormalization fixed points, following arXiv:1606.00608 §3.4
(Cirac–Pérez-García–Schuch–Verstraete) and Appendix B.

## Main results

* `rfp_nt_structural`: formalized structural precursor — a **nonzero** normal RFP tensor is
  already injective
* `rfp_nt_structural_of_leftCanonical`: left-canonical normal RFP tensors are injective
  without a separate nonzero hypothesis
* `rfp_nt_cfii_diagonal_fixedPoint`: Appendix B / CFII reduction step — after unitary
  conjugation, a left-canonical normal RFP tensor has a diagonal positive-definite fixed point
* `rfp_cf_structural`: each canonical-form block is injective
* `rfp_bnt_structural`: each BNT block is injective

## Proof strategy

The full Appendix B decomposition `A i = X * Λ * U i * X⁻¹` is stated in
`TNLean.Archive.RFPStructuralFull` with a deferred proof (tracked by issue #233).
What *is* formalized here is the span-collapse step:
`E² = E` implies every nonempty blocked word lies in the one-site Kraus span, so a nonzero normal
RFP tensor is automatically injective.
-/

open scoped Matrix ComplexOrder

namespace MPSTensor

variable {d D : ℕ}

local notation "Mat" => Matrix (Fin D) (Fin D) ℂ

/-- For an RFP tensor, every nonempty word evaluates into the one-site Kraus span.

This is the algebraic consequence of `E² = E`: the product family `{AᵢAⱼ}` is already a linear
combination of `{Aₖ}`, and a strong induction on the word length propagates this to all nonempty
words. -/
private theorem evalWord_mem_span_of_isRFP
    (A : MPSTensor d D) (hRFP : IsRFP A) :
    ∀ w : List (Fin d), w ≠ [] →
      evalWord A w ∈ Submodule.span ℂ (Set.range A) := by
  obtain ⟨V, _, hprod⟩ := (isRFP_iff_kraus_isometry A).1 hRFP
  have hmain :
      ∀ n : ℕ, ∀ w : List (Fin d), w.length = n → w ≠ [] →
        evalWord A w ∈ Submodule.span ℂ (Set.range A) := by
    intro n
    refine Nat.strong_induction_on n ?_
    intro n ih w hlen hne
    cases w with
    | nil =>
        contradiction
    | cons i w =>
        cases w with
        | nil =>
            exact Submodule.subset_span ⟨i, by simp [evalWord]⟩
        | cons j w =>
            have hword :
                evalWord A (i :: j :: w) = ∑ k : Fin d, V (i, j) k • evalWord A (k :: w) := by
              calc
                evalWord A (i :: j :: w) = (A i * A j) * evalWord A w := by
                  simp [evalWord, Matrix.mul_assoc]
                _ = (∑ k : Fin d, V (i, j) k • A k) * evalWord A w := by
                  rw [hprod]
                _ = ∑ k : Fin d, V (i, j) k • evalWord A (k :: w) := by
                  simp [evalWord, Finset.sum_mul]
            rw [hword]
            simpa using
              (Submodule.sum_mem (Submodule.span ℂ (Set.range A))
                (t := Finset.univ)
                (f := fun k : Fin d => V (i, j) k • evalWord A (k :: w))
                (by
                  intro k hk
                  refine Submodule.smul_mem _ _ ?_
                  have hk_lt : (k :: w).length < n := by
                    have hlen' : w.length + 2 = n := by
                      simpa using hlen
                    simpa [hlen'] using Nat.lt_succ_self (w.length + 1)
                  exact ih (k :: w).length hk_lt (k :: w) rfl (by simp)))
  intro w hne
  exact hmain w.length w rfl hne

/-- Formalized structural precursor to Appendix B:
a **nonzero** normal RFP tensor is already injective.

The proof uses the RFP span-collapse lemma above: once every nonempty blocked word lies in the
one-site Kraus span, any positive-length block-injectivity witness immediately upgrades to
single-site injectivity. The remaining `N = 0` case can only happen in the one-dimensional
matrix algebra generated by `1`; there, any nonzero Kraus operator already spans the algebra. -/
theorem rfp_nt_structural (A : MPSTensor d D)
    (hNT : IsNormal A) (hRFP : IsRFP A) (hA : ∃ i, A i ≠ 0) :
    IsInjective A := by
  rcases hNT with ⟨N, hNinj⟩
  rw [IsInjective]
  by_cases hN0 : N = 0
  · have hrange0 :
        (Set.range fun σ : Fin 0 → Fin d => evalWord A (List.ofFn σ)) =
          ({(1 : Mat)} : Set Mat) := by
      ext M
      constructor
      · rintro ⟨σ, rfl⟩
        simp only [List.ofFn_zero, evalWord_nil, Set.mem_singleton_iff]
      · intro hM
        rcases Set.mem_singleton_iff.mp hM with rfl
        refine ⟨fun i => Fin.elim0 i, ?_⟩
        simp only [List.ofFn_zero, evalWord_nil]
    have hspan1 : Submodule.span ℂ ({(1 : Mat)} : Set Mat) = (⊤ : Submodule ℂ Mat) := by
      unfold IsNBlkInjective at hNinj
      rw [hN0] at hNinj
      simpa [hrange0] using hNinj
    obtain ⟨i, hi⟩ := hA
    have hAi_span1 : A i ∈ Submodule.span ℂ ({(1 : Mat)} : Set Mat) := by
      rw [hspan1]
      simp only [Submodule.mem_top]
    rw [Submodule.mem_span_singleton] at hAi_span1
    obtain ⟨c, hc⟩ := hAi_span1
    have hc_ne : c ≠ 0 := by
      intro hc0
      apply hi
      simpa [hc0] using hc.symm
    have hAi_mem : c • (1 : Mat) ∈ Submodule.span ℂ (Set.range A) := by
      simpa [hc] using
        (Submodule.subset_span (by exact (show A i ∈ Set.range A from ⟨i, rfl⟩)))
    have hone : (1 : Mat) ∈ Submodule.span ℂ (Set.range A) := by
      simpa [smul_smul, hc_ne] using
        (Submodule.smul_mem (Submodule.span ℂ (Set.range A)) c⁻¹ hAi_mem)
    have htop_le : (⊤ : Submodule ℂ Mat) ≤ Submodule.span ℂ (Set.range A) := by
      rw [← hspan1]
      exact Submodule.span_le.2 (by
        intro M hM
        rcases Set.mem_singleton_iff.mp hM with rfl
        exact hone)
    exact le_antisymm le_top htop_le
  · have htop_le : (⊤ : Submodule ℂ Mat) ≤ Submodule.span ℂ (Set.range A) := by
      unfold IsNBlkInjective at hNinj
      rw [← hNinj]
      refine Submodule.span_le.2 ?_
      intro M hM
      rcases hM with ⟨σ, rfl⟩
      have hσ_ne : List.ofFn σ ≠ [] := by
        intro hnil
        have hlenσ : (List.ofFn σ).length = N := List.length_ofFn
        have hlen_nil : (List.ofFn σ).length = 0 := by
          simpa using congrArg List.length hnil
        have : N = 0 := by rw [← hlenσ, hlen_nil]
        exact hN0 this
      change evalWord A (List.ofFn σ) ∈ Submodule.span ℂ (Set.range A)
      exact evalWord_mem_span_of_isRFP A hRFP (List.ofFn σ) hσ_ne
    exact le_antisymm le_top htop_le

/-- A left-canonical tensor has a nonzero Kraus operator as soon as `D ≠ 0`. -/
private theorem exists_nonzero_of_leftCanonical [DecidableEq (Fin D)] [NeZero D]
    (A : MPSTensor d D)
    (hLeft : ∑ i : Fin d, (A i)ᴴ * A i = 1) :
    ∃ i, A i ≠ 0 := by
  by_contra hA
  push Not at hA
  have hsum : ∑ i : Fin d, (A i)ᴴ * A i = 0 := by
    simp [hA]
  have h1 : (1 : Mat) = 0 := by
    rw [hLeft] at hsum
    exact hsum
  exact (one_ne_zero : (1 : Mat) ≠ 0) h1

/-- Appendix B precursor without a separate nonzero side condition:
for a left-canonical normal RFP tensor, the one-site Kraus span is already all of `M_D(ℂ)`. -/
theorem rfp_nt_structural_of_leftCanonical [DecidableEq (Fin D)] [NeZero D]
    (A : MPSTensor d D)
    (hNT : IsNormal A) (hRFP : IsRFP A)
    (hLeft : ∑ i : Fin d, (A i)ᴴ * A i = 1) :
    IsInjective A :=
  rfp_nt_structural A hNT hRFP (exists_nonzero_of_leftCanonical A hLeft)

/-- Appendix B / CFII reduction step:
after unitary conjugation, a left-canonical normal RFP tensor has a diagonal
positive-definite fixed point for its transfer map. -/
theorem rfp_nt_cfii_diagonal_fixedPoint [DecidableEq (Fin D)] [NeZero D]
    (A : MPSTensor d D)
    (hNT : IsNormal A) (hRFP : IsRFP A)
    (hLeft : ∑ i : Fin d, (A i)ᴴ * A i = 1) :
    ∃ (U : Matrix.unitaryGroup (Fin D) ℂ)
      (Λ : Matrix (Fin D) (Fin D) ℂ),
        Λ.PosDef ∧ Λ.IsDiag ∧
        (∑ i : Fin d, ((↑U : Matrix _ _ ℂ)ᴴ * A i * (↑U : Matrix _ _ ℂ))ᴴ
                      * ((↑U : Matrix _ _ ℂ)ᴴ * A i * (↑U : Matrix _ _ ℂ)) = 1) ∧
        transferMap (d := d) (D := D)
          (fun i => (↑U : Matrix _ _ ℂ)ᴴ * A i * (↑U : Matrix _ _ ℂ)) Λ = Λ := by
  have hInj : IsInjective A := rfp_nt_structural_of_leftCanonical A hNT hRFP hLeft
  have hIrrMap : IsIrreducibleMap (transferMap (d := d) (D := D) A) :=
    injective_implies_irreducibleCP A hInj
  have hIrrTensor : IsIrreducibleTensor (d := d) (D := D) A :=
    isIrreducibleTensor_of_isIrreducibleMap A hIrrMap
  have hD : 0 < D := Nat.pos_of_ne_zero (NeZero.ne D)
  exact exists_unitary_diag_posDef_fixedPoint_of_leftCanonical_of_isIrreducibleTensor
    (d := d) (D := D) A hLeft hIrrTensor hD

/-- **Rank-one classification** (arXiv:1606.00608, Appendix B): for an injective
left-canonical RFP tensor, the transfer map equals the rank-one fixed-point projection
`X ↦ (tr X / tr ρ) • ρ`.

The proof combines exponential convergence (`E^n → P`) with idempotence (`E^n = E`
for `n ≥ 1`). Since `E` is both the limit and is equal to every iterate, `E = P`. -/
theorem transferMap_eq_fixedPointProj_of_isRFP_injective [NeZero D]
    (A : MPSTensor d D)
    (hInj : IsInjective A) (hRFP : IsRFP A)
    (hLeft : ∑ i : Fin d, (A i)ᴴ * A i = 1)
    (ρ : Matrix (Fin D) (Fin D) ℂ) (hρ_pd : ρ.PosDef)
    (hρ_fix : transferMap A ρ = ρ) :
    transferMap A = fixedPointProj ρ (ne_of_gt hρ_pd.trace_pos) := by
  obtain ⟨C, δ, hC, hδ, hδ1, hbound⟩ :=
    exponential_convergence_of_primitive A hLeft hInj ρ hρ_pd hρ_fix
  have hIdem : IsIdempotentElem (transferMap (d := d) (D := D) A) := hRFP
  set E := transferMap (d := d) (D := D) A
  set P := fixedPointProj ρ (ne_of_gt hρ_pd.trace_pos)
  apply LinearMap.ext; intro X
  -- For all n: E^[n+1] X = E X (idempotence), so ‖E X - P X‖ ≤ C(1-δ)^{n+1} ‖X‖
  have h_bound_const : ∀ n : ℕ, ‖E X - P X‖ ≤
      C * (1 - δ) ^ (n + 1) * ‖X‖ := by
    intro n
    have h_iter : E^[n + 1] X = E X := by
      rw [← Module.End.pow_apply]; congr 1; exact hIdem.pow_succ_eq n
    rw [← h_iter]; exact hbound (n + 1) X
  -- C(1-δ)^{n+1} ‖X‖ → 0
  have h_rate : Filter.Tendsto (fun n => C * (1 - δ) ^ (n + 1) * ‖X‖)
      Filter.atTop (nhds 0) := by
    have h_base := tendsto_pow_atTop_nhds_zero_of_lt_one
      (show (0 : ℝ) ≤ 1 - δ by linarith) (show 1 - δ < 1 by linarith)
    -- (1-δ)^(n+1) = (1-δ) * (1-δ)^n → (1-δ) * 0 = 0
    have h_shift : Filter.Tendsto (fun n => (1 - δ) ^ (n + 1)) Filter.atTop (nhds 0) := by
      have := h_base.const_mul (1 - δ)
      simp only [mul_zero] at this
      exact this.congr fun n => by ring
    have h_mul := h_shift.const_mul (C * ‖X‖)
    simp only [mul_zero] at h_mul
    exact h_mul.congr fun n => by ring
  -- Constant sequence E X - P X → 0 by squeeze, so E X - P X = 0
  have h_tend : Filter.Tendsto (fun _ : ℕ => E X - P X) Filter.atTop (nhds 0) :=
    squeeze_zero_norm h_bound_const h_rate
  exact eq_of_sub_eq_zero (tendsto_nhds_unique tendsto_const_nhds h_tend)

/-- Canonical-form blocks are already injective, so the structural precursor above is automatic. -/
theorem rfp_cf_structural {r : ℕ} {dim : Fin r → ℕ}
    (μ : Fin r → ℂ) (A : (k : Fin r) → MPSTensor d (dim k))
    (hCF : IsCanonicalForm μ A) :
    ∀ k, IsInjective (A k) :=
  hCF.block_injective

/-- BNT blocks are already injective, so the same precursor applies blockwise. -/
theorem rfp_bnt_structural {r : ℕ} {dim : Fin r → ℕ}
    (μ : Fin r → ℂ) (A : (k : Fin r) → MPSTensor d (dim k))
    (hCF : IsCanonicalFormBNT μ A) :
    ∀ k, IsInjective (A k) :=
  hCF.toIsCanonicalForm.block_injective

end MPSTensor
