/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.
-- Import architecture: docs/import_structure.md.
-- Generated aggregator module: TNLean.Circuit

import TNLean.Circuit.ArbitrarySiteGateEmbedding
import TNLean.Circuit.Channel
import TNLean.Circuit.CleanImplementationPlacement
import TNLean.Circuit.CleanUnitaryImplementation
import TNLean.Circuit.CoherentEncoder
import TNLean.Circuit.Composition
import TNLean.Circuit.ConfigurationLayers
import TNLean.Circuit.EmbeddedProduct
import TNLean.Circuit.ExactAmplificationBudget
import TNLean.Circuit.ExactSubspaceAmplification
import TNLean.Circuit.ExpectationBounds
import TNLean.Circuit.GHZState
import TNLean.Circuit.Gates
import TNLean.Circuit.ImageReflectionCircuit
import TNLean.Circuit.InitializedRegisterProjection
import TNLean.Circuit.LiebRobinson
import TNLean.Circuit.LocalCircuit
import TNLean.Circuit.Measurement
import TNLean.Circuit.PairProduct
import TNLean.Circuit.PairProductPowers
import TNLean.Circuit.PartialIsometryDilation
import TNLean.Circuit.ProductStateCircuit
import TNLean.Circuit.ProductVector
import TNLean.Circuit.QuantitativeSitePermutation
import TNLean.Circuit.QuantitativeUnitaryGates
import TNLean.Circuit.RingSeparation
import TNLean.Circuit.SelectedZeroRegisterReflection
import TNLean.Circuit.SelectedZeroRegisterReflectionPool
import TNLean.Circuit.SelectedZeroRegisterSupport
import TNLean.Circuit.SiteEmbedding
import TNLean.Circuit.SiteExpectation
import TNLean.Circuit.SiteExpectationOrder
import TNLean.Circuit.SupportedMatrixElements
import TNLean.Circuit.Teleportation
import TNLean.Circuit.UniformPostselection
import TNLean.Circuit.UniformSuccessAttenuation
import TNLean.Circuit.WeightedGHZ
import TNLean.Circuit.WindowProduct
import TNLean.Circuit.ZeroRegisterConjunction
import TNLean.Circuit.ZeroRegisterReflection
