/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.
-- Import architecture: docs/import_structure.md.
-- Generated aggregator module: TNLean.QCA

import TNLean.QCA.AlgebraicBlocking
import TNLean.QCA.AlgebraicTranslation
import TNLean.QCA.BipartiteLocalAlgebra
import TNLean.QCA.BipartiteSupportAlgebra
import TNLean.QCA.Blocking
import TNLean.QCA.BlockingQCA
import TNLean.QCA.BlockingTranslation
import TNLean.QCA.CompatibleLocalAutomorphism
import TNLean.QCA.DisjointSupport
import TNLean.QCA.FiniteLocalRestriction
import TNLean.QCA.FinitePropagation
import TNLean.QCA.InversePropagation
import TNLean.QCA.IsQCA
import TNLean.QCA.LocalAlgebra
import TNLean.QCA.LocalLimit
import TNLean.QCA.LocalNorm
import TNLean.QCA.NearestNeighborBlocking
import TNLean.QCA.OverlappingSupportAlgebra
import TNLean.QCA.QuasiLocal
import TNLean.QCA.QuasiLocalBlocking
import TNLean.QCA.QuasiLocalCommutant
import TNLean.QCA.QuasiLocalTranslation
import TNLean.QCA.RegionSumset
import TNLean.QCA.RelativeCommutant
import TNLean.QCA.SiteIndexedSupportAlgebra
import TNLean.QCA.SupportAlgebraCommutation
import TNLean.QCA.Translation
import TNLean.QCA.TranslationCovariance
