/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.
-- Import architecture: docs/import_structure.md.
-- Generated aggregator module: TNLean.Spectral

import TNLean.Spectral.CrossCorrelation
import TNLean.Spectral.FrobeniusNorm
import TNLean.Spectral.GaugeConstruction
import TNLean.Spectral.MPVOverlapDecay
import TNLean.Spectral.MPVOverlapDecayRect
import TNLean.Spectral.MPVOverlapTrace
import TNLean.Spectral.MixedTransfer
import TNLean.Spectral.PrimitiveOverlap
import TNLean.Spectral.QuantitativeGap
import TNLean.Spectral.Radius
import TNLean.Spectral.TraceExpansion
import TNLean.Spectral.TransferOperatorGap
import TNLean.Spectral.TransferOperatorGapCommon
import TNLean.Spectral.TransferOperatorGapInjective
import TNLean.Spectral.TransferOperatorGapNT
import TNLean.Spectral.TransferOperatorGapNormalized
import TNLean.Spectral.TransferOperatorGapRect
import TNLean.Spectral.TransferOperatorGapRectNormalized
