/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import TNLean.MPS.FundamentalTheorem.Reduction.CompressionPeriodic
import TNLean.MPS.Examples.Fibonacci.Fibonacci
import TNLean.MPS.Examples.Rings.GoldenCompression

/-!
# Fibonacci action: the regular representation on two normal states

**Source.** Garre-Rubio, Lootens and Molnár 2023 (arXiv:2203.12563), Section `sec:inter`,
`Papers/2203.12563/REsubmission.tex` lines 459–460: a matrix product operator symmetry acts on the
blocks `A_x` of a symmetric matrix product state through action tensors, with nonnegative integer
multiplicities `M_{a,x}^y`; lines 564–568: these multiplicities satisfy
`∑_c N_{ab}^c M_{c,x}^y = ∑_z M_{a,z}^y M_{b,x}^z` and `O_a ψ_{A_x} = ∑_y M_{a,x}^y ψ_{A_y}`;
Section `sec:examples`, lines 1991–1993: for the Fibonacci matrix product operator of
arXiv:1511.08090 the only invariant family of normal states consists of two blocks `x_1, x_τ` with
`τ · x_1 = x_τ` and `τ · x_τ = x_1 + x_τ`. The operator tensor is that of Bultinck et al.
(arXiv:1511.08090), Appendix D.1.1, `References/1511.08090/AnyonsPEPS.tex` lines 1240–1269. The
source prints no explicit pair of states; the two tensors below are a construction of this
development.

**Formalized here.** An explicit realisation of the source's two-block solution. The first state
is the all-`τ` product state `|τ ⋯ τ⟩`, generated by the bond-one tensor `A` with `A^1 = 0` and
`A^τ = 1`. The second is its image `O_τ |τ ⋯ τ⟩`, generated by the bond-two tensor `C` with
`C^1 = [[0, σ], [0, 0]]` and `C^τ = [[0, 0], [1, -φ⁻¹]]`, normal at word length three. The three
action tensors `1 · A`, `τ · A` and `τ · C` compress, in exact arithmetic over `ℤ[σ]`, onto `A`,
onto `C`, and onto the pair `A ⊕ C`: on the pair of periodic states this is
`O_1 ψ_A = ψ_A`, `O_τ ψ_A = ψ_C`, `O_τ ψ_C = ψ_A + ψ_C`, the source's action
`τ · x_1 = x_τ`, `τ · x_τ = x_1 + x_τ`, with multiplicity matrix the regular representation
`N_τ = [[0, 1], [1, 1]]` of the Fibonacci fusion rules. Every gauge and its inverse have entries
in `ℤ[σ]`, and the conjugated letters are block diagonal, so every extension splits.

**Local fix (provenance):** the operator blocks `O_1`, `O_τ` are those of
`Examples/Fibonacci.lean`, whose entries the source does not print; documented in
`docs/paper-gaps/bmwshv17_fibonacci_block_entries_provenance.tex`.

## Main definitions

* `FibonacciCompression.fibAllTau`, `FibonacciCompression.fibChain`: the two normal tensors.
* `FibonacciCompression.fibUnitAllTau`, `FibonacciCompression.fibActAllTau`,
  `FibonacciCompression.fibActChain`: the three action tensors.
* `FibonacciCompression.fibNimTargets`: the pair `A ⊕ C` as a family of target blocks.
* `FibonacciCompression.fibUnitAllTau_compression`,
  `FibonacciCompression.fibActAllTau_compression`,
  `FibonacciCompression.fibActChain_compression`: the three compression data.

## Main results

* `FibonacciCompression.fibAllTau_isNormal`, `FibonacciCompression.fibChain_isNormal`: both
  states are normal.
* `FibonacciCompression.mpo_fibOne_mulVec_allTau`,
  `FibonacciCompression.mpo_fibTau_mulVec_allTau`,
  `FibonacciCompression.mpo_fibTau_mulVec_chain`: the action of the periodic operators on the
  periodic states at every positive system size.

## References

- [arXiv:2203.12563](https://arxiv.org/abs/2203.12563) -- J. Garre-Rubio, L. Lootens,
  A. Molnár, *Classifying phases protected by matrix product operator symmetries using matrix
  product states*
- [arXiv:1511.08090](https://arxiv.org/abs/1511.08090) -- N. Bultinck, M. Mariën,
  D. J. Williamson, M. B. Sahinoglu, J. Haegeman, F. Verstraete, *Anyons and matrix product
  operator algebras*

## Provenance

The two states, the three compression data and their exact-arithmetic verification were first
recorded in `Notes/OpenProblemsTN/checks/asym_fibonacci_categorical_data.md`, §4, and
`Notes/OpenProblemsTN/checks/asym_fibonacci_categorical_verify.py`, as instances of the
multi-block asymmetric compression theorem (P5 note,
`Notes/OpenProblemsTN/problems/p5_asymmetric_fundamental_theorem.tex`, Theorem 7.7,
`thm:p5-asymmetric-compression`). These are verification records, not the source.
-/

noncomputable section

open scoped Matrix

namespace FibonacciCompression

open GoldenInt MPSTensor

/-! ### The two normal states -/

/-- The golden matrices of the all-`τ` product state: `A^1 = 0`, `A^τ = 1` (data file §4.1). -/
def fibAllTauGolden : Fin 2 → Matrix (Fin 1) (Fin 1) GoldenInt
  | 0 => 0
  | 1 => 1

/-- The bond-one tensor of the all-`τ` product state `|τ ⋯ τ⟩` (data file §4.1). -/
def fibAllTau : MPSTensor 2 1 := fun i => complexOfGolden (fibAllTauGolden i)

theorem fibAllTau_eq (i : Fin 2) : fibAllTau i = complexOfGolden (fibAllTauGolden i) := rfl

/-- The one-site matrices of the all-`τ` product state: zero at the trivial label, one at `τ`
(data file §4.1). -/
theorem fibAllTau_apply : fibAllTau 0 = 0 ∧ fibAllTau 1 = 1 :=
  ⟨complexOfGolden_zero, complexOfGolden_one⟩

/-- **The all-`τ` product state is normal**: its single nonzero letter is the identity of the
one-by-one matrix algebra (data file §4.1). -/
theorem fibAllTau_isNormal : Kraus.IsNormal fibAllTau :=
  isNormal_of_complexOfRing_single goldenToComplex fibAllTauGolden fibAllTau_eq
    Nat.one_pos (κ := Unit)
    (fun _ _ _ => ![1]) (fun _ _ _ => 1) (by decide +kernel)

/-- The golden matrices of the bond-two tensor `C` generating `O_τ |τ ⋯ τ⟩`:
`C^1 = [[0, σ], [0, 0]]` and `C^τ = [[0, 0], [1, -φ⁻¹]]` (data file §4.1). -/
def fibChainGolden : Fin 2 → Matrix (Fin 2) (Fin 2) GoldenInt
  | 0 =>
    !![⟨0, 0, 0, 0⟩, ⟨0, 1, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]
  | 1 =>
    !![⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨1, 0, 0, 0⟩, ⟨0, 0, -1, 0⟩]

/-- The bond-two tensor `C` generating the state `O_τ |τ ⋯ τ⟩` (data file §4.1). -/
def fibChain : MPSTensor 2 2 := fun i => complexOfGolden (fibChainGolden i)

theorem fibChain_eq (i : Fin 2) : fibChain i = complexOfGolden (fibChainGolden i) := rfl

/-- The four length-three words of `C` spanning the two-by-two matrix algebra (data file
§4.1): `C^1 C^τ C^1 = σ² E₀₁`, `C^1 C^τ C^τ = -σ³ E₀₀ + σ⁵ E₀₁`, `C^τ C^1 C^τ = σ C^τ` and
`C^τ C^τ C^1 = -σ³ E₁₁`. -/
def fibChainWord : Fin 4 → Fin 3 → Fin 2
  | 0 => ![0, 1, 0]
  | 1 => ![0, 1, 1]
  | 2 => ![1, 0, 1]
  | 3 => ![1, 1, 0]

/-- The coefficients expressing the matrix unit `E_{ij}` of `C` as a combination of the four
words of `fibChainWord`. -/
def fibChainUnitCoeff : Fin 2 → Fin 2 → Fin 4 → GoldenInt
  | 0, 0 => ![1, ⟨0, -2, 0, -1⟩, 0, 0]
  | 0, 1 => ![⟨1, 0, 1, 0⟩, 0, 0, 0]
  | 1, 0 => ![0, 0, ⟨0, 1, 0, 1⟩, ⟨0, -1, 0, -1⟩]
  | 1, 1 => ![0, 0, 0, ⟨0, -2, 0, -1⟩]

/-- **The tensor `C` is normal**: its length-three words span the full two-by-two matrix
algebra (data file §4.1). -/
theorem fibChain_isNormal : Kraus.IsNormal fibChain :=
  isNormal_of_complexOfRing_single goldenToComplex fibChainGolden fibChain_eq
    (by norm_num : 0 < 3)
    (fun _ _ k => fibChainWord k) fibChainUnitCoeff (by decide +kernel)

/-! ### The unit acting on the all-`τ` state -/

/-- The action tensor `fibOne · fibAllTau`, of bond dimension 2 (data file §4.2). -/
def fibUnitAllTau : MPSTensor 2 2 := MPOTensor.actTensor fibOne fibAllTau

/-- The golden matrices of the action tensor `fibOne · fibAllTau`, in the bond order of
`finProdFinEquiv` (data file §4.2). -/
def fibUnitAllTauGolden : Fin 2 → Matrix (Fin 2) (Fin 2) GoldenInt
  | 0 =>
    !![⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]
  | 1 =>
    !![⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨1, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩]

theorem fibUnitAllTau_eq (i : Fin 2) :
    fibUnitAllTau i = complexOfGolden (fibUnitAllTauGolden i) := by
  have h : fibUnitAllTau i = complexOfGolden (actTensorR fibOneGolden fibAllTauGolden i) :=
    actTensor_complexOfRing _ fibOneGolden fibAllTauGolden i
  have hgolden : ∀ j : Fin 2,
      actTensorR fibOneGolden fibAllTauGolden j = fibUnitAllTauGolden j := by
    decide +kernel
  rw [h, hgolden]

/-- The inverse change of bond coordinates of `fibOne · fibAllTau`: its first 1 columns are
the sitewise right intertwiner onto the target, the last column spans the joint kernel of the
letters (data file §4.2). -/
def fibUnitAllTauGaugeInvGolden : Matrix (Fin 2) (Fin 2) GoldenInt :=
  !![⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩;
     ⟨1, 0, 0, 0⟩, ⟨-1, 0, 0, 0⟩]

/-- The change of bond coordinates of `fibOne · fibAllTau` (data file §4.2). -/
def fibUnitAllTauGaugeGolden : Matrix (Fin 2) (Fin 2) GoldenInt :=
  !![⟨1, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩;
     ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]

theorem fibUnitAllTauGauge_mul_inv :
    fibUnitAllTauGaugeGolden * fibUnitAllTauGaugeInvGolden = 1 := by
  decide +kernel

theorem fibUnitAllTauGaugeInv_mul :
    fibUnitAllTauGaugeInvGolden * fibUnitAllTauGaugeGolden = 1 := by
  decide +kernel

/-- The letters of `1 · A` in the block coordinates: the identity on the target coordinate and
zero on the zero slot (data file §4.2). -/
def fibUnitAllTauConjGolden : Fin 2 → Matrix (Fin 2) (Fin 2) GoldenInt
  | 0 => 0
  | 1 => !![1, 0; 0, 0]

/-- Every letter of `fibOne · fibAllTau` carries the adapted basis into itself block by block. -/
theorem fibUnitAllTau_mul_gaugeInv (i : Fin 2) :
    fibUnitAllTauGolden i * fibUnitAllTauGaugeInvGolden =
      fibUnitAllTauGaugeInvGolden * fibUnitAllTauConjGolden i := by
  revert i
  decide +kernel

private theorem fibUnitAllTau_matched (i : Fin 2) (p q : Fin 1) :
    fibUnitAllTauConjGolden i (unitCoord 1 1 ⟨Sum.inl oneSlotMem, p⟩)
      (unitCoord 1 1 ⟨Sum.inl oneSlotMem, q⟩) = fibAllTauGolden i p q := by
  revert i
  revert p q
  decide +kernel

private theorem fibUnitAllTau_unmatched (i : Fin 2) (t : Fin 1) (p q : Fin 1) :
    fibUnitAllTauConjGolden i (unitCoord 1 1 ⟨Sum.inr t, p⟩)
      (unitCoord 1 1 ⟨Sum.inr t, q⟩) = 0 := by
  revert i t p q
  decide +kernel

private theorem fibUnitAllTau_offDiagonal (i : Fin 2)
    (x y : BlockSpace (fun _ : Unit => 1) oneSlot 1) (h : x.1 ≠ y.1) :
    fibUnitAllTauConjGolden i (unitCoord 1 1 x) (unitCoord 1 1 y) = 0 := by
  revert i x y
  decide +kernel

/-- **The compression datum of `fibOne · fibAllTau`** (P5 note, Theorem 7.7, clauses (i)-(iii),
applied to an action tensor as in arXiv:2203.12563, equation `fusiontensors2`, lines 459–460;
data file §4.2): the action tensor compresses onto the single block `fibAllTau` with `z = 1`
zero slot. -/
def fibUnitAllTau_compression :
    MultiBlockCompression fibUnitAllTau oneSlot (fun _ : Unit => fibAllTau) :=
  MultiBlockCompression.ofGolden 1 (unitOrd 1) (unitCoord 1 1) fibUnitAllTauGolden
    fibUnitAllTau_eq (fun _ => fibAllTauGolden) (fun _ a => fibAllTau_eq a)
    fibUnitAllTauGaugeGolden fibUnitAllTauGaugeInvGolden fibUnitAllTauGauge_mul_inv
    fibUnitAllTauGaugeInv_mul fibUnitAllTauConjGolden fibUnitAllTau_mul_gaugeInv
    (fun i => MultiBlockCompression.triangular_of_offDiag (fibUnitAllTau_offDiagonal i))
    (fun i s _ p q => by cases s; exact fibUnitAllTau_matched i p q) fibUnitAllTau_unmatched

/-- **The remainder of the compression of `fibOne · fibAllTau` vanishes**: the extension splits
(data file §4.2). -/
theorem fibUnitAllTau_remainder_eq_zero (i : Fin 2) :
    fibUnitAllTau_compression.remainder i = 0 := by
  unfold fibUnitAllTau_compression
  exact MultiBlockCompression.remainder_ofRing fibUnitAllTau_offDiagonal i

/-- **The unit fixes the all-`τ` state**, `O_1 ψ_A = ψ_A`, at every positive system size (data
file §4.2). -/
theorem mpo_fibOne_mulVec_allTau (L : ℕ) (hL : 0 < L) :
    MPOTensor.mpo fibOne L *ᵥ (fun τ : Fin L → Fin 2 => mpv fibAllTau τ) =
      fun σ : Fin L → Fin 2 => mpv fibAllTau σ := by
  have h := MPOTensor.mpo_mulVec_mpv_eq_sum_of_multiBlockCompression fibUnitAllTau_compression
    L hL
  simpa only [Finset.sum_singleton] using h

/-! ### The `τ` family acting on the all-`τ` state -/

/-- The action tensor `fibTau · fibAllTau`, of bond dimension 3 (data file §4.3). -/
def fibActAllTau : MPSTensor 2 3 := MPOTensor.actTensor fibTau fibAllTau

/-- The golden matrices of the action tensor `fibTau · fibAllTau`, in the bond order of
`finProdFinEquiv` (data file §4.3). -/
def fibActAllTauGolden : Fin 2 → Matrix (Fin 3) (Fin 3) GoldenInt
  | 0 =>
    !![⟨0, 0, 0, 0⟩, ⟨0, 0, 1, 0⟩, ⟨0, 1, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]
  | 1 =>
    !![⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨1, 0, 0, 0⟩, ⟨0, 1, 0, 0⟩, ⟨0, 0, -1, 0⟩]

theorem fibActAllTau_eq (i : Fin 2) : fibActAllTau i = complexOfGolden (fibActAllTauGolden i) := by
  have h : fibActAllTau i = complexOfGolden (actTensorR fibTauGolden fibAllTauGolden i) :=
    actTensor_complexOfRing _ fibTauGolden fibAllTauGolden i
  have hgolden : ∀ j : Fin 2,
      actTensorR fibTauGolden fibAllTauGolden j = fibActAllTauGolden j := by
    decide +kernel
  rw [h, hgolden]

/-- The inverse change of bond coordinates of `fibTau · fibAllTau`: its first 2 columns are
the sitewise right intertwiner onto the target, the last column spans the joint kernel of the
letters (data file §4.3). -/
def fibActAllTauGaugeInvGolden : Matrix (Fin 3) (Fin 3) GoldenInt :=
  !![⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩;
     ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, -1, 0, 0⟩;
     ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 1, 0⟩]

/-- The change of bond coordinates of `fibTau · fibAllTau` (data file §4.3). -/
def fibActAllTauGaugeGolden : Matrix (Fin 3) (Fin 3) GoldenInt :=
  !![⟨1, 0, 0, 0⟩, ⟨0, 1, 0, 1⟩, ⟨0, 0, 0, 0⟩;
     ⟨0, 0, 0, 0⟩, ⟨0, 1, 0, 0⟩, ⟨1, 0, 0, 0⟩;
     ⟨0, 0, 0, 0⟩, ⟨0, -1, 0, -1⟩, ⟨0, 0, 0, 0⟩]

theorem fibActAllTauGauge_mul_inv : fibActAllTauGaugeGolden * fibActAllTauGaugeInvGolden = 1 := by
  decide +kernel

theorem fibActAllTauGaugeInv_mul : fibActAllTauGaugeInvGolden * fibActAllTauGaugeGolden = 1 := by
  decide +kernel

/-- The letters of `τ · A` in the block coordinates: the letters of `C` in the leading two-by-two
block and zero on the zero slot (data file §4.3). -/
def fibActAllTauConjGolden : Fin 2 → Matrix (Fin 3) (Fin 3) GoldenInt
  | 0 =>
    !![⟨0, 0, 0, 0⟩, ⟨0, 1, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]
  | 1 =>
    !![⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨1, 0, 0, 0⟩, ⟨0, 0, -1, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]

/-- Every letter of `fibTau · fibAllTau` carries the adapted basis into itself block by block. -/
theorem fibActAllTau_mul_gaugeInv (i : Fin 2) :
    fibActAllTauGolden i * fibActAllTauGaugeInvGolden =
      fibActAllTauGaugeInvGolden * fibActAllTauConjGolden i := by
  revert i
  decide +kernel

private theorem fibActAllTau_matched (i : Fin 2) (p q : Fin 2) :
    fibActAllTauConjGolden i (unitCoord 2 1 ⟨Sum.inl oneSlotMem, p⟩)
      (unitCoord 2 1 ⟨Sum.inl oneSlotMem, q⟩) = fibChainGolden i p q := by
  revert i
  revert p q
  decide +kernel

private theorem fibActAllTau_unmatched (i : Fin 2) (t : Fin 1) (p q : Fin 1) :
    fibActAllTauConjGolden i (unitCoord 2 1 ⟨Sum.inr t, p⟩)
      (unitCoord 2 1 ⟨Sum.inr t, q⟩) = 0 := by
  revert i t p q
  decide +kernel

private theorem fibActAllTau_offDiagonal (i : Fin 2)
    (x y : BlockSpace (fun _ : Unit => 2) oneSlot 1) (h : x.1 ≠ y.1) :
    fibActAllTauConjGolden i (unitCoord 2 1 x) (unitCoord 2 1 y) = 0 := by
  revert i x y
  decide +kernel

/-- **The compression datum of `fibTau · fibAllTau`** (P5 note, Theorem 7.7, clauses (i)-(iii),
applied to an action tensor as in arXiv:2203.12563, equation `fusiontensors2`, lines 459–460;
data file §4.3): the action tensor compresses onto the single block `fibChain` with `z = 1`
zero slot. -/
def fibActAllTau_compression :
    MultiBlockCompression fibActAllTau oneSlot (fun _ : Unit => fibChain) :=
  MultiBlockCompression.ofGolden 1 (unitOrd 1) (unitCoord 2 1) fibActAllTauGolden
    fibActAllTau_eq (fun _ => fibChainGolden) (fun _ a => fibChain_eq a)
    fibActAllTauGaugeGolden fibActAllTauGaugeInvGolden fibActAllTauGauge_mul_inv
    fibActAllTauGaugeInv_mul fibActAllTauConjGolden fibActAllTau_mul_gaugeInv
    (fun i => MultiBlockCompression.triangular_of_offDiag (fibActAllTau_offDiagonal i))
    (fun i s _ p q => by cases s; exact fibActAllTau_matched i p q) fibActAllTau_unmatched

/-- **The remainder of the compression of `fibTau · fibAllTau` vanishes**: the extension splits
(data file §4.3). -/
theorem fibActAllTau_remainder_eq_zero (i : Fin 2) : fibActAllTau_compression.remainder i = 0 := by
  unfold fibActAllTau_compression
  exact MultiBlockCompression.remainder_ofRing fibActAllTau_offDiagonal i

/-- **The `τ` family carries the all-`τ` state to the state of `C`**, `O_τ ψ_A = ψ_C`, at every
positive system size (data file §4.3). -/
theorem mpo_fibTau_mulVec_allTau (L : ℕ) (hL : 0 < L) :
    MPOTensor.mpo fibTau L *ᵥ (fun τ : Fin L → Fin 2 => mpv fibAllTau τ) =
      fun σ : Fin L → Fin 2 => mpv fibChain σ := by
  have h := MPOTensor.mpo_mulVec_mpv_eq_sum_of_multiBlockCompression fibActAllTau_compression
    L hL
  simpa only [Finset.sum_singleton] using h

/-! ### The `τ` family acting on the state of `C` -/

/-- The action tensor `τ · C`, of bond dimension `6 = 3 · 2` (data file §4.4). -/
def fibActChain : MPSTensor 2 6 := MPOTensor.actTensor fibTau fibChain

/-- The golden matrices of the action tensor `τ · C`, in the bond order of `finProdFinEquiv`
(data file §4.4). -/
def fibActChainGolden : Fin 2 → Matrix (Fin 6) (Fin 6) GoldenInt
  | 0 =>
    !![⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1, 0⟩, ⟨-1, 0, 1, 0⟩, ⟨0, 1, 0, 0⟩, ⟨0, 0, 0, -1⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]
  | 1 =>
    !![⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 1, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 1, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨1, 0, 0, 0⟩, ⟨0, 0, -1, 0⟩, ⟨0, 1, 0, 0⟩, ⟨0, 0, 0, -1⟩, ⟨0, 0, -1, 0⟩, ⟨1, 0, -1, 0⟩]

theorem fibActChain_eq (i : Fin 2) : fibActChain i = complexOfGolden (fibActChainGolden i) := by
  have h : fibActChain i = complexOfGolden (actTensorR fibTauGolden fibChainGolden i) :=
    actTensor_complexOfRing _ fibTauGolden fibChainGolden i
  have hgolden : ∀ j : Fin 2,
      actTensorR fibTauGolden fibChainGolden j = fibActChainGolden j := by
    decide +kernel
  rw [h, hgolden]

/-- The bond dimensions of the two target slots of `τ · C`: one for `A`, two for `C`. -/
def fibNimDim : Fin 2 → ℕ
  | 0 => 1
  | 1 => 2

/-- The pair of normal states `A ⊕ C` as a family of target blocks, each with multiplicity one
and weight one (data file §4.4). -/
def fibNimTargets : (s : Fin 2) → MPSTensor 2 (fibNimDim s)
  | 0 => fibAllTau
  | 1 => fibChain

/-- The golden matrices of the two target blocks of `τ · C`. -/
def fibNimTargetsGolden :
    (s : Fin 2) → Fin 2 → Matrix (Fin (fibNimDim s)) (Fin (fibNimDim s)) GoldenInt
  | 0 => fibAllTauGolden
  | 1 => fibChainGolden

theorem fibNimTargets_eq (s : Fin 2) (i : Fin 2) :
    fibNimTargets s i = complexOfGolden (fibNimTargetsGolden s i) := by
  fin_cases s <;> rfl

/-- The slots of `τ · C`: both target blocks. -/
abbrev fibNimSlots : Finset (Fin 2) := Finset.univ

/-- The block ordering of `τ · C`: `A`, then `C`, then the three zero slots. -/
def fibNimOrd : BlockIndex fibNimSlots 3 ≃ Fin 5 where
  toFun := Sum.elim (fun s => ![0, 1] s.1) ![2, 3, 4]
  invFun
    | 0 => Sum.inl ⟨0, Finset.mem_univ 0⟩
    | 1 => Sum.inl ⟨1, Finset.mem_univ 1⟩
    | 2 => Sum.inr 0
    | 3 => Sum.inr 1
    | 4 => Sum.inr 2
  left_inv := by decide +kernel
  right_inv := by decide +kernel

/-- The position of the first bond coordinate of each block of `τ · C`. -/
def fibNimOffset : BlockIndex fibNimSlots 3 → ℕ :=
  Sum.elim (fun s => ![0, 1] s.1) ![3, 4, 5]

/-- The bond coordinate attached to a graded coordinate of `τ · C`. -/
def fibNimCoordNat (x : BlockSpace fibNimDim fibNimSlots 3) : ℕ := fibNimOffset x.1 + (x.2 : ℕ)

theorem fibNimCoordNat_lt (x : BlockSpace fibNimDim fibNimSlots 3) : fibNimCoordNat x < 6 := by
  revert x
  decide +kernel

/-- The labelling of the six bond coordinates of `τ · C` by the graded block space: `A` at the
coordinate `0`, `C` at the coordinates `1, 2`, and the zero slots at `3, 4, 5` (data file
§4.4). -/
def fibNimCoord : BlockSpace fibNimDim fibNimSlots 3 ≃ Fin 6 where
  toFun x := ⟨fibNimCoordNat x, fibNimCoordNat_lt x⟩
  invFun
    | 0 => ⟨Sum.inl ⟨0, Finset.mem_univ 0⟩, ⟨0, by decide⟩⟩
    | 1 => ⟨Sum.inl ⟨1, Finset.mem_univ 1⟩, ⟨0, by decide⟩⟩
    | 2 => ⟨Sum.inl ⟨1, Finset.mem_univ 1⟩, ⟨1, by decide⟩⟩
    | 3 => ⟨Sum.inr 0, ⟨0, by decide⟩⟩
    | 4 => ⟨Sum.inr 1, ⟨0, by decide⟩⟩
    | 5 => ⟨Sum.inr 2, ⟨0, by decide⟩⟩
  left_inv := by decide +kernel
  right_inv := by decide +kernel

/-- The inverse change of bond coordinates of `τ · C`: its first column is the sitewise right
intertwiner onto `A`, the next two columns the one onto `C`, and the last three columns span the
joint kernel of the letters (data file §4.4). -/
def fibActChainGaugeInvGolden : Matrix (Fin 6) (Fin 6) GoldenInt :=
  !![⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩;
     ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1, 0⟩;
     ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 1, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, -1, 0, 0⟩, ⟨0, 0, 0, -1⟩;
     ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 1, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
     ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1, 0⟩, ⟨0, 0, 0, 0⟩;
     ⟨0, 1, 0, 1⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, -1, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, -1, 0⟩]

/-- The change of bond coordinates of `τ · C` (data file §4.4). -/
def fibActChainGaugeGolden : Matrix (Fin 6) (Fin 6) GoldenInt :=
  !![⟨0, 0, 0, 1⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1, 0⟩, ⟨1, 0, -2, 0⟩, ⟨0, -1, 0, 1⟩, ⟨0, 0, 0, 1⟩;
     ⟨0, 0, -1, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
     ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 1, 0, 0⟩, ⟨0, 0, 0, -1⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, -1, 0⟩;
     ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
     ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 1, 0⟩, ⟨0, 0, 0, 0⟩;
     ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-1, 0, -1, 0⟩, ⟨0, 0, 0, 0⟩]

theorem fibActChainGauge_mul_inv : fibActChainGaugeGolden * fibActChainGaugeInvGolden = 1 := by
  decide +kernel

theorem fibActChainGaugeInv_mul : fibActChainGaugeInvGolden * fibActChainGaugeGolden = 1 := by
  decide +kernel

/-- The letters of `τ · C` in the block coordinates: block diagonal, with the letter of `A`, the
letter of `C` and three one-by-one zero blocks on the diagonal (data file §4.4). -/
def fibActChainConjGolden : Fin 2 → Matrix (Fin 6) (Fin 6) GoldenInt
  | 0 =>
    !![⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 1, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]
  | 1 =>
    !![⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, -1, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩;
       ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]

/-- Every letter of `τ · C` carries the adapted basis into itself block by block. -/
theorem fibActChain_mul_gaugeInv (i : Fin 2) :
    fibActChainGolden i * fibActChainGaugeInvGolden =
      fibActChainGaugeInvGolden * fibActChainConjGolden i := by
  revert i
  decide +kernel

private theorem fibActChain_matched (i : Fin 2) (s : Fin 2) (p q : Fin (fibNimDim s)) :
    fibActChainConjGolden i (fibNimCoord ⟨Sum.inl ⟨s, Finset.mem_univ s⟩, p⟩)
      (fibNimCoord ⟨Sum.inl ⟨s, Finset.mem_univ s⟩, q⟩) = fibNimTargetsGolden s i p q := by
  revert i
  fin_cases s <;> revert p q <;> decide +kernel

private theorem fibActChain_unmatched (i : Fin 2) (t : Fin 3) (p q : Fin 1) :
    fibActChainConjGolden i (fibNimCoord ⟨Sum.inr t, p⟩) (fibNimCoord ⟨Sum.inr t, q⟩) = 0 := by
  revert i t p q
  decide +kernel

private theorem fibActChain_offDiagonal (i : Fin 2) (x y : BlockSpace fibNimDim fibNimSlots 3)
    (h : x.1 ≠ y.1) : fibActChainConjGolden i (fibNimCoord x) (fibNimCoord y) = 0 := by
  revert i x y
  decide +kernel

/-- **The multi-block compression datum of `τ · C`** (P5 note, Theorem 7.7, clauses (i)-(iii),
applied to an action tensor as in arXiv:2203.12563, equation `fusiontensors2`, lines 459–460;
data file §4.4): the action tensor compresses onto the pair `A ⊕ C` with three zero slots. Its
block multiplicities `(1, 1)` are the `τ` row of the Fibonacci fusion matrix. -/
def fibActChain_compression : MultiBlockCompression fibActChain fibNimSlots fibNimTargets :=
  MultiBlockCompression.ofGolden 3 fibNimOrd fibNimCoord fibActChainGolden fibActChain_eq
    fibNimTargetsGolden fibNimTargets_eq fibActChainGaugeGolden fibActChainGaugeInvGolden
    fibActChainGauge_mul_inv fibActChainGaugeInv_mul fibActChainConjGolden
    fibActChain_mul_gaugeInv
    (fun i => MultiBlockCompression.triangular_of_offDiag (fibActChain_offDiagonal i))
    (fun i s _ p q => fibActChain_matched i s p q) fibActChain_unmatched

/-- **The remainder of the compression of `τ · C` vanishes**: the extension splits (data file
§4.4). -/
theorem fibActChain_remainder_eq_zero (i : Fin 2) : fibActChain_compression.remainder i = 0 := by
  unfold fibActChain_compression
  exact MultiBlockCompression.remainder_ofRing fibActChain_offDiagonal i

/-- **The `τ` family carries the state of `C` to the sum of the two states**,
`O_τ ψ_C = ψ_A + ψ_C`, at every positive system size (data file §4.4). -/
theorem mpo_fibTau_mulVec_chain (L : ℕ) (hL : 0 < L) :
    MPOTensor.mpo fibTau L *ᵥ (fun τ : Fin L → Fin 2 => mpv fibChain τ) =
      fun σ : Fin L → Fin 2 => mpv fibAllTau σ + mpv fibChain σ := by
  have h := MPOTensor.mpo_mulVec_mpv_eq_sum_of_multiBlockCompression fibActChain_compression
    L hL
  rw [show fibNimSlots = Finset.univ from rfl] at h
  simp only [Fin.sum_univ_two] at h
  exact h

end FibonacciCompression
