/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.PEPS.Approximation.SourceInputFrames
import TNLean.PEPS.Approximation.SourceGaussianContraction
import TNLean.PEPS.Approximation.GaussianPhysicalSource

/-!
# Input isometries from the original corrected sources

The endpoint Schmidt matrices at the original source occurrences determine the
proper tensor frame of the corrected registers. The original occurrence index
is retained, independently of the partial branch and of the numerical source
vectors. Exact crossing sources supply the remaining two Schmidt frames.

Source: polynomial-PEPS Theorem 5.2, `04-compression.tex`, lines 383–434.
-/

/-!
Source: September 24, 2026, polynomial-PEPS manuscript, 04-compression.tex,
eq:compression-exterior-input; Theorem 5.2, lines 409–480.
Manuscript revision: openai/math@adc7f1241b42e322a6451854ab7e4b4c146bf78a.
Independently formalized; no upstream Lean proof text reused.

Provenance-ID: 8769-source-resource-correctedsourceframes-01
TNLean.PEPS.PairEffect.SourceCircuit.correctedSourceFrame
Provenance-ID: 8769-source-resource-correctedsourceframes-02
TNLean.PEPS.PairEffect.SourceCircuit.correctedSourceFrame_basis
Provenance-ID: 8769-source-resource-correctedsourceframes-03
TNLean.PEPS.PairEffect.SourceInventory.freeSourceVector_congr
-/


noncomputable section
open scoped TensorProduct Matrix
namespace TNLean.PEPS.PairEffect.SourceInventory

/-- The joint free-source vector depends only on the selected positions. -/
theorem freeSourceVector_congr {P : Type} (R : SourceInventory P)
    (U V : Fin R.length → HSpace) (free : Fin R.length → Bool)
    (η ζ : ∀ i, U i ⊗[ℂ] V i) (h : ∀ i, free i = true → η i = ζ i) :
    freeSourceVector R U V free η = freeSourceVector R U V free ζ := by
  have hs : selectedSources R U V free η = selectedSources R U V free ζ := by
    simp only [selectedSources_eq_map]
    apply List.map_congr_left
    intro i hi
    rw [h i (List.mem_filter.mp hi).2]
  apply eq_of_heq
  exact (Layout.memCongr_apply_heq _ _).trans
    ((by rw [hs] : HEq (vector (selectedSources R U V free η))
      (vector (selectedSources R U V free ζ))).trans (Layout.memCongr_apply_heq _ _).symm)

end TNLean.PEPS.PairEffect.SourceInventory

namespace TNLean.PEPS.PairEffect.SourceCircuit
open SourceInventory TNLean.PEPS.Approximation
variable {P : Type} {a b : Layout P}

/-- Every corrected occurrence meets the affected parties generated by its endpoints. -/
private theorem correctedMask_meets (w : SourceCircuit a b) (S : Finset (sourceLocations w)) :
    ∀ e ∈ S, correctedMask w S (endpoints w e).1 = true ∨
      correctedMask w S (endpoints w e).2 = true := by
  intro e he
  left
  simp only [correctedMask, decide_eq_true_eq, mem_correctedParties]
  exact ⟨e, he, Or.inl rfl⟩

/-- The selected corrected slots retain exactly their original corrected occurrences. -/
private def correctedPositionEquiv (w : SourceCircuit a b)
    (S : Finset (sourceLocations w)) :
    {i : Fin (partialSlots (correctedMask w S) w).length // correctedSlotMask w S i = true} ≃ S :=
  (Equiv.subtypeEquivRight (fun i ↦ by
    simp only [correctedSlotMask, decide_eq_true_eq, mem_selectedPartialSlots])).trans
      (selectedPartialSlotEquiv (correctedMask w S) w S (correctedMask_meets w S))

/-- A normalized source has a nonzero Schmidt coordinate space. -/
private theorem sourceSchmidtDim_pos (w : SourceCircuit a b) (e : sourceLocations w)
    (ξ : branchLabels w e.1) : 0 < min (sourceDims w e).1 (sourceDims w e).2 := by
  have h := sourceVectorAt_norm w e ξ
  apply Nat.lt_min.mpr
  constructor
  · by_contra hn
    have hz : (sourceDims w e).1 = 0 := Nat.eq_zero_of_not_pos hn
    have hs : Subsingleton (euc (Fin (sourceDims w e).1)) := by
      rw [hz]
      infer_instance
    let := hs
    have ht : sourceVectorAt w e ξ = 0 := Subsingleton.elim _ _
    rw [ht, norm_zero] at h
    exact zero_ne_one h
  · by_contra hn
    have hz : (sourceDims w e).2 = 0 := Nat.eq_zero_of_not_pos hn
    have hs : Subsingleton (euc (Fin (sourceDims w e).2)) := by
      rw [hz]
      infer_instance
    let := hs
    have ht : sourceVectorAt w e ξ = 0 := Subsingleton.elim _ _
    rw [ht, norm_zero] at h
    exact zero_ne_one h

variable (w : SourceCircuit a b) (S : Finset (sourceLocations w))
    (E : ∀ e : sourceLocations w, branchLabels w e.1 →
      Matrix (Fin (sourceDims w e).1) (Fin (min (sourceDims w e).1 (sourceDims w e).2)) ℂ)
    (F : ∀ e : sourceLocations w, branchLabels w e.1 →
      Matrix (Fin (sourceDims w e).2) (Fin (min (sourceDims w e).1 (sourceDims w e).2)) ℂ)
    (hE : ∀ e ξ, (E e ξ)ᴴ * E e ξ = 1) (hF : ∀ e ξ, (F e ξ)ᴴ * F e ξ = 1)

open Classical in
/-- Tensor the original endpoint Schmidt columns into the actual corrected
input memory, with coordinates indexed by original occurrences. -/
def correctedSourceFrame (ξ : Choices (correctedMask w S) w) :
    EuclideanSpace ℂ (CorrectedSchmidtCoordinates w S) →ₗᵢ[ℂ]
      Mem (correctedSourceLayout w S) :=
  let A := correctedMask w S
  let R := partialSlots A w
  let U := fun i : Fin R.length ↦ euc (Fin (sourceDims w (partialSlotEquiv A w i).1).1)
  let V := fun i : Fin R.length ↦ euc (Fin (sourceDims w (partialSlotEquiv A w i).1).2)
  let K := fun i : Fin R.length ↦ Fin (min (sourceDims w (partialSlotEquiv A w i).1).1
    (sourceDims w (partialSlotEquiv A w i).1).2)
  let q := Equiv.piCongrLeft
    (fun e : S ↦ Fin (min (sourceDims w e.1).1 (sourceDims w e.1).2) ×
      Fin (min (sourceDims w e.1).1 (sourceDims w e.1).2))
    (correctedPositionEquiv w S)
  (Layout.mapOwnerIso (fun p : Option {p // A p = true} ↦ p.isSome)
    (freeSlotLayout R U V (correctedSlotMask w S))).toLinearIsometry.comp
    ((selectedSourceFrame R U V (correctedSlotMask w S) K K
      (fun i ↦ matrixFrame (E (partialSlotEquiv A w i).1 (partialSlotChoice A w ξ i))
        (hE _ _))
      (fun i ↦ matrixFrame (F (partialSlotEquiv A w i).1 (partialSlotChoice A w ξ i))
        (hF _ _))).comp
      (LinearIsometryEquiv.piLpCongrLeft 2 ℂ ℂ q.symm).toLinearIsometry)

set_option maxHeartbeats 400000 in
-- Transport between original and selected dependent tensor memories needs extra elaboration steps.
open Classical in
/-- Each corrected frame column is the actual tensor of original endpoint
Schmidt columns at the selected occurrences. Unselected slots do not contribute. -/
theorem correctedSourceFrame_basis (ξ : Choices (correctedMask w S) w)
    (u : PartialSchmidtCoordinates (correctedMask w S) w S) :
    let A := correctedMask w S
    let R := partialSlots A w
    let U := fun i : Fin R.length ↦ euc (Fin (sourceDims w (partialSlotEquiv A w i).1).1)
    let V := fun i : Fin R.length ↦ euc (Fin (sourceDims w (partialSlotEquiv A w i).1).2)
    correctedSourceFrame w S E F hE hF ξ (EuclideanSpace.basisFun _ ℂ
        (partialSchmidtCoordinateEquiv A w S (correctedMask_meets w S) u)) =
      Layout.mapOwnerIso (fun p : Option {p // A p = true} ↦ p.isSome)
        (freeSlotLayout R U V (correctedSlotMask w S))
        (freeSourceVector R U V (correctedSlotMask w S)
          (partialSchmidtSourceVectors A w S E F ξ u)) := by
  let A := correctedMask w S
  let R := partialSlots A w
  let U := fun i : Fin R.length ↦ euc (Fin (sourceDims w (partialSlotEquiv A w i).1).1)
  let V := fun i : Fin R.length ↦ euc (Fin (sourceDims w (partialSlotEquiv A w i).1).2)
  let K := fun i : Fin R.length ↦ Fin (min (sourceDims w (partialSlotEquiv A w i).1).1
    (sourceDims w (partialSlotEquiv A w i).1).2)
  let f := fun i : Fin R.length ↦ matrixFrame
    (E (partialSlotEquiv A w i).1 (partialSlotChoice A w ξ i)) (hE _ _)
  let g := fun i : Fin R.length ↦ matrixFrame
    (F (partialSlotEquiv A w i).1 (partialSlotChoice A w ξ i)) (hF _ _)
  let v : ∀ i, K i × K i := fun i ↦ if h : i ∈ selectedPartialSlots A w S then u ⟨i, h⟩
    else (⟨0, sourceSchmidtDim_pos w _ (partialSlotChoice A w ξ i)⟩,
      ⟨0, sourceSchmidtDim_pos w _ (partialSlotChoice A w ξ i)⟩)
  let η := fun i ↦ f i (EuclideanSpace.basisFun (K i) ℂ (v i).1) ⊗ₜ[ℂ]
    g i (EuclideanSpace.basisFun (K i) ℂ (v i).2)
  have hc : correctedSourceFrame w S E F hE hF ξ (EuclideanSpace.basisFun _ ℂ
        (partialSchmidtCoordinateEquiv A w S (correctedMask_meets w S) u)) =
      Layout.mapOwnerIso (fun p : Option {p // A p = true} ↦ p.isSome)
        (freeSlotLayout R U V (correctedSlotMask w S))
        (selectedSourceFrame R U V (correctedSlotMask w S) K K f g
          (EuclideanSpace.basisFun _ ℂ (fun i ↦ v i.1))) := by
    let q := Equiv.piCongrLeft
      (fun e : S ↦ Fin (min (sourceDims w e.1).1 (sourceDims w e.1).2) ×
        Fin (min (sourceDims w e.1).1 (sourceDims w e.1).2))
      (correctedPositionEquiv w S)
    change Layout.mapOwnerIso _ _ ((selectedSourceFrame R U V (correctedSlotMask w S)
      K K f g) ((LinearIsometryEquiv.piLpCongrLeft 2 ℂ ℂ q.symm)
        (EuclideanSpace.basisFun _ ℂ
          (partialSchmidtCoordinateEquiv A w S (correctedMask_meets w S) u)))) = _
    apply congrArg (fun z ↦ Layout.mapOwnerIso
      (fun p : Option {p // A p = true} ↦ p.isSome)
      (freeSlotLayout R U V (correctedSlotMask w S))
      (selectedSourceFrame R U V (correctedSlotMask w S) K K f g z))
    rw [EuclideanSpace.basisFun_apply, EuclideanSpace.piLpCongrLeft_single,
      ← EuclideanSpace.basisFun_apply]
    apply congrArg (EuclideanSpace.basisFun _ ℂ)
    funext i
    have hi : i.1 ∈ selectedPartialSlots A w S := by
      simpa only [correctedSlotMask, decide_eq_true_eq, mem_selectedPartialSlots] using i.2
    have hh := partialSchmidtCoordinateEquiv_apply A w S
      (correctedMask_meets w S) u ⟨i.1, hi⟩
    have hv : v i.1 = u ⟨i.1, hi⟩ := dite_eq_left hi
    exact hh.trans hv.symm
  refine hc.trans ?_
  apply congrArg (Layout.mapOwnerIso
    (fun p : Option {p // A p = true} ↦ p.isSome)
    (freeSlotLayout R U V (correctedSlotMask w S)))
  have hp := selectedSourceFrame_basis_prepare R U V (correctedSlotMask w S) K K f g
    v [] (1 : ℂ)
  rw [eval_prepareFreeSlots_eq_appendIso_symm] at hp
  have hv : selectedSourceFrame R U V (correctedSlotMask w S) K K f g
      (EuclideanSpace.basisFun _ ℂ (fun i ↦ v i.1)) =
      freeSourceVector R U V (correctedSlotMask w S) η := by
    have hh := congrArg (TensorProduct.rid ℂ (Mem (freeSlotLayout R U V
      (correctedSlotMask w S)))) ((appendIso _ []).symm.injective hp)
    simpa only [TensorProduct.rid_tmul, one_smul] using hh
  exact hv.trans (freeSourceVector_congr R U V (correctedSlotMask w S) η
    (partialSchmidtSourceVectors A w S E F ξ u) (by
      intro i hi
      have his : i ∈ selectedPartialSlots A w S :=
        (mem_selectedPartialSlots A w S i).mpr (of_decide_eq_true hi)
      dsimp only [η, f, g]
      have hvi : v i = u ⟨i, his⟩ := dite_eq_left his
      rw [hvi]
      change matrixFrame _ _ (EuclideanSpace.basisFun _ ℂ (u ⟨i, his⟩).1) ⊗ₜ[ℂ]
        matrixFrame _ _ (EuclideanSpace.basisFun _ ℂ (u ⟨i, his⟩).2) = _
      rw [matrixFrame_basis, matrixFrame_basis]
      simp only [partialSchmidtSourceVectors, dite_eq_left his]))

end TNLean.PEPS.PairEffect.SourceCircuit
