/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Data.ZMod.Basic
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.Tactic.Abel

/-!
# Distributing a cyclic phase across blocked sites

This module supplies the scalar telescoping step in arXiv:1708.00029,
Section 4.1, lines 765--806. Given a residue class `α` and a cyclic coordinate
`k` with `α(u+p)=α(u)` and `k(u+p)=k(u)+1`, a phase `c_α` whose order divides
the orbit length is distributed among the one-site factors by ratios of the
vertex phases `c_α^k`. Their product over `p` sites is `c_α`.

The residue-coordinate decomposition and the corresponding cyclic projectors
are separate mathematical inputs to the full tensor construction.
-/

open scoped BigOperators

namespace MPSTensor

variable {G : Type*} [CommGroup G]

/-- Products of consecutive vertex-phase ratios telescope to the phase of a
blocked step. Source: arXiv:1708.00029, lines 788--803. -/
theorem phaseDistribution_product {m p : ℕ} (b c : ZMod m → G)
    (h : ∀ u, b (u + p) = c u * b u) (u : ZMod m) :
    (∏ k ∈ Finset.range p, b (u + (k + 1 : ℕ)) / b (u + (k : ℕ))) = c u := by
  have ht := Finset.prod_range_div (fun k : ℕ => b (u + k)) p
  have he : (∏ k ∈ Finset.range p, b (u + (k + 1 : ℕ)) / b (u + (k : ℕ))) =
      b (u + p) / b u := by
    simpa using ht
  rw [he, h]
  simp

private theorem phase_pow_val_add_one {n : ℕ} [NeZero n]
    (c : G) (hc : c ^ n = 1) (k : ZMod n) :
    c ^ (k + 1).val = c * c ^ k.val := by
  have hm : (k + 1).val ≡ k.val + 1 [MOD n] := by
    simp [Nat.ModEq, ZMod.val_add, ZMod.val_one_eq_one_mod, Nat.add_mod]
  rw [pow_eq_pow_of_modEq hm hc, pow_succ]
  ac_rfl

/-- The cyclic phase distribution used in the proof of the refinement theorem.
Here `α(u)` identifies the orbit of the blocked shift by `p`, and `k(u)` is its
coordinate in `ZMod n`. If `c_α^n=1`, the one-site factor
`d_u=b(u+1)/b(u)` with `b(u)=c_{α(u)}^{k(u)}` satisfies
`∏_{j=0}^{p-1} d_{u+j}=c_{α(u)}`.

Source: arXiv:1708.00029, equations `eq:ZPA-is-cPA` and
`eq:Aprime-is-cPA`, lines 765--806. -/
theorem phaseDistribution_of_residue_coordinates
    {m n p : ℕ} [NeZero n] {ι : Type*}
    (α : ZMod m → ι) (k : ZMod m → ZMod n) (c : ι → G)
    (hα : ∀ u, α (u + p) = α u)
    (hk : ∀ u, k (u + p) = k u + 1)
    (hc : ∀ a, c a ^ n = 1) (u : ZMod m) :
    (∏ j ∈ Finset.range p,
      (c (α (u + (j + 1 : ℕ))) ^ (k (u + (j + 1 : ℕ))).val) /
        (c (α (u + (j : ℕ))) ^ (k (u + (j : ℕ))).val)) = c (α u) := by
  let b : ZMod m → G := fun v => c (α v) ^ (k v).val
  have hb : ∀ v, b (v + p) = c (α v) * b v := by
    intro v
    simp only [b, hα v, hk v]
    exact phase_pow_val_add_one (c (α v)) (hc (α v)) (k v)
  exact phaseDistribution_product b (fun v => c (α v)) hb u

/-- The orbit of translation by `p` on `ZMod m` has length
`m / gcd(m,p)`. Source: arXiv:1708.00029, Lemma `lem:unique-dec`,
lines 446--450. -/
theorem phase_residue_orbit_length {m p : ℕ} [NeZero m] :
    addOrderOf (p : ZMod m) = m / Nat.gcd m p := by
  exact ZMod.addOrderOf_coe p (NeZero.ne m)

/-- For the shift by `p` on a cyclic set of `m` sites, orbit labels and
coordinates always exist. The orbit length is the additive order of `p` in
`ZMod m`, namely `m / gcd(m,p)`. The construction uses the quotient by the
subgroup generated by `p` and the cyclic equivalence of that subgroup. The
labels are onto and identify exactly the sites in the same shift orbit.

Source: arXiv:1708.00029, Lemma `lem:unique-dec`, lines 446--450. -/
theorem exists_phase_residue_coordinates {m p : ℕ} [NeZero m] :
    ∃ (ι : Type) (α : ZMod m → ι)
      (k : ZMod m → ZMod (addOrderOf (p : ZMod m))),
      (∀ u, α (u + p) = α u) ∧
      (∀ u, k (u + p) = k u + 1) ∧
      Function.Surjective α ∧
      (∀ u v, α u = α v ↔
        u - v ∈ AddSubgroup.zmultiples (p : ZMod m)) ∧
      Nat.card ι = Nat.gcd m p := by
  classical
  let H := AddSubgroup.zmultiples (p : ZMod m)
  let g : H := ⟨p, AddSubgroup.mem_zmultiples_iff.mpr ⟨1, by simp⟩⟩
  have hg : ∀ x : H, x ∈ AddSubgroup.zmultiples g := by
    intro x
    obtain ⟨z, hz⟩ := AddSubgroup.mem_zmultiples_iff.mp x.property
    apply AddSubgroup.mem_zmultiples_iff.mpr
    refine ⟨z, ?_⟩
    apply Subtype.ext
    simpa [g] using hz
  have hn : Nat.card H = addOrderOf (p : ZMod m) := by
    simpa [H] using Nat.card_zmultiples (p : ZMod m)
  let E : ZMod (addOrderOf (p : ZMod m)) ≃+ H := zmodAddEquivOfGenerator hg hn
  let q : ZMod m →+ (ZMod m ⧸ H) := QuotientAddGroup.mk' H
  let α : ZMod m → (ZMod m ⧸ H) := q
  have hα : ∀ u, α (u + p) = α u := by
    intro u
    apply QuotientAddGroup.eq_iff_sub_mem.mpr
    simp [H]
  have hsurj : Function.Surjective q := QuotientAddGroup.mk'_surjective H
  let s : (ZMod m ⧸ H) → ZMod m := fun a => Classical.choose (hsurj a)
  have hs : ∀ a, q (s a) = a := fun a => Classical.choose_spec (hsurj a)
  let v : ZMod m → H := fun u => ⟨u - s (α u), by
    apply QuotientAddGroup.eq_iff_sub_mem.mp
    change q u = q (s (α u))
    rw [hs]⟩
  let k : ZMod m → ZMod (addOrderOf (p : ZMod m)) := fun u => E.symm (v u)
  refine ⟨(ZMod m ⧸ H), α, k, hα, ?_, hsurj, ?_, ?_⟩
  · intro u
    have hv : v (u + p) = v u + g := by
      apply Subtype.ext
      change u + p - s (α (u + p)) = (u - s (α u)) + p
      rw [hα]
      abel
    have he : E 1 = g := by
      simp [E]
    change E.symm (v (u + p)) = E.symm (v u) + 1
    rw [hv, ← he, map_add]
    simp
  · intro u v
    exact QuotientAddGroup.eq_iff_sub_mem
  · have hfact := H.card_eq_card_quotient_mul_card_addSubgroup
    have hfact' : m = Nat.card (ZMod m ⧸ H) * Nat.card H := by
      simpa only [Nat.card_zmod] using hfact
    rw [hn, phase_residue_orbit_length] at hfact'
    have hgcd : 0 < Nat.gcd m p := Nat.gcd_pos_of_pos_left p (NeZero.pos m)
    have hdiv : 0 < m / Nat.gcd m p :=
      Nat.div_pos (Nat.le_of_dvd (NeZero.pos m) (Nat.gcd_dvd_left m p)) hgcd
    have hmul : Nat.card (ZMod m ⧸ H) * (m / Nat.gcd m p) =
        Nat.gcd m p * (m / Nat.gcd m p) := by
      calc
        Nat.card (ZMod m ⧸ H) * (m / Nat.gcd m p) = m := by
          exact hfact'.symm
        _ = Nat.gcd m p * (m / Nat.gcd m p) :=
          (Nat.mul_div_cancel' (Nat.gcd_dvd_left m p)).symm
    exact Nat.eq_of_mul_eq_mul_right hdiv hmul


/-- Every phase constant along the shift by `p` and of order dividing the
shift-orbit length can be distributed over one-site factors. No orbit labels or
coordinate choices appear in the statement. Source: arXiv:1708.00029,
Lemma `lem:unique-dec` and equations `eq:ZPA-is-cPA` and
`eq:Aprime-is-cPA`, lines 446--450 and 765--806. -/
theorem exists_phaseDistribution_of_shift_invariant {m p : ℕ} [NeZero m]
    (c : ZMod m → G)
    (hshift : ∀ u, c (u + p) = c u)
    (hroot : ∀ u, c u ^ addOrderOf (p : ZMod m) = 1) :
    ∃ d : ZMod m → G,
      ∀ u : ZMod m,
        (∏ j ∈ Finset.range p, d (u + (j : ℕ))) = c u := by
  obtain ⟨ι, α, k, hα, hk, _hsurj, _horbit, _hcard⟩ :=
    exists_phase_residue_coordinates (m := m) (p := p)
  let hne : NeZero (addOrderOf (p : ZMod m)) :=
    ⟨Nat.ne_of_gt (addOrderOf_pos (p : ZMod m))⟩
  let b : ZMod m → G := fun v => c v ^ (k v).val
  have hb : ∀ v, b (v + p) = c v * b v := by
    intro v
    simp only [b, hshift v, hk v]
    exact @phase_pow_val_add_one G _ (addOrderOf (p : ZMod m)) hne
      (c v) (hroot v) (k v)
  let d : ZMod m → G := fun v => b (v + 1) / b v
  refine ⟨d, ?_⟩
  intro u
  simpa only [d, Nat.cast_add, Nat.cast_one, add_assoc] using
    phaseDistribution_product b c hb u

/-- Fin-indexed form of cyclic phase distribution for the sector projectors
of a periodic tensor. If the target phase is invariant under a blocked shift
and its order divides the shift-orbit length, it is the product of one-site
phases on every blocked segment. Source: arXiv:1708.00029, equations
`eq:ZPA-is-cPA` and `eq:Aprime-is-cPA`, lines 765--806. -/
theorem exists_phaseDistribution_fin {m p : ℕ} [NeZero m] (c : Fin m → G)
    (hshift : ∀ u : Fin m, c (u + p • (1 : Fin m)) = c u)
    (hroot : ∀ u : Fin m, c u ^ addOrderOf (p : ZMod m) = 1) :
    ∃ d : Fin m → G,
      ∀ u : Fin m, (∏ j ∈ Finset.range p, d (u + j • (1 : Fin m))) = c u := by
  let e : Fin m ≃+* ZMod m := ZMod.finEquiv m
  have he : ∀ (u : Fin m) (j : ℕ),
      e (u + j • (1 : Fin m)) = e u + j := by
    intro u j
    simp [map_add, map_nsmul]
  let cZ : ZMod m → G := fun u => c (e.symm u)
  have hshiftZ : ∀ u : ZMod m, cZ (u + p) = cZ u := by
    intro u
    have hpre : e.symm (u + p) = e.symm u + p • (1 : Fin m) := by
      apply e.injective
      simp [he]
    simpa [cZ, hpre] using hshift (e.symm u)
  have hrootZ : ∀ u : ZMod m, cZ u ^ addOrderOf (p : ZMod m) = 1 := by
    intro u
    exact hroot (e.symm u)
  obtain ⟨dZ, hdZ⟩ := exists_phaseDistribution_of_shift_invariant cZ hshiftZ hrootZ
  let d : Fin m → G := fun u => dZ (e u)
  refine ⟨d, ?_⟩
  intro u
  simpa only [d, he, cZ, e.symm_apply_apply] using hdZ (e u)
end MPSTensor
