/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.Periodic.Symmetry
import TNLean.Algebra.ProjectiveRepresentation
import TNLean.Algebra.CocycleCohomology

/-!
# Periodic MPS — projective-representation upgrade of Corollary 4.1 (arXiv:1708.00029, Section 4.2)

This file upgrades `MPSTensor.cor_4_1_physical_symmetry_zgauge_explicit`
(obtained in `MPS/Periodic/Symmetry.lean`) to a *genuine projective representation*
of the symmetry group `G` on the bond space, following Section 4.2 of arXiv:1708.00029.

The injective analogue is `MPSTensor.virtual_rep_of_symmetric_injective`
(in `MPS/Symmetry/VirtualRepresentation.lean`): there, gauge uniqueness
(`MPS/Symmetry/GaugeUniqueness.lean`) reduces associativity of the induced
virtual action to a scalar 2-cocycle on `G`. In the genuinely periodic case
the bond-space commutant of `A` is generated by the `Z_g` matrices
(`Z_g^{m_g} = 1`), so an additional analytic input is required to reduce the
full rigidity back to a scalar cocycle. Following the established repository
pattern (see `PeriodicEqualCaseFT`), that input is exposed as an explicit
hypothesis `PeriodicProjectiveRigidity`; the remainder of the projective-
representation data — the cocycle identity and the construction of a
`ProjectiveRepresentation` on the bond space — is formalised here.

## Main definitions and results

* `MPSTensor.PeriodicProjectiveRigidity` — the analytic hypothesis packaging
  the existence of a compatible family `Y : G → GL (Fin D) ℂ` together with a
  scalar 2-cochain `u : G × G → ℂˣ` satisfying the projective law on the
  bond space while every `Y g` realises the Corollary-4.1 intertwining with
  the twisted tensor.
* `MPSTensor.cor_4_1_projective_rep` — the projective-representation upgrade:
  from `PeriodicProjectiveRigidity`, produce a
  `TNLean.Algebra.ProjectiveRepresentation` on the bond space together with
  the intertwining relation between `A` and the twisted tensors.
* `MPSTensor.cor_4_1_projective_rep_cocycle` — if `D > 0`, the factor system
  satisfies the 2-cocycle identity (via
  `ProjectiveRepresentation.cocycle_of_assoc`).

## References

* arXiv:1708.00029 Section 4.2 (de las Cuevas–Schuch–Pérez-García–Cirac, 2017) —
  SPT cocycle classification.
* arXiv:0802.0447 — original projective-representation construction (injective
  case).
* Chen, Gu, Wen, *Classification of gapped symmetric phases in one-dimensional
  spin systems*, Phys. Rev. B 83, 035107 (2011).
* `MPS/Symmetry/VirtualRepresentation.lean` — injective analogue.
-/

open scoped Matrix BigOperators

namespace MPSTensor

open TNLean.Algebra

variable {d D : ℕ} {G : Type*} [Group G]

/-! ## Periodic projective-representation rigidity hypothesis -/

/-- **Periodic projective-representation rigidity hypothesis.**

A tensor `A : MPSTensor d D` in irreducible form carrying an on-site symmetry
`U : G →* Mat_d(ℂ)` satisfies `PeriodicProjectiveRigidity A U` if the `Y`-gauges
implementing Corollary 4.1 can be chosen coherently: there is a family
`Y : G → GL (Fin D) ℂ` and a scalar 2-cochain `u : G × G → ℂˣ` such that

1. Each `Y g`, together with some `Z`-matrix (satisfying the period, commutation
   and gauge-intertwining data of Corollary 4.1), realises the `Z`-gauge
   equivalence of Corollary 4.1 between `A` and the `g`-twisted tensor.
2. The family satisfies the projective multiplication law on the bond space:
   `(Y h) · (Y g) = u(g, h) • Y (g * h)` as matrices.

In the injective case (period `1`), this hypothesis reduces to
`gauge_unique_up_to_scalar` applied to `A`; in the genuinely periodic case the
`Z`-commutant of `A` is non-trivial, so an additional analytic input is required.
Callers committing to this Prop are committing to a finiteness/rigidity result
analogous to `MPSTensor.PeriodicEqualCaseFT`. -/
def PeriodicProjectiveRigidity
    (A : MPSTensor d D) (U : G →* Matrix (Fin d) (Fin d) ℂ) : Prop :=
  ∃ (Y : G → GL (Fin D) ℂ) (u : G → G → Units ℂ),
    (∀ g : G, ∃ (m : ℕ) (Z : Matrix (Fin D) (Fin D) ℂ),
      0 < m ∧ Z ^ m = 1 ∧ (∀ i : Fin d, Z * A i = A i * Z) ∧
      (∀ i : Fin d,
        Z * A i =
          (Y g : Matrix (Fin D) (Fin D) ℂ) * twistedTensor A U g i *
            (((Y g)⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ))) ∧
    ∀ g h : G,
      ((Y h : Matrix (Fin D) (Fin D) ℂ) * (Y g : Matrix (Fin D) (Fin D) ℂ)) =
        (u g h : ℂ) • ((Y (g * h) : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)

/-! ## Projective representation from the rigidity hypothesis -/

/-- **Corollary 4.1 projective-representation upgrade (arXiv:1708.00029, Section 4.2).**

If the `Y_g` family from `cor_4_1_physical_symmetry_zgauge_explicit` can be chosen
to satisfy the periodic projective-representation rigidity hypothesis, then the
bond-space gauges assemble into a projective representation of `G`:
there exist a scalar 2-cochain `ω : G × G → ℂˣ` and a
`TNLean.Algebra.ProjectiveRepresentation` on the bond space whose virtual gauges
still realise the Corollary-4.1 intertwining with the twisted tensors.

The construction uses the *inversion convention* of
`MPS/Symmetry/VirtualRepresentation.lean`: the virtual representation is
`X g := Y (g⁻¹)`, so that the projective multiplication law takes the standard
form `X g · X h = ω(g, h) • X (g * h)` with `ω(g, h) := u(h⁻¹, g⁻¹)`. -/
theorem cor_4_1_projective_rep
    (A : MPSTensor d D)
    (U : G →* Matrix (Fin d) (Fin d) ℂ)
    (hRigidity : PeriodicProjectiveRigidity A U) :
    ∃ (ω : ScalarCocycle G) (ρ : ProjectiveRepresentation (D := D) ω),
      ∀ g : G, ∃ (m : ℕ) (Z : Matrix (Fin D) (Fin D) ℂ),
        0 < m ∧ Z ^ m = 1 ∧ (∀ i : Fin d, Z * A i = A i * Z) ∧
        (∀ i : Fin d,
          Z * A i =
            ((ρ.X (g⁻¹) : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ) *
              twistedTensor A U g i *
              (((ρ.X (g⁻¹))⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)) := by
  obtain ⟨Y, u, hY, hmul⟩ := hRigidity
  refine ⟨fun g h => u (h⁻¹) (g⁻¹),
    { X := fun g => Y (g⁻¹)
      map_mul' := by
        intro g h
        have h₁ := hmul (h⁻¹) (g⁻¹)
        simpa [mul_inv_rev] using h₁ },
    ?_⟩
  intro g
  simpa using hY g

/-- **Cocycle condition for the projective-representation upgrade.**

For positive bond dimension, the factor system produced by `cor_4_1_projective_rep`
satisfies the multiplicative 2-cocycle identity on `G`. This is a consequence of
associativity of matrix multiplication via
`ProjectiveRepresentation.cocycle_of_assoc`. -/
theorem cor_4_1_projective_rep_cocycle
    (A : MPSTensor d D)
    (U : G →* Matrix (Fin d) (Fin d) ℂ)
    (hRigidity : PeriodicProjectiveRigidity A U)
    (hD : 0 < D) :
    ∃ (ω : ScalarCocycle G) (_ρ : ProjectiveRepresentation (D := D) ω),
      ScalarCocycle.IsCocycle ω := by
  obtain ⟨ω, ρ, _⟩ := cor_4_1_projective_rep A U hRigidity
  exact ⟨ω, ρ, ScalarCocycle.isCocycle_of_projRep ρ hD⟩

/-! ## Bundled constructor from the rigidity hypothesis -/

/-- **Projective representation from the periodic projective-rigidity hypothesis.**

High-level packaging of `cor_4_1_projective_rep` together with the cocycle
condition of `cor_4_1_projective_rep_cocycle`: the rigidity hypothesis upgrades
the bond-space symmetry data of Corollary 4.1 to a coherent projective
representation of `G` on the bond space, with factor system satisfying the
2-cocycle identity whenever `D > 0`.

Callers that already have the Corollary 4.1 data (irreducible form, unitary
on-site action, symmetry, periodic equal-case FT) can produce
`PeriodicProjectiveRigidity A U` in the presence of an additional analytic
coherence hypothesis. -/
theorem projectiveRep_of_symmetry
    (A : MPSTensor d D)
    (U : G →* Matrix (Fin d) (Fin d) ℂ)
    (hRigidity : PeriodicProjectiveRigidity A U) :
    ∃ (ω : ScalarCocycle G) (ρ : ProjectiveRepresentation (D := D) ω),
      (∀ g : G, ∃ (m : ℕ) (Z : Matrix (Fin D) (Fin D) ℂ),
        0 < m ∧ Z ^ m = 1 ∧ (∀ i : Fin d, Z * A i = A i * Z) ∧
        (∀ i : Fin d,
          Z * A i =
            ((ρ.X (g⁻¹) : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ) *
              twistedTensor A U g i *
              (((ρ.X (g⁻¹))⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ))) ∧
      (0 < D → ScalarCocycle.IsCocycle ω) := by
  obtain ⟨ω, ρ, hIntertwine⟩ := cor_4_1_projective_rep A U hRigidity
  exact ⟨ω, ρ, hIntertwine, fun hD => ScalarCocycle.isCocycle_of_projRep ρ hD⟩

end MPSTensor
