/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.FinSum
import TNLean.MPS.FundamentalTheorem.SectorWeightComparison
import TNLean.MPS.Periodic.FundamentalTheorem
import TNLean.MPS.Periodic.Overlap.Dichotomy

/-!
# Non-decaying periodic overlaps from proportional matrix-product vectors

This file derives the cross-family non-decaying overlaps used in the periodic
fundamental theorem from proportionality of matrix-product vectors generated by
multiplicity-bearing block-diagonal tensors. The proof compares grouped
coefficients at each fixed length along a common multiple of the block periods.
It does not impose any asymptotic condition on the proportionality scalars or
the nonzero complex multiplicity weights.

## Main result

* `PeriodicOverlapHypothesis.ofSectorDecompositions`: literal normalized
  multiplicity-bearing tensors with proportional MPVs satisfy the periodic
  overlap hypothesis.
* `PeriodicOverlapHypothesis.ofIsIrreducibleForm`: the scalar-weight
  irreducible-form specialization.

## Reference

* De las Cuevas, Cirac, Schuch, Perez-Garcia,
  *Irreducible forms of Matrix Product States: Theory and Applications*,
  arXiv:1708.00029, theorem `thm:bd`, lines 613--632.
-/

open scoped Matrix BigOperators
open Filter Topology

namespace MPSTensor

variable {d : ℕ}

/-- Repeated blocks have proportional matrix-product states at every length.

Source: arXiv:1708.00029, definition `eq:rep`, lines 276--284. -/
private lemma mpvState_eq_smul_of_hetRepeatedBlocks
    {D₁ D₂ : ℕ} {A : MPSTensor d D₁} {B : MPSTensor d D₂}
    (hRep : HetRepeatedBlocks A B) :
    ∃ α : ℕ → ℂ, ∀ N : ℕ, mpvState (d := d) A N = α N • mpvState (d := d) B N := by
  classical
  rcases hRep with ⟨hDim, ξ, Y, _hξ, hGauge⟩
  refine ⟨fun N : ℕ => ξ ^ N, ?_⟩
  intro N
  apply PiLp.ext
  intro σ
  simp only [mpvState_apply]
  rw [← mpv_cast_dim hDim A N σ]
  exact mpv_eq_pow_mul_of_gaugePhase B
    (cast (congr_arg (MPSTensor d) hDim) A) Y ξ hGauge N σ

/-- A chosen block has a non-decaying overlap partner when two tensors with
the prescribed periodic-basis expansions are projectively proportional.

Source: arXiv:1708.00029, proof of theorem `thm:bd`, lines 630--631. -/
private lemma exists_nondecaying_overlap_of_nonzeroProportionalDecompositions
    {rA rB D₁ D₂ : ℕ} {dimA : Fin rA → ℕ} {dimB : Fin rB → ℕ}
    [hneA : ∀ j, NeZero (dimA j)] [hneB : ∀ k, NeZero (dimB k)]
    (A : (j : Fin rA) → MPSTensor d (dimA j))
    (B : (k : Fin rB) → MPSTensor d (dimB k))
    (periodA : Fin rA → ℕ) (periodB : Fin rB → ℕ)
    (hPerA : ∀ j, IsPeriodic (periodA j) (A j))
    (hPerB : ∀ k, IsPeriodic (periodB k) (B k))
    (hNonRepA : ∀ i j, i ≠ j → ¬ HetRepeatedBlocks (A i) (A j))
    (hNonRepB : ∀ i j, i ≠ j → ¬ HetRepeatedBlocks (B i) (B j))
    (X : MPSTensor d D₁) (Y : MPSTensor d D₂)
    (coeffA : ℕ → Fin rA → ℂ) (coeffB : ℕ → Fin rB → ℂ)
    (hExpandA : ∀ {N : ℕ} (σ : Fin N → Fin d),
      mpv X σ = ∑ j : Fin rA, coeffA N j * mpv (A j) σ)
    (hExpandB : ∀ {N : ℕ} (σ : Fin N → Fin d),
      mpv Y σ = ∑ k : Fin rB, coeffB N k * mpv (B k) σ)
    (hCoeffA : ∀ p : ℕ, 0 < p → ∀ j : Fin rA,
      ¬ (∀ᶠ N in atTop, coeffA (p * N) j = 0))
    (hProp : NonzeroProportionalMPV₂ X Y)
    (j₀ : Fin rA) :
    ∃ k₀ : Fin rB,
      ¬ Tendsto (fun N ↦ mpvOverlap (d := d) (A j₀) (B k₀) N) atTop (nhds 0) := by
  classical
  by_contra hNo
  push Not at hNo
  let T : Finset (Fin rA) := Finset.univ.filter fun j : Fin rA ↦
    ∀ k : Fin rB,
      Tendsto (fun N ↦ mpvOverlap (d := d) (A j) (B k) N) atTop (nhds 0)
  have hj₀T : j₀ ∈ T := by
    simp [T, hNo]
  have hTQ : ∀ (j : Fin rA), j ∈ T → ∀ k : Fin rB,
      Tendsto (fun N ↦ mpvOverlap (d := d) (A j) (B k) N) atTop (nhds 0) := by
    intro j hj k
    simpa [T] using (Finset.mem_filter.mp hj).2 k
  have hNotT_nondecay : ∀ j : Fin rA, j ∉ T →
      ∃ k : Fin rB,
        ¬ Tendsto (fun N ↦ mpvOverlap (d := d) (A j) (B k) N) atTop (nhds 0) := by
    intro j hjT
    have hNot : ¬ ∀ k : Fin rB,
        Tendsto (fun N ↦ mpvOverlap (d := d) (A j) (B k) N) atTop (nhds 0) := by
      intro hAll
      exact hjT (by simp [T, hAll])
    push Not at hNot
    exact hNot
  have hScalar : ∀ c : {j : Fin rA // j ∉ T},
      ∃ k : Fin rB, ∃ α : ℕ → ℂ, ∀ N : ℕ,
        mpvState (d := d) (A c.1) N = α N • mpvState (d := d) (B k) N := by
    intro c
    obtain ⟨k, hk⟩ := hNotT_nondecay c.1 c.2
    rcases periodicOverlapDichotomy (A c.1) (B k) (hPerA c.1) (hPerB k) with
      hDecay | hRep
    · exact (hk hDecay).elim
    · obtain ⟨α, hα⟩ := mpvState_eq_smul_of_hetRepeatedBlocks hRep
      exact ⟨k, α, hα⟩
  choose kOf αOf hStateOf using hScalar
  letI : Fintype {j : Fin rA // j ∈ T} := Subtype.fintype (fun j ↦ j ∈ T)
  letI : Fintype {j : Fin rA // j ∉ T} := Subtype.fintype (fun j ↦ j ∉ T)
  let dimC : Sum {j : Fin rA // j ∈ T} (Fin rB) → ℕ :=
    Sum.elim (fun j ↦ dimA j.1) dimB
  let C : (x : Sum {j : Fin rA // j ∈ T} (Fin rB)) → MPSTensor d (dimC x) :=
    Sum.rec (motive := fun x ↦ MPSTensor d (dimC x))
      (fun j ↦ A j.1) (fun k ↦ B k)
  let periodC : Sum {j : Fin rA // j ∈ T} (Fin rB) → ℕ :=
    Sum.elim (fun j ↦ periodA j.1) periodB
  have hPerC : ∀ x, IsPeriodic (periodC x) (C x) := by
    intro x
    cases x with
    | inl j => simpa [C, dimC, periodC] using hPerA j.1
    | inr k => simpa [C, dimC, periodC] using hPerB k
  let pA : ℕ := ∏ j : Fin rA, periodA j
  let pB : ℕ := ∏ k : Fin rB, periodB k
  let p : ℕ := pA * pB
  have hpA : 0 < pA := Finset.prod_pos fun j _ ↦ (hPerA j).period_pos
  have hpB : 0 < pB := Finset.prod_pos fun k _ ↦ (hPerB k).period_pos
  have hp : 0 < p := by
    exact Nat.mul_pos hpA hpB
  letI : NeZero p := ⟨hp.ne'⟩
  have hDivC : ∀ x, periodC x ∣ p := by
    intro x
    cases x with
    | inl j =>
        simpa [periodC, p] using dvd_mul_of_dvd_left
          (Finset.dvd_prod_of_mem periodA (Finset.mem_univ j.1)) pB
    | inr k =>
        simpa [periodC, p] using dvd_mul_of_dvd_right
          (Finset.dvd_prod_of_mem periodB (Finset.mem_univ k)) pA
  have hCrossC : ∀ x y, x ≠ y →
      Tendsto (fun N ↦ mpvOverlap (d := d) (C x) (C y) N) atTop (nhds 0) := by
    intro x y hxy
    cases x with
    | inl i =>
        cases y with
        | inl j =>
            have hij : i.1 ≠ j.1 := by
              intro hij
              apply hxy
              exact congrArg Sum.inl (Subtype.ext hij)
            rcases periodicOverlapDichotomy (A i.1) (A j.1) (hPerA i.1) (hPerA j.1) with
              hDecay | hRep
            · simpa [C, dimC] using hDecay
            · exact absurd hRep (hNonRepA i.1 j.1 hij)
        | inr k => simpa [C, dimC] using hTQ i.1 i.2 k
    | inr k =>
        cases y with
        | inl i =>
            simpa [C, dimC] using
              tendsto_mpvOverlap_zero_swap (A i.1) (B k) (hTQ i.1 i.2 k)
        | inr l =>
            have hkl : k ≠ l := by
              intro hkl
              apply hxy
              simp [hkl]
            rcases periodicOverlapDichotomy (B k) (B l) (hPerB k) (hPerB l) with
              hDecay | hRep
            · simpa [C, dimC] using hDecay
            · exact absurd hRep (hNonRepB k l hkl)
  obtain ⟨N₀, hLI⟩ :=
    periodicFamily_eventuallyLinearlyIndependent_of_cross_overlap_tendsto_zero
      C periodC hPerC p hDivC hCrossC
  have hCoeff_eventually_zero :
      ∀ᶠ N in atTop, coeffA (p * N) j₀ = 0 := by
    rw [eventually_atTop]
    refine ⟨max N₀ 1, ?_⟩
    intro N hN
    have hN₀ : N₀ ≤ N := le_trans (le_max_left N₀ 1) hN
    have hNpos : 0 < N := lt_of_lt_of_le Nat.zero_lt_one
      (le_trans (le_max_right N₀ 1) hN)
    have hLIN : LinearIndependent ℂ
        (fun x ↦ mpvState (d := d) (C x) (p * N)) := hLI N hN₀
    have hpNpos : 0 < p * N := Nat.mul_pos hp hNpos
    obtain ⟨c, _hc, hEq⟩ := hProp (p * N) hpNpos
    have hAstate :
        mpvState (d := d) X (p * N) =
          ∑ j : Fin rA, coeffA (p * N) j •
            mpvState (d := d) (A j) (p * N) := by
      refine mpvState_eq_sum_of_decomp (d := d) X A
        (N := p * N) (coeffA (p * N)) ?_
      intro σ
      simpa [smul_eq_mul] using hExpandA σ
    have hBstate :
        mpvState (d := d) Y (p * N) =
          ∑ k : Fin rB, coeffB (p * N) k •
            mpvState (d := d) (B k) (p * N) := by
      refine mpvState_eq_sum_of_decomp (d := d) Y B
        (N := p * N) (coeffB (p * N)) ?_
      intro σ
      simpa [smul_eq_mul] using hExpandB σ
    have hStateEq :
        mpvState (d := d) X (p * N) = c • mpvState (d := d) Y (p * N) := by
      apply PiLp.ext
      intro σ
      simpa [mpvState_apply] using hEq σ
    have hSum :
        (∑ j : Fin rA, coeffA (p * N) j •
            mpvState (d := d) (A j) (p * N)) =
          ∑ k : Fin rB, (c * coeffB (p * N) k) •
            mpvState (d := d) (B k) (p * N) := by
      calc
        (∑ j : Fin rA, coeffA (p * N) j •
            mpvState (d := d) (A j) (p * N)) =
            mpvState (d := d) X (p * N) := hAstate.symm
        _ = c • mpvState (d := d) Y (p * N) := hStateEq
        _ = c • (∑ k : Fin rB, coeffB (p * N) k •
            mpvState (d := d) (B k) (p * N)) := by rw [hBstate]
        _ = ∑ k : Fin rB, (c * coeffB (p * N) k) •
            mpvState (d := d) (B k) (p * N) := by
          simp [Finset.smul_sum, smul_smul]
    have hLIN' : LinearIndependent ℂ
        (Sum.elim
          (fun j : {j : Fin rA // j ∈ T} ↦ mpvState (d := d) (A j.1) (p * N))
          (fun k : Fin rB ↦ mpvState (d := d) (B k) (p * N))) := by
      have hFamily :
          (fun x ↦ mpvState (d := d) (C x) (p * N)) =
            Sum.elim
              (fun j : {j : Fin rA // j ∈ T} ↦
                mpvState (d := d) (A j.1) (p * N))
              (fun k : Fin rB ↦ mpvState (d := d) (B k) (p * N)) := by
        funext x
        cases x <;> rfl
      rw [← hFamily]
      exact hLIN
    exact coefficient_eq_zero_of_sum_eq_of_complement_smul
      (T := T)
      (a := coeffA (p * N))
      (u := fun j ↦ mpvState (d := d) (A j) (p * N))
      (b := fun k ↦ c * coeffB (p * N) k)
      (v := fun k ↦ mpvState (d := d) (B k) (p * N))
      (kOf := kOf)
      (α := fun i ↦ αOf i (p * N))
      (hComplement := fun i ↦ hStateOf i (p * N))
      (hSum := hSum)
      (hLI := hLIN') hj₀T
  exact hCoeffA p hp j₀ hCoeff_eventually_zero

/-- Literal multiplicity-bearing direct sums of normalized bases of periodic
tensors with proportional MPVs have non-decaying overlap partners in both
directions.

For a sector `j`, the coefficient of its basis vector at length `N` is
`P.coeff N j = ∑ q, (P.weight j q) ^ N`, namely the trace of the `N`-th power
of the diagonal multiplicity matrix. The proof compares these grouped
coefficients; repeated copies are not treated as linearly independent vectors.
The two bases are assumed pairwise non-repeated, and the proportionality scalar
may depend freely on the positive chain length.

Source: arXiv:1708.00029, equations `eq:bdnr` and `eq:Bbdnr`, lines 286--305
and 575--585; proof of theorem `thm:bd`, lines 630--631.

**Scope restriction (normalization):** The source first assumes irreducible
blocks of spectral radius one and then obtains trace-preserving blocks by a
block-diagonal similarity at lines 313--332. Here each basis block is already
`IsPeriodic`, hence left-canonical. The literal multiplicity-bearing
presentation and positive-length proportionality agree with the source, but
normalization by similarity and transport back to the original blocks remain
to be formalized. This theorem constructs the three fields of
`PeriodicOverlapHypothesis`; it does not assert the unique basis matching in
source theorem `thm:bd`. This restriction is recorded in
`docs/paper-gaps/1708_periodic_overlap_route_alignment.tex`. -/
theorem PeriodicOverlapHypothesis.ofSectorDecompositions
    (P Q : SectorDecomposition d)
    (periodP : Fin P.basisCount → ℕ)
    (periodQ : Fin Q.basisCount → ℕ)
    (hPerP : ∀ j, IsPeriodic (periodP j) (P.basis j))
    (hPerQ : ∀ k, IsPeriodic (periodQ k) (Q.basis k))
    (hNonRepP : ∀ i j, i ≠ j → ¬ HetRepeatedBlocks (P.basis i) (P.basis j))
    (hNonRepQ : ∀ i j, i ≠ j → ¬ HetRepeatedBlocks (Q.basis i) (Q.basis j))
    (hProp : NonzeroProportionalMPV₂ P.toTensor Q.toTensor) :
    PeriodicOverlapHypothesis P.basis Q.basis := by
  classical
  letI : ∀ j, NeZero (P.basisDim j) := fun j ↦ ⟨(hPerP j).bondDim_ne_zero⟩
  letI : ∀ k, NeZero (Q.basisDim k) := fun k ↦ ⟨(hPerQ k).bondDim_ne_zero⟩
  have hExP : ∀ j₀ : Fin P.basisCount, ∃ k₀ : Fin Q.basisCount,
      ¬ Tendsto (fun N ↦ mpvOverlap (d := d) (P.basis j₀) (Q.basis k₀) N)
        atTop (nhds 0) := fun j₀ ↦
    exists_nondecaying_overlap_of_nonzeroProportionalDecompositions
      P.basis Q.basis periodP periodQ hPerP hPerQ hNonRepP hNonRepQ
      P.toTensor Q.toTensor P.coeff Q.coeff
      (fun σ ↦ P.mpv_toTensor_eq_sum_coeff σ)
      (fun σ ↦ Q.mpv_toTensor_eq_sum_coeff σ)
      (fun p hp j ↦ P.coeff_mul_not_eventually_zero p hp j) hProp j₀
  have hExQ : ∀ k₀ : Fin Q.basisCount, ∃ j₀ : Fin P.basisCount,
      ¬ Tendsto (fun N ↦ mpvOverlap (d := d) (P.basis j₀) (Q.basis k₀) N)
        atTop (nhds 0) := by
    intro k₀
    obtain ⟨j₀, hNondecay⟩ :=
      exists_nondecaying_overlap_of_nonzeroProportionalDecompositions
        Q.basis P.basis periodQ periodP hPerQ hPerP hNonRepQ hNonRepP
        Q.toTensor P.toTensor Q.coeff P.coeff
        (fun σ ↦ Q.mpv_toTensor_eq_sum_coeff σ)
        (fun σ ↦ P.mpv_toTensor_eq_sum_coeff σ)
        (fun p hp k ↦ Q.coeff_mul_not_eventually_zero p hp k) hProp.symm k₀
    refine ⟨j₀, ?_⟩
    intro hDecay
    apply hNondecay
    exact tendsto_mpvOverlap_zero_swap (P.basis j₀) (Q.basis k₀) hDecay
  exact PeriodicOverlapHypothesis.ofIsPeriodic
    P.basis Q.basis periodP periodQ hPerP hPerQ hExP hExQ

/-- Proportional, normalized scalar-weight MPV representations have
non-decaying overlap partners in both directions.

The proportionality scalar may depend on the chain length. The proof uses
only fixed-length coefficient comparison along a common multiple of the block
periods; no convergence or boundedness condition is imposed on those scalars
or on the positive real weights.

Source: arXiv:1708.00029, equations `eq:bdnr` and `eq:Bbdnr`, lines 286--305
and 575--585; normalization by similarity, lines 313--332; and theorem
`thm:bd`, lines 613--632.

**Scope restriction (weights, length, representation, and normalization):**
`IsIrreducibleForm` records one positive real scalar for each periodic block,
rather than the diagonal multiplicity matrices in the source irreducible form.
Its `sameMPV` field gives MPV-family equality with the scalar-weight direct-sum
tensor rather than literal tensor equality. That equality includes the empty
word and therefore forces equality of bond-dimension traces, while the source
physical family is positive-length and permits a lower-dimensional
representative at lines 266--271. The local `IsPeriodic` blocks are also
left-canonical. The source obtains that normalization by a block-diagonal
similarity at lines 313--332, but the reduction and transport back are absent
from this declaration. Pairwise non-repetition is supplied explicitly, as in
the source basis of periodic tensors. This theorem proves the three fields of
`PeriodicOverlapHypothesis`; it does not prove the unique block matching
conclusion of source theorem `thm:bd`. These restrictions are recorded in
`docs/paper-gaps/1708_periodic_overlap_route_alignment.tex`. -/
theorem PeriodicOverlapHypothesis.ofIsIrreducibleForm
    {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hA : IsIrreducibleForm A) (hB : IsIrreducibleForm B)
    (hNonRepA : ∀ i j : Fin hA.r, i ≠ j →
      ¬ HetRepeatedBlocks (hA.blocks i) (hA.blocks j))
    (hNonRepB : ∀ i j : Fin hB.r, i ≠ j →
      ¬ HetRepeatedBlocks (hB.blocks i) (hB.blocks j))
    (hProp : NonzeroProportionalMPV₂ A B) :
    PeriodicOverlapHypothesis hA.blocks hB.blocks := by
  classical
  letI : ∀ j, NeZero (hA.dim j) := fun j ↦ ⟨(hA.periodic j).bondDim_ne_zero⟩
  letI : ∀ k, NeZero (hB.dim k) := fun k ↦ ⟨(hB.periodic k).bondDim_ne_zero⟩
  have hμA : ∀ j, hA.μ j ≠ 0 := by
    intro j hzero
    simpa [hzero] using (hA.weight_pos j).1
  have hμB : ∀ k, hB.μ k ≠ 0 := by
    intro k hzero
    simpa [hzero] using (hB.weight_pos k).1
  have hPropAssemblies : NonzeroProportionalMPV₂
      (toTensorFromBlocks (d := d) hA.μ hA.blocks)
      (toTensorFromBlocks (d := d) hB.μ hB.blocks) := by
    intro N hN
    obtain ⟨c, hc, hEq⟩ := hProp N hN
    refine ⟨c, hc, fun σ ↦ ?_⟩
    calc
      mpv (toTensorFromBlocks (d := d) hA.μ hA.blocks) σ = mpv A σ :=
        (hA.sameMPV N σ).symm
      _ = c * mpv B σ := hEq σ
      _ = c * mpv (toTensorFromBlocks (d := d) hB.μ hB.blocks) σ := by
        rw [hB.sameMPV N σ]
  have hExA : ∀ j₀ : Fin hA.r, ∃ k₀ : Fin hB.r,
      ¬ Tendsto (fun N ↦ mpvOverlap (d := d) (hA.blocks j₀) (hB.blocks k₀) N)
        atTop (nhds 0) := fun j₀ ↦
    exists_nondecaying_overlap_of_nonzeroProportionalDecompositions
      hA.blocks hB.blocks hA.period hB.period hA.periodic hB.periodic
      hNonRepA hNonRepB
      (toTensorFromBlocks (d := d) hA.μ hA.blocks)
      (toTensorFromBlocks (d := d) hB.μ hB.blocks)
      (fun N j ↦ (hA.μ j) ^ N) (fun N k ↦ (hB.μ k) ^ N)
      (fun σ ↦ by
        simpa [smul_eq_mul] using mpv_toTensorFromBlocks_eq_sum hA.μ hA.blocks σ)
      (fun σ ↦ by
        simpa [smul_eq_mul] using mpv_toTensorFromBlocks_eq_sum hB.μ hB.blocks σ)
      (fun p _hp j hEv ↦ by
        rw [eventually_atTop] at hEv
        obtain ⟨M, hM⟩ := hEv
        exact pow_ne_zero (p * M) (hμA j) (hM M le_rfl))
      hPropAssemblies j₀
  have hExB : ∀ k₀ : Fin hB.r, ∃ j₀ : Fin hA.r,
      ¬ Tendsto (fun N ↦ mpvOverlap (d := d) (hA.blocks j₀) (hB.blocks k₀) N)
        atTop (nhds 0) := by
    intro k₀
    obtain ⟨j₀, hNondecay⟩ :=
      exists_nondecaying_overlap_of_nonzeroProportionalDecompositions
        hB.blocks hA.blocks hB.period hA.period hB.periodic hA.periodic
        hNonRepB hNonRepA
        (toTensorFromBlocks (d := d) hB.μ hB.blocks)
        (toTensorFromBlocks (d := d) hA.μ hA.blocks)
        (fun N k ↦ (hB.μ k) ^ N) (fun N j ↦ (hA.μ j) ^ N)
        (fun σ ↦ by
          simpa [smul_eq_mul] using mpv_toTensorFromBlocks_eq_sum hB.μ hB.blocks σ)
        (fun σ ↦ by
          simpa [smul_eq_mul] using mpv_toTensorFromBlocks_eq_sum hA.μ hA.blocks σ)
        (fun p _hp k hEv ↦ by
          rw [eventually_atTop] at hEv
          obtain ⟨M, hM⟩ := hEv
          exact pow_ne_zero (p * M) (hμB k) (hM M le_rfl))
        hPropAssemblies.symm k₀
    refine ⟨j₀, ?_⟩
    intro hDecay
    apply hNondecay
    exact tendsto_mpvOverlap_zero_swap (hA.blocks j₀) (hB.blocks k₀) hDecay
  exact PeriodicOverlapHypothesis.ofIsPeriodic
    hA.blocks hB.blocks hA.period hB.period hA.periodic hB.periodic hExA hExB

end MPSTensor
