/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import TNLean.Algebra.ComplexSqrt
import TNLean.MPS.Examples.CZY.CZYSquare

/-!
# CZY: the reduced bond-three tensor `A_0`

**Source.** arXiv:2509.03600, `References/2509.03600/main.tex` lines 223–240: the change of
virtual basis `X_{1,1}` brings the stacked tensor to `A_0 ⊕ 0` with
`A_0^{00} = [[0,-1,1],[0,1,-1],[0,0,0]]`, `A_0^{11} = [[0,1,1],[0,1,1],[0,0,0]]`, and the
mixed components zero; `A_0` is not injective, "cannot be further decomposed into a direct sum
of injective MPOs", and generates the identity on periodic chains. The matrix `X_{1,1}` is
printed in the appendix, main.tex lines 664–673; the fusion tensor `Y_{0,0}` is the first three
rows of `X_{0,0}`, main.tex lines 700–714, with the one-sided fusion identity
`Y_{0,0} (∑_j A_0^{ij} ⊗ A_0^{jk}) = A_0^{ik} Y_{0,0}` of main.tex lines 249–253.

**Formalized here.** The printed `X_{1,1}` is orthogonal and conjugates the stacked tensor to
`A_0 ⊕ 0` exactly as printed. The tensor `A_0` is an instance of the multi-block asymmetric
compression theorem with the single target the bond-one identity tensor `δ` and two zero slots,
with the identity gauge: its letters are already upper triangular with `δ` on the middle
diagonal entry. Hence `A_0` generates the identity at every length `N ≥ 1`. Both sitewise
intertwiner spaces between `A_0` and `δ` vanish, so every compression of `A_0` onto `δ` has a
nonzero remainder and the algebra generated by its letters is not closed under conjugate
transposition; in particular it is not the full matrix algebra, so `A_0` is not injective, as the
source states. The commutant of its letters consists of matrices `aI + bE₀₂`, whose only
idempotents are zero and the identity. Consequently its virtual space has no nontrivial
decomposition into complementary invariant subspaces. This excludes arbitrary simultaneous
bond similarities to direct sums of injective MPO tensors, including decompositions retaining
zero blocks.
The printed `Y_{0,0}` satisfies the one-sided fusion identity.

## Main results

* `CZYCompression.czyX11_mul_transpose`, `CZYCompression.czyX11_conj`: the printed change of
  basis is orthogonal and conjugates the stacked tensor to `A_0 ⊕ 0`.
* `CZYCompression.czyReduced_compression`: the compression of `A_0` onto `δ` with two zero
  slots.
* `CZYCompression.mpo_czyReducedTensor`: `A_0` generates the identity at every `N ≥ 1`.
* `CZYCompression.czyReduced_remainder_ne_zero`, `CZYCompression.czyReduced_not_starClosed`,
  `CZYCompression.czyReduced_adjoin_ne_top`: no compression of `A_0` splits, its virtual algebra
  is not star closed, and it is a proper subalgebra.
* `CZYCompression.czyReduced_commuting_idempotent`,
  `CZYCompression.czyReduced_invariant_isCompl`: no nontrivial commuting idempotent or
  complementary invariant subspaces.
* `CZYCompression.czyY00_fusion`: the one-sided fusion identity for `Y_{0,0}`.

## References

- [arXiv:2509.03600](https://arxiv.org/abs/2509.03600) -- Y. Liu, A. Molnár, X.-Q. Sun,
  F. Verstraete, K. Kato, L. Lootens, *Trading Mathematical for Physical Simplicity:
  Bialgebraic Structures in Matrix Product Operator Symmetries*
-/

noncomputable section

open scoped Matrix

namespace CZYCompression

open MPSTensor CZXCompression

/-! ### The tensor `A_0` -/

/-- The integer tensor `A_0` (arXiv:2509.03600, main.tex lines 223–239). -/
def czyReducedIntTensor : Fin 2 → Fin 2 → Matrix (Fin 3) (Fin 3) ℤ
  | 0, 0 => !![0, -1, 1; 0, 1, -1; 0, 0, 0]
  | 1, 1 => !![0, 1, 1; 0, 1, 1; 0, 0, 0]
  | _, _ => 0

/-- The tensor `A_0` as a matrix product operator tensor (arXiv:2509.03600, main.tex
lines 223–239). -/
def czyReducedTensor : MPOTensor 2 3 := fun i j => complexOfInt (czyReducedIntTensor i j)

/-- The integer matrices of `A_0` in the pair-alphabet order `(0,0), (0,1), (1,0), (1,1)`. -/
def czyReducedIntMPS : Fin 4 → Matrix (Fin 3) (Fin 3) ℤ
  | 0 => !![0, -1, 1; 0, 1, -1; 0, 0, 0]
  | 1 => 0
  | 2 => 0
  | 3 => !![0, 1, 1; 0, 1, 1; 0, 0, 0]

/-- The tensor `A_0` in the pair-alphabet view. -/
def czyReduced : MPSTensor 4 3 := czyReducedTensor.toMPSTensor

theorem czyReduced_eq (a : Fin 4) : czyReduced a = complexOfInt (czyReducedIntMPS a) := by
  fin_cases a <;> rfl

/-! ### The printed change of basis `X_{1,1}` -/

/-- The integer matrix `√2 X_{1,1}` (arXiv:2509.03600, main.tex lines 664–673). -/
def czyX11Int : Matrix (Fin 4) (Fin 4) ℤ :=
  !![0, 1, 1, 0; 0, -1, 1, 0; -1, 0, 0, 1; -1, 0, 0, -1]

/-- The integer matrices of `A_0 ⊕ 0`, with `A_0` on the first three coordinates. -/
def czyReducedPadInt : Fin 4 → Matrix (Fin 4) (Fin 4) ℤ
  | 0 => !![0, -1, 1, 0; 0, 1, -1, 0; 0, 0, 0, 0; 0, 0, 0, 0]
  | 1 => 0
  | 2 => 0
  | 3 => !![0, 1, 1, 0; 0, 1, 1, 0; 0, 0, 0, 0; 0, 0, 0, 0]

/-- The padded letters are `A_0` on the first three coordinates and zero on the last row and
column. -/
theorem czyReducedPadInt_apply (a : Fin 4) (x y : Fin 3) :
    czyReducedPadInt a (Fin.castSucc x : Fin 4) (Fin.castSucc y : Fin 4) =
      czyReducedIntMPS a x y ∧
    czyReducedPadInt a 3 (Fin.castSucc y : Fin 4) = 0 ∧
    czyReducedPadInt a (Fin.castSucc x : Fin 4) 3 = 0 ∧ czyReducedPadInt a 3 3 = 0 := by
  fin_cases a <;> fin_cases x <;> fin_cases y <;> decide

theorem czyX11Int_mul_transpose : czyX11Int * czyX11Intᵀ = (2 : ℤ) • 1 := by decide

theorem czyX11Int_conj (a : Fin 4) :
    czyX11Int * czySquareInt a * czyX11Intᵀ = (2 : ℤ) • czyReducedPadInt a := by
  revert a
  decide

/-- The printed change of basis `X_{1,1}` (arXiv:2509.03600, main.tex lines 664–673). -/
def czyX11 : Matrix (Fin 4) (Fin 4) ℂ := Complex.invSqrtTwo • complexOfInt czyX11Int

private theorem czyX11_transpose : czyX11ᵀ = Complex.invSqrtTwo • complexOfInt czyX11Intᵀ :=
  rfl

private theorem czyX11_sandwich (M : Matrix (Fin 4) (Fin 4) ℂ) :
    czyX11 * M * czyX11ᵀ =
      (2 : ℂ)⁻¹ • (complexOfInt czyX11Int * M * complexOfInt czyX11Intᵀ) := by
  rw [czyX11_transpose, czyX11]
  simp only [Matrix.smul_mul, Matrix.mul_smul, smul_smul, Complex.invSqrtTwo_mul_self]

/-- **`X_{1,1}` is orthogonal**: `X_{1,1} X_{1,1}ᵀ = 1`, so its inverse is its transpose. -/
theorem czyX11_mul_transpose : czyX11 * czyX11ᵀ = 1 := by
  have h := czyX11_sandwich 1
  rw [Matrix.mul_one, Matrix.mul_one, ← complexOfInt_mul, czyX11Int_mul_transpose,
    complexOfInt_zsmul, complexOfInt_one, smul_smul] at h
  rw [h]
  norm_num

/-- **The printed reduction of the stacked tensor** (arXiv:2509.03600, main.tex lines 223–239):
`X_{1,1} Ã_0^a X_{1,1}⁻¹ = A_0^a ⊕ 0` for every letter `a`, with `X_{1,1}⁻¹ = X_{1,1}ᵀ`. -/
theorem czyX11_conj (a : Fin 4) :
    czyX11 * czySquare a * czyX11ᵀ = complexOfInt (czyReducedPadInt a) := by
  rw [czyX11_sandwich, czySquare_eq, ← complexOfInt_mul, ← complexOfInt_mul, czyX11Int_conj,
    complexOfInt_zsmul, smul_smul]
  norm_num

/-! ### The compression of `A_0` onto `δ` -/

/-- The block ordering of `A_0`: a zero slot, the target `δ`, and a zero slot. -/
def czyReducedOrd : BlockIndex oneSlot 2 ≃ Fin 3 where
  toFun
    | Sum.inl _ => 1
    | Sum.inr t => ![0, 2] t
  invFun
    | 0 => Sum.inr 0
    | 1 => Sum.inl ⟨(), Finset.mem_singleton_self ()⟩
    | 2 => Sum.inr 1
  left_inv := by decide
  right_inv := by decide

/-- The labelling of the three bond coordinates of `A_0` by the graded block space. -/
def czyReducedTau : BlockSpace squareDim oneSlot 2 ≃ Fin 3 where
  toFun x := czyReducedOrd x.1
  invFun
    | 0 => ⟨Sum.inr 0, 0⟩
    | 1 => ⟨Sum.inl ⟨(), Finset.mem_singleton_self ()⟩, 0⟩
    | 2 => ⟨Sum.inr 1, 0⟩
  left_inv := by decide
  right_inv := by decide

/-- The identity gauge of `A_0`, relabelled along the block coordinates. -/
def czyReducedGauge : (Fin 3 → ℂ) ≃ₗ[ℂ] (BlockSpace squareDim oneSlot 2 → ℂ) :=
  gaugeOfRingMatrix (Int.castRingHom ℂ) czyReducedTau 1 1 (Matrix.mul_one 1) (Matrix.mul_one 1)

theorem czyReduced_conjMatrix (i : Fin 4) :
    conjMatrix czyReducedGauge (czyReduced i) =
      (complexOfInt (czyReducedIntMPS i)).submatrix czyReducedTau czyReducedTau := by
  rw [czyReducedGauge, conjMatrix_gaugeOfRingMatrix _ _ _ _ (czyReduced_eq i), Matrix.one_mul,
    Matrix.mul_one]

private theorem czyReduced_triangular_int (i : Fin 4)
    (x y : BlockSpace squareDim oneSlot 2) (h : czyReducedOrd y.1 < czyReducedOrd x.1) :
    czyReducedIntMPS i (czyReducedTau x) (czyReducedTau y) = 0 := by
  revert i x y
  decide

private theorem czyReduced_matched_int (i : Fin 4) (p q : Fin 1) :
    czyReducedIntMPS i (czyReducedTau ⟨Sum.inl oneSlotMem, p⟩)
        (czyReducedTau ⟨Sum.inl oneSlotMem, q⟩) = identityIntMPS i p q := by
  obtain rfl : p = 0 := Subsingleton.elim p 0
  obtain rfl : q = 0 := Subsingleton.elim q 0
  revert i
  decide

private theorem czyReduced_unmatched_int (i : Fin 4) (t : Fin 2) (p q : Fin 1) :
    czyReducedIntMPS i (czyReducedTau ⟨Sum.inr t, p⟩) (czyReducedTau ⟨Sum.inr t, q⟩) = 0 := by
  revert i t p q
  decide

/-- **`A_0` as a multi-block compression onto `δ`** with one matched slot and two zero slots
(arXiv:2509.03600, main.tex lines 223–240, read through the multi-block asymmetric compression
theorem). -/
def czyReduced_compression : MultiBlockCompression czyReduced oneSlot czySquareTarget :=
  MultiBlockCompression.ofRing (Int.castRingHom ℂ) czyReducedOrd czyReducedTau czyReducedGauge
    czyReducedIntMPS czyReduced_conjMatrix (fun _ => identityIntMPS) czySquareTarget_eq
    czyReduced_triangular_int
    (fun i s p q => by
      obtain rfl := eq_oneSlotMem s
      exact czyReduced_matched_int i p q)
    czyReduced_unmatched_int

/-- **Nilpotency of the remainder of `A_0`**: every word of length at least `1 + 2 = 3` in the
remainder vanishes. -/
theorem czyReduced_evalWord_remainder_eq_zero (w : List (Fin 4)) (hw : 3 ≤ w.length) :
    Kraus.evalWord czyReduced_compression.remainder w = 0 :=
  czyReduced_compression.evalWord_remainder_eq_zero w (by change (1 : ℕ) + 2 ≤ w.length; omega)

/-- **`A_0` generates the identity at every positive length** (arXiv:2509.03600, main.tex
line 240). -/
theorem mpo_czyReducedTensor (N : ℕ) (hN : 0 < N) : MPOTensor.mpo czyReducedTensor N = 1 := by
  rw [MPOTensor.mpo_eq_of_trace_evalWord _ identityTensor (fun w hw => by
      rw [show czyReducedTensor.toMPSTensor = czyReduced from rfl,
        czyReduced_compression.trace_evalWord_eq_sum w hw, Finset.sum_singleton]
      rfl) N hN,
    identityTensor_eq_idTensor, MPOTensor.mpo_idTensor]

/-! ### Nonsplitting of `A_0` -/

/-- **No nonzero right sitewise intertwiner** `A_0^i X = X δ^i`. -/
theorem czyReduced_right_intertwiner_eq_zero (X : Matrix (Fin 3) (Fin 1) ℂ)
    (h : ∀ i, czyReduced i * X = X * czySquareTarget () i) : X = 0 :=
  right_intertwiner_eq_zero_of_ringCertificate (Int.castRingHom ℂ) czyReducedIntMPS
    czyReduced_eq identityIntMPS (czySquareTarget_eq ()) ![(0, 0, 0), (0, 1, 0), (3, 0, 0)]
    (Matrix.of fun x => ![![-1, -2, -1], ![-1, 0, 1], ![0, -2, 0]] x.1)
    (c := 2) (by norm_num) (by decide) X h

/-- **No nonzero left sitewise intertwiner** `Y A_0^i = δ^i Y`. -/
theorem czyReduced_left_intertwiner_eq_zero (Y : Matrix (Fin 1) (Fin 3) ℂ)
    (h : ∀ i, Y * czyReduced i = czySquareTarget () i * Y) : Y = 0 :=
  left_intertwiner_eq_zero_of_ringCertificate (Int.castRingHom ℂ) czyReducedIntMPS
    czyReduced_eq identityIntMPS (czySquareTarget_eq ()) ![(0, 0, 0), (0, 2, 0), (3, 2, 0)]
    (Matrix.of fun x => ![![-2, 0, 0], ![0, -1, 1], ![-2, -1, -1]] x.1)
    (c := 2) (by norm_num) (by decide) Y h

/-- **No compression of `A_0` onto `δ` splits**: the remainder of every multi-block compression
onto `δ` is nonzero. This excludes only compressions onto `δ`; the claim of arXiv:2509.03600,
main.tex line 240, that `A_0` "cannot be further decomposed into a direct sum of injective MPOs"
concerns arbitrary decompositions and is established by `czyReduced_invariant_isCompl`. -/
theorem czyReduced_remainder_ne_zero
    (P : MultiBlockCompression czyReduced oneSlot czySquareTarget) : P.remainder ≠ 0 :=
  P.remainder_ne_zero_of_forall_right_intertwiner_eq_zero oneSlotMem Nat.one_pos
    czyReduced_right_intertwiner_eq_zero

/-- **The virtual algebra of `A_0` is not star closed.** -/
theorem czyReduced_not_starClosed :
    ¬ ∀ i, (czyReduced i)ᴴ ∈ Algebra.adjoin ℂ (Set.range czyReduced) :=
  MPSTensor.not_forall_conjTranspose_mem_adjoin_of_forall_right_intertwiner_eq_zero
    oneSlot czySquareTarget (fun s _ => czySquareTarget_isNormal s)
    (fun _ _ => Nat.one_pos) czyReduced
    (fun w hw => czyReduced_compression.trace_evalWord_eq_sum w hw) oneSlotMem
    czyReduced_right_intertwiner_eq_zero

/-- **The letters of `A_0` do not generate the full matrix algebra** (arXiv:2509.03600, main.tex
line 240): the generated algebra is not star closed, while the full matrix algebra is. -/
theorem czyReduced_adjoin_ne_top : Algebra.adjoin ℂ (Set.range czyReduced) ≠ ⊤ := by
  intro h
  exact czyReduced_not_starClosed fun i => h ▸ Algebra.mem_top

/-! ### Indecomposability of the virtual space -/

/-- Every matrix commuting with the two nonzero letters of `A₀` is of the form `aI + bE₀₂`.
This calculation establishes the indecomposability asserted in arXiv:2509.03600, Section II,
main.tex line 240. -/
theorem czyReduced_commutant_form (P : Matrix (Fin 3) (Fin 3) ℂ)
    (h₀ : P * czyReduced 0 = czyReduced 0 * P)
    (h₁ : P * czyReduced 3 = czyReduced 3 * P) :
    P = !![P 2 2, 0, P 0 2; 0, P 2 2, 0; 0, 0, P 2 2] := by
  have h : ∀ i j, (P * czyReduced 0) i j = (czyReduced 0 * P) i j ∧
      (P * czyReduced 3) i j = (czyReduced 3 * P) i j :=
    fun i j => ⟨congrArg (fun M => M i j) h₀, congrArg (fun M => M i j) h₁⟩
  norm_num [Fin.forall_fin_succ, czyReduced_eq, czyReducedIntMPS,
    complexOfInt, complexOfRing, Matrix.mul_apply, Fin.sum_univ_succ] at h
  ext i j
  fin_cases i <;> fin_cases j <;> simp <;> grind

/-- The commutant of `A₀` has no nontrivial idempotent (arXiv:2509.03600, Section II,
main.tex line 240). -/
theorem czyReduced_commuting_idempotent (P : Matrix (Fin 3) (Fin 3) ℂ)
    (hP : P * P = P) (h : ∀ i, P * czyReduced i = czyReduced i * P) :
    P = 0 ∨ P = 1 := by
  have hform := czyReduced_commutant_form P (h 0) (h 3)
  have ha := congrArg (fun M => (M 2 2, M 0 2)) hP
  rw [hform] at ha
  norm_num [Matrix.mul_apply, Fin.sum_univ_succ] at ha
  have ha01 : P 2 2 = 0 ∨ P 2 2 = 1 := by grind
  have hb : P 0 2 = 0 := by grind
  rcases ha01 with h0 | h1
  · left
    rw [hform, h0, hb]
    ext i j; fin_cases i <;> fin_cases j <;> simp
  · right
    rw [hform, h1, hb]
    ext i j; fin_cases i <;> fin_cases j <;> simp

/-- The virtual space of `A₀` has no nontrivial decomposition into complementary invariant
subspaces. Thus no simultaneous bond similarity can split `A₀` into two nonempty blocks,
even if one block is zero (arXiv:2509.03600, Section II, main.tex line 240). Together with
`czyReduced_adjoin_ne_top`, this excludes every direct sum of injective MPO tensors. -/
theorem czyReduced_invariant_isCompl (V W : Submodule ℂ (Fin 3 → ℂ)) (hc : IsCompl V W)
    (hV : ∀ a x, x ∈ V → (czyReduced a).mulVec x ∈ V)
    (hW : ∀ a x, x ∈ W → (czyReduced a).mulVec x ∈ W) :
    V = ⊥ ∨ W = ⊥ := by
  let p := V.projection W hc
  have hcomm : ∀ a, p * Matrix.toLinAlgEquiv' (czyReduced a) =
      Matrix.toLinAlgEquiv' (czyReduced a) * p := by
    intro a
    refine LinearMap.ext fun x => ?_
    obtain ⟨v, w, rfl, _⟩ := Submodule.existsUnique_add_of_isCompl hc x
    simp [Matrix.mulVec_add, p, Submodule.projection_apply_of_mem_left hc (hV a v v.property),
      Submodule.projection_apply_of_mem_right hc (hW a w w.property)]
  have hp := congrArg LinearMap.toMatrixAlgEquiv'
    (Submodule.isIdempotentElem_projection hc : p * p = p)
  have hcases := czyReduced_commuting_idempotent (LinearMap.toMatrixAlgEquiv' p)
    (by simpa only [map_mul] using hp)
    (fun a => by simpa only [map_mul, LinearMap.toMatrixAlgEquiv'_toLinAlgEquiv']
      using congrArg LinearMap.toMatrixAlgEquiv' (hcomm a))
  have hp01 : p = 0 ∨ p = 1 := by simpa using hcases
  rcases hp01 with h0 | h1
  · left
    simpa [show V.projection W hc = 0 from h0] using (Submodule.range_projection hc).symm
  · right
    simpa [show V.projection W hc = 1 from h1, Module.End.one_eq_id]
      using (Submodule.ker_projection hc).symm

/-! ### The fusion tensor `Y_{0,0}` -/

/-- The integer fusion tensor `Y_{0,0}`, the first three rows of `X_{0,0}` (arXiv:2509.03600,
main.tex lines 700–714). -/
def czyY00Int : Matrix (Fin 3) (Fin 9) ℤ :=
  !![0, 1, 0, 1, 0, 0, 0, 0, 0;
    0, 0, 0, 0, 2, 0, 0, 0, 2;
    0, 0, 0, 0, 0, 2, 0, 2, 0]

theorem czyY00Int_fusion (i k : Fin 2) :
    czyY00Int * mulIntTensor czyReducedIntTensor czyReducedIntTensor i k =
      czyReducedIntTensor i k * czyY00Int := by
  revert i k
  decide

/-- **The one-sided fusion identity** `Y_{0,0} (∑_j A_0^{ij} ⊗ A_0^{jk}) = A_0^{ik} Y_{0,0}`
(arXiv:2509.03600, main.tex lines 249–253, with `Y_{0,0}` from lines 700–714). -/
theorem czyY00_fusion (i k : Fin 2) :
    complexOfInt czyY00Int * MPOTensor.mulTensor czyReducedTensor czyReducedTensor i k =
      czyReducedTensor i k * complexOfInt czyY00Int := by
  rw [show MPOTensor.mulTensor czyReducedTensor czyReducedTensor i k =
      complexOfInt (mulIntTensor czyReducedIntTensor czyReducedIntTensor i k) from
    mulTensor_complexOfRing _ czyReducedIntTensor czyReducedIntTensor i k,
    czyReducedTensor, ← complexOfInt_mul, ← complexOfInt_mul, czyY00Int_fusion]

end CZYCompression
