/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import TNLean.MPS.Examples.CZX.CZXSquare
import TNLean.MPS.Examples.CZY.CZYTensor
import TNLean.MPS.FundamentalTheorem.Reduction.Splitting
import TNLean.MPS.MPDO.BondOneOperator
import TNLean.MPS.MPDO.IdentityTensor
import TNLean.MPS.MPDO.OperatorFromWordTrace

/-!
# CZY: the stacked square as a nonsplit compression onto the identity

**Source.** arXiv:2509.03600, `References/2509.03600/main.tex` lines 219–240: the stacked
bond-four tensor `Ã_0` of two copies of the CZY operator is brought by a change of virtual
basis to `A_0 ⊕ 0` with a non-injective bond-three tensor `A_0`, which "cannot be further
decomposed into a direct sum of injective MPOs"; on periodic boundary conditions it generates
the identity, "as expected from `(U_CZY)² = 1`".

**Formalized here.** The stacked tensor is an instance of the multi-block asymmetric
compression theorem with the single target the bond-one identity tensor `δ` and three zero
slots: in the integer basis `(0,1,1,0), (0,1,0,0), (1,0,0,0), (0,0,0,1)` every letter is upper
triangular, with `δ` on the second diagonal entry and zero on the other three. Consequently the
periodic operator of the stacked tensor is the identity at every length `N ≥ 1`, with no parity
restriction, and `U_N² = 1` for every `N ≥ 1`; at `N = 0` the periodic operator is the trace of
the identity of the bond space, `4`, and not `1`.

Both sitewise intertwiner spaces between the stacked tensor and `δ` vanish. Hence every
compression of the stacked tensor onto `δ` has a nonzero remainder, and the virtual algebra
generated by the stacked letters is not closed under conjugate transposition. This is the
nonsplitting content of the source's indecomposability claim; the associator
`ω(1,1,1) = -1` of the source (main.tex lines 283–294) is not formalized here.

## Main results

* `CZYCompression.czySquare_compression`: the multi-block compression datum.
* `CZYCompression.mpo_czySquare`, `CZYCompression.mpo_czyTensor_mul_self`: the stacked operator
  is the identity and `U_N² = 1`, for every `N ≥ 1`.
* `CZYCompression.mpo_czySquare_zero_ne_one`: the identity fails at `N = 0`.
* `CZYCompression.czySquare_isReduction`: the explicit compression pair
  `W = (0,1,-1,0)`, `V = (0,1,0,0)ᵀ`.
* `CZYCompression.czySquare_evalWord_remainder_eq_zero`: the remainder is nilpotent of length
  four.
* `CZYCompression.czySquare_right_intertwiner_eq_zero`,
  `CZYCompression.czySquare_left_intertwiner_eq_zero`: both sitewise intertwiner spaces vanish.
* `CZYCompression.czySquare_remainder_ne_zero`, `CZYCompression.czySquare_not_starClosed`: no
  compression splits, and the virtual algebra is not star closed.

## References

- [arXiv:2509.03600](https://arxiv.org/abs/2509.03600) -- Y. Liu, A. Molnár, X.-Q. Sun,
  F. Verstraete, K. Kato, L. Lootens, *Trading Mathematical for Physical Simplicity:
  Bialgebraic Structures in Matrix Product Operator Symmetries*
-/

noncomputable section

open scoped Matrix

namespace CZYCompression

open MPSTensor CZXCompression

/-! ### The target and the gauge -/

/-- The single target: the bond-one identity tensor `δ` in the pair-alphabet view. -/
def czySquareTarget : (s : Unit) → MPSTensor 4 (squareDim s) := fun _ => identityMPS

theorem czySquareTarget_eq (s : Unit) (a : Fin 4) :
    czySquareTarget s a = complexOfInt (identityIntMPS a) :=
  identityMPS_eq a

/-- The identity tensor of the CZX files is the general bond-one identity tensor. -/
theorem identityTensor_eq_idTensor : identityTensor = MPOTensor.idTensor 2 := by
  funext i j
  ext a b
  obtain rfl := Subsingleton.elim a b
  fin_cases i <;> fin_cases j <;> simp [identityTensor, identityIntTensor, MPOTensor.idTensor]

/-- The target `δ` is normal: its letter `(0,0)` is the scalar `1`. -/
theorem czySquareTarget_isNormal (s : Unit) : Kraus.IsNormal (czySquareTarget s) :=
  MPOTensor.isNormal_of_bondOne identityTensor 0 0 (by simp [identityTensor, identityIntTensor])

/-- The change of bond coordinates: the inverse of the matrix whose columns are the flag basis
`(0,1,1,0), (0,1,0,0), (1,0,0,0), (0,0,0,1)`. -/
def czySquareGaugeInt : Matrix (Fin 4) (Fin 4) ℤ :=
  !![0, 0, 1, 0; 0, 1, -1, 0; 1, 0, 0, 0; 0, 0, 0, 1]

/-- The flag basis `(0,1,1,0), (0,1,0,0), (1,0,0,0), (0,0,0,1)` as columns. The first vector
spans the intersection of the common kernel and the common image of the letters. -/
def czySquareGaugeInvInt : Matrix (Fin 4) (Fin 4) ℤ :=
  !![0, 0, 1, 0; 1, 1, 0, 0; 1, 0, 0, 0; 0, 0, 0, 1]

theorem czySquareGauge_mul_inv : czySquareGaugeInt * czySquareGaugeInvInt = 1 := by decide

theorem czySquareGaugeInv_mul : czySquareGaugeInvInt * czySquareGaugeInt = 1 := by decide

/-- The gauge of the compression, with the block labelling of the CZX square: the target on
the second coordinate and zero slots on the other three. -/
def czySquareGauge : (Fin 4 → ℂ) ≃ₗ[ℂ] (BlockSpace squareDim oneSlot 3 → ℂ) :=
  gaugeOfRingMatrix (Int.castRingHom ℂ) czxSquareTau czySquareGaugeInt czySquareGaugeInvInt
    czySquareGauge_mul_inv czySquareGaugeInv_mul

/-- The letters in the flag basis: upper triangular, with `δ` on the second diagonal entry. -/
def czySquareConjInt : Fin 4 → Matrix (Fin 4) (Fin 4) ℤ
  | 0 => !![0, 0, 0, 0; 0, 1, -1, 1; 0, 0, 0, 0; 0, 0, 0, 0]
  | 1 => 0
  | 2 => 0
  | 3 => !![0, -1, -1, 1; 0, 1, 1, -1; 0, 0, 0, 0; 0, 0, 0, 0]

theorem czySquare_conj_int (i : Fin 4) :
    czySquareGaugeInt * czySquareInt i * czySquareGaugeInvInt = czySquareConjInt i := by
  revert i
  decide

theorem czySquare_conjMatrix (i : Fin 4) :
    conjMatrix czySquareGauge (czySquare i) =
      (complexOfInt (czySquareConjInt i)).submatrix czxSquareTau czxSquareTau := by
  rw [czySquareGauge, conjMatrix_gaugeOfRingMatrix _ _ _ _ (czySquare_eq i), czySquare_conj_int]

/-! ### The compression datum -/

private theorem czySquare_triangular_int (i : Fin 4)
    (x y : BlockSpace squareDim oneSlot 3) (h : czxSquareOrd y.1 < czxSquareOrd x.1) :
    czySquareConjInt i (czxSquareTau x) (czxSquareTau y) = 0 := by
  revert i x y
  decide

private theorem czySquare_matched_int (i : Fin 4) (p q : Fin 1) :
    czySquareConjInt i (czxSquareTau ⟨Sum.inl oneSlotMem, p⟩)
        (czxSquareTau ⟨Sum.inl oneSlotMem, q⟩) = identityIntMPS i p q := by
  obtain rfl : p = 0 := Subsingleton.elim p 0
  obtain rfl : q = 0 := Subsingleton.elim q 0
  revert i
  decide

private theorem czySquare_unmatched_int (i : Fin 4) (t : Fin 3) (p q : Fin 1) :
    czySquareConjInt i (czxSquareTau ⟨Sum.inr t, p⟩) (czxSquareTau ⟨Sum.inr t, q⟩) = 0 := by
  revert i t p q
  decide

/-- **The stacked CZY tensor as a multi-block compression onto `δ`**, with one matched slot and
three zero slots (arXiv:2509.03600, main.tex lines 219–240, read through the multi-block
asymmetric compression theorem). -/
def czySquare_compression : MultiBlockCompression czySquare oneSlot czySquareTarget :=
  MultiBlockCompression.ofRing (Int.castRingHom ℂ) czxSquareOrd czxSquareTau czySquareGauge
    czySquareConjInt czySquare_conjMatrix (fun _ => identityIntMPS) czySquareTarget_eq
    czySquare_triangular_int
    (fun i s p q => by
      obtain rfl := eq_oneSlotMem s
      exact czySquare_matched_int i p q)
    czySquare_unmatched_int

/-! ### The periodic operator -/

/-- The stacked tensor has the word traces of `δ` on every nonempty word. -/
theorem czySquare_trace_evalWord (w : List (Fin 4)) (hw : w ≠ []) :
    Matrix.trace (Kraus.evalWord czySquare w) =
      Matrix.trace (Kraus.evalWord identityMPS w) := by
  rw [czySquare_compression.trace_evalWord_eq_sum w hw, Finset.sum_singleton]
  rfl

/-- **The stacked CZY operator is the identity at every positive length** (arXiv:2509.03600,
main.tex line 240). The source's claim holds for all `N ≥ 1`, odd lengths included. -/
theorem mpo_czySquare (N : ℕ) (hN : 0 < N) :
    MPOTensor.mpo (MPOTensor.mulTensor czyTensor czyTensor) N = 1 := by
  rw [MPOTensor.mpo_eq_of_trace_evalWord _ identityTensor czySquare_trace_evalWord N hN,
    identityTensor_eq_idTensor, MPOTensor.mpo_idTensor]

/-- **The CZY operator squares to the identity** at every positive length:
`(U_CZY)² = 1` (arXiv:2509.03600, main.tex line 240). -/
theorem mpo_czyTensor_mul_self (N : ℕ) (hN : 0 < N) :
    MPOTensor.mpo czyTensor N * MPOTensor.mpo czyTensor N = 1 := by
  rw [← MPOTensor.mpo_mulTensor, mpo_czySquare N hN]

/-- At length zero the periodic operator of the stacked tensor is the trace of the identity of
the four-dimensional bond space, so it is not the identity: the restriction `N ≥ 1` in
`mpo_czySquare` is sharp. -/
theorem mpo_czySquare_zero_ne_one :
    MPOTensor.mpo (MPOTensor.mulTensor czyTensor czyTensor) 0 ≠ 1 := by
  intro h
  have h0 := congrFun (congrFun h finZeroElim) finZeroElim
  simp [MPOTensor.mpoMatrixEntry, Matrix.trace_one] at h0

/-! ### The compression pair and the remainder -/

/-- The left compression witness `W = (0,1,-1,0)`, the second row of the gauge. -/
def czySquareLeft : Matrix (Fin 1) (Fin 4) ℂ := !![0, 1, -1, 0]

/-- The right compression witness `V = (0,1,0,0)ᵀ`, the second flag vector. -/
def czySquareRight : Matrix (Fin 4) (Fin 1) ℂ := !![0; 1; 0; 0]

theorem czySquare_left_eq : czySquare_compression.left oneSlotMem = czySquareLeft := by
  rw [MultiBlockCompression.left_gaugeOfMatrix czySquare_compression
    (hG := complexOfRing_mul_eq_one _ czySquareGauge_mul_inv)
    (hG' := complexOfRing_mul_eq_one _ czySquareGaugeInv_mul) rfl]
  ext i y
  change ((czySquareGaugeInt 1 y : ℤ) : ℂ) = czySquareLeft i y
  fin_cases i
  fin_cases y <;> norm_num [czySquareGaugeInt, czySquareLeft]

theorem czySquare_right_eq : czySquare_compression.right oneSlotMem = czySquareRight := by
  rw [MultiBlockCompression.right_gaugeOfMatrix czySquare_compression
    (hG := complexOfRing_mul_eq_one _ czySquareGauge_mul_inv)
    (hG' := complexOfRing_mul_eq_one _ czySquareGaugeInv_mul) rfl]
  ext x j
  change ((czySquareGaugeInvInt x 1 : ℤ) : ℂ) = czySquareRight x j
  fin_cases j
  fin_cases x <;> norm_num [czySquareGaugeInvInt, czySquareRight]

/-- **The explicit compression pair**: `W = (0,1,-1,0)` and `V = (0,1,0,0)ᵀ` compress every
word of the stacked tensor onto the corresponding word of `δ`. -/
theorem czySquare_isReduction :
    IsReduction czySquare (czySquareTarget ()) czySquareLeft czySquareRight := by
  have h := czySquare_compression.isReduction oneSlotMem
  rwa [czySquare_left_eq, czySquare_right_eq] at h

/-- **Nilpotency of the remainder**, with the length `1 + 3 = 4` of the compression theorem. -/
theorem czySquare_evalWord_remainder_eq_zero (w : List (Fin 4)) (hw : 4 ≤ w.length) :
    Kraus.evalWord
      (fun i => czySquare i - czySquareRight * czySquareTarget () i * czySquareLeft) w = 0 := by
  have hsum : (fun i => czySquare i - czySquareRight * czySquareTarget () i * czySquareLeft) =
      czySquare_compression.remainder := by
    funext i
    rw [MultiBlockCompression.remainder_oneSlot _ oneSlotMem, czySquare_left_eq,
      czySquare_right_eq]
  rw [hsum]
  refine czySquare_compression.evalWord_remainder_eq_zero w ?_
  change (1 : ℕ) + 3 ≤ w.length
  omega

/-- **The dimension count** `4 = 1 + 3`. -/
theorem czySquare_dim_eq : (4 : ℕ) = ∑ s ∈ oneSlot, squareDim s + 3 :=
  czySquare_compression.dim_eq

/-! ### Absence of sitewise intertwiners -/

/-- **No nonzero right sitewise intertwiner** `Ã_0^i X = X δ^i`. -/
theorem czySquare_right_intertwiner_eq_zero (X : Matrix (Fin 4) (Fin 1) ℂ)
    (h : ∀ i, czySquare i * X = X * czySquareTarget () i) : X = 0 :=
  right_intertwiner_eq_zero_of_ringCertificate (Int.castRingHom ℂ) czySquareInt czySquare_eq
    identityIntMPS (czySquareTarget_eq ()) ![(0, 0, 0), (0, 2, 0), (0, 3, 0), (3, 1, 0)]
    (Matrix.of fun x => ![![-1, 0, 0, 0], ![0, 0, 0, -1], ![0, -1, 0, 0], ![0, 0, -1, 0]] x.1)
    (c := 1) (by norm_num) (by decide) X h

/-- **No nonzero left sitewise intertwiner** `Y Ã_0^i = δ^i Y`. -/
theorem czySquare_left_intertwiner_eq_zero (Y : Matrix (Fin 1) (Fin 4) ℂ)
    (h : ∀ i, Y * czySquare i = czySquareTarget () i * Y) : Y = 0 :=
  left_intertwiner_eq_zero_of_ringCertificate (Int.castRingHom ℂ) czySquareInt czySquare_eq
    identityIntMPS (czySquareTarget_eq ()) ![(0, 0, 0), (0, 2, 0), (0, 3, 0), (3, 0, 0)]
    (Matrix.of fun x =>
      ![![-1, 1, 0, -1], ![-1, -1, 0, 1], ![1, -1, 0, -1], ![-1, -1, -2, 1]] x.1)
    (c := 2) (by norm_num) (by decide) Y h

/-- **No compression of the stacked tensor onto `δ` splits**: the remainder of every
multi-block compression is nonzero. -/
theorem czySquare_remainder_ne_zero
    (P : MultiBlockCompression czySquare oneSlot czySquareTarget) : P.remainder ≠ 0 :=
  P.remainder_ne_zero_of_forall_right_intertwiner_eq_zero oneSlotMem Nat.one_pos
    czySquare_right_intertwiner_eq_zero

/-- **The virtual algebra of the stacked tensor is not star closed.** A star-closed algebra
would give a nonzero sitewise right intertwiner with the normal target `δ`. -/
theorem czySquare_not_starClosed :
    ¬ ∀ i, (czySquare i)ᴴ ∈ Algebra.adjoin ℂ (Set.range czySquare) :=
  MPSTensor.not_forall_conjTranspose_mem_adjoin_of_forall_right_intertwiner_eq_zero
    oneSlot czySquareTarget (fun s _ => czySquareTarget_isNormal s)
    (fun _ _ => Nat.one_pos) czySquare
    (fun w hw => czySquare_compression.trace_evalWord_eq_sum w hw) oneSlotMem
    czySquare_right_intertwiner_eq_zero

end CZYCompression
