import MPSLean.MPS.BasisNormal
import MPSLean.MPS.MPVOverlap
import MPSLean.Algebra.GramMatrixLI

import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.Topology.Algebra.Star

/-!
# Basis normal tensors (BNT)

This module introduces the basic infrastructure for **basis normal tensors** (BNT), as in
Def. 4.2 of arXiv:2011.12127.

A BNT decomposition of a tensor `A_total` is a finite family of normal tensors which
1. are normal individually,
2. span the MPV family generated by `A_total`, and
3. whose MPV states are eventually linearly independent.

We also provide a convenient lemma: if pairwise overlaps of a finite family of MPV states
converge to the Kronecker delta (i.e. the Gram matrix tends to the identity), then the
states are eventually linearly independent.
-/

open scoped BigOperators InnerProductSpace
open Filter

namespace MPSTensor

/--
`IsBNT A_total g dim A_bnt` means that the family `A_bnt` is a **basis normal tensor** (BNT)
for `A_total` in the sense of Def. 4.2 of arXiv:2011.12127.

Informally, `A_bnt` is a finite family of normal tensors which spans the MPV family of `A_total`
and whose MPV states become linearly independent for large enough system size.
-/
structure IsBNT {d Dtot : ℕ} (A_total : MPSTensor d Dtot)
    (g : ℕ) (dim : Fin g → ℕ) (A_bnt : (j : Fin g) → MPSTensor d (dim j)) : Prop where
  /-- Each basis tensor is normal. -/
  normal : ∀ j, IsNormal (A_bnt j)
  /-- At each system size, `A_total`'s MPV is a linear combination of the basis MPVs. -/
  spans_mpv : ∀ N : ℕ, ∃ c : Fin g → ℂ, ∀ σ : Fin N → Fin d,
      mpv A_total σ = ∑ j : Fin g, c j * mpv (A_bnt j) σ
  /-- For large enough sizes, the corresponding MPV states are linearly independent. -/
  eventually_li : ∃ N0 : ℕ, ∀ N > N0,
      LinearIndependent ℂ (fun j : Fin g => mpvState (d := d) (A_bnt j) N)

/--
If the MPV overlaps of a finite family `A j` converge to an orthonormal Gram matrix,
then the MPV states `mpvState (A j) N` are eventually linearly independent.

This is a convenient wrapper around
`MPSTensor.eventually_linearIndependent_of_gram_tendsto_id`.
-/
theorem eventually_linearIndependent_of_overlap_tendsto_orthonormal
    {d : ℕ} {g : ℕ} {dim : Fin g → ℕ}
    (A : (j : Fin g) → MPSTensor d (dim j))
    (h_self : ∀ j,
      Tendsto (fun N => mpvOverlap (d := d) (A j) (A j) N) atTop (nhds (1 : ℂ)))
    (h_cross : ∀ i j, i ≠ j →
      Tendsto (fun N => mpvOverlap (d := d) (A i) (A j) N) atTop (nhds (0 : ℂ))) :
    ∀ᶠ N in atTop,
      LinearIndependent ℂ (fun j : Fin g => mpvState (d := d) (A j) N) := by
  classical
  -- Work in a fixed Hilbert space containing all `MPVSpace d N` as orthogonal summands.
  let V : Type := lp (fun N : ℕ => MPVSpace d N) 2
  -- Embed each `mpvState (A j) N : MPVSpace d N` into the `N`-th summand of `V`.
  let v : Fin g → ℕ → V := fun j N => lp.single 2 N (mpvState (d := d) (A j) N)
  -- First show convergence of the inner products `⟪mpvState (A i) N, mpvState (A j) N⟫`.
  have hInnerState : ∀ i j : Fin g,
      Tendsto (fun N =>
        ⟪mpvState (d := d) (A i) N, mpvState (d := d) (A j) N⟫_ℂ)
        atTop (nhds (if i = j then (1 : ℂ) else 0)) := by
    intro i j
    by_cases h : i = j
    · subst h
      -- `mpvOverlap = star mpvInner`, so `.star` converts the limit.
      have h1 : Tendsto (fun N => star (mpvInner (d := d) (A i) (A i) N)) atTop (nhds 1) :=
        (h_self i).congr fun N =>
          mpvOverlap_eq_star_mpvInner (A := A i) (B := A i) N
      simpa [mpvInner] using h1.star
    · have h1 : Tendsto (fun N => star (mpvInner (d := d) (A i) (A j) N)) atTop (nhds 0) :=
        (h_cross i j h).congr fun N =>
          mpvOverlap_eq_star_mpvInner (A := A i) (B := A j) N
      simpa [mpvInner, if_neg h] using h1.star
  -- Translate the Gram convergence to the embedded vectors `v` in the fixed space `V`.
  have hGram : ∀ i j : Fin g,
      Tendsto (fun N => ⟪v i N, v j N⟫_ℂ)
        atTop (nhds (if i = j then (1 : ℂ) else 0)) := fun i j =>
    -- `⟪v i N, v j N⟫ = ⟪lp.single 2 N (mpvState A i N), ...⟫ = ⟪mpvState A i N, ...⟫`
    -- by `lp.inner_single_left` and `lp.single_apply_self`.
    (hInnerState i j).congr fun N => by
      simp only [v]
      rw [lp.inner_single_left, lp.single_apply_self]
  -- Apply the Gram-matrix criterion in the fixed inner product space `V`.
  have hLI_emb : ∀ᶠ N in atTop, LinearIndependent ℂ (fun j : Fin g => v j N) :=
    MPSTensor.eventually_linearIndependent_of_gram_tendsto_id (v := v) hGram
  -- Pull back linear independence along the linear map `lp.lsingle 2 N`.
  refine hLI_emb.mono ?_
  intro N hN
  -- `lp.lsingle 2 N` is the linear map `MPVSpace d N →ₗ[ℂ] V` sending `x` to `lp.single 2 N x`.
  let fN : MPVSpace d N →ₗ[ℂ] V := lp.lsingle (𝕜 := ℂ) (E := fun N : ℕ => MPVSpace d N) 2 N
  -- Rewrite the embedded family as `fN ∘ mpvState` and apply `LinearIndependent.of_comp`.
  have hN' : LinearIndependent ℂ (fun j : Fin g => fN (mpvState (d := d) (A j) N)) := by
    simpa [v, fN, lp.lsingle_apply] using hN
  exact LinearIndependent.of_comp fN hN'

end MPSTensor
