/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.Channel.Peripheral.CyclicDecomposition.PeripheralUnitary
import TNLean.Channel.Peripheral.CyclicDecomposition.CyclicProjections

/-!
# Cyclic decompositions for irreducible Schwarz maps

This file combines the peripheral-unitary and cyclic-projection constructions to
produce the cyclic decomposition promised by Wolf Theorem 6.6.

## Main statements

* `exists_cyclic_decomposition_of_irreducible_schwarz` — cyclic
  decomposition for irreducible unital Schwarz transfer maps.

## References

* [M. Wolf, *Quantum Channels & Operations: Guided Tour*, Theorem 6.6]
-/

open scoped Matrix ComplexOrder MatrixOrder BigOperators
open Matrix Finset Complex

namespace MPSTensor

/-- Wolf Theorem 6.6 for transfer maps of irreducible unital Schwarz maps,
assuming the peripheral spectrum is generated by a primitive `m`-th root `γ`. -/
theorem exists_cyclic_decomposition_of_irreducible_schwarz
    {r D m : ℕ} [NeZero D] [NeZero m]
    (K : Fin r → MatrixAlg D)
    (hUnital : KadisonSchwarz.IsUnitalKraus (d := r) (D := D) K)
    (ρ : MatrixAlg D) (hρ : ρ.PosDef)
    (hρfix : Kraus.adjointMap K ρ = ρ)
    (hIrr : IsIrreducibleMap (transferMap (d := r) (D := D) K))
    {γ : ℂ} (hγprim : IsPrimitiveRoot γ m)
    (hperiph : peripheralEigenvalues (transferMap (d := r) (D := D) K) =
      Set.range (fun j : Fin m => γ ^ (j : ℕ))) :
    ∃ U : Matrix.unitaryGroup (Fin D) ℂ,
      ∃ P : Fin m → MatrixAlg D,
        transferMap (d := r) (D := D) K (U : MatrixAlg D) = γ • (U : MatrixAlg D) ∧
        (∀ k : ℕ,
          transferMap (d := r) (D := D) K ((U : MatrixAlg D) ^ k) =
            γ ^ k • ((U : MatrixAlg D) ^ k)) ∧
        ((U : MatrixAlg D) ^ m = 1) ∧
        (∀ k : Fin m, IsOrthogonalProjection (P k)) ∧
        (∑ k : Fin m, P k = 1) ∧
        ((U : MatrixAlg D) = ∑ k : Fin m, γ ^ (k : ℕ) • P k) ∧
        (∀ k : Fin m, transferMap (d := r) (D := D) K (P (k + 1)) = P k) := by
  have hγ : γ ∈ peripheralEigenvalues (transferMap (d := r) (D := D) K) := by
    rw [hperiph]
    by_cases hm1 : m = 1
    · subst hm1
      simp only [
        IsPrimitiveRoot.one_right_iff.mp hγprim, Fin.val_eq_zero, pow_zero, Set.range_const,
        Set.mem_singleton_iff
      ]
    · have hm0 : m ≠ 0 := NeZero.ne m
      have hm_gt : 1 < m := Nat.one_lt_iff_ne_zero_and_ne_one.mpr ⟨hm0, hm1⟩
      exact ⟨⟨1, hm_gt⟩, by simp only [pow_one]⟩
  obtain ⟨U, hU, hUm⟩ :=
    exists_normalized_peripheral_unitary_of_irreducible_schwarz
      (K := K) hUnital ρ hρ hρfix hIrr hγprim hγ
  have hPow :
      ∀ k : ℕ,
        transferMap (d := r) (D := D) K ((U : MatrixAlg D) ^ k) =
          γ ^ k • ((U : MatrixAlg D) ^ k) :=
    map_powers_of_peripheral_unitary
      (K := K) hUnital ρ hρ hρfix hγ U hU
  obtain ⟨P, hPproj, hPsum, hUspec, hcyclic⟩ :=
    exists_cyclic_projections_of_peripheral_unitary
      (T := transferMap (d := r) (D := D) K) hγprim U hUm hPow
  exact ⟨U, P, hU, hPow, hUm, hPproj, hPsum, hUspec, hcyclic⟩

end MPSTensor
