/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.PEPS.Examples.CZX
import TNLean.PEPS.OnSiteOperator
import TNLean.MPS.Examples.CZX.CZXReviewTensor
import TNLean.MPS.Examples.CZX.CZXUnitary

/-!
# CZX: the on-site `ℤ₂` symmetry of the CZX PEPS and its boundary matrix product unitary

**Source.** Chen, Liu, Wen 2011 (arXiv:1106.4752), Section "CZX model",
`References/1106.4752/source/dDSPTmodel.tex` lines 283–312: the on-site `ℤ₂` symmetry of the
CZX model is generated by `U_{CZX} = U_X U_{CZ}` with `U_X = X₁X₂X₃X₄` and
`U_{CZ} = CZ₁₂CZ₂₃CZ₃₄CZ₄₁` on the four qubits of a site, and the plaquette ground state is
invariant under it, because between two neighbouring plaquettes `CZ` is applied twice.
Section "CZX model boundary", lines 339–345 and 377–385: on the boundary of a region the
effective symmetry is `∏ X_i ∏ CZ_{i,i+1}` on one effective spin per boundary plaquette, the
matrix product unitary with `T^{0,1} = |0⟩⟨+|`, `T^{1,0} = |1⟩⟨-|`.
Review: arXiv:2011.12127, Appendix A, "The CZX model", `Papers/2011.12127/TN-Review-main.tex`
lines 2502–2516, and "The CZX MPU", lines 2582–2587: the CZX PEPS is invariant under a global
on-site `ℤ₂` symmetry, whose virtual action is the CZX matrix product unitary.

**Formalized here.**
* The on-site operator `U_{CZX}` on the sixteen states of a site, a monomial matrix.
* Invariance of the CZX PEPS on the torus under `U_{CZX}` at every site (widths and heights at
  least three).
* The pulling-through identity of one site tensor: `U_{CZX}` on the physical index equals the
  operator `V = (X ⊗ X) CZ` on each of the four virtual legs, a bond carrying two qubits.
* The boundary identification: on a closed chain of `N` boundary legs whose neighbouring legs
  carry the same qubit of their common plaquette, `V^{⊗ N}` acts as the CZX matrix product
  unitary `X^{⊗ N} D_N` of `CZXCompression.czxTensor`, which is `(-1)^N` times the review's
  operator `O(A)` of `CZXCompression.reviewCZXTensor`.

**Local fix (CZX bond orientation):** the PEPS statements (`czxOnSite_mul_czxSiteTensor` on
the printed site tensor, and the invariance of `czxPEPS`) use the review's tensor with each bond
identifying the pair `(a, b)` at one end with `(b, a)` at the other; contracted with equal labels
at both ends, the printed tensor gives GHZ states on diagonal loops, not the plaquette state.
Documented in `docs/paper-gaps/rmp_peps_czx_bond_orientation.tex`.

**Local fix (review CZX normalization):** the bridge
`onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding_review` uses the review's tensor with
the printed matrices `A^{01}`, `A^{10}` (lines 2588–2591); its bra-ket display at line 2585
carries a factor `2^{-1/2}` per site and does not give a unitary. Documented in
`docs/paper-gaps/mpu_czx_tensor_normalization.tex`.

**Scope restriction (torus size):** the invariance of the PEPS
(`onSiteOperator_czxOnSite_mulVec_stateCoeff_czxPEPS`) is stated for a torus of width and
height at least three sites. On a torus of width two the two horizontal bonds between a pair of
neighbouring sites are one edge of the simple lattice graph, so the four legs of a site are not
four distinct bonds; the source's torus of `2N × 2M` qubits also allows `N, M ∈ {1, 2}`.
Documented in `docs/paper-gaps/rmp_peps_examples_small_torus.tex`.

**Scope restriction (boundary chain):** the identification of the boundary action is stated
for a closed chain of legs subject to the plaquette constraint that the PEPS imposes on the
legs around a region, not for the boundary of a region of the torus PEPS; that the
contraction of a region is supported on this subspace is not formalized. Documented in
`docs/paper-gaps/rmp_peps_czx_boundary_chain.tex`.

## Main definitions

* `TNLean.PEPS.czxSiteFlip`, `TNLean.PEPS.czxCZExponent`, `TNLean.PEPS.czxOnSite`: the on-site
  symmetry `U_{CZX} = U_X U_{CZ}`.
* `TNLean.PEPS.czxLegFlip`, `TNLean.PEPS.czxLegPhase`, `TNLean.PEPS.czxLegOperator`: the
  operator `(X ⊗ X) CZ` on one virtual leg.
* `TNLean.PEPS.czxBoundaryLegs`, `TNLean.PEPS.czxBoundaryEmbedding`: the closed chain of
  boundary legs carrying the effective spins.

## Main results

* `TNLean.PEPS.onSiteOperator_czxOnSite_mulVec_stateCoeff_czxPEPS`: the CZX PEPS is invariant.
* `TNLean.PEPS.czxOnSite_mul_czxSiteTensor`: the pulling-through identity.
* `TNLean.PEPS.onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding`,
  `TNLean.PEPS.czxBoundaryEmbedding_conjTranspose_mul_onSiteOperator_mul`,
  `TNLean.PEPS.onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding_review`: the boundary
  action is the CZX matrix product unitary.

## References

- [arXiv:1106.4752](https://arxiv.org/abs/1106.4752) -- X. Chen, Z.-X. Liu, X.-G. Wen,
  *Two-dimensional symmetry-protected topological orders and their protected gapless edge
  excitations*
- [arXiv:2011.12127](https://arxiv.org/abs/2011.12127) -- J. I. Cirac, D. Pérez-García,
  N. Schuch, F. Verstraete, *Matrix product states and projected entangled pair states:
  Concepts, symmetries, theorems*
-/

open scoped BigOperators Matrix
open Matrix

namespace TNLean
namespace PEPS

/-! ### The on-site symmetry -/

/-- The Pauli `X` on each of the four qubits of a site. -/
def czxSiteFlip : Equiv.Perm (Fin 16) :=
  czxQubits.permCongr
    ((Fin.revPerm.prodCongr Fin.revPerm).prodCongr (Fin.revPerm.prodCongr Fin.revPerm))

@[simp] theorem czxTopLeft_czxSiteFlip (s : Fin 16) :
    czxTopLeft (czxSiteFlip s) = (czxTopLeft s).rev := by
  simp [czxSiteFlip, czxTopLeft, Equiv.permCongr_apply]

@[simp] theorem czxTopRight_czxSiteFlip (s : Fin 16) :
    czxTopRight (czxSiteFlip s) = (czxTopRight s).rev := by
  simp [czxSiteFlip, czxTopRight, Equiv.permCongr_apply]

@[simp] theorem czxBottomRight_czxSiteFlip (s : Fin 16) :
    czxBottomRight (czxSiteFlip s) = (czxBottomRight s).rev := by
  simp [czxSiteFlip, czxBottomRight, Equiv.permCongr_apply]

@[simp] theorem czxBottomLeft_czxSiteFlip (s : Fin 16) :
    czxBottomLeft (czxSiteFlip s) = (czxBottomLeft s).rev := by
  simp [czxSiteFlip, czxBottomLeft, Equiv.permCongr_apply]

@[simp] theorem czxSiteFlip_czxQubits (i j k l : Fin 2) :
    czxSiteFlip (czxQubits ((i, j), (k, l))) = czxQubits ((i.rev, j.rev), (k.rev, l.rev)) := by
  simp [czxSiteFlip, Equiv.permCongr_apply]

theorem czxSiteFlip_czxSiteFlip (s : Fin 16) : czxSiteFlip (czxSiteFlip s) = s := by
  obtain ⟨⟨⟨i, j⟩, ⟨k, l⟩⟩, rfl⟩ := czxQubits.surjective s
  simp

theorem czxSiteFlip_symm : czxSiteFlip.symm = czxSiteFlip :=
  Equiv.ext fun s => by rw [Equiv.symm_apply_eq, czxSiteFlip_czxSiteFlip]

/-- The exponent of the phase of `U_{CZ} = CZ₁₂CZ₂₃CZ₃₄CZ₄₁` on the state `|ijkl⟩` of a site,
`ij + jk + kl + li`. -/
def czxCZExponent (s : Fin 16) : ℕ :=
  (czxTopLeft s).val * (czxTopRight s).val + (czxTopRight s).val * (czxBottomRight s).val +
    (czxBottomRight s).val * (czxBottomLeft s).val +
      (czxBottomLeft s).val * (czxTopLeft s).val

/-- Source: arXiv:1106.4752, `References/1106.4752/source/dDSPTmodel.tex` lines 283–294. The
on-site symmetry `U_{CZX} = U_X U_{CZ}` of a site: first the controlled-`Z` gates on the four
pairs of neighbouring qubits of the site, then the Pauli `X` on each qubit. -/
noncomputable def czxOnSite : Matrix (Fin 16) (Fin 16) ℂ :=
  Matrix.monomial czxSiteFlip 1 * Matrix.diagonal fun s => (-1 : ℂ) ^ czxCZExponent s

/-- `U_{CZX}` is the monomial matrix that flips all four qubits with the controlled-`Z` sign of
the input. -/
theorem czxOnSite_eq_monomial :
    czxOnSite = Matrix.monomial czxSiteFlip fun s => (-1 : ℂ) ^ czxCZExponent s := by
  ext t s
  simp [czxOnSite, Matrix.mul_diagonal, Matrix.monomial_apply]

/-! ### Invariance of the CZX PEPS -/

section Torus

variable {width height : ℕ} [NeZero width] [NeZero height]

/-- On a plaquette-constant configuration of the torus, the product of the controlled-`Z` signs
of all sites is `1`: each pair of neighbouring plaquettes meets at two sites, and their
controlled-`Z` gates cancel (arXiv:1106.4752, `References/1106.4752/source/dDSPTmodel.tex`
line 312). -/
theorem prod_neg_one_pow_czxCZExponent (σ : TorusVertex width height → Fin 16)
    (h : ∀ v : TorusVertex width height, czxTopRight (σ v) = czxTopLeft (σ (v.1 + 1, v.2)) ∧
      czxTopRight (σ v) = czxBottomRight (σ (v.1, v.2 + 1)) ∧
      czxTopRight (σ v) = czxBottomLeft (σ (v.1 + 1, v.2 + 1))) :
    ∏ v, (-1 : ℂ) ^ czxCZExponent (σ v) = 1 := by
  set P : TorusVertex width height → ℕ := fun v => (czxTopRight (σ v)).val with hP
  have htl : ∀ v : TorusVertex width height, (czxTopLeft (σ v)).val = P (v.1 - 1, v.2) := by
    intro v
    have := (h (v.1 - 1, v.2)).1
    simp only [sub_add_cancel] at this
    simp [hP, this]
  have hbr : ∀ v : TorusVertex width height, (czxBottomRight (σ v)).val = P (v.1, v.2 - 1) := by
    intro v
    have := (h (v.1, v.2 - 1)).2.1
    simp only [sub_add_cancel] at this
    simp [hP, this]
  have hbl : ∀ v : TorusVertex width height,
      (czxBottomLeft (σ v)).val = P (v.1 - 1, v.2 - 1) := by
    intro v
    have := (h (v.1 - 1, v.2 - 1)).2.2
    simp only [sub_add_cancel] at this
    simp [hP, this]
  have hexp : ∀ v : TorusVertex width height, czxCZExponent (σ v) =
      P (v.1 - 1, v.2) * P v + P v * P (v.1, v.2 - 1) +
        P (v.1, v.2 - 1) * P (v.1 - 1, v.2 - 1) + P (v.1 - 1, v.2 - 1) * P (v.1 - 1, v.2) := by
    intro v
    simp only [czxCZExponent, htl, hbr, hbl]
    rfl
  -- the third and fourth sums are the first two, shifted down and to the left
  have h3 : ∑ v : TorusVertex width height, P (v.1, v.2 - 1) * P (v.1 - 1, v.2 - 1) =
      ∑ v : TorusVertex width height, P (v.1 - 1, v.2) * P v :=
    Fintype.sum_equiv ((Equiv.refl _).prodCongr (Equiv.subRight 1)) _ _ fun ⟨x, y⟩ => by
      simp only [Equiv.prodCongr_apply, Prod.map_apply, Equiv.refl_apply, Equiv.subRight_apply]
      ring
  have h4 : ∑ v : TorusVertex width height, P (v.1 - 1, v.2 - 1) * P (v.1 - 1, v.2) =
      ∑ v : TorusVertex width height, P v * P (v.1, v.2 - 1) :=
    Fintype.sum_equiv ((Equiv.subRight 1).prodCongr (Equiv.refl _)) _ _ fun ⟨x, y⟩ => by
      simp only [Equiv.prodCongr_apply, Prod.map_apply, Equiv.refl_apply, Equiv.subRight_apply]
      ring
  rw [Finset.prod_pow_eq_pow_sum]
  simp only [hexp, Finset.sum_add_distrib, h3, h4]
  rw [show ∀ a b : ℕ, a + b + a + b = 2 * (a + b) from fun a b => by ring, pow_mul]
  simp

variable [Fact (1 < width)] [Fact (1 < height)] [Fact (2 < width)] [Fact (2 < height)]

/-- Source: arXiv:2011.12127, `Papers/2011.12127/TN-Review-main.tex` lines 2502–2516, and
arXiv:1106.4752, `References/1106.4752/source/dDSPTmodel.tex` lines 310–312: the CZX PEPS is
invariant under the on-site symmetry `U_{CZX}` applied at every site. Stated for width and
height at least three (the module's scope restriction on the torus size). -/
theorem onSiteOperator_czxOnSite_mulVec_stateCoeff_czxPEPS :
    onSiteOperator czxOnSite *ᵥ stateCoeff (czxPEPS width height) =
      stateCoeff (czxPEPS width height) := by
  rw [czxOnSite_eq_monomial, onSiteOperator_monomial, Matrix.monomial_mulVec]
  funext σ'
  set σ := (Equiv.piCongrRight fun _ : TorusVertex width height => czxSiteFlip).symm σ' with hσ
  have hσ' : σ' = fun v => czxSiteFlip (σ v) := by
    funext v
    simp [hσ, czxSiteFlip_symm, Equiv.piCongrRight_symm_apply, czxSiteFlip_czxSiteFlip]
  rw [hσ', stateCoeff_czxPEPS, stateCoeff_czxPEPS, Finset.prod_boole, Finset.prod_boole]
  simp only [czxTopLeft_czxSiteFlip, czxTopRight_czxSiteFlip, czxBottomRight_czxSiteFlip,
    czxBottomLeft_czxSiteFlip, Fin.rev_inj]
  split_ifs with hc
  · rw [mul_one]
    exact prod_neg_one_pow_czxCZExponent σ fun v => hc v (Finset.mem_univ v)
  · rw [mul_zero]

end Torus

/-! ### Pulling the symmetry through one site tensor -/

/-- The Pauli `X` on both qubits of a bond. -/
def czxLegFlip : Equiv.Perm (Fin 4) :=
  czxBond.permCongr (Fin.revPerm.prodCongr Fin.revPerm)

@[simp] theorem czxLegFlip_czxBond (a b : Fin 2) :
    czxLegFlip (czxBond (a, b)) = czxBond (a.rev, b.rev) := by
  simp [czxLegFlip, Equiv.permCongr_apply]

/-- The controlled-`Z` sign `(-1)^{ab}` of the bond state `|ab⟩`. -/
def czxLegPhase (x : Fin 4) : ℂ :=
  (-1 : ℂ) ^ ((czxBond.symm x).1.val * (czxBond.symm x).2.val)

@[simp] theorem czxLegPhase_czxBond (a b : Fin 2) :
    czxLegPhase (czxBond (a, b)) = (-1 : ℂ) ^ (a.val * b.val) := by
  simp [czxLegPhase]

/-- The operator `V = (X ⊗ X) CZ` on the two qubits carried by one virtual leg. -/
noncomputable def czxLegOperator : Matrix (Fin 4) (Fin 4) ℂ :=
  Matrix.monomial czxLegFlip czxLegPhase

/-- Source: arXiv:2011.12127, `Papers/2011.12127/TN-Review-main.tex` lines 1462–1466 (the
pulling-through of an on-site symmetry to the virtual level) and lines 2513–2516: the on-site
symmetry `U_{CZX}` applied to the physical index of the CZX tensor equals the operator
`V = (X ⊗ X) CZ` applied to each of its four virtual legs,
`∑_s (U_{CZX})_{s' s} A_{t r b l}^{s} = ∑_{t' r' b' l'} A_{t' r' b' l'}^{s'} V_{t' t} V_{r' r}
V_{b' b} V_{l' l}`, the right side written out for the monomial matrix `V`. -/
theorem czxOnSite_mul_czxSiteTensor (t r b l : Fin 4) (s' : Fin 16) :
    ∑ s, czxOnSite s' s * czxSiteTensor t r b l s =
      czxLegPhase t * czxLegPhase r * czxLegPhase b * czxLegPhase l *
        czxSiteTensor (czxLegFlip t) (czxLegFlip r) (czxLegFlip b) (czxLegFlip l) s' := by
  rw [czxOnSite_eq_monomial, Finset.sum_eq_single (czxSiteFlip s')]
  · obtain ⟨⟨⟨i, j⟩, ⟨k, m⟩⟩, rfl⟩ := czxQubits.surjective s'
    obtain ⟨⟨t₁, t₂⟩, rfl⟩ := czxBond.surjective t
    obtain ⟨⟨r₁, r₂⟩, rfl⟩ := czxBond.surjective r
    obtain ⟨⟨b₁, b₂⟩, rfl⟩ := czxBond.surjective b
    obtain ⟨⟨l₁, l₂⟩, rfl⟩ := czxBond.surjective l
    simp only [Matrix.monomial_apply, czxSiteFlip_czxQubits,
      czxSiteTensor, czxLegFlip_czxBond, czxLegPhase_czxBond, czxCZExponent, czxTopLeft,
      czxTopRight, czxBottomRight, czxBottomLeft, Equiv.symm_apply_apply,
      EmbeddingLike.apply_eq_iff_eq, Prod.mk.injEq, Fin.rev_eq_iff, mul_ite, mul_one, mul_zero]
    by_cases hc : (t₁ = i.rev ∧ t₂ = j.rev) ∧ (r₁ = j.rev ∧ r₂ = k.rev) ∧
        (b₁ = k.rev ∧ b₂ = m.rev) ∧ l₁ = m.rev ∧ l₂ = i.rev
    · obtain ⟨⟨rfl, rfl⟩, ⟨rfl, rfl⟩, ⟨rfl, rfl⟩, rfl, rfl⟩ := hc
      simp only [Fin.rev_rev, and_self, ↓reduceIte, ← pow_add]
    · simp only [hc, ↓reduceIte]
  · intro s _ hs
    have hne : s' ≠ czxSiteFlip s := fun h => hs (by rw [h, czxSiteFlip_czxSiteFlip])
    simp [Matrix.monomial_apply, hne]
  · simp

/-! ### The boundary matrix product unitary -/

section Boundary

variable (N : ℕ) [NeZero N]

/-- The closed chain of `N` boundary legs carrying the effective spins `c`: leg `m` carries the
qubits `(c m, c (m + 1))` of the two plaquettes it touches, so neighbouring legs carry the same
qubit of their common plaquette (arXiv:1106.4752,
`References/1106.4752/source/dDSPTmodel.tex` lines 339–341). -/
def czxBoundaryLegs (c : Fin N → Fin 2) : Fin N → Fin 4 :=
  fun m => czxBond (c m, c (m + 1))

theorem czxBoundaryLegs_injective : Function.Injective (czxBoundaryLegs N) := by
  intro c c' h
  funext m
  have := congrArg (fun x => (czxBond.symm (x m)).1) h
  simpa [czxBoundaryLegs] using this

/-- The isometric embedding of the effective spins into the configurations of the boundary
legs. -/
def czxBoundaryEmbedding : Matrix (Fin N → Fin 4) (Fin N → Fin 2) ℂ :=
  Matrix.of fun x c => if x = czxBoundaryLegs N c then 1 else 0

theorem czxBoundaryEmbedding_conjTranspose_mul_self :
    (czxBoundaryEmbedding N)ᴴ * czxBoundaryEmbedding N = 1 := by
  ext c c'
  simp only [Matrix.mul_apply, Matrix.conjTranspose_apply, czxBoundaryEmbedding, Matrix.of_apply,
    apply_ite star, star_one, star_zero, ite_mul, one_mul, zero_mul, Finset.sum_ite_eq',
    Finset.mem_univ, ↓reduceIte, Matrix.one_apply]
  simp [(czxBoundaryLegs_injective N).eq_iff]

/-- Source: arXiv:1106.4752, `References/1106.4752/source/dDSPTmodel.tex` lines 339–345 and
377–385; arXiv:2011.12127, `Papers/2011.12127/TN-Review-main.tex` lines 2582–2587: on the
closed chain of boundary legs subject to the plaquette constraint, the virtual action
`V^{⊗ N}` of the on-site symmetry is the CZX matrix product unitary: it intertwines the
embedding of the effective spins with `X^{⊗ N} D_N`, the operator of `czxTensor`. -/
theorem onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding :
    onSiteOperator (V := Fin N) czxLegOperator * czxBoundaryEmbedding N =
      czxBoundaryEmbedding N * MPOTensor.mpo CZXCompression.czxTensor N := by
  rw [czxLegOperator, onSiteOperator_monomial, CZXCompression.mpo_czxTensor]
  ext x c
  simp only [Matrix.mul_apply, Matrix.monomial_apply, czxBoundaryEmbedding, Matrix.of_apply,
    ite_mul, one_mul, zero_mul, mul_ite, mul_one, mul_zero, Finset.sum_ite_eq',
    Finset.mem_univ, ↓reduceIte]
  have hlegs : (Equiv.piCongrRight fun _ : Fin N => czxLegFlip) (czxBoundaryLegs N c) =
      czxBoundaryLegs N (CZXCompression.spinFlip N c) := by
    funext m
    simp [czxBoundaryLegs, CZXCompression.spinFlip_apply]
  have hphase : ∏ m, czxLegPhase (czxBoundaryLegs N c m) =
      (-1 : ℂ) ^ CZXCompression.czExponent c := by
    simp [czxBoundaryLegs, CZXCompression.czExponent, Finset.prod_pow_eq_pow_sum]
  rw [hlegs, hphase]

/-- Source: arXiv:1106.4752, `References/1106.4752/source/dDSPTmodel.tex` lines 339–345: the
effective symmetry on the boundary, the compression of `V^{⊗ N}` to the effective spins, is the
CZX matrix product unitary `X^{⊗ N} D_N`. -/
theorem czxBoundaryEmbedding_conjTranspose_mul_onSiteOperator_mul :
    (czxBoundaryEmbedding N)ᴴ * onSiteOperator (V := Fin N) czxLegOperator *
        czxBoundaryEmbedding N =
      MPOTensor.mpo CZXCompression.czxTensor N := by
  rw [Matrix.mul_assoc, onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding, ← Matrix.mul_assoc,
    czxBoundaryEmbedding_conjTranspose_mul_self, Matrix.one_mul]

/-- Bridge: arXiv:2011.12127, `Papers/2011.12127/TN-Review-main.tex` lines 2582–2591: in terms
of the review's tensor with the printed matrices `A^{01}`, `A^{10}`, the boundary action is
`(-1)^N O(A)`. -/
theorem onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding_review :
    onSiteOperator (V := Fin N) czxLegOperator * czxBoundaryEmbedding N =
      ((-1 : ℂ) ^ N) • (czxBoundaryEmbedding N *
        MPOTensor.mpo CZXCompression.reviewCZXTensor N) := by
  rw [onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding,
    CZXCompression.mpo_reviewCZXTensor_eq_smul, Matrix.mul_smul, smul_smul, ← pow_add,
    ← two_mul, pow_mul]
  simp

end Boundary

end PEPS
end TNLean
