/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.PEPS.Examples.CZXBoundaryChain
import TNLean.PEPS.Examples.CZXRectangleMap
import TNLean.MPS.Examples.CZX.CZXReviewTensor
import TNLean.MPS.Examples.CZX.CZXUnitary

/-!
# CZX: the on-site `ℤ₂` symmetry of the CZX PEPS and its boundary matrix product unitary

**Source.** Chen, Liu, Wen 2011 (arXiv:1106.4752), Section "CZX model",
`References/1106.4752/source/dDSPTmodel.tex` lines 283–312: the on-site `ℤ₂` symmetry of the
CZX model is generated by `U_{CZX} = U_X U_{CZ}` with `U_X = X₁X₂X₃X₄` and
`U_{CZ} = CZ₁₂CZ₂₃CZ₃₄CZ₄₁` on the four qubits of a site, and the plaquette ground state is
invariant under it, because between two neighbouring plaquettes `CZ` is applied twice.
Section "CZX model boundary", lines 339–345 and 377–385: on the boundary of a region the
effective symmetry is `∏ X_i ∏ CZ_{i,i+1}` on one effective spin per boundary plaquette, the
matrix product unitary with `T^{0,1} = |0⟩⟨+|`, `T^{1,0} = |1⟩⟨-|`.
Review: arXiv:2011.12127, Appendix A, "The CZX model", `Papers/2011.12127/TN-Review-main.tex`
lines 2502–2516, and "The CZX MPU", lines 2582–2587: the CZX PEPS is invariant under a global
on-site `ℤ₂` symmetry, whose virtual action is the CZX matrix product unitary.

**Formalized here.**
* The on-site operator `U_{CZX}` on the sixteen states of a site, a monomial matrix.
* Invariance of the CZX PEPS on the torus under `U_{CZX}` at every site (widths and heights at
  least three).
* The pulling-through identity of one site tensor: `U_{CZX}` on the physical index equals the
  operator `V = (X ⊗ X) CZ` on each of the four virtual legs, a bond carrying two qubits.
* The boundary identification: on a closed chain of `N` boundary legs whose neighbouring legs
  carry the same qubit of their common plaquette, `V^{⊗ N}` acts as the CZX matrix product
  unitary `X^{⊗ N} D_N` of `CZXCompression.czxTensor`, which is `(-1)^N` times the review's
  operator `O(A)` of `CZXCompression.reviewCZXTensor`.

* The actual open-region image of a positive proper bounded rectangle has a faithful
  effective plaquette-spin basis, and its physical symmetry intertwines with the review's
  printed CZX matrix product operator. The even perimeter removes the ordering sign.

**Local fix (CZX bond orientation):** the PEPS statements (`czxOnSite_mul_czxSiteTensor` on
the printed site tensor, and the invariance of `czxPEPS`) use the review's tensor with each bond
identifying the pair `(a, b)` at one end with `(b, a)` at the other; contracted with equal labels
at both ends, the printed tensor gives GHZ states on diagonal loops, not the plaquette state.
Documented in `docs/paper-gaps/rmp_peps_czx_bond_orientation.tex`.

**Local fix (review CZX normalization):** the bridge
`onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding_review` uses the review's tensor with
the printed matrices `A^{01}`, `A^{10}` (lines 2588–2591); its bra-ket display at line 2585
carries a factor `2^{-1/2}` per site and does not give a unitary. Documented in
`docs/paper-gaps/mpu_czx_tensor_normalization.tex`.

**Scope restriction (torus size):** the invariance of the PEPS
(`onSiteOperator_czxOnSite_mulVec_stateCoeff_czxPEPS`) is stated for a torus of width and
height at least three sites. On a torus of width two the two horizontal bonds between a pair of
neighbouring sites are one edge of the simple lattice graph, so the four legs of a site are not
four distinct bonds; the source's torus of `2N × 2M` qubits also allows `N, M ∈ {1, 2}`.
Documented in `docs/paper-gaps/rmp_peps_examples_small_torus.tex`.

**Scope restriction (boundary region):** the actual open-region image and its effective
plaquette-spin action are identified for positive proper bounded coordinate rectangles in
`CZXRectangleMap`. The actual reduced-density support and rank, including trace normalization,
are proved in `CZXRectangleDensity`. Its nonzero spectrum and arbitrary nonrectangular regions
remain outside these results. Documented in `docs/paper-gaps/rmp_peps_czx_boundary_chain.tex`.

## Main definitions

* `TNLean.PEPS.czxSiteFlip`, `TNLean.PEPS.czxCZExponent`, `TNLean.PEPS.czxOnSite`: the on-site
  symmetry `U_{CZX} = U_X U_{CZ}`.
* `TNLean.PEPS.czxLegFlip`, `TNLean.PEPS.czxLegPhase`, `TNLean.PEPS.czxLegOperator`: the
  operator `(X ⊗ X) CZ` on one virtual leg.
* `TNLean.PEPS.czxBoundaryLegs`, `TNLean.PEPS.czxBoundaryEmbedding`: the closed chain of
  boundary legs carrying the effective spins.

## Main results

* `TNLean.PEPS.onSiteOperator_czxOnSite_mulVec_stateCoeff_czxPEPS`: the CZX PEPS is invariant.
* `TNLean.PEPS.czxOnSite_mul_czxSiteTensor`: the pulling-through identity.
* `TNLean.PEPS.onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding`,
  `TNLean.PEPS.czxBoundaryEmbedding_conjTranspose_mul_onSiteOperator_mul`,
  `TNLean.PEPS.onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding_review`: the boundary
  action is the CZX matrix product unitary.

* `TNLean.PEPS.regionPhysicalProductMatrix_czxRectangleBoundaryMatrix_review`: the
  printed boundary operator acts on the actual faithful rectangle image.

## References

- [arXiv:1106.4752](https://arxiv.org/abs/1106.4752) -- X. Chen, Z.-X. Liu, X.-G. Wen,
  *Two-dimensional symmetry-protected topological orders and their protected gapless edge
  excitations*
- [arXiv:2011.12127](https://arxiv.org/abs/2011.12127) -- J. I. Cirac, D. Pérez-García,
  N. Schuch, F. Verstraete, *Matrix product states and projected entangled pair states:
  Concepts, symmetries, theorems*
-/

open scoped BigOperators Matrix
open Matrix

namespace TNLean
namespace PEPS

/-! ### The boundary matrix product unitary -/

section Boundary

variable (N : ℕ) [NeZero N]

/-- Source: arXiv:1106.4752, `References/1106.4752/source/dDSPTmodel.tex` lines 339–345 and
377–385; arXiv:2011.12127, `Papers/2011.12127/TN-Review-main.tex` lines 2582–2587: on the
closed chain of boundary legs subject to the plaquette constraint, the virtual action
`V^{⊗ N}` of the on-site symmetry is the CZX matrix product unitary: it intertwines the
embedding of the effective spins with `X^{⊗ N} D_N`, the operator of `czxTensor`. -/
theorem onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding :
    onSiteOperator (V := Fin N) czxLegOperator * czxBoundaryEmbedding N =
      czxBoundaryEmbedding N * MPOTensor.mpo CZXCompression.czxTensor N := by
  rw [czxLegOperator, onSiteOperator_monomial, CZXCompression.mpo_czxTensor]
  ext x c
  simp only [Matrix.mul_apply, Matrix.monomial_apply, czxBoundaryEmbedding, Matrix.of_apply,
    ite_mul, one_mul, zero_mul, mul_ite, mul_one, mul_zero, Finset.sum_ite_eq',
    Finset.mem_univ, ↓reduceIte]
  have hlegs : (Equiv.piCongrRight fun _ : Fin N => czxLegFlip) (czxBoundaryLegs N c) =
      czxBoundaryLegs N (CZXCompression.spinFlip N c) := by
    funext m
    simp [czxBoundaryLegs, CZXCompression.spinFlip_apply]
  have hphase : ∏ m, czxLegPhase (czxBoundaryLegs N c m) =
      (-1 : ℂ) ^ CZXCompression.czExponent c := by
    simp [czxBoundaryLegs, CZXCompression.czExponent, Finset.prod_pow_eq_pow_sum]
  rw [hlegs, hphase]

/-- Source: arXiv:1106.4752, `References/1106.4752/source/dDSPTmodel.tex` lines 339–345: the
effective symmetry on the boundary, the compression of `V^{⊗ N}` to the effective spins, is the
CZX matrix product unitary `X^{⊗ N} D_N`. -/
theorem czxBoundaryEmbedding_conjTranspose_mul_onSiteOperator_mul :
    (czxBoundaryEmbedding N)ᴴ * onSiteOperator (V := Fin N) czxLegOperator *
        czxBoundaryEmbedding N =
      MPOTensor.mpo CZXCompression.czxTensor N := by
  rw [Matrix.mul_assoc, onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding, ← Matrix.mul_assoc,
    czxBoundaryEmbedding_conjTranspose_mul_self, Matrix.one_mul]

/-- Bridge: arXiv:2011.12127, `Papers/2011.12127/TN-Review-main.tex` lines 2582–2591: in terms
of the review's tensor with the printed matrices `A^{01}`, `A^{10}`, the boundary action is
`(-1)^N O(A)`. -/
theorem onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding_review :
    onSiteOperator (V := Fin N) czxLegOperator * czxBoundaryEmbedding N =
      ((-1 : ℂ) ^ N) • (czxBoundaryEmbedding N *
        MPOTensor.mpo CZXCompression.reviewCZXTensor N) := by
  rw [onSiteOperator_czxLegOperator_mul_czxBoundaryEmbedding,
    CZXCompression.mpo_reviewCZXTensor_eq_smul, Matrix.mul_smul, smul_smul, ← pow_add,
    ← two_mul, pow_mul]
  simp

end Boundary

section Rectangle

variable {width height : ℕ} [NeZero width] [NeZero height]
variable [Fact (2 < width)] [Fact (2 < height)]
local instance : Fact (1 < width) := ⟨by have := Fact.out (p := 2 < width); omega⟩
local instance : Fact (1 < height) := ⟨by have := Fact.out (p := 2 < height); omega⟩
variable (xStart yStart w h : ℕ) (hw : 0 < w) (hh : 0 < h)
variable (hx : xStart + w ≤ width) (hy : yStart + h ≤ height)
variable (hwp : w < width) (hhp : h < height) [NeZero (2 * w + 2 * h)]

private theorem regionPhysicalProductMatrix_czxRectangleBoundaryMatrix_czxTensor :
    regionPhysicalProductMatrix (torusContiguousRectangle xStart yStart w h)
        (fun _ => czxOnSite) *
      czxRectangleBoundaryMatrix xStart yStart w h hw hh hx hy hwp hhp =
    czxRectangleBoundaryMatrix xStart yStart w h hw hh hx hy hwp hhp *
      MPOTensor.mpo CZXCompression.czxTensor (2 * w + 2 * h) := by
  change @HMul.hMul _ _ _ Matrix.instHMulOfFintypeOfMulOfAddCommMonoid
    (regionPhysicalProductMatrix (torusContiguousRectangle xStart yStart w h)
      (fun _ => czxOnSite))
    (czxRectangleBoundaryMatrix xStart yStart w h hw hh hx hy hwp hhp) =
    @HMul.hMul _ _ _ Matrix.instHMulOfFintypeOfMulOfAddCommMonoid
      (czxRectangleBoundaryMatrix xStart yStart w h hw hh hx hy hwp hhp)
      (MPOTensor.mpo CZXCompression.czxTensor (2 * w + 2 * h))
  rw [regionPhysicalProductMatrix_czxRectangleBoundaryMatrix_monomial,
    CZXCompression.mpo_czxTensor]
  apply congrArg (fun M =>
    czxRectangleBoundaryMatrix xStart yStart w h hw hh hx hy hwp hhp * M)
  change Matrix.monomial (CZXCompression.spinFlip (2 * w + 2 * h)) _ =
    Matrix.monomial (CZXCompression.spinFlip (2 * w + 2 * h)) _
  apply congrArg (Matrix.monomial (CZXCompression.spinFlip (2 * w + 2 * h)))
  funext c
  simp only [czxBoundaryLegs, czxLegPhase_czxBond, CZXCompression.czExponent,
    Finset.prod_pow_eq_pow_sum]

/-- The printed CZX matrix product unitary is the physical symmetry on the
actual rectangle image, in its faithful effective plaquette-spin coordinates.
The perimeter is even, so the review normalization sign is exactly one.
Source: CLW11, lines 330–345 and 377–385; review Appendix A, lines 2582–2591. -/
theorem regionPhysicalProductMatrix_czxRectangleBoundaryMatrix_review :
    regionPhysicalProductMatrix (torusContiguousRectangle xStart yStart w h)
        (fun _ => czxOnSite) *
      czxRectangleBoundaryMatrix xStart yStart w h hw hh hx hy hwp hhp =
    czxRectangleBoundaryMatrix xStart yStart w h hw hh hx hy hwp hhp *
      MPOTensor.mpo CZXCompression.reviewCZXTensor (2 * w + 2 * h) := by
  change @HMul.hMul _ _ _ Matrix.instHMulOfFintypeOfMulOfAddCommMonoid
    (regionPhysicalProductMatrix (torusContiguousRectangle xStart yStart w h)
      (fun _ => czxOnSite))
    (czxRectangleBoundaryMatrix xStart yStart w h hw hh hx hy hwp hhp) =
    @HMul.hMul _ _ _ Matrix.instHMulOfFintypeOfMulOfAddCommMonoid
      (czxRectangleBoundaryMatrix xStart yStart w h hw hh hx hy hwp hhp)
      (MPOTensor.mpo CZXCompression.reviewCZXTensor (2 * w + 2 * h))
  rw [CZXCompression.mpo_reviewCZXTensor_eq_smul]
  have hsign : (-1 : ℂ) ^ (2 * w + 2 * h) = 1 := by
    simp [pow_add, pow_mul]
  rw [hsign, one_smul]
  exact regionPhysicalProductMatrix_czxRectangleBoundaryMatrix_czxTensor
    xStart yStart w h hw hh hx hy hwp hhp

end Rectangle

end PEPS
end TNLean
