/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import QICLean.Algebra.NilMatrixSubalgebra
import QICLean.Algebra.ShiftedZeroTraceNilpotent
import TNLean.MPS.Core.Reduction
import TNLean.MPS.Core.TracePairing

/-!
# Residual words of a rectangular MPS reduction

For a selected reduction from `B` to `A`, this file studies the residual letters
$N^i=B^i-WA^iV$ and the nonunital algebra that they generate.  It proves the
sandwich identity, the corrected strict-window expansion, nilpotency under
positive-length closed-chain equality, the two contracted expansions, and the
exterior-buffer identity used in blocking arguments.

**Local fix (arXiv:1706.07329v2, Lemma `B_expand`, lines 3993--4005):** the
printed weak-range expansion is false.  The statements below use a pure
residual term and a strict nonempty central window, as documented in
`docs/paper-gaps/mgsc18_residual_expansion_empty_word_error.tex`.
-/

open scoped Matrix BigOperators

namespace MPSTensor

variable {d D_A D_B : ℕ}

/-- The reduction-specific residual letter $N^i=B^i-WA^iV$.

Source: Molnár--Ge--Schuch--Cirac, arXiv:1706.07329v2, Definition 8,
`cornerproblem.tex` lines 3147--3152. -/
noncomputable def reductionResidual (B : MPSTensor d D_B) (A : MPSTensor d D_A)
    (V : Matrix (Fin D_A) (Fin D_B) ℂ) (W : Matrix (Fin D_B) (Fin D_A) ℂ) :
    MPSTensor d D_B :=
  fun i ↦ B i - W * A i * V

/-- The set of residual letters belonging to one selected reduction. -/
noncomputable def reductionResidualGeneratorSet (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) : Set (Matrix (Fin D_B) (Fin D_B) ℂ) :=
  Set.range (reductionResidual B A V W)

/-- The nonunital algebra generated by the residual letters of one selected reduction.

Source: arXiv:1706.07329v2, Proposition 21 and its proof,
`cornerproblem.tex` lines 3972--3986. -/
noncomputable def reductionResidualAlgebra (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) :
    NonUnitalSubalgebra ℂ (Matrix (Fin D_B) (Fin D_B) ℂ) :=
  NonUnitalAlgebra.adjoin ℂ (reductionResidualGeneratorSet B A V W)

/-- The strict-window terms whose central $A$-word starts at the first
letter of the input word.  The recursion enumerates every nonempty initial
central word exactly once. -/
noncomputable def reductionInitialWindowSum (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) :
    List (Fin d) → Matrix (Fin D_B) (Fin D_B) ℂ
  | [] => 0
  | i :: w => W * A i * V *
      (Kraus.evalWord (reductionResidual B A V W) w +
        reductionInitialWindowSum B A V W w)

/-- The sum over all strict windows $0\leq r<s\leq |w|$.  Its summand is
$N^{w_{<r}} W A^{w_{[r,s)}} V N^{w_{\geq s}}$.  The first recursive term
collects windows with `r = 0`; the second shifts every window in the tail and
therefore collects `0 < r < s`. -/
noncomputable def reductionStrictWindowSum (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) :
    List (Fin d) → Matrix (Fin D_B) (Fin D_B) ℂ
  | [] => 0
  | i :: w => reductionInitialWindowSum B A V W (i :: w) +
      reductionResidual B A V W i * reductionStrictWindowSum B A V W w

/-- Every selected-reduction residual letter belongs to its generated algebra. -/
theorem reductionResidual_mem_reductionResidualAlgebra
    (B : MPSTensor d D_B) (A : MPSTensor d D_A)
    (V : Matrix (Fin D_A) (Fin D_B) ℂ) (W : Matrix (Fin D_B) (Fin D_A) ℂ)
    (i : Fin d) :
    reductionResidual B A V W i ∈ reductionResidualAlgebra B A V W := by
  apply NonUnitalAlgebra.subset_adjoin ℂ
  exact ⟨i, rfl⟩

namespace IsReduction

variable {B : MPSTensor d D_B} {A : MPSTensor d D_A}
  {V : Matrix (Fin D_A) (Fin D_B) ℂ} {W : Matrix (Fin D_B) (Fin D_A) ℂ}

private lemma evalWord_eq_prod_map (K : MPSTensor d D_B) (w : List (Fin d)) :
    Kraus.evalWord K w = (w.map K).prod := by
  induction w with
  | nil => simp
  | cons i w ih => simp [Kraus.evalWord_cons, ih]

/-- A nonempty residual block vanishes when it is placed between arbitrary
`B`-words and then compressed by the reduction matrices.

The case of empty exterior words is the source identity
$V N^{a_1}\cdots N^{a_m}W=0$.

Source: arXiv:1706.07329v2, Lemma `lem:VNW=0`,
`cornerproblem.tex` lines 3946--3970. -/
theorem evalWord_mul_reductionResidual_mul_evalWord_eq_zero
    (h : IsReduction B A V W) (p u q : List (Fin d)) (hu : u ≠ []) :
    V * Kraus.evalWord B p * Kraus.evalWord (reductionResidual B A V W) u *
        Kraus.evalWord B q * W = 0 := by
  induction u generalizing p with
  | nil => exact (hu rfl).elim
  | cons i u ih =>
      rw [Kraus.evalWord_cons, reductionResidual]
      simp only [Matrix.mul_sub, Matrix.sub_mul]
      by_cases hu' : u = []
      · subst u
        simp only [Kraus.evalWord_nil, Matrix.mul_one]
        have hpq := h.evalWord (p ++ i :: q)
        have hp := h.evalWord p
        have hq := h.evalWord q
        simp only [Kraus.evalWord_append, Kraus.evalWord_cons, Matrix.mul_assoc] at hpq
        have hmain :
            V * Kraus.evalWord B p * B i * Kraus.evalWord B q * W =
              Kraus.evalWord A p * A i * Kraus.evalWord A q := by
          simpa only [Matrix.mul_assoc] using hpq
        have hcompressed :
            V * Kraus.evalWord B p * (W * A i * V) * Kraus.evalWord B q * W =
              Kraus.evalWord A p * A i * Kraus.evalWord A q := by
          simpa only [Matrix.mul_assoc] using
            congrArg₂ (fun X Y ↦ X * A i * Y) hp hq
        simpa only [Matrix.mul_one] using sub_eq_zero.mpr (hmain.trans hcompressed.symm)
      · have hfirst := ih (p := p ++ [i]) hu'
        have hsecond := ih (p := []) hu'
        simp only [Kraus.evalWord_nil] at hsecond
        rw [Kraus.evalWord_append, Kraus.evalWord_cons, Kraus.evalWord_nil,
          Matrix.mul_one] at hfirst
        have hfirst' :
            V * Kraus.evalWord B p *
                (B i * Kraus.evalWord (reductionResidual B A V W) u) *
                Kraus.evalWord B q * W = 0 := by
          simpa only [Matrix.mul_assoc] using hfirst
        have hsecond' :
            V * Kraus.evalWord (reductionResidual B A V W) u *
                Kraus.evalWord B q * W = 0 := by
          simpa only [Matrix.mul_assoc, Matrix.one_mul] using hsecond
        have hcorrection :
            V * Kraus.evalWord B p *
                (W * A i * V * Kraus.evalWord (reductionResidual B A V W) u) *
                Kraus.evalWord B q * W = 0 := by
          have := congrArg
            (fun X ↦ (V * Kraus.evalWord B p * W) * A i * X) hsecond'
          simpa only [Matrix.mul_assoc, Matrix.mul_zero] using this
        rw [hfirst', hcorrection]
        simp

/-- Every positive selected-reduction residual word vanishes after sandwiching
by the reduction matrices.

Source: arXiv:1706.07329v2, Lemma `lem:VNW=0`,
`cornerproblem.tex` lines 3946--3970. -/
theorem evalWord_reductionResidual_sandwich_eq_zero
    (h : IsReduction B A V W) (u : List (Fin d)) (hu : u ≠ []) :
    V * Kraus.evalWord (reductionResidual B A V W) u * W = 0 := by
  simpa using h.evalWord_mul_reductionResidual_mul_evalWord_eq_zero [] u [] hu

private theorem evalWord_reductionResidual_mul_strictWindowSum_eq_zero
    (h : IsReduction B A V W) (u w : List (Fin d)) (hu : u ≠ []) :
    V * Kraus.evalWord (reductionResidual B A V W) u *
      reductionStrictWindowSum B A V W w = 0 := by
  induction w generalizing u with
  | nil => simp [reductionStrictWindowSum]
  | cons i w ih =>
      rw [reductionStrictWindowSum]
      simp only [Matrix.mul_add]
      have hinitial :
          V * Kraus.evalWord (reductionResidual B A V W) u *
            reductionInitialWindowSum B A V W (i :: w) = 0 := by
        rw [reductionInitialWindowSum]
        have hsandwich := h.evalWord_reductionResidual_sandwich_eq_zero u hu
        have := congrArg
          (fun X ↦ X * A i * V *
            (Kraus.evalWord (reductionResidual B A V W) w +
              reductionInitialWindowSum B A V W w)) hsandwich
        simpa only [Matrix.mul_assoc, Matrix.zero_mul] using this
      have hshift :
          V * Kraus.evalWord (reductionResidual B A V W) u *
              (reductionResidual B A V W i *
                reductionStrictWindowSum B A V W w) = 0 := by
        simpa only [Kraus.evalWord_append, Kraus.evalWord_cons, Kraus.evalWord_nil,
          Matrix.mul_one, Matrix.mul_assoc] using ih (u ++ [i]) (by simp [hu])
      rw [hinitial, hshift]
      simp

private theorem mul_strictWindowSum_eq_mul_initialWindowSum
    (h : IsReduction B A V W) (w : List (Fin d)) :
    V * reductionStrictWindowSum B A V W w =
      V * reductionInitialWindowSum B A V W w := by
  cases w with
  | nil => simp [reductionStrictWindowSum, reductionInitialWindowSum]
  | cons i w =>
      rw [reductionStrictWindowSum, Matrix.mul_add]
      have hzero := h.evalWord_reductionResidual_mul_strictWindowSum_eq_zero [i] w (by simp)
      simpa [Kraus.evalWord_cons, Kraus.evalWord_nil, Matrix.mul_assoc] using hzero

/-- Corrected full residual expansion.  The first term is the pure residual
word.  `reductionStrictWindowSum` is the sum over the strict range
$0\leq r<s\leq |w|$, so every central $A$-word is nonempty.

Source: arXiv:1706.07329v2, Lemma `lem:B_expand`, lines 3993--4005.
The corrected range is documented in
`docs/paper-gaps/mgsc18_residual_expansion_empty_word_error.tex`. -/
theorem evalWord_eq_reductionResidual_add_strictWindowSum
    (h : IsReduction B A V W) (w : List (Fin d)) :
    Kraus.evalWord B w = Kraus.evalWord (reductionResidual B A V W) w +
      reductionStrictWindowSum B A V W w := by
  induction w with
  | nil => simp [reductionStrictWindowSum]
  | cons i w ih =>
      rw [Kraus.evalWord_cons, ih, reductionStrictWindowSum,
        reductionInitialWindowSum, reductionResidual]
      have hmerge := congrArg (fun X ↦ W * A i * X)
        (h.mul_strictWindowSum_eq_mul_initialWindowSum w)
      have hmerge' :
          W * A i * V * reductionStrictWindowSum B A V W w =
            W * A i * V * reductionInitialWindowSum B A V W w := by
        simpa only [Matrix.mul_assoc] using hmerge
      simp only [Kraus.evalWord_cons, reductionResidual, Matrix.mul_add]
      noncomm_ring [hmerge']

/-- Every nonempty residual word has zero trace when `B` and `A` have the
same positive-length closed chains.  This is the trace input to the residual
nilpotency argument.

Source: arXiv:1706.07329v2, Proposition 21 proof,
`cornerproblem.tex` lines 3972--3986. -/
theorem trace_evalWord_reductionResidual_eq_zero
    (h : IsReduction B A V W) (hSame : SameMPV₂Pos B A)
    (u : List (Fin d)) (hu : u ≠ []) :
    Matrix.trace (Kraus.evalWord (reductionResidual B A V W) u) = 0 := by
  have haux : ∀ (p u : List (Fin d)), u ≠ [] →
      Matrix.trace (Kraus.evalWord B p *
        Kraus.evalWord (reductionResidual B A V W) u) = 0 := by
    intro p u hu
    induction u generalizing p with
    | nil => exact (hu rfl).elim
    | cons i u ih =>
        rw [Kraus.evalWord_cons, reductionResidual, Matrix.sub_mul,
          Matrix.mul_sub, Matrix.trace_sub]
        by_cases hu' : u = []
        · subst u
          simp only [Kraus.evalWord_nil, Matrix.mul_one]
          have htrace := hSame.trace_evalWord (p ++ [i]) (by simp)
          have hp := h.evalWord p
          have hcompressed :
              Matrix.trace (Kraus.evalWord B p * (W * A i * V)) =
                Matrix.trace (Kraus.evalWord A p * A i) := by
            calc
              _ = Matrix.trace (V * Kraus.evalWord B p * W * A i) := by
                simpa only [Matrix.mul_assoc] using
                  Matrix.trace_mul_cycle (Kraus.evalWord B p * W) (A i) V
              _ = _ := by rw [hp]
          rw [hcompressed]
          apply sub_eq_zero.mpr
          simpa [Kraus.evalWord_append, Matrix.mul_assoc] using htrace
        · have hfirst := ih (p ++ [i]) hu'
          have hsandwich := h.evalWord_mul_reductionResidual_mul_evalWord_eq_zero
            [] u p hu'
          have hsecond :
              Matrix.trace (Kraus.evalWord B p *
                (W * A i * V * Kraus.evalWord (reductionResidual B A V W) u)) = 0 := by
            calc
              _ = Matrix.trace
                    (V * Kraus.evalWord (reductionResidual B A V W) u *
                      Kraus.evalWord B p * W * A i) := by
                  simpa only [Matrix.mul_assoc] using
                    Matrix.trace_mul_cycle (Kraus.evalWord B p * W) (A i)
                      (V * Kraus.evalWord (reductionResidual B A V W) u)
              _ = 0 := by
                have hsandwich' :
                    V * Kraus.evalWord (reductionResidual B A V W) u *
                      Kraus.evalWord B p * W = 0 := by
                  simpa only [Kraus.evalWord_nil, Matrix.one_mul, Matrix.mul_assoc] using hsandwich
                rw [hsandwich', Matrix.zero_mul, Matrix.trace_zero]
          have hfirst' :
              Matrix.trace (Kraus.evalWord B p *
                (B i * Kraus.evalWord (reductionResidual B A V W) u)) = 0 := by
            simpa [Kraus.evalWord_append, Matrix.mul_assoc] using hfirst
          rw [hfirst', hsecond]
          simp
  simpa using haux [] u hu

end IsReduction

private theorem exists_reductionResiduals_eq_list_of_mem_generatorSet
    (B : MPSTensor d D_B) (A : MPSTensor d D_A)
    (V : Matrix (Fin D_A) (Fin D_B) ℂ) (W : Matrix (Fin D_B) (Fin D_A) ℂ)
    (l : List (Matrix (Fin D_B) (Fin D_B) ℂ))
    (hl : ∀ X ∈ l, X ∈ reductionResidualGeneratorSet B A V W) :
    ∃ letters : Fin l.length → Fin d,
      l = List.ofFn (fun k ↦ reductionResidual B A V W (letters k)) := by
  classical
  have hletter : ∀ k : Fin l.length,
      ∃ i : Fin d, l[k] = reductionResidual B A V W i := by
    intro k
    obtain ⟨i, hi⟩ := hl l[k] (List.get_mem l k)
    exact ⟨i, hi.symm⟩
  choose letters hletters using hletter
  refine ⟨letters, ?_⟩
  calc
    l = List.ofFn (fun k ↦ l[k]) := (List.ofFn_get l).symm
    _ = List.ofFn (fun k ↦ reductionResidual B A V W (letters k)) := by
      congr 1
      funext k
      exact hletters k

private theorem Subsemigroup.exists_nonempty_list_prod_of_mem_closure_reductionResidual
    {M : Type*} [Monoid M] {s : Set M} {x : M}
    (hx : x ∈ Subsemigroup.closure s) :
    ∃ l : List M, l ≠ [] ∧ (∀ a ∈ l, a ∈ s) ∧ l.prod = x := by
  induction hx using Subsemigroup.closure_induction with
  | mem x hx => exact ⟨[x], by simp, by simpa, by simp⟩
  | mul x y _ _ hx hy =>
      obtain ⟨lx, hlx, hlxs, hxl⟩ := hx
      obtain ⟨ly, hly, hlys, hyl⟩ := hy
      refine ⟨lx ++ ly, ?_, ?_, ?_⟩
      · simp [hlx]
      · intro a ha
        exact List.mem_append.mp ha |>.elim (hlxs a) (hlys a)
      · rw [List.prod_append, hxl, hyl]

private theorem pow_mem_nonUnitalSubalgebra_of_pos_reductionResidual
    {R M : Type*} [CommSemiring R] [Semiring M] [Module R M]
    [IsScalarTower R M M] [SMulCommClass R M M]
    (S : NonUnitalSubalgebra R M) {x : M} (hx : x ∈ S)
    {N : ℕ} (hN : 0 < N) : x ^ N ∈ S := by
  cases N with
  | zero => omega
  | succ N =>
      clear hN
      induction N with
      | zero => simpa using hx
      | succ N ih => simpa [pow_succ] using S.mul_mem ih hx

namespace IsReduction

variable {B : MPSTensor d D_B} {A : MPSTensor d D_A}
  {V : Matrix (Fin D_A) (Fin D_B) ℂ} {W : Matrix (Fin D_B) (Fin D_A) ℂ}

/-- Every element of the selected-reduction residual algebra has zero trace. -/
theorem trace_eq_zero_of_mem_reductionResidualAlgebra
    (h : IsReduction B A V W) (hSame : SameMPV₂Pos B A)
    {X : Matrix (Fin D_B) (Fin D_B) ℂ}
    (hX : X ∈ reductionResidualAlgebra B A V W) : Matrix.trace X = 0 := by
  change X ∈ (NonUnitalAlgebra.adjoin ℂ
    (reductionResidualGeneratorSet B A V W)).toSubmodule at hX
  rw [NonUnitalAlgebra.adjoin_eq_span] at hX
  induction hX using Submodule.span_induction with
  | mem X hX =>
      obtain ⟨l, hne, hl, rfl⟩ :=
        Subsemigroup.exists_nonempty_list_prod_of_mem_closure_reductionResidual hX
      obtain ⟨letters, hl_eq⟩ :=
        exists_reductionResiduals_eq_list_of_mem_generatorSet B A V W l hl
      rw [hl_eq]
      have heval := evalWord_eq_prod_map (reductionResidual B A V W) (List.ofFn letters)
      simp only [List.map_ofFn] at heval
      have hmap :
          List.ofFn (reductionResidual B A V W ∘ letters) =
            List.ofFn (fun k ↦ reductionResidual B A V W (letters k)) := by
        congr 1
      rw [hmap] at heval
      rw [← heval]
      apply h.trace_evalWord_reductionResidual_eq_zero hSame
      simpa using hne
  | zero => simp
  | add X Y _ _ hX hY => simp [Matrix.trace_add, hX, hY]
  | smul c X _ hX => simp [Matrix.trace_smul, hX]

/-- Every element of the selected-reduction residual algebra is nilpotent. -/
theorem isNilpotent_of_mem_reductionResidualAlgebra
    (h : IsReduction B A V W) (hSame : SameMPV₂Pos B A)
    (X : reductionResidualAlgebra B A V W) :
    IsNilpotent (X : Matrix (Fin D_B) (Fin D_B) ℂ) := by
  apply Matrix.isNilpotent_of_forall_trace_pow_eq_zero_of_one_lt
  intro N hN
  apply h.trace_eq_zero_of_mem_reductionResidualAlgebra hSame
  exact pow_mem_nonUnitalSubalgebra_of_pos_reductionResidual
    (reductionResidualAlgebra B A V W) X.property (by omega)

/-- Every mixed product of exactly the bond dimension `D_B` elements of the
selected-reduction residual algebra vanishes. -/
theorem reductionResidualAlgebra_list_prod_eq_zero
    (h : IsReduction B A V W) (hSame : SameMPV₂Pos B A)
    (l : List (Matrix (Fin D_B) (Fin D_B) ℂ))
    (hl : ∀ X ∈ l, X ∈ reductionResidualAlgebra B A V W)
    (hlen : l.length = D_B) : l.prod = 0 := by
  apply (reductionResidualAlgebra B A V W).matrix_list_prod_eq_zero_of_forall_isNilpotent
    (h.isNilpotent_of_mem_reductionResidualAlgebra hSame) l hl
  simpa using hlen

/-- Every residual word whose length is at least `D_B` vanishes.  The bound is
the bond dimension, not its square. -/
theorem evalWord_reductionResidual_eq_zero_of_bondDim_le_length
    (h : IsReduction B A V W) (hSame : SameMPV₂Pos B A)
    (w : List (Fin d)) (hlen : D_B ≤ w.length) :
    Kraus.evalWord (reductionResidual B A V W) w = 0 := by
  rw [← w.take_append_drop D_B, Kraus.evalWord_append]
  have htake : Kraus.evalWord (reductionResidual B A V W) (w.take D_B) = 0 := by
    rw [evalWord_eq_prod_map]
    apply h.reductionResidualAlgebra_list_prod_eq_zero hSame
    · intro X hX
      obtain ⟨i, hi, rfl⟩ := List.mem_map.mp hX
      exact reductionResidual_mem_reductionResidualAlgebra B A V W i
    · simp [List.length_take, Nat.min_eq_left hlen]
  rw [htake, Matrix.zero_mul]

end IsReduction

end MPSTensor
