/-
Copyright (c) 2025 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import QICLean.Channel.Peripheral.ClosureFixedPointKraus
import QICLean.Channel.Peripheral.CyclicGroupKraus
import QICLean.Channel.Peripheral.CyclicDecomposition.LetterShift
import QICLean.Kraus.TransferChannel

/-!
# Transfer-map forms of the peripheral fixed-point and cyclic-group results

For a finite matrix family, the Kraus map equals its MPS transfer map. The
results below restate the Kraus-level peripheral theory in transfer-map
notation: peripheral invertibility, closure of the peripheral eigenvalues
under powers and products, roots of unity, the cyclic group generated by a
primitive root, and the word-level cyclic shift across the cyclic
projections.

## Main statements

* `isUnit_peripheral_eigenvector` — peripheral eigenvectors of irreducible
  unital transfer maps are units.
* `peripheralEigenvalues_pow_mem_of_irreducible_unital_of_adjoint_fixedPoint`,
  `peripheralEigenvalues_mul_mem_of_irreducible_unital_of_adjoint_fixedPoint`
  — closure under powers and products.
* `peripheral_isRootOfUnity_of_irreducible_unital_of_adjoint_fixedPoint` —
  peripheral eigenvalues are roots of unity.
* `peripheralEigenvalues_eq_range_primitiveRoot` — the peripheral
  eigenvalues form a cyclic group of roots of unity.
* `evalWord_mul_cyclicProj` — a word of length $\ell$ shifts every cyclic
  projection by $\ell$ steps.

## References

* [M. Wolf, *Quantum Channels & Operations: Guided Tour*, Theorem 6.6]
-/

open scoped Matrix ComplexOrder MatrixOrder BigOperators Fin.NatCast
open Matrix Finset Complex

namespace MPSTensor

/-- A peripheral eigenvector of an irreducible unital MPS transfer map with a
positive-definite adjoint fixed point is a unit. -/
theorem isUnit_peripheral_eigenvector
    {d D : ℕ} [NeZero D]
    (K : Fin d → Matrix (Fin D) (Fin D) ℂ)
    (h_unital : KadisonSchwarz.IsUnitalKraus (d := d) (D := D) K)
    (ρ : Matrix (Fin D) (Fin D) ℂ) (hρ : ρ.PosDef)
    (hfix : Kraus.adjointMap K ρ = ρ)
    (hIrr : IsIrreducibleMap (Kraus.transferMap (d := d) (D := D) K))
    (X : Matrix (Fin D) (Fin D) ℂ) (μ : ℂ)
    (hEig : Kraus.transferMap (d := d) (D := D) K X = μ • X)
    (hμ : ‖μ‖ = 1) (hX_ne : X ≠ 0) :
    IsUnit X := by
  have hIrr' : IsIrreducibleMap (Kraus.mapLM K) :=
    Kraus.isIrreducibleMap_mapLM_of_transferMap K hIrr
  have hEig' : Kraus.mapLM K X = μ • X := by
    rw [Kraus.mapLM_eq_transferMap]
    exact hEig
  exact Kraus.isUnit_peripheral_eigenvector
    K h_unital ρ hρ hfix hIrr' X μ hEig' hμ hX_ne

/-- Peripheral eigenvalues of an irreducible unital MPS transfer map with a
positive-definite adjoint fixed point are closed under powers. -/
theorem peripheralEigenvalues_pow_mem_of_irreducible_unital_of_adjoint_fixedPoint
    {d D : ℕ} [NeZero D]
    (K : Fin d → Matrix (Fin D) (Fin D) ℂ)
    (h_unital : KadisonSchwarz.IsUnitalKraus (d := d) (D := D) K)
    (ρ : Matrix (Fin D) (Fin D) ℂ) (hρ : ρ.PosDef)
    (hfix : Kraus.adjointMap K ρ = ρ)
    (hIrr : IsIrreducibleMap (Kraus.transferMap (d := d) (D := D) K)) :
    ∀ μ : ℂ,
      μ ∈ peripheralEigenvalues (Kraus.transferMap (d := d) (D := D) K) →
        ∀ n : ℕ,
          μ ^ n ∈ peripheralEigenvalues (Kraus.transferMap (d := d) (D := D) K) := by
  have hIrr' : IsIrreducibleMap (Kraus.mapLM K) :=
    Kraus.isIrreducibleMap_mapLM_of_transferMap K hIrr
  simpa only [Kraus.mapLM_eq_transferMap] using
    (Kraus.peripheralEigenvalues_pow_mem_of_irreducible_unital_of_adjoint_fixedPoint
      K h_unital ρ hρ hfix hIrr')

/-- Peripheral eigenvalues of an irreducible unital MPS transfer map with a
positive-definite adjoint fixed point are roots of unity. -/
theorem peripheral_isRootOfUnity_of_irreducible_unital_of_adjoint_fixedPoint
    {d D : ℕ} [NeZero D]
    (K : Fin d → Matrix (Fin D) (Fin D) ℂ)
    (h_unital : KadisonSchwarz.IsUnitalKraus (d := d) (D := D) K)
    (ρ : Matrix (Fin D) (Fin D) ℂ) (hρ : ρ.PosDef)
    (hfix : Kraus.adjointMap K ρ = ρ)
    (hIrr : IsIrreducibleMap (Kraus.transferMap (d := d) (D := D) K)) :
    ∀ μ : ℂ,
      μ ∈ peripheralEigenvalues (Kraus.transferMap (d := d) (D := D) K) →
        ∃ p : ℕ, 0 < p ∧ μ ^ p = 1 := by
  have hIrr' : IsIrreducibleMap (Kraus.mapLM K) :=
    Kraus.isIrreducibleMap_mapLM_of_transferMap K hIrr
  simpa only [Kraus.mapLM_eq_transferMap] using
    (Kraus.peripheral_isRootOfUnity_of_irreducible_unital_of_adjoint_fixedPoint
      K h_unital ρ hρ hfix hIrr')

/-- Peripheral eigenvalues are closed under multiplication for irreducible
unital MPS transfer maps with a positive-definite adjoint fixed point. -/
theorem peripheralEigenvalues_mul_mem_of_irreducible_unital_of_adjoint_fixedPoint
    {d D : ℕ} [NeZero D]
    (K : Fin d → Matrix (Fin D) (Fin D) ℂ)
    (h_unital : KadisonSchwarz.IsUnitalKraus (d := d) (D := D) K)
    (ρ : Matrix (Fin D) (Fin D) ℂ) (hρ : ρ.PosDef)
    (hfix : Kraus.adjointMap K ρ = ρ)
    (hIrr : IsIrreducibleMap (Kraus.transferMap (d := d) (D := D) K)) :
    ∀ μ ν : ℂ,
      μ ∈ peripheralEigenvalues (Kraus.transferMap (d := d) (D := D) K) →
      ν ∈ peripheralEigenvalues (Kraus.transferMap (d := d) (D := D) K) →
        μ * ν ∈ peripheralEigenvalues (Kraus.transferMap (d := d) (D := D) K) := by
  have hIrr' : IsIrreducibleMap (Kraus.mapLM K) :=
    Kraus.isIrreducibleMap_mapLM_of_transferMap K hIrr
  simpa only [Kraus.mapLM_eq_transferMap] using
    (Kraus.peripheralEigenvalues_mul_mem_of_irreducible_unital_of_adjoint_fixedPoint
      K h_unital ρ hρ hfix hIrr')

/-- The peripheral eigenvalues of an irreducible unital MPS transfer map with a
positive-definite adjoint fixed point form a cyclic group of roots of unity. -/
theorem peripheralEigenvalues_eq_range_primitiveRoot {d D : ℕ} [NeZero D]
    (K : Fin d → Matrix (Fin D) (Fin D) ℂ)
    (h_unital : KadisonSchwarz.IsUnitalKraus (d := d) (D := D) K)
    (ρ : Matrix (Fin D) (Fin D) ℂ) (hρ : ρ.PosDef)
    (hfix : Kraus.adjointMap K ρ = ρ)
    (hIrr : IsIrreducibleMap (Kraus.transferMap (d := d) (D := D) K)) :
    let E := Kraus.transferMap (d := d) (D := D) K
    let hfin := peripheralEigenvalues_finite (f := E)
    let m := hfin.toFinset.card
    0 < m ∧
    ∃ (γ : ℂ), IsPrimitiveRoot γ m ∧
      peripheralEigenvalues E = Set.range (fun j : Fin m => γ ^ (j : ℕ)) := by
  have hIrr' : IsIrreducibleMap (Kraus.mapLM K) :=
    Kraus.isIrreducibleMap_mapLM_of_transferMap K hIrr
  rw [← Kraus.mapLM_eq_transferMap K]
  exact Kraus.peripheralEigenvalues_eq_range_primitiveRoot
    K h_unital ρ hρ hfix hIrr'

/-- Deprecated alias of `Kraus.one_sub_mul_kraus_mul_eq_zero_of_mapLM_proj`, restated over the
MPS transfer map instead of the finite Kraus map. -/
@[deprecated Kraus.one_sub_mul_kraus_mul_eq_zero_of_mapLM_proj (since := "2026-08-19")]
theorem one_sub_mul_kraus_mul_eq_zero_of_transferMap_proj
    {r n : ℕ} (K : Fin r → MatrixAlg n) {P P' : MatrixAlg n}
    (hP : IsOrthogonalProjection P) (hP' : IsOrthogonalProjection P')
    (hmap : Kraus.transferMap (d := r) (D := n) K P' = P) :
    ∀ v, (1 - P) * K v * P' = 0 := by
  have hmap' : Kraus.mapLM K P' = P := by rw [Kraus.mapLM_eq_transferMap]; exact hmap
  exact Kraus.one_sub_mul_kraus_mul_eq_zero_of_mapLM_proj K hP hP' hmap'

/-- Deprecated alias of `Kraus.kraus_mul_cyclicProj`, restated over the MPS transfer map instead
of the finite Kraus map. -/
@[deprecated Kraus.kraus_mul_cyclicProj (since := "2026-08-19")]
theorem kraus_mul_cyclicProj
    {r n m : ℕ} [NeZero m] (K : Fin r → MatrixAlg n) (P : Fin m → MatrixAlg n)
    (hproj : ∀ k, IsOrthogonalProjection (P k))
    (hsum : ∑ k : Fin m, P k = 1)
    (hcyclic : ∀ k : Fin m, Kraus.transferMap (d := r) (D := n) K (P (k + 1)) = P k) :
    ∀ (v : Fin r) (k : Fin m), K v * P (k + 1) = P k * K v := by
  have hcyclic' : ∀ k : Fin m, Kraus.mapLM K (P (k + 1)) = P k := fun k => by
    rw [Kraus.mapLM_eq_transferMap]; exact hcyclic k
  exact Kraus.kraus_mul_cyclicProj K P hproj hsum hcyclic'

/-- Deprecated alias of `Kraus.cyclicProj_ne_zero`, restated over the MPS transfer map instead of
the finite Kraus map. -/
@[deprecated Kraus.cyclicProj_ne_zero (since := "2026-08-19")]
theorem cyclicProj_ne_zero
    {r n m : ℕ} [NeZero m] [NeZero n] (K : Fin r → MatrixAlg n) (P : Fin m → MatrixAlg n)
    (hsum : ∑ k : Fin m, P k = 1)
    (hcyclic : ∀ k : Fin m, Kraus.transferMap (d := r) (D := n) K (P (k + 1)) = P k) :
    ∀ k : Fin m, P k ≠ 0 := by
  have hcyclic' : ∀ k : Fin m, Kraus.mapLM K (P (k + 1)) = P k := fun k => by
    rw [Kraus.mapLM_eq_transferMap]; exact hcyclic k
  exact Kraus.cyclicProj_ne_zero K P hsum hcyclic'

/-- **Word-level cyclic shift**: a word $A^w=K_{w_1}\cdots K_{w_\ell}$ of
length $\ell$ moves each cyclic projection back by $\ell$ steps,
$A^wP_k=P_{k-\ell}A^w$.  In particular a word of length $m$ commutes with
every cyclic projection. -/
theorem evalWord_mul_cyclicProj {r n m : ℕ} [NeZero m]
    (K : Fin r → MatrixAlg n) (P : Fin m → MatrixAlg n)
    (hproj : ∀ k, IsOrthogonalProjection (P k))
    (hsum : ∑ k : Fin m, P k = 1)
    (hcyclic : ∀ k : Fin m, Kraus.transferMap (d := r) (D := n) K (P (k + 1)) = P k) :
    ∀ (w : List (Fin r)) (k : Fin m),
      Kraus.evalWord K w * P k = P (k - (w.length : Fin m)) * Kraus.evalWord K w := by
  have hcyclicLM : ∀ k : Fin m, Kraus.mapLM K (P (k + 1)) = P k := fun k => by
    rw [Kraus.mapLM_eq_transferMap]
    exact hcyclic k
  intro w
  induction w with
  | nil =>
    intro k
    simp
  | cons v w ih =>
    intro k
    have hstep : K v * P (k - (w.length : Fin m)) =
        P (k - (w.length : Fin m) - 1) * K v := by
      have := Kraus.kraus_mul_cyclicProj K P hproj hsum hcyclicLM v
        (k - (w.length : Fin m) - 1)
      rwa [sub_add_cancel] at this
    calc Kraus.evalWord K (v :: w) * P k
        = K v * (Kraus.evalWord K w * P k) := by rw [Kraus.evalWord_cons, Matrix.mul_assoc]
      _ = K v * (P (k - (w.length : Fin m)) * Kraus.evalWord K w) := by rw [ih k]
      _ = (K v * P (k - (w.length : Fin m))) * Kraus.evalWord K w := by
          rw [Matrix.mul_assoc]
      _ = P (k - (w.length : Fin m) - 1) * (K v * Kraus.evalWord K w) := by
          rw [hstep, Matrix.mul_assoc]
      _ = P (k - ((v :: w).length : Fin m)) * Kraus.evalWord K (v :: w) := by
          rw [Kraus.evalWord_cons]
          congr 2
          rw [List.length_cons, Nat.cast_add, Nat.cast_one, sub_sub]

end MPSTensor
