/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.
-- Import architecture: docs/import_structure.md.
-- Generated aggregator module: TNLean.MPS.Core

import TNLean.MPS.Core.Blocking
import TNLean.MPS.Core.BlockingInfrastructure
import TNLean.MPS.Core.BlockingTransfer
import QICLean.MPS.Core.CPPrimitive
import TNLean.MPS.Core.CanonicalNormalization
import TNLean.MPS.Core.CorrelationReduction
import TNLean.MPS.Core.Correlations
import TNLean.MPS.Core.CyclicTrace
import QICLean.MPS.Core.Injectivity
import QICLean.MPS.Core.InvariantProjection
import TNLean.MPS.Core.MultiBlock
import TNLean.MPS.Core.MultiBlockWord
import TNLean.MPS.Core.OrthogonalProjectionInvariance
import TNLean.MPS.Core.PhysicalReindexTransport
import TNLean.MPS.Core.RepeatedWord
import TNLean.MPS.Core.TPGauge
import QICLean.MPS.Core.Transfer
import QICLean.MPS.Core.TransferChannel
import TNLean.MPS.Core.TransferMatrix
import TNLean.MPS.Core.TransferPeripheral
import QICLean.MPS.Core.Word
import TNLean.MPS.Core.WordFactor
