/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.MPDO.BiCFDerivation.Core
import TNLean.Algebra.SkolemNoether
import Mathlib.Algebra.Algebra.Prod

/-!
# Pair-span homogenization for MPDO biCF

This module contains the homogeneous pair-span padding criteria and the
Burnside-Jacobson pair-algebra placeholders used to turn all-length pair trace
separation into a fixed homogeneous word length.
-/

open scoped Matrix BigOperators

namespace MPSTensor

variable {d : ℕ} {r : ℕ} {dim : Fin r → ℕ}

abbrev MatD (D : ℕ) := Matrix (Fin D) (Fin D) ℂ

/-! ### Homogenizing cumulative pair spans -/

/-- The unital algebra generated by simultaneous pair words of one letter.

For equal bond dimensions this is the subdirect product algebra used in the
Burnside-Jacobson branch of the BNT pair-separation argument. -/
noncomputable def pairAlgSpan {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) :
    Subalgebra ℂ (Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ) :=
  Algebra.adjoin ℂ (Set.range fun i : Fin d => (A i, B i))

private lemma algebra_adjoin_eq_top_of_isInjective {D : ℕ} {A : MPSTensor d D}
    (hA : IsInjective A) :
    Algebra.adjoin ℂ (Set.range A) = (⊤ : Subalgebra ℂ (Matrix (Fin D) (Fin D) ℂ)) := by
  classical
  apply Subalgebra.ext
  intro M
  constructor
  · intro _
    trivial
  · intro _
    have htop : (Algebra.adjoin ℂ (Set.range A)).toSubmodule =
        (⊤ : Submodule ℂ (Matrix (Fin D) (Fin D) ℂ)) := by
      apply le_antisymm
      · exact le_top
      · rw [← hA]
        exact Algebra.span_le_adjoin ℂ (Set.range A)
    change M ∈ (Algebra.adjoin ℂ (Set.range A)).toSubmodule
    rw [htop]
    exact Submodule.mem_top

/-- The first coordinate projection of the pair algebra is full when the first
block is injective. -/
theorem pairAlgSpan_map_fst_eq_top_of_isInjective {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) (hA : IsInjective A) :
    (pairAlgSpan A B).map
      (AlgHom.fst ℂ (Matrix (Fin D₁) (Fin D₁) ℂ) (Matrix (Fin D₂) (Fin D₂) ℂ)) =
        (⊤ : Subalgebra ℂ (Matrix (Fin D₁) (Fin D₁) ℂ)) := by
  classical
  rw [pairAlgSpan, AlgHom.map_adjoin]
  have himage :
      (AlgHom.fst ℂ (Matrix (Fin D₁) (Fin D₁) ℂ) (Matrix (Fin D₂) (Fin D₂) ℂ)) ''
          Set.range (fun i : Fin d => (A i, B i)) =
        Set.range A := by
    ext M
    constructor
    · rintro ⟨P, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, rfl⟩
    · rintro ⟨i, rfl⟩
      exact ⟨(A i, B i), ⟨i, rfl⟩, rfl⟩
  rw [himage]
  exact algebra_adjoin_eq_top_of_isInjective hA

/-- The second coordinate projection of the pair algebra is full when the
second block is injective. -/
theorem pairAlgSpan_map_snd_eq_top_of_isInjective {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) (hB : IsInjective B) :
    (pairAlgSpan A B).map
      (AlgHom.snd ℂ (Matrix (Fin D₁) (Fin D₁) ℂ) (Matrix (Fin D₂) (Fin D₂) ℂ)) =
        (⊤ : Subalgebra ℂ (Matrix (Fin D₂) (Fin D₂) ℂ)) := by
  classical
  rw [pairAlgSpan, AlgHom.map_adjoin]
  have himage :
      (AlgHom.snd ℂ (Matrix (Fin D₁) (Fin D₁) ℂ) (Matrix (Fin D₂) (Fin D₂) ℂ)) ''
          Set.range (fun i : Fin d => (A i, B i)) =
        Set.range B := by
    ext M
    constructor
    · rintro ⟨P, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, rfl⟩
    · rintro ⟨i, rfl⟩
      exact ⟨(A i, B i), ⟨i, rfl⟩, rfl⟩
  rw [himage]
  exact algebra_adjoin_eq_top_of_isInjective hB

/-- Every finite simultaneous pair word lies in the pair algebra. -/
theorem pairEvalWordTuple_mem_pairAlgSpan {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) (w : List (Fin d)) :
    pairEvalWordTuple A B w ∈ pairAlgSpan A B := by
  induction w with
  | nil =>
      exact (pairAlgSpan A B).one_mem
  | cons i w ih =>
      have hgen : (A i, B i) ∈ pairAlgSpan A B := by
        exact Algebra.subset_adjoin ⟨i, rfl⟩
      exact (pairAlgSpan A B).mul_mem hgen ih

/-- The all-words pair span is closed under componentwise multiplication. -/
theorem pair_mul_mem_pairAllWordsSpan {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    {M N : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ}
    (hM : M ∈ pairAllWordsSpan A B) (hN : N ∈ pairAllWordsSpan A B) :
    (M.1 * N.1, M.2 * N.2) ∈ pairAllWordsSpan A B := by
  classical
  let W := pairAllWordsSpan A B
  have hleft_gen : ∀ w : List (Fin d),
      ((pairEvalWordTuple A B w).1 * N.1, (pairEvalWordTuple A B w).2 * N.2) ∈ W := by
    intro w
    induction hN using Submodule.span_induction with
    | mem N' hNmem =>
        rcases hNmem with ⟨v, rfl⟩
        have hEq :
            ((pairEvalWordTuple A B w).1 * (pairEvalWordTuple A B v).1,
              (pairEvalWordTuple A B w).2 * (pairEvalWordTuple A B v).2) =
              pairEvalWordTuple A B (w ++ v) := by
          ext <;> simp [pairEvalWordTuple, evalWord_append]
        rw [hEq]
        exact Submodule.subset_span ⟨w ++ v, rfl⟩
    | zero =>
        have hzero :
            ((pairEvalWordTuple A B w).1 *
                (0 : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ).1,
              (pairEvalWordTuple A B w).2 *
                (0 : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ).2) = 0 := by
          simp
        rw [hzero]
        exact Submodule.zero_mem _
    | add N₁ N₂ _ _ hN₁ hN₂ =>
        have hEq :
            ((pairEvalWordTuple A B w).1 * (N₁ + N₂).1,
              (pairEvalWordTuple A B w).2 * (N₁ + N₂).2) =
              ((pairEvalWordTuple A B w).1 * N₁.1,
                (pairEvalWordTuple A B w).2 * N₁.2) +
              ((pairEvalWordTuple A B w).1 * N₂.1,
                (pairEvalWordTuple A B w).2 * N₂.2) := by
          ext <;> simp [Matrix.mul_add]
        rw [hEq]
        exact Submodule.add_mem _ hN₁ hN₂
    | smul a N _ hN =>
        have hEq :
            ((pairEvalWordTuple A B w).1 * (a • N).1,
              (pairEvalWordTuple A B w).2 * (a • N).2) =
              a • ((pairEvalWordTuple A B w).1 * N.1,
                (pairEvalWordTuple A B w).2 * N.2) := by
          ext <;> simp
        rw [hEq]
        exact Submodule.smul_mem _ a hN
  induction hM using Submodule.span_induction with
  | mem M hMmem =>
      rcases hMmem with ⟨w, rfl⟩
      exact hleft_gen w
  | zero =>
      have hzero :
          ((0 : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ).1 * N.1,
            (0 : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ).2 * N.2) = 0 := by
        simp
      rw [hzero]
      exact Submodule.zero_mem _
  | add M₁ M₂ _ _ hM₁ hM₂ =>
      have hEq : ((M₁ + M₂).1 * N.1, (M₁ + M₂).2 * N.2) =
          (M₁.1 * N.1, M₁.2 * N.2) + (M₂.1 * N.1, M₂.2 * N.2) := by
        ext <;> simp [Matrix.add_mul]
      rw [hEq]
      exact Submodule.add_mem _ hM₁ hM₂
  | smul a M _ hM =>
      have hEq : ((a • M).1 * N.1, (a • M).2 * N.2) =
          a • (M.1 * N.1, M.2 * N.2) := by
        ext <;> simp
      rw [hEq]
      exact Submodule.smul_mem _ a hM

/-- The submodule underlying the pair algebra is contained in the all-words
pair span. -/
theorem pairAlgSpan_toSubmodule_le_pairAllWordsSpan {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) :
    (pairAlgSpan A B).toSubmodule ≤ pairAllWordsSpan A B := by
  intro M hM
  change M ∈ pairAllWordsSpan A B
  induction hM using Algebra.adjoin_induction with
  | mem M hM =>
      rcases hM with ⟨i, rfl⟩
      have hword : pairEvalWordTuple A B [i] ∈ pairAllWordsSpan A B :=
        Submodule.subset_span ⟨[i], rfl⟩
      simpa [pairEvalWordTuple] using hword
  | algebraMap r =>
      have hone : pairEvalWordTuple A B [] ∈ pairAllWordsSpan A B :=
        Submodule.subset_span ⟨[], rfl⟩
      simpa [pairEvalWordTuple, Algebra.smul_def] using
        (pairAllWordsSpan A B).smul_mem r hone
  | add _ _ _ _ hx hy =>
      exact Submodule.add_mem _ hx hy
  | mul x y _ _ hx hy =>
      exact pair_mul_mem_pairAllWordsSpan A B hx hy

/-- If the generated pair algebra is the whole product algebra, then all finite
pair words span the whole product algebra linearly. -/
theorem pairAllWordsSpanTop_of_pairAlgSpan_eq_top {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hAlg : pairAlgSpan A B =
      (⊤ : Subalgebra ℂ
        (Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ))) :
    PairAllWordsSpanTop A B := by
  unfold PairAllWordsSpanTop
  apply eq_top_iff.mpr
  intro M _
  have hM : M ∈ (pairAlgSpan A B).toSubmodule := by
    rw [hAlg]
    exact Submodule.mem_top
  exact pairAlgSpan_toSubmodule_le_pairAllWordsSpan A B hM

/-- Full pair algebra gives all-length pair trace separation. -/
theorem pairTraceSeparatingAll_of_pairAlgSpan_eq_top {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hAlg : pairAlgSpan A B =
      (⊤ : Subalgebra ℂ
        (Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ))) :
    PairTraceSeparatingAll A B :=
  pairTraceSeparatingAll_of_pairAllWordsSpanTop A B
    (pairAllWordsSpanTop_of_pairAlgSpan_eq_top A B hAlg)

/-- If the pair algebra is the graph of an automorphism of the matrix algebra,
then the two tensors are gauge-phase equivalent.

This is the Skolem-Noether endpoint of the graph branch in the subdirect-product
proof route for the pair algebra. -/
theorem gaugePhaseEquiv_of_pairAlgSpan_eq_graph_algEquiv
    {d D : ℕ} [NeZero D] (A B : MPSTensor d D)
    (φ : MatD D ≃ₐ[ℂ] MatD D)
    (hS : pairAlgSpan A B =
      AlgHom.range
        ((AlgHom.id ℂ (MatD D)).prod (φ : MatD D →ₐ[ℂ] MatD D))) :
    GaugePhaseEquiv A B := by
  classical
  have hGraph : ∀ i : Fin d, B i = φ (A i) := by
    intro i
    have hgen : (A i, B i) ∈ pairAlgSpan A B := by
      exact Algebra.subset_adjoin ⟨i, rfl⟩
    rw [hS] at hgen
    rcases hgen with ⟨M, hM⟩
    have hfst : M = A i := by
      simpa using congrArg Prod.fst hM
    have hsnd : φ M = B i := by
      simpa using congrArg Prod.snd hM
    simpa [hfst] using hsnd.symm
  rcases skolemNoether_matrix φ with ⟨X, hX⟩
  exact GaugeEquiv.toGaugePhaseEquiv ⟨X, fun i => by
    rw [hGraph i, hX (A i)]⟩

/-- Under non-gauge-equivalence, the pair algebra cannot be the graph of a
matrix-algebra automorphism. -/
theorem not_pairAlgSpan_eq_graph_algEquiv_of_not_gaugePhaseEquiv
    {d D : ℕ} [NeZero D] (A B : MPSTensor d D)
    (hNot : ¬ GaugePhaseEquiv A B)
    (φ : MatD D ≃ₐ[ℂ] MatD D) :
    pairAlgSpan A B ≠
      AlgHom.range
        ((AlgHom.id ℂ (MatD D)).prod (φ : MatD D →ₐ[ℂ] MatD D)) := by
  intro hS
  exact hNot (gaugePhaseEquiv_of_pairAlgSpan_eq_graph_algEquiv A B φ hS)

private theorem subalgebra_prod_eq_top_of_axes {R A B : Type*}
    [CommSemiring R] [Semiring A] [Algebra R A] [Semiring B] [Algebra R B]
    (S : Subalgebra R (A × B))
    (hfst : ∀ x : A, (x, 0) ∈ S)
    (hsnd : ∀ y : B, (0, y) ∈ S) :
    S = ⊤ := by
  apply eq_top_iff.mpr
  rintro ⟨x, y⟩ _
  simpa using S.add_mem (hfst x) (hsnd y)

/-- If both coordinate axes lie in a matrix-pair subalgebra, the subalgebra is
the whole product. This is the top branch of the subdirect-product dichotomy
used in the pair-algebra density route. -/
theorem matrixPairSubalgebra_eq_top_of_axes {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : ∀ x : MatD D, (x, 0) ∈ S)
    (hsnd : ∀ y : MatD D, (0, y) ∈ S) :
    S = ⊤ :=
  subalgebra_prod_eq_top_of_axes S hfst hsnd

private noncomputable def leftAxisIdeal {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤) :
    TwoSidedIdeal (MatD D) :=
  TwoSidedIdeal.mk'
    {x : MatD D | (x, 0) ∈ S}
    S.zero_mem
    (fun hx hy => by simpa using S.add_mem hx hy)
    (fun hx => by simpa using S.neg_mem hx)
    (fun {x y} hy => by
      have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D) (MatD D)) := by
        rw [hfst]
        trivial
      rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
      have hpx' : p.1 = x := by simpa using hpx
      have hmul : (p * (y, 0)) ∈ S := S.mul_mem hpS hy
      have hprod : p * (y, 0) = (x * y, 0) := by
        ext <;> simp [hpx']
      simpa [hprod] using hmul)
    (fun {x y} hx => by
      have hymap : y ∈ S.map (AlgHom.fst ℂ (MatD D) (MatD D)) := by
        rw [hfst]
        trivial
      rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
      have hpy' : p.1 = y := by simpa using hpy
      have hmul : ((x, 0) * p) ∈ S := S.mul_mem hx hpS
      have hprod : (x, 0) * p = (x * y, 0) := by
        ext <;> simp [hpy']
      simpa [hprod] using hmul)

private noncomputable def rightAxisIdeal {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤) :
    TwoSidedIdeal (MatD D) :=
  TwoSidedIdeal.mk'
    {y : MatD D | (0, y) ∈ S}
    S.zero_mem
    (fun hx hy => by simpa using S.add_mem hx hy)
    (fun hx => by simpa using S.neg_mem hx)
    (fun {x y} hy => by
      have hxmap : x ∈ S.map (AlgHom.snd ℂ (MatD D) (MatD D)) := by
        rw [hsnd]
        trivial
      rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
      have hpx' : p.2 = x := by simpa using hpx
      have hmul : (p * (0, y)) ∈ S := S.mul_mem hpS hy
      have hprod : p * (0, y) = (0, x * y) := by
        ext <;> simp [hpx']
      simpa [hprod] using hmul)
    (fun {x y} hx => by
      have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D) (MatD D)) := by
        rw [hsnd]
        trivial
      rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
      have hpy' : p.2 = y := by simpa using hpy
      have hmul : ((0, x) * p) ∈ S := S.mul_mem hx hpS
      have hprod : (0, x) * p = (0, x * y) := by
        ext <;> simp [hpy']
      simpa [hprod] using hmul)

/-- A full left-axis ideal forces a subdirect matrix-pair subalgebra to be the
whole product. -/
theorem matrixPairSubalgebra_eq_top_of_leftAxisIdeal_eq_top {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤)
    (hleft : leftAxisIdeal S hfst = ⊤) :
    S = ⊤ := by
  apply matrixPairSubalgebra_eq_top_of_axes
  · intro x
    have hx : x ∈ leftAxisIdeal S hfst := by rw [hleft]; trivial
    simpa [leftAxisIdeal] using hx
  · intro y
    have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D) (MatD D)) := by
      rw [hsnd]
      trivial
    rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
    have hpy' : p.2 = y := by simpa using hpy
    have hneg : (-p.1, 0) ∈ S := by
      have hx : -p.1 ∈ leftAxisIdeal S hfst := by rw [hleft]; trivial
      simpa [leftAxisIdeal] using hx
    have hadd : (-p.1, 0) + p ∈ S := S.add_mem hneg hpS
    have hsum : (-p.1, 0) + p = (0, y) := by
      ext <;> simp [hpy']
    simpa [hsum] using hadd

/-- A full right-axis ideal forces a subdirect matrix-pair subalgebra to be the
whole product. -/
theorem matrixPairSubalgebra_eq_top_of_rightAxisIdeal_eq_top {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤)
    (hright : rightAxisIdeal S hsnd = ⊤) :
    S = ⊤ := by
  apply matrixPairSubalgebra_eq_top_of_axes
  · intro x
    have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D) (MatD D)) := by
      rw [hfst]
      trivial
    rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
    have hpx' : p.1 = x := by simpa using hpx
    have hneg : (0, -p.2) ∈ S := by
      have hy : -p.2 ∈ rightAxisIdeal S hsnd := by rw [hright]; trivial
      simpa [rightAxisIdeal] using hy
    have hadd : p + (0, -p.2) ∈ S := S.add_mem hpS hneg
    have hsum : p + (0, -p.2) = (x, 0) := by
      ext <;> simp [hpx']
    simpa [hsum] using hadd
  · intro y
    have hy : y ∈ rightAxisIdeal S hsnd := by rw [hright]; trivial
    simpa [rightAxisIdeal] using hy

private theorem fstProjection_injective_of_rightAxisIdeal_eq_bot {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤)
    (hright : rightAxisIdeal S hsnd = ⊥) :
    Function.Injective ((AlgHom.fst ℂ (MatD D) (MatD D)).comp S.val) := by
  intro x y hxy
  apply Subtype.ext
  apply Prod.ext
  · exact hxy
  · have hdiffS : x.1 - y.1 ∈ S := S.sub_mem x.2 y.2
    have hfirst : x.1.1 - y.1.1 = 0 := sub_eq_zero.mpr hxy
    have haxis : x.1.2 - y.1.2 ∈ rightAxisIdeal S hsnd := by
      have hdiff : x.1 - y.1 = (0, x.1.2 - y.1.2) := by
        apply Prod.ext
        · exact hfirst
        · rfl
      simpa [rightAxisIdeal] using (hdiff ▸ hdiffS)
    have hbot : x.1.2 - y.1.2 ∈ (⊥ : TwoSidedIdeal (MatD D)) := by
      simpa [hright] using haxis
    exact sub_eq_zero.mp (by simpa using hbot)

private theorem sndProjection_injective_of_leftAxisIdeal_eq_bot {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤)
    (hleft : leftAxisIdeal S hfst = ⊥) :
    Function.Injective ((AlgHom.snd ℂ (MatD D) (MatD D)).comp S.val) := by
  intro x y hxy
  apply Subtype.ext
  apply Prod.ext
  · have hdiffS : x.1 - y.1 ∈ S := S.sub_mem x.2 y.2
    have hsecond : x.1.2 - y.1.2 = 0 := sub_eq_zero.mpr hxy
    have haxis : x.1.1 - y.1.1 ∈ leftAxisIdeal S hfst := by
      have hdiff : x.1 - y.1 = (x.1.1 - y.1.1, 0) := by
        apply Prod.ext
        · rfl
        · exact hsecond
      simpa [leftAxisIdeal] using (hdiff ▸ hdiffS)
    have hbot : x.1.1 - y.1.1 ∈ (⊥ : TwoSidedIdeal (MatD D)) := by
      simpa [hleft] using haxis
    exact sub_eq_zero.mp (by simpa using hbot)
  · exact hxy

private noncomputable def leftAxisIdealHetero {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤) :
    TwoSidedIdeal (MatD D₁) :=
  TwoSidedIdeal.mk'
    {x : MatD D₁ | (x, 0) ∈ S}
    S.zero_mem
    (fun hx hy => by simpa using S.add_mem hx hy)
    (fun hx => by simpa using S.neg_mem hx)
    (fun {x y} hy => by
      have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) := by
        rw [hfst]
        trivial
      rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
      have hpx' : p.1 = x := by simpa using hpx
      have hmul : (p * (y, 0)) ∈ S := S.mul_mem hpS hy
      have hprod : p * (y, 0) = (x * y, 0) := by
        ext <;> simp [hpx']
      simpa [hprod] using hmul)
    (fun {x y} hx => by
      have hymap : y ∈ S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) := by
        rw [hfst]
        trivial
      rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
      have hpy' : p.1 = y := by simpa using hpy
      have hmul : ((x, 0) * p) ∈ S := S.mul_mem hx hpS
      have hprod : (x, 0) * p = (x * y, 0) := by
        ext <;> simp [hpy']
      simpa [hprod] using hmul)

private noncomputable def rightAxisIdealHetero {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤) :
    TwoSidedIdeal (MatD D₂) :=
  TwoSidedIdeal.mk'
    {y : MatD D₂ | (0, y) ∈ S}
    S.zero_mem
    (fun hx hy => by simpa using S.add_mem hx hy)
    (fun hx => by simpa using S.neg_mem hx)
    (fun {x y} hy => by
      have hxmap : x ∈ S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) := by
        rw [hsnd]
        trivial
      rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
      have hpx' : p.2 = x := by simpa using hpx
      have hmul : (p * (0, y)) ∈ S := S.mul_mem hpS hy
      have hprod : p * (0, y) = (0, x * y) := by
        ext <;> simp [hpx']
      simpa [hprod] using hmul)
    (fun {x y} hx => by
      have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) := by
        rw [hsnd]
        trivial
      rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
      have hpy' : p.2 = y := by simpa using hpy
      have hmul : ((0, x) * p) ∈ S := S.mul_mem hx hpS
      have hprod : (0, x) * p = (0, x * y) := by
        ext <;> simp [hpy']
      simpa [hprod] using hmul)

private theorem matrixPairSubalgebra_eq_top_of_leftAxisIdealHetero_eq_top {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hleft : leftAxisIdealHetero S hfst = ⊤) :
    S = ⊤ := by
  apply subalgebra_prod_eq_top_of_axes
  · intro x
    have hx : x ∈ leftAxisIdealHetero S hfst := by rw [hleft]; trivial
    simpa [leftAxisIdealHetero] using hx
  · intro y
    have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) := by
      rw [hsnd]
      trivial
    rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
    have hpy' : p.2 = y := by simpa using hpy
    have hneg : (-p.1, 0) ∈ S := by
      have hx : -p.1 ∈ leftAxisIdealHetero S hfst := by rw [hleft]; trivial
      simpa [leftAxisIdealHetero] using hx
    have hadd : (-p.1, 0) + p ∈ S := S.add_mem hneg hpS
    have hsum : (-p.1, 0) + p = (0, y) := by
      ext <;> simp [hpy']
    simpa [hsum] using hadd

private theorem matrixPairSubalgebra_eq_top_of_rightAxisIdealHetero_eq_top {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hright : rightAxisIdealHetero S hsnd = ⊤) :
    S = ⊤ := by
  apply subalgebra_prod_eq_top_of_axes
  · intro x
    have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) := by
      rw [hfst]
      trivial
    rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
    have hpx' : p.1 = x := by simpa using hpx
    have hneg : (0, -p.2) ∈ S := by
      have hy : -p.2 ∈ rightAxisIdealHetero S hsnd := by rw [hright]; trivial
      simpa [rightAxisIdealHetero] using hy
    have hadd : p + (0, -p.2) ∈ S := S.add_mem hpS hneg
    have hsum : p + (0, -p.2) = (x, 0) := by
      ext <;> simp [hpx']
    simpa [hsum] using hadd
  · intro y
    have hy : y ∈ rightAxisIdealHetero S hsnd := by rw [hright]; trivial
    simpa [rightAxisIdealHetero] using hy

private theorem fstProjectionHetero_injective_of_rightAxisIdeal_eq_bot {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hright : rightAxisIdealHetero S hsnd = ⊥) :
    Function.Injective ((AlgHom.fst ℂ (MatD D₁) (MatD D₂)).comp S.val) := by
  intro x y hxy
  apply Subtype.ext
  apply Prod.ext
  · exact hxy
  · have hdiffS : x.1 - y.1 ∈ S := S.sub_mem x.2 y.2
    have hfirst : x.1.1 - y.1.1 = 0 := sub_eq_zero.mpr hxy
    have haxis : x.1.2 - y.1.2 ∈ rightAxisIdealHetero S hsnd := by
      have hdiff : x.1 - y.1 = (0, x.1.2 - y.1.2) := by
        apply Prod.ext
        · exact hfirst
        · rfl
      simpa [rightAxisIdealHetero] using (hdiff ▸ hdiffS)
    have hbot : x.1.2 - y.1.2 ∈ (⊥ : TwoSidedIdeal (MatD D₂)) := by
      simpa [hright] using haxis
    exact sub_eq_zero.mp (by simpa using hbot)

private theorem sndProjectionHetero_injective_of_leftAxisIdeal_eq_bot {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hleft : leftAxisIdealHetero S hfst = ⊥) :
    Function.Injective ((AlgHom.snd ℂ (MatD D₁) (MatD D₂)).comp S.val) := by
  intro x y hxy
  apply Subtype.ext
  apply Prod.ext
  · have hdiffS : x.1 - y.1 ∈ S := S.sub_mem x.2 y.2
    have hsecond : x.1.2 - y.1.2 = 0 := sub_eq_zero.mpr hxy
    have haxis : x.1.1 - y.1.1 ∈ leftAxisIdealHetero S hfst := by
      have hdiff : x.1 - y.1 = (x.1.1 - y.1.1, 0) := by
        apply Prod.ext
        · rfl
        · exact hsecond
      simpa [leftAxisIdealHetero] using (hdiff ▸ hdiffS)
    have hbot : x.1.1 - y.1.1 ∈ (⊥ : TwoSidedIdeal (MatD D₁)) := by
      simpa [hleft] using haxis
    exact sub_eq_zero.mp (by simpa using hbot)
  · exact hxy

private theorem fstProjectionHetero_surjective_of_map_eq_top {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤) :
    Function.Surjective ((AlgHom.fst ℂ (MatD D₁) (MatD D₂)).comp S.val) := by
  intro x
  have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) := by
    rw [hfst]
    trivial
  rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
  exact ⟨⟨p, hpS⟩, by simpa using hpx⟩

private theorem sndProjectionHetero_surjective_of_map_eq_top {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤) :
    Function.Surjective ((AlgHom.snd ℂ (MatD D₁) (MatD D₂)).comp S.val) := by
  intro y
  have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) := by
    rw [hsnd]
    trivial
  rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
  exact ⟨⟨p, hpS⟩, by simpa using hpy⟩

private theorem matrixAlgEquiv_dim_eq {D₁ D₂ : ℕ}
    (e : MatD D₁ ≃ₐ[ℂ] MatD D₂) :
    D₁ = D₂ := by
  have hfin := LinearEquiv.finrank_eq (e : MatD D₁ ≃ₗ[ℂ] MatD D₂)
  simp [MatD, Module.finrank_matrix, Fintype.card_fin] at hfin
  exact Nat.mul_self_inj.mp hfin

private noncomputable def matrixPairSubalgebra_algEquiv_of_axisIdealsHetero_eq_bot {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hleft : leftAxisIdealHetero S hfst = ⊥)
    (hright : rightAxisIdealHetero S hsnd = ⊥) :
    MatD D₁ ≃ₐ[ℂ] MatD D₂ := by
  let p₁ : S →ₐ[ℂ] MatD D₁ := (AlgHom.fst ℂ (MatD D₁) (MatD D₂)).comp S.val
  let p₂ : S →ₐ[ℂ] MatD D₂ := (AlgHom.snd ℂ (MatD D₁) (MatD D₂)).comp S.val
  have hp₁ : Function.Bijective p₁ :=
    ⟨fstProjectionHetero_injective_of_rightAxisIdeal_eq_bot S hsnd hright,
      fstProjectionHetero_surjective_of_map_eq_top S hfst⟩
  have hp₂ : Function.Bijective p₂ :=
    ⟨sndProjectionHetero_injective_of_leftAxisIdeal_eq_bot S hfst hleft,
      sndProjectionHetero_surjective_of_map_eq_top S hsnd⟩
  let e₁ : S ≃ₐ[ℂ] MatD D₁ := AlgEquiv.ofBijective p₁ hp₁
  let e₂ : S ≃ₐ[ℂ] MatD D₂ := AlgEquiv.ofBijective p₂ hp₂
  exact e₁.symm.trans e₂

/-- A subdirect product of two full matrix algebras of different sizes is the
whole product. -/
theorem subdirect_matrix_pair_eq_top_of_dim_ne {D₁ D₂ : ℕ} [NeZero D₁] [NeZero D₂]
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hdim : D₁ ≠ D₂) :
    S = ⊤ := by
  classical
  haveI : Nonempty (Fin D₁) := Fin.pos_iff_nonempty.mp (Nat.pos_of_neZero D₁)
  haveI : Nonempty (Fin D₂) := Fin.pos_iff_nonempty.mp (Nat.pos_of_neZero D₂)
  haveI : IsSimpleRing (MatD D₁) := IsSimpleRing.matrix (Fin D₁) ℂ
  haveI : IsSimpleRing (MatD D₂) := IsSimpleRing.matrix (Fin D₂) ℂ
  rcases eq_bot_or_eq_top (leftAxisIdealHetero S hfst) with hleft | hleft
  · rcases eq_bot_or_eq_top (rightAxisIdealHetero S hsnd) with hright | hright
    · exact False.elim
        (hdim (matrixAlgEquiv_dim_eq
          (matrixPairSubalgebra_algEquiv_of_axisIdealsHetero_eq_bot
            S hfst hsnd hleft hright)))
    · exact matrixPairSubalgebra_eq_top_of_rightAxisIdealHetero_eq_top S hfst hsnd hright
  · exact matrixPairSubalgebra_eq_top_of_leftAxisIdealHetero_eq_top S hfst hsnd hleft

private theorem fstProjection_surjective_of_map_eq_top {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤) :
    Function.Surjective ((AlgHom.fst ℂ (MatD D) (MatD D)).comp S.val) := by
  intro x
  have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D) (MatD D)) := by
    rw [hfst]
    trivial
  rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
  exact ⟨⟨p, hpS⟩, by simpa using hpx⟩

private theorem sndProjection_surjective_of_map_eq_top {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤) :
    Function.Surjective ((AlgHom.snd ℂ (MatD D) (MatD D)).comp S.val) := by
  intro y
  have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D) (MatD D)) := by
    rw [hsnd]
    trivial
  rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
  exact ⟨⟨p, hpS⟩, by simpa using hpy⟩

/-- If both axis ideals are trivial, a subdirect matrix-pair subalgebra is the
graph of a matrix-algebra automorphism. -/
theorem matrixPairSubalgebra_eq_graph_algEquiv_of_axisIdeals_eq_bot {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤)
    (hleft : leftAxisIdeal S hfst = ⊥)
    (hright : rightAxisIdeal S hsnd = ⊥) :
    ∃ φ : MatD D ≃ₐ[ℂ] MatD D,
      S =
        AlgHom.range
          ((AlgHom.id ℂ (MatD D)).prod (φ : MatD D →ₐ[ℂ] MatD D)) := by
  let p₁ : S →ₐ[ℂ] MatD D := (AlgHom.fst ℂ (MatD D) (MatD D)).comp S.val
  let p₂ : S →ₐ[ℂ] MatD D := (AlgHom.snd ℂ (MatD D) (MatD D)).comp S.val
  have hp₁ : Function.Bijective p₁ :=
    ⟨fstProjection_injective_of_rightAxisIdeal_eq_bot S hsnd hright,
      fstProjection_surjective_of_map_eq_top S hfst⟩
  have hp₂ : Function.Bijective p₂ :=
    ⟨sndProjection_injective_of_leftAxisIdeal_eq_bot S hfst hleft,
      sndProjection_surjective_of_map_eq_top S hsnd⟩
  let e₁ : S ≃ₐ[ℂ] MatD D := AlgEquiv.ofBijective p₁ hp₁
  let e₂ : S ≃ₐ[ℂ] MatD D := AlgEquiv.ofBijective p₂ hp₂
  refine ⟨e₁.symm.trans e₂, ?_⟩
  apply SetLike.ext
  intro z
  constructor
  · intro hz
    let s : S := ⟨z, hz⟩
    refine ⟨z.1, ?_⟩
    apply Prod.ext
    · rfl
    · change (e₁.symm.trans e₂) z.1 = z.2
      have he₁ : e₁ s = z.1 := rfl
      have hs : e₁.symm z.1 = s := by
        simpa [he₁] using e₁.symm_apply_apply s
      calc
        (e₁.symm.trans e₂) z.1 = e₂ (e₁.symm z.1) := rfl
        _ = e₂ s := by rw [hs]
        _ = z.2 := rfl
  · rintro ⟨x, rfl⟩
    have hval :
        (↑(e₁.symm x) : MatD D × MatD D) =
          ((AlgHom.id ℂ (MatD D)).prod (e₁.symm.trans e₂ : MatD D →ₐ[ℂ] MatD D)) x := by
      apply Prod.ext
      · exact e₁.apply_symm_apply x
      · rfl
    simpa [hval] using (e₁.symm x).property

/-- Matrix-pair subdirect products are either the full product or the graph of
a matrix-algebra automorphism. -/
theorem subdirect_matrix_pair_eq_top_or_eq_graph_algEquiv {D : ℕ} [NeZero D]
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤) :
    S = ⊤ ∨
      ∃ φ : MatD D ≃ₐ[ℂ] MatD D,
        S =
          AlgHom.range
            ((AlgHom.id ℂ (MatD D)).prod (φ : MatD D →ₐ[ℂ] MatD D)) := by
  classical
  haveI : Nonempty (Fin D) := Fin.pos_iff_nonempty.mp (Nat.pos_of_neZero D)
  haveI : IsSimpleRing (MatD D) := IsSimpleRing.matrix (Fin D) ℂ
  rcases eq_bot_or_eq_top (leftAxisIdeal S hfst) with hleft | hleft
  · rcases eq_bot_or_eq_top (rightAxisIdeal S hsnd) with hright | hright
    · exact Or.inr
        (matrixPairSubalgebra_eq_graph_algEquiv_of_axisIdeals_eq_bot
          S hfst hsnd hleft hright)
    · exact Or.inl (matrixPairSubalgebra_eq_top_of_rightAxisIdeal_eq_top S hfst hsnd hright)
  · exact Or.inl (matrixPairSubalgebra_eq_top_of_leftAxisIdeal_eq_top S hfst hsnd hleft)

/-- A finite word pair belongs to the homogeneous pair span at its own length. -/
theorem pairEvalWordTuple_mem_span_pairWordTuple_length {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) (w : List (Fin d)) :
    pairEvalWordTuple A B w ∈
      Submodule.span ℂ (Set.range (pairWordTuple A B w.length)) := by
  apply Submodule.subset_span
  exact ⟨w.get, by simp [pairWordTuple, pairEvalWordTuple, List.ofFn_get]⟩

/-- Homogeneous pair spans are closed under componentwise multiplication, with
word lengths adding. -/
theorem pair_mul_mem_span_pairWordTuple_add {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) {L S : ℕ}
    {M N : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ}
    (hM : M ∈ Submodule.span ℂ (Set.range (pairWordTuple A B L)))
    (hN : N ∈ Submodule.span ℂ (Set.range (pairWordTuple A B S))) :
    (M.1 * N.1, M.2 * N.2) ∈
      Submodule.span ℂ (Set.range (pairWordTuple A B (L + S))) := by
  classical
  let spanLS : Submodule ℂ
      (Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ) :=
    Submodule.span ℂ (Set.range (pairWordTuple A B (L + S)))
  have hleft_gen : ∀ u : Fin L → Fin d,
      ((pairWordTuple A B L u).1 * N.1, (pairWordTuple A B L u).2 * N.2) ∈
        spanLS := by
    intro u
    induction hN using Submodule.span_induction with
    | mem N' hNmem =>
        rcases hNmem with ⟨v, rfl⟩
        have hEq :
            ((pairWordTuple A B L u).1 * (pairWordTuple A B S v).1,
                (pairWordTuple A B L u).2 * (pairWordTuple A B S v).2) =
              pairWordTuple A B (L + S) (Fin.append u v) := by
          ext <;> simp [pairWordTuple, List.ofFn_fin_append, evalWord_append]
        rw [hEq]
        exact Submodule.subset_span ⟨Fin.append u v, rfl⟩
    | zero =>
        let PairMat := Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ
        have hzero :
            ((pairWordTuple A B L u).1 * (0 : PairMat).1,
              (pairWordTuple A B L u).2 * (0 : PairMat).2) = 0 := by
          simp [PairMat]
        rw [hzero]
        exact Submodule.zero_mem _
    | add N₁ N₂ _ _ hN₁ hN₂ =>
        have hEq :
            ((pairWordTuple A B L u).1 * (N₁ + N₂).1,
              (pairWordTuple A B L u).2 * (N₁ + N₂).2) =
              ((pairWordTuple A B L u).1 * N₁.1,
                (pairWordTuple A B L u).2 * N₁.2) +
              ((pairWordTuple A B L u).1 * N₂.1,
                (pairWordTuple A B L u).2 * N₂.2) := by
          ext <;> simp [Matrix.mul_add]
        rw [hEq]
        exact Submodule.add_mem _ hN₁ hN₂
    | smul a N _ hN =>
        have hEq :
            ((pairWordTuple A B L u).1 * (a • N).1,
              (pairWordTuple A B L u).2 * (a • N).2) =
              a • ((pairWordTuple A B L u).1 * N.1,
                (pairWordTuple A B L u).2 * N.2) := by
          ext <;> simp
        rw [hEq]
        exact Submodule.smul_mem _ a hN
  induction hM using Submodule.span_induction with
  | mem M hMmem =>
      rcases hMmem with ⟨u, rfl⟩
      exact hleft_gen u
  | zero =>
      have hzero :
          ((0 : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ).1 * N.1,
            (0 : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ).2 * N.2)
            = 0 := by
        simp
      rw [hzero]
      exact Submodule.zero_mem _
  | add M₁ M₂ _ _ hM₁ hM₂ =>
      have hEq : ((M₁ + M₂).1 * N.1, (M₁ + M₂).2 * N.2) =
          (M₁.1 * N.1, M₁.2 * N.2) + (M₂.1 * N.1, M₂.2 * N.2) := by
        ext <;> simp [Matrix.add_mul]
      rw [hEq]
      exact Submodule.add_mem _ hM₁ hM₂
  | smul a M _ hM =>
      have hEq : ((a • M).1 * N.1, (a • M).2 * N.2) =
          a • (M.1 * N.1, M.2 * N.2) := by
        ext <;> simp
      rw [hEq]
      exact Submodule.smul_mem _ a hM

/-- The simultaneous pair identity lies in the homogeneous span of length zero. -/
theorem pairIdentity_mem_pairWordTupleSpan_zero {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) :
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B 0)) := by
  apply Submodule.subset_span
  refine ⟨(fun i : Fin 0 => Fin.elim0 i), ?_⟩
  ext <;> simp [pairWordTuple]

/-- Homogeneous identity padding is closed under adding word lengths. -/
theorem pairIdentity_mem_pairWordTupleSpan_add {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) {m n : ℕ}
    (hm :
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B m)))
    (hn :
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B n))) :
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B (m + n))) := by
  simpa using
    pair_mul_mem_span_pairWordTuple_add (A := A) (B := B)
      (L := m) (S := n)
      (M := ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)))
      (N := ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)))
      hm hn

/-- Once the simultaneous pair identity is available at a period length, it is
available at every multiple of that period. -/
theorem pairIdentity_mem_pairWordTupleSpan_mul {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) {period : ℕ}
    (hperiod :
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B period))) :
      ∀ k : ℕ,
        ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
          Submodule.span ℂ (Set.range (pairWordTuple A B (k * period)))
  | 0 => by
      rw [Nat.zero_mul]
      exact pairIdentity_mem_pairWordTupleSpan_zero A B
  | k + 1 => by
      have hk :
          ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
            Submodule.span ℂ (Set.range (pairWordTuple A B (k * period))) :=
        pairIdentity_mem_pairWordTupleSpan_mul (A := A) (B := B) hperiod k
      have hstep :=
        pairIdentity_mem_pairWordTupleSpan_add (A := A) (B := B)
          (m := k * period) (n := period) hk hperiod
      rw [Nat.succ_mul]
      exact hstep

/-- A residue-window padding certificate extends along any number of period
steps. This is the arithmetic shell needed by the corrected Burnside-Jacobson
identity-padding route. -/
theorem pairIdentity_mem_pairWordTupleSpan_add_mul {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) {base period : ℕ}
    (hbase :
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B base)))
    (hperiod :
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B period))) :
      ∀ k : ℕ,
        ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
          Submodule.span ℂ (Set.range (pairWordTuple A B (base + k * period))) := by
  intro k
  exact pairIdentity_mem_pairWordTupleSpan_add (A := A) (B := B)
    (m := base) (n := k * period) hbase
    (pairIdentity_mem_pairWordTupleSpan_mul (A := A) (B := B) hperiod k)

/-- If the homogeneous pair span is already full at length `n`, then it contains
the simultaneous pair identity at length `n`. -/
theorem pairIdentity_mem_pairWordTupleSpan_of_pairWordTupleSpanTop {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) {n : ℕ}
    (hSpan : PairWordTupleSpanTop A B n) :
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B n)) := by
  rw [hSpan]
  exact Submodule.mem_top

/-- A finite residue window plus one period supplies identity padding at every
sufficiently large length. -/
theorem pairIdentity_mem_pairWordTupleSpan_eventually_of_period_window {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    {start period : ℕ} (hperiod_pos : 0 < period)
    (hperiod :
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B period)))
    (hwindow : ∀ r : ℕ, r < period →
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B (start + r)))) :
    ∃ L : ℕ, ∀ n : ℕ, n ≥ L →
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B n)) := by
  refine ⟨start, ?_⟩
  intro n hn
  let r := (n - start) % period
  let k := (n - start) / period
  have hr : r < period := by
    exact Nat.mod_lt _ hperiod_pos
  have hbase :
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B (start + r))) :=
    hwindow r hr
  have hpad :=
    pairIdentity_mem_pairWordTupleSpan_add_mul (A := A) (B := B)
      (base := start + r) (period := period) hbase hperiod k
  have hlen : start + r + k * period = n := by
    dsimp [r, k]
    rw [Nat.add_assoc]
    rw [Nat.mul_comm ((n - start) / period) period]
    rw [Nat.mod_add_div]
    exact Nat.add_sub_of_le hn
  rw [← hlen]
  exact hpad

/-- A finite residue window of full homogeneous pair spans gives eventual
identity padding. -/
theorem pairIdentity_mem_pairWordTupleSpan_eventually_of_pairWordTupleSpanTop_period_window
    {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    {start period : ℕ} (hperiod_pos : 0 < period)
    (hperiod : PairWordTupleSpanTop A B period)
    (hwindow : ∀ r : ℕ, r < period → PairWordTupleSpanTop A B (start + r)) :
    ∃ L : ℕ, ∀ n : ℕ, n ≥ L →
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B n)) :=
  pairIdentity_mem_pairWordTupleSpan_eventually_of_period_window
    (A := A) (B := B) hperiod_pos
    (pairIdentity_mem_pairWordTupleSpan_of_pairWordTupleSpanTop A B hperiod)
    (fun r hr =>
      pairIdentity_mem_pairWordTupleSpan_of_pairWordTupleSpanTop A B (hwindow r hr))

/-- A cumulative pair span can be homogenized once the simultaneous pair identity
is available at every padding length needed to reach the target length.

The padding hypothesis is the Burnside-Jacobson input deferred to a later step. -/
theorem pairWordTupleSpanTop_of_pairCumulativeWordTupleSpanTop_of_identity_padding
    {D₁ D₂ : ℕ} (A : MPSTensor d D₁) (B : MPSTensor d D₂) {S T : ℕ}
    (hST : S ≤ T)
    (hCum : PairCumulativeWordTupleSpanTop A B S)
    (hPad : ∀ l : ℕ, l ≤ S →
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B (T - l)))) :
    PairWordTupleSpanTop A B T := by
  classical
  unfold PairWordTupleSpanTop
  apply eq_top_iff.mpr
  intro M _
  have hM : M ∈ pairCumulativeSpan A B S := by
    rw [hCum]
    exact Submodule.mem_top
  suffices hle : pairCumulativeSpan A B S ≤
      Submodule.span ℂ (Set.range (pairWordTuple A B T)) from hle hM
  apply Submodule.span_le.mpr
  rintro N ⟨w, hwS, rfl⟩
  have hwT : w.length ≤ T := le_trans hwS hST
  have hword :
      pairEvalWordTuple A B w ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B w.length)) :=
    pairEvalWordTuple_mem_span_pairWordTuple_length A B w
  have hmul :=
    pair_mul_mem_span_pairWordTuple_add (A := A) (B := B)
      (L := w.length) (S := T - w.length)
      (M := pairEvalWordTuple A B w)
      (N := ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)))
      hword (hPad w.length hwS)
  have hlen : w.length + (T - w.length) = T := Nat.add_sub_of_le hwT
  have hprod :
      ((pairEvalWordTuple A B w).1 * (1 : Matrix (Fin D₁) (Fin D₁) ℂ),
        (pairEvalWordTuple A B w).2 * (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) =
        pairEvalWordTuple A B w := by
    ext <;> simp
  rw [hlen] at hmul
  simpa [hprod] using hmul

/-- Trace-separation version of
`pairWordTupleSpanTop_of_pairCumulativeWordTupleSpanTop_of_identity_padding`. -/
theorem pairTraceSeparatingAt_of_pairTraceSeparatingUpTo_of_identity_padding
    {D₁ D₂ : ℕ} (A : MPSTensor d D₁) (B : MPSTensor d D₂) {S T : ℕ}
    (hST : S ≤ T)
    (hSep : PairTraceSeparatingUpTo A B S)
    (hPad : ∀ l : ℕ, l ≤ S →
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B (T - l)))) :
    PairTraceSeparatingAt A B T :=
  pairTraceSeparatingAt_of_pairWordTupleSpanTop A B
    (pairWordTupleSpanTop_of_pairCumulativeWordTupleSpanTop_of_identity_padding
      A B hST (pairCumulativeWordTupleSpanTop_of_pairTraceSeparatingUpTo A B hSep) hPad)

/-! ### Conditional all-words homogenization -/

/-- All-words pair separation plus eventual homogeneous identity padding gives
one homogeneous pair-trace separating length.

This is the proved interface between the pair-product algebra density theorem
(`PairAllWordsSpanTop`) and the Burnside-Jacobson identity-padding theorem.
It records that once the two independent inputs are available, no additional
BNT-specific argument is needed to obtain `PairTraceSeparatingAt`. -/
theorem exists_pairTraceSeparatingAt_of_pairAllWordsSpanTop_of_identity_padding
    {D₁ D₂ : ℕ} (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hSpan : PairAllWordsSpanTop A B)
    (hPad : ∃ L : ℕ, ∀ n : ℕ, n ≥ L →
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B n))) :
    ∃ T : ℕ, PairTraceSeparatingAt A B T := by
  have hSepAll : PairTraceSeparatingAll A B :=
    pairTraceSeparatingAll_of_pairAllWordsSpanTop A B hSpan
  obtain ⟨S, hSepUpTo⟩ :=
    exists_pairTraceSeparatingUpTo_of_pairTraceSeparatingAll A B hSepAll
  obtain ⟨L, hPadAll⟩ := hPad
  refine ⟨L + S, ?_⟩
  exact pairTraceSeparatingAt_of_pairTraceSeparatingUpTo_of_identity_padding
    A B (S := S) (T := L + S) (by omega) hSepUpTo
    (fun l hl => hPadAll (L + S - l) (by omega))

/-! ### Burnside–Jacobson homogenization: from non-equivalence to homogeneous separation

The theorems in this section bridge the gap between BNT block non-equivalence
(`¬ GaugePhaseEquiv A B` for injective blocks) and the existence of a homogeneous
length `T` at which `PairTraceSeparatingAt A B T` holds.

**Route A (spectral):**
`¬ GaugePhaseEquiv` → `spectralRadius(mixedTransfer) < 1` → `mpvOverlap → 0`.
This is the non-decaying overlap argument from the spectral-gap development.

**Route B (algebraic, this section):**
`¬ GaugePhaseEquiv` → `PairTraceSeparatingAll A B` → cumulative finite cutoff
→ homogenization via identity padding.  The identity-padding input is the
remaining Burnside–Jacobson algebraic step deferred to the pair algebra.
-/

/-- **Pair product-algebra density for non-gauge-equivalent injective blocks.**

For two injective blocks of the same bond dimension, if they are not
gauge-phase equivalent then the algebra generated by the simultaneous
one-letter pairs `(A i, B i)` is the full product matrix algebra. -/
theorem pairAlgSpan_eq_top_of_injective_not_gaugePhaseEquiv
    {d D : ℕ} [NeZero D]
    (A B : MPSTensor d D)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hNot : ¬ GaugePhaseEquiv A B) :
    pairAlgSpan A B =
      (⊤ : Subalgebra ℂ (MatD D × MatD D)) := by
  have hfst := pairAlgSpan_map_fst_eq_top_of_isInjective A B hA_inj
  have hsnd := pairAlgSpan_map_snd_eq_top_of_isInjective A B hB_inj
  rcases subdirect_matrix_pair_eq_top_or_eq_graph_algEquiv
      (pairAlgSpan A B) hfst hsnd with htop | hgraph
  · exact htop
  · rcases hgraph with ⟨φ, hφ⟩
    exact False.elim
      ((not_pairAlgSpan_eq_graph_algEquiv_of_not_gaugePhaseEquiv A B hNot φ) hφ)

/-- **Pair product-algebra density for injective blocks of unequal dimensions.**

If the two blocks are individually injective and have different bond
dimensions, the simultaneous pair algebra is the full product algebra.  The
subdirect-product graph branch would give an algebra equivalence between the
two full matrix algebras, which is impossible because their finite dimensions
over `ℂ` are `D₁^2` and `D₂^2`. -/
theorem pairAlgSpan_eq_top_of_injective_dim_ne
    {d D₁ D₂ : ℕ} [NeZero D₁] [NeZero D₂]
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hdim : D₁ ≠ D₂) :
    pairAlgSpan A B =
      (⊤ : Subalgebra ℂ (MatD D₁ × MatD D₂)) := by
  have hfst := pairAlgSpan_map_fst_eq_top_of_isInjective A B hA_inj
  have hsnd := pairAlgSpan_map_snd_eq_top_of_isInjective A B hB_inj
  exact subdirect_matrix_pair_eq_top_of_dim_ne (pairAlgSpan A B) hfst hsnd hdim

/-- **BNT non-equivalence ⇒ all-length pair trace separation.**
For injective, left-canonical tensors `A, B` of the same dimension that are
not gauge-phase-equivalent, no nonzero pair of test matrices `(ΔA, ΔB)` can
annihilate the pair-trace pairing `tr(ΔA·evalWord A w) + tr(ΔB·evalWord B w)`
for all words `w`.

The proof should analyze the pair product algebra
`S := alg{(Aᵢ, Bᵢ) | i}` inside `M_{D}(ℂ) × M_{D}(ℂ)`.  Because `A` and `B`
are individually injective, the two coordinate projections of `S` are the full
matrix algebra.  A subdirect-product argument then leaves two possibilities:
either a coordinate kernel supplies the two axes and hence `S = M_D × M_D`, or
`S` is the graph of an algebra automorphism of `M_D`.  In the graph case,
Skolem–Noether turns the automorphism into a gauge equivalence, contradicting
the non-gauge-equivalence hypothesis.  The full-product conclusion is exactly
the statement that the pair word tuples over all word lengths span the full
product algebra.  By duality this is `PairTraceSeparatingAll`.

The theorem applies the matrix-pair subdirect-product dichotomy to the pair
algebra generated by the simultaneous one-letter pairs. -/
theorem pairTraceSeparatingAll_of_injective_not_gaugePhaseEquiv
    {d D : ℕ} [NeZero D]
    (A B : MPSTensor d D)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (_hA_norm : ∑ i : Fin d, (A i)ᴴ * A i = 1)
    (_hB_norm : ∑ i : Fin d, (B i)ᴴ * B i = 1)
    (hNot : ¬ GaugePhaseEquiv A B) :
    PairTraceSeparatingAll A B := by
  have hPairSpanTop : PairAllWordsSpanTop A B := by
    exact pairAllWordsSpanTop_of_pairAlgSpan_eq_top A B
      (pairAlgSpan_eq_top_of_injective_not_gaugePhaseEquiv A B hA_inj hB_inj hNot)
  exact pairTraceSeparatingAll_of_pairAllWordsSpanTop A B hPairSpanTop

/-- **Dimension mismatch ⇒ all-length pair trace separation.**

For injective blocks with different bond dimensions, no nonzero pair of test
matrices can annihilate all simultaneous pair words.  This is the unequal-size
branch needed before the BNT finite-maximum assembly: the pair algebra is the
full product algebra by `pairAlgSpan_eq_top_of_injective_dim_ne`, and the
all-words product span is dual to `PairTraceSeparatingAll`. -/
theorem pairTraceSeparatingAll_of_injective_dim_ne
    {d D₁ D₂ : ℕ} [NeZero D₁] [NeZero D₂]
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hdim : D₁ ≠ D₂) :
    PairTraceSeparatingAll A B := by
  have hPairSpanTop : PairAllWordsSpanTop A B := by
    exact pairAllWordsSpanTop_of_pairAlgSpan_eq_top A B
      (pairAlgSpan_eq_top_of_injective_dim_ne A B hA_inj hB_inj hdim)
  exact pairTraceSeparatingAll_of_pairAllWordsSpanTop A B hPairSpanTop

/-- Unequal bond dimensions plus a finite period-window of homogeneous pair spans
give one homogeneous pair trace-separating length.

The dimension mismatch supplies all-words pair trace separation.  The
period-window span hypothesis supplies the identity padding needed to convert
that cumulative separation into a single homogeneous length. -/
theorem exists_pairTraceSeparatingAt_of_injective_dim_ne_of_pairWordTupleSpanTop_period_window
    {d D₁ D₂ : ℕ} [NeZero D₁] [NeZero D₂]
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hdim : D₁ ≠ D₂)
    {start period : ℕ} (hperiod_pos : 0 < period)
    (hperiod : PairWordTupleSpanTop A B period)
    (hwindow : ∀ r : ℕ, r < period → PairWordTupleSpanTop A B (start + r)) :
    ∃ T : ℕ, PairTraceSeparatingAt A B T := by
  apply exists_pairTraceSeparatingAt_of_pairAllWordsSpanTop_of_identity_padding
  · exact (pairAllWordsSpanTop_iff_pairTraceSeparatingAll A B).2
      (pairTraceSeparatingAll_of_injective_dim_ne A B hA_inj hB_inj hdim)
  · exact pairIdentity_mem_pairWordTupleSpan_eventually_of_pairWordTupleSpanTop_period_window
      A B hperiod_pos hperiod hwindow

/-- Placeholder for the Burnside–Jacobson identity-padding lemma.
Once proved, it supplies the missing input to
`pairTraceSeparatingAt_of_pairTraceSeparatingUpTo_of_identity_padding` and
thereby completes `exists_pairTraceSeparatingAt_of_not_gaugePhaseEquiv`.

The statement: for injective, non-gauge-equivalent tensors `A, B`, there
exists `L` such that the pair identity `(1, 1)` belongs to the homogeneous
pair word span at every length `≥ L` (or at least at an arithmetic progression
that covers all offsets needed for the padding argument). -/
theorem pairIdentity_mem_pairWordTupleSpan_eventually_of_not_gaugePhaseEquiv
    {d D : ℕ} [NeZero D]
    (A B : MPSTensor d D)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hNot : ¬ GaugePhaseEquiv A B) :
    ∃ L : ℕ, ∀ n : ℕ, n ≥ L →
      ((1 : Matrix (Fin D) (Fin D) ℂ), (1 : Matrix (Fin D) (Fin D) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B n)) := by
  sorry

/-- **Homogeneous pair trace separation from BNT non-equivalence (Route B).**
Under the same hypotheses, there exists a finite homogeneous length `S` such
that `PairTraceSeparatingAt A B S` holds.

The proof chains:
1. `¬ GaugePhaseEquiv` → `PairTraceSeparatingAll` (the lemma above)
2. `PairTraceSeparatingAll` → finite cumulative cutoff `S₀`
3. `PairTraceSeparatingUpTo` + Burnside–Jacobson identity padding
   → homogeneous `PairTraceSeparatingAt T`

The remaining blocker for step 3 is the identity-padding hypothesis: there
must exist a length `L` such that `(1, 1)` lies in the homogeneous pair word
span at every length `≥ L`.  This is the Burnside–Jacobson homogenization
step for the pair product algebra.  The theorem below states the full
conclusion with that step admitted. -/
theorem exists_pairTraceSeparatingAt_of_not_gaugePhaseEquiv
    {d D : ℕ} [NeZero D]
    (A B : MPSTensor d D)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hA_norm : ∑ i : Fin d, (A i)ᴴ * A i = 1)
    (hB_norm : ∑ i : Fin d, (B i)ᴴ * B i = 1)
    (hNot : ¬ GaugePhaseEquiv A B) :
    ∃ T : ℕ, PairTraceSeparatingAt A B T := by
  apply exists_pairTraceSeparatingAt_of_pairAllWordsSpanTop_of_identity_padding
  · have hSepAll : PairTraceSeparatingAll A B :=
      pairTraceSeparatingAll_of_injective_not_gaugePhaseEquiv
        A B hA_inj hB_inj hA_norm hB_norm hNot
    exact (pairAllWordsSpanTop_iff_pairTraceSeparatingAll A B).2 hSepAll
  · exact pairIdentity_mem_pairWordTupleSpan_eventually_of_not_gaugePhaseEquiv
      A B hA_inj hB_inj hNot

end MPSTensor
