/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import Mathlib.Algebra.Star.Subalgebra
import Mathlib.Data.Matrix.Basis
import Mathlib.LinearAlgebra.Basis.VectorSpace
import QICLean.Algebra.MatrixKroneckerEmbed
import QICLean.Algebra.OperatorBlock
import QICLean.Channel.OperatorSystem

/-!
# Support algebras of bipartite matrix algebras

For a star-subalgebra `A ⊆ M_m(ℂ) ⊗ M_n(ℂ)`, this file defines its left and
right support algebras. They are generated by the coefficient matrices obtained by fixing
the two indices in the complementary tensor factor.

The main statements are the full-matrix specialization of Gross--Nesme--Vogts--Werner,
Lemma `lem:spp`: the support algebra is the least star-subalgebra needed on the chosen
factor, and its commutant consists exactly of matrices whose identity extension commutes
with the original algebra.

## Main definitions

* `Matrix.kroneckerSubmodule`: the span of Kronecker products from two matrix submodules.
* `StarSubalgebra.leftCoefficientSet`: coefficient matrices on the first factor.
* `StarSubalgebra.rightCoefficientSet`: coefficient matrices on the second factor.
* `StarSubalgebra.leftSupportAlgebra`: support algebra on the first factor.
* `StarSubalgebra.rightSupportAlgebra`: support algebra on the second factor.

## Main statements

* `Matrix.eq_sum_bipartiteSlice_kronecker_single`: reconstruction from first-factor
  coefficients.
* `Matrix.eq_sum_single_kronecker_operatorBlock`: reconstruction from second-factor
  coefficients.
* `StarSubalgebra.leftSupportAlgebra_le_iff`: leastness on the first factor.
* `StarSubalgebra.rightSupportAlgebra_le_iff`: leastness on the second factor.
* `StarSubalgebra.centralizer_leftSupportAlgebra`: the first-factor commutant formula.
* `StarSubalgebra.centralizer_rightSupportAlgebra`: the second-factor commutant formula.
* `StarSubalgebra.le_kroneckerSubmodule_supportAlgebras`: the two-sided containment.

## References

* D. Gross, V. Nesme, H. Vogts, and R. F. Werner, arXiv:0910.3675,
  Lemma `lem:spp` and equation `a2Supp`.
* B. Schumacher and R. F. Werner, arXiv:quant-ph/0405174,
  Section `sec:supp`, equations `a2supp` and `a2Supp`.
-/

open scoped BigOperators Kronecker

namespace Matrix

/-- The tensor-product submodule generated by Kronecker products with factors in `S` and `T`.

This is the concrete matrix realization of the two-factor linear space used in
arXiv:0910.3675, equation `a2Supp`, lines 1211--1219. -/
def kroneckerSubmodule {m n : Type*}
    (S : Submodule ℂ (Matrix m m ℂ)) (T : Submodule ℂ (Matrix n n ℂ)) :
    Submodule ℂ (Matrix (m × n) (m × n) ℂ) :=
  Submodule.span ℂ
    {X | ∃ L ∈ S, ∃ R ∈ T, L ⊗ₖ R = X}

/-- A Kronecker product of members of the two factors belongs to their
tensor-product submodule. -/
theorem kronecker_mem_kroneckerSubmodule {m n : Type*}
    (S : Submodule ℂ (Matrix m m ℂ)) (T : Submodule ℂ (Matrix n n ℂ))
    {L : Matrix m m ℂ} {R : Matrix n n ℂ} (hL : L ∈ S) (hR : R ∈ T) :
    L ⊗ₖ R ∈ kroneckerSubmodule S T :=
  Submodule.subset_span ⟨L, hL, R, hR, rfl⟩

variable {m n : Type*} [Fintype m] [DecidableEq m] [Fintype n] [DecidableEq n]

omit [Fintype m] [DecidableEq m] in
/-- A bipartite matrix is reconstructed by expanding the second factor in matrix units.

This is the full-matrix form of the coefficient expansion
`a = ∑_μ a_μ ⊗ e_μ` in arXiv:0910.3675, Lemma `lem:spp`, lines 1188--1191. -/
theorem eq_sum_bipartiteSlice_kronecker_single
    (X : Matrix (m × n) (m × n) ℂ) :
    X = ∑ i : n, ∑ j : n,
      bipartiteSlice X i j ⊗ₖ Matrix.single i j 1 := by
  classical
  apply Matrix.ext
  intro p q
  rcases p with ⟨a, i⟩
  rcases q with ⟨b, j⟩
  simp only [Matrix.sum_apply, Matrix.kroneckerMap_apply,
    Matrix.bipartiteSlice_apply, Matrix.single_apply]
  rw [← Fintype.sum_prod_type']
  simp [← Prod.mk_inj]

omit [Fintype n] [DecidableEq n] in
/-- A bipartite matrix is reconstructed by expanding the first factor in matrix units.

This is the factor-swapped full-matrix form of the coefficient expansion in
arXiv:0910.3675, Lemma `lem:spp`, lines 1188--1191 and equation `a2Supp`,
lines 1211--1219. -/
theorem eq_sum_single_kronecker_operatorBlock
    (X : Matrix (m × n) (m × n) ℂ) :
    X = ∑ i : m, ∑ j : m,
      Matrix.single i j 1 ⊗ₖ operatorBlock X i j := by
  classical
  apply Matrix.ext
  intro p q
  rcases p with ⟨i, a⟩
  rcases q with ⟨j, b⟩
  simp only [Matrix.sum_apply, Matrix.kroneckerMap_apply,
    Matrix.operatorBlock_apply, Matrix.single_apply]
  rw [← Fintype.sum_prod_type']
  simp [← Prod.mk_inj]

omit [Fintype m] [DecidableEq m] [Fintype n] [DecidableEq n] in
/-- After swapping the tensor factors, a first-factor slice is an operator block.

This is the coordinate swap used for the second support algebra in arXiv:0910.3675,
equation `a2Supp`, lines 1211--1219. -/
theorem bipartiteSlice_submatrix_swap
    (X : Matrix (m × n) (m × n) ℂ) (i j : m) :
    bipartiteSlice (X.submatrix Prod.swap Prod.swap) i j =
      operatorBlock X i j := by
  rfl

omit [Fintype m] [DecidableEq m] [Fintype n] [DecidableEq n] in
/-- If all first-factor coefficients of `X` lie in `S` and all second-factor
coefficients lie in `T`, then `X` lies in the submodule generated by products
`L ⊗ R` with `L ∈ S` and `R ∈ T`.

This is the finite full-matrix double-coefficient argument underlying
arXiv:0910.3675, equation `a2Supp`, lines 1211--1219. -/
theorem mem_kroneckerSubmodule_of_bipartiteSlice_mem_of_operatorBlock_mem
    [Finite m]
    (S : Submodule ℂ (Matrix m m ℂ)) (T : Submodule ℂ (Matrix n n ℂ))
    (X : Matrix (m × n) (m × n) ℂ)
    (hS : ∀ i j : n, bipartiteSlice X i j ∈ S)
    (hT : ∀ i j : m, operatorBlock X i j ∈ T) :
    X ∈ kroneckerSubmodule S T := by
  classical
  let _ := Fintype.ofFinite m
  let b := Module.finBasis ℂ S
  let φ (k : Fin (Module.finrank ℂ S)) : S →ₗ[ℂ] ℂ :=
    (Finsupp.lapply k : (Fin (Module.finrank ℂ S) →₀ ℂ) →ₗ[ℂ] ℂ).comp
      b.repr.toLinearMap
  let ψ (k : Fin (Module.finrank ℂ S)) : Matrix m m ℂ →ₗ[ℂ] ℂ :=
    Classical.choose (LinearMap.exists_extend (φ k))
  have hψ (k : Fin (Module.finrank ℂ S)) : (ψ k).comp S.subtype = φ k :=
    Classical.choose_spec (LinearMap.exists_extend (φ k))
  let R (k : Fin (Module.finrank ℂ S)) : Matrix n n ℂ :=
    fun i j ↦ ψ k (bipartiteSlice X i j)
  have hcoord (k : Fin (Module.finrank ℂ S)) (i j : n) :
      R k i j = b.repr ⟨bipartiteSlice X i j, hS i j⟩ k := by
    have hk := congrArg (fun f : S →ₗ[ℂ] ℂ ↦ f ⟨bipartiteSlice X i j, hS i j⟩) (hψ k)
    simpa [R, φ, LinearMap.comp_apply, Finsupp.lapply_apply] using hk
  have hψ_expand (k : Fin (Module.finrank ℂ S)) (M : Matrix m m ℂ) :
      ψ k M = ∑ i : m, ∑ j : m, ψ k (Matrix.single i j 1) * M i j := by
    conv_lhs => rw [Matrix.matrix_eq_sum_single M]
    simp only [map_sum]
    apply Finset.sum_congr rfl
    intro i _
    apply Finset.sum_congr rfl
    intro j _
    have hsingle : Matrix.single i j (M i j) =
        (M i j) • Matrix.single i j (1 : ℂ) := by
      rw [Matrix.smul_single]
      simp
    rw [hsingle, map_smul]
    simp [smul_eq_mul, mul_comm]
  have hR_eq (k : Fin (Module.finrank ℂ S)) :
      R k = ∑ i : m, ∑ j : m,
        ψ k (Matrix.single i j 1) • operatorBlock X i j := by
    apply Matrix.ext
    intro i j
    simpa only [R, Matrix.sum_apply, Matrix.smul_apply,
      Matrix.operatorBlock_apply, Matrix.bipartiteSlice_apply, smul_eq_mul] using
        hψ_expand k (bipartiteSlice X i j)
  have hRT (k : Fin (Module.finrank ℂ S)) : R k ∈ T := by
    rw [hR_eq k]
    exact Submodule.sum_mem _ fun i _ ↦ Submodule.sum_mem _ fun j _ ↦
      T.smul_mem (ψ k (Matrix.single i j 1)) (hT i j)
  have hX_eq : X = ∑ k : Fin (Module.finrank ℂ S),
      (b k : Matrix m m ℂ) ⊗ₖ R k := by
    apply Matrix.ext
    intro p q
    rcases p with ⟨a, i⟩
    rcases q with ⟨c, j⟩
    let Y : S := ⟨bipartiteSlice X i j, hS i j⟩
    have hmatrix : bipartiteSlice X i j =
        ∑ k : Fin (Module.finrank ℂ S),
          b.repr Y k • (b k : Matrix m m ℂ) := by
      have hb := congrArg (fun Z : S ↦ S.subtype Z) (b.sum_repr Y).symm
      simpa only [Y, map_sum, map_smul, Submodule.subtype_apply] using hb
    have hsum := congrFun (congrFun hmatrix a) c
    simp only [Matrix.sum_apply, Matrix.kroneckerMap_apply, hcoord]
    simpa only [Matrix.bipartiteSlice_apply, Matrix.sum_apply,
      Matrix.smul_apply, smul_eq_mul, mul_comm] using hsum
  rw [hX_eq]
  exact Submodule.sum_mem _ fun k _ ↦
    kronecker_mem_kroneckerSubmodule S T (b k).property (hRT k)

/-- Commutation with an identity extension on the right is equivalent to commutation of
every first-factor coefficient matrix.

This is the coefficientwise calculation in arXiv:0910.3675, proof of Lemma `lem:spp`,
lines 1197--1208. -/
theorem mul_leftKroneckerEmbed_eq_iff
    (X : Matrix (m × n) (m × n) ℂ) (B : Matrix m m ℂ) :
    X * leftKroneckerEmbed (n := n) B =
        leftKroneckerEmbed (n := n) B * X ↔
      ∀ i j : n, bipartiteSlice X i j * B = B * bipartiteSlice X i j := by
  classical
  constructor
  · intro h i j
    apply Matrix.ext
    intro a b
    have hentry := congrFun (congrFun h (a, i)) (b, j)
    simpa [Matrix.mul_apply, Matrix.leftKroneckerEmbed_apply,
      Matrix.kroneckerMap_apply, Matrix.one_apply,
      Matrix.bipartiteSlice_apply, Fintype.sum_prod_type] using hentry
  · intro h
    apply Matrix.ext
    intro p q
    rcases p with ⟨a, i⟩
    rcases q with ⟨b, j⟩
    have hentry := congrFun (congrFun (h i j) a) b
    simpa [Matrix.mul_apply, Matrix.leftKroneckerEmbed_apply,
      Matrix.kroneckerMap_apply, Matrix.one_apply,
      Matrix.bipartiteSlice_apply, Fintype.sum_prod_type] using hentry

/-- Commutation with an identity extension on the left is equivalent to commutation of
every second-factor coefficient matrix.

This is the factor-swapped coefficientwise calculation in arXiv:0910.3675, proof of
Lemma `lem:spp`, lines 1197--1208. -/
theorem mul_rightKroneckerEmbed_eq_iff
    (X : Matrix (m × n) (m × n) ℂ) (B : Matrix n n ℂ) :
    X * rightKroneckerEmbed (m := m) B =
        rightKroneckerEmbed (m := m) B * X ↔
      ∀ i j : m, operatorBlock X i j * B = B * operatorBlock X i j := by
  classical
  constructor
  · intro h i j
    apply Matrix.ext
    intro a b
    have hentry := congrFun (congrFun h (i, a)) (j, b)
    simpa [Matrix.mul_apply, Matrix.rightKroneckerEmbed_apply,
      Matrix.kroneckerMap_apply, Matrix.one_apply,
      Matrix.operatorBlock_apply, Fintype.sum_prod_type] using hentry
  · intro h
    apply Matrix.ext
    intro p q
    rcases p with ⟨i, a⟩
    rcases q with ⟨j, b⟩
    have hentry := congrFun (congrFun (h i j) a) b
    simpa [Matrix.mul_apply, Matrix.rightKroneckerEmbed_apply,
      Matrix.kroneckerMap_apply, Matrix.one_apply,
      Matrix.operatorBlock_apply, Fintype.sum_prod_type] using hentry

end Matrix

namespace StarSubalgebra

variable {m n : Type*} [Fintype m] [DecidableEq m] [Fintype n] [DecidableEq n]

/-- The first-factor coefficient matrices of a bipartite star-subalgebra.

This is the matrix-unit specialization of the coefficients `a_μ` in arXiv:0910.3675,
Lemma `lem:spp`, item 2, lines 1188--1191. -/
def leftCoefficientSet
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) : Set (Matrix m m ℂ) :=
  {B | ∃ X ∈ A, ∃ i j : n, Matrix.bipartiteSlice X i j = B}

/-- The second-factor coefficient matrices of a bipartite star-subalgebra.

This is the factor-swapped matrix-unit specialization in arXiv:0910.3675,
Lemma `lem:spp`, item 2, and equation `a2Supp`, lines 1188--1191 and 1211--1219. -/
def rightCoefficientSet
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) : Set (Matrix n n ℂ) :=
  {B | ∃ X ∈ A, ∃ i j : m, Matrix.operatorBlock X i j = B}

/-- The support algebra of a bipartite star-subalgebra on its first matrix factor.

It is generated by all first-factor coefficient matrices, as in arXiv:0910.3675,
Lemma `lem:spp`, items 1--2, lines 1181--1191. -/
def leftSupportAlgebra
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) :
    StarSubalgebra ℂ (Matrix m m ℂ) :=
  StarAlgebra.adjoin ℂ A.leftCoefficientSet

/-- The support algebra of a bipartite star-subalgebra on its second matrix factor.

It is the factor-swapped construction in arXiv:0910.3675, Lemma `lem:spp`, and
equation `a2Supp`, lines 1181--1191 and 1211--1219. -/
def rightSupportAlgebra
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) :
    StarSubalgebra ℂ (Matrix n n ℂ) :=
  StarAlgebra.adjoin ℂ A.rightCoefficientSet

/-- Every first-factor coefficient belongs to the left support algebra.

This is the generator membership implicit in arXiv:0910.3675, Lemma `lem:spp`,
item 2, lines 1188--1191. -/
theorem bipartiteSlice_mem_leftSupportAlgebra
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ))
    {X : Matrix (m × n) (m × n) ℂ} (hX : X ∈ A) (i j : n) :
    Matrix.bipartiteSlice X i j ∈ A.leftSupportAlgebra := by
  apply StarAlgebra.subset_adjoin ℂ A.leftCoefficientSet
  exact ⟨X, hX, i, j, rfl⟩

/-- Every second-factor coefficient belongs to the right support algebra.

This is the factor-swapped generator membership in arXiv:0910.3675,
equation `a2Supp`, lines 1211--1219. -/
theorem operatorBlock_mem_rightSupportAlgebra
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ))
    {X : Matrix (m × n) (m × n) ℂ} (hX : X ∈ A) (i j : m) :
    Matrix.operatorBlock X i j ∈ A.rightSupportAlgebra := by
  apply StarAlgebra.subset_adjoin ℂ A.rightCoefficientSet
  exact ⟨X, hX, i, j, rfl⟩

/-- The left support algebra is the least star-subalgebra containing all first-factor
coefficients.

This is the full-matrix specialization of arXiv:0910.3675, Lemma `lem:spp`,
items 1--2 and their proof, lines 1181--1207. -/
theorem leftSupportAlgebra_le_iff
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ))
    (C : StarSubalgebra ℂ (Matrix m m ℂ)) :
    A.leftSupportAlgebra ≤ C ↔
      ∀ X ∈ A, ∀ i j : n, Matrix.bipartiteSlice X i j ∈ C := by
  change StarAlgebra.adjoin ℂ A.leftCoefficientSet ≤ C ↔ _
  rw [StarAlgebra.adjoin_le_iff]
  constructor
  · intro h X hX i j
    apply h
    exact ⟨X, hX, i, j, rfl⟩
  · intro h B hB
    rcases hB with ⟨X, hX, i, j, rfl⟩
    exact h X hX i j

/-- The right support algebra is the least star-subalgebra containing all second-factor
coefficients.

This is the factor-swapped full-matrix specialization of arXiv:0910.3675,
Lemma `lem:spp` and equation `a2Supp`, lines 1181--1207 and 1211--1219. -/
theorem rightSupportAlgebra_le_iff
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ))
    (C : StarSubalgebra ℂ (Matrix n n ℂ)) :
    A.rightSupportAlgebra ≤ C ↔
      ∀ X ∈ A, ∀ i j : m, Matrix.operatorBlock X i j ∈ C := by
  change StarAlgebra.adjoin ℂ A.rightCoefficientSet ≤ C ↔ _
  rw [StarAlgebra.adjoin_le_iff]
  constructor
  · intro h X hX i j
    apply h
    exact ⟨X, hX, i, j, rfl⟩
  · intro h B hB
    rcases hB with ⟨X, hX, i, j, rfl⟩
    exact h X hX i j

/-- For full finite matrices, leastness of the left support algebra is exactly
containment of every element of `A` in `C ⊗ M_n(ℂ)`.

This is the `Matrix.tensorSubmodule` form of arXiv:0910.3675, Lemma `lem:spp`,
items 1--2, lines 1181--1191. -/
theorem leftSupportAlgebra_le_iff_tensorSubmodule {p q : ℕ}
    (A : StarSubalgebra ℂ
      (Matrix (Fin p × Fin q) (Fin p × Fin q) ℂ))
    (C : StarSubalgebra ℂ (Matrix (Fin p) (Fin p) ℂ)) :
    A.leftSupportAlgebra ≤ C ↔
      ∀ X ∈ A,
        X ∈ Matrix.tensorSubmodule C.toSubalgebra.toSubmodule q := by
  rw [leftSupportAlgebra_le_iff]
  rfl

/-- For full finite matrices, leastness of the right support algebra is the
factor-swapped containment of every element of `A` in `C ⊗ M_p(ℂ)`.

This is the factor-swapped `Matrix.tensorSubmodule` form of arXiv:0910.3675,
equation `a2Supp`, lines 1211--1219. -/
theorem rightSupportAlgebra_le_iff_tensorSubmodule {p q : ℕ}
    (A : StarSubalgebra ℂ
      (Matrix (Fin p × Fin q) (Fin p × Fin q) ℂ))
    (C : StarSubalgebra ℂ (Matrix (Fin q) (Fin q) ℂ)) :
    A.rightSupportAlgebra ≤ C ↔
      ∀ X ∈ A, X.submatrix Prod.swap Prod.swap ∈
        Matrix.tensorSubmodule C.toSubalgebra.toSubmodule p := by
  rw [rightSupportAlgebra_le_iff]
  rfl

/-- Every element of a bipartite algebra lies in the one-sided tensor submodule
defined by its left support algebra.

This is the full-matrix containment in arXiv:0910.3675, Lemma `lem:spp`, item 1,
lines 1181--1187. -/
theorem mem_tensorSubmodule_leftSupportAlgebra {p q : ℕ}
    (A : StarSubalgebra ℂ
      (Matrix (Fin p × Fin q) (Fin p × Fin q) ℂ))
    {X : Matrix (Fin p × Fin q) (Fin p × Fin q) ℂ} (hX : X ∈ A) :
    X ∈ Matrix.tensorSubmodule
      A.leftSupportAlgebra.toSubalgebra.toSubmodule q := by
  exact (leftSupportAlgebra_le_iff_tensorSubmodule A A.leftSupportAlgebra).mp
    le_rfl X hX

/-- Every element of a bipartite algebra lies, after swapping the factors, in
the one-sided tensor submodule defined by its right support algebra.

This is the symmetric containment in arXiv:0910.3675, equation `a2Supp`,
lines 1211--1219. -/
theorem submatrix_swap_mem_tensorSubmodule_rightSupportAlgebra {p q : ℕ}
    (A : StarSubalgebra ℂ
      (Matrix (Fin p × Fin q) (Fin p × Fin q) ℂ))
    {X : Matrix (Fin p × Fin q) (Fin p × Fin q) ℂ} (hX : X ∈ A) :
    X.submatrix Prod.swap Prod.swap ∈ Matrix.tensorSubmodule
      A.rightSupportAlgebra.toSubalgebra.toSubmodule p := by
  exact (rightSupportAlgebra_le_iff_tensorSubmodule A A.rightSupportAlgebra).mp
    le_rfl X hX

/-- Every element of `A` belongs to the tensor-product span of its left and
right support algebras.

This is the full complex matrix-algebra form of arXiv:0910.3675, equation
`a2Supp`, lines 1211--1219. -/
theorem mem_kroneckerSubmodule_supportAlgebras
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ))
    {X : Matrix (m × n) (m × n) ℂ} (hX : X ∈ A) :
    X ∈ Matrix.kroneckerSubmodule
      A.leftSupportAlgebra.toSubalgebra.toSubmodule
      A.rightSupportAlgebra.toSubalgebra.toSubmodule := by
  exact Matrix.mem_kroneckerSubmodule_of_bipartiteSlice_mem_of_operatorBlock_mem
    _ _ X (fun i j ↦ bipartiteSlice_mem_leftSupportAlgebra A hX i j)
      (fun i j ↦ operatorBlock_mem_rightSupportAlgebra A hX i j)

/-- The underlying vector space of `A` is contained in the tensor-product span
of its two support algebras.

This is the star-subalgebra containment in arXiv:0910.3675, equation `a2Supp`,
lines 1211--1219. -/
theorem le_kroneckerSubmodule_supportAlgebras
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) :
    A.toSubalgebra.toSubmodule ≤ Matrix.kroneckerSubmodule
      A.leftSupportAlgebra.toSubalgebra.toSubmodule
      A.rightSupportAlgebra.toSubalgebra.toSubmodule := by
  intro X hX
  exact mem_kroneckerSubmodule_supportAlgebras A hX

/-- The commutant of the left support algebra consists of the matrices whose identity
extension on the right commutes with the original bipartite algebra.

This is the full-matrix specialization of arXiv:0910.3675, Lemma `lem:spp`, item 3,
and its coefficient-expansion proof, lines 1192--1208. -/
theorem centralizer_leftSupportAlgebra
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) :
    StarSubalgebra.centralizer ℂ (A.leftSupportAlgebra : Set (Matrix m m ℂ)) =
      (StarSubalgebra.centralizer ℂ
        (A : Set (Matrix (m × n) (m × n) ℂ))).comap
          (Matrix.leftKroneckerEmbed (m := m) (n := n)) := by
  ext B
  constructor
  · intro hB
    change Matrix.leftKroneckerEmbed (n := n) B ∈
      StarSubalgebra.centralizer ℂ
        (A : Set (Matrix (m × n) (m × n) ℂ))
    rw [StarSubalgebra.mem_centralizer_iff]
    intro X hX
    constructor
    · rw [Matrix.mul_leftKroneckerEmbed_eq_iff]
      intro i j
      exact ((StarSubalgebra.mem_centralizer_iff ℂ).mp hB
        (Matrix.bipartiteSlice X i j)
        (bipartiteSlice_mem_leftSupportAlgebra A hX i j)).1
    · rw [Matrix.mul_leftKroneckerEmbed_eq_iff]
      intro i j
      exact ((StarSubalgebra.mem_centralizer_iff ℂ).mp hB
        (Matrix.bipartiteSlice (star X) i j)
        (bipartiteSlice_mem_leftSupportAlgebra A (star_mem hX) i j)).1
  · intro hB
    have hBstar := star_mem hB
    change Matrix.leftKroneckerEmbed (n := n) B ∈
      StarSubalgebra.centralizer ℂ
        (A : Set (Matrix (m × n) (m × n) ℂ)) at hB
    change Matrix.leftKroneckerEmbed (n := n) (star B) ∈
      StarSubalgebra.centralizer ℂ
        (A : Set (Matrix (m × n) (m × n) ℂ)) at hBstar
    have hcoeff : A.leftCoefficientSet ⊆
        StarSubalgebra.centralizer ℂ ({B} : Set (Matrix m m ℂ)) := by
      intro C hC
      rcases hC with ⟨X, hX, i, j, rfl⟩
      change Matrix.bipartiteSlice X i j ∈
        StarSubalgebra.centralizer ℂ ({B} : Set (Matrix m m ℂ))
      apply (StarSubalgebra.mem_centralizer_iff ℂ).2
      intro C hC
      simp only [Set.mem_singleton_iff] at hC
      subst C
      constructor
      · exact (((Matrix.mul_leftKroneckerEmbed_eq_iff X B).mp
          ((StarSubalgebra.mem_centralizer_iff ℂ).mp hB X hX).1) i j).symm
      · exact (((Matrix.mul_leftKroneckerEmbed_eq_iff X (star B)).mp
          ((StarSubalgebra.mem_centralizer_iff ℂ).mp hBstar X hX).1) i j).symm
    have hsupp : A.leftSupportAlgebra ≤
        StarSubalgebra.centralizer ℂ ({B} : Set (Matrix m m ℂ)) :=
      StarAlgebra.adjoin_le hcoeff
    apply (StarSubalgebra.mem_centralizer_iff ℂ).2
    intro C hC
    have hCB := (StarSubalgebra.mem_centralizer_iff ℂ).mp
      (hsupp hC) B (Set.mem_singleton B)
    have hstarCB := (StarSubalgebra.mem_centralizer_iff ℂ).mp
      (hsupp (star_mem hC)) B (Set.mem_singleton B)
    exact ⟨hCB.1.symm, hstarCB.1.symm⟩

/-- The commutant of the right support algebra consists of the matrices whose identity
extension on the left commutes with the original bipartite algebra.

This is the factor-swapped full-matrix specialization of arXiv:0910.3675,
Lemma `lem:spp`, item 3, and equation `a2Supp`, lines 1192--1219. -/
theorem centralizer_rightSupportAlgebra
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) :
    StarSubalgebra.centralizer ℂ (A.rightSupportAlgebra : Set (Matrix n n ℂ)) =
      (StarSubalgebra.centralizer ℂ
        (A : Set (Matrix (m × n) (m × n) ℂ))).comap
          (Matrix.rightKroneckerEmbed (m := m) (n := n)) := by
  ext B
  constructor
  · intro hB
    change Matrix.rightKroneckerEmbed (m := m) B ∈
      StarSubalgebra.centralizer ℂ
        (A : Set (Matrix (m × n) (m × n) ℂ))
    rw [StarSubalgebra.mem_centralizer_iff]
    intro X hX
    constructor
    · rw [Matrix.mul_rightKroneckerEmbed_eq_iff]
      intro i j
      exact ((StarSubalgebra.mem_centralizer_iff ℂ).mp hB
        (Matrix.operatorBlock X i j)
        (operatorBlock_mem_rightSupportAlgebra A hX i j)).1
    · rw [Matrix.mul_rightKroneckerEmbed_eq_iff]
      intro i j
      exact ((StarSubalgebra.mem_centralizer_iff ℂ).mp hB
        (Matrix.operatorBlock (star X) i j)
        (operatorBlock_mem_rightSupportAlgebra A (star_mem hX) i j)).1
  · intro hB
    have hBstar := star_mem hB
    change Matrix.rightKroneckerEmbed (m := m) B ∈
      StarSubalgebra.centralizer ℂ
        (A : Set (Matrix (m × n) (m × n) ℂ)) at hB
    change Matrix.rightKroneckerEmbed (m := m) (star B) ∈
      StarSubalgebra.centralizer ℂ
        (A : Set (Matrix (m × n) (m × n) ℂ)) at hBstar
    have hcoeff : A.rightCoefficientSet ⊆
        StarSubalgebra.centralizer ℂ ({B} : Set (Matrix n n ℂ)) := by
      intro C hC
      rcases hC with ⟨X, hX, i, j, rfl⟩
      change Matrix.operatorBlock X i j ∈
        StarSubalgebra.centralizer ℂ ({B} : Set (Matrix n n ℂ))
      apply (StarSubalgebra.mem_centralizer_iff ℂ).2
      intro C hC
      simp only [Set.mem_singleton_iff] at hC
      subst C
      constructor
      · exact (((Matrix.mul_rightKroneckerEmbed_eq_iff X B).mp
          ((StarSubalgebra.mem_centralizer_iff ℂ).mp hB X hX).1) i j).symm
      · exact (((Matrix.mul_rightKroneckerEmbed_eq_iff X (star B)).mp
          ((StarSubalgebra.mem_centralizer_iff ℂ).mp hBstar X hX).1) i j).symm
    have hsupp : A.rightSupportAlgebra ≤
        StarSubalgebra.centralizer ℂ ({B} : Set (Matrix n n ℂ)) :=
      StarAlgebra.adjoin_le hcoeff
    apply (StarSubalgebra.mem_centralizer_iff ℂ).2
    intro C hC
    have hCB := (StarSubalgebra.mem_centralizer_iff ℂ).mp
      (hsupp hC) B (Set.mem_singleton B)
    have hstarCB := (StarSubalgebra.mem_centralizer_iff ℂ).mp
      (hsupp (star_mem hC)) B (Set.mem_singleton B)
    exact ⟨hCB.1.symm, hstarCB.1.symm⟩

end StarSubalgebra
