/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import TNLean.MPS.Defs

import Mathlib.Algebra.Algebra.Subalgebra.Lattice

-- Burnside / Jacobson density ingredients
import Mathlib.LinearAlgebra.Matrix.ToLin
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.RingTheory.SimpleRing.Matrix
import Mathlib.RepresentationTheory.AlgebraRepresentation.Basic
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.Algebra.Module.Submodule.RestrictScalars
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.LinearAlgebra.FreeModule.Finite.Basic

/-!
# Burnside theorem for matrix algebras

This file proves the Burnside/Jacobson density theorem for the subalgebra of
`Matrix (Fin D) (Fin D) ℂ` generated by the Kraus operators of an MPS tensor.

The main result is `MPSTensor.burnside_matrix`:
if a family of matrices `A : MPSTensor d D` acts irreducibly on `ℂ^D` (no nontrivial invariant
submodule), then the unital subalgebra they generate is all of `M_D(ℂ)`.

The proof follows the standard strategy:

* transport matrices to `Module.End ℂ (Fin D → ℂ)` via `Matrix.toLinAlgEquiv'`,
* use `IsIrreducibleAction` to obtain a simple module,
* apply Schur's lemma over the algebraically closed field `ℂ`,
* use Jacobson density (`Module.Finite.toModuleEnd_moduleEnd_surjective`) to conclude surjectivity
  onto all endomorphisms.
-/

open scoped Matrix

namespace MPSTensor

variable {d D : ℕ}

/-! ## Definitions: algebra span and irreducible action -/

/-- The unital subalgebra of `M_D(ℂ)` generated by the Kraus operators. -/
def algSpan (A : MPSTensor d D) : Subalgebra ℂ (Matrix (Fin D) (Fin D) ℂ) :=
  Algebra.adjoin ℂ (Set.range A)

/-- Each Kraus operator is in the algebra span. -/
theorem algSpan_mem (A : MPSTensor d D) (i : Fin d) : A i ∈ algSpan A :=
  Algebra.subset_adjoin ⟨i, rfl⟩

/-- A submodule `W` of `ℂ^D` is `A`-invariant if every `A i` maps `W` into itself. -/
def IsInvariantSubmodule (A : MPSTensor d D) (W : Submodule ℂ (Fin D → ℂ)) : Prop :=
  ∀ i : Fin d, ∀ v ∈ W, (A i).mulVec v ∈ W

/-- The irreducible-action condition: no nontrivial `A`-invariant submodule. -/
def IsIrreducibleAction (A : MPSTensor d D) : Prop :=
  ∀ W : Submodule ℂ (Fin D → ℂ), IsInvariantSubmodule A W → W = ⊥ ∨ W = ⊤

/-! ## Burnside's theorem (Jacobson density + Schur) -/

/-- **Burnside/Jacobson density theorem (matrix form)**.

If the Kraus operators of `A : MPSTensor d D` act irreducibly on `ℂ^D` (in the sense
`IsIrreducibleAction`), then the unital subalgebra they generate is all of `M_D(ℂ)`.

Implementation outline:
* Transport `algSpan A` along `Matrix.toLinAlgEquiv'` to a subalgebra of `Module.End ℂ (Fin D → ℂ)`.
* `IsIrreducibleAction` gives a simple module.
* Schur (over an algebraically closed field) identifies the commuting endomorphisms with scalars.
* Jacobson density then forces surjectivity onto all endomorphisms.
-/
theorem burnside_matrix [NeZero D]
    (A : MPSTensor d D) (hIrr : IsIrreducibleAction (d := d) (D := D) A) :
    algSpan (d := d) (D := D) A = ⊤ := by
  classical
  -- `V = ℂ^D`
  let V : Type := Fin D → ℂ
  -- matrices as endomorphisms of `V`
  let φ : Matrix (Fin D) (Fin D) ℂ →ₐ[ℂ] Module.End ℂ V :=
    (Matrix.toLinAlgEquiv' :
        Matrix (Fin D) (Fin D) ℂ ≃ₐ[ℂ] (V →ₗ[ℂ] V)).toAlgHom
  -- image of the generated matrix algebra inside `End(V)`
  let R : Subalgebra ℂ (Module.End ℂ V) := (algSpan A).map φ
  -- `End(V)` acts on `V` by evaluation, and we restrict this action to the subalgebra `R`.
  letI : Module (Module.End ℂ V) V := Module.End.applyModule
  letI : Module R V :=
    Subalgebra.moduleLeft (R := ℂ) (A := Module.End ℂ V) (α := V) R
  -- Scalar tower `ℂ → R → V` for the evaluation action.
  -- Needed for `Submodule.restrictScalars` and for Schur's lemma.
  -- (Typeclass inference times out otherwise.)
  letI : IsScalarTower ℂ R V := by
    refine ⟨?_⟩
    intro c r v
    -- Do not let simp use `smul_assoc` here: it would request this very instance.
    simp only [Subalgebra.smul_def, Module.End.smul_def, Subalgebra.coe_smul,
      LinearMap.smul_apply]
  -- The `R`-action commutes with scalar multiplication by `ℂ` since elements of `R` are
  -- `ℂ`-linear endomorphisms.
  letI : SMulCommClass R ℂ V := by
    refine ⟨?_⟩
    intro r c v
    -- `r` is `ℂ`-linear, hence `r (c • v) = c • r v`.
    simp [Subalgebra.smul_def, Module.End.smul_def]
  -- Step 1: irreducibility ⇒ `V` is a simple `R`-module.
  have hSimple : IsSimpleModule R V := by
    refine (isSimpleModule_iff R V).2 ?_
    classical
    refine IsSimpleOrder.mk (α := Submodule R V) ?_
    intro W
    let Wℂ : Submodule ℂ V := Submodule.restrictScalars ℂ W
    have hWInv : IsInvariantSubmodule A Wℂ := by
      intro i v hv
      have hAi : φ (A i) ∈ R := by
        refine (Subalgebra.mem_map).2 ?_
        exact ⟨A i, algSpan_mem A i, rfl⟩
      have hv' : v ∈ W := by
        simpa [Wℂ] using hv
      have hsmul : (⟨φ (A i), hAi⟩ : R) • v ∈ W :=
        W.smul_mem ⟨φ (A i), hAi⟩ hv'
      have : (A i).mulVec v ∈ W := by
        simpa [φ, Subalgebra.smul_def, Module.End.smul_def, Matrix.toLinAlgEquiv'_apply] using hsmul
      simpa [Wℂ] using this
    rcases hIrr Wℂ hWInv with hbot | htop
    · left
      exact (Submodule.restrictScalars_eq_bot_iff (S := ℂ) (R := R) (M := V)).1 hbot
    · right
      exact (Submodule.restrictScalars_eq_top_iff (S := ℂ) (R := R) (M := V)).1 htop
  -- Make simplicity available as an instance.
  letI : IsSimpleModule R V := hSimple
  -- Step 2: Schur (alg closed) ⇒ commuting endomorphisms are scalars.
  have hSchur : Function.Bijective (algebraMap ℂ (Module.End R V)) := by
    simpa using
      (IsSimpleModule.algebraMap_end_bijective_of_isAlgClosed (k := ℂ) (A := R) (V := V))
  have hAlgSurj : Function.Surjective (algebraMap ℂ (Module.End R V)) := hSchur.2
  -- Step 3: Jacobson density ⇒ surjectivity of the action map.
  -- First show `V` is finite over its commutant `Module.End R V`.
  haveI : Module.Finite (Module.End R V) V := by
    classical
    -- `V` is finite as an `ℂ`-module (finite basis), and Schur gives a surjective ring map
    -- `ℂ → Module.End R V`. Transport finiteness along this surjection.
    haveI : Module.Finite ℂ V := Module.Finite.of_basis (Pi.basisFun ℂ (Fin D))
    haveI : RingHomSurjective (algebraMap ℂ (Module.End R V)) :=
      RingHomSurjective.mk hAlgSurj
    let f : V →ₛₗ[algebraMap ℂ (Module.End R V)] V :=
      LinearMap.mk (toAddHom := AddMonoidHom.id V) (map_smul' := by
        intro c v
        -- `algebraMap` into `Module.End R V` gives scalar multiplication maps on `V`.
        simp [Algebra.algebraMap_eq_smul_one])
    have hf : Function.Surjective f := by
      intro v
      exact ⟨v, rfl⟩
    exact Module.Finite.of_surjective (f := f) hf
  -- Help typeclass inference for `Module.toModuleEnd`: endomorphisms in `Module.End R V`
  -- commute with the `R`-action on `V` by `R`-linearity.
  letI : SMulCommClass R (Module.End R V) V := by
    refine ⟨?_⟩
    intro r f v
    -- `f` is `R`-linear, so `f (r • v) = r • f v`.
    -- Rearranged to match the `SMulCommClass` convention.
    simp [Module.End.smul_def]
  have hJD : Function.Surjective (Module.toModuleEnd (Module.End R V) V) :=
    Module.Finite.toModuleEnd_moduleEnd_surjective (R := R) (M := V)
  -- Conclude `R = ⊤` by showing every `ℂ`-linear endomorphism lies in `R`.
  have hRtop : R = ⊤ := by
    apply eq_top_iff.2
    intro f _
    -- Regard `f` as `Module.End R V`-linear using surjectivity of `algebraMap`.
    let g : Module.End (Module.End R V) V :=
      { toFun := fun v => f v
        map_add' := by simp
        map_smul' := by
          intro d v
          rcases hAlgSurj d with ⟨c, rfl⟩
          -- `algebraMap` into `Module.End R V` acts on `V` by scalar multiplication.
          simp }
    rcases hJD g with ⟨r, hr⟩
    have hrf : (r : Module.End ℂ V) = f := by
      -- Use `LinearMap.ext` to avoid `ext` picking a basis lemma for `Fin D → ℂ`.
      apply LinearMap.ext
      intro v
      ext x
      have hv : (Module.toModuleEnd (Module.End R V) V r) v = g v :=
        congrArg (fun h => h v) hr
      have hx : ((Module.toModuleEnd (Module.End R V) V r) v) x = (g v) x :=
        congrArg (fun w => w x) hv
      simpa [g, Module.toModuleEnd_apply, DistribSMul.toLinearMap_apply,
        Subalgebra.smul_def, Module.End.smul_def] using hx
    simpa [hrf] using r.2
  -- Transport back along `Matrix.toLinAlgEquiv'`.
  have hcomap : Subalgebra.comap φ R = algSpan A := by
    dsimp [R]
    exact Subalgebra.comap_map_eq_self_of_injective (f := φ) φ.injective (algSpan A)
  have : algSpan A = ⊤ := by
    calc
      algSpan A = Subalgebra.comap φ R := hcomap.symm
      _ = Subalgebra.comap φ ⊤ := by simp [hRtop]
      _ = ⊤ := by
        ext x
        simp [Subalgebra.comap]
  exact this

end MPSTensor
