/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import Mathlib.Analysis.CStarAlgebra.Matrix
import Mathlib.Topology.ContinuousMap.Bounded.Normed
import Mathlib.Topology.Algebra.Module.FiniteDimension
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Logic.Function.Iterate
import Mathlib.Tactic.NoncommRing
import TNLean.Algebra.NewtonIdempotentConvergence

/-!
# Continuous local idempotents in generated matrix algebras

Near an idempotent matrix, the polynomial Newton corrections converge
uniformly. Applying the convergence theorem in the Banach algebra of bounded
continuous matrix-valued functions gives a continuous idempotent family with
the prescribed base value. Each iterate lies in the algebra generated by the
original matrix. This algebra is finite-dimensional and closed, so its limit
lies in it as well. Hermiticity is not needed.

This supplies a finite-dimensional ingredient for reconstructing a continuous
matrix-algebra realization from trace-quotient multiplication at constant
rank. It does not derive constant minimal dimension from a physical gap;
see `docs/paper-gaps/spc11_spt_interpolation_upper_range.tex` for that separate
step in arXiv:1010.3732, Section II.F.2, lines 953–993.
-/

set_option relaxedAutoImplicit false
set_option maxSynthPendingDepth 3
set_option linter.mathlibStandardSet true
open scoped Matrix Matrix.Norms.L2Operator Topology BoundedContinuousFunction
open Filter

namespace Matrix

private theorem newton_iterate_mem_adjoin {n : ℕ}
    (X : Matrix (Fin n) (Fin n) ℂ) (k : ℕ) :
    ((fun x => 3 * x ^ 2 - 2 * x ^ 3)^[k]) X ∈ Algebra.adjoin ℂ {X} := by
  let S := Algebra.adjoin ℂ {X}
  induction k with
  | zero => exact Algebra.subset_adjoin (Set.mem_singleton X)
  | succ k hk =>
    rw [Function.iterate_succ_apply']
    exact S.sub_mem (S.mul_mem (S.natCast_mem 3) (S.pow_mem hk 2))
      (S.mul_mem (S.natCast_mem 2) (S.pow_mem hk 3))

private theorem newton_iterate_eq_of_idempotent {n : ℕ}
    (X : Matrix (Fin n) (Fin n) ℂ) (hX : IsIdempotentElem X) (k : ℕ) :
    ((fun x => 3 * x ^ 2 - 2 * x ^ 3)^[k]) X = X := by
  have hX₂ : X ^ 2 = X := by simpa only [pow_two] using hX.eq
  have hX₃ : X ^ 3 = X := by rw [pow_succ, hX₂, hX.eq]
  apply Function.iterate_fixed
  rw [hX₂, hX₃]
  noncomm_ring [smul_smul]

private theorem newton_limit_mem_adjoin {n : ℕ}
    (X P : Matrix (Fin n) (Fin n) ℂ)
    (hP : Tendsto (fun k => ((fun x => 3 * x ^ 2 - 2 * x ^ 3)^[k]) X)
      atTop (𝓝 P)) : P ∈ Algebra.adjoin ℂ {X} := by
  exact (Algebra.adjoin ℂ {X}).toSubmodule.closed_of_finiteDimensional.mem_of_tendsto hP
    (Eventually.of_forall (newton_iterate_mem_adjoin X))


/-- An idempotent matrix extends locally to a continuous idempotent lying in
the complex algebra generated by each nearby matrix. Hermiticity is unnecessary. -/
theorem exists_local_continuous_idempotent_in_adjoin
    {T : Type*} [TopologicalSpace T] {n : ℕ}
    (X : T → Matrix (Fin n) (Fin n) ℂ) (hX : Continuous X)
    (t₀ : T) (hBase : IsIdempotentElem (X t₀)) :
    ∃ (S : Set T) (P : T → Matrix (Fin n) (Fin n) ℂ),
      IsOpen S ∧ t₀ ∈ S ∧ ContinuousOn P S ∧ P t₀ = X t₀ ∧
      ∀ t ∈ S, IsIdempotentElem (P t) ∧ P t ∈ Algebra.adjoin ℂ {X t} := by
  classical
  let S := {t | ‖X t ^ 2 - X t‖ < 1 / 16 ∧ ‖X t‖ < ‖X t₀‖ + 1}
  have hS : IsOpen S := (isOpen_lt ((hX.pow 2).sub hX).norm continuous_const).inter
    (isOpen_lt hX.norm continuous_const)
  have ht₀ : t₀ ∈ S := by
    have hPow : X t₀ ^ 2 = X t₀ := by simpa only [pow_two] using hBase.eq
    constructor
    · simp only [hPow, sub_self, norm_zero]
      norm_num
    · exact lt_add_one _
  let f : S →ᵇ Matrix (Fin n) (Fin n) ℂ :=
    BoundedContinuousFunction.ofNormedAddCommGroup (fun t : S => X t)
      (hX.comp continuous_subtype_val) (‖X t₀‖ + 1) (fun t => t.property.2.le)
  have hf : ∀ t : S, f t = X t := fun _ => rfl
  have hOneMatrix : ‖(1 : Matrix (Fin n) (Fin n) ℂ)‖ ≤ 1 := by
    rcases subsingleton_or_nontrivial (Matrix (Fin n) (Fin n) ℂ) with h | h
    · let := h
      rw [show (1 : Matrix (Fin n) (Fin n) ℂ) = 0 from Subsingleton.elim _ _, norm_zero]
      norm_num
    · let := h
      exact (CStarRing.norm_one).le
  have hOne : ‖(1 : S →ᵇ Matrix (Fin n) (Fin n) ℂ)‖ ≤ 1 :=
    (BoundedContinuousFunction.norm_const_le _).trans hOneMatrix
  have hDef : ‖f ^ 2 - f‖ ≤ 1 / 16 := by
    apply (BoundedContinuousFunction.norm_le (by norm_num)).mpr
    intro t
    simpa only [BoundedContinuousFunction.sub_apply, BoundedContinuousFunction.pow_apply, hf]
      using t.property.1.le
  obtain ⟨p, hLim, hpPow⟩ := idempotent_newton_tendsto_of_small_defect hOne f hDef
  have hp : IsIdempotentElem p := by simpa only [pow_two, IsIdempotentElem] using hpPow
  have hEval : ∀ t : S, ∀ k,
      (((fun x => 3 * x ^ 2 - 2 * x ^ 3)^[k]) f) t =
        ((fun x => 3 * x ^ 2 - 2 * x ^ 3)^[k]) (X t) := by
    intro t k
    have hSemi : Function.Semiconj
        (fun g : S →ᵇ Matrix (Fin n) (Fin n) ℂ => g t)
        (fun x => 3 * x ^ 2 - 2 * x ^ 3) (fun x => 3 * x ^ 2 - 2 * x ^ 3) := by
      intro g
      rfl
    exact hSemi.iterate_right k f
  have hPoint : ∀ t : S,
      Tendsto (fun k => ((fun x => 3 * x ^ 2 - 2 * x ^ 3)^[k]) (X t))
        atTop (𝓝 (p t)) := by
    intro t
    simpa only [Function.comp_def, hEval] using
      ((BoundedContinuousFunction.lipschitz_eval_const t).continuous.tendsto p).comp hLim
  let P := fun t : T => if ht : t ∈ S then p ⟨t, ht⟩ else X t
  refine ⟨S, P, hS, ht₀, ?_, ?_, ?_⟩
  · rw [continuousOn_iff_continuous_domRestrict]
    have hRestrict : S.domRestrict P = (p : S → Matrix (Fin n) (Fin n) ℂ) := by
      funext t
      simp only [Set.domRestrict_apply, P, dite_eq_left t.property]
    rw [hRestrict]
    exact p.continuous
  · simp only [P, dite_eq_left ht₀]
    have hConst : Tendsto (fun k => ((fun x => 3 * x ^ 2 - 2 * x ^ 3)^[k]) (X t₀))
        atTop (𝓝 (X t₀)) := by
      simpa only [newton_iterate_eq_of_idempotent _ hBase] using
        (tendsto_const_nhds : Tendsto (fun _ : ℕ => X t₀) atTop (𝓝 (X t₀)))
    exact tendsto_nhds_unique (hPoint ⟨t₀, ht₀⟩) hConst
  · intro t ht
    have hPt : P t = p ⟨t, ht⟩ := by simp only [P, dite_eq_left ht]
    rw [hPt]
    refine ⟨?_, newton_limit_mem_adjoin _ _ (hPoint ⟨t, ht⟩)⟩
    exact congrArg (fun g : S →ᵇ Matrix (Fin n) (Fin n) ℂ => g ⟨t, ht⟩) hp.eq

end Matrix
