/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.ScalarThreeCocycleCyclicExamples
import TNLean.Algebra.ScalarThreeCocycleCyclicInvariant
import Mathlib.GroupTheory.GroupAction.Quotient

/-!
# The eight Klein-four cocycle representatives

The three binary parameters and the three order-two restriction signs are those of
arXiv:2203.12563, `Papers/2203.12563/REsubmission.tex`, lines 1845–1872.
These are explicit representatives; this module does not claim that they exhaust
third cohomology or classify the corresponding matrix product operator phases.
The representatives are pairwise inequivalent. Their restrictions to any subgroup
are classified by the three diagonal signs; the all-ones class restricts
trivially only to the trivial subgroup. Compatible L-symbols force each block
orbit to have four elements.

## Main results

* `LSymbol.card_of_kleinCocycleFamily_one`: a nonempty transitive compatible block
  action has four blocks.
* `kleinCocycleFamily_signs`: the three diagonal signs for every parameter triple.
* `kleinCocycleFamily_restriction_iff`: the test on each cyclic subgroup.
* `kleinCocycleFamily_cohomologousTo_iff`: equality of classes detects all three parameters.
* `kleinCocycleFamily_one_isTrivialGaugeClass_comap_iff`: the last row remains valid
  when arbitrary fusion gauges are allowed.
* `kleinCocycleFamily_one_subgroup_iff`: only the trivial subgroup has identically
  one restriction for the all-ones parameter triple.

## References

* Garre-Rubio, Lootens, Molnár, *Classifying phases protected by matrix product
  operator symmetries using matrix product states*, arXiv:2203.12563, Section 6.
-/

namespace TNLean.Algebra.ScalarThreeCochain

open Multiplicative

/-- The product of the two type-I components and the type-II component in
arXiv:2203.12563, lines 1845–1848. -/
def kleinCocycleFamily (p q r : ZMod 2) :
    ScalarThreeCochain (Multiplicative (ZMod 2 × ZMod 2)) :=
  fun a b c ↦ (-1) ^ (p * (toAdd a).1 * (toAdd b).1 * (toAdd c).1 +
    q * (toAdd a).2 * (toAdd b).2 * (toAdd c).2 +
    r * (toAdd a).1 * (toAdd b).2 * (toAdd c).2).val

/-- Every representative in the table of arXiv:2203.12563, lines 1856–1872,
satisfies the three-cocycle equation. -/
theorem kleinCocycleFamily_isCocycle (p q r : ZMod 2) :
    IsCocycle (kleinCocycleFamily p q r) := by
  intro g h k l
  simp only [kleinCocycleFamily, neg_one_pow_val_add, toAdd_mul, Prod.fst_add, Prod.snd_add]
  congr 2
  ring

/-- The representatives of arXiv:2203.12563, lines 1845–1848, are normalized. -/
theorem kleinCocycleFamily_isNormalized (p q r : ZMod 2) :
    IsNormalized (kleinCocycleFamily p q r) := by
  refine ⟨fun _ _ ↦ ?_, fun _ _ ↦ ?_, fun _ _ ↦ ?_⟩ <;> simp [kleinCocycleFamily]

/-- The three signs in the table of arXiv:2203.12563, lines 1856–1872. -/
theorem kleinCocycleFamily_signs (p q r : ZMod 2) :
    (kleinCocycleFamily p q r (ofAdd (1, 0)) (ofAdd (1, 0)) (ofAdd (1, 0)),
      kleinCocycleFamily p q r (ofAdd (0, 1)) (ofAdd (0, 1)) (ofAdd (0, 1)),
      kleinCocycleFamily p q r (ofAdd (1, 1)) (ofAdd (1, 1)) (ofAdd (1, 1))) =
      ((-1) ^ p.val, (-1) ^ q.val, (-1) ^ (p + q + r).val) := by
  simp [kleinCocycleFamily]

/-- Restricting a table representative to the line generated by `(x,y)` is identically one
precisely when its diagonal sign is positive (arXiv:2203.12563, lines 1850–1872). -/
theorem kleinCocycleFamily_restriction_eq_one_iff (p q r x y : ZMod 2) :
    (∀ u v w : ZMod 2, kleinCocycleFamily p q r
      (ofAdd (u * x, u * y)) (ofAdd (v * x, v * y)) (ofAdd (w * x, w * y)) = 1) ↔
      kleinCocycleFamily p q r (ofAdd (x, y)) (ofAdd (x, y)) (ofAdd (x, y)) = 1 := by
  constructor
  · intro h
    simpa using h 1 1 1
  · intro h u v w
    have hcases (z : ZMod 2) : z = 0 ∨ z = 1 := by revert z; decide
    rcases hcases u with rfl | rfl <;>
      rcases hcases v with rfl | rfl <;>
      rcases hcases w with rfl | rfl <;> simp_all [kleinCocycleFamily]

/-- The restriction test underlying all eight rows of arXiv:2203.12563,
lines 1856–1872: the restriction to the subgroup generated by `(x,y)` is identically one
exactly when
`p x + q y + r x y = 0` in `ℤ₂`. -/
theorem kleinCocycleFamily_restriction_iff (p q r x y : ZMod 2) :
    (∀ u v w : ZMod 2, kleinCocycleFamily p q r
      (ofAdd (u * x, u * y)) (ofAdd (v * x, v * y)) (ofAdd (w * x, w * y)) = 1) ↔
      p * x + q * y + r * x * y = 0 := by
  rw [kleinCocycleFamily_restriction_eq_one_iff, kleinCocycleFamily]
  have hsquare (z : ZMod 2) : z * z = z := by revert z; decide
  simp only [toAdd_ofAdd, mul_assoc, hsquare]
  generalize p * x + q * y + r * (x * y) = z
  have hz : z = 0 ∨ z = 1 := by revert z; decide
  rcases hz with rfl | rfl <;> norm_num [ZMod.val_one]

/-- For the `(1,1,1)` representative only the identity generates a subgroup with
trivial restriction, as in the last row of arXiv:2203.12563, lines 1870–1872. -/
theorem kleinCocycleFamily_one_restriction_iff (x y : ZMod 2) :
    (∀ u v w : ZMod 2, kleinCocycleFamily 1 1 1
      (ofAdd (u * x, u * y)) (ofAdd (v * x, v * y)) (ofAdd (w * x, w * y)) = 1) ↔
      x = 0 ∧ y = 0 := by
  rw [kleinCocycleFamily_restriction_iff]
  norm_num
  revert x y
  decide

/-- The last row of the subgroup table in arXiv:2203.12563, lines 1870–1872:
the `(1,1,1)` representative restricts to one only on the trivial subgroup. -/
theorem kleinCocycleFamily_one_subgroup_iff
    (H : Subgroup (Multiplicative (ZMod 2 × ZMod 2))) :
    (∀ a b c : H, kleinCocycleFamily 1 1 1 a b c = 1) ↔ H = ⊥ := by
  constructor
  · intro h
    apply le_antisymm ?_ bot_le
    intro g hg
    change g = 1
    have hd := ((kleinCocycleFamily_restriction_eq_one_iff 1 1 1
      (toAdd g).1 (toAdd g).2).symm.trans
      (kleinCocycleFamily_one_restriction_iff (toAdd g).1 (toAdd g).2)).mp
        (h ⟨g, hg⟩ ⟨g, hg⟩ ⟨g, hg⟩)
    exact congrArg ofAdd (Prod.ext hd.1 hd.2)
  · rintro rfl a b c
    have ha : (a : Multiplicative (ZMod 2 × ZMod 2)) = 1 := a.property
    rw [ha]
    exact (kleinCocycleFamily_isNormalized 1 1 1).1 b c

/-- The type-II row agrees with the existing representative of
arXiv:2203.12563, line 1848. -/
theorem kleinCocycleFamily_zero_zero_one : kleinCocycleFamily 0 0 1 = kleinCocycle := by
  funext a b c
  simp [kleinCocycleFamily, kleinCocycle]

/-- The three signs are invariant under arbitrary fusion gauges, as asserted in
arXiv:2203.12563, lines 1850–1852. -/
theorem kleinCocycleFamily_diagonal_eq_of_cohomologousTo
    {p q r p' q' r' : ZMod 2}
    (h : CohomologousTo (kleinCocycleFamily p q r) (kleinCocycleFamily p' q' r'))
    (g : Multiplicative (ZMod 2 × ZMod 2)) :
    kleinCocycleFamily p q r g g g = kleinCocycleFamily p' q' r' g g g := by
  have hg : g ^ 2 = 1 := by
    change ofAdd (2 • toAdd g) = ofAdd 0
    congr 1
    ext <;> simp [show (2 : ZMod 2) = 0 from rfl]
  have he := h.cyclicInvariant_eq hg
  simpa [cyclicInvariant, Finset.prod_range_succ, kleinCocycleFamily] using he

/-- Distinct parameter triples give distinct cohomology classes, as asserted in
arXiv:2203.12563, lines 1845–1852. This does not assert exhaustiveness. -/
theorem kleinCocycleFamily_cohomologousTo_iff (p q r p' q' r' : ZMod 2) :
    CohomologousTo (kleinCocycleFamily p q r) (kleinCocycleFamily p' q' r') ↔
      p = p' ∧ q = q' ∧ r = r' := by
  constructor
  · intro h
    have hinj : Function.Injective (fun x : ZMod 2 ↦ (-1 : Units ℂ) ^ x.val) := by
      intro x y
      have hcases (z : ZMod 2) : z = 0 ∨ z = 1 := by revert z; decide
      rcases hcases x with rfl | rfl <;>
        rcases hcases y with rfl | rfl <;> norm_num [ZMod.val_one]
    have ha := kleinCocycleFamily_diagonal_eq_of_cohomologousTo h (ofAdd (1, 0))
    have hb := kleinCocycleFamily_diagonal_eq_of_cohomologousTo h (ofAdd (0, 1))
    have hc := kleinCocycleFamily_diagonal_eq_of_cohomologousTo h (ofAdd (1, 1))
    simp only [kleinCocycleFamily, toAdd_ofAdd, mul_one, mul_zero, add_zero, zero_add] at ha hb hc
    have hp := hinj ha
    have hq := hinj hb
    refine ⟨hp, hq, ?_⟩
    exact add_left_cancel (hp ▸ hq ▸ hinj hc)
  · rintro ⟨rfl, rfl, rfl⟩
    exact CohomologousTo.refl _

private theorem klein_exponent_eq_zero_of_diagonal (p q r : ZMod 2) (a b c : ZMod 2 × ZMod 2)
    (ha : p * a.1 + q * a.2 + r * a.1 * a.2 = 0)
    (hb : p * b.1 + q * b.2 + r * b.1 * b.2 = 0)
    (hc : p * c.1 + q * c.2 + r * c.1 * c.2 = 0)
    (hab : p * (a + b).1 + q * (a + b).2 + r * (a + b).1 * (a + b).2 = 0)
    (hac : p * (a + c).1 + q * (a + c).2 + r * (a + c).1 * (a + c).2 = 0)
    (hbc : p * (b + c).1 + q * (b + c).2 + r * (b + c).1 * (b + c).2 = 0) :
    p * a.1 * b.1 * c.1 + q * a.2 * b.2 * c.2 + r * a.1 * b.2 * c.2 = 0 := by
  fin_cases p <;> fin_cases q <;> fin_cases r <;> revert a b c <;> decide

/-- For any subgroup, the restricted class of a Klein-four representative is
trivial exactly when every member has positive diagonal sign. This is the
subgroup test in arXiv:2203.12563, lines 1850–1872, allowing arbitrary fusion gauges. -/
theorem kleinCocycleFamily_isTrivialGaugeClass_comap_iff (p q r : ZMod 2)
    (H : Subgroup (Multiplicative (ZMod 2 × ZMod 2))) :
    IsTrivialGaugeClass (comap H.subtype (kleinCocycleFamily p q r)) ↔
      ∀ g : H, p * (toAdd g.val).1 + q * (toAdd g.val).2 +
        r * (toAdd g.val).1 * (toAdd g.val).2 = 0 := by
  constructor
  · intro h g
    have hg2 : g ^ 2 = 1 := by
      apply Subtype.ext
      change ofAdd (2 • toAdd g.val) = ofAdd 0
      congr 1
      ext <;> simp [show (2 : ZMod 2) = 0 from rfl]
    have hi := cyclicInvariant_eq_one_of_isTrivialGaugeClass h hg2
    have hd : kleinCocycleFamily p q r g g g = 1 := by
      simpa [cyclicInvariant, Finset.prod_range_succ, comap, kleinCocycleFamily] using hi
    exact (kleinCocycleFamily_restriction_iff p q r _ _).mp
      ((kleinCocycleFamily_restriction_eq_one_iff p q r _ _).mpr hd)
  · intro h
    have he : comap H.subtype (kleinCocycleFamily p q r) = 1 := by
      funext a b c
      have hz := klein_exponent_eq_zero_of_diagonal p q r (toAdd a.val) (toAdd b.val) (toAdd c.val)
        (h a) (h b) (h c) (h (a * b)) (h (a * c)) (h (b * c))
      simp only [comap, kleinCocycleFamily, Subgroup.subtype_apply, hz,
        ZMod.val_zero, pow_zero, Pi.one_apply]
    rw [he]
    exact CohomologousTo.refl _

/-- The three membership tests determining all eight subgroup-table rows in
arXiv:2203.12563, lines 1856–1872. A generator with negative diagonal sign
cannot belong to the subgroup, and these are the only restrictions. -/
theorem kleinCocycleFamily_isTrivialGaugeClass_comap_iff_generators (p q r : ZMod 2)
    (H : Subgroup (Multiplicative (ZMod 2 × ZMod 2))) :
    IsTrivialGaugeClass (comap H.subtype (kleinCocycleFamily p q r)) ↔
      (ofAdd (1, 0) ∈ H → p = 0) ∧ (ofAdd (0, 1) ∈ H → q = 0) ∧
        (ofAdd (1, 1) ∈ H → p + q + r = 0) := by
  rw [kleinCocycleFamily_isTrivialGaugeClass_comap_iff]
  constructor
  · intro h
    refine ⟨fun ha ↦ ?_, fun hb ↦ ?_, fun hc ↦ ?_⟩
    · simpa using h ⟨ofAdd (1, 0), ha⟩
    · simpa using h ⟨ofAdd (0, 1), hb⟩
    · simpa using h ⟨ofAdd (1, 1), hc⟩
  · rintro ⟨ha, hb, hc⟩ ⟨⟨x, y⟩, hg⟩
    change p * x + q * y + r * x * y = 0
    change ofAdd (x, y) ∈ H at hg
    have hcases (z : ZMod 2) : z = 0 ∨ z = 1 := by revert z; decide
    rcases hcases x with rfl | rfl <;>
      rcases hcases y with rfl | rfl <;> simp_all

/-- For the last row of arXiv:2203.12563, lines 1870–1888, the restricted
cohomology class is trivial exactly on the trivial subgroup. -/
theorem kleinCocycleFamily_one_isTrivialGaugeClass_comap_iff
    (H : Subgroup (Multiplicative (ZMod 2 × ZMod 2))) :
    IsTrivialGaugeClass (comap H.subtype (kleinCocycleFamily 1 1 1)) ↔ H = ⊥ := by
  constructor
  · intro h
    apply le_antisymm ?_ bot_le
    intro g hg
    change g = 1
    have hsign := (kleinCocycleFamily_isTrivialGaugeClass_comap_iff 1 1 1 H).mp h ⟨g, hg⟩
    have hz := (kleinCocycleFamily_one_restriction_iff (toAdd g).1 (toAdd g).2).mp
      ((kleinCocycleFamily_restriction_iff 1 1 1 (toAdd g).1 (toAdd g).2).mpr hsign)
    exact congrArg ofAdd (Prod.ext hz.1 hz.2)
  · intro h
    have he : comap H.subtype (kleinCocycleFamily 1 1 1) = 1 := by
      funext a b c
      exact (kleinCocycleFamily_one_subgroup_iff H).mpr h a b c
    rw [he]
    exact CohomologousTo.refl _

end TNLean.Algebra.ScalarThreeCochain

namespace TNLean.Algebra.LSymbol

open ScalarThreeCochain

/-- Every block stabilizer is trivial for compatible L-symbols in the last row of
arXiv:2203.12563, lines 1870–1888. -/
theorem stabilizer_eq_bot_of_kleinCocycleFamily_one
    {X : Type*} [MulAction (Multiplicative (ZMod 2 × ZMod 2)) X]
    {L : LSymbol (Multiplicative (ZMod 2 × ZMod 2)) X}
    (hL : IsCompatible L (kleinCocycleFamily 1 1 1)) (x : X) :
    MulAction.stabilizer (Multiplicative (ZMod 2 × ZMod 2)) x = ⊥ := by
  exact (kleinCocycleFamily_one_isTrivialGaugeClass_comap_iff _).mp
    (isTrivialGaugeClass_comap_of_isCompatible hL x
      (MulAction.stabilizer (Multiplicative (ZMod 2 × ZMod 2)) x).subtype
      (fun g ↦ g.property))

/-- Each orbit of blocks has four elements for the last-row cocycle of
arXiv:2203.12563, line 1888. This does not assert uniqueness of the phase. -/
theorem card_orbit_of_kleinCocycleFamily_one
    {X : Type*} [MulAction (Multiplicative (ZMod 2 × ZMod 2)) X]
    {L : LSymbol (Multiplicative (ZMod 2 × ZMod 2)) X}
    (hL : IsCompatible L (kleinCocycleFamily 1 1 1)) (x : X) :
    Nat.card (MulAction.orbit (Multiplicative (ZMod 2 × ZMod 2)) x) = 4 := by
  have hc := Nat.card_congr
    (MulAction.orbitProdStabilizerEquivGroup (Multiplicative (ZMod 2 × ZMod 2)) x)
  rw [Nat.card_prod, stabilizer_eq_bot_of_kleinCocycleFamily_one hL x] at hc
  simpa [Nat.card_eq_fintype_card] using hc

/-- A transitive block action compatible with the last-row cocycle has exactly
four blocks, as in arXiv:2203.12563, line 1888. -/
theorem card_of_kleinCocycleFamily_one
    {X : Type*} [MulAction (Multiplicative (ZMod 2 × ZMod 2)) X]
    [MulAction.IsPretransitive (Multiplicative (ZMod 2 × ZMod 2)) X]
    {L : LSymbol (Multiplicative (ZMod 2 × ZMod 2)) X}
    (hL : IsCompatible L (kleinCocycleFamily 1 1 1)) (x : X) : Nat.card X = 4 := by
  have hc := card_orbit_of_kleinCocycleFamily_one hL x
  rw [MulAction.orbit_eq_univ] at hc
  simpa using hc

end TNLean.Algebra.LSymbol
