/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import Mathlib.Basic.Complex.Basic
import Mathlib.LinearAlgebra.Matrix.ToLin
import Mathlib.LinearAlgebra.Matrix.Basis
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

/-!
# Dimension of a primitive matrix left ideal

Right multiplication by a diagonal matrix unit has a D-dimensional range in the
D by D complex matrix algebra. The same statement holds in any multiplicative linear
coordinate identification of that algebra. These elementary facts supply the base ideal
dimension for the reconstruction of a tensor from finite-ring trace data, motivated by
arXiv:1010.3732, Section II.F.2, lines 953–993 of the local source. They assert neither
continuous selection of an ideal nor a physical-gap implication.
-/

set_option relaxedAutoImplicit false
set_option maxSynthPendingDepth 3
set_option linter.mathlibStandardSet true
open scoped Matrix

namespace Matrix

/-- The principal left ideal generated by a diagonal matrix unit has dimension D. -/
theorem finrank_range_mulRight_single {D : ℕ} (i : Fin D) :
    Module.finrank ℂ (LinearMap.range
      (LinearMap.mulRight ℂ (Matrix.single i i (1 : ℂ)))) = D := by
  let J : (Fin D → ℂ) →ₗ[ℂ] Matrix (Fin D) (Fin D) ℂ :=
    (vecMulVecBilin ℂ ℂ).flip (Pi.single i 1)
  have hJ : Function.Injective J := by
    intro x y hxy
    funext j
    have h := congrArg (fun M => M j i) hxy
    change x j * (Pi.single i (1 : ℂ) : Fin D → ℂ) i =
      y j * (Pi.single i (1 : ℂ) : Fin D → ℂ) i at h
    simpa only [Pi.single_eq_same, mul_one] using h
  have hRange : LinearMap.range (LinearMap.mulRight ℂ (Matrix.single i i (1 : ℂ))) =
      LinearMap.range J := by
    ext M
    constructor
    · rintro ⟨N, rfl⟩
      refine ⟨N.col i, ?_⟩
      change Matrix.vecMulVec (N.col i) (Pi.single i 1) =
        N * Matrix.single i i (1 : ℂ)
      rw [Matrix.single_eq_single_vecMulVec_single, Matrix.mul_vecMulVec,
        Matrix.mulVec_single_one]
    · rintro ⟨v, rfl⟩
      refine ⟨J v, ?_⟩
      change Matrix.vecMulVec v (Pi.single i 1) * Matrix.single i i (1 : ℂ) =
        Matrix.vecMulVec v (Pi.single i 1)
      rw [Matrix.single_eq_single_vecMulVec_single, Matrix.vecMulVec_mul_vecMulVec]
      simp only [dotProduct_single_one, Pi.single_eq_same, one_smul]
  rw [hRange, LinearMap.finrank_range_of_inj hJ]
  simp

/-- A primitive matrix unit defines a D-dimensional principal left ideal in any
pointwise matrix-algebra coordinate identification. -/
theorem finrank_range_rightMul_of_matrixAlgebra {r D : ℕ}
    (μ : (Fin r → ℂ) →ₗ[ℂ] (Fin r → ℂ) →ₗ[ℂ] (Fin r → ℂ))
    (E : (Fin r → ℂ) ≃ₗ[ℂ] Matrix (Fin D) (Fin D) ℂ)
    (hE : ∀ x y, E (μ x y) = E x * E y) (i : Fin D) :
    Module.finrank ℂ (LinearMap.range (μ.flip (E.symm (Matrix.single i i 1)))) = D := by
  have hComp : E.toLinearMap.comp (μ.flip (E.symm (Matrix.single i i 1))) =
      (LinearMap.mulRight ℂ (Matrix.single i i (1 : ℂ))).comp E.toLinearMap := by
    ext x a b
    simp only [LinearMap.comp_apply, LinearEquiv.coe_coe, LinearMap.flip_apply, hE,
      E.apply_symm_apply, LinearMap.mulRight_apply]
  have hMap : (LinearMap.range (μ.flip (E.symm (Matrix.single i i 1)))).map
      E.toLinearMap = LinearMap.range (LinearMap.mulRight ℂ (Matrix.single i i (1 : ℂ))) := by
    rw [← LinearMap.range_comp, hComp,
      LinearMap.range_comp_of_range_eq_top _ E.range]
  rw [← E.finrank_map_eq, hMap, finrank_range_mulRight_single]

end Matrix
