/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.LinearAlgebra.Matrix.ToLin
import QICLean.Algebra.StarSubalgebraSpatial

/-!
# Invariant complements for a star-closed family of matrices

A family of complex square matrices whose conjugate transposes lie in the algebra generated by
the family reduces completely: every invariant subspace of the coordinate space has an invariant
complement, namely its orthogonal complement for the standard inner product. This is the
splitting criterion of the asymmetric compression theorem
(`Notes/OpenProblemsTN/strategies/final_resolution/p5_local_zipper_hypotheses.tex`, the adjoint
closure hypothesis): a fixed occurrence of a block splits off exactly when the step of the
invariant flag carrying it is a direct summand, and adjoint closure of the generated matrix
algebra is a sufficient condition for that.

## Main definitions

* `Matrix.mulVecInvtSubalgebra`: the subalgebra of matrices leaving a subspace invariant.

## Main results

* `Matrix.exists_isCompl_forall_mulVec_mem`: a subspace invariant under a family of matrices
  whose conjugate transposes lie in the generated algebra has an invariant complement.
-/

open scoped Matrix

namespace Matrix

variable {D : ℕ}

/-- The subalgebra of matrices leaving a subspace of the coordinate space invariant. -/
def mulVecInvtSubalgebra (W : Submodule ℂ (Fin D → ℂ)) :
    Subalgebra ℂ (Matrix (Fin D) (Fin D) ℂ) where
  carrier := {A | ∀ v ∈ W, A *ᵥ v ∈ W}
  mul_mem' {A A'} hA hA' v hv := by
    rw [← Matrix.mulVec_mulVec]
    exact hA _ (hA' v hv)
  one_mem' v hv := by rwa [Matrix.one_mulVec]
  add_mem' {A A'} hA hA' v hv := by
    rw [Matrix.add_mulVec]
    exact W.add_mem (hA v hv) (hA' v hv)
  zero_mem' v _ := by
    rw [Matrix.zero_mulVec]
    exact W.zero_mem
  algebraMap_mem' c v hv := by
    rw [Algebra.algebraMap_eq_smul_one, Matrix.smul_mulVec, Matrix.one_mulVec]
    exact W.smul_mem c hv

@[simp] theorem mem_mulVecInvtSubalgebra {W : Submodule ℂ (Fin D → ℂ)}
    {A : Matrix (Fin D) (Fin D) ℂ} :
    A ∈ mulVecInvtSubalgebra W ↔ ∀ v ∈ W, A *ᵥ v ∈ W := Iff.rfl

/-- A subspace invariant under a family of matrices is invariant under the whole algebra
generated by the family. -/
theorem forall_mulVec_mem_of_mem_adjoin {d : ℕ} {B : Fin d → Matrix (Fin D) (Fin D) ℂ}
    {W : Submodule ℂ (Fin D → ℂ)} (hW : ∀ i, ∀ v ∈ W, B i *ᵥ v ∈ W)
    {A : Matrix (Fin D) (Fin D) ℂ} (hA : A ∈ Algebra.adjoin ℂ (Set.range B)) :
    ∀ v ∈ W, A *ᵥ v ∈ W :=
  Algebra.adjoin_le (S := mulVecInvtSubalgebra W) (by rintro _ ⟨i, rfl⟩; exact hW i) hA

/-- **Complete reducibility of a star-closed family** . If the conjugate transpose of every
matrix of a finite family lies in the algebra generated by the family, then every invariant
subspace of the coordinate space has an invariant complement: the orthogonal complement for the
standard inner product works, because the conjugate transposes preserve the subspace itself. -/
theorem exists_isCompl_forall_mulVec_mem {d : ℕ} (B : Fin d → Matrix (Fin D) (Fin D) ℂ)
    (hstar : ∀ i, (B i)ᴴ ∈ Algebra.adjoin ℂ (Set.range B))
    (W : Submodule ℂ (Fin D → ℂ)) (hW : ∀ i, ∀ v ∈ W, B i *ᵥ v ∈ W) :
    ∃ W' : Submodule ℂ (Fin D → ℂ), IsCompl W W' ∧ ∀ i, ∀ v ∈ W', B i *ᵥ v ∈ W' := by
  set κ : EuclideanSpace ℂ (Fin D) ≃ₗ[ℂ] (Fin D → ℂ) := WithLp.linearEquiv 2 ℂ (Fin D → ℂ)
  set p : Submodule ℂ (EuclideanSpace ℂ (Fin D)) := W.comap (κ : _ →ₗ[ℂ] _) with hp
  -- The conjugate transposes preserve `W`, so `p` is invariant under them.
  have hstarW : ∀ i, p ∈ Module.End.invtSubmodule (Matrix.toEuclideanLin (B i)ᴴ) := by
    intro i x hx
    exact forall_mulVec_mem_of_mem_adjoin hW (hstar i) _ hx
  have hperp : ∀ i, pᗮ ∈ Module.End.invtSubmodule (Matrix.toEuclideanLin (B i)) := fun i =>
    Matrix.orthogonal_mem_invtSubmodule_toEuclideanLin (hstarW i)
  refine ⟨pᗮ.map (κ : _ →ₗ[ℂ] _), ?_, ?_⟩
  · have hcompl : IsCompl p pᗮ := Submodule.isCompl_orthogonal (K := p)
    have hWp : W = p.map (κ : _ →ₗ[ℂ] _) := by
      rw [hp, Submodule.map_comap_eq_of_surjective κ.surjective]
    rw [hWp]
    exact (Submodule.orderIsoMapComap κ).isCompl hcompl
  · rintro i _ ⟨x, hx, rfl⟩
    exact ⟨Matrix.toEuclideanLin (B i) x, hperp i hx, rfl⟩

end Matrix
