/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import QICLean.Algebra.StarSubalgebraBlockDiagonal
import TNLean.Algebra.CharacterProjector
import Mathlib.Analysis.Normed.Lp.Matrix

/-!
# Unitary group representations and their generated star algebras

For a unitary representation, taking the star algebra generated by its matrices does not
change its invariant subspaces or irreducible sectors: the adjoint of each group operator
is the operator of the inverse group element. This identifies the representation-theoretic
and algebraic decompositions used in SCP10, Section 4.1 and Section 7. The orthonormal
adapted-basis existence theorem is reused from QICLean.
-/

open scoped Matrix Pointwise
namespace Subrepresentation
variable {k G V : Type*} [Field k] [Monoid G] [AddCommGroup V] [Module k V]
  {ρ : Representation k G V}

/-- An irreducible restriction is an atom of the lattice of subrepresentations.
This is the converse to `isIrreducible_toRepresentation_of_isAtom`, used to identify
the group and algebra notions of irreducible sector in SCP10, Section 4.1. -/
theorem isAtom_of_isIrreducible_toRepresentation (S : Subrepresentation ρ)
    [S.toRepresentation.IsIrreducible] : IsAtom S := by
  refine ⟨?_, ?_⟩
  · intro hS
    have := Representation.nontrivial_of_isIrreducible S.toRepresentation
    obtain ⟨v, hv⟩ := exists_ne (0 : S.toSubmodule)
    have hmem : (v : V) ∈ (⊥ : Subrepresentation ρ) := hS ▸ v.2
    exact hv (Subtype.ext ((Submodule.mem_bot k).mp hmem))
  · intro T hT
    let T' : Subrepresentation S.toRepresentation :=
      { toSubmodule := T.toSubmodule.comap S.toSubmodule.subtype
        apply_mem_toSubmodule := fun g v hv => T.apply_mem_toSubmodule g hv }
    rcases IsSimpleOrder.eq_bot_or_eq_top T' with h | h
    · apply Subrepresentation.toSubmodule_injective
      apply (Submodule.eq_bot_iff _).mpr
      intro v hv
      have hv' : (⟨v, hT.le hv⟩ : S.toSubmodule) ∈ T' := hv
      rw [h] at hv'
      exact congrArg Subtype.val ((Submodule.mem_bot k).mp hv')
    · exfalso
      exact (not_le_of_gt hT) fun v hv => by
        have hv' : (⟨v, hv⟩ : S.toSubmodule) ∈ T' := by rw [h]; exact Submodule.mem_top
        exact hv'
end Subrepresentation

namespace Representation
variable {G n : Type*} [Group G] [Fintype n] [DecidableEq n]

/-- A matrix representation acting on the standard finite-dimensional Hilbert space.
This is Mathlib’s matrix-to-linear-map equivalence applied to the given representation.
Source: SCP10, Section 4.1. -/
noncomputable def euclideanMatrixRepresentation (U : G →* Matrix n n ℂ) :
    Representation ℂ G (EuclideanSpace ℂ n) :=
  (Matrix.toLpLinAlgEquiv (2 : ENNReal)).toMonoidHom.comp U

/-- The star algebra generated by a matrix representation.
Source: SCP10, Section 4.1, the algebra spanned by the virtual group operators. -/
noncomputable def generatedMatrixStarAlgebra (U : G →* Matrix n n ℂ) :
    StarSubalgebra ℂ (Matrix n n ℂ) := StarAlgebra.adjoin ℂ (Set.range U)

private theorem star_apply_eq_inverse_of_unitary (U : G →* Matrix n n ℂ)
    (hU : ∀ g, U g ∈ Matrix.unitaryGroup n ℂ) (g : G) : star (U g) = U g⁻¹ := by
  apply left_inv_eq_right_inv (Matrix.mem_unitaryGroup_iff'.mp (hU g))
  rw [← map_mul, mul_inv_cancel, map_one]

/-- For a unitary representation, invariance under the generated star algebra is exactly
invariance under the group operators. The adjoints of the generators are their inverses.
Source: SCP10, Section 4.1. -/
theorem isInvariantSubspace_generatedMatrixStarAlgebra_iff
    (U : G →* Matrix n n ℂ) (hU : ∀ g, U g ∈ Matrix.unitaryGroup n ℂ)
    (p : Submodule ℂ (EuclideanSpace ℂ n)) :
    (generatedMatrixStarAlgebra U).IsInvariantSubspace p ↔
      ∀ g, p ∈ Module.End.invtSubmodule (euclideanMatrixRepresentation U g) := by
  constructor
  · intro hp g
    exact hp (U g) (StarAlgebra.subset_adjoin ℂ (Set.range U) ⟨g, rfl⟩)
  · intro hp A hA
    change A ∈ Algebra.adjoin ℂ (Set.range U ∪ star (Set.range U)) at hA
    induction hA using Algebra.adjoin_induction with
    | mem A hA =>
      rcases hA with hA | hA
      · obtain ⟨g, rfl⟩ := hA
        exact hp g
      · have hs : star A ∈ Set.range U := Set.mem_star.mp hA
        obtain ⟨g, hg⟩ := hs
        have heq : A = U g⁻¹ := by
          rw [← star_star A, ← hg, star_apply_eq_inverse_of_unitary U hU g]
        rw [heq]
        exact hp g⁻¹
    | algebraMap r =>
      rw [Module.End.mem_invtSubmodule_iff_forall_mem_of_mem]
      intro x hx
      change Matrix.toEuclideanLin (algebraMap ℂ (Matrix n n ℂ) r) x ∈ p
      rw [Algebra.algebraMap_eq_smul_one, map_smul, Matrix.toLpLin_one]
      change r • x ∈ p
      exact p.smul_mem r hx
    | add A B hA hB ihA ihB =>
      rw [Module.End.mem_invtSubmodule_iff_forall_mem_of_mem] at ihA ihB ⊢
      intro x hx
      change Matrix.toEuclideanLin (A + B) x ∈ p
      rw [map_add]
      change Matrix.toEuclideanLin A x + Matrix.toEuclideanLin B x ∈ p
      exact p.add_mem (ihA x hx) (ihB x hx)
    | mul A B hA hB ihA ihB =>
      rw [Module.End.mem_invtSubmodule_iff_forall_mem_of_mem] at ihA ihB ⊢
      intro x hx
      change Matrix.toEuclideanLin (A * B) x ∈ p
      rw [Matrix.toLpLin_mul_same]
      exact ihA _ (ihB x hx)

/-- The group subrepresentation carried by an invariant subspace of the generated algebra.
Source: SCP10, Section 4.1. -/
noncomputable def matrixInvariantSubrepresentation
    (U : G →* Matrix n n ℂ) (hU : ∀ g, U g ∈ Matrix.unitaryGroup n ℂ)
    (p : Submodule ℂ (EuclideanSpace ℂ n))
    (hp : (generatedMatrixStarAlgebra U).IsInvariantSubspace p) :
    Subrepresentation (euclideanMatrixRepresentation U) where
  toSubmodule := p
  apply_mem_toSubmodule g v hv :=
    (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).mp
      ((isInvariantSubspace_generatedMatrixStarAlgebra_iff U hU p).mp hp g) v hv

/-- The irreducible invariant subspaces of the generated star algebra are precisely
the irreducible group subrepresentations. Source: SCP10, Section 4.1. -/
theorem isIrreducibleSubspace_generatedMatrixStarAlgebra_iff
    (U : G →* Matrix n n ℂ) (hU : ∀ g, U g ∈ Matrix.unitaryGroup n ℂ)
    (S : Subrepresentation (euclideanMatrixRepresentation U)) :
    (generatedMatrixStarAlgebra U).IsIrreducibleSubspace S.toSubmodule ↔
      S.toRepresentation.IsIrreducible := by
  have hS : (generatedMatrixStarAlgebra U).IsInvariantSubspace S.toSubmodule :=
    (isInvariantSubspace_generatedMatrixStarAlgebra_iff U hU _).mpr fun g =>
      (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).mpr
        fun _ hv => S.apply_mem_toSubmodule g hv
  constructor
  · intro h
    apply Subrepresentation.isIrreducible_toRepresentation_of_isAtom
    refine ⟨fun hbot => h.2.1 (congrArg Subrepresentation.toSubmodule hbot), ?_⟩
    intro T hT
    have hTinv : (generatedMatrixStarAlgebra U).IsInvariantSubspace T.toSubmodule :=
      (isInvariantSubspace_generatedMatrixStarAlgebra_iff U hU _).mpr fun g =>
        (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).mpr
          fun _ hv => T.apply_mem_toSubmodule g hv
    rcases h.2.2 T.toSubmodule hTinv hT.le with hbot | heq
    · exact Subrepresentation.toSubmodule_injective hbot
    · exact (ne_of_lt hT) (Subrepresentation.toSubmodule_injective heq) |>.elim
  · intro h
    have := h
    have hAtom := Subrepresentation.isAtom_of_isIrreducible_toRepresentation S
    refine ⟨hS, fun hbot => hAtom.1 (Subrepresentation.toSubmodule_injective hbot), ?_⟩
    intro q hq hqS
    let Q := matrixInvariantSubrepresentation U hU q hq
    rcases hAtom.le_iff.mp (show Q ≤ S from fun v hv => hqS hv) with hbot | heq
    · exact Or.inl (show q = ⊥ from congrArg Subrepresentation.toSubmodule hbot)
    · exact Or.inr (show q = S.toSubmodule from congrArg Subrepresentation.toSubmodule heq)

/-- An operator intertwines the generated algebra on an invariant subspace exactly
when it intertwines every group operator there. Source: SCP10, Section 4.1. -/
theorem isIntertwiner_generatedMatrixStarAlgebra_iff
    (U : G →* Matrix n n ℂ) (hU : ∀ g, U g ∈ Matrix.unitaryGroup n ℂ)
    (S T : Subrepresentation (euclideanMatrixRepresentation U))
    (f : Module.End ℂ (EuclideanSpace ℂ n)) :
    (generatedMatrixStarAlgebra U).IsIntertwiner S.toSubmodule T.toSubmodule f ↔
      Submodule.map f S.toSubmodule ≤ T.toSubmodule ∧
        ∀ g, ∀ x ∈ S, f (euclideanMatrixRepresentation U g x) =
          euclideanMatrixRepresentation U g (f x) := by
  constructor
  · intro h
    exact ⟨h.1, fun g x hx => h.2 (U g)
      (StarAlgebra.subset_adjoin ℂ (Set.range U) ⟨g, rfl⟩) x hx⟩
  · rintro ⟨hmap, hcomm⟩
    refine ⟨hmap, ?_⟩
    intro A hA
    change A ∈ Algebra.adjoin ℂ (Set.range U ∪ star (Set.range U)) at hA
    induction hA using Algebra.adjoin_induction with
    | mem A hA =>
      rcases hA with hA | hA
      · obtain ⟨g, rfl⟩ := hA
        exact hcomm g
      · obtain ⟨g, hg⟩ := Set.mem_star.mp hA
        have heq : A = U g⁻¹ := by
          rw [← star_star A, ← hg, star_apply_eq_inverse_of_unitary U hU g]
        rw [heq]
        exact hcomm g⁻¹
    | algebraMap r =>
      intro x hx
      rw [Algebra.algebraMap_eq_smul_one, map_smul, Matrix.toLpLin_one]
      simp
    | add A B hA hB ihA ihB =>
      intro x hx
      rw [map_add]
      simp only [LinearMap.add_apply, map_add, ihA x hx, ihB x hx]
    | mul A B hA hB ihA ihB =>
      intro x hx
      have hBS : (generatedMatrixStarAlgebra U).IsInvariantSubspace S.toSubmodule :=
        (isInvariantSubspace_generatedMatrixStarAlgebra_iff U hU _).mpr fun g =>
          (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).mpr
            fun _ hv => S.apply_mem_toSubmodule g hv
      have hBx : Matrix.toEuclideanLin B x ∈ S :=
        (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).mp (hBS B hB) x hx
      rw [Matrix.toLpLin_mul_same]
      simp only [LinearMap.comp_apply, ihA _ hBx, ihB x hx]

/-- Two irreducible invariant subspaces have the same algebra isotype exactly when
their group representations are equivalent. Source: SCP10, Section 4.1. -/
theorem sameIsotype_generatedMatrixStarAlgebra_iff
    (U : G →* Matrix n n ℂ) (hU : ∀ g, U g ∈ Matrix.unitaryGroup n ℂ)
    (S T : Subrepresentation (euclideanMatrixRepresentation U))
    [S.toRepresentation.IsIrreducible] [T.toRepresentation.IsIrreducible] :
    (generatedMatrixStarAlgebra U).SameIsotype S.toSubmodule T.toSubmodule ↔
      Nonempty (S.toRepresentation.Equiv T.toRepresentation) := by
  constructor
  · rintro ⟨f, hf, hne⟩
    obtain ⟨hmap, hcomm⟩ :=
      (isIntertwiner_generatedMatrixStarAlgebra_iff U hU S T f).mp hf
    let F : IntertwiningMap S.toRepresentation T.toRepresentation :=
      { toLinearMap := (f.comp S.toSubmodule.subtype).codRestrict T.toSubmodule
          fun x => hmap (Submodule.mem_map_of_mem x.2)
        isIntertwining' := fun g => LinearMap.ext fun x => Subtype.ext (hcomm g x x.2) }
    have hF : F ≠ 0 := by
      intro hz
      apply hne
      intro x hx
      exact congrArg Subtype.val (congrArg (fun F : IntertwiningMap
        S.toRepresentation T.toRepresentation => F ⟨x, hx⟩) hz)
    exact ⟨F.ofBijective ((IsIrreducible.bijective_or_eq_zero F).resolve_right hF)⟩
  · rintro ⟨e⟩
    let f : Module.End ℂ (EuclideanSpace ℂ n) :=
      T.toSubmodule.subtype ∘ₗ e.toLinearMap ∘ₗ
        S.toSubmodule.orthogonalProjectionOnto.toLinearMap
    have hf : ∀ x : S.toSubmodule, f x = (e x : EuclideanSpace ℂ n) := by
      intro x
      simp [f]
    refine ⟨f, (isIntertwiner_generatedMatrixStarAlgebra_iff U hU S T f).mpr
      ⟨?_, ?_⟩, ?_⟩
    · rintro x ⟨y, hy, rfl⟩
      rw [hf ⟨y, hy⟩]
      exact (e ⟨y, hy⟩).2
    · intro g x hx
      change f (S.toRepresentation g ⟨x, hx⟩ : EuclideanSpace ℂ n) = _
      rw [hf, hf ⟨x, hx⟩]
      exact congrArg Subtype.val (IntertwiningMap.isIntertwining
        S.toRepresentation T.toRepresentation e.toIntertwiningMap g ⟨x, hx⟩)
    · intro hz
      have := Representation.nontrivial_of_isIrreducible S.toRepresentation
      obtain ⟨x, hx⟩ := exists_ne (0 : S.toSubmodule)
      have hzero : e x = 0 := Subtype.ext (by simpa [hf x] using hz x x.2)
      exact hx (e.toLinearEquiv.map_eq_zero_iff.mp hzero)

/-- A finite-dimensional unitary representation of a finite group admits an orthonormal
basis of irreducible rows, grouped by distinct irreducible characters, with the same
matrix acting on every multiplicity row of each group. This applies QICLean’s adapted
star-algebra decomposition rather than reproving it. Source: SCP10, Section 4.1 and
Section 7, lines 2992–3019. -/
theorem exists_unitary_irreducible_matrix_blocks [Finite G]
    (U : G →* Matrix n n ℂ) (hU : ∀ g, U g ∈ Matrix.unitaryGroup n ℂ) :
    ∃ (K : ℕ) (d m : Fin K → ℕ)
      (b : OrthonormalBasis ((k : Fin K) × (Fin (m k) × Fin (d k))) ℂ
        (EuclideanSpace ℂ n))
      (S : ∀ k, Fin (m k) → Subrepresentation (euclideanMatrixRepresentation U)),
      (∀ k, 0 < d k) ∧ (∀ k, 0 < m k) ∧
      (∀ k i, (S k i).toSubmodule =
        Submodule.span ℂ (Set.range fun j => b ⟨k, (i, j)⟩)) ∧
      (∀ k i, (S k i).toRepresentation.IsIrreducible) ∧
      (∀ k k', k ≠ k' → ∀ i i',
        (S k i).toRepresentation.character ≠ (S k' i').toRepresentation.character) ∧
      ∀ g, ∃ B : ∀ k, Matrix (Fin (d k)) (Fin (d k)) ℂ,
        ∀ k i j, euclideanMatrixRepresentation U g (b ⟨k, (i, j)⟩) =
          ∑ j', B k j' j • b ⟨k, (i, j')⟩ := by
  classical
  obtain ⟨K, d, m, b, hd, hm, hirr, hcross, hact⟩ :=
    (generatedMatrixStarAlgebra U).exists_adapted_orthonormalBasis
  let S := fun k i => matrixInvariantSubrepresentation U hU
    (Submodule.span ℂ (Set.range fun j => b ⟨k, (i, j)⟩)) (hirr k i).1
  have hS : ∀ k i, (S k i).toRepresentation.IsIrreducible := fun k i =>
    (isIrreducibleSubspace_generatedMatrixStarAlgebra_iff U hU (S k i)).mp (hirr k i)
  refine ⟨K, d, m, b, S, hd, hm, fun _ _ => rfl, hS, ?_, ?_⟩
  · intro k k' hkk i i' hchar
    have := hS k i
    have := hS k' i'
    exact hcross k k' hkk i i'
      ((sameIsotype_generatedMatrixStarAlgebra_iff U hU (S k i) (S k' i')).mpr
        ((nonempty_equiv_iff_character_eq _ _).mpr hchar))
  · intro g
    exact hact (U g) (StarAlgebra.subset_adjoin ℂ (Set.range U) ⟨g, rfl⟩)
end Representation
