/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.MPDO.BiCFDerivation.Core
import TNLean.Algebra.SkolemNoether
import Mathlib.Algebra.Algebra.Prod

/-!
# Subdirect product algebra density for pair-span homogenization

This module contains the subdirect product algebra density portion:
`pairAlgSpan`, gauge-equivalence detection via Skolem–Noether, two-sided axis
ideals, `subdirect_matrix_pair_eq_top_or_eq_graph_algEquiv` and its
dependencies.  It is part of the pair-span homogenization layer for MPDO biCF.
-/

open scoped Matrix BigOperators

namespace MPSTensor

variable {d : ℕ} {r : ℕ} {dim : Fin r → ℕ}

abbrev MatD (D : ℕ) := Matrix (Fin D) (Fin D) ℂ

/-! ### Homogenizing cumulative pair spans -/

/-- The unital algebra generated by simultaneous pair words of one letter.

For equal bond dimensions this is the subdirect product algebra used in the
Burnside-Jacobson branch of the BNT pair-separation argument. -/
noncomputable def pairAlgSpan {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) :
    Subalgebra ℂ (Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ) :=
  Algebra.adjoin ℂ (Set.range fun i : Fin d => (A i, B i))

private lemma algebra_adjoin_eq_top_of_isInjective {D : ℕ} {A : MPSTensor d D}
    (hA : IsInjective A) :
    Algebra.adjoin ℂ (Set.range A) = (⊤ : Subalgebra ℂ (Matrix (Fin D) (Fin D) ℂ)) := by
  classical
  apply Subalgebra.ext
  intro M
  constructor
  · intro _
    trivial
  · intro _
    have htop : (Algebra.adjoin ℂ (Set.range A)).toSubmodule =
        (⊤ : Submodule ℂ (Matrix (Fin D) (Fin D) ℂ)) := by
      apply le_antisymm
      · exact le_top
      · rw [← hA]
        exact Algebra.span_le_adjoin ℂ (Set.range A)
    change M ∈ (Algebra.adjoin ℂ (Set.range A)).toSubmodule
    rw [htop]
    exact Submodule.mem_top

/-- The first coordinate projection of the pair algebra is full when the first
block is injective. -/
theorem pairAlgSpan_map_fst_eq_top_of_isInjective {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) (hA : IsInjective A) :
    (pairAlgSpan A B).map
      (AlgHom.fst ℂ (Matrix (Fin D₁) (Fin D₁) ℂ) (Matrix (Fin D₂) (Fin D₂) ℂ)) =
        (⊤ : Subalgebra ℂ (Matrix (Fin D₁) (Fin D₁) ℂ)) := by
  classical
  rw [pairAlgSpan, AlgHom.map_adjoin]
  have himage :
      (AlgHom.fst ℂ (Matrix (Fin D₁) (Fin D₁) ℂ) (Matrix (Fin D₂) (Fin D₂) ℂ)) ''
          Set.range (fun i : Fin d => (A i, B i)) =
        Set.range A := by
    ext M
    constructor
    · rintro ⟨P, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, rfl⟩
    · rintro ⟨i, rfl⟩
      exact ⟨(A i, B i), ⟨i, rfl⟩, rfl⟩
  rw [himage]
  exact algebra_adjoin_eq_top_of_isInjective hA

/-- The second coordinate projection of the pair algebra is full when the
second block is injective. -/
theorem pairAlgSpan_map_snd_eq_top_of_isInjective {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) (hB : IsInjective B) :
    (pairAlgSpan A B).map
      (AlgHom.snd ℂ (Matrix (Fin D₁) (Fin D₁) ℂ) (Matrix (Fin D₂) (Fin D₂) ℂ)) =
        (⊤ : Subalgebra ℂ (Matrix (Fin D₂) (Fin D₂) ℂ)) := by
  classical
  rw [pairAlgSpan, AlgHom.map_adjoin]
  have himage :
      (AlgHom.snd ℂ (Matrix (Fin D₁) (Fin D₁) ℂ) (Matrix (Fin D₂) (Fin D₂) ℂ)) ''
          Set.range (fun i : Fin d => (A i, B i)) =
        Set.range B := by
    ext M
    constructor
    · rintro ⟨P, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, rfl⟩
    · rintro ⟨i, rfl⟩
      exact ⟨(A i, B i), ⟨i, rfl⟩, rfl⟩
  rw [himage]
  exact algebra_adjoin_eq_top_of_isInjective hB

/-- Every finite simultaneous pair word lies in the pair algebra. -/
theorem pairEvalWordTuple_mem_pairAlgSpan {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) (w : List (Fin d)) :
    pairEvalWordTuple A B w ∈ pairAlgSpan A B := by
  induction w with
  | nil =>
      exact (pairAlgSpan A B).one_mem
  | cons i w ih =>
      have hgen : (A i, B i) ∈ pairAlgSpan A B := by
        exact Algebra.subset_adjoin ⟨i, rfl⟩
      exact (pairAlgSpan A B).mul_mem hgen ih

/-- The all-words pair span is closed under componentwise multiplication. -/
theorem pair_mul_mem_pairAllWordsSpan {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    {M N : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ}
    (hM : M ∈ pairAllWordsSpan A B) (hN : N ∈ pairAllWordsSpan A B) :
    (M.1 * N.1, M.2 * N.2) ∈ pairAllWordsSpan A B := by
  classical
  let W := pairAllWordsSpan A B
  have hleft_gen : ∀ w : List (Fin d),
      ((pairEvalWordTuple A B w).1 * N.1, (pairEvalWordTuple A B w).2 * N.2) ∈ W := by
    intro w
    induction hN using Submodule.span_induction with
    | mem N' hNmem =>
        rcases hNmem with ⟨v, rfl⟩
        have hEq :
            ((pairEvalWordTuple A B w).1 * (pairEvalWordTuple A B v).1,
              (pairEvalWordTuple A B w).2 * (pairEvalWordTuple A B v).2) =
              pairEvalWordTuple A B (w ++ v) := by
          ext <;> simp [pairEvalWordTuple, evalWord_append]
        rw [hEq]
        exact Submodule.subset_span ⟨w ++ v, rfl⟩
    | zero =>
        have hzero :
            ((pairEvalWordTuple A B w).1 *
                (0 : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ).1,
              (pairEvalWordTuple A B w).2 *
                (0 : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ).2) = 0 := by
          simp
        rw [hzero]
        exact Submodule.zero_mem _
    | add N₁ N₂ _ _ hN₁ hN₂ =>
        have hEq :
            ((pairEvalWordTuple A B w).1 * (N₁ + N₂).1,
              (pairEvalWordTuple A B w).2 * (N₁ + N₂).2) =
              ((pairEvalWordTuple A B w).1 * N₁.1,
                (pairEvalWordTuple A B w).2 * N₁.2) +
              ((pairEvalWordTuple A B w).1 * N₂.1,
                (pairEvalWordTuple A B w).2 * N₂.2) := by
          ext <;> simp [Matrix.mul_add]
        rw [hEq]
        exact Submodule.add_mem _ hN₁ hN₂
    | smul a N _ hN =>
        have hEq :
            ((pairEvalWordTuple A B w).1 * (a • N).1,
              (pairEvalWordTuple A B w).2 * (a • N).2) =
              a • ((pairEvalWordTuple A B w).1 * N.1,
                (pairEvalWordTuple A B w).2 * N.2) := by
          ext <;> simp
        rw [hEq]
        exact Submodule.smul_mem _ a hN
  induction hM using Submodule.span_induction with
  | mem M hMmem =>
      rcases hMmem with ⟨w, rfl⟩
      exact hleft_gen w
  | zero =>
      have hzero :
          ((0 : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ).1 * N.1,
            (0 : Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ).2 * N.2) = 0 := by
        simp
      rw [hzero]
      exact Submodule.zero_mem _
  | add M₁ M₂ _ _ hM₁ hM₂ =>
      have hEq : ((M₁ + M₂).1 * N.1, (M₁ + M₂).2 * N.2) =
          (M₁.1 * N.1, M₁.2 * N.2) + (M₂.1 * N.1, M₂.2 * N.2) := by
        ext <;> simp [Matrix.add_mul]
      rw [hEq]
      exact Submodule.add_mem _ hM₁ hM₂
  | smul a M _ hM =>
      have hEq : ((a • M).1 * N.1, (a • M).2 * N.2) =
          a • (M.1 * N.1, M.2 * N.2) := by
        ext <;> simp
      rw [hEq]
      exact Submodule.smul_mem _ a hM

/-- The submodule underlying the pair algebra is contained in the all-words
pair span. -/
theorem pairAlgSpan_toSubmodule_le_pairAllWordsSpan {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂) :
    (pairAlgSpan A B).toSubmodule ≤ pairAllWordsSpan A B := by
  intro M hM
  change M ∈ pairAllWordsSpan A B
  induction hM using Algebra.adjoin_induction with
  | mem M hM =>
      rcases hM with ⟨i, rfl⟩
      have hword : pairEvalWordTuple A B [i] ∈ pairAllWordsSpan A B :=
        Submodule.subset_span ⟨[i], rfl⟩
      simpa [pairEvalWordTuple] using hword
  | algebraMap r =>
      have hone : pairEvalWordTuple A B [] ∈ pairAllWordsSpan A B :=
        Submodule.subset_span ⟨[], rfl⟩
      simpa [pairEvalWordTuple, Algebra.smul_def] using
        (pairAllWordsSpan A B).smul_mem r hone
  | add _ _ _ _ hx hy =>
      exact Submodule.add_mem _ hx hy
  | mul x y _ _ hx hy =>
      exact pair_mul_mem_pairAllWordsSpan A B hx hy

/-- If the generated pair algebra is the whole product algebra, then all finite
pair words span the whole product algebra linearly. -/
theorem pairAllWordsSpanTop_of_pairAlgSpan_eq_top {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hAlg : pairAlgSpan A B =
      (⊤ : Subalgebra ℂ
        (Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ))) :
    PairAllWordsSpanTop A B := by
  unfold PairAllWordsSpanTop
  apply eq_top_iff.mpr
  intro M _
  have hM : M ∈ (pairAlgSpan A B).toSubmodule := by
    rw [hAlg]
    exact Submodule.mem_top
  exact pairAlgSpan_toSubmodule_le_pairAllWordsSpan A B hM

/-- Full pair algebra gives all-length pair trace separation. -/
theorem pairTraceSeparatingAll_of_pairAlgSpan_eq_top {D₁ D₂ : ℕ}
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hAlg : pairAlgSpan A B =
      (⊤ : Subalgebra ℂ
        (Matrix (Fin D₁) (Fin D₁) ℂ × Matrix (Fin D₂) (Fin D₂) ℂ))) :
    PairTraceSeparatingAll A B :=
  pairTraceSeparatingAll_of_pairAllWordsSpanTop A B
    (pairAllWordsSpanTop_of_pairAlgSpan_eq_top A B hAlg)

/-- If the pair algebra is the graph of an automorphism of the matrix algebra,
then the two tensors are gauge-phase equivalent.

This is the Skolem-Noether endpoint of the graph branch in the subdirect-product
proof route for the pair algebra. -/
theorem gaugePhaseEquiv_of_pairAlgSpan_eq_graph_algEquiv
    {d D : ℕ} [NeZero D] (A B : MPSTensor d D)
    (φ : MatD D ≃ₐ[ℂ] MatD D)
    (hS : pairAlgSpan A B =
      AlgHom.range
        ((AlgHom.id ℂ (MatD D)).prod (φ : MatD D →ₐ[ℂ] MatD D))) :
    GaugePhaseEquiv A B := by
  classical
  have hGraph : ∀ i : Fin d, B i = φ (A i) := by
    intro i
    have hgen : (A i, B i) ∈ pairAlgSpan A B := by
      exact Algebra.subset_adjoin ⟨i, rfl⟩
    rw [hS] at hgen
    rcases hgen with ⟨M, hM⟩
    have hfst : M = A i := by
      simpa using congrArg Prod.fst hM
    have hsnd : φ M = B i := by
      simpa using congrArg Prod.snd hM
    simpa [hfst] using hsnd.symm
  rcases skolemNoether_matrix φ with ⟨X, hX⟩
  exact GaugeEquiv.toGaugePhaseEquiv ⟨X, fun i => by
    rw [hGraph i, hX (A i)]⟩

/-- Under non-gauge-equivalence, the pair algebra cannot be the graph of a
matrix-algebra automorphism. -/
theorem not_pairAlgSpan_eq_graph_algEquiv_of_not_gaugePhaseEquiv
    {d D : ℕ} [NeZero D] (A B : MPSTensor d D)
    (hNot : ¬ GaugePhaseEquiv A B)
    (φ : MatD D ≃ₐ[ℂ] MatD D) :
    pairAlgSpan A B ≠
      AlgHom.range
        ((AlgHom.id ℂ (MatD D)).prod (φ : MatD D →ₐ[ℂ] MatD D)) := by
  intro hS
  exact hNot (gaugePhaseEquiv_of_pairAlgSpan_eq_graph_algEquiv A B φ hS)

private theorem subalgebra_prod_eq_top_of_axes {R A B : Type*}
    [CommSemiring R] [Semiring A] [Algebra R A] [Semiring B] [Algebra R B]
    (S : Subalgebra R (A × B))
    (hfst : ∀ x : A, (x, 0) ∈ S)
    (hsnd : ∀ y : B, (0, y) ∈ S) :
    S = ⊤ := by
  apply eq_top_iff.mpr
  rintro ⟨x, y⟩ _
  simpa using S.add_mem (hfst x) (hsnd y)

/-- If both coordinate axes lie in a matrix-pair subalgebra, the subalgebra is
the whole product. This is the top branch of the subdirect-product dichotomy
used in the pair-algebra density route. -/
theorem matrixPairSubalgebra_eq_top_of_axes {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : ∀ x : MatD D, (x, 0) ∈ S)
    (hsnd : ∀ y : MatD D, (0, y) ∈ S) :
    S = ⊤ :=
  subalgebra_prod_eq_top_of_axes S hfst hsnd

private noncomputable def leftAxisIdeal {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤) :
    TwoSidedIdeal (MatD D) :=
  TwoSidedIdeal.mk'
    {x : MatD D | (x, 0) ∈ S}
    S.zero_mem
    (fun hx hy => by simpa using S.add_mem hx hy)
    (fun hx => by simpa using S.neg_mem hx)
    (fun {x y} hy => by
      have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D) (MatD D)) := by
        rw [hfst]
        trivial
      rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
      have hpx' : p.1 = x := by simpa using hpx
      have hmul : (p * (y, 0)) ∈ S := S.mul_mem hpS hy
      have hprod : p * (y, 0) = (x * y, 0) := by
        ext <;> simp [hpx']
      simpa [hprod] using hmul)
    (fun {x y} hx => by
      have hymap : y ∈ S.map (AlgHom.fst ℂ (MatD D) (MatD D)) := by
        rw [hfst]
        trivial
      rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
      have hpy' : p.1 = y := by simpa using hpy
      have hmul : ((x, 0) * p) ∈ S := S.mul_mem hx hpS
      have hprod : (x, 0) * p = (x * y, 0) := by
        ext <;> simp [hpy']
      simpa [hprod] using hmul)

private noncomputable def rightAxisIdeal {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤) :
    TwoSidedIdeal (MatD D) :=
  TwoSidedIdeal.mk'
    {y : MatD D | (0, y) ∈ S}
    S.zero_mem
    (fun hx hy => by simpa using S.add_mem hx hy)
    (fun hx => by simpa using S.neg_mem hx)
    (fun {x y} hy => by
      have hxmap : x ∈ S.map (AlgHom.snd ℂ (MatD D) (MatD D)) := by
        rw [hsnd]
        trivial
      rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
      have hpx' : p.2 = x := by simpa using hpx
      have hmul : (p * (0, y)) ∈ S := S.mul_mem hpS hy
      have hprod : p * (0, y) = (0, x * y) := by
        ext <;> simp [hpx']
      simpa [hprod] using hmul)
    (fun {x y} hx => by
      have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D) (MatD D)) := by
        rw [hsnd]
        trivial
      rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
      have hpy' : p.2 = y := by simpa using hpy
      have hmul : ((0, x) * p) ∈ S := S.mul_mem hx hpS
      have hprod : (0, x) * p = (0, x * y) := by
        ext <;> simp [hpy']
      simpa [hprod] using hmul)

/-- A full left-axis ideal forces a subdirect matrix-pair subalgebra to be the
whole product. -/
theorem matrixPairSubalgebra_eq_top_of_leftAxisIdeal_eq_top {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤)
    (hleft : leftAxisIdeal S hfst = ⊤) :
    S = ⊤ := by
  apply matrixPairSubalgebra_eq_top_of_axes
  · intro x
    have hx : x ∈ leftAxisIdeal S hfst := by rw [hleft]; trivial
    simpa [leftAxisIdeal] using hx
  · intro y
    have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D) (MatD D)) := by
      rw [hsnd]
      trivial
    rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
    have hpy' : p.2 = y := by simpa using hpy
    have hneg : (-p.1, 0) ∈ S := by
      have hx : -p.1 ∈ leftAxisIdeal S hfst := by rw [hleft]; trivial
      simpa [leftAxisIdeal] using hx
    have hadd : (-p.1, 0) + p ∈ S := S.add_mem hneg hpS
    have hsum : (-p.1, 0) + p = (0, y) := by
      ext <;> simp [hpy']
    simpa [hsum] using hadd

/-- A full right-axis ideal forces a subdirect matrix-pair subalgebra to be the
whole product. -/
theorem matrixPairSubalgebra_eq_top_of_rightAxisIdeal_eq_top {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤)
    (hright : rightAxisIdeal S hsnd = ⊤) :
    S = ⊤ := by
  apply matrixPairSubalgebra_eq_top_of_axes
  · intro x
    have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D) (MatD D)) := by
      rw [hfst]
      trivial
    rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
    have hpx' : p.1 = x := by simpa using hpx
    have hneg : (0, -p.2) ∈ S := by
      have hy : -p.2 ∈ rightAxisIdeal S hsnd := by rw [hright]; trivial
      simpa [rightAxisIdeal] using hy
    have hadd : p + (0, -p.2) ∈ S := S.add_mem hpS hneg
    have hsum : p + (0, -p.2) = (x, 0) := by
      ext <;> simp [hpx']
    simpa [hsum] using hadd
  · intro y
    have hy : y ∈ rightAxisIdeal S hsnd := by rw [hright]; trivial
    simpa [rightAxisIdeal] using hy

private theorem fstProjection_injective_of_rightAxisIdeal_eq_bot {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤)
    (hright : rightAxisIdeal S hsnd = ⊥) :
    Function.Injective ((AlgHom.fst ℂ (MatD D) (MatD D)).comp S.val) := by
  intro x y hxy
  apply Subtype.ext
  apply Prod.ext
  · exact hxy
  · have hdiffS : x.1 - y.1 ∈ S := S.sub_mem x.2 y.2
    have hfirst : x.1.1 - y.1.1 = 0 := sub_eq_zero.mpr hxy
    have haxis : x.1.2 - y.1.2 ∈ rightAxisIdeal S hsnd := by
      have hdiff : x.1 - y.1 = (0, x.1.2 - y.1.2) := by
        apply Prod.ext
        · exact hfirst
        · rfl
      simpa [rightAxisIdeal] using (hdiff ▸ hdiffS)
    have hbot : x.1.2 - y.1.2 ∈ (⊥ : TwoSidedIdeal (MatD D)) := by
      simpa [hright] using haxis
    exact sub_eq_zero.mp (by simpa using hbot)

private theorem sndProjection_injective_of_leftAxisIdeal_eq_bot {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤)
    (hleft : leftAxisIdeal S hfst = ⊥) :
    Function.Injective ((AlgHom.snd ℂ (MatD D) (MatD D)).comp S.val) := by
  intro x y hxy
  apply Subtype.ext
  apply Prod.ext
  · have hdiffS : x.1 - y.1 ∈ S := S.sub_mem x.2 y.2
    have hsecond : x.1.2 - y.1.2 = 0 := sub_eq_zero.mpr hxy
    have haxis : x.1.1 - y.1.1 ∈ leftAxisIdeal S hfst := by
      have hdiff : x.1 - y.1 = (x.1.1 - y.1.1, 0) := by
        apply Prod.ext
        · rfl
        · exact hsecond
      simpa [leftAxisIdeal] using (hdiff ▸ hdiffS)
    have hbot : x.1.1 - y.1.1 ∈ (⊥ : TwoSidedIdeal (MatD D)) := by
      simpa [hleft] using haxis
    exact sub_eq_zero.mp (by simpa using hbot)
  · exact hxy

private noncomputable def leftAxisIdealHetero {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤) :
    TwoSidedIdeal (MatD D₁) :=
  TwoSidedIdeal.mk'
    {x : MatD D₁ | (x, 0) ∈ S}
    S.zero_mem
    (fun hx hy => by simpa using S.add_mem hx hy)
    (fun hx => by simpa using S.neg_mem hx)
    (fun {x y} hy => by
      have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) := by
        rw [hfst]
        trivial
      rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
      have hpx' : p.1 = x := by simpa using hpx
      have hmul : (p * (y, 0)) ∈ S := S.mul_mem hpS hy
      have hprod : p * (y, 0) = (x * y, 0) := by
        ext <;> simp [hpx']
      simpa [hprod] using hmul)
    (fun {x y} hx => by
      have hymap : y ∈ S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) := by
        rw [hfst]
        trivial
      rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
      have hpy' : p.1 = y := by simpa using hpy
      have hmul : ((x, 0) * p) ∈ S := S.mul_mem hx hpS
      have hprod : (x, 0) * p = (x * y, 0) := by
        ext <;> simp [hpy']
      simpa [hprod] using hmul)

private noncomputable def rightAxisIdealHetero {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤) :
    TwoSidedIdeal (MatD D₂) :=
  TwoSidedIdeal.mk'
    {y : MatD D₂ | (0, y) ∈ S}
    S.zero_mem
    (fun hx hy => by simpa using S.add_mem hx hy)
    (fun hx => by simpa using S.neg_mem hx)
    (fun {x y} hy => by
      have hxmap : x ∈ S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) := by
        rw [hsnd]
        trivial
      rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
      have hpx' : p.2 = x := by simpa using hpx
      have hmul : (p * (0, y)) ∈ S := S.mul_mem hpS hy
      have hprod : p * (0, y) = (0, x * y) := by
        ext <;> simp [hpx']
      simpa [hprod] using hmul)
    (fun {x y} hx => by
      have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) := by
        rw [hsnd]
        trivial
      rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
      have hpy' : p.2 = y := by simpa using hpy
      have hmul : ((0, x) * p) ∈ S := S.mul_mem hx hpS
      have hprod : (0, x) * p = (0, x * y) := by
        ext <;> simp [hpy']
      simpa [hprod] using hmul)

private theorem matrixPairSubalgebra_eq_top_of_leftAxisIdealHetero_eq_top {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hleft : leftAxisIdealHetero S hfst = ⊤) :
    S = ⊤ := by
  apply subalgebra_prod_eq_top_of_axes
  · intro x
    have hx : x ∈ leftAxisIdealHetero S hfst := by rw [hleft]; trivial
    simpa [leftAxisIdealHetero] using hx
  · intro y
    have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) := by
      rw [hsnd]
      trivial
    rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
    have hpy' : p.2 = y := by simpa using hpy
    have hneg : (-p.1, 0) ∈ S := by
      have hx : -p.1 ∈ leftAxisIdealHetero S hfst := by rw [hleft]; trivial
      simpa [leftAxisIdealHetero] using hx
    have hadd : (-p.1, 0) + p ∈ S := S.add_mem hneg hpS
    have hsum : (-p.1, 0) + p = (0, y) := by
      ext <;> simp [hpy']
    simpa [hsum] using hadd

private theorem matrixPairSubalgebra_eq_top_of_rightAxisIdealHetero_eq_top {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hright : rightAxisIdealHetero S hsnd = ⊤) :
    S = ⊤ := by
  apply subalgebra_prod_eq_top_of_axes
  · intro x
    have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) := by
      rw [hfst]
      trivial
    rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
    have hpx' : p.1 = x := by simpa using hpx
    have hneg : (0, -p.2) ∈ S := by
      have hy : -p.2 ∈ rightAxisIdealHetero S hsnd := by rw [hright]; trivial
      simpa [rightAxisIdealHetero] using hy
    have hadd : p + (0, -p.2) ∈ S := S.add_mem hpS hneg
    have hsum : p + (0, -p.2) = (x, 0) := by
      ext <;> simp [hpx']
    simpa [hsum] using hadd
  · intro y
    have hy : y ∈ rightAxisIdealHetero S hsnd := by rw [hright]; trivial
    simpa [rightAxisIdealHetero] using hy

private theorem fstProjectionHetero_injective_of_rightAxisIdeal_eq_bot {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hright : rightAxisIdealHetero S hsnd = ⊥) :
    Function.Injective ((AlgHom.fst ℂ (MatD D₁) (MatD D₂)).comp S.val) := by
  intro x y hxy
  apply Subtype.ext
  apply Prod.ext
  · exact hxy
  · have hdiffS : x.1 - y.1 ∈ S := S.sub_mem x.2 y.2
    have hfirst : x.1.1 - y.1.1 = 0 := sub_eq_zero.mpr hxy
    have haxis : x.1.2 - y.1.2 ∈ rightAxisIdealHetero S hsnd := by
      have hdiff : x.1 - y.1 = (0, x.1.2 - y.1.2) := by
        apply Prod.ext
        · exact hfirst
        · rfl
      simpa [rightAxisIdealHetero] using (hdiff ▸ hdiffS)
    have hbot : x.1.2 - y.1.2 ∈ (⊥ : TwoSidedIdeal (MatD D₂)) := by
      simpa [hright] using haxis
    exact sub_eq_zero.mp (by simpa using hbot)

private theorem sndProjectionHetero_injective_of_leftAxisIdeal_eq_bot {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hleft : leftAxisIdealHetero S hfst = ⊥) :
    Function.Injective ((AlgHom.snd ℂ (MatD D₁) (MatD D₂)).comp S.val) := by
  intro x y hxy
  apply Subtype.ext
  apply Prod.ext
  · have hdiffS : x.1 - y.1 ∈ S := S.sub_mem x.2 y.2
    have hsecond : x.1.2 - y.1.2 = 0 := sub_eq_zero.mpr hxy
    have haxis : x.1.1 - y.1.1 ∈ leftAxisIdealHetero S hfst := by
      have hdiff : x.1 - y.1 = (x.1.1 - y.1.1, 0) := by
        apply Prod.ext
        · rfl
        · exact hsecond
      simpa [leftAxisIdealHetero] using (hdiff ▸ hdiffS)
    have hbot : x.1.1 - y.1.1 ∈ (⊥ : TwoSidedIdeal (MatD D₁)) := by
      simpa [hleft] using haxis
    exact sub_eq_zero.mp (by simpa using hbot)
  · exact hxy

private theorem fstProjectionHetero_surjective_of_map_eq_top {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤) :
    Function.Surjective ((AlgHom.fst ℂ (MatD D₁) (MatD D₂)).comp S.val) := by
  intro x
  have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) := by
    rw [hfst]
    trivial
  rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
  exact ⟨⟨p, hpS⟩, by simpa using hpx⟩

private theorem sndProjectionHetero_surjective_of_map_eq_top {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤) :
    Function.Surjective ((AlgHom.snd ℂ (MatD D₁) (MatD D₂)).comp S.val) := by
  intro y
  have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) := by
    rw [hsnd]
    trivial
  rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
  exact ⟨⟨p, hpS⟩, by simpa using hpy⟩

private theorem matrixAlgEquiv_dim_eq {D₁ D₂ : ℕ}
    (e : MatD D₁ ≃ₐ[ℂ] MatD D₂) :
    D₁ = D₂ := by
  have hfin := LinearEquiv.finrank_eq (e : MatD D₁ ≃ₗ[ℂ] MatD D₂)
  simp [MatD, Module.finrank_matrix, Fintype.card_fin] at hfin
  exact Nat.mul_self_inj.mp hfin

private noncomputable def matrixPairSubalgebra_algEquiv_of_axisIdealsHetero_eq_bot {D₁ D₂ : ℕ}
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hleft : leftAxisIdealHetero S hfst = ⊥)
    (hright : rightAxisIdealHetero S hsnd = ⊥) :
    MatD D₁ ≃ₐ[ℂ] MatD D₂ := by
  let p₁ : S →ₐ[ℂ] MatD D₁ := (AlgHom.fst ℂ (MatD D₁) (MatD D₂)).comp S.val
  let p₂ : S →ₐ[ℂ] MatD D₂ := (AlgHom.snd ℂ (MatD D₁) (MatD D₂)).comp S.val
  have hp₁ : Function.Bijective p₁ :=
    ⟨fstProjectionHetero_injective_of_rightAxisIdeal_eq_bot S hsnd hright,
      fstProjectionHetero_surjective_of_map_eq_top S hfst⟩
  have hp₂ : Function.Bijective p₂ :=
    ⟨sndProjectionHetero_injective_of_leftAxisIdeal_eq_bot S hfst hleft,
      sndProjectionHetero_surjective_of_map_eq_top S hsnd⟩
  let e₁ : S ≃ₐ[ℂ] MatD D₁ := AlgEquiv.ofBijective p₁ hp₁
  let e₂ : S ≃ₐ[ℂ] MatD D₂ := AlgEquiv.ofBijective p₂ hp₂
  exact e₁.symm.trans e₂

/-- A subdirect product of two full matrix algebras of different sizes is the
whole product. -/
theorem subdirect_matrix_pair_eq_top_of_dim_ne {D₁ D₂ : ℕ} [NeZero D₁] [NeZero D₂]
    (S : Subalgebra ℂ (MatD D₁ × MatD D₂))
    (hfst : S.map (AlgHom.fst ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D₁) (MatD D₂)) = ⊤)
    (hdim : D₁ ≠ D₂) :
    S = ⊤ := by
  classical
  haveI : Nonempty (Fin D₁) := Fin.pos_iff_nonempty.mp (Nat.pos_of_neZero D₁)
  haveI : Nonempty (Fin D₂) := Fin.pos_iff_nonempty.mp (Nat.pos_of_neZero D₂)
  haveI : IsSimpleRing (MatD D₁) := IsSimpleRing.matrix (Fin D₁) ℂ
  haveI : IsSimpleRing (MatD D₂) := IsSimpleRing.matrix (Fin D₂) ℂ
  rcases eq_bot_or_eq_top (leftAxisIdealHetero S hfst) with hleft | hleft
  · rcases eq_bot_or_eq_top (rightAxisIdealHetero S hsnd) with hright | hright
    · exact False.elim
        (hdim (matrixAlgEquiv_dim_eq
          (matrixPairSubalgebra_algEquiv_of_axisIdealsHetero_eq_bot
            S hfst hsnd hleft hright)))
    · exact matrixPairSubalgebra_eq_top_of_rightAxisIdealHetero_eq_top S hfst hsnd hright
  · exact matrixPairSubalgebra_eq_top_of_leftAxisIdealHetero_eq_top S hfst hsnd hleft

private theorem fstProjection_surjective_of_map_eq_top {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤) :
    Function.Surjective ((AlgHom.fst ℂ (MatD D) (MatD D)).comp S.val) := by
  intro x
  have hxmap : x ∈ S.map (AlgHom.fst ℂ (MatD D) (MatD D)) := by
    rw [hfst]
    trivial
  rcases (Subalgebra.mem_map.mp hxmap) with ⟨p, hpS, hpx⟩
  exact ⟨⟨p, hpS⟩, by simpa using hpx⟩

private theorem sndProjection_surjective_of_map_eq_top {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤) :
    Function.Surjective ((AlgHom.snd ℂ (MatD D) (MatD D)).comp S.val) := by
  intro y
  have hymap : y ∈ S.map (AlgHom.snd ℂ (MatD D) (MatD D)) := by
    rw [hsnd]
    trivial
  rcases (Subalgebra.mem_map.mp hymap) with ⟨p, hpS, hpy⟩
  exact ⟨⟨p, hpS⟩, by simpa using hpy⟩

/-- If both axis ideals are trivial, a subdirect matrix-pair subalgebra is the
graph of a matrix-algebra automorphism. -/
theorem matrixPairSubalgebra_eq_graph_algEquiv_of_axisIdeals_eq_bot {D : ℕ}
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤)
    (hleft : leftAxisIdeal S hfst = ⊥)
    (hright : rightAxisIdeal S hsnd = ⊥) :
    ∃ φ : MatD D ≃ₐ[ℂ] MatD D,
      S =
        AlgHom.range
          ((AlgHom.id ℂ (MatD D)).prod (φ : MatD D →ₐ[ℂ] MatD D)) := by
  let p₁ : S →ₐ[ℂ] MatD D := (AlgHom.fst ℂ (MatD D) (MatD D)).comp S.val
  let p₂ : S →ₐ[ℂ] MatD D := (AlgHom.snd ℂ (MatD D) (MatD D)).comp S.val
  have hp₁ : Function.Bijective p₁ :=
    ⟨fstProjection_injective_of_rightAxisIdeal_eq_bot S hsnd hright,
      fstProjection_surjective_of_map_eq_top S hfst⟩
  have hp₂ : Function.Bijective p₂ :=
    ⟨sndProjection_injective_of_leftAxisIdeal_eq_bot S hfst hleft,
      sndProjection_surjective_of_map_eq_top S hsnd⟩
  let e₁ : S ≃ₐ[ℂ] MatD D := AlgEquiv.ofBijective p₁ hp₁
  let e₂ : S ≃ₐ[ℂ] MatD D := AlgEquiv.ofBijective p₂ hp₂
  refine ⟨e₁.symm.trans e₂, ?_⟩
  apply SetLike.ext
  intro z
  constructor
  · intro hz
    let s : S := ⟨z, hz⟩
    refine ⟨z.1, ?_⟩
    apply Prod.ext
    · rfl
    · change (e₁.symm.trans e₂) z.1 = z.2
      have he₁ : e₁ s = z.1 := rfl
      have hs : e₁.symm z.1 = s := by
        simpa [he₁] using e₁.symm_apply_apply s
      calc
        (e₁.symm.trans e₂) z.1 = e₂ (e₁.symm z.1) := rfl
        _ = e₂ s := by rw [hs]
        _ = z.2 := rfl
  · rintro ⟨x, rfl⟩
    have hval :
        (↑(e₁.symm x) : MatD D × MatD D) =
          ((AlgHom.id ℂ (MatD D)).prod (e₁.symm.trans e₂ : MatD D →ₐ[ℂ] MatD D)) x := by
      apply Prod.ext
      · exact e₁.apply_symm_apply x
      · rfl
    simpa [hval] using (e₁.symm x).property

/-- Matrix-pair subdirect products are either the full product or the graph of
a matrix-algebra automorphism. -/
theorem subdirect_matrix_pair_eq_top_or_eq_graph_algEquiv {D : ℕ} [NeZero D]
    (S : Subalgebra ℂ (MatD D × MatD D))
    (hfst : S.map (AlgHom.fst ℂ (MatD D) (MatD D)) = ⊤)
    (hsnd : S.map (AlgHom.snd ℂ (MatD D) (MatD D)) = ⊤) :
    S = ⊤ ∨
      ∃ φ : MatD D ≃ₐ[ℂ] MatD D,
        S =
          AlgHom.range
            ((AlgHom.id ℂ (MatD D)).prod (φ : MatD D →ₐ[ℂ] MatD D)) := by
  classical
  haveI : Nonempty (Fin D) := Fin.pos_iff_nonempty.mp (Nat.pos_of_neZero D)
  haveI : IsSimpleRing (MatD D) := IsSimpleRing.matrix (Fin D) ℂ
  rcases eq_bot_or_eq_top (leftAxisIdeal S hfst) with hleft | hleft
  · rcases eq_bot_or_eq_top (rightAxisIdeal S hsnd) with hright | hright
    · exact Or.inr
        (matrixPairSubalgebra_eq_graph_algEquiv_of_axisIdeals_eq_bot
          S hfst hsnd hleft hright)
    · exact Or.inl (matrixPairSubalgebra_eq_top_of_rightAxisIdeal_eq_top S hfst hsnd hright)
  · exact Or.inl (matrixPairSubalgebra_eq_top_of_leftAxisIdeal_eq_top S hfst hsnd hleft)

end MPSTensor
