/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.MPDO.BiCFDerivation.PairHomogenization.Algebra
import TNLean.MPS.MPDO.BiCFDerivation.PairHomogenization.Span

/-!
# Burnside–Jacobson homogenization for MPDO biCF

This module contains the finite-family separation and the Burnside–Jacobson
connection to `PairTraceSeparatingAt`.  It imports `Algebra` and `Span` from
the pair-homogenization subpackage and completes the pair-span homogenization
layer.
-/

open scoped Matrix BigOperators

namespace MPSTensor

variable {d : ℕ} {r : ℕ} {dim : Fin r → ℕ}

/-- A finite family of all-words pair-separation hypotheses and per-pair
period-window identity-padding certificates admits one common homogeneous
trace-separating length.

The proof is a finite-family arithmetic reduction: the mathematical hypothesis
is the period-window identity certificate for each ordered pair. -/
theorem
    exists_forall_pairTraceSeparatingAt_of_pairTraceSeparatingAll_of_identity_period_windows
    (A : (k : Fin r) → MPSTensor d (dim k))
    (hSep : ∀ k j : Fin r, j ≠ k → PairTraceSeparatingAll (A k) (A j))
    (hWindow : ∀ k j : Fin r, j ≠ k → ∃ start period : ℕ, 0 < period ∧
      ((1 : Matrix (Fin (dim k)) (Fin (dim k)) ℂ),
          (1 : Matrix (Fin (dim j)) (Fin (dim j)) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple (A k) (A j) period)) ∧
      ∀ s : ℕ, s < period →
        ((1 : Matrix (Fin (dim k)) (Fin (dim k)) ℂ),
            (1 : Matrix (Fin (dim j)) (Fin (dim j)) ℂ)) ∈
          Submodule.span ℂ (Set.range (pairWordTuple (A k) (A j) (start + s)))) :
    ∃ T : ℕ, ∀ k j : Fin r, j ≠ k → PairTraceSeparatingAt (A k) (A j) T := by
  refine exists_forall_pairTraceSeparatingAt_of_pairTraceSeparatingAll_of_identity_padding
    A hSep ?_
  intro k j hj
  rcases hWindow k j hj with ⟨start, period, hperiod_pos, hperiod, hwindow⟩
  exact pairIdentity_mem_pairWordTupleSpan_eventually_of_period_window
    (A k) (A j) hperiod_pos hperiod hwindow

/-- A finite family of all-words pair-separation hypotheses and per-pair
period windows of full homogeneous pair spans admits one common homogeneous
trace-separating length.

This is the homogeneous-span version of
`exists_forall_pairTraceSeparatingAt_of_pairTraceSeparatingAll_of_identity_period_windows`.
It keeps the fixed-length period-window hypothesis explicit and only converts
full homogeneous pair span into the identity-padding certificates needed by the
generic homogenization theorem. -/
theorem
    exists_forall_pairTraceSeparatingAt_of_pairSpanTop_period_windows
    (A : (k : Fin r) → MPSTensor d (dim k))
    (hSep : ∀ k j : Fin r, j ≠ k → PairTraceSeparatingAll (A k) (A j))
    (hWindow : ∀ k j : Fin r, j ≠ k → ∃ start period : ℕ, 0 < period ∧
      PairWordTupleSpanTop (A k) (A j) period ∧
      ∀ s : ℕ, s < period → PairWordTupleSpanTop (A k) (A j) (start + s)) :
    ∃ T : ℕ, ∀ k j : Fin r, j ≠ k → PairTraceSeparatingAt (A k) (A j) T := by
  refine exists_forall_pairTraceSeparatingAt_of_pairTraceSeparatingAll_of_identity_period_windows
    A hSep ?_
  intro k j hj
  rcases hWindow k j hj with ⟨start, period, hperiod_pos, hperiod, hwindow⟩
  refine ⟨start, period, hperiod_pos, ?_, ?_⟩
  · exact pairIdentity_mem_pairWordTupleSpan_of_pairWordTupleSpanTop (A k) (A j) hperiod
  · intro s hs
    exact pairIdentity_mem_pairWordTupleSpan_of_pairWordTupleSpanTop (A k) (A j)
      (hwindow s hs)

/-! ### Burnside–Jacobson homogenization: from non-equivalence to homogeneous separation

The theorems in this section connect BNT block non-equivalence — when injective
blocks are not gauge-phase equivalent — to the existence of a homogeneous length
`T` at which the pair traces separate.

**Spectral approach:** non-gauge-equivalence forces the spectral radius of the
mixed transfer map below one, so the matrix-product-vector overlap decays to
zero.  This is the non-decaying overlap argument from the spectral-gap
development.

**Algebraic approach (this section):** non-gauge-equivalence implies all-length
pair trace separation, which yields a cumulative finite cutoff and, after
identity padding, a single homogeneous length.  The identity-padding input is
the remaining Burnside–Jacobson algebraic step for the pair algebra.
-/

/-- **Pair product-algebra density for non-gauge-equivalent injective blocks.**

For two injective blocks of the same bond dimension, if they are not
gauge-phase equivalent then the algebra generated by the simultaneous
one-letter pairs `(A i, B i)` is the full product matrix algebra. -/
theorem pairAlgSpan_eq_top_of_injective_not_gaugePhaseEquiv
    {d D : ℕ} [NeZero D]
    (A B : MPSTensor d D)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hNot : ¬ GaugePhaseEquiv A B) :
    pairAlgSpan A B =
      (⊤ : Subalgebra ℂ (MatD D × MatD D)) := by
  have hfst := pairAlgSpan_map_fst_eq_top_of_isInjective A B hA_inj
  have hsnd := pairAlgSpan_map_snd_eq_top_of_isInjective A B hB_inj
  rcases subdirect_matrix_pair_eq_top_or_eq_graph_algEquiv
      (pairAlgSpan A B) hfst hsnd with htop | hgraph
  · exact htop
  · rcases hgraph with ⟨φ, hφ⟩
    exact False.elim
      ((not_pairAlgSpan_eq_graph_algEquiv_of_not_gaugePhaseEquiv A B hNot φ) hφ)

/-- **Pair product-algebra density for injective blocks of unequal dimensions.**

If the two blocks are individually injective and have different bond
dimensions, the simultaneous pair algebra is the full product algebra.  The
subdirect-product graph branch would give an algebra equivalence between the
two full matrix algebras, which is impossible because their finite dimensions
over `ℂ` are `D₁^2` and `D₂^2`. -/
theorem pairAlgSpan_eq_top_of_injective_dim_ne
    {d D₁ D₂ : ℕ} [NeZero D₁] [NeZero D₂]
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hdim : D₁ ≠ D₂) :
    pairAlgSpan A B =
      (⊤ : Subalgebra ℂ (MatD D₁ × MatD D₂)) := by
  have hfst := pairAlgSpan_map_fst_eq_top_of_isInjective A B hA_inj
  have hsnd := pairAlgSpan_map_snd_eq_top_of_isInjective A B hB_inj
  exact subdirect_matrix_pair_eq_top_of_dim_ne (pairAlgSpan A B) hfst hsnd hdim

/-- **BNT non-equivalence ⇒ all-length pair trace separation.**
For injective, left-canonical tensors `A, B` of the same dimension that are
not gauge-phase-equivalent, no nonzero pair of test matrices `(Δ_A, Δ_B)` can
annihilate the pair-trace functional `tr(Δ_A · A^w) + tr(Δ_B · B^w)` for all
words `w`.

The proof analyzes the pair product algebra `S := alg{(Aᵢ, Bᵢ) | i}` inside
`M_{D}(ℂ) × M_{D}(ℂ)`.  Because `A` and `B` are individually injective, the two
coordinate projections of `S` are the full matrix algebra.  A subdirect-product
argument then leaves two possibilities: either a coordinate kernel supplies the
two axes and hence `S = M_D × M_D`, or `S` is the graph of an algebra
automorphism of `M_D`.  In the graph case, Skolem–Noether turns the
automorphism into a gauge equivalence, contradicting the non-gauge-equivalence
hypothesis.  The full-product conclusion is exactly the statement that the pair
word tuples over all word lengths span the full product algebra.  By duality
this is exactly the all-lengths pair trace separation property.

The theorem applies the matrix-pair subdirect-product dichotomy to the pair
algebra generated by the simultaneous one-letter pairs. -/
theorem pairTraceSeparatingAll_of_injective_not_gaugePhaseEquiv
    {d D : ℕ} [NeZero D]
    (A B : MPSTensor d D)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (_hA_norm : ∑ i : Fin d, (A i)ᴴ * A i = 1)
    (_hB_norm : ∑ i : Fin d, (B i)ᴴ * B i = 1)
    (hNot : ¬ GaugePhaseEquiv A B) :
    PairTraceSeparatingAll A B := by
  have hPairSpanTop : PairAllWordsSpanTop A B := by
    exact pairAllWordsSpanTop_of_pairAlgSpan_eq_top A B
      (pairAlgSpan_eq_top_of_injective_not_gaugePhaseEquiv A B hA_inj hB_inj hNot)
  exact pairTraceSeparatingAll_of_pairAllWordsSpanTop A B hPairSpanTop

/-- If two injective blocks have propositionally equal bond dimensions and are not
gauge-phase equivalent after identifying those dimensions, then their simultaneous pair
words are trace separating over all lengths. -/
theorem pairTraceSeparatingAll_of_injective_not_gaugePhaseEquiv_cast_left
    {d D₁ D₂ : ℕ} [NeZero D₁] [NeZero D₂] (h : D₁ = D₂)
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hA_norm : ∑ i : Fin d, (A i)ᴴ * (A i) = 1)
    (hB_norm : ∑ i : Fin d, (B i)ᴴ * (B i) = 1)
    (hNot : ¬ GaugePhaseEquiv (cast (congr_arg (MPSTensor d) h) A) B) :
    PairTraceSeparatingAll A B := by
  subst h
  simpa using pairTraceSeparatingAll_of_injective_not_gaugePhaseEquiv
    A B hA_inj hB_inj hA_norm hB_norm hNot

/-- **Dimension mismatch ⇒ all-length pair trace separation.**

For injective blocks with different bond dimensions, no nonzero pair of test
matrices can annihilate all simultaneous pair words.  This is the unequal-size
branch of the BNT argument that produces a finite common separating length: the
pair algebra equals the full product algebra by the pair-algebra density
theorem for blocks of unequal dimensions, and the all-length pair word span is
dual to the all-lengths trace separation property. -/
theorem pairTraceSeparatingAll_of_injective_dim_ne
    {d D₁ D₂ : ℕ} [NeZero D₁] [NeZero D₂]
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hdim : D₁ ≠ D₂) :
    PairTraceSeparatingAll A B := by
  have hPairSpanTop : PairAllWordsSpanTop A B := by
    exact pairAllWordsSpanTop_of_pairAlgSpan_eq_top A B
      (pairAlgSpan_eq_top_of_injective_dim_ne A B hA_inj hB_inj hdim)
  exact pairTraceSeparatingAll_of_pairAllWordsSpanTop A B hPairSpanTop

/-- Unequal bond dimensions plus a finite period-window of homogeneous pair spans
give one homogeneous pair trace-separating length.

The dimension mismatch supplies all-words pair trace separation.  The
period-window span hypothesis supplies the identity padding needed to convert
that cumulative separation into a single homogeneous length. -/
theorem exists_pairTraceSeparatingAt_of_injective_dim_ne_of_pairWordTupleSpanTop_period_window
    {d D₁ D₂ : ℕ} [NeZero D₁] [NeZero D₂]
    (A : MPSTensor d D₁) (B : MPSTensor d D₂)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hdim : D₁ ≠ D₂)
    {start period : ℕ} (hperiod_pos : 0 < period)
    (hperiod : PairWordTupleSpanTop A B period)
    (hwindow : ∀ r : ℕ, r < period → PairWordTupleSpanTop A B (start + r)) :
    ∃ T : ℕ, PairTraceSeparatingAt A B T := by
  apply exists_pairTraceSeparatingAt_of_pairAllWordsSpanTop_of_identity_padding
  · exact (pairAllWordsSpanTop_iff_pairTraceSeparatingAll A B).2
      (pairTraceSeparatingAll_of_injective_dim_ne A B hA_inj hB_inj hdim)
  · exact pairIdentity_mem_pairWordTupleSpan_eventually_of_pairWordTupleSpanTop_period_window
      A B hperiod_pos hperiod hwindow

/-- Homogeneous pair trace separation from same-dimension BNT non-equivalence
and a homogeneous identity-padding period window.

For injective same-dimension tensors satisfying the left-canonical
normalization hypotheses and not gauge-phase equivalent, the simultaneous pair
words are trace-separating over all finite lengths.  A period-window of full
homogeneous pair spans supplies the identity padding needed to convert that
all-length separation into one homogeneous trace-separating length. -/
theorem exists_pairTraceSeparatingAt_of_not_gaugePhaseEquiv_of_pairWordTupleSpanTop_period_window
    {d D : ℕ} [NeZero D]
    (A B : MPSTensor d D)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hA_norm : ∑ i : Fin d, (A i)ᴴ * A i = 1)
    (hB_norm : ∑ i : Fin d, (B i)ᴴ * B i = 1)
    (hNot : ¬ GaugePhaseEquiv A B)
    {start period : ℕ} (hperiod_pos : 0 < period)
    (hperiod : PairWordTupleSpanTop A B period)
    (hwindow : ∀ r : ℕ, r < period → PairWordTupleSpanTop A B (start + r)) :
    ∃ T : ℕ, PairTraceSeparatingAt A B T := by
  apply exists_pairTraceSeparatingAt_of_pairAllWordsSpanTop_of_identity_padding
  · have hSepAll : PairTraceSeparatingAll A B :=
      pairTraceSeparatingAll_of_injective_not_gaugePhaseEquiv
        A B hA_inj hB_inj hA_norm hB_norm hNot
    exact (pairAllWordsSpanTop_iff_pairTraceSeparatingAll A B).2 hSepAll
  · exact pairIdentity_mem_pairWordTupleSpan_eventually_of_pairWordTupleSpanTop_period_window
      A B hperiod_pos hperiod hwindow

/-! ### Cumulative pair separation and homogeneous padding

BNT injectivity, left-canonical normalization, and non-gauge-equivalence imply
all-length trace separation for the simultaneous pair words:
`PairTraceSeparatingAll A B`. Finite-dimensional stabilization then gives a
cutoff `S` with `PairTraceSeparatingUpTo A B S`.

A homogeneous fixed-length conclusion `PairTraceSeparatingAt A B T` also
requires identity padding: the pair identity `(1, 1)` must lie in appropriate
homogeneous pair-word spans. The source paper (arXiv:1606.00608, lines 317--345)
gets fixed-length span from the Wielandt/Pérez-García--Verstraete--Wolf--Cirac
bound; the identity-padding hypotheses below keep that missing input explicit.

For the unequal-dimension case see
`exists_pairTraceSeparatingAt_of_injective_dim_ne_of_pairWordTupleSpanTop_period_window`. -/

/-- From injectivity, left-canonical normalization, and non-gauge-equivalence of
a same-dimension pair, obtain `PairTraceSeparatingAll` and a finite cutoff `S`
such that `PairTraceSeparatingUpTo A B S`.

The homogeneous fixed-length conclusion additionally requires identity-padding
hypotheses. -/
theorem pairTraceSeparatingAll_and_exists_pairTraceSeparatingUpTo_of_injective_not_gaugePhaseEquiv
    {d D : ℕ} [NeZero D]
    (A B : MPSTensor d D)
    (hA_inj : IsInjective A) (hB_inj : IsInjective B)
    (hA_norm : ∑ i : Fin d, (A i)ᴴ * A i = 1)
    (hB_norm : ∑ i : Fin d, (B i)ᴴ * B i = 1)
    (hNot : ¬ GaugePhaseEquiv A B) :
    PairTraceSeparatingAll A B ∧
    (∃ S : ℕ, PairTraceSeparatingUpTo A B S) := by
  have hSepAll : PairTraceSeparatingAll A B :=
    pairTraceSeparatingAll_of_injective_not_gaugePhaseEquiv
      A B hA_inj hB_inj hA_norm hB_norm hNot
  obtain ⟨S, hSepUpTo⟩ :=
    exists_pairTraceSeparatingUpTo_of_pairTraceSeparatingAll A B hSepAll
  exact ⟨hSepAll, ⟨S, hSepUpTo⟩⟩

/-- **Cumulative-to-homogeneous implication, period-window form.** From
cumulative pair trace separation and a period-window identity-padding
certificate, obtain a homogeneous pair trace-separating length.

`hperiod_pos`, `hperiod_pad`, and `hwindow_pad` together give eventual identity
padding via `pairIdentity_mem_pairWordTupleSpan_eventually_of_period_window`. -/
theorem exists_pairTraceSeparatingAt_of_pairTraceSeparatingUpTo_of_identity_period_window
    {d D₁ D₂ : ℕ} (A : MPSTensor d D₁) (B : MPSTensor d D₂) {S : ℕ}
    (hSepUpTo : PairTraceSeparatingUpTo A B S)
    {start period : ℕ} (hperiod_pos : 0 < period)
    (hperiod_pad :
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B period)))
    (hwindow_pad : ∀ s : ℕ, s < period →
      ((1 : Matrix (Fin D₁) (Fin D₁) ℂ), (1 : Matrix (Fin D₂) (Fin D₂) ℂ)) ∈
        Submodule.span ℂ (Set.range (pairWordTuple A B (start + s)))) :
    ∃ T : ℕ, PairTraceSeparatingAt A B T :=
  exists_pairTraceSeparatingAt_of_pairTraceSeparatingUpTo_of_eventual_identity_padding
    A B hSepUpTo
    (pairIdentity_mem_pairWordTupleSpan_eventually_of_period_window
      A B hperiod_pos hperiod_pad hwindow_pad)

end MPSTensor
