/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.Algebra.MatrixOperatorSpace
import TNLean.Channel.Semigroup.CPClosure
import Mathlib.Algebra.Azumaya.Defs
import Mathlib.Analysis.Normed.Operator.Mul
import Mathlib.Analysis.Normed.Algebra.MatrixExponential

/-!
# Dissipative drift semigroups

This file isolates the explicit semigroup generated by the drift term
`ρ ↦ -κρ - ρκ†` appearing in the GKSL decomposition.

## Main results

* `dissipativeDrift` — the linear drift generator `ρ ↦ -κρ - ρκ†`
* `expSemigroup_dissipativeDrift_apply` —
  `exp(t · dissipativeDrift κ)(ρ) = e^{-tκ} ρ e^{-tκ†}`
* `isCPMap_expSemigroup_dissipativeDrift` — the drift semigroup is completely positive

## References

* [M. Wolf, *Quantum Channels & Operations: Guided Tour*, Section 7.1.2][Wolf2012Quantum]
-/

open scoped Matrix ComplexOrder BigOperators NNReal MatrixOrder TNOperatorSpace
open Matrix TNLean

attribute [local instance 1001]
  ContinuousLinearMap.toNormedAddCommGroup
  ContinuousLinearMap.toNormedSpace
  ContinuousLinearMap.toNormedRing
  ContinuousLinearMap.toNormedAlgebra

noncomputable section

section DissipativeDrift

variable {D : ℕ}

private abbrev Mat (D : ℕ) := Matrix (Fin D) (Fin D) ℂ
private abbrev LM (D : ℕ) := Mat D →ₗ[ℂ] Mat D

/-- The linear drift generator `ρ ↦ -κρ - ρκ†`. -/
abbrev dissipativeDrift (κ : Mat D) : LM D :=
  -(LinearMap.mulLeft ℂ κ) - LinearMap.mulRight ℂ κᴴ

@[simp] theorem dissipativeDrift_apply
    (κ ρ : Mat D) :
    dissipativeDrift κ ρ = -κ * ρ - ρ * κᴴ := by
  simp [dissipativeDrift, LinearMap.mulLeft_apply, LinearMap.mulRight_apply]

private abbrev leftMulAlgHom (D : ℕ) : Mat D →ₐ[ℂ] LM D :=
  Algebra.lmul ℂ (Mat D)

private theorem leftMulAlgHom_apply (A ρ : Mat D) :
    leftMulAlgHom D A ρ = A * ρ := by
  simp [leftMulAlgHom]

private def matExpD (A : Mat D) : Mat D :=
  letI : NormedRing (Mat D) := Matrix.linftyOpNormedRing (n := Fin D) (α := ℂ)
  letI : NormedAlgebra ℂ (Mat D) :=
    Matrix.linftyOpNormedAlgebra (R := ℂ) (n := Fin D) (α := ℂ)
  NormedSpace.exp A

private def clmExpD (T : MatrixCLM (Fin D)) : MatrixCLM (Fin D) :=
  letI : NormedRing (MatrixCLM (Fin D)) := ContinuousLinearMap.toNormedRing
  NormedSpace.exp T

private abbrev rightMulAlgHom (D : ℕ) : (Mat D)ᵐᵒᵖ →ₐ[ℂ] LM D :=
  (AlgHom.mulLeftRight ℂ (Mat D)).comp
    (Algebra.TensorProduct.includeRight (R := ℂ) (A := Mat D) (B := (Mat D)ᵐᵒᵖ))

private theorem rightMulAlgHom_apply (A : (Mat D)ᵐᵒᵖ) (ρ : Mat D) :
    rightMulAlgHom D A ρ = ρ * MulOpposite.unop A := by
  simp [rightMulAlgHom]

private abbrev leftMulCLMAlgHom (D : ℕ) : Mat D →ₐ[ℂ] MatrixCLM (Fin D) :=
  (endEquiv (D := D)).toAlgHom.comp (leftMulAlgHom D)

private abbrev rightMulCLMAlgHom (D : ℕ) : (Mat D)ᵐᵒᵖ →ₐ[ℂ] MatrixCLM (Fin D) :=
  (endEquiv (D := D)).toAlgHom.comp (rightMulAlgHom D)

private theorem leftMulCLM_apply (A ρ : Mat D) :
    leftMulCLMAlgHom D A ρ = A * ρ := by
  change leftMulAlgHom D A ρ = A * ρ
  exact leftMulAlgHom_apply A ρ

private theorem rightMulCLM_apply (A : (Mat D)ᵐᵒᵖ) (ρ : Mat D) :
    rightMulCLMAlgHom D A ρ = ρ * MulOpposite.unop A := by
  change rightMulAlgHom D A ρ = ρ * MulOpposite.unop A
  exact rightMulAlgHom_apply A ρ

private lemma continuous_leftMulCLMAlgHom :
    Continuous (leftMulCLMAlgHom D) := by
  have h_eq : (leftMulCLMAlgHom D : Mat D → MatrixCLM (Fin D)) =
      ContinuousLinearMap.mul ℂ (Mat D) := by
    funext A
    apply ContinuousLinearMap.ext
    intro ρ
    rw [leftMulCLM_apply]
    rfl
  rw [h_eq]
  exact (ContinuousLinearMap.mul ℂ (Mat D)).continuous

private lemma continuous_rightMulCLMAlgHom :
    Continuous (rightMulCLMAlgHom D) := by
  have hunop : Continuous (MulOpposite.unop : (Mat D)ᵐᵒᵖ → Mat D) :=
    MulOpposite.continuous_unop
  have h_eq : (rightMulCLMAlgHom D : (Mat D)ᵐᵒᵖ → MatrixCLM (Fin D)) =
      fun A : (Mat D)ᵐᵒᵖ =>
        (ContinuousLinearMap.mul ℂ (Mat D)).flip (MulOpposite.unop A) := by
    funext A
    apply ContinuousLinearMap.ext
    intro ρ
    rw [rightMulCLM_apply]
    rfl
  rw [h_eq]
  exact (ContinuousLinearMap.mul ℂ (Mat D)).flip.continuous.comp hunop

private theorem mulLeft_eq_leftMulAlgHom (A : Mat D) :
    LinearMap.mulLeft ℂ A = leftMulAlgHom D A := by
  ext ρ i j
  simp

private theorem mulRight_eq_rightMulAlgHom (A : Mat D) :
    LinearMap.mulRight ℂ A = rightMulAlgHom D (MulOpposite.op A) := by
  ext ρ i j
  rw [rightMulAlgHom_apply]
  simp

private theorem endEquiv_mulLeft (A : Mat D) :
    endEquiv (D := D) (LinearMap.mulLeft ℂ A) = leftMulCLMAlgHom D A := by
  simpa [leftMulCLMAlgHom] using
    congrArg (endEquiv (D := D)) (mulLeft_eq_leftMulAlgHom (D := D) A)

private theorem endEquiv_mulRight (A : Mat D) :
    endEquiv (D := D) (LinearMap.mulRight ℂ A) = rightMulCLMAlgHom D (MulOpposite.op A) := by
  simpa [rightMulCLMAlgHom] using
    congrArg (endEquiv (D := D)) (mulRight_eq_rightMulAlgHom (D := D) A)

private theorem left_right_commute (A B : Mat D) :
    Commute (leftMulCLMAlgHom D A) (rightMulCLMAlgHom D (MulOpposite.op B)) := by
  rw [← endEquiv_mulLeft (D := D) A, ← endEquiv_mulRight (D := D) B]
  exact (LinearMap.commute_mulLeft_right (R := ℂ) A B).map (endEquiv (D := D))

private theorem endEquiv_dissipativeDrift
    (κ : Mat D) :
    endEquiv (D := D) (dissipativeDrift κ) =
      leftMulCLMAlgHom D (-κ) + rightMulCLMAlgHom D (MulOpposite.op (-κᴴ)) := by
  calc
    endEquiv (D := D) (dissipativeDrift κ)
        = -(endEquiv (D := D) (LinearMap.mulLeft ℂ κ)) -
          endEquiv (D := D) (LinearMap.mulRight ℂ κᴴ) := by
            simp [dissipativeDrift]
    _ = -leftMulCLMAlgHom D κ - rightMulCLMAlgHom D (MulOpposite.op κᴴ) := by
          rw [endEquiv_mulLeft, endEquiv_mulRight]
    _ = leftMulCLMAlgHom D (-κ) + rightMulCLMAlgHom D (MulOpposite.op (-κᴴ)) := by
          rw [sub_eq_add_neg]
          congr 1
          · exact (map_neg (leftMulCLMAlgHom D) κ).symm
          · rw [← map_neg (rightMulCLMAlgHom D) (MulOpposite.op κᴴ)]
            simp

private theorem exp_leftMulCLM
    (A : Mat D) :
    NormedSpace.exp (leftMulCLMAlgHom D A) =
      leftMulCLMAlgHom D (NormedSpace.exp A) := by
  change clmExpD (leftMulCLMAlgHom D A) =
    leftMulCLMAlgHom D (matExpD A)
  letI : NormedRing (Mat D) := Matrix.linftyOpNormedRing (n := Fin D) (α := ℂ)
  letI : NormedAlgebra ℂ (Mat D) :=
    Matrix.linftyOpNormedAlgebra (R := ℂ) (n := Fin D) (α := ℂ)
  letI : CompleteSpace (Mat D) := FiniteDimensional.complete ℂ (Mat D)
  have h := NormedSpace.map_exp (leftMulCLMAlgHom D) continuous_leftMulCLMAlgHom A
  exact h.symm

private theorem exp_rightMulCLM
    (A : Mat D) :
    NormedSpace.exp (rightMulCLMAlgHom D (MulOpposite.op A)) =
      rightMulCLMAlgHom D (MulOpposite.op (NormedSpace.exp A)) := by
  change clmExpD (rightMulCLMAlgHom D (MulOpposite.op A)) =
    rightMulCLMAlgHom D (MulOpposite.op (matExpD A))
  have h := NormedSpace.map_exp (rightMulCLMAlgHom D) continuous_rightMulCLMAlgHom
    (MulOpposite.op A)
  have hop : NormedSpace.exp (MulOpposite.op A) = MulOpposite.op (matExpD A) := by
    simp [matExpD, NormedSpace.exp_op (𝔸 := Mat D) (x := A)]
  rw [← hop]
  exact h.symm

/-- The dissipative drift semigroup is explicit:
`exp(t · (ρ ↦ -κρ - ρκ†))(ρ) = e^{-tκ} ρ e^{-tκ†}`. -/
theorem expSemigroup_dissipativeDrift_apply
    (κ ρ : Mat D) (t : ℝ) :
    expSemigroup (dissipativeDrift κ) t ρ =
      NormedSpace.exp (-(t : ℂ) • κ) * ρ *
        (NormedSpace.exp (-(t : ℂ) • κ))ᴴ := by
  have hκ :
      expSemigroupCLM (endEquiv (D := D) (dissipativeDrift κ)) t =
        leftMulCLMAlgHom D (NormedSpace.exp (-(t : ℂ) • κ)) *
          rightMulCLMAlgHom D
            (MulOpposite.op (NormedSpace.exp (-(t : ℂ) • κᴴ))) := by
    rw [endEquiv_dissipativeDrift]
    have hsplit :
        (t : ℂ) •
            (leftMulCLMAlgHom D (-κ) +
              rightMulCLMAlgHom D (MulOpposite.op (-κᴴ))) =
          leftMulCLMAlgHom D (-(t : ℂ) • κ) +
            rightMulCLMAlgHom D (MulOpposite.op (-(t : ℂ) • κᴴ)) := by
      refine (smul_add (t : ℂ) (leftMulCLMAlgHom D (-κ))
        (rightMulCLMAlgHom D (MulOpposite.op (-κᴴ)))).trans ?_
      congr 1
      · simpa [smul_neg] using
          (map_smul (leftMulCLMAlgHom D) (t : ℂ) (-κ)).symm
      · simpa [smul_neg] using
          (map_smul (rightMulCLMAlgHom D) (t : ℂ) (MulOpposite.op (-κᴴ))).symm
    have hcomm := left_right_commute (D := D) (-(t : ℂ) • κ) (-(t : ℂ) • κᴴ)
    letI : CompleteSpace (Mat D →L[ℂ] Mat D) :=
      FiniteDimensional.complete ℂ (Mat D →L[ℂ] Mat D)
    have hsum :
        NormedSpace.exp
            (leftMulCLMAlgHom D (-(t : ℂ) • κ) +
              rightMulCLMAlgHom D (MulOpposite.op (-(t : ℂ) • κᴴ))) =
          NormedSpace.exp (leftMulCLMAlgHom D (-(t : ℂ) • κ)) *
            NormedSpace.exp
              (rightMulCLMAlgHom D (MulOpposite.op (-(t : ℂ) • κᴴ))) := by
      change
        clmExpD
            (leftMulCLMAlgHom D (-(t : ℂ) • κ) +
              rightMulCLMAlgHom D (MulOpposite.op (-(t : ℂ) • κᴴ))) =
          clmExpD (leftMulCLMAlgHom D (-(t : ℂ) • κ)) *
            clmExpD
              (rightMulCLMAlgHom D (MulOpposite.op (-(t : ℂ) • κᴴ)))
      exact @NormedSpace.exp_add_of_commute (MatrixCLM (Fin D))
        ContinuousLinearMap.toNormedRing
        inferInstance
        (TNOperatorSpace.instCompleteSpaceMatrixCLM (Fin D))
        (x := leftMulCLMAlgHom D (-(t : ℂ) • κ))
        (y := rightMulCLMAlgHom D (MulOpposite.op (-(t : ℂ) • κᴴ)))
        hcomm
    rw [expSemigroupCLM, hsplit, hsum, exp_leftMulCLM, exp_rightMulCLM]
  change expSemigroupCLM (endEquiv (D := D) (dissipativeDrift κ)) t ρ = _
  rw [hκ]
  have hconj : NormedSpace.exp (-(t : ℂ) • κᴴ) =
      (NormedSpace.exp (-(t : ℂ) • κ))ᴴ := by
    calc
      NormedSpace.exp (-(t : ℂ) • κᴴ) = NormedSpace.exp (((-(t : ℂ)) • κ)ᴴ) := by
        rw [Matrix.conjTranspose_smul]
        simp
      _ = (NormedSpace.exp (-(t : ℂ) • κ))ᴴ := Matrix.exp_conjTranspose (A := (-(t : ℂ)) • κ)
  rw [hconj]
  change
    leftMulCLMAlgHom D (NormedSpace.exp (-(t : ℂ) • κ))
      ((rightMulCLMAlgHom D
        (MulOpposite.op ((NormedSpace.exp (-(t : ℂ) • κ))ᴴ))) ρ) = _
  rw [rightMulCLM_apply, leftMulCLM_apply]
  simp [Matrix.mul_assoc]

/-- The dissipative drift semigroup is completely positive, with a single Kraus operator
`e^{-tκ}`. -/
theorem isCPMap_expSemigroup_dissipativeDrift
    (κ : Mat D) (t : ℝ) :
    IsCPMap (expSemigroup (dissipativeDrift κ) t) := by
  refine ⟨1, fun _ => NormedSpace.exp (-(t : ℂ) • κ), ?_⟩
  intro ρ
  simp [expSemigroup_dissipativeDrift_apply, Matrix.mul_assoc]

end DissipativeDrift

end -- noncomputable section
