/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.Algebra.MatrixOperatorSpace
import TNLean.Channel.Semigroup.CPClosure
import Mathlib.Analysis.Normed.Operator.Mul
import Mathlib.Analysis.Normed.Algebra.MatrixExponential

/-!
# Dissipative drift semigroups

This file isolates the explicit semigroup generated by the drift term
`ρ ↦ -κρ - ρκ†` appearing in the GKSL decomposition.

## Main results

* `dissipativeDrift` — the linear drift generator `ρ ↦ -κρ - ρκ†`
* `expSemigroup_dissipativeDrift_apply` —
  `exp(t · dissipativeDrift κ)(ρ) = e^{-tκ} ρ e^{-tκ†}`
* `isCPMap_expSemigroup_dissipativeDrift` — the drift semigroup is completely positive

## References

* [M. Wolf, *Quantum Channels & Operations: Guided Tour*, Section 7.1.2][Wolf2012QChannels]
-/

open scoped Matrix ComplexOrder BigOperators NNReal MatrixOrder TNOperatorSpace
open Matrix TNLean

noncomputable section

section DissipativeDrift

variable {D : ℕ}

private abbrev Mat (D : ℕ) := Matrix (Fin D) (Fin D) ℂ
private abbrev LM (D : ℕ) := Mat D →ₗ[ℂ] Mat D

private abbrev endEquivD (D : ℕ) : LM D ≃ₐ[ℂ] MatrixCLM (Fin D) :=
  matrixEndEquiv (Fin D)

/-- The linear drift generator `ρ ↦ -κρ - ρκ†`. -/
abbrev dissipativeDrift (κ : Mat D) : LM D :=
  -(LinearMap.mulLeft ℂ κ) - LinearMap.mulRight ℂ κᴴ

@[simp] theorem dissipativeDrift_apply
    (κ ρ : Mat D) :
    dissipativeDrift κ ρ = -κ * ρ - ρ * κᴴ := by
  simp [dissipativeDrift, LinearMap.mulLeft_apply, LinearMap.mulRight_apply]

private abbrev leftMulAlgHom (D : ℕ) : Mat D →ₐ[ℂ] LM D :=
  Algebra.lmul ℂ (Mat D)

private theorem leftMulAlgHom_apply (A ρ : Mat D) :
    leftMulAlgHom D A ρ = A * ρ := by
  simp [leftMulAlgHom]

private theorem mem_exp_ball {A : Type*}
    [NormedRing A] [NormedAlgebra ℂ A] [CompleteSpace A] (x : A) :
    x ∈ Metric.eball (0 : A) (NormedSpace.expSeries ℂ A).radius := by
  rw [NormedSpace.expSeries_radius_eq_top]
  exact edist_lt_top _ _

private def rightMulAlgHom (D : ℕ) : (Mat D)ᵐᵒᵖ →ₐ[ℂ] LM D where
  toFun := fun B => LinearMap.mulRight ℂ (MulOpposite.unop B)
  map_zero' := by
    ext ρ i j
    simp
  map_add' A B := by
    ext ρ i j
    simp [Matrix.mul_add]
  map_one' := by
    ext ρ i j
    simp
  map_mul' A B := by
    ext ρ i j
    simp [mul_assoc]
  commutes' c := by
    ext ρ i j
    rw [MulOpposite.algebraMap_apply]
    simp [LinearMap.mulRight_apply, Algebra.algebraMap_eq_smul_one]

private theorem rightMulAlgHom_apply (A : (Mat D)ᵐᵒᵖ) (ρ : Mat D) :
    rightMulAlgHom D A ρ = ρ * MulOpposite.unop A := by
  rfl

private abbrev leftMulCLMAlgHom (D : ℕ) : Mat D →ₐ[ℂ] MatrixCLM (Fin D) :=
  (endEquivD D).toAlgHom.comp (leftMulAlgHom D)

private abbrev rightMulCLMAlgHom (D : ℕ) : (Mat D)ᵐᵒᵖ →ₐ[ℂ] MatrixCLM (Fin D) :=
  (endEquivD D).toAlgHom.comp (rightMulAlgHom D)

private lemma continuous_leftMulCLMAlgHom :
    Continuous (leftMulCLMAlgHom D) :=
  (leftMulCLMAlgHom D).toLinearMap.continuous_of_finiteDimensional

private lemma continuous_rightMulCLMAlgHom :
    Continuous (rightMulCLMAlgHom D) :=
  (rightMulCLMAlgHom D).toLinearMap.continuous_of_finiteDimensional

private theorem leftMulCLM_apply (A ρ : Mat D) :
    leftMulCLMAlgHom D A ρ = A * ρ := by
  change leftMulAlgHom D A ρ = A * ρ
  exact leftMulAlgHom_apply A ρ

private theorem rightMulCLM_apply (A : (Mat D)ᵐᵒᵖ) (ρ : Mat D) :
    rightMulCLMAlgHom D A ρ = ρ * MulOpposite.unop A := by
  change rightMulAlgHom D A ρ = ρ * MulOpposite.unop A
  exact rightMulAlgHom_apply A ρ

private theorem left_right_commute (A B : Mat D) :
    Commute (leftMulCLMAlgHom D A) (rightMulCLMAlgHom D (MulOpposite.op B)) := by
  ext ρ i j
  change (A * (ρ * B)) i j = ((A * ρ) * B) i j
  rw [Matrix.mul_assoc]

private theorem mulLeft_eq_leftMulAlgHom (A : Mat D) :
    LinearMap.mulLeft ℂ A = leftMulAlgHom D A := by
  ext ρ i j
  simp

private theorem mulRight_eq_rightMulAlgHom (A : Mat D) :
    LinearMap.mulRight ℂ A = rightMulAlgHom D (MulOpposite.op A) := by
  ext ρ i j
  simp [rightMulAlgHom_apply]

private theorem endEquiv_mulLeft (A : Mat D) :
    endEquivD D (LinearMap.mulLeft ℂ A) = leftMulCLMAlgHom D A := by
  simpa [leftMulCLMAlgHom] using congrArg (endEquivD D) (mulLeft_eq_leftMulAlgHom (D := D) A)

private theorem endEquiv_mulRight (A : Mat D) :
    endEquivD D (LinearMap.mulRight ℂ A) = rightMulCLMAlgHom D (MulOpposite.op A) := by
  simpa [rightMulCLMAlgHom] using congrArg (endEquivD D) (mulRight_eq_rightMulAlgHom (D := D) A)

private theorem endEquiv_dissipativeDrift
    (κ : Mat D) :
    endEquivD D (dissipativeDrift κ) =
      leftMulCLMAlgHom D (-κ) + rightMulCLMAlgHom D (MulOpposite.op (-κᴴ)) := by
  calc
    endEquivD D (dissipativeDrift κ)
        = -(endEquivD D (LinearMap.mulLeft ℂ κ)) - endEquivD D (LinearMap.mulRight ℂ κᴴ) := by
            simp [dissipativeDrift]
    _ = -leftMulCLMAlgHom D κ - rightMulCLMAlgHom D (MulOpposite.op κᴴ) := by
          rw [endEquiv_mulLeft, endEquiv_mulRight]
    _ = leftMulCLMAlgHom D (-κ) + rightMulCLMAlgHom D (MulOpposite.op (-κᴴ)) := by
          simp [sub_eq_add_neg]

private theorem exp_leftMulCLM
    (A : Mat D) :
    NormedSpace.exp (leftMulCLMAlgHom D A) =
      leftMulCLMAlgHom D (NormedSpace.exp A) := by
  have h := NormedSpace.map_exp_of_mem_ball (leftMulCLMAlgHom D)
    continuous_leftMulCLMAlgHom A (mem_exp_ball _)
  simpa using h.symm

private theorem exp_rightMulCLM
    (A : Mat D) :
    NormedSpace.exp (rightMulCLMAlgHom D (MulOpposite.op A)) =
      rightMulCLMAlgHom D (MulOpposite.op (NormedSpace.exp A)) := by
  have h := NormedSpace.map_exp_of_mem_ball (rightMulCLMAlgHom D)
    continuous_rightMulCLMAlgHom (MulOpposite.op A) (mem_exp_ball _)
  simpa [NormedSpace.exp_op] using h.symm

set_option synthInstance.maxHeartbeats 200000 in
-- `exp_add_of_commute` on CLMs triggers deep completeness search under Lean 4.29.
/-- The dissipative drift semigroup is explicit:
`exp(t · (ρ ↦ -κρ - ρκ†))(ρ) = e^{-tκ} ρ e^{-tκ†}`. -/
theorem expSemigroup_dissipativeDrift_apply
    (κ ρ : Mat D) (t : ℝ) :
    expSemigroup (dissipativeDrift κ) t ρ =
      NormedSpace.exp (-(t : ℂ) • κ) * ρ *
        (NormedSpace.exp (-(t : ℂ) • κ))ᴴ := by
  have hκ :
      expSemigroupCLM (endEquivD D (dissipativeDrift κ)) t =
        leftMulCLMAlgHom D (NormedSpace.exp (-(t : ℂ) • κ)) *
          rightMulCLMAlgHom D
            (MulOpposite.op (NormedSpace.exp (-(t : ℂ) • κᴴ))) := by
    rw [endEquiv_dissipativeDrift]
    have hsplit :
        (t : ℂ) •
            (leftMulCLMAlgHom D (-κ) +
              rightMulCLMAlgHom D (MulOpposite.op (-κᴴ))) =
          leftMulCLMAlgHom D (-(t : ℂ) • κ) +
            rightMulCLMAlgHom D (MulOpposite.op (-(t : ℂ) • κᴴ)) := by
      rw [smul_add]
      congr 1
      · simpa [smul_neg] using
          (map_smul (leftMulCLMAlgHom D) (t : ℂ) (-κ)).symm
      · simpa [smul_neg] using
          (map_smul (rightMulCLMAlgHom D) (t : ℂ) (MulOpposite.op (-κᴴ))).symm
    have hcomm := left_right_commute (D := D) (-(t : ℂ) • κ) (-(t : ℂ) • κᴴ)
    letI : CompleteSpace (Mat D →L[ℂ] Mat D) :=
      FiniteDimensional.complete ℂ (Mat D →L[ℂ] Mat D)
    have hsum :
        NormedSpace.exp
            (leftMulCLMAlgHom D (-(t : ℂ) • κ) +
              rightMulCLMAlgHom D (MulOpposite.op (-(t : ℂ) • κᴴ))) =
          NormedSpace.exp (leftMulCLMAlgHom D (-(t : ℂ) • κ)) *
            NormedSpace.exp
              (rightMulCLMAlgHom D (MulOpposite.op (-(t : ℂ) • κᴴ))) := by
      simpa using
        (NormedSpace.exp_add_of_commute
          (x := leftMulCLMAlgHom D (-(t : ℂ) • κ))
          (y := rightMulCLMAlgHom D (MulOpposite.op (-(t : ℂ) • κᴴ)))
          hcomm)
    rw [expSemigroupCLM, hsplit, hsum, exp_leftMulCLM, exp_rightMulCLM]
  change expSemigroupCLM (endEquivD D (dissipativeDrift κ)) t ρ = _
  rw [hκ]
  have hconj : NormedSpace.exp (-(t : ℂ) • κᴴ) =
      (NormedSpace.exp (-(t : ℂ) • κ))ᴴ := by
    calc
      NormedSpace.exp (-(t : ℂ) • κᴴ) = NormedSpace.exp (((-(t : ℂ)) • κ)ᴴ) := by
        rw [Matrix.conjTranspose_smul]
        simp
      _ = (NormedSpace.exp (-(t : ℂ) • κ))ᴴ := Matrix.exp_conjTranspose (A := (-(t : ℂ)) • κ)
  rw [hconj]
  change
    leftMulCLMAlgHom D (NormedSpace.exp (-(t : ℂ) • κ))
      ((rightMulCLMAlgHom D
        (MulOpposite.op ((NormedSpace.exp (-(t : ℂ) • κ))ᴴ))) ρ) = _
  rw [rightMulCLM_apply, leftMulCLM_apply]
  simp [Matrix.mul_assoc]

/-- The dissipative drift semigroup is completely positive, with a single Kraus operator
`e^{-tκ}`. -/
theorem isCPMap_expSemigroup_dissipativeDrift
    (κ : Mat D) (t : ℝ) :
    IsCPMap (expSemigroup (dissipativeDrift κ) t) := by
  refine ⟨1, fun _ => NormedSpace.exp (-(t : ℂ) • κ), ?_⟩
  intro ρ
  simp [expSemigroup_dissipativeDrift_apply, Matrix.mul_assoc]

end DissipativeDrift

end -- noncomputable section
