/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.Channel.Semigroup.Basic
import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Topology.Algebra.Module.StrongTopology

/-!
# Kernel / fixed-point bridges for semigroup generators

This file packages witness-based notions for the mixing theory of quantum
semigroups and proves the basic bridge between the generator kernel and fixed
points of the exponential semigroup.

## Main definitions

* `HasFaithfulStationaryState`:
  the generator kernel contains a positive-definite density matrix.
* `HasSimpleKernel`:
  a positive-definite matrix spans the whole kernel.
* `HasSimpleFaithfulKernel`:
  the kernel is one-dimensional and generated by a faithful density matrix.
* `RelaxesTo`, `IsRelaxingQDS`:
  witness-based relaxation predicates for semigroup mixing.

## Main results

* `generator_apply_eq_zero_iff_expSemigroup_fixed_nonneg`:
  `L X = 0` iff `expSemigroup L t X = X` for all `t ≥ 0`.
* `generator_apply_eq_zero_iff_fixed_nonneg`:
  the same bridge for any semigroup identified with `expSemigroup`.

These statements are the semigroup-side kernel/fixed-point bridges needed for
Wolf Chapter 7.
-/

open scoped Matrix ComplexOrder BigOperators NNReal TNOperatorSpace
open Matrix Finset NormedSpace

noncomputable section

variable {D : ℕ}

local notation "Mat" => Matrix (Fin D) (Fin D) ℂ

/-- `L` has a faithful stationary state if its kernel contains a positive-definite
trace-one matrix. -/
def HasFaithfulStationaryState (L : Mat →ₗ[ℂ] Mat) : Prop :=
  ∃ ρ : Mat, ρ ∈ densityMatrices D ∧ ρ.PosDef ∧ L ρ = 0

/-- `ρ` spans the kernel of `L` and is positive definite. -/
structure HasSimpleKernel (L : Mat →ₗ[ℂ] Mat) (ρ : Mat) : Prop where
  /-- `ρ` lies in the kernel. -/
  kernel : L ρ = 0
  /-- `ρ` is faithful. -/
  posDef : ρ.PosDef
  /-- Every kernel element is a scalar multiple of `ρ`. -/
  unique : ∀ X : Mat, L X = 0 → ∃ c : ℂ, X = c • ρ

/-- `L` has a simple faithful kernel if some positive-definite density matrix
spans the whole kernel. -/
def HasSimpleFaithfulKernel (L : Mat →ₗ[ℂ] Mat) : Prop :=
  ∃ ρ : Mat, ρ ∈ densityMatrices D ∧ HasSimpleKernel L ρ

/-- `T` relaxes to `ρ∞` if every density matrix converges to `ρ∞` as
`t → +∞`, and `ρ∞` is faithful. -/
def RelaxesTo (T : ℝ → Mat →ₗ[ℂ] Mat) (ρInf : Mat) : Prop :=
  ρInf ∈ densityMatrices D ∧ ρInf.PosDef ∧
    ∀ ρ : Mat, ρ ∈ densityMatrices D →
      Filter.Tendsto (fun t : ℝ => T t ρ) Filter.atTop (nhds ρInf)

/-- A semigroup is relaxing if it relaxes to some faithful density matrix. -/
def IsRelaxingQDS (T : ℝ → Mat →ₗ[ℂ] Mat) : Prop :=
  ∃ ρInf : Mat, RelaxesTo (D := D) T ρInf

/-- If `L X = 0`, then `X` is fixed by the exponential semigroup at every
nonnegative time. -/
theorem expSemigroup_apply_eq_self_of_generator_apply_eq_zero
    (L : Mat →ₗ[ℂ] Mat) {X : Mat} (hX : L X = 0) :
    ∀ t : ℝ, 0 ≤ t → expSemigroup L t X = X := by
  intro t _ht
  have hdiff : Differentiable ℝ (fun u : ℝ => expSemigroup L u X) := by
    intro u
    exact (hasDerivAt_expSemigroup_apply (L := L) X u).differentiableAt
  have hderiv : ∀ u : ℝ, deriv (fun s : ℝ => expSemigroup L s X) u = 0 := by
    intro u
    simpa [hX] using (hasDerivAt_expSemigroup_apply (L := L) X u).deriv
  have hconst := is_const_of_deriv_eq_zero hdiff hderiv 0 t
  simpa [expSemigroup_zero] using hconst.symm

/-- If `X` is fixed by `exp(tL)` for every `t ≥ 0`, then `L X = 0`. -/
theorem generator_apply_eq_zero_of_expSemigroup_apply_eq_self
    (L : Mat →ₗ[ℂ] Mat) {X : Mat}
    (hX : ∀ t : ℝ, 0 ≤ t → expSemigroup L t X = X) :
    L X = 0 := by
  have hd₁ :
      HasDerivWithinAt (fun u : ℝ => expSemigroup L u X) (L X) (Set.Ici 0) 0 := by
    simpa [expSemigroup_zero] using
      (hasDerivAt_expSemigroup_apply (L := L) X 0).hasDerivWithinAt
  have hd₂' : HasDerivWithinAt (fun _ : ℝ => X) 0 (Set.Ici 0) 0 :=
    (hasDerivAt_const 0 X).hasDerivWithinAt
  have hd₂ : HasDerivWithinAt (fun u : ℝ => expSemigroup L u X) 0 (Set.Ici 0) 0 := by
    exact hd₂'.congr (fun u hu => hX u hu) (by simp [expSemigroup_zero])
  exact (uniqueDiffWithinAt_Ici 0).eq_deriv _ hd₁ hd₂

/-- Kernel elements of `L` are exactly the matrices fixed by `exp(tL)` for every
nonnegative time. -/
theorem generator_apply_eq_zero_iff_expSemigroup_fixed_nonneg
    (L : Mat →ₗ[ℂ] Mat) (X : Mat) :
    L X = 0 ↔ ∀ t : ℝ, 0 ≤ t → expSemigroup L t X = X := by
  constructor
  · exact expSemigroup_apply_eq_self_of_generator_apply_eq_zero L
  · exact generator_apply_eq_zero_of_expSemigroup_apply_eq_self L

/-- Kernel elements of `L` are exactly the matrices fixed by a semigroup family
`T` identified with `expSemigroup L` on nonnegative times. -/
theorem generator_apply_eq_zero_iff_fixed_nonneg
    (L : Mat →ₗ[ℂ] Mat)
    (T : ℝ → Mat →ₗ[ℂ] Mat)
    (hexp : ∀ t : ℝ, 0 ≤ t → T t = expSemigroup L t)
    (X : Mat) :
    L X = 0 ↔ ∀ t : ℝ, 0 ≤ t → T t X = X := by
  constructor
  · intro hX t ht
    rw [hexp t ht]
    exact (generator_apply_eq_zero_iff_expSemigroup_fixed_nonneg (L := L) X).1 hX t ht
  · intro hX
    exact (generator_apply_eq_zero_iff_expSemigroup_fixed_nonneg (L := L) X).2 <|
      fun t ht => by
        rw [← hexp t ht]
        exact hX t ht

/-- A simple faithful kernel yields a faithful stationary state. -/
theorem HasSimpleFaithfulKernel.hasFaithfulStationaryState
    {L : Mat →ₗ[ℂ] Mat} (hL : HasSimpleFaithfulKernel (D := D) L) :
    HasFaithfulStationaryState (D := D) L := by
  rcases hL with ⟨ρ, hρ_mem, hρ_simple⟩
  exact ⟨ρ, hρ_mem, hρ_simple.posDef, hρ_simple.kernel⟩

/-- For a simple kernel witness, the kernel is exactly the span of that witness. -/
theorem HasSimpleKernel.generator_apply_eq_zero_iff
    {L : Mat →ₗ[ℂ] Mat} {ρ X : Mat} (hρ : HasSimpleKernel L ρ) :
    L X = 0 ↔ ∃ c : ℂ, X = c • ρ := by
  constructor
  · exact hρ.unique X
  · rintro ⟨c, rfl⟩
    simp [hρ.kernel]

/-- For a simple kernel witness, fixed points of the exponential semigroup are
exactly the scalar multiples of the witness. -/
theorem HasSimpleKernel.expSemigroup_fixed_nonneg_iff
    {L : Mat →ₗ[ℂ] Mat} {ρ X : Mat} (hρ : HasSimpleKernel L ρ) :
    (∀ t : ℝ, 0 ≤ t → expSemigroup L t X = X) ↔ ∃ c : ℂ, X = c • ρ := by
  rw [← generator_apply_eq_zero_iff_expSemigroup_fixed_nonneg (L := L) X]
  exact hρ.generator_apply_eq_zero_iff

end
