/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.SpinCover.Basic
import TNLean.Analysis.Entropy
import TNLean.Analysis.SchattenNorm
import TNLean.Channel.Semigroup.Kernel
import TNLean.Channel.Semigroup.LindbladForm.Basic

/-!
# Dissipation generated by two Pauli matrices

This file supplies the finite-dimensional algebraic part of the two-of-three
Pauli dissipation problem. For distinct `a b : Fin 3` and positive rates
`γa γb`, the generator is

`L(X) = γa D[σₐ](X) + γb D[σᵦ](X)`.

Its kernel consists exactly of scalar matrices, so the maximally mixed qubit
state spans the kernel and is fixed by the exponential semigroup.

The final theorem is deliberately assumption-driven. Its `hDecay` hypothesis
is the CMLSI/relative-entropy-decay input which is not yet available in TNLean,
and `hPinsker` is the quantum Pinsker input. The distance itself is the matrix
Schatten one-norm, rather than TNLean's ambient operator norm.

## References

- `Notes/OpenProblemsQC/problems/q3_two_of_three_pauli_dissipation.tex`
  gives the complete mathematical argument and fixes the normalization of the
  generator and the logarithmic time bound.
- Li Gao and Cambyse Rouzé, *Complete entropic inequalities for quantum Markov
  chains*, arXiv:2102.04146, Theorems 1.1 and 3.3, gives the CMLSI estimate used
  as an explicit hypothesis below.
-/

open scoped Matrix ComplexOrder BigOperators
noncomputable section

namespace PauliDissipation

local notation "QubitMat" => Matrix (Fin 2) (Fin 2) ℂ

/-- Pauli matrices are Hermitian. -/
@[simp] theorem pauli_conjTranspose (k : Fin 3) :
    (SpinCover.pauli k)ᴴ = SpinCover.pauli k := by
  fin_cases k <;> ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [SpinCover.pauli, Matrix.conjTranspose_apply]

/-- Every Pauli matrix squares to the identity. -/
@[simp] theorem pauli_sq (k : Fin 3) :
    SpinCover.pauli k * SpinCover.pauli k = (1 : QubitMat) := by
  fin_cases k <;> ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [SpinCover.pauli, Matrix.mul_apply, Fin.sum_univ_two]

/-- Conjugation by a Pauli matrix fixes itself and negates either other Pauli. -/
theorem pauli_mul_pauli_mul (a k : Fin 3) :
    SpinCover.pauli a * SpinCover.pauli k * SpinCover.pauli a =
      if a = k then SpinCover.pauli k else -SpinCover.pauli k := by
  fin_cases a <;> fin_cases k <;> ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [SpinCover.pauli, Matrix.mul_apply, Fin.sum_univ_two]

/-- The dissipator of a Pauli operator is conjugation minus the identity map. -/
theorem dissipator_pauli (a : Fin 3) (X : QubitMat) :
    dissipator (SpinCover.pauli a) X =
      SpinCover.pauli a * X * SpinCover.pauli a - X := by
  simp [dissipator, pauli_conjTranspose, pauli_sq]
  module

/-- The two-Pauli dissipative generator with real rates. -/
def twoPauliGenerator (a b : Fin 3) (γa γb : ℝ) :
    QubitMat →ₗ[ℂ] QubitMat where
  toFun X := (γa : ℂ) • dissipator (SpinCover.pauli a) X +
    (γb : ℂ) • dissipator (SpinCover.pauli b) X
  map_add' X Y := by simp [dissipator_add, add_add_add_comm]
  map_smul' c X := by
    simp only [RingHom.id_apply, dissipator_smul, smul_add, smul_smul]
    simp [mul_comm c]

/-- The two-Pauli generator evaluates as the weighted sum of its two dissipators. -/
@[simp] theorem twoPauliGenerator_apply (a b : Fin 3) (γa γb : ℝ) (X : QubitMat) :
    twoPauliGenerator a b γa γb X =
      (γa : ℂ) • dissipator (SpinCover.pauli a) X +
      (γb : ℂ) • dissipator (SpinCover.pauli b) X := rfl

/-- The two-Pauli generator is unital. -/
@[simp] theorem twoPauliGenerator_one (a b : Fin 3) (γa γb : ℝ) :
    twoPauliGenerator a b γa γb (1 : QubitMat) = 0 := by
  simp [twoPauliGenerator, dissipator_pauli]

/-- Exact diagonal action on the three Pauli basis vectors.

This is equation `eq:q3-pauli-spectrum` in
`Notes/OpenProblemsQC/problems/q3_two_of_three_pauli_dissipation.tex`. -/
theorem twoPauliGenerator_pauli (a b k : Fin 3) (γa γb : ℝ) :
    twoPauliGenerator a b γa γb (SpinCover.pauli k) =
      ((-2 * ((if a = k then 0 else γa) + (if b = k then 0 else γb)) : ℝ) : ℂ) •
        SpinCover.pauli k := by
  simp only [twoPauliGenerator_apply, dissipator_pauli, pauli_mul_pauli_mul]
  split_ifs <;> subst_vars <;> simp <;> module

/-- For distinct selected directions, the `a`-Pauli eigenvalue is `-2 γb`. -/
theorem twoPauliGenerator_pauli_a {a b : Fin 3} (hab : a ≠ b) (γa γb : ℝ) :
    twoPauliGenerator a b γa γb (SpinCover.pauli a) =
      ((-2 * γb : ℝ) : ℂ) • SpinCover.pauli a := by
  simpa [hab, hab.symm] using twoPauliGenerator_pauli a b a γa γb

/-- For distinct selected directions, the `b`-Pauli eigenvalue is `-2 γa`. -/
theorem twoPauliGenerator_pauli_b {a b : Fin 3} (hab : a ≠ b) (γa γb : ℝ) :
    twoPauliGenerator a b γa γb (SpinCover.pauli b) =
      ((-2 * γa : ℝ) : ℂ) • SpinCover.pauli b := by
  simpa [hab, hab.symm] using twoPauliGenerator_pauli a b b γa γb

/-- Any unselected Pauli direction has eigenvalue `-2 (γa + γb)`. -/
theorem twoPauliGenerator_pauli_remaining {a b k : Fin 3}
    (hka : k ≠ a) (hkb : k ≠ b) (γa γb : ℝ) :
    twoPauliGenerator a b γa γb (SpinCover.pauli k) =
      ((-2 * (γa + γb) : ℝ) : ℂ) • SpinCover.pauli k := by
  simpa [hka.symm, hkb.symm] using twoPauliGenerator_pauli a b k γa γb

/-- A Pauli dissipator is symmetric for the Hilbert--Schmidt trace pairing. -/
theorem dissipator_pauli_trace_symmetry (a : Fin 3) (X Y : QubitMat) :
    Matrix.trace (Xᴴ * dissipator (SpinCover.pauli a) Y) =
      Matrix.trace ((dissipator (SpinCover.pauli a) X)ᴴ * Y) := by
  rw [dissipator_pauli, dissipator_pauli]
  calc
    Matrix.trace (Xᴴ * (SpinCover.pauli a * Y * SpinCover.pauli a - Y)) =
        Matrix.trace (Xᴴ * SpinCover.pauli a * Y * SpinCover.pauli a) -
          Matrix.trace (Xᴴ * Y) := by
            simp [Matrix.mul_sub, Matrix.trace_sub, mul_assoc]
    _ = Matrix.trace (SpinCover.pauli a * Xᴴ * SpinCover.pauli a * Y) -
          Matrix.trace (Xᴴ * Y) := by
            rw [Matrix.trace_mul_cycle (Xᴴ * SpinCover.pauli a) Y
              (SpinCover.pauli a)]
            simp only [mul_assoc]
    _ = Matrix.trace ((SpinCover.pauli a * X * SpinCover.pauli a - X)ᴴ * Y) := by
          simp [Matrix.conjTranspose_sub, pauli_conjTranspose, Matrix.trace_sub,
            Matrix.sub_mul, mul_assoc]

/-- The two-Pauli generator with real rates is Hilbert--Schmidt (equivalently,
GNS for the maximally mixed state) symmetric.  The statement deliberately shows
both the matrix trace and conjugate transpose used by that pairing. -/
theorem twoPauliGenerator_trace_conjTranspose_symmetry
    (a b : Fin 3) (γa γb : ℝ) (X Y : QubitMat) :
    Matrix.trace (Xᴴ * twoPauliGenerator a b γa γb Y) =
      Matrix.trace ((twoPauliGenerator a b γa γb X)ᴴ * Y) := by
  simp only [twoPauliGenerator_apply, Matrix.mul_add, Matrix.trace_add,
    Matrix.mul_smul, Matrix.trace_smul, Matrix.conjTranspose_add,
    Matrix.conjTranspose_smul, Matrix.add_mul, Matrix.smul_mul]
  rw [dissipator_pauli_trace_symmetry, dissipator_pauli_trace_symmetry]
  simp

/-- A linear combination of Pauli matrices vanishes only when all coefficients
vanish. This trace-pairing form is useful independently of the generator. -/
theorem pauli_sum_eq_zero_iff (c : Fin 3 → ℂ) :
    (∑ k : Fin 3, c k • SpinCover.pauli k) = 0 ↔ ∀ k, c k = 0 := by
  constructor
  · intro h k
    have hk := congrArg (fun X : QubitMat => (SpinCover.pauli k * X).trace) h
    simp only [Matrix.mul_sum, Matrix.mul_smul, Matrix.trace_sum, Matrix.trace_smul,
      SpinCover.pauli_mul_pauli_trace, Matrix.mul_zero, Matrix.trace_zero] at hk
    simpa using hk
  · intro h
    simp [h]

/-- For distinct Pauli directions and strictly positive rates, the kernel is
exactly the scalar identity matrices. -/
theorem twoPauliGenerator_eq_zero_iff {a b : Fin 3} (hab : a ≠ b)
    {γa γb : ℝ} (hγa : 0 < γa) (hγb : 0 < γb) (X : QubitMat) :
    twoPauliGenerator a b γa γb X = 0 ↔
      ∃ c : ℂ, X = c • (1 : QubitMat) := by
  constructor
  · intro hX
    have hLX : twoPauliGenerator a b γa γb
        ((X.trace / 2) • (1 : QubitMat) +
          ∑ k : Fin 3, ((SpinCover.pauli k * X).trace / 2) • SpinCover.pauli k) = 0 := by
      rwa [← SpinCover.pauli_expansion X]
    rw [SpinCover.pauli_expansion X]
    refine ⟨X.trace / 2, ?_⟩
    simp only [map_add, map_smul, twoPauliGenerator_one, smul_zero, zero_add,
      map_sum, twoPauliGenerator_pauli] at hLX
    simp only [smul_smul] at hLX
    rw [pauli_sum_eq_zero_iff] at hLX
    have hcoeff : ∀ k : Fin 3, ((SpinCover.pauli k * X).trace / 2) = 0 := by
      intro k
      have hk := hLX k
      have hrate : (if a = k then 0 else γa) + (if b = k then 0 else γb) ≠ 0 := by
        by_cases hak : a = k
        · have hbk : b ≠ k := by simpa [hak] using hab.symm
          simp [hak, hbk, ne_of_gt hγb]
        · by_cases hbk : b = k
          · simp [hak, hbk, ne_of_gt hγa]
          · simp [hak, hbk, ne_of_gt (add_pos hγa hγb)]
      have heigenR : (-2 : ℝ) * ((if a = k then 0 else γa) +
          (if b = k then 0 else γb)) ≠ 0 :=
        mul_ne_zero (by norm_num) hrate
      have heigen : (((-2 : ℝ) * ((if a = k then 0 else γa) +
          (if b = k then 0 else γb)) : ℝ) : ℂ) ≠ 0 :=
        Complex.ofReal_ne_zero.mpr heigenR
      exact (mul_eq_zero.mp hk).resolve_right heigen
    simp [hcoeff]
  · rintro ⟨c, rfl⟩
    rw [map_smul, twoPauliGenerator_one, smul_zero]

/-- The maximally mixed qubit state. -/
def maximallyMixed : QubitMat := (1 / 2 : ℂ) • (1 : QubitMat)

/-- The maximally mixed qubit state lies in the kernel of every two-Pauli generator. -/
@[simp] theorem twoPauliGenerator_maximallyMixed (a b : Fin 3) (γa γb : ℝ) :
    twoPauliGenerator a b γa γb maximallyMixed = 0 := by
  rw [maximallyMixed, map_smul, twoPauliGenerator_one, smul_zero]

/-- The maximally mixed qubit state is positive definite. -/
theorem maximallyMixed_posDef : maximallyMixed.PosDef := by
  exact Matrix.PosDef.one.smul (by norm_num [maximallyMixed])

/-- The maximally mixed state is a density matrix. -/
theorem maximallyMixed_mem_densityMatrices : maximallyMixed ∈ densityMatrices 2 := by
  constructor
  · exact maximallyMixed_posDef.posSemidef
  · simp [maximallyMixed, Matrix.trace_smul, Matrix.trace_one]

/-- The maximally mixed state realizes the one-dimensional kernel in the form
used by the semigroup theory. -/
theorem twoPauliGenerator_hasSimpleKernel {a b : Fin 3} (hab : a ≠ b)
    {γa γb : ℝ} (hγa : 0 < γa) (hγb : 0 < γb) :
    HasSimpleKernel (twoPauliGenerator a b γa γb) maximallyMixed where
  kernel := twoPauliGenerator_maximallyMixed a b γa γb
  posDef := maximallyMixed_posDef
  unique X hX := by
    rcases (twoPauliGenerator_eq_zero_iff hab hγa hγb X).1 hX with ⟨c, rfl⟩
    refine ⟨2 * c, ?_⟩
    rw [maximallyMixed, smul_smul]
    congr 1
    ring

/-- The generator has a simple faithful density-matrix kernel. -/
theorem twoPauliGenerator_hasSimpleFaithfulKernel {a b : Fin 3} (hab : a ≠ b)
    {γa γb : ℝ} (hγa : 0 < γa) (hγb : 0 < γb) :
    HasSimpleFaithfulKernel (twoPauliGenerator a b γa γb) :=
  ⟨maximallyMixed, maximallyMixed_mem_densityMatrices,
    twoPauliGenerator_hasSimpleKernel hab hγa hγb⟩

/-- The exponential-semigroup fixed points are exactly the scalar matrices. -/
theorem expSemigroup_fixed_iff_scalar {a b : Fin 3} (hab : a ≠ b)
    {γa γb : ℝ} (hγa : 0 < γa) (hγb : 0 < γb) (X : QubitMat) :
    (∀ t : ℝ, 0 ≤ t → expSemigroup (twoPauliGenerator a b γa γb) t X = X) ↔
      ∃ c : ℂ, X = c • (1 : QubitMat) := by
  rw [← generator_apply_eq_zero_iff_expSemigroup_fixed_nonneg]
  exact twoPauliGenerator_eq_zero_iff hab hγa hγb X

/-- The same fixed-point classification for any autonomous semigroup identified
with the exponential semigroup on nonnegative times. -/
theorem autonomousSemigroup_fixed_iff_scalar {a b : Fin 3} (hab : a ≠ b)
    {γa γb : ℝ} (hγa : 0 < γa) (hγb : 0 < γb)
    (T : ℝ → QubitMat →ₗ[ℂ] QubitMat)
    (hexp : ∀ t : ℝ, 0 ≤ t →
      T t = expSemigroup (twoPauliGenerator a b γa γb) t) (X : QubitMat) :
    (∀ t : ℝ, 0 ≤ t → T t X = X) ↔ ∃ c : ℂ, X = c • (1 : QubitMat) := by
  rw [← generator_apply_eq_zero_iff_fixed_nonneg _ T hexp]
  exact twoPauliGenerator_eq_zero_iff hab hγa hγb X

/-- In particular, the maximally mixed state is fixed at every nonnegative time. -/
theorem expSemigroup_fixes_maximallyMixed (a b : Fin 3) (γa γb : ℝ)
    (t : ℝ) (ht : 0 ≤ t) :
    expSemigroup (twoPauliGenerator a b γa γb) t maximallyMixed = maximallyMixed :=
  expSemigroup_apply_eq_self_of_generator_apply_eq_zero _
    (twoPauliGenerator_maximallyMixed a b γa γb) t ht

section ConditionalTraceNormEstimates

variable {State : Type*}

/-- Composition of entropy decay and Pinsker's inequality.

`hDecay` is the currently absent CMLSI consequence (exponential
relative-entropy decay), and `hPinsker` is the currently absent Pinsker
inequality for the intended squared trace distance `distSq`. The theorem keeps
that distance abstract rather than replacing it by the ambient operator norm. -/
theorem squared_trace_distance_bound_of_entropy_decay_and_pinsker
    (Drel : State → State → ℝ) (distSq : State → State → ℝ)
    (evolve : ℝ → State → State) (ρ ω : State) (n : ℕ) (α t : ℝ)
    (hDecay : Drel (evolve t ρ) ω ≤ Real.exp (-α * t) * Drel ρ ω)
    (hInitial : Drel ρ ω ≤ (n : ℝ) * Real.log 2)
    (hPinsker : distSq (evolve t ρ) ω ≤ 2 * Drel (evolve t ρ) ω) :
    distSq (evolve t ρ) ω ≤
      2 * Real.exp (-α * t) * ((n : ℝ) * Real.log 2) := by
  have hexp : 0 ≤ Real.exp (-α * t) := (Real.exp_pos _).le
  calc
    distSq (evolve t ρ) ω ≤ 2 * Drel (evolve t ρ) ω := hPinsker
    _ ≤ 2 * (Real.exp (-α * t) * Drel ρ ω) := by linarith
    _ ≤ 2 * (Real.exp (-α * t) * ((n : ℝ) * Real.log 2)) := by
      gcongr
    _ = 2 * Real.exp (-α * t) * ((n : ℝ) * Real.log 2) := by ring

/-- An explicit polynomial-target corollary. To obtain a squared trace-distance
bound `n⁻ᵖ`, it suffices to run until the exponential factor is at most
`n⁻ᵖ / (2 n log 2)`. Turning this displayed exponential condition into a
closed formula for `t` is elementary real analysis and independent of the
currently absent CMLSI and Pinsker inputs. -/
theorem squared_trace_distance_le_rpow_of_exp_threshold
    (Drel : State → State → ℝ) (distSq : State → State → ℝ)
    (evolve : ℝ → State → State) (ρ ω : State) (n : ℕ) (p α t : ℝ)
    (hn : 0 < n)
    (hDecay : Drel (evolve t ρ) ω ≤ Real.exp (-α * t) * Drel ρ ω)
    (hInitial : Drel ρ ω ≤ (n : ℝ) * Real.log 2)
    (hPinsker : distSq (evolve t ρ) ω ≤ 2 * Drel (evolve t ρ) ω)
    (hThreshold : Real.exp (-α * t) ≤
      (n : ℝ) ^ (-p) / (2 * ((n : ℝ) * Real.log 2))) :
    distSq (evolve t ρ) ω ≤ (n : ℝ) ^ (-p) := by
  have hbase := squared_trace_distance_bound_of_entropy_decay_and_pinsker
    Drel distSq evolve ρ ω n α t hDecay hInitial hPinsker
  have hnR : (0 : ℝ) < n := Nat.cast_pos.mpr hn
  have hlog : 0 < Real.log 2 := Real.log_pos (by norm_num)
  have hscale : 0 < 2 * ((n : ℝ) * Real.log 2) := mul_pos (by norm_num) (mul_pos hnR hlog)
  calc
    distSq (evolve t ρ) ω ≤
        2 * Real.exp (-α * t) * ((n : ℝ) * Real.log 2) := hbase
    _ ≤ 2 * ((n : ℝ) ^ (-p) / (2 * ((n : ℝ) * Real.log 2))) *
        ((n : ℝ) * Real.log 2) := by gcongr
    _ = (n : ℝ) ^ (-p) := by
      field_simp [ne_of_gt hscale]

/-- Finite-matrix form of the Q3 estimate using quantum relative entropy and
the matrix Schatten one-norm. The matrix size `2 ^ n` records an `n`-qubit
system. Quantum Pinsker and entropy decay remain explicit hypotheses. -/
theorem q3_traceNorm_sq_bound_of_entropy_decay_and_pinsker
    (n : ℕ)
    (evolve : ℝ → Matrix (Fin (2 ^ n)) (Fin (2 ^ n)) ℂ →
      Matrix (Fin (2 ^ n)) (Fin (2 ^ n)) ℂ)
    (ρ ω : Matrix (Fin (2 ^ n)) (Fin (2 ^ n)) ℂ) (α t : ℝ)
    (hDecay : quantumRelativeEntropy (evolve t ρ) ω ≤
      Real.exp (-α * t) * quantumRelativeEntropy ρ ω)
    (hInitial : quantumRelativeEntropy ρ ω ≤ (n : ℝ) * Real.log 2)
    (hPinsker : Matrix.traceNorm (evolve t ρ - ω) ^ 2 ≤
      2 * quantumRelativeEntropy (evolve t ρ) ω) :
    0 ≤ Matrix.traceNorm (evolve t ρ - ω) ∧
      Matrix.traceNorm (evolve t ρ - ω) ^ 2 ≤
        2 * Real.exp (-α * t) * ((n : ℝ) * Real.log 2) := by
  refine ⟨Matrix.traceNorm_nonneg _, ?_⟩
  exact squared_trace_distance_bound_of_entropy_decay_and_pinsker
    quantumRelativeEntropy (fun X Y => Matrix.traceNorm (X - Y) ^ 2)
      evolve ρ ω n α t hDecay hInitial hPinsker

/-- The exact logarithmic Q3 time scale implies the exponential threshold for
squared target `n⁻²ᵖ` when the entropy-decay rate is `γstar / 2`.  Here `n` is a
positive real so the lemma is a self-contained real-analysis statement. -/
theorem q3_exp_threshold_of_logarithmic_time
    (n p γstar t : ℝ) (hn : 0 < n) (_hp : 0 ≤ p) (hγstar : 0 < γstar)
    (ht : (2 / γstar) *
      ((2 * p + 1) * Real.log n + Real.log (2 * Real.log 2)) ≤ t) :
    Real.exp (-(γstar / 2) * t) ≤
      n ^ (-2 * p) / (2 * (n * Real.log 2)) := by
  have hlogTwo : 0 < Real.log 2 := Real.log_pos (by norm_num)
  have hc : 0 < 2 * Real.log 2 := mul_pos (by norm_num) hlogTwo
  have htime : 2 * ((2 * p + 1) * Real.log n + Real.log (2 * Real.log 2)) ≤
      γstar * t := by
    calc
      2 * ((2 * p + 1) * Real.log n + Real.log (2 * Real.log 2)) =
          γstar * ((2 / γstar) *
            ((2 * p + 1) * Real.log n + Real.log (2 * Real.log 2))) := by
        field_simp [ne_of_gt hγstar]
      _ ≤ γstar * t := mul_le_mul_of_nonneg_left ht hγstar.le
  have harg : -(γstar / 2) * t ≤
      -(2 * p + 1) * Real.log n - Real.log (2 * Real.log 2) := by
    nlinarith
  rw [Real.rpow_def_of_pos hn]
  calc
    Real.exp (-(γstar / 2) * t) ≤
        Real.exp (-(2 * p + 1) * Real.log n - Real.log (2 * Real.log 2)) :=
      Real.exp_le_exp.mpr harg
    _ = Real.exp (Real.log n * (-2 * p) -
        (Real.log n + Real.log (2 * Real.log 2))) := by
      congr 1
      ring
    _ = Real.exp (Real.log n * (-2 * p)) /
        Real.exp (Real.log n + Real.log (2 * Real.log 2)) := by
      rw [Real.exp_sub]
    _ = Real.exp (Real.log n * (-2 * p)) /
        (Real.exp (Real.log n) * Real.exp (Real.log (2 * Real.log 2))) := by
      rw [Real.exp_add]
    _ = Real.exp (Real.log n * (-2 * p)) / (n * (2 * Real.log 2)) := by
      rw [Real.exp_log hn, Real.exp_log hc]
    _ = Real.exp (Real.log n * (-2 * p)) / (2 * (n * Real.log 2)) := by ring

/-- Conditional `n`-qubit Q3 estimate at the logarithmic time in
`Notes/OpenProblemsQC/problems/q3_two_of_three_pauli_dissipation.tex`,
equation `eq:q3-threshold`. The explicit inputs are entropy decay with the
CMLSI lower-bound rate `γstar / 2`, the `n log 2` initial entropy bound, and
quantum Pinsker. -/
theorem q3_traceNorm_le_rpow_of_logarithmic_time
    (n : ℕ) (hn : 0 < n) (p γstar t : ℝ) (hp : 0 ≤ p) (hγstar : 0 < γstar)
    (evolve : ℝ → Matrix (Fin (2 ^ n)) (Fin (2 ^ n)) ℂ →
      Matrix (Fin (2 ^ n)) (Fin (2 ^ n)) ℂ)
    (ρ ω : Matrix (Fin (2 ^ n)) (Fin (2 ^ n)) ℂ)
    (hDecay : quantumRelativeEntropy (evolve t ρ) ω ≤
      Real.exp (-(γstar / 2) * t) * quantumRelativeEntropy ρ ω)
    (hInitial : quantumRelativeEntropy ρ ω ≤ (n : ℝ) * Real.log 2)
    (hPinsker : Matrix.traceNorm (evolve t ρ - ω) ^ 2 ≤
      2 * quantumRelativeEntropy (evolve t ρ) ω)
    (ht : (2 / γstar) *
      ((2 * p + 1) * Real.log (n : ℝ) + Real.log (2 * Real.log 2)) ≤ t) :
    Matrix.traceNorm (evolve t ρ - ω) ≤ (n : ℝ) ^ (-p) := by
  have hnR : (0 : ℝ) < n := Nat.cast_pos.mpr hn
  have hThreshold : Real.exp (-(γstar / 2) * t) ≤
      (n : ℝ) ^ (-2 * p) / (2 * ((n : ℝ) * Real.log 2)) :=
    q3_exp_threshold_of_logarithmic_time (n : ℝ) p γstar t hnR hp hγstar ht
  have hThreshold' : Real.exp (-(γstar / 2) * t) ≤
      (n : ℝ) ^ (-(2 * p)) / (2 * ((n : ℝ) * Real.log 2)) := by
    simpa only [neg_mul] using hThreshold
  have hsq : Matrix.traceNorm (evolve t ρ - ω) ^ 2 ≤ (n : ℝ) ^ (-(2 * p)) :=
    squared_trace_distance_le_rpow_of_exp_threshold
      quantumRelativeEntropy (fun X Y => Matrix.traceNorm (X - Y) ^ 2)
        evolve ρ ω n (2 * p) (γstar / 2) t hn hDecay hInitial hPinsker hThreshold'
  have hrpowSq : (n : ℝ) ^ (-(2 * p)) = ((n : ℝ) ^ (-p)) ^ 2 := by
    calc
      (n : ℝ) ^ (-(2 * p)) = (n : ℝ) ^ ((-p) * 2) := by
        congr 1
        ring
      _ = ((n : ℝ) ^ (-p)) ^ (2 : ℝ) := Real.rpow_mul hnR.le (-p) 2
      _ = ((n : ℝ) ^ (-p)) ^ 2 := Real.rpow_two _
  rw [hrpowSq] at hsq
  exact (sq_le_sq₀ (Matrix.traceNorm_nonneg _) (Real.rpow_nonneg hnR.le _)).mp hsq

end ConditionalTraceNormEstimates

end PauliDissipation
