/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.MonomialMatrix
import TNLean.Algebra.ScalarThreeCocycle
import TNLean.MPS.Core.CyclicTrace
import TNLean.MPS.MPU.GroupRepresentation

/-!
# Group matrix product operators from a three-cocycle: the periodic representation

**Source.** Garre-Rubio, Lootens, Molnár 2023 (arXiv:2203.12563), Section
"Examples of explicit MPSs and MPO representations", subsubsection "Periodic boundary
condition case", `Papers/2203.12563/REsubmission.tex` lines 2200–2224: for a finite group
`G` and a three-cocycle `ω`, the operators `U_g = ⨂_i (L_g^i ⊗ L_g^{i+1}) · W_g^{i,i+1}` on
`ℂ[G]^{⊗ N}`, generated by the bond-`|G|` tensor `T̂_g`, form a periodic matrix product
operator representation of `G` with `U_e = 1` (lines 2204–2205; tensor at lines 2206–2222).
Here `W_g |k,l⟩ = ω(g,l,l⁻¹k) |k,l⟩` (line 2068) and `L_g` is the left-regular shift
(lines 2005–2024 and 2070). The adjoint law `O_g† = O_{g⁻¹}` is printed at line 2096 for the
arbitrary-boundary operators only. The notion of a matrix product unitary representation
(`U_g U_h = U_{gh}`, `U_e = 1`) is that of Garre-Rubio–Schuch (arXiv:2405.00439),
Section IV.A, `Papers/2405.00439/MPU-DW.tex` line 1684.

**Formalized here.** For every normalized scalar three-cocycle `ω` and every positive chain
length `N`, the periodic operator of `T̂_g` is the monomial matrix of the left shift by `g`
with phase `∏_i ω(g, t_{i+1}, t_{i+1}⁻¹ t_i)` on the input configuration `t`; it satisfies
`U_g U_h = U_{gh}` and `U_e = 1`, and, when `ω` takes unit-modulus values, `U_g` is unitary
and `U_g† = U_{g⁻¹}`. Entrywise, the operator is `(⨂_i L_g) · ∏_i W_g^{i,i+1}`, built from
the gates `W_g` and the shifts `L_g` of the source. The site set is `Fin N` with cyclic
successor `i + 1`, and the group is transported to the bond and physical index `Fin n` by an
explicit bijection `e`.

**Local fix (one shift per site):** read literally, the display
`⨂_i (L_g^i ⊗ L_g^{i+1}) · W_g^{i,i+1}` at line 2205 applies `L_g` twice to every site, which
gives `L_{g²}`; the factor pair descends from the two halves of one site of the
arbitrary-boundary operator (line 2094), merged by `Γ`, and the tensor `T̂_g`
(lines 2208–2222) carries one `L_g` per site. The operator here has one `L_g` per site,
applied after all the gates `W_g^{i,i+1}`; documented in
`docs/paper-gaps/glm23_pbc_group_mpo_single_shift.tex`.

The tensors are not injective as single-site tensors (their `|G|²` physical matrices span a
space of dimension at most `|G|`), so `MPOTensor.GroupFamily.IsRawRepresentation`, which
requires injectivity, is not claimed; the four operator laws are stated directly.

## Main definitions

* `MPOTensor.GroupCocycle.wGate`: the diagonal two-site gate `W_g`.
* `MPOTensor.GroupCocycle.leftShift`: the left-regular shift `L_g`.
* `MPOTensor.GroupCocycle.tensor`: the bond-`|G|` tensor `T̂_g`.
* `MPOTensor.GroupCocycle.shift`, `MPOTensor.GroupCocycle.phase`: the permutation and phase of
  the periodic operator.
* `MPOTensor.GroupCocycle.family`: the group-indexed tensor family.

## Main results

* `MPOTensor.GroupCocycle.wGate_one`: `W_e = 1` for normalized cocycles.
* `MPOTensor.GroupCocycle.mpo_tensor_apply`, `MPOTensor.GroupCocycle.mpo_tensor`: the periodic
  operator is monomial.
* `MPOTensor.GroupCocycle.mpo_tensor_apply_eq_leftShift_wGate`: its entries are those of
  `(⨂_i L_g) · ∏_i W_g^{i,i+1}`.
* `MPOTensor.GroupCocycle.mpo_tensor_mul`: `U_g U_h = U_{gh}`.
* `MPOTensor.GroupCocycle.mpo_tensor_one`: `U_e = 1`.
* `MPOTensor.GroupCocycle.isMPUPos`: `U_g` is unitary on every nonempty chain.
* `MPOTensor.GroupCocycle.mpo_tensor_conjTranspose`: `U_g† = U_{g⁻¹}`.

## References
- [arXiv:2203.12563](https://arxiv.org/abs/2203.12563) -- Garre-Rubio, Lootens, Molnár,
  *Classifying phases protected by matrix product operator symmetries using matrix product
  states*
- [arXiv:2405.00439](https://arxiv.org/abs/2405.00439) -- Garre-Rubio, Schuch,
  *Fractional domain wall statistics in spin chains with anomalous symmetries*
-/

noncomputable section

open scoped BigOperators Matrix

namespace MPOTensor.GroupCocycle

open TNLean.Algebra

variable {G : Type*} [Group G] {n : ℕ}

/-! ### The local gates -/

/-- The diagonal two-site gate `W_g |k,l⟩ = ω(g,l,l⁻¹k) |k,l⟩`.

Source: arXiv:2203.12563, lines 2060–2068. -/
def wGate [DecidableEq G] (ω : ScalarThreeCochain G) (g : G) : Matrix (G × G) (G × G) ℂ :=
  Matrix.diagonal fun kl ↦ (ω g kl.2 (kl.2⁻¹ * kl.1) : ℂ)

/-- For a normalized three-cocycle the gate of the identity is the identity.

Source: arXiv:2203.12563, line 2068 ("`W_e = id` for normalized 3-cocycles"). -/
theorem wGate_one [DecidableEq G] {ω : ScalarThreeCochain G}
    (hω : ScalarThreeCochain.IsNormalized ω) :
    wGate ω 1 = 1 := by
  simp [wGate, hω.1]

/-- The left-regular shift `L_g |k⟩ = |gk⟩`.

Source: arXiv:2203.12563, lines 2005–2024 and 2070. -/
def leftShift [DecidableEq G] (g : G) : Matrix G G ℂ :=
  Matrix.monomial (Equiv.mulLeft g) fun _ ↦ 1

theorem leftShift_apply [DecidableEq G] (g a b : G) :
    leftShift g a b = if a = g * b then 1 else 0 := rfl

/-! ### The tensor -/

variable (e : G ≃ Fin n)

/-- The left shift by `g` transported to the index `Fin n`. -/
def siteShift (g : G) : Equiv.Perm (Fin n) :=
  e.symm.trans ((Equiv.mulLeft g).trans e)

@[simp]
theorem siteShift_apply (g : G) (j : Fin n) : siteShift e g j = e (g * e.symm j) := rfl

/-- The periodic-chain tensor `T̂_g`: the output is `g` times the input `j`, the outgoing
bond carries the input `j`, and the incoming bond `l` (the input of the previous site)
contributes the gate entry `ω(g, j, j⁻¹ l)`. The first physical index is the output row,
the second the input column.

Source: arXiv:2203.12563, lines 2204–2222 (the tensor `T̂_g`). -/
def tensor (ω : ScalarThreeCochain G) (g : G) : MPOTensor n n :=
  fun i j ↦ Matrix.of fun l r ↦
    if i = siteShift e g j ∧ r = j then (ω g (e.symm j) ((e.symm j)⁻¹ * e.symm l) : ℂ)
    else 0

theorem tensor_apply (ω : ScalarThreeCochain G) (g : G) (i j l r : Fin n) :
    tensor e ω g i j l r =
      if i = siteShift e g j ∧ r = j then (ω g (e.symm j) ((e.symm j)⁻¹ * e.symm l) : ℂ)
      else 0 := rfl

/-- The group-indexed family of the tensors `T̂_g`, with bond dimension `|G|`. -/
def family (ω : ScalarThreeCochain G) : GroupFamily G n where
  bondDim _ := n
  bondDim_pos _ := (e 1).pos
  tensor := tensor e ω

/-! ### The periodic operator -/

/-- The global left shift `⨂_i L_g` on periodic configurations. -/
def shift (g : G) (N : ℕ) : Equiv.Perm (Fin N → Fin n) :=
  Equiv.piCongrRight fun _ ↦ siteShift e g

@[simp]
theorem shift_apply (g : G) {N : ℕ} (t : Fin N → Fin n) (i : Fin N) :
    shift e g N t i = e (g * e.symm (t i)) := rfl

theorem shift_mul (g h : G) (N : ℕ) : shift e g N * shift e h N = shift e (g * h) N := by
  ext t i
  simp [Equiv.Perm.mul_apply, mul_assoc]

theorem shift_one (N : ℕ) : shift e (1 : G) N = 1 := by
  ext t i
  simp

variable {N : ℕ} [NeZero N]

/-- The phase `∏_i ω(g, t_{i+1}, t_{i+1}⁻¹ t_i)` of the input configuration `t`, the product
of the diagonal gates `W_g^{i,i+1}` around the periodic chain.

Source: arXiv:2203.12563, lines 2068 and 2205. -/
def phase (ω : ScalarThreeCochain G) (g : G) (t : Fin N → Fin n) : ℂˣ :=
  ∏ i, ω g (e.symm (t (i + 1))) ((e.symm (t (i + 1)))⁻¹ * e.symm (t i))

/-- **The periodic operator of `T̂_g` entrywise**: the entry at `(s, t)` vanishes unless `s`
is the left shift of `t` by `g`, and then equals the phase of `t`.

Source: arXiv:2203.12563, lines 2204–2222 (the operator `U_g` and its tensor `T̂_g`). The
source does not print this kernel: it is the closed-chain contraction of `T̂_g` along the
unique surviving bond configuration `b_i = t_{i-1}`, with the site pairing read from the
diagram at lines 2208–2215. -/
theorem mpo_tensor_apply (ω : ScalarThreeCochain G) (g : G) (s t : Fin N → Fin n) :
    mpo (tensor e ω g) N s t =
      if s = shift e g N t then
        ∏ i, (ω g (e.symm (t (i + 1))) ((e.symm (t (i + 1)))⁻¹ * e.symm (t i)) : ℂ)
      else 0 := by
  rw [mpo_apply, mpoMatrixEntry, evalWord_ofFn]
  have h := MPSTensor.trace_evalWord_eq_sum_cyclic (tensor e ω g).toMPSTensor
    (fun m ↦ finProdFinEquiv (s m, t m))
  rw [MPSTensor.evalWord_ofFn_eq_prod] at h
  have h' : (List.ofFn fun m ↦ tensor e ω g (s m) (t m)).prod.trace =
      ∑ b : Fin N → Fin n, ∏ v : Fin N, tensor e ω g (s v) (t v) (b v) (b (v + 1)) := by
    simpa only [toMPSTensor, MPSTensor.finProdFinEquiv_divNat,
      MPSTensor.finProdFinEquiv_modNat] using h
  rw [h']
  let b0 : Fin N → Fin n := fun m ↦ t (m - 1)
  rw [Fintype.sum_eq_single b0]
  · by_cases hst : s = shift e g N t
    · have hp : ∀ m, s m = siteShift e g (t m) := fun m ↦ congrFun hst m
      rw [ite_eq_left hst]
      calc
        _ = ∏ m, (ω g (e.symm (t m)) ((e.symm (t m))⁻¹ * e.symm (t (m - 1))) : ℂ) := by
          refine Finset.prod_congr rfl fun m _ ↦ ?_
          rw [tensor_apply, ite_eq_left ⟨hp m, by simp [b0]⟩]
        _ = _ := (Fintype.prod_equiv (Equiv.addRight 1) _ _ fun m ↦ by simp).symm
    · rw [ite_eq_right hst]
      obtain ⟨m, hm⟩ := Function.ne_iff.mp hst
      refine Finset.prod_eq_zero (Finset.mem_univ m) ?_
      rw [tensor_apply, ite_eq_right]
      exact fun h ↦ hm h.1
  · intro b hb
    obtain ⟨m, hm⟩ := Function.ne_iff.mp hb
    refine Finset.prod_eq_zero (Finset.mem_univ (m - 1)) ?_
    rw [tensor_apply, ite_eq_right]
    intro h
    apply hm
    simpa [b0] using h.2

/-- **The periodic operator of `T̂_g` is monomial**: the global left shift by `g` with the
phase of the input configuration.

Source: arXiv:2203.12563, lines 2204–2222. -/
theorem mpo_tensor (ω : ScalarThreeCochain G) (g : G) :
    mpo (tensor e ω g) N = Matrix.monomial (shift e g N) fun t ↦ (phase e ω g t : ℂ) := by
  ext s t
  rw [mpo_tensor_apply, Matrix.monomial_apply, phase, Units.coe_prod]

/-- **The periodic operator of `T̂_g` is `(⨂_i L_g) · ∏_i W_g^{i,i+1}`** entrywise: since the
gates are diagonal, the entry at `(s, t)` is the product of the shift entries `(L_g)_{s_i t_i}`
times the product of the gate entries at the neighboring pairs `(t_i, t_{i+1})`.

Bridge: arXiv:2203.12563, line 2205, with one `L_g` per site (see the module docstring). -/
theorem mpo_tensor_apply_eq_leftShift_wGate [DecidableEq G] (ω : ScalarThreeCochain G) (g : G)
    (s t : Fin N → Fin n) :
    mpo (tensor e ω g) N s t =
      (∏ i, leftShift g (e.symm (s i)) (e.symm (t i))) *
        ∏ i, wGate ω g (e.symm (t i), e.symm (t (i + 1))) (e.symm (t i), e.symm (t (i + 1))) := by
  have hs : s = shift e g N t ↔ ∀ i ∈ Finset.univ, e.symm (s i) = g * e.symm (t i) := by
    simp only [Finset.mem_univ, true_implies, funext_iff, shift_apply, Equiv.symm_apply_eq]
  simp only [mpo_tensor_apply, leftShift_apply, wGate, Matrix.diagonal_apply_eq,
    Finset.prod_ite_zero, Finset.prod_const_one, ← hs]
  split_ifs <;> simp

/-- The sitewise cocycle identity behind the multiplication law: after the shift by `h`, the
phases of `g` and `h` multiply to the phase of `gh` times a ratio that telescopes around the
chain. -/
private theorem phase_site {ω : ScalarThreeCochain G} (hω : ScalarThreeCochain.IsCocycle ω)
    (g h a x : G) :
    ω g (h * a) ((h * a)⁻¹ * (h * x)) * ω h a (a⁻¹ * x) =
      ω (g * h) a (a⁻¹ * x) * (ω g h x * (ω g h a)⁻¹) := by
  have hc := hω g h a (a⁻¹ * x)
  rw [mul_inv_cancel_left] at hc
  have hx : (h * a)⁻¹ * (h * x) = a⁻¹ * x := by group
  rw [hx, ← mul_assoc, hc, eq_mul_inv_iff_mul_eq]
  simp only [mul_comm, mul_left_comm]

theorem phase_mul {ω : ScalarThreeCochain G} (hω : ScalarThreeCochain.IsCocycle ω)
    (g h : G) (t : Fin N → Fin n) :
    phase e ω g (shift e h N t) * phase e ω h t = phase e ω (g * h) t := by
  simp only [phase, shift_apply, Equiv.symm_apply_apply, ← Finset.prod_mul_distrib,
    phase_site hω]
  rw [Finset.prod_mul_distrib, Finset.prod_mul_distrib, Finset.prod_inv_distrib,
    Fintype.prod_equiv (Equiv.addRight 1) (fun i ↦ ω g h (e.symm (t (i + 1))))
      (fun i ↦ ω g h (e.symm (t i))) (fun i ↦ rfl), mul_inv_cancel, mul_one]

/-- **Multiplication law** `U_g U_h = U_{gh}` on every nonempty periodic chain.

Source: arXiv:2203.12563, lines 2204–2205 ("The final MPOs are a representation of the
group `G`"). -/
theorem mpo_tensor_mul {ω : ScalarThreeCochain G} (hω : ScalarThreeCochain.IsCocycle ω)
    (g h : G) :
    mpo (tensor e ω g) N * mpo (tensor e ω h) N = mpo (tensor e ω (g * h)) N := by
  rw [mpo_tensor, mpo_tensor, mpo_tensor, Matrix.monomial_mul_monomial, shift_mul]
  congr 1
  funext t
  rw [← Units.val_mul, phase_mul e hω]

/-- **Identity law** `U_e = 1` on every nonempty periodic chain.

Source: arXiv:2203.12563, line 2204 ("`U_e = id^{⊗ n}`"). -/
theorem mpo_tensor_one {ω : ScalarThreeCochain G} (hω : ScalarThreeCochain.IsNormalized ω) :
    mpo (tensor e ω 1) N = 1 := by
  rw [mpo_tensor, shift_one, ← Matrix.monomial_one]
  congr 1
  funext t
  simp [phase, hω.1]

/-- The phase has unit modulus when every value of `ω` does. -/
theorem star_phase_mul_phase {ω : ScalarThreeCochain G} (hω : ∀ a b c, ‖(ω a b c : ℂ)‖ = 1)
    (g : G) (t : Fin N → Fin n) :
    star (phase e ω g t : ℂ) * (phase e ω g t : ℂ) = 1 := by
  rw [Complex.star_def, Complex.conj_mul', phase, Units.coe_prod, norm_prod]
  simp [hω]

/-- `U_g` is unitary on every nonempty periodic chain when `ω` takes unit-modulus values.

Source: arXiv:2405.00439, line 1684 (matrix product unitary representations), applied to the
operators of arXiv:2203.12563, lines 2204–2205. -/
theorem mpo_tensor_mem_unitaryGroup {ω : ScalarThreeCochain G}
    (hω : ∀ a b c, ‖(ω a b c : ℂ)‖ = 1) (g : G) :
    mpo (tensor e ω g) N ∈ Matrix.unitaryGroup (Fin N → Fin n) ℂ := by
  rw [mpo_tensor]
  exact Matrix.monomial_mem_unitaryGroup _ _ (star_phase_mul_phase e hω g)

/-- **Adjoint law** `U_g† = U_{g⁻¹}` on every nonempty periodic chain, for a normalized
three-cocycle with unit-modulus values.

Source: arXiv:2203.12563, line 2096, where `O_g† = O_{g⁻¹}` is stated for the
arbitrary-boundary operators; the periodic passage (lines 2204–2205) does not restate it.
Here it is carried over to `U_g` as a consequence of unitarity and the group laws. -/
theorem mpo_tensor_conjTranspose {ω : ScalarThreeCochain G}
    (hc : ScalarThreeCochain.IsCocycle ω) (hn : ScalarThreeCochain.IsNormalized ω)
    (hω : ∀ a b c, ‖(ω a b c : ℂ)‖ = 1) (g : G) :
    (mpo (tensor e ω g) N)ᴴ = mpo (tensor e ω g⁻¹) N := by
  have hu := mpo_tensor_mem_unitaryGroup e hω g (N := N)
  rw [Matrix.mem_unitaryGroup_iff', Matrix.star_eq_conjTranspose] at hu
  calc
    _ = (mpo (tensor e ω g) N)ᴴ * (mpo (tensor e ω g) N * mpo (tensor e ω g⁻¹) N) := by
      rw [mpo_tensor_mul e hc, mul_inv_cancel, mpo_tensor_one e hn, Matrix.mul_one]
    _ = _ := by rw [← Matrix.mul_assoc, hu, Matrix.one_mul]

end MPOTensor.GroupCocycle

namespace MPOTensor.GroupCocycle

open TNLean.Algebra

variable {G : Type*} [Group G] {n : ℕ} (e : G ≃ Fin n)

/-- **`T̂_g` is a matrix product unitary** on every nonempty periodic chain when `ω` takes
unit-modulus values.

Source: arXiv:2203.12563, lines 2204–2222; arXiv:2405.00439, line 1684. -/
theorem isMPUPos {ω : ScalarThreeCochain G} (hω : ∀ a b c, ‖(ω a b c : ℂ)‖ = 1) (g : G) :
    IsMPUPos (tensor e ω g) := by
  intro N hN
  have : NeZero N := ⟨by omega⟩
  exact mpo_tensor_mem_unitaryGroup e hω g

/-- The operator laws of a periodic matrix product unitary representation, stated for the
positive chain lengths of `MPOTensor.GroupFamily.IsRawRepresentation` without its one-site
injectivity clause: `U_e = 1`, `U_g U_h = U_{gh}`, and `U_g† = U_{g⁻¹}`.

Source: arXiv:2203.12563, lines 2204–2222 and 2096; arXiv:2405.00439, line 1684. -/
theorem family_operator_laws {ω : ScalarThreeCochain G}
    (hc : ScalarThreeCochain.IsCocycle ω) (hn : ScalarThreeCochain.IsNormalized ω)
    (hω : ∀ a b c, ‖(ω a b c : ℂ)‖ = 1) :
    (∀ g, IsMPUPos ((family e ω).tensor g)) ∧
      (∀ N, 0 < N → mpo ((family e ω).tensor 1) N = 1) ∧
      (∀ g h N, 0 < N →
        mpo ((family e ω).tensor g) N * mpo ((family e ω).tensor h) N =
          mpo ((family e ω).tensor (g * h)) N) ∧
      (∀ g N, 0 < N → (mpo ((family e ω).tensor g) N)ᴴ = mpo ((family e ω).tensor g⁻¹) N) :=
  ⟨isMPUPos e hω,
    fun N hN ↦ have : NeZero N := ⟨by omega⟩; mpo_tensor_one e hn,
    fun g h N hN ↦ have : NeZero N := ⟨by omega⟩; mpo_tensor_mul e hc g h,
    fun g N hN ↦ have : NeZero N := ⟨by omega⟩; mpo_tensor_conjTranspose e hc hn hω g⟩

end MPOTensor.GroupCocycle
