/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.NilMatrixSubalgebra
import TNLean.MPS.MPU.DoubleLayerContraction

/-!
# Residual nonunital algebra of a matrix product unitary

This file formalizes the nil-algebra step in the proof of arXiv:1703.09188,
Proposition `blockingsimple`, lines 405--415.  The residual slices generate a
nonunital algebra.  Positive residual words have zero trace, so linearity extends
trace vanishing to the whole algebra.  Every positive power remains in that
algebra, hence every element is nilpotent.  The finite-dimensional nil-matrix
theorem then makes every product of exactly `D²` residual matrices vanish.

The source claims a strict intermediate bound.  We use the corrected exact
length `D²`; see `docs/paper-gaps/mpu_nil_matrix_bound.tex`.
-/

open scoped Matrix

namespace MPOTensor

variable {d D : ℕ}

/-- The set of virtual residual slices of the physical-adjoint double layer.

Source: arXiv:1703.09188, equation `WIsom` and Proposition III.3, lines 390--410. -/
noncomputable def residualGeneratorSet (U : MPOTensor d D) :
    Set (Matrix (Fin (D * D)) (Fin (D * D)) ℂ) :=
  Set.range (residualSlice (doubleLayerTensor U))

/-- The nonunital complex algebra generated by the residual slices.

Source: arXiv:1703.09188, Proposition III.3, line 410. -/
noncomputable def residualAlgebra (U : MPOTensor d D) :
    NonUnitalSubalgebra ℂ (Matrix (Fin (D * D)) (Fin (D * D)) ℂ) :=
  NonUnitalAlgebra.adjoin ℂ (residualGeneratorSet U)

/-- Every residual slice belongs to the generated residual algebra.

Source: arXiv:1703.09188, Proposition III.3, line 410. -/
theorem residualSlice_mem_residualAlgebra (U : MPOTensor d D)
    (X : Matrix (Fin d) (Fin d) ℂ) :
    residualSlice (doubleLayerTensor U) X ∈ residualAlgebra U := by
  apply NonUnitalAlgebra.subset_adjoin ℂ
  exact ⟨X, rfl⟩

private theorem list_prod_eq_residual_word_of_mem_generatorSet
    (U : MPOTensor d D) (l : List (Matrix (Fin (D * D)) (Fin (D * D)) ℂ))
    (hl : ∀ A ∈ l, A ∈ residualGeneratorSet U) :
    ∃ X : Fin l.length → Matrix (Fin d) (Fin d) ℂ,
      l = List.ofFn (fun k ↦ residualSlice (doubleLayerTensor U) (X k)) := by
  classical
  have hX : ∀ k : Fin l.length,
      ∃ X : Matrix (Fin d) (Fin d) ℂ,
        l[k] = residualSlice (doubleLayerTensor U) X := by
    intro k
    obtain ⟨X, hX⟩ := hl l[k] (List.get_mem l k)
    exact ⟨X, hX.symm⟩
  choose X hX using hX
  refine ⟨X, ?_⟩
  calc
    l = List.ofFn (fun k ↦ l[k]) := (List.ofFn_get l).symm
    _ = List.ofFn (fun k ↦ residualSlice (doubleLayerTensor U) (X k)) := by
      congr 1
      funext k
      exact hX k

/-- Every nonempty word in residual generators has zero trace.

Source: arXiv:1703.09188, Proposition III.3, lines 405--410. -/
theorem IsMPU.trace_list_prod_eq_zero_of_mem_residualGeneratorSet
    [NeZero d] {U : MPOTensor d D} (hU : IsMPU U)
    (l : List (Matrix (Fin (D * D)) (Fin (D * D)) ℂ))
    (hl : ∀ A ∈ l, A ∈ residualGeneratorSet U) (hne : l ≠ []) :
    Matrix.trace l.prod = 0 := by
  classical
  obtain ⟨X, hword⟩ := list_prod_eq_residual_word_of_mem_generatorSet U l hl
  let isResidual : Fin l.length → Bool := fun _ ↦ true
  have hpos : 0 < l.length := List.length_pos_iff.mpr hne
  have hmixed : ∃ k, isResidual k = true := ⟨⟨0, hpos⟩, rfl⟩
  calc
    Matrix.trace l.prod = Matrix.trace
        (List.ofFn (fun k ↦ residualSlice (doubleLayerTensor U) (X k))).prod := by
      exact congrArg (fun xs ↦ Matrix.trace xs.prod) hword
    _ = 0 := by
      simpa [isResidual, mixedResidualFactor] using
        hU.trace_prod_mixedResidualFactor_doubleLayerTensor_eq_zero_of_pos
          hpos isResidual X hmixed

private theorem Subsemigroup.exists_nonempty_list_prod_of_mem_closure
    {M : Type*} [Monoid M] {s : Set M} {x : M}
    (hx : x ∈ Subsemigroup.closure s) :
    ∃ l : List M, l ≠ [] ∧ (∀ a ∈ l, a ∈ s) ∧ l.prod = x := by
  induction hx using Subsemigroup.closure_induction with
  | mem x hx => exact ⟨[x], by simp, by simpa, by simp⟩
  | mul x y _ _ hx hy =>
      obtain ⟨lx, hlx, hlxs, hxl⟩ := hx
      obtain ⟨ly, hly, hlys, hyl⟩ := hy
      refine ⟨lx ++ ly, ?_, ?_, ?_⟩
      · simp [hlx]
      · intro a ha
        exact List.mem_append.mp ha |>.elim (hlxs a) (hlys a)
      · rw [List.prod_append, hxl, hyl]

/-- Every element of the residual nonunital algebra has zero trace.

The proof uses `NonUnitalAlgebra.adjoin_eq_span`: semigroup closure gives
nonempty residual words, and `Submodule.span_induction` extends their trace
identity by linearity.

Source: arXiv:1703.09188, Proposition III.3, lines 405--410. -/
theorem IsMPU.trace_eq_zero_of_mem_residualAlgebra
    [NeZero d] {U : MPOTensor d D} (hU : IsMPU U)
    {A : Matrix (Fin (D * D)) (Fin (D * D)) ℂ}
    (hA : A ∈ residualAlgebra U) : Matrix.trace A = 0 := by
  change A ∈ (NonUnitalAlgebra.adjoin ℂ (residualGeneratorSet U)).toSubmodule at hA
  rw [NonUnitalAlgebra.adjoin_eq_span] at hA
  induction hA using Submodule.span_induction with
  | mem A hA =>
      obtain ⟨l, hne, hl, rfl⟩ :=
        Subsemigroup.exists_nonempty_list_prod_of_mem_closure hA
      exact hU.trace_list_prod_eq_zero_of_mem_residualGeneratorSet l hl hne
  | zero => simp
  | add A B _ _ hA hB => simp [Matrix.trace_add, hA, hB]
  | smul c A _ hA => simp [Matrix.trace_smul, hA]

private theorem pow_mem_nonUnitalSubalgebra_of_pos
    {R A : Type*} [CommSemiring R] [Semiring A] [Module R A]
    [IsScalarTower R A A] [SMulCommClass R A A]
    (S : NonUnitalSubalgebra R A) {x : A} (hx : x ∈ S)
    {N : ℕ} (hN : 0 < N) : x ^ N ∈ S := by
  cases N with
  | zero => omega
  | succ N =>
      clear hN
      induction N with
      | zero => simpa using hx
      | succ N ih => simpa [pow_succ] using S.mul_mem ih hx

/-- Every element of the residual algebra has zero trace in every power whose
exponent is greater than one.

Source: arXiv:1703.09188, Proposition III.3, line 410. -/
theorem IsMPU.trace_pow_eq_zero_of_mem_residualAlgebra
    [NeZero d] {U : MPOTensor d D} (hU : IsMPU U)
    {A : Matrix (Fin (D * D)) (Fin (D * D)) ℂ}
    (hA : A ∈ residualAlgebra U) {N : ℕ} (hN : 1 < N) :
    Matrix.trace (A ^ N) = 0 := by
  apply hU.trace_eq_zero_of_mem_residualAlgebra
  exact pow_mem_nonUnitalSubalgebra_of_pos (residualAlgebra U) hA (by omega)

/-- Every element of the residual algebra is nilpotent.

Source: arXiv:1703.09188, Proposition III.3, line 410. -/
theorem IsMPU.isNilpotent_of_mem_residualAlgebra
    [NeZero d] {U : MPOTensor d D} (hU : IsMPU U)
    (A : residualAlgebra U) : IsNilpotent (A : Matrix (Fin (D * D)) (Fin (D * D)) ℂ) := by
  apply Matrix.isNilpotent_of_forall_trace_pow_eq_zero_of_one_lt
  intro N hN
  exact hU.trace_pow_eq_zero_of_mem_residualAlgebra A.property hN

/-- Every product of exactly `D²` elements of the residual algebra vanishes.

**Local fix (arXiv:1703.09188, Proposition III.3, lines 410--415):** the source's
unsupported strict intermediate bound is replaced by the exact ambient-dimension
length `D²`; see `docs/paper-gaps/mpu_nil_matrix_bound.tex`. -/
theorem IsMPU.residualAlgebra_list_prod_eq_zero
    [NeZero d] {U : MPOTensor d D} (hU : IsMPU U)
    (l : List (Matrix (Fin (D * D)) (Fin (D * D)) ℂ))
    (hl : ∀ A ∈ l, A ∈ residualAlgebra U) (hlen : l.length = D * D) :
    l.prod = 0 := by
  apply (residualAlgebra U).matrix_list_prod_eq_zero_of_forall_isNilpotent
    hU.isNilpotent_of_mem_residualAlgebra l hl
  simpa using hlen

/-- Every product of exactly `D²` residual slices vanishes.

**Local fix (arXiv:1703.09188, equation `Sprime=0`, lines 410--415):** the
corrected length is `D²`, rather than a strict bound below it; see
`docs/paper-gaps/mpu_nil_matrix_bound.tex`. -/
theorem IsMPU.prod_residualSlice_doubleLayerTensor_eq_zero
    [NeZero d] {U : MPOTensor d D} (hU : IsMPU U)
    (X : Fin (D * D) → Matrix (Fin d) (Fin d) ℂ) :
    (List.ofFn (fun k ↦ residualSlice (doubleLayerTensor U) (X k))).prod = 0 := by
  apply hU.residualAlgebra_list_prod_eq_zero
  · intro A hA
    obtain ⟨k, _, rfl⟩ := List.mem_ofFn.mp hA
    exact residualSlice_mem_residualAlgebra U (X k)
  · simp

end MPOTensor
