/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.Core.BlockingInfrastructure
import TNLean.MPS.MPU.ThreeFormSpan

/-!
# Bounded blocking to a simple matrix product unitary

This file completes the algebraic contraction step in arXiv:1703.09188,
Proposition `blockingsimple`, lines 415--427, and its all-later-blocks
corollary, lines 442--446.  It turns the basis-invariant three-form residual
classification into the exact `simple1` and `simple2` identities and proves
that simplicity persists at every larger direct blocking length.

The trace is a character on the algebra generated by the double-layer letters,
and its kernel is a nilpotent subalgebra.  Applying the three-form argument to
that kernel shows that blocking `D²` sites already makes every MPU simple
(`IsMPU.blockTensor_sq_isMPUSimple`), sharpening the source bound below `D⁴`.
-/

open scoped Matrix BigOperators
open Matrix

namespace MPOTensor

variable {d D : ℕ}

section ThreeFormInsertion

variable {n : Type*} [Fintype n] [DecidableEq n]

private def threeFormGeneratorSet (E : Matrix n n ℂ)
    (A : NonUnitalSubalgebra ℂ (Matrix n n ℂ)) : Set (Matrix n n ℂ) :=
  {x | ∃ a : A, x = E * (a : Matrix n n ℂ)} ∪
    {x | ∃ a : A, x = (a : Matrix n n ℂ) * E} ∪
      {x | ∃ a b : A, x = (a : Matrix n n ℂ) * E * (b : Matrix n n ℂ)}

private theorem threeFormSubmodule_eq_span_generatorSet
    (E : Matrix n n ℂ) (A : NonUnitalSubalgebra ℂ (Matrix n n ℂ)) :
    threeFormSubmodule E A = Submodule.span ℂ (threeFormGeneratorSet E A) := by
  simp only [threeFormSubmodule, projectorMulResidualSubmodule,
    residualMulProjectorSubmodule, residualMulProjectorMulResidualSubmodule,
    threeFormGeneratorSet, Submodule.span_union]

omit [DecidableEq n] in
private theorem threeForm_generator_mul_eq_mul_projector_mul
    (E : Matrix n n ℂ) (A : NonUnitalSubalgebra ℂ (Matrix n n ℂ))
    (hE : E * E = E) (hEAE : ∀ a : A, E * (a : Matrix n n ℂ) * E = 0)
    {x y : Matrix n n ℂ} (hx : x ∈ threeFormGeneratorSet E A)
    (hy : y ∈ threeFormGeneratorSet E A) : x * y = x * E * y := by
  classical
  have hcollapse (X : Matrix n n ℂ) : X * E * E = X * E := by
    rw [Matrix.mul_assoc, hE]
  rcases hx with (⟨a, rfl⟩ | ⟨a, rfl⟩) | ⟨a, b, rfl⟩ <;>
    rcases hy with (⟨c, rfl⟩ | ⟨c, rfl⟩) | ⟨c, e, rfl⟩
  · simp only [← mul_assoc, hEAE, zero_mul]
  · have hac : E * ((a : Matrix n n ℂ) * c : Matrix n n ℂ) * E = 0 :=
      hEAE ⟨(a : Matrix n n ℂ) * c, A.mul_mem a.property c.property⟩
    rw [show (E * (a : Matrix n n ℂ)) * ((c : Matrix n n ℂ) * E) =
      E * ((a : Matrix n n ℂ) * c) * E by simp [mul_assoc], hac]
    simp only [← mul_assoc, hEAE, zero_mul]
  · have hac : E * ((a : Matrix n n ℂ) * c : Matrix n n ℂ) * E = 0 :=
      hEAE ⟨(a : Matrix n n ℂ) * c, A.mul_mem a.property c.property⟩
    rw [show (E * (a : Matrix n n ℂ)) * ((c : Matrix n n ℂ) * E * e) =
      (E * ((a : Matrix n n ℂ) * c) * E) * e by simp [mul_assoc], hac, zero_mul]
    simp only [← mul_assoc, hEAE, zero_mul]
  · symm
    rw [hcollapse]
  · rw [show ((a : Matrix n n ℂ) * E) * ((c : Matrix n n ℂ) * E) =
      (a : Matrix n n ℂ) * (E * c * E) by simp [mul_assoc], hEAE, mul_zero]
    rw [hcollapse]
    rw [show ((a : Matrix n n ℂ) * E) * ((c : Matrix n n ℂ) * E) =
      (a : Matrix n n ℂ) * (E * c * E) by simp [mul_assoc], hEAE, mul_zero]
  · rw [show ((a : Matrix n n ℂ) * E) * ((c : Matrix n n ℂ) * E * e) =
      (a : Matrix n n ℂ) * (E * c * E) * e by simp [mul_assoc], hEAE, mul_zero,
      zero_mul]
    rw [hcollapse]
    rw [show ((a : Matrix n n ℂ) * E) * ((c : Matrix n n ℂ) * E * e) =
      (a : Matrix n n ℂ) * (E * c * E) * e by simp [mul_assoc], hEAE, mul_zero,
      zero_mul]
  · rw [show ((a : Matrix n n ℂ) * E * b) * (E * (c : Matrix n n ℂ)) =
      (a : Matrix n n ℂ) * (E * b * E) * c by simp [mul_assoc], hEAE, mul_zero,
      zero_mul]
    rw [show ((a : Matrix n n ℂ) * E * b) * E * (E * (c : Matrix n n ℂ)) =
      (a : Matrix n n ℂ) * (E * b * E) * (E * c) by simp [mul_assoc], hEAE,
      mul_zero, zero_mul]
  · have hbc : E * ((b : Matrix n n ℂ) * c : Matrix n n ℂ) * E = 0 :=
      hEAE ⟨(b : Matrix n n ℂ) * c, A.mul_mem b.property c.property⟩
    rw [show ((a : Matrix n n ℂ) * E * b) * ((c : Matrix n n ℂ) * E) =
      (a : Matrix n n ℂ) * (E * ((b : Matrix n n ℂ) * c) * E) by simp [mul_assoc],
      hbc, mul_zero]
    rw [show ((a : Matrix n n ℂ) * E * b) * E * ((c : Matrix n n ℂ) * E) =
      (a : Matrix n n ℂ) * (E * b * E) * c * E by simp [mul_assoc], hEAE,
      mul_zero, zero_mul]
    simp
  · have hbc : E * ((b : Matrix n n ℂ) * c : Matrix n n ℂ) * E = 0 :=
      hEAE ⟨(b : Matrix n n ℂ) * c, A.mul_mem b.property c.property⟩
    rw [show ((a : Matrix n n ℂ) * E * b) * ((c : Matrix n n ℂ) * E * e) =
      (a : Matrix n n ℂ) * (E * ((b : Matrix n n ℂ) * c) * E) * e by
        simp [mul_assoc], hbc, mul_zero, zero_mul]
    rw [show ((a : Matrix n n ℂ) * E * b) * E * ((c : Matrix n n ℂ) * E * e) =
      (a : Matrix n n ℂ) * (E * b * E) * c * E * e by simp [mul_assoc], hEAE,
      mul_zero, zero_mul]
    simp

/-- Bilinear insertion identity on the basis-invariant three-form residual
subspace.

Source: arXiv:1703.09188, equation `simple2` and the paragraph following
`sprimeforms`, lines 419--426. -/
theorem mul_eq_mul_projector_mul_of_mem_threeFormSubmodule
    (E : Matrix n n ℂ) (A : NonUnitalSubalgebra ℂ (Matrix n n ℂ))
    (hE : E * E = E) (hEAE : ∀ a : A, E * (a : Matrix n n ℂ) * E = 0)
    {x y : Matrix n n ℂ} (hx : x ∈ threeFormSubmodule E A)
    (hy : y ∈ threeFormSubmodule E A) : x * y = x * E * y := by
  classical
  rw [threeFormSubmodule_eq_span_generatorSet] at hx hy
  induction hx using Submodule.span_induction with
  | mem x hx =>
      induction hy using Submodule.span_induction with
      | mem y hy => exact threeForm_generator_mul_eq_mul_projector_mul E A hE hEAE hx hy
      | zero => simp
      | add y z _ _ hy hz => simp [Matrix.mul_add, hy, hz]
      | smul c y _ hy => simp [hy]
  | zero => simp
  | add x z _ _ hx hz => simp [Matrix.add_mul, hx, hz]
  | smul c x _ hx => simp [hx]

omit [DecidableEq n] in
private theorem trace_mul_projector_eq_zero_generator
    (E : Matrix n n ℂ) (A : NonUnitalSubalgebra ℂ (Matrix n n ℂ))
    (hE : E * E = E) (hEAE : ∀ a : A, E * (a : Matrix n n ℂ) * E = 0)
    {x : Matrix n n ℂ} (hx : x ∈ threeFormGeneratorSet E A) :
    Matrix.trace (x * E) = 0 := by
  classical
  rcases hx with (⟨a, rfl⟩ | ⟨a, rfl⟩) | ⟨a, b, rfl⟩
  · simp [hEAE]
  · have htr : Matrix.trace ((a : Matrix n n ℂ) * E) = 0 := by
      calc
        Matrix.trace ((a : Matrix n n ℂ) * E) =
            Matrix.trace (E * (a : Matrix n n ℂ)) := Matrix.trace_mul_comm _ _
        _ = Matrix.trace (E * E * (a : Matrix n n ℂ)) := by rw [hE]
        _ = Matrix.trace (E * (a : Matrix n n ℂ) * E) :=
          (Matrix.trace_mul_cycle E (a : Matrix n n ℂ) E).symm
        _ = 0 := by rw [hEAE, Matrix.trace_zero]
    rw [Matrix.mul_assoc, hE, htr]
  · rw [show ((a : Matrix n n ℂ) * E * b) * E =
      (a : Matrix n n ℂ) * (E * b * E) by simp [mul_assoc], hEAE, mul_zero,
      Matrix.trace_zero]

/-- Every three-form residual has zero contraction between the rank-one
projector witnesses.

Source: arXiv:1703.09188, equation `simple1`, lines 423--426. -/
theorem trace_mul_projector_eq_zero_of_mem_threeFormSubmodule
    (E : Matrix n n ℂ) (A : NonUnitalSubalgebra ℂ (Matrix n n ℂ))
    (hE : E * E = E) (hEAE : ∀ a : A, E * (a : Matrix n n ℂ) * E = 0)
    {x : Matrix n n ℂ} (hx : x ∈ threeFormSubmodule E A) :
    Matrix.trace (x * E) = 0 := by
  classical
  rw [threeFormSubmodule_eq_span_generatorSet] at hx
  induction hx using Submodule.span_induction with
  | mem x hx => exact trace_mul_projector_eq_zero_generator E A hE hEAE hx
  | zero => simp
  | add x y _ _ hx hy => simp [Matrix.add_mul, Matrix.trace_add, hx, hy]
  | smul c x _ hx => simp [Matrix.trace_smul, hx]

/-- A first-block MPU whose normalized double-layer diagonal is a normalized
rank-one projector becomes MPU-simple after the corrected second blocking of
exact length \(D^2\).

Source: arXiv:1703.09188, Proposition III.3(ii), lines 405--427.

**Local fix (nil-matrix length):** the second blocking uses \(D^2\), replacing the
unsupported strict intermediate bound; see <https://sirui-lu.com/QICLean/paper-gaps/mpu_nil_matrix_bound.pdf>. -/
theorem IsMPU.blockTensor_sq_simple_contractions_of_normalizedDiagonal_eq_vecMulVec
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U)
    (ρ Φ : Fin (D * D) → ℂ) (hpair : Φ ⬝ᵥ ρ = 1)
    (hE : normalizedDiagonal (doubleLayerTensor U) = Matrix.vecMulVec ρ Φ) :
    (∀ i j,
      Φ ⬝ᵥ (doubleLayerTensor (MPOTensor.blockTensor U (D * D)) i j *ᵥ ρ) =
        if i = j then 1 else 0) ∧
    (∀ i j k l,
      doubleLayerTensor (MPOTensor.blockTensor U (D * D)) i j *
          doubleLayerTensor (MPOTensor.blockTensor U (D * D)) k l =
        doubleLayerTensor (MPOTensor.blockTensor U (D * D)) i j *
          Matrix.vecMulVec ρ Φ *
            doubleLayerTensor (MPOTensor.blockTensor U (D * D)) k l) := by
  classical
  let E := normalizedDiagonal (doubleLayerTensor U)
  let A := residualAlgebra U
  have hEouter : E = Matrix.vecMulVec ρ Φ := by simpa [E] using hE
  have hEidem : E * E = E := by
    rw [hEouter, Matrix.vecMulVec_mul_vecMulVec, hpair, one_smul]
  have hEAE : ∀ a : A, E * (a : Matrix (Fin (D * D)) (Fin (D * D)) ℂ) * E = 0 :=
    hU.normalizedDiagonal_mul_mem_residualAlgebra_mul_normalizedDiagonal_eq_zero ρ Φ hE
  let V := MPOTensor.blockTensor U (D * D)
  have hEV : normalizedDiagonal (doubleLayerTensor V) = E := by
    dsimp [V, E]
    rw [doubleLayerTensor_blockTensor, normalizedDiagonal_blockTensor,
      IsIdempotentElem.pow_eq hEidem (Nat.mul_pos (NeZero.pos D) (NeZero.pos D)).ne']
  constructor
  · intro i j
    let R := residualSlice (doubleLayerTensor V) (Matrix.single j i 1)
    have hR : R ∈ threeFormSubmodule E A :=
      hU.residualSlice_doubleLayerTensor_blockTensor_single_mem_threeFormSubmodule
        ρ Φ hE hEidem i j
    have hRtrace : Matrix.trace (R * E) = 0 :=
      trace_mul_projector_eq_zero_of_mem_threeFormSubmodule E A hEidem hEAE hR
    have hRpair : Φ ⬝ᵥ (R *ᵥ ρ) = 0 := by
      calc
        Φ ⬝ᵥ (R *ᵥ ρ) = Matrix.trace (Matrix.vecMulVec (R *ᵥ ρ) Φ) := by
          rw [Matrix.trace_vecMulVec, dotProduct_comm]
        _ = Matrix.trace (R * Matrix.vecMulVec ρ Φ) := by rw [Matrix.mul_vecMulVec]
        _ = Matrix.trace (R * E) := by
          rw [hEouter]
        _ = 0 := hRtrace
    rw [entry_eq_diagonal_add_residual (doubleLayerTensor V) i j, hEV]
    change Φ ⬝ᵥ (((if i = j then (1 : ℂ) else 0) • E + R) *ᵥ ρ) = _
    simp only [Matrix.add_mulVec, Matrix.smul_mulVec, dotProduct_add, dotProduct_smul,
      hRpair, add_zero]
    rw [hEouter, Matrix.vecMulVec_mulVec]
    simp [hpair]
  · intro i j k l
    let Rij := residualSlice (doubleLayerTensor V) (Matrix.single j i 1)
    let Rkl := residualSlice (doubleLayerTensor V) (Matrix.single l k 1)
    have hRij : Rij ∈ threeFormSubmodule E A :=
      hU.residualSlice_doubleLayerTensor_blockTensor_single_mem_threeFormSubmodule
        ρ Φ hE hEidem i j
    have hRkl : Rkl ∈ threeFormSubmodule E A :=
      hU.residualSlice_doubleLayerTensor_blockTensor_single_mem_threeFormSubmodule
        ρ Φ hE hEidem k l
    have hRR : Rij * Rkl = Rij * E * Rkl :=
      mul_eq_mul_projector_mul_of_mem_threeFormSubmodule E A hEidem hEAE hRij hRkl
    rw [entry_eq_diagonal_add_residual (doubleLayerTensor V) i j,
      entry_eq_diagonal_add_residual (doubleLayerTensor V) k l, hEV]
    change _ = _ * Matrix.vecMulVec ρ Φ * _
    rw [← hEouter]
    change ((if i = j then (1 : ℂ) else 0) • E + Rij) *
      ((if k = l then (1 : ℂ) else 0) • E + Rkl) =
      ((if i = j then (1 : ℂ) else 0) • E + Rij) * E *
        ((if k = l then (1 : ℂ) else 0) • E + Rkl)
    simp [Matrix.add_mul, Matrix.mul_add, hEidem, hRR, mul_assoc]

/-- A first-block MPU with supplied normalized rank-one fixed witnesses becomes
MPU-simple after the corrected second blocking of exact length \(D^2\).

Source: arXiv:1703.09188, Proposition III.3(ii), lines 405--427.

**Local fix (nil-matrix length):** the second blocking uses \(D^2\), replacing the
unsupported strict intermediate bound; see <https://sirui-lu.com/QICLean/paper-gaps/mpu_nil_matrix_bound.pdf>. -/
theorem IsMPU.blockTensor_sq_isMPUSimple_of_normalizedDiagonal_eq_vecMulVec
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U)
    (ρ Φ : Fin (D * D) → ℂ) (hpair : Φ ⬝ᵥ ρ = 1)
    (hE : normalizedDiagonal (doubleLayerTensor U) = Matrix.vecMulVec ρ Φ) :
    IsMPUSimple (MPOTensor.blockTensor U (D * D)) := by
  exact ⟨Φ, ρ,
    hU.blockTensor_sq_simple_contractions_of_normalizedDiagonal_eq_vecMulVec ρ Φ hpair hE⟩

end ThreeFormInsertion

section BlockingConstruction

private theorem listProd_mul_eq_listProd_mul_rankOne_mul
    {n : Type*} [Fintype n] [DecidableEq n]
    (a b : n → ℂ) (P : Matrix n n ℂ → Prop)
    (hpair : ∀ A B, P A → P B →
      A * B = A * Matrix.vecMulVec b a * B) :
    ∀ l r : List (Matrix n n ℂ), l ≠ [] → r ≠ [] →
      (∀ A ∈ l, P A) → (∀ B ∈ r, P B) →
      l.prod * r.prod = l.prod * Matrix.vecMulVec b a * r.prod := by
  intro l r hl hr hlP hrP
  induction l with
  | nil => exact (hl rfl).elim
  | cons A l ih =>
      cases l with
      | nil =>
          obtain ⟨B, r, rfl⟩ := List.exists_cons_of_ne_nil hr
          simp only [List.prod_cons, List.prod_nil, mul_one]
          rw [← Matrix.mul_assoc, hpair A B (hlP A (by simp))
            (hrP B (by simp)), Matrix.mul_assoc]
      | cons B l =>
          have htail : ∀ X ∈ B :: l, P X := by
            intro X hX
            exact hlP X (by simp [hX])
          have hih := ih (by simp) htail
          simpa only [List.prod_cons, Matrix.mul_assoc] using
            congrArg (fun X ↦ A * X) hih

/-- For specified witnesses, MPU unitarity and `simple2` recover `simple1`
without changing either witness.

The two- and three-site constant physical configurations give respectively
$x^2=\delta_{ij}$ and $x^3=\delta_{ij}$ for
$x=(a|W^{ij}|b)$.  These identities force $x=\delta_{ij}$.

Source: arXiv:1703.09188, Definition III.2 and the corollary following
Proposition III.3, lines 363--374 and 442--446. -/
theorem IsMPU.simple1_of_simple2_supplied {U : MPOTensor d D} (hU : IsMPU U)
    (a b : Fin (D * D) → ℂ)
    (h₂ : ∀ i j k l : Fin d,
      doubleLayerTensor U i j * doubleLayerTensor U k l =
        doubleLayerTensor U i j * Matrix.vecMulVec b a *
          doubleLayerTensor U k l) :
    ∀ i j : Fin d,
      a ⬝ᵥ (doubleLayerTensor U i j *ᵥ b) = if i = j then 1 else 0 := by
  classical
  let P : Matrix (Fin (D * D)) (Fin (D * D)) ℂ → Prop :=
    fun A ↦ ∃ i j, A = doubleLayerTensor U i j
  have hpair : ∀ A B, P A → P B →
      A * B = A * Matrix.vecMulVec b a * B := by
    rintro A B ⟨i, j, rfl⟩ ⟨k, l, rfl⟩
    exact h₂ i j k l
  have hpower (N : ℕ) (hN : 1 < N) (i j : Fin d) :
      (a ⬝ᵥ (doubleLayerTensor U i j *ᵥ b)) ^ N =
        if i = j then 1 else 0 := by
    let σ : Fin N → Fin d := fun _ ↦ i
    let τ : Fin N → Fin d := fun _ ↦ j
    have hentry := congrArg (fun M ↦ M σ τ)
      (show mpo (doubleLayerTensor U) N =
          (1 : Matrix (Fin N → Fin d) (Fin N → Fin d) ℂ) by
        rw [mpo_doubleLayerTensor, hU.conjTranspose_mpo_mul_mpo hN])
    rw [mpo_apply, mpoMatrixEntry, evalWord_ofFn] at hentry
    let l := List.ofFn (fun _ : Fin N ↦ doubleLayerTensor U i j)
    have hlP : ∀ A ∈ l, P A := by
      intro A hA
      simp only [l, List.mem_ofFn] at hA
      obtain ⟨x, rfl⟩ := hA
      exact ⟨i, j, rfl⟩
    have htrace := trace_listProd a b P hpair l (by simp [l, hN]) hlP
    rw [htrace] at hentry
    have hστ : σ = τ ↔ i = j := by
      constructor
      · intro h
        exact congrFun h ⟨0, by omega⟩
      · intro h
        subst j
        rfl
    simpa [l, σ, τ, List.map_ofFn, List.prod_ofFn, Matrix.one_apply, hστ] using hentry
  intro i j
  let x := a ⬝ᵥ (doubleLayerTensor U i j *ᵥ b)
  have hx2 : x ^ 2 = if i = j then 1 else 0 := hpower 2 (by omega) i j
  have hx3 : x ^ 3 = if i = j then 1 else 0 := hpower 3 (by omega) i j
  by_cases hij : i = j
  · rw [ite_eq_left hij] at hx2 hx3 ⊢
    have hx3' : x ^ 2 * x = 1 := by simpa [pow_succ] using hx3
    rw [hx2, one_mul] at hx3'
    exact hx3'
  · rw [ite_eq_right hij] at hx2 hx3 ⊢
    exact sq_eq_zero_iff.mp hx2

/-- For an MPU, witnesses satisfying `simple2` automatically satisfy
`simple1` with the same witnesses.

Source: arXiv:1703.09188, corollary following Proposition III.3,
lines 442--446. -/
theorem IsMPU.isMPUSimple_of_simple2 {U : MPOTensor d D} (hU : IsMPU U)
    (a b : Fin (D * D) → ℂ)
    (h₂ : ∀ i j k l : Fin d,
      doubleLayerTensor U i j * doubleLayerTensor U k l =
        doubleLayerTensor U i j * Matrix.vecMulVec b a *
          doubleLayerTensor U k l) :
    IsMPUSimple U :=
  ⟨a, b, hU.simple1_of_simple2_supplied a b h₂, h₂⟩

/-- MPU simplicity is preserved by blocking an already simple tensor by any
positive factor.

This is the multiplicative iterated-blocking preservation step used in
Proposition III.3 of arXiv:1703.09188.  After canonical reindexing it applies
at direct lengths \(kL\); the all-\(k' \geq k\) direct-block conclusion is
proved separately below, without a divisibility assumption. -/
theorem IsMPUSimple.blockTensor {U : MPOTensor d D} (hU : IsMPUSimple U)
    (L : ℕ) (hL : 0 < L) : IsMPUSimple (MPOTensor.blockTensor U L) := by
  classical
  obtain ⟨a, b, h₁, h₂⟩ := hU
  let P : Matrix (Fin (D * D)) (Fin (D * D)) ℂ → Prop :=
    fun A ↦ ∃ i j, A = doubleLayerTensor U i j
  have hpair : ∀ A B, P A → P B →
      A * B = A * Matrix.vecMulVec b a * B := by
    rintro A B ⟨i, j, rfl⟩ ⟨k, l, rfl⟩
    exact h₂ i j k l
  refine ⟨a, b, ?_, ?_⟩
  · intro I J
    rw [doubleLayerTensor_blockTensor, blockTensor_apply]
    simp only [Kraus.wordOfBlock]
    rw [MPOTensor.evalWord_ofFn]
    let l := List.ofFn (fun k : Fin L ↦
      doubleLayerTensor U (Kraus.decodeBlock d L I k)
        (Kraus.decodeBlock d L J k))
    have hl : l ≠ [] := by simp [l, Nat.ne_of_gt hL]
    have hlP : ∀ A ∈ l, P A := by
      intro A hA
      simp only [l, List.mem_ofFn] at hA
      obtain ⟨k, rfl⟩ := hA
      exact ⟨_, _, rfl⟩
    rw [sandwich_listProd a b P hpair l hl hlP]
    simp only [l, List.map_ofFn, List.prod_ofFn, Function.comp_apply, h₁]
    by_cases hIJ : I = J
    · subst J
      simp
    · rw [ite_eq_right hIJ]
      have hpoint : ∃ k : Fin L,
          Kraus.decodeBlock d L I k ≠ Kraus.decodeBlock d L J k := by
        by_contra h
        apply hIJ
        exact (Kraus.decodeBlockEquiv d L).injective
          (funext fun k ↦ not_ne_iff.mp (not_exists.mp h k))
      obtain ⟨k, hk⟩ := hpoint
      apply Finset.prod_eq_zero (Finset.mem_univ k)
      simp [hk]
  · intro I J K M
    rw [doubleLayerTensor_blockTensor, blockTensor_apply, blockTensor_apply]
    simp only [Kraus.wordOfBlock]
    rw [MPOTensor.evalWord_ofFn, MPOTensor.evalWord_ofFn]
    apply listProd_mul_eq_listProd_mul_rankOne_mul a b P hpair
    · simp [Nat.ne_of_gt hL]
    · simp [Nat.ne_of_gt hL]
    · intro A hA
      simp only [List.mem_ofFn] at hA
      obtain ⟨k, rfl⟩ := hA
      exact ⟨_, _, rfl⟩
    · intro A hA
      simp only [List.mem_ofFn] at hA
      obtain ⟨k, rfl⟩ := hA
      exact ⟨_, _, rfl⟩

/-- Supplied `simple2` witnesses persist when a direct block is extended by
one site; the suffix/prefix windows preserve the exact witnesses.

Source: arXiv:1703.09188, corollary following Proposition III.3, lines
442--446. -/
theorem blockTensor_succ_simple2_of_supplied
    {d D : ℕ} {U : MPOTensor d D} {k : ℕ}
    (a b : Fin (D * D) → ℂ)
    (h₂ : ∀ i j m l : Fin (MPSTensor.blockPhysDim d k),
      doubleLayerTensor (blockTensor U k) i j *
          doubleLayerTensor (blockTensor U k) m l =
        doubleLayerTensor (blockTensor U k) i j * Matrix.vecMulVec b a *
          doubleLayerTensor (blockTensor U k) m l) :
    ∀ I J K L : Fin (MPSTensor.blockPhysDim d (k + 1)),
      doubleLayerTensor (blockTensor U (k + 1)) I J *
          doubleLayerTensor (blockTensor U (k + 1)) K L =
        doubleLayerTensor (blockTensor U (k + 1)) I J * Matrix.vecMulVec b a *
          doubleLayerTensor (blockTensor U (k + 1)) K L := by
  classical
  let W := doubleLayerTensor U
  let suffixIndex (I : Fin (Kraus.blockPhysDim d (k + 1))) :
      Fin (Kraus.blockPhysDim d k) :=
    (Kraus.decodeBlockEquiv d k).symm
      (fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) I x.succ)
  let prefixIndex (I : Fin (Kraus.blockPhysDim d (k + 1))) :
      Fin (Kraus.blockPhysDim d k) :=
    (Kraus.decodeBlockEquiv d k).symm
      (fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) I x.castSucc)
  have hmiddle (I J K L : Fin (Kraus.blockPhysDim d (k + 1))) :
      evalWord W
          (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) I x.succ)
          (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) J x.succ) *
        evalWord W
          (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) K x.castSucc)
          (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) L x.castSucc) =
      evalWord W
          (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) I x.succ)
          (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) J x.succ) *
        Matrix.vecMulVec b a *
          evalWord W
            (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) K x.castSucc)
            (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) L x.castSucc) := by
    have h := h₂ (suffixIndex I) (suffixIndex J) (prefixIndex K) (prefixIndex L)
    simpa only [doubleLayerTensor_blockTensor, blockTensor_apply,
      Kraus.wordOfBlock, Kraus.decodeBlock_decodeBlockEquiv_symm,
      W, suffixIndex, prefixIndex] using h
  have hfirst (I J : Fin (Kraus.blockPhysDim d (k + 1))) :
      evalWord W (List.ofFn (Kraus.decodeBlock d (k + 1) I))
          (List.ofFn (Kraus.decodeBlock d (k + 1) J)) =
        W (Kraus.decodeBlock d (k + 1) I 0)
            (Kraus.decodeBlock d (k + 1) J 0) *
          evalWord W
            (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) I x.succ)
            (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) J x.succ) := by
    rw [List.ofFn_succ, List.ofFn_succ, evalWord_cons]
  have hlast (I J : Fin (Kraus.blockPhysDim d (k + 1))) :
      evalWord W (List.ofFn (Kraus.decodeBlock d (k + 1) I))
          (List.ofFn (Kraus.decodeBlock d (k + 1) J)) =
        evalWord W
            (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) I x.castSucc)
            (List.ofFn fun x : Fin k ↦ Kraus.decodeBlock d (k + 1) J x.castSucc) *
          W (Kraus.decodeBlock d (k + 1) I (Fin.last k))
            (Kraus.decodeBlock d (k + 1) J (Fin.last k)) := by
    rw [List.ofFn_succ', List.ofFn_succ', List.concat_eq_append,
      List.concat_eq_append, evalWord_append W _ _ _ _ (by simp)]
    simp
  intro I J K L
  simp only [doubleLayerTensor_blockTensor, blockTensor_apply,
    Kraus.wordOfBlock]
  rw [hfirst I J, hlast K L]
  have h := congrArg
    (fun X ↦ W (Kraus.decodeBlock d (k + 1) I 0)
        (Kraus.decodeBlock d (k + 1) J 0) * X *
      W (Kraus.decodeBlock d (k + 1) K (Fin.last k))
        (Kraus.decodeBlock d (k + 1) L (Fin.last k)))
    (hmiddle I J K L)
  simpa only [Matrix.mul_assoc] using h

/-- If a positive direct block of an MPU is simple, then the direct block one
site longer is simple with the same witnesses.

The `simple2` contraction is applied to the suffix of the first blocked word
and the prefix of the second blocked word, so the original order of all local
letters is preserved.  MPU unitarity then recovers `simple1` for those same
witnesses.

Source: arXiv:1703.09188, corollary following Proposition III.3,
lines 442--446. -/
theorem IsMPU.blockTensor_succ_isMPUSimple {U : MPOTensor d D} (hU : IsMPU U)
    {k : ℕ} (hk : 0 < k) (hsimple : IsMPUSimple (MPOTensor.blockTensor U k)) :
    IsMPUSimple (MPOTensor.blockTensor U (k + 1)) := by
  obtain ⟨a, b, _, h₂⟩ := hsimple
  have h₂succ := blockTensor_succ_simple2_of_supplied (a := a) (b := b) h₂
  exact (hU.blockTensor (k + 1) (by omega)).isMPUSimple_of_simple2 a b h₂succ

/-- Once a positive direct blocking of an MPU is simple, every longer direct
blocking is simple; no divisibility assumption on the two lengths is needed.

Source: arXiv:1703.09188, corollary following Proposition III.3,
lines 442--446. -/
theorem IsMPU.blockTensor_isMPUSimple_of_le {U : MPOTensor d D} (hU : IsMPU U)
    {k k' : ℕ} (hk : 0 < k) (hkk' : k ≤ k')
    (hsimple : IsMPUSimple (MPOTensor.blockTensor U k)) :
    IsMPUSimple (MPOTensor.blockTensor U k') := by
  obtain ⟨r, rfl⟩ := Nat.exists_eq_add_of_le hkk'
  clear hkk'
  induction r with
  | zero => simpa using hsimple
  | succ r ih =>
      rw [Nat.add_succ]
      exact hU.blockTensor_succ_isMPUSimple (by omega) ih

private theorem IsMPU.normalized_fixed_points_simple1_of_stabilization
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U)
    {bound : ℕ}
    (data : Matrix.StabilizedRankOneData
      (transferMatrix (Kraus.transferMap U.normalizedFlattening)) bound) :
    ∃ J : ℕ, 0 < J ∧ ∃ Φ ρ : Fin (D * D) → ℂ,
      Φ ⬝ᵥ ρ = 1 ∧
      normalizedDiagonal (doubleLayerTensor U) ^ J = Matrix.vecMulVec ρ Φ ∧
      normalizedDiagonal (doubleLayerTensor U) *ᵥ ρ = ρ ∧
      Matrix.vecMul Φ (normalizedDiagonal (doubleLayerTensor U)) = Φ ∧
      ∀ i j : Fin d,
        Φ ⬝ᵥ (doubleLayerTensor U i j *ᵥ ρ) = if i = j then 1 else 0 := by
  classical
  let J := data.exponent
  let E := normalizedDiagonal (doubleLayerTensor U)
  let ρ : Fin (D * D) → ℂ := fun i ↦ data.right (finProdFinEquiv.symm i)
  let Φ : Fin (D * D) → ℂ := fun i ↦ data.left (finProdFinEquiv.symm i)
  let P := Matrix.vecMulVec ρ Φ
  have hEPow : E ^ J = P := by
    calc
      E ^ J = normalizedDiagonal
          (doubleLayerTensor (MPOTensor.blockTensor U J)) := by
        simp only [E, doubleLayerTensor_blockTensor, normalizedDiagonal_blockTensor]
      _ = P := by
        rw [normalizedDiagonal_doubleLayerTensor_blockTensor, data.power_eq]
        rfl
  have hpair : Φ ⬝ᵥ ρ = 1 := by
    change (∑ i : Fin (D * D),
      data.left (finProdFinEquiv.symm i) * data.right (finProdFinEquiv.symm i)) = 1
    calc
      _ = ∑ ij : Fin D × Fin D, data.left ij * data.right ij := by
        symm
        simpa using Equiv.sum_comp
          (finProdFinEquiv : Fin D × Fin D ≃ Fin (D * D))
          (fun i ↦ data.left (finProdFinEquiv.symm i) *
            data.right (finProdFinEquiv.symm i))
      _ = 1 := by simpa [dotProduct, mul_comm] using data.pairing_eq_one
  have hErho : E *ᵥ ρ = ρ := by
    rw [show E = (transferMatrix
      (Kraus.transferMap U.normalizedFlattening)).submatrix
        finProdFinEquiv.symm finProdFinEquiv.symm by
      exact normalizedDiagonal_doubleLayerTensor U]
    rw [Matrix.submatrix_mulVec_equiv]
    simp only [Equiv.symm_symm]
    have hρ : ρ ∘ finProdFinEquiv = data.right := by
      funext i
      change data.right (finProdFinEquiv.symm (finProdFinEquiv i)) = data.right i
      rw [Equiv.symm_apply_apply]
    rw [hρ, data.right_fixed]
    rfl
  have hEΦ : Matrix.vecMul Φ E = Φ := by
    rw [show E = (transferMatrix
      (Kraus.transferMap U.normalizedFlattening)).submatrix
        finProdFinEquiv.symm finProdFinEquiv.symm by
      exact normalizedDiagonal_doubleLayerTensor U]
    rw [Matrix.submatrix_vecMul_equiv]
    simp only [Equiv.symm_symm]
    have hΦ : Φ ∘ finProdFinEquiv = data.left := by
      funext i
      change data.left (finProdFinEquiv.symm (finProdFinEquiv i)) = data.left i
      rw [Equiv.symm_apply_apply]
    rw [hΦ, data.left_fixed]
    rfl
  have hEP : E * P = P := by
    rw [show P = Matrix.vecMulVec ρ Φ by rfl, Matrix.mul_vecMulVec, hErho]
  have htraceP : Matrix.trace P = 1 := by
    rw [show P = Matrix.vecMulVec ρ Φ by rfl, Matrix.trace_vecMulVec,
      dotProduct_comm, hpair]
  refine ⟨J, data.exponent_pos, Φ, ρ, hpair, hEPow, hErho, hEΦ, ?_⟩
  intro i j
  let R := residualSlice (doubleLayerTensor U) (Matrix.single j i 1)
  have hRtrace : Matrix.trace (R * P) = 0 := by
    let isResidual : Fin (J + 1) → Bool := Fin.cases true (fun _ ↦ false)
    let X : Fin (J + 1) → Matrix (Fin d) (Fin d) ℂ :=
      Fin.cases (Matrix.single j i 1) (fun _ ↦ 0)
    have hmixed : ∃ k, isResidual k = true := ⟨0, rfl⟩
    have htrace := hU.trace_prod_mixedResidualFactor_doubleLayerTensor_eq_zero_of_pos
      (Nat.succ_pos J) isResidual X hmixed
    rw [← hEPow]
    simpa [R, E, isResidual, X, mixedResidualFactor, List.ofFn_succ,
      List.ofFn_const, List.prod_replicate] using htrace
  have hscalar (M : Matrix (Fin (D * D)) (Fin (D * D)) ℂ) :
      Φ ⬝ᵥ (M *ᵥ ρ) = Matrix.trace (M * P) := by
    rw [show P = Matrix.vecMulVec ρ Φ by rfl, Matrix.mul_vecMulVec,
      Matrix.trace_vecMulVec, dotProduct_comm]
  rw [entry_eq_diagonal_add_residual (doubleLayerTensor U) i j]
  change Φ ⬝ᵥ (((if i = j then (1 : ℂ) else 0) • E + R) *ᵥ ρ) = _
  rw [hscalar, Matrix.add_mul, Matrix.smul_mul, Matrix.trace_add,
    Matrix.trace_smul, hEP, htraceP, hRtrace]
  simp

private theorem IsMPU.exists_normalized_fixed_points_pow
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U) :
    ∃ J : ℕ, 0 < J ∧ ∃ Φ ρ : Fin (D * D) → ℂ,
      Φ ⬝ᵥ ρ = 1 ∧
      normalizedDiagonal (doubleLayerTensor U) ^ J = Matrix.vecMulVec ρ Φ ∧
      normalizedDiagonal (doubleLayerTensor U) *ᵥ ρ = ρ ∧
      Matrix.vecMul Φ (normalizedDiagonal (doubleLayerTensor U)) = Φ ∧
      ∀ i j : Fin d,
        Φ ⬝ᵥ (doubleLayerTensor U i j *ᵥ ρ) = if i = j then 1 else 0 := by
  by_cases hD : D = 1
  · subst D
    exact hU.normalized_fixed_points_simple1_of_stabilization
      hU.normalizedTransferStabilization_fin_one
  · have hDpos : 0 < D := NeZero.pos D
    have hDgt : 1 < D := by omega
    exact hU.normalized_fixed_points_simple1_of_stabilization
      (hU.normalizedTransferStabilization hDgt)

/-- Every MPU has normalized left and right fixed vectors satisfying the source
`simple1` contraction, without requiring the unblocked tensor itself to satisfy
`simple2`.

Source: arXiv:1703.09188, Corollary `simple1`, lines 429--438. -/
theorem IsMPU.exists_normalized_fixed_points_simple1
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U) :
    ∃ Φ ρ : Fin (D * D) → ℂ,
      Φ ⬝ᵥ ρ = 1 ∧
      normalizedDiagonal (doubleLayerTensor U) *ᵥ ρ = ρ ∧
      Matrix.vecMul Φ (normalizedDiagonal (doubleLayerTensor U)) = Φ ∧
      ∀ i j : Fin d,
        Φ ⬝ᵥ (doubleLayerTensor U i j *ᵥ ρ) = if i = j then 1 else 0 := by
  obtain ⟨_, _, Φ, ρ, hpair, _, hρ, hΦ, hsimple1⟩ := hU.exists_normalized_fixed_points_pow
  exact ⟨Φ, ρ, hpair, hρ, hΦ, hsimple1⟩

/-- The source `simple1` contraction holds for every MPU, without requiring
the unblocked tensor itself to satisfy `simple2`.

Source: arXiv:1703.09188, Corollary `simple1`, lines 429--438. -/
theorem IsMPU.simple1 [NeZero d] [NeZero D] {U : MPOTensor d D}
    (hU : IsMPU U) :
    ∃ a b : Fin (D * D) → ℂ, ∀ i j : Fin d,
      a ⬝ᵥ (doubleLayerTensor U i j *ᵥ b) = if i = j then 1 else 0 := by
  obtain ⟨Φ, ρ, _, _, _, hsimple1⟩ := hU.exists_normalized_fixed_points_simple1
  exact ⟨Φ, ρ, hsimple1⟩

section TraceCharacter

private theorem pow_succ_mem_nonUnitalSubalgebra
    {A : Type*} [Semiring A] [Module ℂ A] [IsScalarTower ℂ A A] [SMulCommClass ℂ A A]
    (S : NonUnitalSubalgebra ℂ A) {x : A} (hx : x ∈ S) (m : ℕ) : x ^ (m + 1) ∈ S := by
  induction m with
  | zero => simpa using hx
  | succ m ih => simpa [pow_succ] using S.mul_mem ih hx

/-- A matrix having a positive power equal to a normalized rank-one projector
with the same right fixed vector has trace one: its difference from the
projector is nilpotent. -/
private theorem trace_eq_one_of_pow_eq_vecMulVec {n : Type*} [Fintype n] [DecidableEq n]
    (E : Matrix n n ℂ) {J : ℕ} (hJ : 0 < J) (ρ Φ : n → ℂ) (hpair : Φ ⬝ᵥ ρ = 1)
    (hpow : E ^ J = Matrix.vecMulVec ρ Φ) (hρ : E *ᵥ ρ = ρ) : Matrix.trace E = 1 := by
  set p := Matrix.vecMulVec ρ Φ with hp
  have hEp : ∀ k : ℕ, E ^ k * p = p := by
    intro k
    induction k with
    | zero => simp
    | succ k ih => rw [pow_succ, mul_assoc, hp, Matrix.mul_vecMulVec, hρ, ← hp, ih]
  have hpE : p * E = p := by
    rw [← hpow, ← pow_succ, pow_succ', hpow]
    simpa using hEp 1
  have hpp : p * p = p := by
    rw [hp, Matrix.vecMulVec_mul_vecMulVec, hpair, one_smul]
  have hsub : ∀ m : ℕ, (E - p) ^ (m + 1) = E ^ (m + 1) - p := by
    intro m
    induction m with
    | zero => simp
    | succ m ih =>
        rw [pow_succ (E - p), ih, sub_mul, mul_sub, mul_sub, ← pow_succ E (m + 1), hEp, hpE,
          hpp, sub_self, sub_zero]
  obtain ⟨m, rfl⟩ : ∃ m, J = m + 1 := ⟨J - 1, by omega⟩
  have hnil : IsNilpotent (E - p) := ⟨m + 1, by rw [hsub, hpow, sub_self]⟩
  have htr := (Matrix.isNilpotent_trace_of_isNilpotent hnil).eq_zero
  rw [Matrix.trace_sub, hp, Matrix.trace_vecMulVec, dotProduct_comm, hpair,
    sub_eq_zero] at htr
  exact htr

/-- The normalized double-layer diagonal of an MPU has trace one.

Source: arXiv:1703.09188, lines 397--409. -/
theorem IsMPU.trace_normalizedDiagonal_doubleLayerTensor
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U) :
    Matrix.trace (normalizedDiagonal (doubleLayerTensor U)) = 1 := by
  obtain ⟨J, hJ, Φ, ρ, hpair, hpow, hρ, _, _⟩ := hU.exists_normalized_fixed_points_pow
  exact trace_eq_one_of_pow_eq_vecMulVec _ hJ ρ Φ hpair hpow hρ

/-- Every double-layer letter of an MPU has trace equal to the Kronecker delta
of its physical indices.

Source: arXiv:1703.09188, equation `WIsom` and lines 405--410. -/
theorem IsMPU.trace_doubleLayerTensor
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U) (i j : Fin d) :
    Matrix.trace (doubleLayerTensor U i j) = if i = j then 1 else 0 := by
  rw [entry_eq_diagonal_add_residual (doubleLayerTensor U) i j, Matrix.trace_add,
    Matrix.trace_smul, hU.trace_normalizedDiagonal_doubleLayerTensor,
    hU.trace_residualSlice_doubleLayerTensor_eq_zero, smul_eq_mul, mul_one, add_zero]

/-- The trace of every nonempty word of double-layer letters of an MPU is the
product of the traces of its letters, namely the product of the sitewise
Kronecker deltas.

Source: arXiv:1703.09188, equations `UisUnitary` and `WIsom`, lines 327--335
and 390--395. -/
theorem IsMPU.trace_prod_ofFn_doubleLayerTensor
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U)
    {N : ℕ} (hN : 0 < N) (σ τ : Fin N → Fin d) :
    Matrix.trace (List.ofFn fun k ↦ doubleLayerTensor U (σ k) (τ k)).prod =
      ∏ k, Matrix.trace (doubleLayerTensor U (σ k) (τ k)) := by
  classical
  simp only [hU.trace_doubleLayerTensor]
  rw [Finset.prod_boole]
  rcases Nat.lt_or_ge 1 N with hN1 | hN1
  · have h := congrArg (fun M ↦ M σ τ)
      (show mpo (doubleLayerTensor U) N =
          (1 : Matrix (Fin N → Fin d) (Fin N → Fin d) ℂ) by
        rw [mpo_doubleLayerTensor, hU.conjTranspose_mpo_mul_mpo hN1])
    have htr : Matrix.trace (List.ofFn fun k ↦ doubleLayerTensor U (σ k) (τ k)).prod =
        if σ = τ then 1 else 0 := by
      simpa [mpo_apply, mpoMatrixEntry, evalWord_ofFn, Matrix.one_apply] using h
    rw [htr]
    simp [funext_iff]
  · obtain rfl : N = 1 := by omega
    simp only [List.ofFn_succ, List.ofFn_zero, List.prod_cons, List.prod_nil, mul_one]
    rw [hU.trace_doubleLayerTensor]
    simp

/-- The nonunital algebra generated by the double-layer letters `W^{ij}`.

Source: arXiv:1703.09188, equation `WIsom`, lines 390--395. -/
noncomputable def doubleLayerAlgebra (U : MPOTensor d D) :
    NonUnitalSubalgebra ℂ (Matrix (Fin (D * D)) (Fin (D * D)) ℂ) :=
  NonUnitalAlgebra.adjoin ℂ
    (Set.range fun ij : Fin d × Fin d ↦ doubleLayerTensor U ij.1 ij.2)

/-- Every double-layer letter lies in the double-layer algebra. -/
theorem doubleLayerTensor_mem_doubleLayerAlgebra (U : MPOTensor d D) (i j : Fin d) :
    doubleLayerTensor U i j ∈ doubleLayerAlgebra U :=
  NonUnitalAlgebra.subset_adjoin ℂ ⟨(i, j), rfl⟩

/-- The normalized double-layer diagonal lies in the double-layer algebra. -/
theorem normalizedDiagonal_mem_doubleLayerAlgebra (U : MPOTensor d D) :
    normalizedDiagonal (doubleLayerTensor U) ∈ doubleLayerAlgebra U := by
  rw [normalizedDiagonal, contractPhysical]
  refine (doubleLayerAlgebra U).smul_mem _ ?_
  refine sum_mem fun i _ ↦ sum_mem fun j _ ↦ ?_
  exact (doubleLayerAlgebra U).smul_mem _ (doubleLayerTensor_mem_doubleLayerAlgebra U i j)

private theorem IsMPU.trace_list_prod_of_mem_doubleLayerLetters
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U)
    (l : List (Matrix (Fin (D * D)) (Fin (D * D)) ℂ))
    (hl : ∀ A ∈ l, A ∈ Set.range fun ij : Fin d × Fin d ↦ doubleLayerTensor U ij.1 ij.2)
    (hne : l ≠ []) :
    Matrix.trace l.prod = (l.map Matrix.trace).prod := by
  classical
  have hX : ∀ k : Fin l.length, ∃ ij : Fin d × Fin d, doubleLayerTensor U ij.1 ij.2 = l[k] :=
    fun k ↦ hl l[k] (List.get_mem l k)
  choose ij hij using hX
  have hword : l = List.ofFn fun k ↦ doubleLayerTensor U (ij k).1 (ij k).2 := by
    calc
      l = List.ofFn (fun k ↦ l[k]) := (List.ofFn_get l).symm
      _ = _ := by
        congr 1
        funext k
        exact (hij k).symm
  have hpos : 0 < l.length := List.length_pos_iff.mpr hne
  calc
    Matrix.trace l.prod
        = Matrix.trace (List.ofFn fun k ↦ doubleLayerTensor U (ij k).1 (ij k).2).prod :=
      congrArg (fun xs ↦ Matrix.trace xs.prod) hword
    _ = ∏ k, Matrix.trace (doubleLayerTensor U (ij k).1 (ij k).2) :=
      hU.trace_prod_ofFn_doubleLayerTensor hpos (fun k ↦ (ij k).1) (fun k ↦ (ij k).2)
    _ = ((List.ofFn fun k ↦ doubleLayerTensor U (ij k).1 (ij k).2).map Matrix.trace).prod := by
      rw [List.map_ofFn, List.prod_ofFn]
      rfl
    _ = (l.map Matrix.trace).prod :=
      congrArg (fun xs ↦ (xs.map Matrix.trace).prod) hword.symm

/-- The trace is multiplicative on the algebra generated by the double-layer
letters of an MPU: it is the character sending every letter `W^{ij}` to the
Kronecker delta `δ_{ij}`. -/
theorem IsMPU.trace_mul_of_mem_doubleLayerAlgebra
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U)
    {a b : Matrix (Fin (D * D)) (Fin (D * D)) ℂ}
    (ha : a ∈ doubleLayerAlgebra U) (hb : b ∈ doubleLayerAlgebra U) :
    Matrix.trace (a * b) = Matrix.trace a * Matrix.trace b := by
  classical
  let S := Set.range fun ij : Fin d × Fin d ↦ doubleLayerTensor U ij.1 ij.2
  have hword : ∀ x ∈ Subsemigroup.closure S, ∀ y ∈ Subsemigroup.closure S,
      Matrix.trace (x * y) = Matrix.trace x * Matrix.trace y := by
    intro x hx y hy
    obtain ⟨l, hl, hlS, rfl⟩ := Subsemigroup.exists_nonempty_list_prod_of_mem_closure hx
    obtain ⟨m, hm, hmS, rfl⟩ := Subsemigroup.exists_nonempty_list_prod_of_mem_closure hy
    rw [← List.prod_append,
      hU.trace_list_prod_of_mem_doubleLayerLetters (l ++ m)
        (fun A hA ↦ (List.mem_append.mp hA).elim (hlS A) (hmS A)) (by simp [hl]),
      hU.trace_list_prod_of_mem_doubleLayerLetters l hlS hl,
      hU.trace_list_prod_of_mem_doubleLayerLetters m hmS hm, List.map_append, List.prod_append]
  change a ∈ (NonUnitalAlgebra.adjoin ℂ S).toSubmodule at ha
  change b ∈ (NonUnitalAlgebra.adjoin ℂ S).toSubmodule at hb
  rw [NonUnitalAlgebra.adjoin_eq_span] at ha hb
  induction ha using Submodule.span_induction with
  | mem x hx =>
      induction hb using Submodule.span_induction with
      | mem y hy => exact hword x hx y hy
      | zero => simp
      | add y z _ _ hy hz => simp only [Matrix.trace_add, hy, hz, mul_add]
      | smul c y _ hy =>
          simp only [Matrix.mul_smul, Matrix.trace_smul, hy, smul_eq_mul]
          ring
  | zero => simp
  | add x z _ _ hx hz => simp only [Matrix.trace_add, hx, hz, add_mul]
  | smul c x _ hx =>
      simp only [Matrix.smul_mul, Matrix.trace_smul, hx, smul_eq_mul]
      ring

/-- The traceless elements of the double-layer algebra of an MPU.  They form a
nonunital subalgebra because the trace is multiplicative there. -/
private noncomputable def doubleLayerTraceKernel
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U) :
    NonUnitalSubalgebra ℂ (Matrix (Fin (D * D)) (Fin (D * D)) ℂ) where
  carrier := {x | x ∈ doubleLayerAlgebra U ∧ Matrix.trace x = 0}
  add_mem' ha hb := ⟨add_mem ha.1 hb.1, by rw [Matrix.trace_add, ha.2, hb.2, add_zero]⟩
  zero_mem' := ⟨zero_mem _, by simp⟩
  mul_mem' ha hb :=
    ⟨mul_mem ha.1 hb.1, by rw [hU.trace_mul_of_mem_doubleLayerAlgebra ha.1 hb.1, ha.2, zero_mul]⟩
  smul_mem' c x hx :=
    ⟨(doubleLayerAlgebra U).smul_mem c hx.1, by rw [Matrix.trace_smul, hx.2, smul_zero]⟩

private theorem mem_doubleLayerTraceKernel
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U)
    {x : Matrix (Fin (D * D)) (Fin (D * D)) ℂ} :
    x ∈ doubleLayerTraceKernel hU ↔ x ∈ doubleLayerAlgebra U ∧ Matrix.trace x = 0 :=
  Iff.rfl

/-- Every MPU of positive physical and bond dimensions is simple after blocking
exactly `D²` sites, with witnesses the normalized fixed vectors `Φ` and `ρ`.

The trace is a character on the algebra generated by the double-layer letters.
Its kernel `𝒩` is a nil, hence nilpotent, subalgebra of index at most `D²`, and
the letters decompose as `W^{ij} = δ_{ij} p + n_{ij}` with `p = |ρ)(Φ|` a
positive power of the normalized diagonal and `n_{ij} ∈ 𝒩`, where `p 𝒩 p = 0`.
Hence every blocked letter of length `D²` is `δ p` plus an element of the
three-form span of `p` and `𝒩`, which gives `simple2`.

This sharpens arXiv:1703.09188, Proposition III.3(ii), lines 397--427, whose
blocking length is below `D⁴`, and completes the `D²` blocking claim sketched in
arXiv:1704.01943, Theorem 2. -/
theorem IsMPU.blockTensor_sq_isMPUSimple
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U) :
    IsMPUSimple (MPOTensor.blockTensor U (D * D)) := by
  classical
  obtain ⟨J, hJ, Φ, ρ, hpair, hpow, -, -, -⟩ := hU.exists_normalized_fixed_points_pow
  let p := Matrix.vecMulVec ρ Φ
  let 𝒜 := doubleLayerAlgebra U
  let 𝒩 := doubleLayerTraceKernel hU
  have hNpos : 0 < D * D := Nat.mul_pos (NeZero.pos D) (NeZero.pos D)
  have hpp : p * p = p := by
    simp only [p]
    rw [Matrix.vecMulVec_mul_vecMulVec, hpair, one_smul]
  have htrp : Matrix.trace p = 1 := by
    simp only [p]
    rw [Matrix.trace_vecMulVec, dotProduct_comm, hpair]
  have hpA : p ∈ 𝒜 := by
    obtain ⟨m, rfl⟩ : ∃ m, J = m + 1 := ⟨J - 1, by omega⟩
    change Matrix.vecMulVec ρ Φ ∈ 𝒜
    rw [← hpow]
    exact pow_succ_mem_nonUnitalSubalgebra 𝒜 (normalizedDiagonal_mem_doubleLayerAlgebra U) m
  have hpNp : ∀ a : 𝒩, p * (a : Matrix (Fin (D * D)) (Fin (D * D)) ℂ) * p = 0 := by
    intro a
    have ha := (mem_doubleLayerTraceKernel hU).mp a.property
    exact Matrix.rankOne_sandwich_eq_zero_of_trace p _ ρ Φ rfl
      (by rw [hU.trace_mul_of_mem_doubleLayerAlgebra ha.1 hpA, ha.2, zero_mul])
  have hnil : ∀ a : 𝒩, IsNilpotent (a : Matrix (Fin (D * D)) (Fin (D * D)) ℂ) := by
    intro a
    apply Matrix.isNilpotent_of_forall_trace_pow_eq_zero_of_one_lt
    intro N hN
    obtain ⟨m, rfl⟩ : ∃ m, N = m + 1 := ⟨N - 1, by omega⟩
    exact ((mem_doubleLayerTraceKernel hU).mp
      (pow_succ_mem_nonUnitalSubalgebra 𝒩 a.property m)).2
  have hvanish : ∀ l : List (Matrix (Fin (D * D)) (Fin (D * D)) ℂ),
      (∀ x ∈ l, x ∈ 𝒩) → l.length = D * D → l.prod = 0 := fun l hl hlen ↦
    𝒩.matrix_list_prod_eq_zero_of_forall_isNilpotent hnil l hl (by simpa using hlen)
  have hletter (i j : Fin d) :
      doubleLayerTensor U i j - (if i = j then (1 : ℂ) else 0) • p ∈ 𝒩 := by
    refine (mem_doubleLayerTraceKernel hU).mpr
      ⟨sub_mem (doubleLayerTensor_mem_doubleLayerAlgebra U i j) (𝒜.smul_mem _ hpA), ?_⟩
    rw [Matrix.trace_sub, Matrix.trace_smul, htrp, hU.trace_doubleLayerTensor]
    simp
  have hthree (I K : Fin (MPSTensor.blockPhysDim d (D * D))) :
      doubleLayerTensor (MPOTensor.blockTensor U (D * D)) I K -
          (if I = K then (1 : ℂ) else 0) • p ∈ threeFormSubmodule p 𝒩 := by
    let σ := Kraus.decodeBlock d (D * D) I
    let τ := Kraus.decodeBlock d (D * D) K
    let c : Fin (D * D) → ℂ := fun k ↦ if σ k = τ k then 1 else 0
    let S : Fin (D * D) → 𝒩 := fun k ↦
      ⟨doubleLayerTensor U (σ k) (τ k) - c k • p, hletter (σ k) (τ k)⟩
    have hword := ordered_prod_smul_projector_add_sub_mem_threeFormSubmodule
      p 𝒩 hpp hpNp hNpos hvanish c S
    have hentry : doubleLayerTensor (MPOTensor.blockTensor U (D * D)) I K =
        (List.ofFn fun k ↦
          c k • p + (S k : Matrix (Fin (D * D)) (Fin (D * D)) ℂ)).prod := by
      rw [doubleLayerTensor_blockTensor]
      simp only [blockTensor_apply, Kraus.wordOfBlock, MPOTensor.evalWord_ofFn]
      apply congrArg List.prod
      apply congrArg List.ofFn
      funext k
      simp [S, σ, τ]
    rw [hentry, ← diagonal_coeff_prod_eq I K]
    exact hword
  have hsimple2 : ∀ I K L M : Fin (MPSTensor.blockPhysDim d (D * D)),
      doubleLayerTensor (MPOTensor.blockTensor U (D * D)) I K *
          doubleLayerTensor (MPOTensor.blockTensor U (D * D)) L M =
        doubleLayerTensor (MPOTensor.blockTensor U (D * D)) I K * Matrix.vecMulVec ρ Φ *
          doubleLayerTensor (MPOTensor.blockTensor U (D * D)) L M := by
    intro I K L M
    set X := doubleLayerTensor (MPOTensor.blockTensor U (D * D)) I K
    set Y := doubleLayerTensor (MPOTensor.blockTensor U (D * D)) L M
    set x : ℂ := if I = K then 1 else 0
    set y : ℂ := if L = M then 1 else 0
    have hXY := mul_eq_mul_projector_mul_of_mem_threeFormSubmodule p 𝒩 hpp hpNp
      (hthree I K) (hthree L M)
    have hX : X = x • p + (X - x • p) := by abel
    have hY : Y = y • p + (Y - y • p) := by abel
    change X * Y = X * p * Y
    rw [hX, hY]
    generalize X - x • p = s at hXY ⊢
    generalize Y - y • p = t at hXY ⊢
    simp [Matrix.add_mul, Matrix.mul_add, hpp, hXY, mul_assoc]
  exact (hU.blockTensor (D * D) hNpos).isMPUSimple_of_simple2 Φ ρ hsimple2

/-- Every MPU of positive physical and bond dimensions is simple after blocking
any number `k ≥ D²` of sites.

This sharpens arXiv:1703.09188, Proposition III.3(ii), lines 397--427, and
completes the `D²` blocking claim sketched in arXiv:1704.01943, Theorem 2; the
passage to longer blocks is the corollary following Proposition III.3 in
arXiv:1703.09188, lines 442--446. -/
theorem IsMPU.blockTensor_isMPUSimple_of_sq_le
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U) {k : ℕ} (hk : D * D ≤ k) :
    IsMPUSimple (MPOTensor.blockTensor U k) :=
  hU.blockTensor_isMPUSimple_of_le (Nat.mul_pos (NeZero.pos D) (NeZero.pos D)) hk
    hU.blockTensor_sq_isMPUSimple

end TraceCharacter

/-- Simultaneous reindexing of both physical coordinates commutes entrywise with
formation of the double layer. This is the local coordinate identity used to compare
iterated and direct physical blockings. -/
theorem doubleLayerTensor_reindexPhysical {d' : ℕ}
    (e : Fin d' ≃ Fin d) (U : MPOTensor d D) (i j : Fin d') :
    doubleLayerTensor (reindexPhysical e U) i j = doubleLayerTensor U (e i) (e j) := by
  classical
  simp only [doubleLayerTensor_apply, reindexPhysical]
  rw [← e.sum_comp]
  rfl

/-- MPU simplicity is invariant under a bijective relabeling of the physical
basis.

Source: arXiv:1703.09188, Proposition III.3, where physical blocking indices
are identified canonically. -/
theorem IsMPUSimple.reindexPhysical {d' : ℕ} {U : MPOTensor d D}
    (hU : IsMPUSimple U) (e : Fin d' ≃ Fin d) :
    IsMPUSimple (reindexPhysical e U) := by
  obtain ⟨a, b, h₁, h₂⟩ := hU
  refine ⟨a, b, ?_, ?_⟩
  · intro i j
    rw [doubleLayerTensor_reindexPhysical]
    simpa [e.injective.eq_iff] using h₁ (e i) (e j)
  · intro i j k l
    simp only [doubleLayerTensor_reindexPhysical]
    exact h₂ (e i) (e j) (e k) (e l)

/-- Iterated MPO blocking, reindexed by the canonical grouping equivalence,
agrees with direct blocking at the product length.

Source: arXiv:1703.09188, Proposition III.3, lines 405--426. -/
theorem reindexPhysical_blockTensor_blockTensor
    (U : MPOTensor d D) (m n : ℕ) :
    reindexPhysical (MPSTensor.directIteratedBlockEquiv d m n)
        (MPOTensor.blockTensor (MPOTensor.blockTensor U m) n) =
      MPOTensor.blockTensor U (m * n) := by
  funext i j
  simp only [reindexPhysical, blockTensor_apply, Kraus.wordOfBlock]
  rw [evalWord_blockTensor_ofFn]
  change evalWord U
      (Kraus.flattenBlockedWord d m
        (Kraus.wordOfBlock (Kraus.blockPhysDim d m) n
          (MPSTensor.directToIteratedBlockIndex d m n i)))
      (Kraus.flattenBlockedWord d m
        (Kraus.wordOfBlock (Kraus.blockPhysDim d m) n
          (MPSTensor.directToIteratedBlockIndex d m n j))) =
    evalWord U (Kraus.wordOfBlock d (m * n) i)
      (Kraus.wordOfBlock d (m * n) j)
  have hi :=
    MPSTensor.flattenBlockedWord_wordOfBlock_directToIteratedBlockIndex d m n i
  have hj :=
    MPSTensor.flattenBlockedWord_wordOfBlock_directToIteratedBlockIndex d m n j
  change Kraus.flattenBlockedWord d m
      (Kraus.wordOfBlock (Kraus.blockPhysDim d m) n
        (MPSTensor.directToIteratedBlockIndex d m n i)) =
    Kraus.wordOfBlock d (m * n) i at hi
  change Kraus.flattenBlockedWord d m
      (Kraus.wordOfBlock (Kraus.blockPhysDim d m) n
        (MPSTensor.directToIteratedBlockIndex d m n j)) =
    Kraus.wordOfBlock d (m * n) j at hj
  rw [hi, hj]

/-- Every MPU of positive physical and bond dimensions is MPU-simple after
blocking exactly \(D^4\) sites.

Source: arXiv:1703.09188, proof of Proposition `prop:continuity-index`,
lines 747--752. -/
theorem IsMPU.blockTensor_pow_four_isMPUSimple
    [NeZero d] [NeZero D] {U : MPOTensor d D} (hU : IsMPU U) :
    IsMPUSimple (MPOTensor.blockTensor U (D ^ 4)) := by
  apply hU.blockTensor_isMPUSimple_of_sq_le
  rw [show D ^ 4 = (D * D) * (D * D) by ring]
  exact Nat.le_mul_of_pos_right _ (Nat.mul_pos (NeZero.pos D) (NeZero.pos D))

/-- Two MPUs, possibly with different physical and bond dimensions, have a
common positive direct blocking at which both are simple. This combines the
bounded simple blocking of arXiv:1703.09188, Proposition III.3(ii), with its
all-later-blockings corollary (lines 442--446). -/
theorem IsMPU.exists_common_blockTensor_isMPUSimple
    [NeZero d] [NeZero D] [NeZero e] [NeZero E]
    {U : MPOTensor d D} {V : MPOTensor e E} (hU : IsMPU U) (hV : IsMPU V) :
    ∃ k : ℕ, 0 < k ∧
      IsMPUSimple (MPOTensor.blockTensor U k) ∧
      IsMPUSimple (MPOTensor.blockTensor V k) := by
  refine ⟨D * D + E * E,
    Nat.lt_of_lt_of_le (Nat.mul_pos (NeZero.pos D) (NeZero.pos D)) (Nat.le_add_right _ _),
    hU.blockTensor_isMPUSimple_of_sq_le (Nat.le_add_right _ _),
    hV.blockTensor_isMPUSimple_of_sq_le (Nat.le_add_left _ _)⟩

/-- Three MPUs, possibly with different physical and bond dimensions, have a
common positive direct blocking at which all three are simple. This is the
finite three-tensor consequence of arXiv:1703.09188, Proposition III.3(ii)
and its all-later-blockings corollary (lines 442--446). -/
theorem IsMPU.exists_common_blockTensor_isMPUSimple_three
    [NeZero d] [NeZero D] [NeZero e] [NeZero E] [NeZero f] [NeZero F]
    {U : MPOTensor d D} {V : MPOTensor e E} {W : MPOTensor f F}
    (hU : IsMPU U) (hV : IsMPU V) (hW : IsMPU W) :
    ∃ k : ℕ, 0 < k ∧
      IsMPUSimple (MPOTensor.blockTensor U k) ∧
      IsMPUSimple (MPOTensor.blockTensor V k) ∧
      IsMPUSimple (MPOTensor.blockTensor W k) := by
  refine ⟨D * D + E * E + F * F,
    Nat.lt_of_lt_of_le (Nat.mul_pos (NeZero.pos D) (NeZero.pos D))
      (Nat.le_add_right_of_le (Nat.le_add_right _ _)),
    hU.blockTensor_isMPUSimple_of_sq_le (Nat.le_add_right_of_le (Nat.le_add_right _ _)),
    hV.blockTensor_isMPUSimple_of_sq_le (Nat.le_add_right_of_le (Nat.le_add_left _ _)),
    hW.blockTensor_isMPUSimple_of_sq_le (Nat.le_add_left _ _)⟩

end BlockingConstruction

end MPOTensor
