import TNLean.PEPS.AreaLaw.RegularizedPatchMinimum
set_option linter.hashCommand false
#print axioms TNLean.PEPS.norm_dependentRegionOperatorLift_mulVec_le
#print axioms TNLean.PEPS.continuous_dependentRegionOperatorLift
#print axioms TNLean.PEPS.regularizedPatchDomain
#print axioms TNLean.PEPS.regularizedPatchFilter
#print axioms TNLean.PEPS.regularizedPatchOperator
#print axioms TNLean.PEPS.regularizedPatchOutput
#print axioms TNLean.PEPS.regularizedPatchObjective
#print axioms TNLean.PEPS.isCompact_regularizedPatchDomain
#print axioms TNLean.PEPS.regularizedPatchDomain_nonempty
#print axioms TNLean.PEPS.continuousOn_regularizedPatchFilter
#print axioms TNLean.PEPS.continuousOn_regularizedPatchObjective
#print axioms TNLean.PEPS.exists_isMinOn_regularizedPatchObjective
#print axioms TNLean.PEPS.regularizedPatchFilter_norm_bounds
#print axioms TNLean.PEPS.regularizedPatchObjective_bounds
#print axioms TNLean.PEPS.regularizedPatchMinimum
#print axioms TNLean.PEPS.regularizedPatchObjective_eq_minimum
#print axioms TNLean.PEPS.regularizedPatchMinimum_bounds
#print axioms TNLean.PEPS.regularizedPatchObjective_pos
#print axioms TNLean.PEPS.regularizedPatchMinimum_pos
#print axioms TNLean.PEPS.normalizedRegularizedPatchOutput
#print axioms TNLean.PEPS.norm_normalizedRegularizedPatchOutput
#print axioms TNLean.PEPS.normalizedRegularizedPatchOutput_eq_minimum_smul
#print axioms TNLean.PEPS.regularizedPatchObjective_exp_bounds
#print axioms TNLean.PEPS.regularizedPatchMinimum_exp_bounds
