/-
Copyright (c) 2025 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.Channel.Schwarz.PositiveOnAbelian

/-!
# Schwarz inequality for normal operators

This file records a direct CP/Kraus corollary of Kadison–Schwarz for normal
operators and states the abstract positive-map version of Wolf Proposition 5.1.

## Main results

* `KadisonSchwarz.kadison_schwarz_normal_cp`
* `KadisonSchwarz.kadison_schwarz_normal_cp_le`
* `KadisonSchwarz.schwarz_inequality_normal_operator`

## References

* [M. Wolf, *Quantum Channels & Operations: Guided Tour*, Proposition 5.1][Wolf2012QChannels]
-/

open scoped Matrix ComplexOrder MatrixOrder
open Matrix Finset

namespace KadisonSchwarz

variable {d D : ℕ}

@[simp] theorem krausAdjointMap_conjTranspose
    (K : Fin d → Matrix (Fin D) (Fin D) ℂ)
    (X : Matrix (Fin D) (Fin D) ℂ) :
    krausAdjointMap K (Xᴴ) = (krausAdjointMap K X)ᴴ := by
  simp [krausAdjointMap, Matrix.conjTranspose_sum, Matrix.conjTranspose_mul, Matrix.mul_assoc]

/-- Kadison-Schwarz for adjoint Kraus maps, restricted to normal inputs.

This is the CP/Kraus special case of Wolf Proposition 5.1. The normality
assumption is included to match the statement of the proposition, although the
proof does not use it since Kadison-Schwarz already holds for arbitrary inputs. -/
theorem kadison_schwarz_normal_cp (K : Fin d → Matrix (Fin D) (Fin D) ℂ)
    (h_tp : IsTPKraus K)
    (A : Matrix (Fin D) (Fin D) ℂ)
    (_hNormal : Aᴴ * A = A * Aᴴ) :
    (krausAdjointMap K (Aᴴ * A) - krausAdjointMap K (Aᴴ) * krausAdjointMap K A).PosSemidef := by
  simpa using kadison_schwarz_adjoint K h_tp A

/-- Loewner-order reformulation of `kadison_schwarz_normal_cp`. -/
theorem kadison_schwarz_normal_cp_le (K : Fin d → Matrix (Fin D) (Fin D) ℂ)
    (h_tp : IsTPKraus K)
    (A : Matrix (Fin D) (Fin D) ℂ)
    (hNormal : Aᴴ * A = A * Aᴴ) :
    krausAdjointMap K (Aᴴ) * krausAdjointMap K A ≤ krausAdjointMap K (Aᴴ * A) := by
  rw [Matrix.le_iff]
  exact kadison_schwarz_normal_cp K h_tp A hNormal

/-- Wolf Prop. 5.1: Schwarz inequality for normal operators under positive maps.

The proof is delegated to the commutative-domain scaffold in
`TNLean.Channel.Schwarz.PositiveOnAbelian`: one restricts `T` to the
commutative `*`-subalgebra generated by `1`, `A`, `Aᴴ`, and `Aᴴ * A`, invokes
Wolf Prop. 1.6 there, and then reads the result as a Loewner-order inequality. -/
theorem schwarz_inequality_normal_operator
    (T : Matrix (Fin D) (Fin D) ℂ →ₗ[ℂ] Matrix (Fin D) (Fin D) ℂ)
    (hPos : IsPositiveMap T)
    (hSub : T 1 ≤ (1 : Matrix (Fin D) (Fin D) ℂ))
    (A : Matrix (Fin D) (Fin D) ℂ)
    (hNormal : Aᴴ * A = A * Aᴴ) :
    (T (Aᴴ * A) - T (Aᴴ) * T A).PosSemidef := by
  rw [← Matrix.le_iff]
  exact PositiveOnAbelian.map_conjTranspose_mul_map_le_of_normal_of_subunital hPos hNormal hSub

end KadisonSchwarz
