/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Basic.Complex.Basic
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.FiniteDimensional.Basic
import Mathlib.Data.Fintype.Pi
import Mathlib.Algebra.BigOperators.Group.Finset.Piecewise

/-!
# The common ground space of independent virtual Bell bonds

On a finite collection of virtual bonds, impose the Bell-vector condition on
every bond slice obtained by fixing the other virtual coordinates. Their
common ground space is exactly the line generated by the product of the Bell
vectors. Bond dimensions may vary and may vanish. With a zero-dimensional
bond, the whole configuration space is empty and the physical vector space
is zero, so the same span formula remains valid.

Source: CPGSV21, arXiv:2011.12127, the independent-bond ground-state argument
preceding equation `eq:4:deformed-parent-1`, lines 2017–2044. This is its
purely virtual part; no physical injectivity assumption is used.
-/

open scoped BigOperators

namespace TNLean.PEPS

variable {E : Type*} [Fintype E] [DecidableEq E]

/-- The two endpoint labels on each virtual bond. Source: CPGSV21,
the virtual Bell-pair construction, lines 2017–2028. -/
abbrev VirtualBondConfig (D : E → ℕ) := (e : E) → Fin (D e) × Fin (D e)

/-- The unnormalized Bell vector on one virtual bond. Source: CPGSV21,
the maximally entangled bond in the independent-bond construction,
lines 2017–2028. -/
def virtualBondBell (D : E → ℕ) (e : E) : Fin (D e) × Fin (D e) → ℂ :=
  fun p => if p.1 = p.2 then 1 else 0

/-- The product of the unnormalized virtual Bell vectors.
Source: CPGSV21, the vector Ω in the independent-bond construction,
lines 2017–2028. -/
def virtualBondProduct (D : E → ℕ) : VirtualBondConfig D → ℂ :=
  fun ζ => ∏ e, virtualBondBell D e (ζ e)

/-- Fix all endpoint labels except those on one bond.
Source: the local virtual-bond condition in CPGSV21, lines 2033–2044. -/
def virtualBondSlice (D : E → ℕ) (e : E) (ζ : VirtualBondConfig D) :
    (VirtualBondConfig D → ℂ) →ₗ[ℂ] (Fin (D e) × Fin (D e) → ℂ) where
  toFun ψ p := ψ (Function.update ζ e p)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- The common space defined by the Bell condition on every fixed-complement
slice. Source: the independent-bond parent condition in CPGSV21,
lines 2033–2044. -/
def virtualBondGroundSpace (D : E → ℕ) : Submodule ℂ (VirtualBondConfig D → ℂ) :=
  ⨅ e, ⨅ ζ, (Submodule.span ℂ {virtualBondBell D e}).comap (virtualBondSlice D e ζ)

omit [Fintype E] in
/-- Membership means precisely the Bell condition on every bond slice.
Source: the independent-bond parent condition in CPGSV21, lines 2033–2044. -/
theorem mem_virtualBondGroundSpace_iff (D : E → ℕ) (ψ : VirtualBondConfig D → ℂ) :
    ψ ∈ virtualBondGroundSpace D ↔
      ∀ e ζ, virtualBondSlice D e ζ ψ ∈ Submodule.span ℂ {virtualBondBell D e} := by
  simp only [virtualBondGroundSpace, Submodule.mem_iInf, Submodule.mem_comap]

/-- Changing one pair of endpoint labels separates its Bell factor from
the other factors. Source: CPGSV21, product Bell vector, lines 2017–2028. -/
theorem virtualBondProduct_update (D : E → ℕ) (ζ : VirtualBondConfig D)
    (e : E) (p : Fin (D e) × Fin (D e)) :
    virtualBondProduct D (Function.update ζ e p) =
      virtualBondBell D e p * ∏ f ∈ Finset.univ.erase e, virtualBondBell D f (ζ f) := by
  unfold virtualBondProduct
  rw [← Finset.mul_prod_erase _ _ (Finset.mem_univ e)]
  simp only [Function.update_self]
  congr 1
  apply Finset.prod_congr rfl
  intro f hf
  rw [Function.update_of_ne (Finset.ne_of_mem_erase hf)]

/-- The product Bell vector satisfies every single-bond slice condition.
Source: CPGSV21, independent-bond frustration freeness, lines 2033–2044. -/
theorem virtualBondProduct_mem_virtualBondGroundSpace (D : E → ℕ) :
    virtualBondProduct D ∈ virtualBondGroundSpace D := by
  rw [mem_virtualBondGroundSpace_iff]
  intro e ζ
  apply Submodule.mem_span_singleton.mpr
  refine ⟨∏ f ∈ Finset.univ.erase e, virtualBondBell D f (ζ f), ?_⟩
  funext p
  change _ * virtualBondBell D e p = virtualBondProduct D (Function.update ζ e p)
  rw [virtualBondProduct_update, mul_comm]

omit [Fintype E] in
/-- A common virtual ground vector vanishes whenever the endpoint labels
of some bond disagree. Source: CPGSV21, the independent Bell-bond
constraint in the ground-state argument, lines 2033–2044. -/
theorem eq_zero_of_mem_virtualBondGroundSpace_off_diagonal
    (D : E → ℕ) {ψ : VirtualBondConfig D → ℂ} (hψ : ψ ∈ virtualBondGroundSpace D)
    (ζ : VirtualBondConfig D) (e : E) (he : (ζ e).1 ≠ (ζ e).2) : ψ ζ = 0 := by
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp
    ((mem_virtualBondGroundSpace_iff D ψ).mp hψ e ζ)
  have h := congrFun hc (ζ e)
  simpa only [Pi.smul_apply, virtualBondBell, ite_eq_right he, smul_zero,
    virtualBondSlice, LinearMap.coe_mk, AddHom.coe_mk, Function.update_eq_self] using h.symm

omit [Fintype E] in
/-- All diagonal replacements of one bond have the same coefficient in
a common virtual ground vector. Source: CPGSV21, the Bell-bond constraint
in the independent-bond ground-state argument, lines 2033–2044. -/
theorem virtualBondGroundSpace_diagonal_update_eq (D : E → ℕ)
    {ψ : VirtualBondConfig D → ℂ} (hψ : ψ ∈ virtualBondGroundSpace D)
    (ζ : VirtualBondConfig D) (e : E) (a b : Fin (D e)) :
    ψ (Function.update ζ e (a, a)) = ψ (Function.update ζ e (b, b)) := by
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp
    ((mem_virtualBondGroundSpace_iff D ψ).mp hψ e ζ)
  have ha := congrFun hc (a, a)
  have hb := congrFun hc (b, b)
  simp only [Pi.smul_apply, virtualBondBell, smul_eq_mul,
    virtualBondSlice, LinearMap.coe_mk, AddHom.coe_mk] at ha hb
  exact ha.symm.trans hb

omit [Fintype E] in
private theorem eq_of_forall_update [Finite E] {β : E → Type*} (F : ((e : E) → β e) → ℂ)
    (hF : ∀ a e t, F (Function.update a e t) = F a) (a b : (e : E) → β e) :
    F a = F b := by
  let _ := Fintype.ofFinite E
  have hEq (s : Finset E) : ∀ a b : (e : E) → β e,
      (∀ e, e ∉ s → a e = b e) → F a = F b := by
    induction s using Finset.induction_on with
    | empty =>
      intro a b hab
      congr 1
      funext e
      exact hab e (Finset.notMem_empty e)
    | @insert e s he ih =>
      intro a b hab
      refine (hF a e (b e)).symm.trans (ih (Function.update a e (b e)) b ?_)
      intro f hf
      by_cases hfe : f = e
      · subst f
        simp
      · rw [Function.update_of_ne hfe]
        exact hab f (by simp [hf, hfe])
  exact hEq Finset.univ a b (fun e he => False.elim (he (Finset.mem_univ e)))

/-- Assign the same label to both endpoints of every virtual bond.
Source: the diagonal coefficients of the Bell product in CPGSV21,
lines 2017–2028. -/
def virtualBondDiagonalConfig (D : E → ℕ) (a : (e : E) → Fin (D e)) :
    VirtualBondConfig D := fun e => (a e, a e)

omit [Fintype E] in
private theorem virtualBondDiagonalConfig_update (D : E → ℕ)
    (a : (e : E) → Fin (D e)) (e : E) (t : Fin (D e)) :
    virtualBondDiagonalConfig D (Function.update a e t) =
      Function.update (virtualBondDiagonalConfig D a) e (t, t) := by
  funext f
  by_cases hfe : f = e
  · subst f
    simp [virtualBondDiagonalConfig]
  · simp [virtualBondDiagonalConfig, Function.update_of_ne hfe]

omit [Fintype E] in
/-- Every diagonal virtual-bond configuration has the same coefficient
in a common ground vector. Source: CPGSV21, independence of the Bell bonds
in the uniqueness argument, lines 2033–2044. -/
theorem virtualBondGroundSpace_diagonal_eq [Finite E] (D : E → ℕ)
    {ψ : VirtualBondConfig D → ℂ} (hψ : ψ ∈ virtualBondGroundSpace D)
    (a b : (e : E) → Fin (D e)) :
    ψ (virtualBondDiagonalConfig D a) = ψ (virtualBondDiagonalConfig D b) := by
  apply eq_of_forall_update (fun a => ψ (virtualBondDiagonalConfig D a)) ?_ a b
  intro c e t
  rw [virtualBondDiagonalConfig_update]
  have h := virtualBondGroundSpace_diagonal_update_eq D hψ
    (virtualBondDiagonalConfig D c) e t (c e)
  change ψ (Function.update (virtualBondDiagonalConfig D c) e (t, t)) =
    ψ (Function.update (virtualBondDiagonalConfig D c) e (virtualBondDiagonalConfig D c e)) at h
  rw [Function.update_eq_self] at h
  exact h

/-- The separate Bell-bond conditions determine precisely the product Bell
line. This includes vanishing bond dimensions and an empty bond collection.
Source: CPGSV21, the independent-bond ground-state uniqueness argument
preceding equation `eq:4:deformed-parent-1`, lines 2017–2044. -/
theorem virtualBondGroundSpace_eq_span (D : E → ℕ) :
    virtualBondGroundSpace D = Submodule.span ℂ {virtualBondProduct D} := by
  classical
  rcases isEmpty_or_nonempty (VirtualBondConfig D) with hEmpty | hNonempty
  · let _ := hEmpty
    exact Subsingleton.elim _ _
  · obtain ⟨ζ₀⟩ := hNonempty
    let a : (e : E) → Fin (D e) := fun e => (ζ₀ e).1
    apply le_antisymm
    · intro ψ hψ
      apply Submodule.mem_span_singleton.mpr
      refine ⟨ψ (virtualBondDiagonalConfig D a), ?_⟩
      funext ζ
      change ψ (virtualBondDiagonalConfig D a) * virtualBondProduct D ζ = ψ ζ
      by_cases hDiag : ∀ e, (ζ e).1 = (ζ e).2
      · let b : (e : E) → Fin (D e) := fun e => (ζ e).1
        have hζ : ζ = virtualBondDiagonalConfig D b := by
          funext e
          exact Prod.ext rfl (hDiag e).symm
        have hProduct : virtualBondProduct D ζ = 1 := by
          simp [virtualBondProduct, virtualBondBell, hDiag]
        rw [hProduct, mul_one, hζ]
        exact virtualBondGroundSpace_diagonal_eq D hψ a b
      · obtain ⟨e, he⟩ := not_forall.mp hDiag
        have hProduct : virtualBondProduct D ζ = 0 := by
          apply Finset.prod_eq_zero (Finset.mem_univ e)
          simp only [virtualBondBell, ite_eq_right he]
        rw [hProduct, mul_zero]
        exact (eq_zero_of_mem_virtualBondGroundSpace_off_diagonal D hψ ζ e he).symm
    · exact (Submodule.span_singleton_le_iff_mem _ _).mpr
        (virtualBondProduct_mem_virtualBondGroundSpace D)

omit [DecidableEq E] in
/-- The product Bell vector is nonzero exactly when every bond has
positive dimension. Source: nonvanishing of the independent Bell product
in CPGSV21, lines 2017–2028. -/
theorem virtualBondProduct_ne_zero_iff (D : E → ℕ) :
    virtualBondProduct D ≠ 0 ↔ ∀ e, 0 < D e := by
  constructor
  · intro h e
    obtain ⟨ζ, hζ⟩ := Function.ne_iff.mp h
    exact lt_of_le_of_lt (Nat.zero_le ((ζ e).1.val)) (ζ e).1.isLt
  · intro hD hzero
    let a : (e : E) → Fin (D e) := fun e => ⟨0, hD e⟩
    have h := congrFun hzero (virtualBondDiagonalConfig D a)
    simp [virtualBondProduct, virtualBondBell, virtualBondDiagonalConfig] at h

omit [Fintype E] in
/-- Positive bond dimensions give a one-dimensional common virtual ground
space. Source: CPGSV21, uniqueness of the independent-bond ground state,
lines 2033–2044. -/
theorem finrank_virtualBondGroundSpace_eq_one [Finite E] (D : E → ℕ) (hD : ∀ e, 0 < D e) :
    Module.finrank ℂ (virtualBondGroundSpace D) = 1 := by
  let _ := Fintype.ofFinite E
  rw [virtualBondGroundSpace_eq_span]
  exact finrank_span_singleton ((virtualBondProduct_ne_zero_iff D).mpr hD)

end TNLean.PEPS
