/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.FundamentalTheorem.PaperBNT.DominantMatch

/-!
# Phase B-α and B-β (paper-faithful) strong existential and bijective matching

This module is **Phase B-α and Phase B-β** of the CPSV16/CPSV21
fundamental-theorem clean-slate plan (issue #1725).  The downstream
Phase B-γ Corollary substitution argument
(`coeff_identity_via_global_gauge`, CPSV16 §II.C lines 1187-1188) lives
in the companion module `PaperBNT/CoeffIdentity.lean` (file split in
PR #1729 to respect the 1000-line module limit).

The paper-faithful strong existential
matching theorem states the CPSV16 §II.C lines 1182–1186 *Step 1*
conclusion directly on the original (un-dropped) pair `(P, Q)` of
BNT canonical forms, iterated over each sector `k` of `Q` that carries
a unit-modulus copy.

## Paper anchor

CPSV16 (arXiv:1606.00608) §II.C lines 1182–1186, the *entire* "Step 1"
of the proof of Theorem `II_cor2` (verbatim):

> "Let us first consider $B_k$ for some given $k$.  It is not possible
> that $\langle V^{(N)}(B_k)|V^{(N)}(A_j)\rangle \to 0$ as $N\to\infty$
> for all $j$, since otherwise the MPV generated by $A$ and $B$ could
> not be proportional for all $N$ (Lemma `Lem1`).  Thus, according to
> Corollary `eqV`, there must exist one $j_k$ such that
> $|V^{(N)}(B_k)\rangle = e^{i\phi_k N} |V^{(N)}(A_{j_k})\rangle$.
> According to Lemma `equalMPS` we have $B_k = e^{i\phi_k} X_k A_{j_k} X_k^{-1}$."

The paper's "given $k$" is *iterated externally* over each unit-block
sector of `Q` (those with at least one unit-modulus weight, per the
CPSV16 §II.A line-246 normalization which is recorded **globally** —
not per-block — in `IsBNTCanonicalForm.weight_unit_exists`).  Non-unit
blocks contribute coefficients that decay exponentially and so do not
constrain the matching; the paper restricts attention to the
"physical" (unit-modulus carrying) blocks.

## Scope (Phase B-α)

The result is a **single `∀ k, ∃ j` existential statement** on the
original pair, with the paper's "given $k$" hypothesis explicitly
encoded as the unit-modulus existential.  There is **no recursion**,
no `dropSector` usage, and no combined-LI obligation on a partial
union: the entire proof routes through the existing
`exists_unit_block_match_of_sameMPV` lemma (which itself routes
through the full-family combined LI `combined_family_eventually_li`,
`PaperBNT/Api.lean`).

The downstream Phase B-β (bijective matching) will apply this theorem
twice — once with `(P, Q)` and once with `(Q, P)` — to derive
`P.basisCount = Q.basisCount` on the unit-block subset and the per-pair
bijection / gauge data.

## Proof strategy (route B of the audit memo)

Given a sector `k` of `Q` with a unit-modulus weight, apply the
existing `exists_unit_block_match_of_sameMPV` (`PaperBNT/DominantMatch`,
post-Phase-A rename in PR #1726) **with `P` and `Q` swapped**:

* feed `hQ`, `hP` (in that order);
* supply `hP_pos : 0 < P.basisCount` from `hP.weight_unit_exists`
  (which exists globally on `P`);
* supply the unit-modulus witness on `Q`'s `k` (the hypothesis of this
  theorem); and
* supply `SameMPV₂ Q.toTensor P.toTensor` via the trivial symmetric
  flip of `hEqual` (pointwise `.symm`).

The result is a `j₀ : Fin P.basisCount` with `Q.basisDim k = P.basisDim j₀`,
a gauge-phase equivalence in the `Q → P` cast direction, and a
non-decaying overlap in the `(Q.basis k, P.basis j₀)` order.  Two
local helpers (`gaugePhaseEquiv_swap_cast` and
`tendsto_mpvOverlap_zero_swap`) flip those into the paper-stated
`(P, Q)`-ordered conclusion.

No `sorry`, no `axiom`, no `unsafe`.
-/

open scoped Matrix BigOperators
open Filter Topology

namespace MPSTensor

variable {d : ℕ}

/-! ### Local helpers: symmetry of `GaugePhaseEquiv` across a bond-dim cast -/

/-- Symmetry of `GaugePhaseEquiv` at a fixed bond dimension.

`GaugePhaseEquiv A B` says there exist a gauge `X ∈ GL` and a nonzero
scalar `ζ` such that `B i = ζ • (X * A i * X⁻¹)` for every physical
index `i`.  Conjugating by `X⁻¹` and scaling by `ζ⁻¹` gives the
reversed identity `A i = ζ⁻¹ • (X⁻¹ * B i * X)`, i.e.
`GaugePhaseEquiv B A`. -/
private theorem gaugePhaseEquiv_symm_same_dim {d D : ℕ} {A B : MPSTensor d D}
    (h : GaugePhaseEquiv A B) : GaugePhaseEquiv B A := by
  classical
  obtain ⟨X, ζ, hζ, hrel⟩ := h
  refine ⟨X⁻¹, ζ⁻¹, inv_ne_zero hζ, ?_⟩
  intro i
  -- From `B i = ζ • (X * A i * X⁻¹)` derive `A i = ζ⁻¹ • (X⁻¹ * B i * X)`.
  have hBi := hrel i
  -- Abbreviations for the matrix coercions.
  set XM : Matrix (Fin D) (Fin D) ℂ := (X : Matrix (Fin D) (Fin D) ℂ)
  set XinvM : Matrix (Fin D) (Fin D) ℂ :=
    ((X⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
  have hXX : XinvM * XM = (1 : Matrix (Fin D) (Fin D) ℂ) := by
    have hU : (X⁻¹ * X : GL (Fin D) ℂ) = 1 := by simp
    have hUval :
        ((X⁻¹ * X : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
          = ((1 : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ) :=
      congrArg Units.val hU
    simp only [Units.val_mul, Units.val_one] at hUval
    exact hUval
  have hXX' : XM * XinvM = (1 : Matrix (Fin D) (Fin D) ℂ) := by
    have hU : (X * X⁻¹ : GL (Fin D) ℂ) = 1 := by simp
    have hUval :
        ((X * X⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
          = ((1 : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ) :=
      congrArg Units.val hU
    simp only [Units.val_mul, Units.val_one] at hUval
    exact hUval
  -- Inverse-of-inverse: `(X⁻¹)⁻¹ = X` for units.
  have hInvInv : ((X⁻¹)⁻¹ : GL (Fin D) ℂ) = X := inv_inv X
  -- The desired identity: `A i = ζ⁻¹ • (X⁻¹ * B i * X)`.
  -- Multiply `hBi : B i = ζ • (X * A i * X⁻¹)` on the left by `X⁻¹` and on
  -- the right by `X`:
  --   X⁻¹ * B i * X = ζ • (X⁻¹ * X * A i * X⁻¹ * X) = ζ • (1 * A i * 1) = ζ • A i.
  have hSandwich :
      XinvM * B i * XM = ζ • A i := by
    calc
      XinvM * B i * XM
          = XinvM * (ζ • (XM * A i * XinvM)) * XM := by rw [hBi]
      _ = ζ • (XinvM * (XM * A i * XinvM) * XM) := by
            simp
      _ = ζ • ((XinvM * XM) * A i * (XinvM * XM)) := by
            simp [Matrix.mul_assoc]
      _ = ζ • A i := by rw [hXX]; simp
  -- Now divide by `ζ`.
  have hAi : A i = ζ⁻¹ • (XinvM * B i * XM) := by
    have := congrArg (fun M => (ζ⁻¹ : ℂ) • M) hSandwich
    simp only [smul_smul, inv_mul_cancel₀ hζ, one_smul] at this
    exact this.symm
  -- Repackage with the inverse of `X⁻¹` being `X`.
  -- The goal expects `((X⁻¹)⁻¹ : GL).val = X.val`.
  change A i = ζ⁻¹ • (XinvM * B i *
    (((X⁻¹)⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ))
  simpa [hInvInv, XM, XinvM] using hAi

/-- Symmetry of `GaugePhaseEquiv` across a bond-dim cast: if the cast
maps the *right-hand* tensor into the *left-hand* space, then we may
flip both the cast direction and the equivalence direction.

The two forms are mathematically the same statement (after eliminating
the cast by `subst`), but the cast routing differs at the term level,
so we record this as an explicit helper used inside
`forall_unit_k_exists_j_nondecaying_overlap_of_sameMPV`. -/
private theorem gaugePhaseEquiv_swap_cast {d D₁ D₂ : ℕ}
    (h : D₁ = D₂) {A : MPSTensor d D₁} {B : MPSTensor d D₂}
    (hGP : GaugePhaseEquiv (cast (congr_arg (MPSTensor d) h.symm) B) A) :
    GaugePhaseEquiv (cast (congr_arg (MPSTensor d) h) A) B := by
  subst h
  -- After `subst`, both casts reduce to identity.
  simpa using gaugePhaseEquiv_symm_same_dim (by simpa using hGP)

/-! ### Phase B-α main theorem: paper-faithful strong existential matching -/

/-- **CPSV16 §II.C lines 1182–1186 Step 1 (paper-faithful Phase B-α).**

For every sector `k` of `Q` that carries at least one unit-modulus
weight (the CPSV16 §II.A line-246 hypothesis, applied at `k`), there
exists a sector `j` of `P` of equal bond dimension, gauge-phase
equivalent to `Q.basis k` after the dimension cast, and with
non-decaying cross-overlap.

This is the paper's Step 1 contrapositive of `Lem1` (CPSV16 lines
1131–1133, combined LI on the **FULL** `{A^{[j]}} ∪ {B^{[k]}}` family),
**iterated externally** over each unit-block sector `k` of `Q`.  No
recursion on a smaller `SectorDecomposition`, no `dropSector` usage,
no combined LI on a partial union — only the weak existential
(packaged as `exists_unit_block_match_of_sameMPV` in
`PaperBNT/DominantMatch.lean`) applied at each sector.

The unit-block restriction on `k` is paper-faithful: the CPSV16 §II.A
line-246 normalization is recorded globally on the two-layer `(j, q)`
indexing of the BNT display (not per-block), so non-unit-block sectors
may exist in principle.  Such "ghost" blocks have coefficients
`Q.coeff N k = ∑_q (Q.weight k q)^N` that decay exponentially to zero,
contribute nothing to the thermodynamic state, and are not constrained
by the matching (the FT cannot reconstruct them from `P` alone).  The
downstream Phase B-β bijective-matching layer applies this theorem
twice (with `P, Q` swapped) to derive `g_a = g_b` on the unit-block
subset and the per-pair gauge data.

Proof strategy (route B of `/tmp/phase_4c_drift_audit_2026-05-14.md`):
apply `exists_unit_block_match_of_sameMPV` with the swap
`(P := Q, Q := P)`, feed `hQ`, `hP`, `hP_pos`, the unit-modulus
witness on `Q`, and the pointwise-symmetric `SameMPV₂` flip
`fun N σ => (hEqual N σ).symm`.  Re-orient the resulting conclusion
via `gaugePhaseEquiv_swap_cast` and `tendsto_mpvOverlap_zero_swap`.

Paper anchor: CPSV16 §II.C lines 1182–1186 (arXiv:1606.00608);
`Lem1` at CPSV16 lines 1131–1133.  Iteration of the paper's
"given $k$" is encoded as the outer `∀ k`. -/
theorem forall_unit_k_exists_j_nondecaying_overlap_of_sameMPV
    {P Q : SectorDecomposition d}
    (hP : IsBNTCanonicalForm P) (hQ : IsBNTCanonicalForm Q)
    (hEqual : SameMPV₂ P.toTensor Q.toTensor) :
    ∀ k : Fin Q.basisCount, (∃ q : Fin (Q.copies k), ‖Q.weight k q‖ = 1) →
      ∃ (j : Fin P.basisCount) (h : P.basisDim j = Q.basisDim k),
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) h) (P.basis j))
            (Q.basis k) ∧
        ¬ Tendsto (fun N : ℕ =>
            mpvOverlap (d := d) (P.basis j) (Q.basis k) N)
          atTop (𝓝 0) := by
  classical
  intro k hUnitQ
  -- `P.basisCount > 0`: the global unit witness on `P` produces a
  -- sector index, which witnesses positivity of the basis count.
  have hP_pos : 0 < P.basisCount := by
    obtain ⟨j₀, _, _⟩ := hP.weight_unit_exists
    exact Nat.lt_of_le_of_lt (Nat.zero_le _) j₀.isLt
  -- Pointwise-symmetric flip of `SameMPV₂`: by `.symm` of each scalar
  -- equality.  No new content; just `Q ↔ P` reordering.
  have hEqual_symm : SameMPV₂ Q.toTensor P.toTensor :=
    fun N σ => (hEqual N σ).symm
  -- Apply the existing Phase-A lemma with `P` and `Q` swapped.
  obtain ⟨j, hsymDim, hGE_swapped, hNonDecay_swapped⟩ :=
    exists_unit_block_match_of_sameMPV
      (P := Q) (Q := P) hQ hP hP_pos k hUnitQ hEqual_symm
  -- `hsymDim : Q.basisDim k = P.basisDim j`; flip to the paper-stated
  -- `P.basisDim j = Q.basisDim k`.
  refine ⟨j, hsymDim.symm, ?_, ?_⟩
  · -- Gauge-phase equivalence: flip the cast direction and the
    -- equivalence direction simultaneously via `gaugePhaseEquiv_swap_cast`.
    -- `hGE_swapped : GaugePhaseEquiv (cast (congr_arg (MPSTensor d) hsymDim) (Q.basis k))
    --                                (P.basis j)`.
    -- We want `GaugePhaseEquiv (cast (congr_arg (MPSTensor d) hsymDim.symm)
    --                                  (P.basis j)) (Q.basis k)`.
    exact gaugePhaseEquiv_swap_cast hsymDim.symm
      (by
        -- `hsymDim.symm.symm = hsymDim` definitionally for `Eq`.
        simpa using hGE_swapped)
  · -- Tendsto symmetry: swap A and B in `mpvOverlap` preserves
    -- convergence to zero (`mpvOverlap A B N = star (mpvOverlap B A N)`).
    intro hTend
    apply hNonDecay_swapped
    exact tendsto_mpvOverlap_zero_swap (P.basis j) (Q.basis k) hTend

/-! ### Phase B-β local helpers: transitivity of `GaugePhaseEquiv` at a fixed bond dim

The Phase B-β bijective-matching proof composes two gauge-phase
equivalences `(P.basis j) ↔ (Q.basis k₁)` and `(P.basis j) ↔ (Q.basis k₂)`
through the common centre `P.basis j` to derive an equivalence
`(Q.basis k₁) ↔ (Q.basis k₂)`.  The `basis_distinct` field of
`IsBNTCanonicalForm` then forces `k₁ = k₂` (injectivity of the matching). -/

/-- Transitivity of `GaugePhaseEquiv` at a fixed bond dimension.

If `B i = ζ₁ • (X₁ * A i * X₁⁻¹)` and `C i = ζ₂ • (X₂ * B i * X₂⁻¹)`,
then `C i = (ζ₂ ζ₁) • ((X₂ X₁) * A i * (X₂ X₁)⁻¹)`, giving
`GaugePhaseEquiv A C` with gauge `X₂ * X₁` and phase scalar `ζ₂ * ζ₁`. -/
private theorem gaugePhaseEquiv_trans_same_dim {d D : ℕ} {A B C : MPSTensor d D}
    (h₁ : GaugePhaseEquiv A B) (h₂ : GaugePhaseEquiv B C) : GaugePhaseEquiv A C := by
  classical
  obtain ⟨X₁, ζ₁, hζ₁, hr₁⟩ := h₁
  obtain ⟨X₂, ζ₂, hζ₂, hr₂⟩ := h₂
  refine ⟨X₂ * X₁, ζ₂ * ζ₁, mul_ne_zero hζ₂ hζ₁, ?_⟩
  intro i
  -- Abbreviations for the matrix coercions of the four GL units in play.
  set X₁M : Matrix (Fin D) (Fin D) ℂ :=
    ((X₁ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
  set X₂M : Matrix (Fin D) (Fin D) ℂ :=
    ((X₂ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
  set X₁invM : Matrix (Fin D) (Fin D) ℂ :=
    ((X₁⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
  set X₂invM : Matrix (Fin D) (Fin D) ℂ :=
    ((X₂⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
  -- Coercion of the product `X₂ * X₁` to a matrix is the matrix product.
  have hMul_val :
      (((X₂ * X₁ : GL (Fin D) ℂ)) : Matrix (Fin D) (Fin D) ℂ) = X₂M * X₁M := by
    simp [X₁M, X₂M]
  -- Coercion of the inverse of the product is the reversed product of inverses.
  have hMulInv_val :
      (((X₂ * X₁)⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ) = X₁invM * X₂invM := by
    have hRev : ((X₂ * X₁)⁻¹ : GL (Fin D) ℂ) = X₁⁻¹ * X₂⁻¹ := mul_inv_rev X₂ X₁
    have := congrArg (fun U : GL (Fin D) ℂ =>
        (U : Matrix (Fin D) (Fin D) ℂ)) hRev
    simp [X₁invM, X₂invM]
  -- Compute `C i` by chaining the two equivalences.
  calc C i
      = ζ₂ • (X₂M * B i * X₂invM) := hr₂ i
    _ = ζ₂ • (X₂M * (ζ₁ • (X₁M * A i * X₁invM)) * X₂invM) := by rw [hr₁ i]
    _ = ζ₂ • (ζ₁ • (X₂M * (X₁M * A i * X₁invM) * X₂invM)) := by
          simp [smul_smul]
    _ = (ζ₂ * ζ₁) • (X₂M * X₁M * A i * X₁invM * X₂invM) := by
          simp [smul_smul, Matrix.mul_assoc]
    _ = (ζ₂ * ζ₁) • ((X₂M * X₁M) * A i * (X₁invM * X₂invM)) := by
          simp [Matrix.mul_assoc]
    _ = (ζ₂ * ζ₁) •
          ((((X₂ * X₁ : GL (Fin D) ℂ)) : Matrix (Fin D) (Fin D) ℂ) * A i *
            (((X₂ * X₁)⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)) := by
          rw [hMul_val, hMulInv_val]

/-- Composition through a common centre `A`: if the cast `D = D₁` carries
`A : MPSTensor d D` into a gauge-phase equivalence with `B : MPSTensor d D₁`,
and similarly the cast `D = D₂` carries `A` into a gauge-phase equivalence
with `C : MPSTensor d D₂`, then `B` and `C` are gauge-phase equivalent
(after the dimension cast `D₁ = D₂`).

This is the cast-aware transitivity used in Phase B-β to derive
`GaugePhaseEquiv (Q.basis k₁) (Q.basis k₂)` (up to cast) from two
matchings against the same `P.basis j`, before invoking `basis_distinct`
of `Q` to force `k₁ = k₂`. -/
private theorem gaugePhaseEquiv_cast_compose_via_centre
    {d D D₁ D₂ : ℕ}
    (h₁ : D = D₁) (h₂ : D = D₂)
    {A : MPSTensor d D} {B : MPSTensor d D₁} {C : MPSTensor d D₂}
    (GE₁ : GaugePhaseEquiv (cast (congr_arg (MPSTensor d) h₁) A) B)
    (GE₂ : GaugePhaseEquiv (cast (congr_arg (MPSTensor d) h₂) A) C) :
    GaugePhaseEquiv
        (cast (congr_arg (MPSTensor d) (h₁.symm.trans h₂)) B) C := by
  subst h₁
  -- After `subst h₁`, `D₁` is replaced everywhere by `D`, the cast on
  -- `GE₁` reduces to identity, and `h₂.symm.trans h₂ = h₂`.
  subst h₂
  -- After `subst h₂`, all three tensors live in `MPSTensor d D`.
  simp only [cast_eq] at GE₁ GE₂ ⊢
  exact gaugePhaseEquiv_trans_same_dim (gaugePhaseEquiv_symm_same_dim GE₁) GE₂

/-! ### Phase B-β main theorem: bijective matching by symmetry

CPSV16 §II.C lines 1184–1186, the **symmetry argument**
`g_a ≥ g_b ∧ g_b ≥ g_a ⇒ g_a = g_b`.

The paper-faithful Phase B-α theorem
`forall_unit_k_exists_j_nondecaying_overlap_of_sameMPV` gives one
direction: for every unit-modulus sector `k` of `Q` there exists a
sector `j` of `P` with matched bond dimension, gauge-phase equivalence
(after cast), and non-decaying cross-overlap.  Applying the SAME theorem
once more with `(P, Q)` swapped and `SameMPV₂` symmetrically flipped
gives the other direction: for every unit-modulus sector `j` of `P`
there exists a sector `k` of `Q` with the matching data.

The resulting two functions are **injective embeddings**

  `φ : { k // ∃ q, ‖Q.weight k q‖ = 1 } ↪ Fin P.basisCount`,
  `ψ : { j // ∃ q, ‖P.weight j q‖ = 1 } ↪ Fin Q.basisCount`.

Injectivity is the CPSV16 §II.C lines 1184–1186 conclusion: two
unit-modulus sectors of `Q` that match the SAME sector `j` of `P`
would force two sectors of `Q` to be gauge-phase equivalent through
the common centre `P.basis j`, contradicting `basis_distinct` of `Q`.

## Scoping note (honest scoping per the task brief)

The user-requested literal form `β : UnitQ ≃ UnitP` (a bijection
between the unit-modulus Finsets) requires an additional argument that
the matched `j` lies in `UnitP`, i.e. that the matched sector of `P`
also carries a unit-modulus weight.  That step is **not** discharged by
the Phase B-α non-decay output alone (`mpvOverlap` is on the *basis*
tensors, not on the weighted sectors); it requires the per-sector
weight-equivariance argument of CPSV16 Lemma `equalMPS` (lines 1148–1167)
combined with the gauge-phase identity on weighted sectors.  Phase B-β
delivers the *symmetric injective matching*, which is the direct
formalisation of the paper's `g_a ≥ g_b ∧ g_b ≥ g_a` step on the
unit-modulus subsets; the upgrade to `UnitQ ≃ UnitP` is deferred to a
later phase that lifts the matching from basis-MPV non-decay to weight
transport.

Style choice: `UnitP` and `UnitQ` are encoded as `Subtype`s on
`Fin P.basisCount` and `Fin Q.basisCount` respectively.  This avoids
the `DecidablePred` obligation that `Finset.univ.filter` would impose,
keeps the bond-dimension/gauge-phase data attached to the original
sector index, and is the cleanest carrier for the matching data. -/

/-- **CPSV16 §II.C lines 1184–1186 (Phase B-β, bijective matching by
symmetry).**

Applying `forall_unit_k_exists_j_nondecaying_overlap_of_sameMPV` twice
(once with `(P, Q, hEqual)` and once with `(Q, P, hEqual.symm)`) yields
two `Function.Embedding`s, one in each direction, on the unit-modulus
subsets

* `UnitQ := { k : Fin Q.basisCount // ∃ q, ‖Q.weight k q‖ = 1 }`,
* `UnitP := { j : Fin P.basisCount // ∃ q, ‖P.weight j q‖ = 1 }`.

Both embeddings carry the matched bond-dimension equality, the
gauge-phase equivalence (cast-left shape), and the non-decaying
cross-overlap of basis MPV states.  Injectivity in each direction
routes through `basis_distinct` of the *target* canonical form, via the
cast-aware transitivity helper
`gaugePhaseEquiv_cast_compose_via_centre`.

Paper anchor: CPSV16 §II.C lines 1184–1186 (arXiv:1606.00608),
`Lem1` at CPSV16 lines 1131–1133.  See the scoping note in the module
docstring for the relationship to the bijection
`β : UnitQ ≃ UnitP` (deferred to a later phase). -/
theorem bijective_match_of_sameMPV
    {P Q : SectorDecomposition d}
    (hP : IsBNTCanonicalForm P) (hQ : IsBNTCanonicalForm Q)
    (hEqual : SameMPV₂ P.toTensor Q.toTensor) :
    let UnitP := { j : Fin P.basisCount // ∃ q : Fin (P.copies j), ‖P.weight j q‖ = 1 }
    let UnitQ := { k : Fin Q.basisCount // ∃ q : Fin (Q.copies k), ‖Q.weight k q‖ = 1 }
    ∃ (φ : UnitQ ↪ Fin P.basisCount) (ψ : UnitP ↪ Fin Q.basisCount),
      (∀ k : UnitQ, ∃ h : P.basisDim (φ k) = Q.basisDim k.val,
          GaugePhaseEquiv
              (cast (congr_arg (MPSTensor d) h) (P.basis (φ k)))
              (Q.basis k.val) ∧
          ¬ Tendsto (fun N : ℕ =>
              mpvOverlap (d := d) (P.basis (φ k)) (Q.basis k.val) N)
            atTop (𝓝 0)) ∧
      (∀ j : UnitP, ∃ h : Q.basisDim (ψ j) = P.basisDim j.val,
          GaugePhaseEquiv
              (cast (congr_arg (MPSTensor d) h) (Q.basis (ψ j)))
              (P.basis j.val) ∧
          ¬ Tendsto (fun N : ℕ =>
              mpvOverlap (d := d) (Q.basis (ψ j)) (P.basis j.val) N)
            atTop (𝓝 0)) := by
  classical
  -- Phase B-α applied in each direction.
  have hFwd := forall_unit_k_exists_j_nondecaying_overlap_of_sameMPV hP hQ hEqual
  have hEqual_symm : SameMPV₂ Q.toTensor P.toTensor :=
    fun N σ => (hEqual N σ).symm
  have hBwd := forall_unit_k_exists_j_nondecaying_overlap_of_sameMPV hQ hP hEqual_symm
  -- Subtype carriers of the unit-modulus subsets.
  set UnitP := { j : Fin P.basisCount // ∃ q : Fin (P.copies j), ‖P.weight j q‖ = 1 }
    with hUnitP_def
  set UnitQ := { k : Fin Q.basisCount // ∃ q : Fin (Q.copies k), ‖Q.weight k q‖ = 1 }
    with hUnitQ_def
  -- Raw matched-sector function for the forward (`UnitQ → Fin P.basisCount`)
  -- direction, by classical choice on the Phase B-α witness.
  let φ₀ : UnitQ → Fin P.basisCount := fun k => (hFwd k.val k.property).choose
  -- The classical-choice spec at each `k : UnitQ`.
  have φ₀_spec : ∀ k : UnitQ,
      ∃ h : P.basisDim (φ₀ k) = Q.basisDim k.val,
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) h) (P.basis (φ₀ k)))
            (Q.basis k.val) ∧
        ¬ Tendsto (fun N : ℕ =>
            mpvOverlap (d := d) (P.basis (φ₀ k)) (Q.basis k.val) N)
          atTop (𝓝 0) := fun k => (hFwd k.val k.property).choose_spec
  -- Forward injectivity (CPSV16 line 1186): two unit-modulus sectors of
  -- `Q` that map to the same `j` of `P` would force two gauge-phase
  -- equivalences with the same centre `P.basis j`, hence
  -- `GaugePhaseEquiv (Q.basis k₁) (Q.basis k₂)` (up to cast), contradicting
  -- `basis_distinct` of `Q`.
  -- Helper: align an equivalence centred at `P.basis j'` to one centred at
  -- `P.basis j` when `j = j'`.  The `rintro ... rfl` performs `subst` on the
  -- *fresh* free variable, sidestepping the motive-type obstruction that
  -- `rw [hjEq]` would hit (because `h_t` depends on `j'`).
  have rebase_centre_P :
      ∀ (j j' : Fin P.basisCount) (_hj : j = j')
        {kv : Fin Q.basisCount}
        (h_t : P.basisDim j' = Q.basisDim kv)
        (_GE : GaugePhaseEquiv
                  (cast (congr_arg (MPSTensor d) h_t) (P.basis j')) (Q.basis kv)),
        ∃ h_t' : P.basisDim j = Q.basisDim kv,
          GaugePhaseEquiv
              (cast (congr_arg (MPSTensor d) h_t') (P.basis j)) (Q.basis kv) := by
    rintro _ _ rfl _ h_t GE
    exact ⟨h_t, GE⟩
  have hφ₀_inj : Function.Injective φ₀ := by
    intro k₁ k₂ hjEq
    obtain ⟨h₁, GE₁, _⟩ := φ₀_spec k₁
    obtain ⟨h₂, GE₂, _⟩ := φ₀_spec k₂
    by_contra hne
    have hne_val : k₁.val ≠ k₂.val := fun h => hne (Subtype.ext h)
    -- Use the helper to move from centre `P.basis (φ₀ k₂)` to `P.basis (φ₀ k₁)`.
    obtain ⟨h₂', GE₂'⟩ :=
      rebase_centre_P (φ₀ k₁) (φ₀ k₂) hjEq h₂ GE₂
    -- Compose the two equivalences through the common centre `P.basis (φ₀ k₁)`.
    have hQdim : Q.basisDim k₁.val = Q.basisDim k₂.val := h₁.symm.trans h₂'
    have hQGE :
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) hQdim) (Q.basis k₁.val))
            (Q.basis k₂.val) :=
      gaugePhaseEquiv_cast_compose_via_centre (A := P.basis (φ₀ k₁))
        (B := Q.basis k₁.val) (C := Q.basis k₂.val) h₁ h₂' GE₁ GE₂'
    exact hQ.basis_distinct k₁.val k₂.val hne_val hQdim hQGE
  -- Symmetric (`UnitP → Fin Q.basisCount`) direction.
  let ψ₀ : UnitP → Fin Q.basisCount := fun j => (hBwd j.val j.property).choose
  have ψ₀_spec : ∀ j : UnitP,
      ∃ h : Q.basisDim (ψ₀ j) = P.basisDim j.val,
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) h) (Q.basis (ψ₀ j)))
            (P.basis j.val) ∧
        ¬ Tendsto (fun N : ℕ =>
            mpvOverlap (d := d) (Q.basis (ψ₀ j)) (P.basis j.val) N)
          atTop (𝓝 0) := fun j => (hBwd j.val j.property).choose_spec
  -- Symmetric helper for the backward direction.
  have rebase_centre_Q :
      ∀ (k k' : Fin Q.basisCount) (_hk : k = k')
        {jv : Fin P.basisCount}
        (h_t : Q.basisDim k' = P.basisDim jv)
        (_GE : GaugePhaseEquiv
                  (cast (congr_arg (MPSTensor d) h_t) (Q.basis k')) (P.basis jv)),
        ∃ h_t' : Q.basisDim k = P.basisDim jv,
          GaugePhaseEquiv
              (cast (congr_arg (MPSTensor d) h_t') (Q.basis k)) (P.basis jv) := by
    rintro _ _ rfl _ h_t GE
    exact ⟨h_t, GE⟩
  have hψ₀_inj : Function.Injective ψ₀ := by
    intro j₁ j₂ hkEq
    obtain ⟨h₁, GE₁, _⟩ := ψ₀_spec j₁
    obtain ⟨h₂, GE₂, _⟩ := ψ₀_spec j₂
    by_contra hne
    have hne_val : j₁.val ≠ j₂.val := fun h => hne (Subtype.ext h)
    obtain ⟨h₂', GE₂'⟩ :=
      rebase_centre_Q (ψ₀ j₁) (ψ₀ j₂) hkEq h₂ GE₂
    have hPdim : P.basisDim j₁.val = P.basisDim j₂.val := h₁.symm.trans h₂'
    have hPGE :
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) hPdim) (P.basis j₁.val))
            (P.basis j₂.val) :=
      gaugePhaseEquiv_cast_compose_via_centre (A := Q.basis (ψ₀ j₁))
        (B := P.basis j₁.val) (C := P.basis j₂.val) h₁ h₂' GE₁ GE₂'
    exact hP.basis_distinct j₁.val j₂.val hne_val hPdim hPGE
  -- Package as `Function.Embedding`s and supply the matching data.
  refine ⟨⟨φ₀, hφ₀_inj⟩, ⟨ψ₀, hψ₀_inj⟩, ?_, ?_⟩
  · intro k
    exact φ₀_spec k
  · intro j
    exact ψ₀_spec j


end MPSTensor
