/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.FundamentalTheorem.PaperBNT.DominantMatch

/-!
# Phase B-α (paper-faithful) strong existential matching

This module is **Phase B-α** of the CPSV16/CPSV21 fundamental-theorem
clean-slate plan (issue #1725) — the paper-faithful strong existential
matching theorem.  It states the CPSV16 §II.C lines 1182–1186 *Step 1*
conclusion directly on the original (un-dropped) pair `(P, Q)` of
BNT canonical forms, iterated over each sector `k` of `Q` that carries
a unit-modulus copy.

## Paper anchor

CPSV16 (arXiv:1606.00608) §II.C lines 1182–1186, the *entire* "Step 1"
of the proof of Theorem `II_cor2` (verbatim):

> "Let us first consider $B_k$ for some given $k$.  It is not possible
> that $\langle V^{(N)}(B_k)|V^{(N)}(A_j)\rangle \to 0$ as $N\to\infty$
> for all $j$, since otherwise the MPV generated by $A$ and $B$ could
> not be proportional for all $N$ (Lemma `Lem1`).  Thus, according to
> Corollary `eqV`, there must exist one $j_k$ such that
> $|V^{(N)}(B_k)\rangle = e^{i\phi_k N} |V^{(N)}(A_{j_k})\rangle$.
> According to Lemma `equalMPS` we have $B_k = e^{i\phi_k} X_k A_{j_k} X_k^{-1}$."

The paper's "given $k$" is *iterated externally* over each unit-block
sector of `Q` (those with at least one unit-modulus weight, per the
CPSV16 §II.A line-246 normalization which is recorded **globally** —
not per-block — in `IsBNTCanonicalForm.weight_unit_exists`).  Non-unit
blocks contribute coefficients that decay exponentially and so do not
constrain the matching; the paper restricts attention to the
"physical" (unit-modulus carrying) blocks.

## Scope (Phase B-α)

The result is a **single `∀ k, ∃ j` existential statement** on the
original pair, with the paper's "given $k$" hypothesis explicitly
encoded as the unit-modulus existential.  There is **no recursion**,
no `dropSector` usage, and no combined-LI obligation on a partial
union: the entire proof routes through the existing
`exists_unit_block_match_of_sameMPV` lemma (which itself routes
through the full-family combined LI `combined_family_eventually_li`,
`PaperBNT/Api.lean`).

The downstream Phase B-β (bijective matching) will apply this theorem
twice — once with `(P, Q)` and once with `(Q, P)` — to derive
`P.basisCount = Q.basisCount` on the unit-block subset and the per-pair
bijection / gauge data.

## Proof strategy (route B of the audit memo)

Given a sector `k` of `Q` with a unit-modulus weight, apply the
existing `exists_unit_block_match_of_sameMPV` (`PaperBNT/DominantMatch`,
post-Phase-A rename in PR #1726) **with `P` and `Q` swapped**:

* feed `hQ`, `hP` (in that order);
* supply `hP_pos : 0 < P.basisCount` from `hP.weight_unit_exists`
  (which exists globally on `P`);
* supply the unit-modulus witness on `Q`'s `k` (the hypothesis of this
  theorem); and
* supply `SameMPV₂ Q.toTensor P.toTensor` via the trivial symmetric
  flip of `hEqual` (pointwise `.symm`).

The result is a `j₀ : Fin P.basisCount` with `Q.basisDim k = P.basisDim j₀`,
a gauge-phase equivalence in the `Q → P` cast direction, and a
non-decaying overlap in the `(Q.basis k, P.basis j₀)` order.  Two
local helpers (`gaugePhaseEquiv_swap_cast` and
`tendsto_mpvOverlap_zero_swap`) flip those into the paper-stated
`(P, Q)`-ordered conclusion.

No `sorry`, no `axiom`, no `unsafe`.
-/

open scoped Matrix BigOperators
open Filter Topology

namespace MPSTensor

variable {d : ℕ}

/-! ### Local helpers: symmetry of `GaugePhaseEquiv` across a bond-dim cast -/

/-- Symmetry of `GaugePhaseEquiv` at a fixed bond dimension.

`GaugePhaseEquiv A B` says there exist a gauge `X ∈ GL` and a nonzero
scalar `ζ` such that `B i = ζ • (X * A i * X⁻¹)` for every physical
index `i`.  Conjugating by `X⁻¹` and scaling by `ζ⁻¹` gives the
reversed identity `A i = ζ⁻¹ • (X⁻¹ * B i * X)`, i.e.
`GaugePhaseEquiv B A`. -/
private theorem gaugePhaseEquiv_symm_same_dim {d D : ℕ} {A B : MPSTensor d D}
    (h : GaugePhaseEquiv A B) : GaugePhaseEquiv B A := by
  classical
  obtain ⟨X, ζ, hζ, hrel⟩ := h
  refine ⟨X⁻¹, ζ⁻¹, inv_ne_zero hζ, ?_⟩
  intro i
  -- From `B i = ζ • (X * A i * X⁻¹)` derive `A i = ζ⁻¹ • (X⁻¹ * B i * X)`.
  have hBi := hrel i
  -- Abbreviations for the matrix coercions.
  set XM : Matrix (Fin D) (Fin D) ℂ := (X : Matrix (Fin D) (Fin D) ℂ)
  set XinvM : Matrix (Fin D) (Fin D) ℂ :=
    ((X⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
  have hXX : XinvM * XM = (1 : Matrix (Fin D) (Fin D) ℂ) := by
    have hU : (X⁻¹ * X : GL (Fin D) ℂ) = 1 := by simp
    have hUval :
        ((X⁻¹ * X : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
          = ((1 : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ) :=
      congrArg Units.val hU
    simp only [Units.val_mul, Units.val_one] at hUval
    exact hUval
  have hXX' : XM * XinvM = (1 : Matrix (Fin D) (Fin D) ℂ) := by
    have hU : (X * X⁻¹ : GL (Fin D) ℂ) = 1 := by simp
    have hUval :
        ((X * X⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
          = ((1 : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ) :=
      congrArg Units.val hU
    simp only [Units.val_mul, Units.val_one] at hUval
    exact hUval
  -- Inverse-of-inverse: `(X⁻¹)⁻¹ = X` for units.
  have hInvInv : ((X⁻¹)⁻¹ : GL (Fin D) ℂ) = X := inv_inv X
  -- The desired identity: `A i = ζ⁻¹ • (X⁻¹ * B i * X)`.
  -- Multiply `hBi : B i = ζ • (X * A i * X⁻¹)` on the left by `X⁻¹` and on
  -- the right by `X`:
  --   X⁻¹ * B i * X = ζ • (X⁻¹ * X * A i * X⁻¹ * X) = ζ • (1 * A i * 1) = ζ • A i.
  have hSandwich :
      XinvM * B i * XM = ζ • A i := by
    calc
      XinvM * B i * XM
          = XinvM * (ζ • (XM * A i * XinvM)) * XM := by rw [hBi]
      _ = ζ • (XinvM * (XM * A i * XinvM) * XM) := by
            simp
      _ = ζ • ((XinvM * XM) * A i * (XinvM * XM)) := by
            simp [Matrix.mul_assoc]
      _ = ζ • A i := by rw [hXX]; simp
  -- Now divide by `ζ`.
  have hAi : A i = ζ⁻¹ • (XinvM * B i * XM) := by
    have := congrArg (fun M => (ζ⁻¹ : ℂ) • M) hSandwich
    simp only [smul_smul, inv_mul_cancel₀ hζ, one_smul] at this
    exact this.symm
  -- Repackage with the inverse of `X⁻¹` being `X`.
  -- The goal expects `((X⁻¹)⁻¹ : GL).val = X.val`.
  change A i = ζ⁻¹ • (XinvM * B i *
    (((X⁻¹)⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ))
  simpa [hInvInv, XM, XinvM] using hAi

/-- Symmetry of `GaugePhaseEquiv` across a bond-dim cast: if the cast
maps the *right-hand* tensor into the *left-hand* space, then we may
flip both the cast direction and the equivalence direction.

The two forms are mathematically the same statement (after eliminating
the cast by `subst`), but the cast routing differs at the term level,
so we record this as an explicit helper used inside
`forall_unit_k_exists_j_nondecaying_overlap_of_sameMPV`. -/
private theorem gaugePhaseEquiv_swap_cast {d D₁ D₂ : ℕ}
    (h : D₁ = D₂) {A : MPSTensor d D₁} {B : MPSTensor d D₂}
    (hGP : GaugePhaseEquiv (cast (congr_arg (MPSTensor d) h.symm) B) A) :
    GaugePhaseEquiv (cast (congr_arg (MPSTensor d) h) A) B := by
  subst h
  -- After `subst`, both casts reduce to identity.
  simpa using gaugePhaseEquiv_symm_same_dim (by simpa using hGP)

/-! ### Phase B-α main theorem: paper-faithful strong existential matching -/

/-- **CPSV16 §II.C lines 1182–1186 Step 1 (paper-faithful Phase B-α).**

For every sector `k` of `Q` that carries at least one unit-modulus
weight (the CPSV16 §II.A line-246 hypothesis, applied at `k`), there
exists a sector `j` of `P` of equal bond dimension, gauge-phase
equivalent to `Q.basis k` after the dimension cast, and with
non-decaying cross-overlap.

This is the paper's Step 1 contrapositive of `Lem1` (CPSV16 lines
1131–1133, combined LI on the **FULL** `{A^{[j]}} ∪ {B^{[k]}}` family),
**iterated externally** over each unit-block sector `k` of `Q`.  No
recursion on a smaller `SectorDecomposition`, no `dropSector` usage,
no combined LI on a partial union — only the weak existential
(packaged as `exists_unit_block_match_of_sameMPV` in
`PaperBNT/DominantMatch.lean`) applied at each sector.

The unit-block restriction on `k` is paper-faithful: the CPSV16 §II.A
line-246 normalization is recorded globally on the two-layer `(j, q)`
indexing of the BNT display (not per-block), so non-unit-block sectors
may exist in principle.  Such "ghost" blocks have coefficients
`Q.coeff N k = ∑_q (Q.weight k q)^N` that decay exponentially to zero,
contribute nothing to the thermodynamic state, and are not constrained
by the matching (the FT cannot reconstruct them from `P` alone).  The
downstream Phase B-β bijective-matching layer applies this theorem
twice (with `P, Q` swapped) to derive `g_a = g_b` on the unit-block
subset and the per-pair gauge data.

Proof strategy (route B of `/tmp/phase_4c_drift_audit_2026-05-14.md`):
apply `exists_unit_block_match_of_sameMPV` with the swap
`(P := Q, Q := P)`, feed `hQ`, `hP`, `hP_pos`, the unit-modulus
witness on `Q`, and the pointwise-symmetric `SameMPV₂` flip
`fun N σ => (hEqual N σ).symm`.  Re-orient the resulting conclusion
via `gaugePhaseEquiv_swap_cast` and `tendsto_mpvOverlap_zero_swap`.

Paper anchor: CPSV16 §II.C lines 1182–1186 (arXiv:1606.00608);
`Lem1` at CPSV16 lines 1131–1133.  Iteration of the paper's
"given $k$" is encoded as the outer `∀ k`. -/
theorem forall_unit_k_exists_j_nondecaying_overlap_of_sameMPV
    {P Q : SectorDecomposition d}
    (hP : IsBNTCanonicalForm P) (hQ : IsBNTCanonicalForm Q)
    (hEqual : SameMPV₂ P.toTensor Q.toTensor) :
    ∀ k : Fin Q.basisCount, (∃ q : Fin (Q.copies k), ‖Q.weight k q‖ = 1) →
      ∃ (j : Fin P.basisCount) (h : P.basisDim j = Q.basisDim k),
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) h) (P.basis j))
            (Q.basis k) ∧
        ¬ Tendsto (fun N : ℕ =>
            mpvOverlap (d := d) (P.basis j) (Q.basis k) N)
          atTop (𝓝 0) := by
  classical
  intro k hUnitQ
  -- `P.basisCount > 0`: the global unit witness on `P` produces a
  -- sector index, which witnesses positivity of the basis count.
  have hP_pos : 0 < P.basisCount := by
    obtain ⟨j₀, _, _⟩ := hP.weight_unit_exists
    exact Nat.lt_of_le_of_lt (Nat.zero_le _) j₀.isLt
  -- Pointwise-symmetric flip of `SameMPV₂`: by `.symm` of each scalar
  -- equality.  No new content; just `Q ↔ P` reordering.
  have hEqual_symm : SameMPV₂ Q.toTensor P.toTensor :=
    fun N σ => (hEqual N σ).symm
  -- Apply the existing Phase-A lemma with `P` and `Q` swapped.
  obtain ⟨j, hsymDim, hGE_swapped, hNonDecay_swapped⟩ :=
    exists_unit_block_match_of_sameMPV
      (P := Q) (Q := P) hQ hP hP_pos k hUnitQ hEqual_symm
  -- `hsymDim : Q.basisDim k = P.basisDim j`; flip to the paper-stated
  -- `P.basisDim j = Q.basisDim k`.
  refine ⟨j, hsymDim.symm, ?_, ?_⟩
  · -- Gauge-phase equivalence: flip the cast direction and the
    -- equivalence direction simultaneously via `gaugePhaseEquiv_swap_cast`.
    -- `hGE_swapped : GaugePhaseEquiv (cast (congr_arg (MPSTensor d) hsymDim) (Q.basis k))
    --                                (P.basis j)`.
    -- We want `GaugePhaseEquiv (cast (congr_arg (MPSTensor d) hsymDim.symm)
    --                                  (P.basis j)) (Q.basis k)`.
    exact gaugePhaseEquiv_swap_cast hsymDim.symm
      (by
        -- `hsymDim.symm.symm = hsymDim` definitionally for `Eq`.
        simpa using hGE_swapped)
  · -- Tendsto symmetry: swap A and B in `mpvOverlap` preserves
    -- convergence to zero (`mpvOverlap A B N = star (mpvOverlap B A N)`).
    intro hTend
    apply hNonDecay_swapped
    exact tendsto_mpvOverlap_zero_swap (P.basis j) (Q.basis k) hTend

end MPSTensor
