/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.FundamentalTheorem.PaperBNT.DominantMatch

/-!
# Phase B-α and B-β (paper-faithful) strong existential and bijective matching

This module is **Phase B-α and Phase B-β** of the CPSV16/CPSV21
fundamental-theorem clean-slate plan (issue #1725).  The downstream
Phase B-γ Corollary substitution argument
(`coeff_identity_via_global_gauge`, CPSV16 §II.C lines 1187-1188) lives
in the companion module `PaperBNT/CoeffIdentity.lean` (file split in
PR #1729 to respect the 1000-line module limit).

The paper-faithful strong existential
matching theorem states the CPSV16 §II.C lines 1182–1186 *Step 1*
conclusion directly on the original (un-dropped) pair `(P, Q)` of
BNT canonical forms, iterated over each sector `k` of `Q` that carries
a unit-modulus copy.

## Paper anchor

CPSV16 (arXiv:1606.00608) §II.C lines 1182–1186, the *entire* "Step 1"
of the proof of Theorem `II_cor2` (verbatim):

> "Let us first consider $B_k$ for some given $k$.  It is not possible
> that $\langle V^{(N)}(B_k)|V^{(N)}(A_j)\rangle \to 0$ as $N\to\infty$
> for all $j$, since otherwise the MPV generated by $A$ and $B$ could
> not be proportional for all $N$ (Lemma `Lem1`).  Thus, according to
> Corollary `eqV`, there must exist one $j_k$ such that
> $|V^{(N)}(B_k)\rangle = e^{i\phi_k N} |V^{(N)}(A_{j_k})\rangle$.
> According to Lemma `equalMPS` we have $B_k = e^{i\phi_k} X_k A_{j_k} X_k^{-1}$."

The paper's "given $k$" is *iterated externally* over each unit-block
sector of `Q` (those with at least one unit-modulus weight, per the
CPSV16 §II.A line-246 normalization which is recorded **globally** —
not per-block — in `IsBNTCanonicalForm.weight_unit_exists`).  Non-unit
blocks contribute coefficients that decay exponentially and so do not
constrain the matching; the paper restricts attention to the
"physical" (unit-modulus carrying) blocks.

## Scope (Phase B-α)

The result is a **single `∀ k, ∃ j` existential statement** on the
original pair, with the paper's "given $k$" hypothesis explicitly
encoded as the unit-modulus existential.  There is **no recursion**,
no `dropSector` usage, and no combined-LI obligation on a partial
union: the entire proof routes through the existing
`exists_block_match_of_sameMPV` lemma (which itself routes
through the full-family combined LI `combined_family_eventually_li`,
`PaperBNT/Api.lean`).

The downstream Phase B-β (bijective matching) will apply this theorem
twice — once with `(P, Q)` and once with `(Q, P)` — to derive
`P.basisCount = Q.basisCount` on the unit-block subset and the per-pair
bijection / gauge data.

## Proof strategy (route B of the audit memo)

Given a sector `k` of `Q` with a unit-modulus weight, apply the
existing `exists_block_match_of_sameMPV` (`PaperBNT/DominantMatch`,
post-Phase-A rename in PR #1726) **with `P` and `Q` swapped**:

* feed `hQ`, `hP` (in that order);
* supply `hP_pos : 0 < P.basisCount` from `hP.weight_unit_exists`
  (which exists globally on `P`);
* supply the unit-modulus witness on `Q`'s `k` (the hypothesis of this
  theorem); and
* supply `SameMPV₂ Q.toTensor P.toTensor` via the trivial symmetric
  flip of `hEqual` (pointwise `.symm`).

The result is a `j₀ : Fin P.basisCount` with `Q.basisDim k = P.basisDim j₀`,
a gauge-phase equivalence in the `Q → P` cast direction, and a
non-decaying overlap in the `(Q.basis k, P.basis j₀)` order.  Two
local auxiliary lemmas (`gaugePhaseEquiv_swap_cast` and
`tendsto_mpvOverlap_zero_swap`) flip those into the paper-stated
`(P, Q)`-ordered conclusion.

All proofs in this file are closed constructively.
-/

open scoped Matrix BigOperators
open Filter Topology

namespace MPSTensor

variable {d : ℕ}

/-! ### Auxiliary symmetry and composition lemmas for `GaugePhaseEquiv`

The four lemmas below — symmetry at a fixed bond dimension, symmetry
across a bond-dimension cast, transitivity at a fixed bond dimension, and
composition through a common centre — are elementary algebraic
manipulations of the `GaugePhaseEquiv` relation.  They are used both in
the bijective-matching argument of this file and in the proportional
analogue in `PaperBNT/ProportionalMatch.lean`. -/

/-- Symmetry of `GaugePhaseEquiv` at a fixed bond dimension.

`GaugePhaseEquiv A B` says there exist a gauge `X ∈ GL` and a nonzero
scalar `ζ` such that `B i = ζ • (X * A i * X⁻¹)` for every physical
index `i`.  Conjugating by `X⁻¹` and scaling by `ζ⁻¹` gives the
reversed identity `A i = ζ⁻¹ • (X⁻¹ * B i * X)`, i.e.
`GaugePhaseEquiv B A`. -/
theorem gaugePhaseEquiv_symm_same_dim {d D : ℕ} {A B : MPSTensor d D}
    (h : GaugePhaseEquiv A B) : GaugePhaseEquiv B A := by
  classical
  obtain ⟨X, ζ, hζ, hrel⟩ := h
  refine ⟨X⁻¹, ζ⁻¹, inv_ne_zero hζ, ?_⟩
  intro i
  -- From `B i = ζ • (X * A i * X⁻¹)` derive `A i = ζ⁻¹ • (X⁻¹ * B i * X)`.
  have hBi := hrel i
  -- Abbreviations for the matrix coercions.
  set XM : Matrix (Fin D) (Fin D) ℂ := (X : Matrix (Fin D) (Fin D) ℂ)
  set XinvM : Matrix (Fin D) (Fin D) ℂ :=
    ((X⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
  have hXX : XinvM * XM = (1 : Matrix (Fin D) (Fin D) ℂ) := by
    have hU : (X⁻¹ * X : GL (Fin D) ℂ) = 1 := by simp
    have hUval :
        ((X⁻¹ * X : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
          = ((1 : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ) :=
      congrArg Units.val hU
    simp only [Units.val_mul, Units.val_one] at hUval
    exact hUval
  have hXX' : XM * XinvM = (1 : Matrix (Fin D) (Fin D) ℂ) := by
    have hU : (X * X⁻¹ : GL (Fin D) ℂ) = 1 := by simp
    have hUval :
        ((X * X⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
          = ((1 : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ) :=
      congrArg Units.val hU
    simp only [Units.val_mul, Units.val_one] at hUval
    exact hUval
  -- Inverse-of-inverse: `(X⁻¹)⁻¹ = X` for units.
  have hInvInv : ((X⁻¹)⁻¹ : GL (Fin D) ℂ) = X := inv_inv X
  -- The desired identity: `A i = ζ⁻¹ • (X⁻¹ * B i * X)`.
  -- Multiply `hBi : B i = ζ • (X * A i * X⁻¹)` on the left by `X⁻¹` and on
  -- the right by `X`:
  --   X⁻¹ * B i * X = ζ • (X⁻¹ * X * A i * X⁻¹ * X) = ζ • (1 * A i * 1) = ζ • A i.
  have hSandwich :
      XinvM * B i * XM = ζ • A i := by
    calc
      XinvM * B i * XM
          = XinvM * (ζ • (XM * A i * XinvM)) * XM := by rw [hBi]
      _ = ζ • (XinvM * (XM * A i * XinvM) * XM) := by
            simp
      _ = ζ • ((XinvM * XM) * A i * (XinvM * XM)) := by
            simp [Matrix.mul_assoc]
      _ = ζ • A i := by rw [hXX]; simp
  -- Now divide by `ζ`.
  have hAi : A i = ζ⁻¹ • (XinvM * B i * XM) := by
    have := congrArg (fun M => (ζ⁻¹ : ℂ) • M) hSandwich
    simp only [smul_smul, inv_mul_cancel₀ hζ, one_smul] at this
    exact this.symm
  -- Repackage with the inverse of `X⁻¹` being `X`.
  -- The goal expects `((X⁻¹)⁻¹ : GL).val = X.val`.
  change A i = ζ⁻¹ • (XinvM * B i *
    (((X⁻¹)⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ))
  simpa [hInvInv, XM, XinvM] using hAi

/-- Symmetry of `GaugePhaseEquiv` across a bond-dim cast: if the cast
maps the *right-hand* tensor into the *left-hand* space, then we may
flip both the cast direction and the equivalence direction.

The two forms are mathematically the same statement (after eliminating
the cast by `subst`), but the cast routing differs at the term level,
so we record this as an explicit auxiliary lemma used inside
`forall_k_exists_j_nondecaying_overlap_of_sameMPV`. -/
theorem gaugePhaseEquiv_swap_cast {d D₁ D₂ : ℕ}
    (h : D₁ = D₂) {A : MPSTensor d D₁} {B : MPSTensor d D₂}
    (hGP : GaugePhaseEquiv (cast (congr_arg (MPSTensor d) h.symm) B) A) :
    GaugePhaseEquiv (cast (congr_arg (MPSTensor d) h) A) B := by
  subst h
  -- After `subst`, both casts reduce to identity.
  simpa using gaugePhaseEquiv_symm_same_dim (by simpa using hGP)

/-! ### Phase B-α main theorem: paper-faithful full-basis matching -/

/-- **CPSV16 §II.C lines 1182–1186 Step 1 (full-basis form).**

For every sector `k` of `Q`, there exists a sector `j` of `P` of equal
bond dimension, gauge-phase equivalent to `Q.basis k` after the dimension
cast, and with non-decaying cross-overlap.

The proof iterates `exists_block_match_of_sameMPV` over every `Q`-sector
with `(P, Q)` swapped, so it consumes the per-block unit-modulus
witnesses on the *swapped* side, namely `hUnitQ : ∀ k, ∃ q, ‖μ_{k,q}‖ = 1`
for $Q$.  The per-block unit-modulus convention is paper-implicit in
CPSV16 §II.C line 1182's projection argument; it is taken here as an
explicit theorem-level hypothesis (CPSV16 §II.A line 246 records only
the global unit witness).

Paper anchor: CPSV16 §II.C lines 1182–1186 (arXiv:1606.00608) and CPSV21
Definition 4.3 lines 1846–1884. -/
theorem forall_k_exists_j_nondecaying_overlap_of_sameMPVPos
    {P Q : SectorDecomposition d}
    (hP : IsBNTCanonicalForm P) (hQ : IsBNTCanonicalForm Q)
    (hUnitQ : ∀ k : Fin Q.basisCount, ∃ q : Fin (Q.copies k), ‖Q.weight k q‖ = 1)
    (hEqual : SameMPV₂Pos P.toTensor Q.toTensor) :
    ∀ k : Fin Q.basisCount, ∃ (j : Fin P.basisCount) (h : P.basisDim j = Q.basisDim k),
      GaugePhaseEquiv
          (cast (congr_arg (MPSTensor d) h) (P.basis j))
          (Q.basis k) ∧
      ¬ Tendsto (fun N : ℕ =>
          mpvOverlap (d := d) (P.basis j) (Q.basis k) N)
        atTop (𝓝 0) := by
  classical
  intro k
  -- `P.basisCount > 0`: the global unit witness on `P` supplies a sector index.
  have hP_pos : 0 < P.basisCount := by
    obtain ⟨j₀, _, _⟩ := hP.weight_unit_exists
    exact Nat.lt_of_le_of_lt (Nat.zero_le _) j₀.isLt
  have hQ_pos : 0 < Q.basisCount := Nat.lt_of_le_of_lt (Nat.zero_le _) k.isLt
  have hEqual_symm : SameMPV₂Pos Q.toTensor P.toTensor := hEqual.symm
  obtain ⟨j, hsymDim, hGE_swapped, hNonDecay_swapped⟩ :=
    exists_block_match_of_sameMPVPos
      (P := Q) (Q := P) hQ hP k (hUnitQ k) hQ_pos hP_pos hEqual_symm
  refine ⟨j, hsymDim.symm, ?_, ?_⟩
  · exact gaugePhaseEquiv_swap_cast hsymDim.symm
      (by simpa using hGE_swapped)
  · intro hTend
    apply hNonDecay_swapped
    exact tendsto_mpvOverlap_zero_swap (P.basis j) (Q.basis k) hTend

/-- Reformulation for the all-length `SameMPV₂` form. -/
theorem forall_k_exists_j_nondecaying_overlap_of_sameMPV
    {P Q : SectorDecomposition d}
    (hP : IsBNTCanonicalForm P) (hQ : IsBNTCanonicalForm Q)
    (hUnitQ : ∀ k : Fin Q.basisCount, ∃ q : Fin (Q.copies k), ‖Q.weight k q‖ = 1)
    (hEqual : SameMPV₂ P.toTensor Q.toTensor) :
    ∀ k : Fin Q.basisCount, ∃ (j : Fin P.basisCount) (h : P.basisDim j = Q.basisDim k),
      GaugePhaseEquiv
          (cast (congr_arg (MPSTensor d) h) (P.basis j))
          (Q.basis k) ∧
      ¬ Tendsto (fun N : ℕ =>
          mpvOverlap (d := d) (P.basis j) (Q.basis k) N)
        atTop (𝓝 0) :=
  forall_k_exists_j_nondecaying_overlap_of_sameMPVPos
    (P := P) (Q := Q) hP hQ hUnitQ hEqual.toSameMPV₂Pos

/-! ### Composition of `GaugePhaseEquiv` through a common centre

The bijective-matching proof composes two gauge-phase equivalences
`(P.basis j) ↔ (Q.basis k₁)` and `(P.basis j) ↔ (Q.basis k₂)` through the
common centre `P.basis j` to derive an equivalence
`(Q.basis k₁) ↔ (Q.basis k₂)`.  The `basis_distinct` field of
`IsBNTCanonicalForm` then forces `k₁ = k₂` (injectivity of the matching). -/

/-- Transitivity of `GaugePhaseEquiv` at a fixed bond dimension.

If `B i = ζ₁ • (X₁ * A i * X₁⁻¹)` and `C i = ζ₂ • (X₂ * B i * X₂⁻¹)`,
then `C i = (ζ₂ ζ₁) • ((X₂ X₁) * A i * (X₂ X₁)⁻¹)`, giving
`GaugePhaseEquiv A C` with gauge `X₂ * X₁` and phase scalar `ζ₂ * ζ₁`. -/
theorem gaugePhaseEquiv_trans_same_dim {d D : ℕ} {A B C : MPSTensor d D}
    (h₁ : GaugePhaseEquiv A B) (h₂ : GaugePhaseEquiv B C) : GaugePhaseEquiv A C := by
  classical
  obtain ⟨X₁, ζ₁, hζ₁, hr₁⟩ := h₁
  obtain ⟨X₂, ζ₂, hζ₂, hr₂⟩ := h₂
  refine ⟨X₂ * X₁, ζ₂ * ζ₁, mul_ne_zero hζ₂ hζ₁, ?_⟩
  intro i
  -- Abbreviations for the matrix coercions of the four GL units in play.
  set X₁M : Matrix (Fin D) (Fin D) ℂ :=
    ((X₁ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
  set X₂M : Matrix (Fin D) (Fin D) ℂ :=
    ((X₂ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
  set X₁invM : Matrix (Fin D) (Fin D) ℂ :=
    ((X₁⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
  set X₂invM : Matrix (Fin D) (Fin D) ℂ :=
    ((X₂⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)
  -- Coercion of the product `X₂ * X₁` to a matrix is the matrix product.
  have hMul_val :
      (((X₂ * X₁ : GL (Fin D) ℂ)) : Matrix (Fin D) (Fin D) ℂ) = X₂M * X₁M := by
    simp [X₁M, X₂M]
  -- Coercion of the inverse of the product is the reversed product of inverses.
  have hMulInv_val :
      (((X₂ * X₁)⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ) = X₁invM * X₂invM := by
    have hRev : ((X₂ * X₁)⁻¹ : GL (Fin D) ℂ) = X₁⁻¹ * X₂⁻¹ := mul_inv_rev X₂ X₁
    have := congrArg (fun U : GL (Fin D) ℂ =>
        (U : Matrix (Fin D) (Fin D) ℂ)) hRev
    simp [X₁invM, X₂invM]
  -- Compute `C i` by chaining the two equivalences.
  calc C i
      = ζ₂ • (X₂M * B i * X₂invM) := hr₂ i
    _ = ζ₂ • (X₂M * (ζ₁ • (X₁M * A i * X₁invM)) * X₂invM) := by rw [hr₁ i]
    _ = ζ₂ • (ζ₁ • (X₂M * (X₁M * A i * X₁invM) * X₂invM)) := by
          simp [smul_smul]
    _ = (ζ₂ * ζ₁) • (X₂M * X₁M * A i * X₁invM * X₂invM) := by
          simp [smul_smul, Matrix.mul_assoc]
    _ = (ζ₂ * ζ₁) • ((X₂M * X₁M) * A i * (X₁invM * X₂invM)) := by
          simp [Matrix.mul_assoc]
    _ = (ζ₂ * ζ₁) •
          ((((X₂ * X₁ : GL (Fin D) ℂ)) : Matrix (Fin D) (Fin D) ℂ) * A i *
            (((X₂ * X₁)⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)) := by
          rw [hMul_val, hMulInv_val]

/-- Composition through a common centre `A`: if the cast `D = D₁` carries
`A : MPSTensor d D` into a gauge-phase equivalence with `B : MPSTensor d D₁`,
and similarly the cast `D = D₂` carries `A` into a gauge-phase equivalence
with `C : MPSTensor d D₂`, then `B` and `C` are gauge-phase equivalent
(after the dimension cast `D₁ = D₂`).

This is the cast-aware transitivity used in Phase B-β to derive
`GaugePhaseEquiv (Q.basis k₁) (Q.basis k₂)` (up to cast) from two
matchings against the same `P.basis j`, before invoking `basis_distinct`
of `Q` to force `k₁ = k₂`. -/
theorem gaugePhaseEquiv_cast_compose_via_centre
    {d D D₁ D₂ : ℕ}
    (h₁ : D = D₁) (h₂ : D = D₂)
    {A : MPSTensor d D} {B : MPSTensor d D₁} {C : MPSTensor d D₂}
    (GE₁ : GaugePhaseEquiv (cast (congr_arg (MPSTensor d) h₁) A) B)
    (GE₂ : GaugePhaseEquiv (cast (congr_arg (MPSTensor d) h₂) A) C) :
    GaugePhaseEquiv
        (cast (congr_arg (MPSTensor d) (h₁.symm.trans h₂)) B) C := by
  subst h₁
  -- After `subst h₁`, `D₁` is replaced everywhere by `D`, the cast on
  -- `GE₁` reduces to identity, and `h₂.symm.trans h₂ = h₂`.
  subst h₂
  -- After `subst h₂`, all three tensors live in `MPSTensor d D`.
  simp only [cast_eq] at GE₁ GE₂ ⊢
  exact gaugePhaseEquiv_trans_same_dim (gaugePhaseEquiv_symm_same_dim GE₁) GE₂

/-! ### Phase B-β main theorem: full bijective matching by symmetry -/

/-- **CPSV16 §II.C lines 1184–1186 full-basis bijection.**

Applying `forall_k_exists_j_nondecaying_overlap_of_sameMPV` in both
directions gives injective maps `Fin Q.basisCount → Fin P.basisCount` and
`Fin P.basisCount → Fin Q.basisCount`.  Finite cardinal comparison turns
the forward injection into an equivalence `β : Fin Q.basisCount ≃
Fin P.basisCount`, carrying the matched bond-dimension equality,
gauge-phase equivalence, and non-decaying overlap for every sector of `Q`.

This is the Lean counterpart of the CPSV16 symmetry step "$g_A \geq g_B$
and $g_B \geq g_A$".  The proof invokes
`forall_k_exists_j_nondecaying_overlap_of_sameMPV` once with $(P,Q)$ and
once with $(Q,P)$, hence it consumes per-block unit-modulus witnesses on
both sides: `hUnitP : ∀ j, ∃ q, ‖μ_{j,q}^P‖ = 1` and `hUnitQ : ∀ k, ∃ q,
‖μ_{k,q}^Q‖ = 1`.  These are paper-implicit in CPSV16 §II.C line 1182's
projection argument and are taken as explicit theorem-level hypotheses
here (CPSV16 §II.A line 246 records only the global unit witness). -/
theorem bijective_match_of_sameMPVPos
    {P Q : SectorDecomposition d}
    (hP : IsBNTCanonicalForm P) (hQ : IsBNTCanonicalForm Q)
    (hUnitP : ∀ j : Fin P.basisCount, ∃ q : Fin (P.copies j), ‖P.weight j q‖ = 1)
    (hUnitQ : ∀ k : Fin Q.basisCount, ∃ q : Fin (Q.copies k), ‖Q.weight k q‖ = 1)
    (hEqual : SameMPV₂Pos P.toTensor Q.toTensor) :
    ∃ β : Fin Q.basisCount ≃ Fin P.basisCount,
      ∀ k : Fin Q.basisCount, ∃ h : P.basisDim (β k) = Q.basisDim k,
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) h) (P.basis (β k)))
            (Q.basis k) ∧
        ¬ Tendsto (fun N : ℕ =>
            mpvOverlap (d := d) (P.basis (β k)) (Q.basis k) N)
          atTop (𝓝 0) := by
  classical
  have hFwd :=
    forall_k_exists_j_nondecaying_overlap_of_sameMPVPos hP hQ hUnitQ hEqual
  have hEqual_symm : SameMPV₂Pos Q.toTensor P.toTensor := hEqual.symm
  have hBwd :=
    forall_k_exists_j_nondecaying_overlap_of_sameMPVPos hQ hP hUnitP hEqual_symm
  let φ₀ : Fin Q.basisCount → Fin P.basisCount := fun k => (hFwd k).choose
  have φ₀_spec : ∀ k : Fin Q.basisCount,
      ∃ h : P.basisDim (φ₀ k) = Q.basisDim k,
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) h) (P.basis (φ₀ k)))
            (Q.basis k) ∧
        ¬ Tendsto (fun N : ℕ =>
            mpvOverlap (d := d) (P.basis (φ₀ k)) (Q.basis k) N)
          atTop (𝓝 0) := fun k => (hFwd k).choose_spec
  have rebase_centre_P :
      ∀ (j j' : Fin P.basisCount) (_hj : j = j')
        {kv : Fin Q.basisCount}
        (h_t : P.basisDim j' = Q.basisDim kv)
        (_GE : GaugePhaseEquiv
                  (cast (congr_arg (MPSTensor d) h_t) (P.basis j')) (Q.basis kv)),
        ∃ h_t' : P.basisDim j = Q.basisDim kv,
          GaugePhaseEquiv
              (cast (congr_arg (MPSTensor d) h_t') (P.basis j)) (Q.basis kv) := by
    rintro _ _ rfl _ h_t GE
    exact ⟨h_t, GE⟩
  have hφ₀_inj : Function.Injective φ₀ := by
    intro k₁ k₂ hjEq
    obtain ⟨h₁, GE₁, _⟩ := φ₀_spec k₁
    obtain ⟨h₂, GE₂, _⟩ := φ₀_spec k₂
    by_contra hne
    obtain ⟨h₂', GE₂'⟩ :=
      rebase_centre_P (φ₀ k₁) (φ₀ k₂) hjEq h₂ GE₂
    have hQdim : Q.basisDim k₁ = Q.basisDim k₂ := h₁.symm.trans h₂'
    have hQGE :
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) hQdim) (Q.basis k₁))
            (Q.basis k₂) :=
      gaugePhaseEquiv_cast_compose_via_centre (A := P.basis (φ₀ k₁))
        (B := Q.basis k₁) (C := Q.basis k₂) h₁ h₂' GE₁ GE₂'
    exact hQ.basis_distinct k₁ k₂ hne hQdim hQGE
  let ψ₀ : Fin P.basisCount → Fin Q.basisCount := fun j => (hBwd j).choose
  have ψ₀_spec : ∀ j : Fin P.basisCount,
      ∃ h : Q.basisDim (ψ₀ j) = P.basisDim j,
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) h) (Q.basis (ψ₀ j)))
            (P.basis j) ∧
        ¬ Tendsto (fun N : ℕ =>
            mpvOverlap (d := d) (Q.basis (ψ₀ j)) (P.basis j) N)
          atTop (𝓝 0) := fun j => (hBwd j).choose_spec
  have rebase_centre_Q :
      ∀ (k k' : Fin Q.basisCount) (_hk : k = k')
        {jv : Fin P.basisCount}
        (h_t : Q.basisDim k' = P.basisDim jv)
        (_GE : GaugePhaseEquiv
                  (cast (congr_arg (MPSTensor d) h_t) (Q.basis k')) (P.basis jv)),
        ∃ h_t' : Q.basisDim k = P.basisDim jv,
          GaugePhaseEquiv
              (cast (congr_arg (MPSTensor d) h_t') (Q.basis k)) (P.basis jv) := by
    rintro _ _ rfl _ h_t GE
    exact ⟨h_t, GE⟩
  have hψ₀_inj : Function.Injective ψ₀ := by
    intro j₁ j₂ hkEq
    obtain ⟨h₁, GE₁, _⟩ := ψ₀_spec j₁
    obtain ⟨h₂, GE₂, _⟩ := ψ₀_spec j₂
    by_contra hne
    obtain ⟨h₂', GE₂'⟩ :=
      rebase_centre_Q (ψ₀ j₁) (ψ₀ j₂) hkEq h₂ GE₂
    have hPdim : P.basisDim j₁ = P.basisDim j₂ := h₁.symm.trans h₂'
    have hPGE :
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) hPdim) (P.basis j₁))
            (P.basis j₂) :=
      gaugePhaseEquiv_cast_compose_via_centre (A := Q.basis (ψ₀ j₁))
        (B := P.basis j₁) (C := P.basis j₂) h₁ h₂' GE₁ GE₂'
    exact hP.basis_distinct j₁ j₂ hne hPdim hPGE
  have hCardQP : Fintype.card (Fin Q.basisCount) ≤ Fintype.card (Fin P.basisCount) :=
    Fintype.card_le_of_injective φ₀ hφ₀_inj
  have hCardPQ : Fintype.card (Fin P.basisCount) ≤ Fintype.card (Fin Q.basisCount) :=
    Fintype.card_le_of_injective ψ₀ hψ₀_inj
  have hCard : Fintype.card (Fin Q.basisCount) = Fintype.card (Fin P.basisCount) :=
    le_antisymm hCardQP hCardPQ
  have hφ₀_bij : Function.Bijective φ₀ :=
    (Fintype.bijective_iff_injective_and_card φ₀).2 ⟨hφ₀_inj, hCard⟩
  let β : Fin Q.basisCount ≃ Fin P.basisCount := Equiv.ofBijective φ₀ hφ₀_bij
  refine ⟨β, ?_⟩
  intro k
  simpa [β] using φ₀_spec k

/-- Reformulation for the all-length `SameMPV₂` form. -/
theorem bijective_match_of_sameMPV
    {P Q : SectorDecomposition d}
    (hP : IsBNTCanonicalForm P) (hQ : IsBNTCanonicalForm Q)
    (hUnitP : ∀ j : Fin P.basisCount, ∃ q : Fin (P.copies j), ‖P.weight j q‖ = 1)
    (hUnitQ : ∀ k : Fin Q.basisCount, ∃ q : Fin (Q.copies k), ‖Q.weight k q‖ = 1)
    (hEqual : SameMPV₂ P.toTensor Q.toTensor) :
    ∃ β : Fin Q.basisCount ≃ Fin P.basisCount,
      ∀ k : Fin Q.basisCount, ∃ h : P.basisDim (β k) = Q.basisDim k,
        GaugePhaseEquiv
            (cast (congr_arg (MPSTensor d) h) (P.basis (β k)))
            (Q.basis k) ∧
        ¬ Tendsto (fun N : ℕ =>
            mpvOverlap (d := d) (P.basis (β k)) (Q.basis k) N)
          atTop (𝓝 0) :=
  bijective_match_of_sameMPVPos
    (P := P) (Q := Q) hP hQ hUnitP hUnitQ hEqual.toSameMPV₂Pos


end MPSTensor
