/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import TNLean.MPS.MPDO.OperatorProduct

/-!
# The action tensor of a matrix product operator on a matrix product state

Contracting the bra index of an MPO tensor with the physical index of an MPS tensor and taking
the Kronecker product of the bond spaces produces the tensor
\[
  (T \cdot A)^{i} = \sum_{j} T^{ij} \otimes A^{j},
\]
which generates the state obtained by applying the periodic operator of `T` to the periodic
state of `A`.  This is the tensor whose local decomposition is described by the action tensors
of Garre-Rubio--Lootens--Molnár, arXiv:2203.12563, equation `mpoMPSsten`, lines 1070--1090.

The contraction convention is the one already used for the bond-one instance
`MPOTensor.CZX.actedSector` in `TNLean/MPS/MPDO/CZXActionTensors.lean`, where the Kronecker
factor of the state bond space is trivial.

## Main definitions

* `MPOTensor.actTensor`: the action tensor `(T · A)^i = ∑_j T^{ij} ⊗ A^j`.

## Main results

* `MPOTensor.evalWord_actTensor`: word evaluation of the action tensor is the sum over the
  contracted bra configurations of the Kronecker products of the two word evaluations.
* `MPOTensor.mpv_actTensor`: the periodic vector of the action tensor is the periodic operator
  of `T` applied to the periodic vector of `A`.
* `MPOTensor.mpo_mulVec_mpv`: the same identity read as a matrix-vector product.

## References

* J. Garre-Rubio, L. Lootens, A. Molnár, arXiv:2203.12563, Section "Periodic boundary condition
  case", equation `mpoMPSsten`.
-/

open scoped Matrix BigOperators Kronecker
open Matrix

namespace MPOTensor

variable {d D₁ D₂ : ℕ}

/-! ### The action tensor -/

/-- The **action tensor** of an MPO tensor on an MPS tensor: contract the bra index of the
operator with the physical index of the state and take the Kronecker product of the bond
spaces, `(T · A)^i = ∑ j, T^{ij} ⊗ A^j`.  The bond space `Fin (D₁ * D₂)` is identified with
`Fin D₁ × Fin D₂` via `finProdFinEquiv`, as for `MPOTensor.mulTensor`.

Source: arXiv:2203.12563, equation `mpoMPSsten`, lines 1070--1090 (the tensor whose local
decomposition onto the image block is given by the action tensors). -/
noncomputable def actTensor (T : MPOTensor d D₁) (A : MPSTensor d D₂) :
    MPSTensor d (D₁ * D₂) :=
  fun i => (∑ j : Fin d, (T i j) ⊗ₖ (A j)).submatrix
    finProdFinEquiv.symm finProdFinEquiv.symm

@[simp] lemma actTensor_apply (T : MPOTensor d D₁) (A : MPSTensor d D₂) (i : Fin d) :
    actTensor T A i = (∑ j : Fin d, (T i j) ⊗ₖ (A j)).submatrix
      finProdFinEquiv.symm finProdFinEquiv.symm := rfl

/-- Word evaluation of the action tensor is a sum over the contracted bra configurations of
Kronecker products of word evaluations.

Source: arXiv:2203.12563, equation `mpoMPSsten`, lines 1070--1090. -/
theorem evalWord_actTensor (T : MPOTensor d D₁) (A : MPSTensor d D₂) {L : ℕ}
    (σ : Fin L → Fin d) :
    Kraus.evalWord (actTensor T A) (List.ofFn σ) =
      (∑ τ : Fin L → Fin d,
        (evalWord T (List.ofFn σ) (List.ofFn τ)) ⊗ₖ
          Kraus.evalWord A (List.ofFn τ)).submatrix
        finProdFinEquiv.symm finProdFinEquiv.symm := by
  induction L with
  | zero =>
    simp only [List.ofFn_zero, Kraus.evalWord_nil, evalWord_nil, Fintype.sum_unique]
    rw [Matrix.kroneckerMap_one_one (· * ·) (fun _ => zero_mul _)
      (fun _ => mul_zero _) (one_mul 1), Matrix.submatrix_one_equiv]
  | succ n ih =>
    simp only [List.ofFn_succ, Kraus.evalWord_cons]
    rw [actTensor_apply]
    have ih_step := ih (σ ∘ Fin.succ)
    simp only [Function.comp_def] at ih_step
    rw [ih_step, Matrix.submatrix_mul_equiv _ _ _ finProdFinEquiv.symm _]
    congr 1
    rw [Finset.sum_mul]
    simp_rw [Finset.mul_sum, ← Matrix.mul_kronecker_mul]
    have reindex : ∀ (F : (Fin (n + 1) → Fin d) →
        Matrix (Fin D₁ × Fin D₂) (Fin D₁ × Fin D₂) ℂ),
        ∑ τ, F τ = ∑ j : Fin d, ∑ τ' : Fin n → Fin d, F (Fin.cons j τ') :=
      fun F => by
        rw [← Fintype.sum_prod_type']
        exact ((Fin.consEquiv (fun _ : Fin (n + 1) => Fin d)).sum_comp F).symm
    symm
    rw [reindex]
    refine Finset.sum_congr rfl fun j _ => Finset.sum_congr rfl fun τ' _ => ?_
    simp only [Fin.cons_zero, Fin.cons_succ, evalWord_cons]

/-! ### The periodic state generated by the action tensor -/

/-- **The action tensor generates the acted state.** The periodic vector of the action tensor
is the periodic operator of `T` applied to the periodic vector of `A`.

Source: arXiv:2203.12563, Section "Periodic boundary condition case", lines 1070--1078
(the relation `U_g |ψ_{A_x}⟩ = |ψ_{A_y}⟩` whose local form is `mpoMPSsten`). -/
theorem mpv_actTensor (T : MPOTensor d D₁) (A : MPSTensor d D₂) {L : ℕ}
    (σ : Fin L → Fin d) :
    MPSTensor.mpv (actTensor T A) σ =
      ∑ τ : Fin L → Fin d, mpo T L σ τ * MPSTensor.mpv A τ := by
  simp only [MPSTensor.mpv, MPSTensor.coeff, mpo_apply, mpoMatrixEntry]
  rw [evalWord_actTensor, Matrix.trace_submatrix_equiv, Matrix.trace_sum]
  simp_rw [Matrix.trace_kronecker]

/-- The identity `MPOTensor.mpv_actTensor` read as a matrix-vector product: the periodic
operator of `T` applied to the periodic vector of `A` is the periodic vector of the action
tensor.

Source: arXiv:2203.12563, Section "Periodic boundary condition case", lines 1070--1078. -/
theorem mpo_mulVec_mpv (T : MPOTensor d D₁) (A : MPSTensor d D₂) (L : ℕ) :
    mpo T L *ᵥ (fun τ : Fin L → Fin d => MPSTensor.mpv A τ) =
      fun σ : Fin L → Fin d => MPSTensor.mpv (actTensor T A) σ := by
  funext σ
  rw [mpv_actTensor]
  rfl

end MPOTensor
