/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.MPDO.BNTCoefficients
import TNLean.MPS.MPDO.OperatorProduct

/-!
# The fusion isometries of Theorem IV.13(iii)

Statement (iii) of Theorem IV.13 of arXiv:1606.00608 asserts the existence of
isometries $U_{\alpha,\beta}$ with
\[
  U_{\alpha,\beta}\, M_\alpha M_\beta\, U_{\alpha,\beta}^\dagger
    = \bigoplus_\gamma \chi_{\alpha,\beta,\gamma} \otimes M_\gamma,
\]
where the $M_\gamma$ are the basis of normal tensors of the vertically read
tensor (Proposition IV.12) and the $\chi_{\alpha,\beta,\gamma}$ are the
positive diagonal matrices of statement (ii). `BNTFusionIsometryFamily`
records exactly this: a labelled family of tensors whose physical dimension
is the original bond dimension, the diagonal chi matrices with positive
entries, and per-pair isometries conjugating the product tensor onto the
weighted direct sum, site by site. Statement (iii) additionally asserts the
idempotent identity for the trace scalars of the vertical decomposition; that
condition is recorded separately by the idempotent coefficient predicate of
`TNLean.MPS.MPDO.BNTCoefficients`.

From the fusion identity the same-length product law of statement (ii)
follows for the concrete operator family: for every positive chain length,
\[
  O_L(M_\alpha)\,O_L(M_\beta)
    = \sum_\gamma \operatorname{tr}(\chi_{\alpha,\beta,\gamma}^{L})\,
        O_L(M_\gamma).
\]
This is the derivation of eq (eq:algebra) from eq (Ualphabeta): the product
of the operators is generated by the product tensor, isometric conjugation
does not change the closed-trace word evaluations, and the word evaluation of
the fused tensor splits block by block with the chi factors accumulating into
matrix powers.

The family is hypothesis-carrying: nothing here constructs the tensors, the
chi matrices, or the isometries from an MPDO tensor. That construction is
the Appendix C.3--C.4 obligation recorded in
`docs/paper-gaps/cpgsv17_blocked_chi_uniformity.tex`.

## References

* [Cirac--Perez-Garcia--Schuch--Verstraete 2017] arXiv:1606.00608,
  Theorem IV.13(iii), lines 986--993, and Appendix C.4, lines 2015--2065
-/

open scoped Matrix BigOperators ComplexOrder Kronecker
open Matrix

namespace MPOTensor

/-- The fusion-isometry family of arXiv:1606.00608, Theorem IV.13(iii),
eq (Ualphabeta): a family of tensors indexed by BNT labels, positive diagonal
chi matrices, and per-pair isometries conjugating the product tensor onto the
chi-weighted direct sum of the labelled tensors.

The tensors are the vertically read basis of normal tensors of
Proposition IV.12: the physical dimension `p` is the bond dimension of the
original tensor, and each label carries its own bond dimension. The direct
sum is realized block-diagonally over the labels, with the block of label
`γ` the Kronecker product of the diagonal matrix `χ_{α,β,γ}` and the letter
of the tensor of `γ`.

Source: arXiv:1606.00608, Theorem IV.13(iii), lines 986--993 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
structure BNTFusionIsometryFamily (Λ : Type*) [Fintype Λ] [DecidableEq Λ]
    (p : ℕ) where
  /-- Bond dimension of the tensor of each label.

  Source: arXiv:1606.00608, Theorem IV.13(iii), lines 986--993 of
  `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  bondDim : Λ → ℕ
  /-- The labelled family of tensors, with common physical dimension `p`.

  Source: arXiv:1606.00608, Theorem IV.13(iii), lines 986--993, and
  Proposition IV.12, lines 944--953 of
  `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  tensor : ∀ γ : Λ, MPOTensor p (bondDim γ)
  /-- The diagonal chi matrices `χ_{α,β,γ}`.

  Source: arXiv:1606.00608, Theorem IV.13(ii)--(iii), lines 976--993 of
  `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  chi : DiagonalChiFamily Λ
  /-- Positivity of the diagonal entries, as in Theorem IV.13(ii).

  Source: arXiv:1606.00608, Theorem IV.13(ii), lines 976--985 of
  `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  posEntries : chi.PosEntries
  /-- The fusion maps `U_{α,β}` from the bond space of the product tensor to
  the bond space of the chi-weighted direct sum.

  Source: arXiv:1606.00608, Theorem IV.13(iii), lines 986--993 of
  `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  fusionIsometry : ∀ α β : Λ,
    Matrix ((γ : Λ) × (Fin (chi.dim α β γ) × Fin (bondDim γ)))
      (Fin (bondDim α * bondDim β)) ℂ
  /-- Each fusion map is an isometry.

  Source: arXiv:1606.00608, Theorem IV.13(iii), lines 986--993 of
  `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  isometry : ∀ α β : Λ, (fusionIsometry α β)ᴴ * fusionIsometry α β = 1
  /-- The fusion identity, site by site:
  `U_{α,β} (M_α M_β)^{ij} U_{α,β}† = ⊕_γ χ_{α,β,γ} ⊗ M_γ^{ij}`.

  Source: arXiv:1606.00608, Theorem IV.13(iii), eq (Ualphabeta),
  lines 986--993 of `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  fusion : ∀ (α β : Λ) (i j : Fin p),
    fusionIsometry α β * (mulTensor (tensor α) (tensor β)) i j *
        (fusionIsometry α β)ᴴ =
      Matrix.blockDiagonal' fun γ => chi.matrix α β γ ⊗ₖ tensor γ i j

namespace BNTFusionIsometryFamily

variable {Λ : Type*} [Fintype Λ] [DecidableEq Λ] {p : ℕ}
variable (Fam : BNTFusionIsometryFamily Λ p)

/-- **The same-length product law with trace-power coefficients**: for every
positive chain length, the product of two labelled operators expands over the
labels with coefficients `tr(χ_{α,β,γ}^L)`. This derives eq (eq:algebra) of
Theorem IV.13(ii) from the fusion identity of Theorem IV.13(iii).

Source: arXiv:1606.00608, lines 976--993, and Appendix C.4,
lines 2015--2037 of `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
theorem mpo_mul_mpo_eq_sum (L : ℕ) (hL : 0 < L) (α β : Λ) :
    mpo (Fam.tensor α) L * mpo (Fam.tensor β) L =
      ∑ γ : Λ, Fam.chi.tracePowerCoeff α β γ L • mpo (Fam.tensor γ) L := by
  obtain ⟨n, rfl⟩ : ∃ n, L = n + 1 := ⟨L - 1, (Nat.succ_pred_eq_of_pos hL).symm⟩
  rw [← mpo_mulTensor]
  ext σ τ
  rw [mpo_apply, mpoMatrixEntry, evalWord_ofFn]
  set U := Fam.fusionIsometry α β with hUdef
  have hUiso : Uᴴ * U = 1 := Fam.isometry α β
  have hletters : (fun l : Fin (n + 1) =>
      U * mulTensor (Fam.tensor α) (Fam.tensor β) (σ l) (τ l) * Uᴴ) =
      fun l => Matrix.blockDiagonal'
        fun γ => Fam.chi.matrix α β γ ⊗ₖ Fam.tensor γ (σ l) (τ l) := by
    funext l
    exact Fam.fusion α β (σ l) (τ l)
  have hconj := listProd_conj_of_conjTranspose_mul_self U hUiso
    (fun l => mulTensor (Fam.tensor α) (Fam.tensor β) (σ l) (τ l))
  set P := (List.ofFn fun l =>
    mulTensor (Fam.tensor α) (Fam.tensor β) (σ l) (τ l)).prod with hPdef
  have htraceP : Matrix.trace P =
      Matrix.trace ((List.ofFn fun l => Matrix.blockDiagonal'
        fun γ => Fam.chi.matrix α β γ ⊗ₖ Fam.tensor γ (σ l) (τ l)).prod) := by
    rw [← hletters, hconj, Matrix.trace_mul_comm, ← Matrix.mul_assoc, hUiso,
      Matrix.one_mul]
  rw [htraceP, listProd_blockDiagonal'_kronecker, Matrix.trace_blockDiagonal']
  simp_rw [Matrix.trace_kronecker, Fam.chi.trace_matrix_pow]
  simp only [Matrix.sum_apply, Matrix.smul_apply, mpo_apply, mpoMatrixEntry,
    evalWord_ofFn, smul_eq_mul]

/-- The concrete MPO operator family of the labelled tensors,
`O_L(M_γ) = mpo (M_γ) L`.

Source: arXiv:1606.00608, lines 962--966 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
noncomputable def toOperatorFamily :
    BNTLabelOperatorFamily Λ
      (fun L => Matrix (Fin L → Fin p) (Fin L → Fin p) ℂ) :=
  ⟨fun L γ => mpo (Fam.tensor γ) L⟩

@[simp] lemma toOperatorFamily_operator (L : ℕ) (γ : Λ) :
    Fam.toOperatorFamily.operator L γ = mpo (Fam.tensor γ) L := rfl

/-- A fusion-isometry family satisfies the same-length product form with the
coefficient family canonically determined by its chi matrices. This provides
the product-law input of the Theorem IV.13(ii) coefficient statements for the
concrete operator family.

Source: arXiv:1606.00608, Theorem IV.13(ii)--(iii), lines 976--993 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
theorem toOperatorFamily_hasSameLengthProductForm :
    Fam.toOperatorFamily.HasSameLengthProductForm
      (BNTLabelCoefficientFamily.ofChi Fam.chi) := by
  intro L hL α β
  simpa [toOperatorFamily_operator, BNTLabelCoefficientFamily.ofChi_coeff]
    using Fam.mpo_mul_mpo_eq_sum L hL α β

/-- The positive chi witness for the coefficient family canonically
determined by the chi matrices of a fusion-isometry family.

Source: arXiv:1606.00608, Theorem IV.13(ii), lines 976--985 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
noncomputable def toPositiveChiWitness :
    PositiveBNTLabelChiTracePowerForm
      (BNTLabelCoefficientFamily.ofChi Fam.chi) :=
  PositiveBNTLabelChiTracePowerForm.ofChi Fam.chi Fam.posEntries

end BNTFusionIsometryFamily

end MPOTensor
