/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.MPDO.LengthIndependentCoefficients
import TNLean.MPS.MPDO.OperatorProduct
import TNLean.MPS.MPDO.BNTTheoremData

/-!
# The fusion isometries of Theorem IV.13(iii)

This file studies the full-support specialization of statement (iii) of
Theorem IV.13 of arXiv:1606.00608. It assumes matrices $U_{\alpha,\beta}$ with
\[
  U_{\alpha,\beta}\, M_\alpha M_\beta\, U_{\alpha,\beta}^\dagger
    = \bigoplus_\gamma \chi_{\alpha,\beta,\gamma} \otimes M_\gamma,
\]
where the $M_\gamma$ are the basis of normal tensors of the vertically read
tensor (Proposition IV.12) and the $\chi_{\alpha,\beta,\gamma}$ are the
positive diagonal matrices of statement (ii). `BNTFusionIsometryFamily`
records exactly this: a labelled family of tensors whose physical dimension
is the original bond dimension, the diagonal chi matrices with positive
entries, and per-pair isometries conjugating the product tensor onto the
weighted direct sum, site by site. Statement (iii) additionally asserts the
idempotent identity for the trace scalars of the vertical decomposition; that
condition is recorded separately by the idempotent coefficient predicate of
`TNLean.MPS.MPDO.BNTCoefficients`.

The fusion identity and $U_{\alpha,\beta}^\dagger U_{\alpha,\beta}=1$ also give the two
chi-weighted zipper equations
\[
  U_{\alpha,\beta}(M_\alpha M_\beta)^{ij}=G_{\alpha,\beta}^{ij}U_{\alpha,\beta},
  \qquad
  (M_\alpha M_\beta)^{ij}U_{\alpha,\beta}^\dagger
    =U_{\alpha,\beta}^\dagger G_{\alpha,\beta}^{ij},
\]
where $G_{\alpha,\beta}^{ij}=\bigoplus_\gamma
\chi_{\alpha,\beta,\gamma}\otimes M_\gamma^{ij}$.  These are weighted analogues of the zipper
condition of arXiv:1511.08090; the unweighted condition requires a separate specialization of
the chi matrices, proved below under length independence of the trace-power coefficients.

From the fusion identity the same-length product law of statement (ii)
follows for the concrete operator family: for every positive chain length,
\[
  O_L(M_\alpha)\,O_L(M_\beta)
    = \sum_\gamma \operatorname{tr}(\chi_{\alpha,\beta,\gamma}^{L})\,
        O_L(M_\gamma).
\]
This derives the product law of Theorem IV.13(ii) (eq:algebra, lines
976--985) from the isometry statement of Theorem IV.13(iii) (Ualphabeta,
lines 986--993): the product of the operators is generated by the product
tensor, isometric conjugation does not change the closed-trace word
evaluations, and the word evaluation of the fused tensor splits block by
block with the chi factors accumulating into matrix powers.

Together with the length-one idempotent scalar law from statement (iii),
`BNTFusionIsometryFamily.toBNTAlgebraClause` combines this product identity
and the positive trace-power witness into the algebra clause of statement (ii).

The family is hypothesis-carrying: nothing here constructs the tensors, the
chi matrices, or the maps from an MPDO tensor.

**Scope restriction (full-support fusion family):** The field
$U_{\alpha,\beta}^\dagger U_{\alpha,\beta}=1$ excludes a common zero corner of
the product tensor. The unrestricted source statement instead requires a
coisometry onto the active sectors and exact reconstruction. This distinction
is documented in
`docs/paper-gaps/cpsv16_figure11_fusion_coisometry.tex`. The source-facing
Appendix C.4 construction is tracked there and in
`docs/paper-gaps/cpgsv17_blocked_chi_uniformity.tex`.

## References

* [Cirac--Perez-Garcia--Schuch--Verstraete 2017] arXiv:1606.00608,
  Theorem IV.13(iii), lines 986--993, and Appendix C.4, lines 2015--2065
-/

open scoped Matrix BigOperators ComplexOrder Kronecker
open Matrix

namespace Matrix

/-- Conjugating a dependent block-diagonal matrix by another dependent block-diagonal matrix
acts blockwise. -/
theorem blockDiagonal'_conj {ι : Type*} [Fintype ι] [DecidableEq ι]
    {m n : ι → Type*} [∀ i, Fintype (n i)] (F : ∀ i, Matrix (m i) (n i) ℂ)
    (G : ∀ i, Matrix (n i) (n i) ℂ) :
    blockDiagonal' F * blockDiagonal' G * (blockDiagonal' F)ᴴ =
      blockDiagonal' fun i => F i * G i * (F i)ᴴ := by
  rw [blockDiagonal'_conjTranspose, ← blockDiagonal'_mul, ← blockDiagonal'_mul]

/-- Reindexing the row space of a conjugating matrix by an equivalence commutes with
conjugation. -/
theorem submatrix_left_conj_equiv {l m u : Type*} [Fintype l] (A : Matrix m l ℂ)
    (r : u ≃ m) (X : Matrix l l ℂ) :
    A.submatrix r id * X * (A.submatrix r id)ᴴ = (A * X * Aᴴ).submatrix r r := by
  have hleft : A.submatrix r id * X = (A * X).submatrix r id :=
    (submatrix_mul A X r id id Function.bijective_id).symm
  rw [hleft]
  rw [conjTranspose_submatrix]
  exact (submatrix_mul (A * X) Aᴴ r id r Function.bijective_id).symm

end Matrix

namespace MPOTensor

/-- The fusion-isometry family of arXiv:1606.00608, Theorem IV.13(iii),
label Ualphabeta: a family of tensors indexed by BNT labels, positive diagonal
chi matrices, and per-pair isometries conjugating the product tensor onto the
chi-weighted direct sum of the labelled tensors.

The tensors are the vertically read basis of normal tensors of
Proposition IV.12: the physical dimension `p` is the bond dimension of the
original tensor, and each label carries its own bond dimension. The direct
sum is realized block-diagonally over the labels, with the block of label
`γ` the Kronecker product of the diagonal matrix `χ_{α,β,γ}` and the letter
of the tensor of `γ`.

Source: arXiv:1606.00608, Theorem IV.13(iii), lines 986--993 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`.

**Scope restriction (full-support fusion family):** This structure assumes
$U_{\alpha,\beta}^\dagger U_{\alpha,\beta}=1$. The source permits a discarded
common zero corner and, in the displayed orientation, gives a coisometry onto
the retained direct sum together with reconstruction. Documented in
`docs/paper-gaps/cpsv16_figure11_fusion_coisometry.tex`. -/
structure BNTFusionIsometryFamily (Λ : Type*) [Fintype Λ] [DecidableEq Λ]
    (p : ℕ) where
  /-- Bond dimension of the tensor of each label.

  Source: arXiv:1606.00608, Theorem IV.13(iii), lines 986--993 of
  `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  bondDim : Λ → ℕ
  /-- The labelled family of tensors, with common physical dimension `p`.

  Source: arXiv:1606.00608, Theorem IV.13(iii), lines 986--993, and
  Proposition IV.12, lines 944--953 of
  `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  tensor : ∀ γ : Λ, MPOTensor p (bondDim γ)
  /-- The diagonal chi matrices `χ_{α,β,γ}`.

  Source: arXiv:1606.00608, Theorem IV.13(ii)--(iii), lines 976--993 of
  `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  chi : DiagonalChiFamily Λ
  /-- Positivity of the diagonal entries, as in Theorem IV.13(ii).

  Source: arXiv:1606.00608, Theorem IV.13(ii), lines 976--985 of
  `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  posEntries : chi.PosEntries
  /-- The fusion maps `U_{α,β}` from the bond space of the product tensor to
  the bond space of the chi-weighted direct sum.

  Source: arXiv:1606.00608, Theorem IV.13(iii), lines 986--993 of
  `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  fusionIsometry : ∀ α β : Λ,
    Matrix ((γ : Λ) × (Fin (chi.dim α β γ) × Fin (bondDim γ)))
      (Fin (bondDim α * bondDim β)) ℂ
  /-- The additional full-support column-isometry condition on each fusion
  map.

  **Scope restriction (full-support fusion family):** The unrestricted source
  statement permits a discarded common zero corner and does not assert this
  identity. Documented in
  `docs/paper-gaps/cpsv16_figure11_fusion_coisometry.tex`. -/
  isometry : ∀ α β : Λ, (fusionIsometry α β)ᴴ * fusionIsometry α β = 1
  /-- The fusion identity, site by site:
  `U_{α,β} (M_α M_β)^{ij} U_{α,β}† = ⊕_γ χ_{α,β,γ} ⊗ M_γ^{ij}`.

  Source: arXiv:1606.00608, Theorem IV.13(iii), label Ualphabeta,
  lines 986--993 of `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
  fusion : ∀ (α β : Λ) (i j : Fin p),
    fusionIsometry α β * (mulTensor (tensor α) (tensor β)) i j *
        (fusionIsometry α β)ᴴ =
      Matrix.blockDiagonal' fun γ => chi.matrix α β γ ⊗ₖ tensor γ i j

namespace BNTFusionIsometryFamily

variable {Λ : Type*} [Fintype Λ] [DecidableEq Λ] {p : ℕ}
variable (Fam : BNTFusionIsometryFamily Λ p)

/-- Length independence makes every chi matrix in a fusion-isometry family
the identity on its multiplicity space.

Source: arXiv:1606.00608, line 1010 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
theorem chi_matrix_eq_one_of_lengthIndependent
    (c : BNTLabelCoefficientFamily Λ)
    (hχ : c.HasPositiveLengthChiTracePowerForm Fam.chi)
    (hLI : c.LengthIndependent) (α β γ : Λ) :
    Fam.chi.matrix α β γ = 1 :=
  DiagonalChiFamily.matrix_eq_one_of_forall_entry_eq_one
    (hχ.entry_eq_one_of_lengthIndependent Fam.posEntries hLI) α β γ

/-- **The fusion map carries a product letter to its weighted direct sum.**

For every pair of labels and physical indices,
\[
  U_{\alpha,\beta}(M_\alpha M_\beta)^{ij}
    = \left(\bigoplus_\gamma
        \chi_{\alpha,\beta,\gamma}\otimes M_\gamma^{ij}\right)U_{\alpha,\beta}.
\]
This is the first direction of the chi-weighted zipper identity.  It follows from the fusion
identity by multiplying on the right by the isometry and using
$U_{\alpha,\beta}^\dagger U_{\alpha,\beta}=1$.

The corresponding equation in arXiv:1511.08090 has identity weights on the multiplicity
spaces.  No identification of the positive diagonal chi indices with those fusion
multiplicities is asserted here.

Source: arXiv:1606.00608, Theorem IV.13(iii), equation `Ualphabeta`; arXiv:1511.08090,
Section ``Fusion tensors'', equations `inversegaugeone` and `zippercondition2`. -/
theorem fusionIsometry_mul_mulTensor (α β : Λ) (i j : Fin p) :
    Fam.fusionIsometry α β * mulTensor (Fam.tensor α) (Fam.tensor β) i j =
      (Matrix.blockDiagonal' fun γ =>
        Fam.chi.matrix α β γ ⊗ₖ Fam.tensor γ i j) * Fam.fusionIsometry α β := by
  calc
    Fam.fusionIsometry α β * mulTensor (Fam.tensor α) (Fam.tensor β) i j =
        (Fam.fusionIsometry α β * mulTensor (Fam.tensor α) (Fam.tensor β) i j *
          (Fam.fusionIsometry α β)ᴴ) * Fam.fusionIsometry α β := by
      rw [Matrix.mul_assoc, Fam.isometry, Matrix.mul_one]
    _ = (Matrix.blockDiagonal' fun γ =>
        Fam.chi.matrix α β γ ⊗ₖ Fam.tensor γ i j) * Fam.fusionIsometry α β := by
      rw [Fam.fusion]

/-- **A product letter carries the adjoint fusion map to its weighted direct sum.**

For every pair of labels and physical indices,
\[
  (M_\alpha M_\beta)^{ij}U_{\alpha,\beta}^\dagger
    = U_{\alpha,\beta}^\dagger
      \left(\bigoplus_\gamma
        \chi_{\alpha,\beta,\gamma}\otimes M_\gamma^{ij}\right).
\]
This is the second direction of the chi-weighted zipper identity.  It follows from the fusion
identity by multiplying on the left by the adjoint isometry and using
$U_{\alpha,\beta}^\dagger U_{\alpha,\beta}=1$.

The corresponding equation in arXiv:1511.08090 has identity weights on the multiplicity
spaces.  The length-independent integer specialization removes the chi weights.  It does not
by itself construct an $F$-move: a comparison of the two triple-fusion orders and final-label
separation remain necessary.

Source: arXiv:1606.00608, Theorem IV.13(iii), equation `Ualphabeta`; arXiv:1511.08090,
Section ``Fusion tensors'', equations `inversegaugeone` and `zippercondition2`. -/
theorem mulTensor_mul_fusionIsometry_conjTranspose (α β : Λ) (i j : Fin p) :
    mulTensor (Fam.tensor α) (Fam.tensor β) i j * (Fam.fusionIsometry α β)ᴴ =
      (Fam.fusionIsometry α β)ᴴ *
        Matrix.blockDiagonal' fun γ =>
          Fam.chi.matrix α β γ ⊗ₖ Fam.tensor γ i j := by
  calc
    mulTensor (Fam.tensor α) (Fam.tensor β) i j * (Fam.fusionIsometry α β)ᴴ =
        (Fam.fusionIsometry α β)ᴴ *
          (Fam.fusionIsometry α β * mulTensor (Fam.tensor α) (Fam.tensor β) i j *
            (Fam.fusionIsometry α β)ᴴ) := by
      rw [← Matrix.mul_assoc, ← Matrix.mul_assoc, Fam.isometry, Matrix.one_mul]
    _ = (Fam.fusionIsometry α β)ᴴ *
        Matrix.blockDiagonal' fun γ =>
          Fam.chi.matrix α β γ ⊗ₖ Fam.tensor γ i j := by
      rw [Fam.fusion]

/-- **The length-independent left zipper identity.**

If the trace-power coefficients of a fusion-isometry family are length
independent, then every chi matrix is the identity and
\[
  U_{\alpha,\beta}(M_\alpha M_\beta)^{ij}
    = \left(\bigoplus_\gamma 1_{r_{\alpha,\beta,\gamma}}
        \otimes M_\gamma^{ij}\right)U_{\alpha,\beta}.
\]

Source: arXiv:1606.00608, lines 995--1010 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`; arXiv:1511.08090,
`AnyonsPEPS.tex`, Section `Fusion tensors`, equation `zippercondition2`. -/
theorem fusionIsometry_mul_mulTensor_of_lengthIndependent
    (c : BNTLabelCoefficientFamily Λ)
    (hχ : c.HasPositiveLengthChiTracePowerForm Fam.chi)
    (hLI : c.LengthIndependent) (α β : Λ) (i j : Fin p) :
    Fam.fusionIsometry α β * mulTensor (Fam.tensor α) (Fam.tensor β) i j =
      (Matrix.blockDiagonal' fun γ =>
        (1 : Matrix (Fin (Fam.chi.dim α β γ))
          (Fin (Fam.chi.dim α β γ)) ℂ) ⊗ₖ Fam.tensor γ i j) *
        Fam.fusionIsometry α β := by
  rw [Fam.fusionIsometry_mul_mulTensor]
  simp_rw [Fam.chi_matrix_eq_one_of_lengthIndependent c hχ hLI]

/-- **The length-independent right zipper identity.**

If the trace-power coefficients of a fusion-isometry family are length
independent, then
\[
  (M_\alpha M_\beta)^{ij}U_{\alpha,\beta}^\dagger
    = U_{\alpha,\beta}^\dagger
      \left(\bigoplus_\gamma 1_{r_{\alpha,\beta,\gamma}}
        \otimes M_\gamma^{ij}\right).
\]

Source: arXiv:1606.00608, lines 995--1010 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`; arXiv:1511.08090,
`AnyonsPEPS.tex`, Section `Fusion tensors`, equation `zippercondition2`. -/
theorem mulTensor_mul_fusionIsometry_conjTranspose_of_lengthIndependent
    (c : BNTLabelCoefficientFamily Λ)
    (hχ : c.HasPositiveLengthChiTracePowerForm Fam.chi)
    (hLI : c.LengthIndependent) (α β : Λ) (i j : Fin p) :
    mulTensor (Fam.tensor α) (Fam.tensor β) i j * (Fam.fusionIsometry α β)ᴴ =
      (Fam.fusionIsometry α β)ᴴ *
        Matrix.blockDiagonal' fun γ =>
          (1 : Matrix (Fin (Fam.chi.dim α β γ))
            (Fin (Fam.chi.dim α β γ)) ℂ) ⊗ₖ Fam.tensor γ i j := by
  rw [Fam.mulTensor_mul_fusionIsometry_conjTranspose]
  simp_rw [Fam.chi_matrix_eq_one_of_lengthIndependent c hχ hLI]

/-- **Length-independent zipper completeness.**

Under length independence, conjugating the direct sum with the adjoint fusion
isometry recovers the product letter:
\[
  (M_\alpha M_\beta)^{ij}
    = U_{\alpha,\beta}^\dagger
      \left(\bigoplus_\gamma 1_{r_{\alpha,\beta,\gamma}}
        \otimes M_\gamma^{ij}\right)U_{\alpha,\beta}.
\]

Source: arXiv:1606.00608, lines 995--1010 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`; arXiv:1511.08090,
`AnyonsPEPS.tex`, Section `Fusion tensors`, equations `blocks` and
`inversegaugeone`. -/
theorem mulTensor_eq_conjTranspose_mul_unweightedDirectSum_mul_of_lengthIndependent
    (c : BNTLabelCoefficientFamily Λ)
    (hχ : c.HasPositiveLengthChiTracePowerForm Fam.chi)
    (hLI : c.LengthIndependent) (α β : Λ) (i j : Fin p) :
    mulTensor (Fam.tensor α) (Fam.tensor β) i j =
      (Fam.fusionIsometry α β)ᴴ *
        (Matrix.blockDiagonal' fun γ =>
          (1 : Matrix (Fin (Fam.chi.dim α β γ))
            (Fin (Fam.chi.dim α β γ)) ℂ) ⊗ₖ Fam.tensor γ i j) *
        Fam.fusionIsometry α β := by
  calc
    mulTensor (Fam.tensor α) (Fam.tensor β) i j =
        ((Fam.fusionIsometry α β)ᴴ * Fam.fusionIsometry α β) *
          mulTensor (Fam.tensor α) (Fam.tensor β) i j *
          ((Fam.fusionIsometry α β)ᴴ * Fam.fusionIsometry α β) := by
      rw [Fam.isometry, Matrix.one_mul, Matrix.mul_one]
    _ = (Fam.fusionIsometry α β)ᴴ *
        (Fam.fusionIsometry α β * mulTensor (Fam.tensor α) (Fam.tensor β) i j *
          (Fam.fusionIsometry α β)ᴴ) * Fam.fusionIsometry α β := by
      simp only [Matrix.mul_assoc]
    _ = (Fam.fusionIsometry α β)ᴴ *
        (Matrix.blockDiagonal' fun γ =>
          (1 : Matrix (Fin (Fam.chi.dim α β γ))
            (Fin (Fam.chi.dim α β γ)) ℂ) ⊗ₖ Fam.tensor γ i j) *
        Fam.fusionIsometry α β := by
      rw [Fam.fusion]
      simp_rw [Fam.chi_matrix_eq_one_of_lengthIndependent c hχ hLI]

/-- **The same-length product law with trace-power coefficients**: for every
positive chain length, the product of two labelled operators expands over the
labels with coefficients `tr(χ_{α,β,γ}^L)`. This derives the product law of
Theorem IV.13(ii) (eq:algebra, lines 976--985) from the fusion identity of
Theorem IV.13(iii) (lines 986--993).

Source: arXiv:1606.00608, lines 976--993, and Appendix C.4,
lines 2015--2037 of `Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
theorem mpo_mul_mpo_eq_sum (L : ℕ) (hL : 0 < L) (α β : Λ) :
    mpo (Fam.tensor α) L * mpo (Fam.tensor β) L =
      ∑ γ : Λ, Fam.chi.tracePowerCoeff α β γ L • mpo (Fam.tensor γ) L := by
  obtain ⟨n, rfl⟩ : ∃ n, L = n + 1 := ⟨L - 1, (Nat.succ_pred_eq_of_pos hL).symm⟩
  rw [← mpo_mulTensor]
  ext σ τ
  rw [mpo_apply, mpoMatrixEntry, evalWord_ofFn]
  set U := Fam.fusionIsometry α β with hUdef
  have hUiso : Uᴴ * U = 1 := Fam.isometry α β
  have hletters : (fun l : Fin (n + 1) =>
      U * mulTensor (Fam.tensor α) (Fam.tensor β) (σ l) (τ l) * Uᴴ) =
      fun l => Matrix.blockDiagonal'
        fun γ => Fam.chi.matrix α β γ ⊗ₖ Fam.tensor γ (σ l) (τ l) := by
    funext l
    exact Fam.fusion α β (σ l) (τ l)
  have hconj := listProd_conj_of_conjTranspose_mul_self U hUiso
    (fun l => mulTensor (Fam.tensor α) (Fam.tensor β) (σ l) (τ l))
  set P := (List.ofFn fun l =>
    mulTensor (Fam.tensor α) (Fam.tensor β) (σ l) (τ l)).prod with hPdef
  have htraceP : Matrix.trace P =
      Matrix.trace ((List.ofFn fun l => Matrix.blockDiagonal'
        fun γ => Fam.chi.matrix α β γ ⊗ₖ Fam.tensor γ (σ l) (τ l)).prod) := by
    rw [← hletters, hconj, Matrix.trace_mul_comm, ← Matrix.mul_assoc, hUiso,
      Matrix.one_mul]
  rw [htraceP, listProd_blockDiagonal'_kronecker, Matrix.trace_blockDiagonal']
  simp_rw [Matrix.trace_kronecker, Fam.chi.trace_matrix_pow]
  simp only [Matrix.sum_apply, Matrix.smul_apply, mpo_apply, mpoMatrixEntry,
    evalWord_ofFn, smul_eq_mul]

/-- The concrete MPO operator family of the labelled tensors,
`O_L(M_γ) = mpo (M_γ) L`.

Source: arXiv:1606.00608, lines 962--966 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
noncomputable def toOperatorFamily :
    BNTLabelOperatorFamily Λ
      (fun L => Matrix (Fin L → Fin p) (Fin L → Fin p) ℂ) :=
  ⟨fun L γ => mpo (Fam.tensor γ) L⟩

@[simp] lemma toOperatorFamily_operator (L : ℕ) (γ : Λ) :
    Fam.toOperatorFamily.operator L γ = mpo (Fam.tensor γ) L := rfl

/-- A fusion-isometry family satisfies the same-length product form with the
coefficient family canonically determined by its chi matrices. This provides
the product-law input of the Theorem IV.13(ii) coefficient statements for the
concrete operator family.

Source: arXiv:1606.00608, Theorem IV.13(ii)--(iii), lines 976--993 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
theorem toOperatorFamily_hasSameLengthProductForm :
    Fam.toOperatorFamily.HasSameLengthProductForm
      (BNTLabelCoefficientFamily.ofChi Fam.chi) := by
  intro L hL α β
  simpa [toOperatorFamily_operator, BNTLabelCoefficientFamily.ofChi_coeff]
    using Fam.mpo_mul_mpo_eq_sum L hL α β

/-- The fusion-isometry clause, together with its idempotent trace-scalar law,
implies the algebra clause for the concrete operators generated by the labelled
tensors.

This is the object-level implication (iii) to (ii) in arXiv:1606.00608,
Theorem IV.13. It uses the same diagonal matrices and trace scalars on both
sides, and does not assert the full equivalence for an underlying MPDO tensor.

Source: arXiv:1606.00608, Theorem IV.13(ii)--(iii), lines 972--993, and
Appendix C.4, lines 1929--1947 and 2046 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
noncomputable def toBNTAlgebraClause
    (m : BNTLabelTraceScalarFamily Λ)
    (hIdempotent :
      m.HasIdempotentCoefficientForm (BNTLabelCoefficientFamily.ofChi Fam.chi)) :
    BNTAlgebraClause (BNTLabelCoefficientFamily.ofChi Fam.chi)
      Fam.toOperatorFamily m where
  positiveChi := PositiveBNTLabelChiTracePowerForm.ofChi Fam.chi Fam.posEntries
  sameLengthProduct := Fam.toOperatorFamily_hasSameLengthProductForm
  idempotent := hIdempotent

end BNTFusionIsometryFamily

end MPOTensor
