/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.MPDO.BondTwoSingletonGramBoundary
import TNLean.MPS.MPDO.CyclicEdgeWeightTensor
import TNLean.Algebra.OrthogonalProjection

/-!
# An all-length positive base model for the bond-two singleton

This module packages the matrix-unit singleton retained tensor from
`BondTwoSingletonGramBoundary` as an ambient bond-four MPO.  Its ambient closed
operators are the unnormalized rank-one GHZ operators; these are kept distinct
from the diagonal cyclic-edge projections generated by the retained singleton.

The construction is an explicit test model motivated by arXiv:1606.00608,
Appendix C.4, lines 2048--2057.  It is not a tensor stated in the source.
-/

open scoped BigOperators ComplexOrder Matrix

noncomputable section

namespace MPOTensor.BondTwoSingletonBaseModel

open BondTwoSingletonGramBoundary

private abbrev I := Fin 2

/-- The ambient bond-four MPO.  Its physical letter `(i,j)` is the diagonal
matrix unit indexed by the same pair. -/
def baseMPO : MPOTensor 2 4 :=
  fun i j => Matrix.single (finProdFinEquiv (i, j)) (finProdFinEquiv (i, j)) 1

/-- The vertical tensor of the ambient model is exactly the retained singleton. -/
theorem verticalTensor_baseMPO : verticalTensor baseMPO = singletonTensor := by
  funext v i j
  obtain ⟨⟨x, y⟩, rfl⟩ :=
    (finProdFinEquiv : Fin 4 × Fin 4 ≃ Fin (4 * 4)).surjective v
  obtain ⟨⟨a, b⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective x
  obtain ⟨⟨c, d⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective y
  rw [verticalTensor_finProdFinEquiv]
  simp only [baseMPO, singletonTensor, Equiv.symm_apply_apply]
  split_ifs <;> simp_all [Matrix.single] <;> aesop

/-- The cyclic equality weight selecting one fixed ket--bra pair around the chain. -/
def constantPairWeight (i j i' j' : I) : ℂ :=
  if i = i' ∧ j = j' then 1 else 0

/-- The base MPO is the cyclic-edge tensor for the equality weight. -/
theorem baseMPO_eq_cyclicEdgeWeightTensor :
    baseMPO = cyclicEdgeWeightTensor constantPairWeight := by
  funext i j a b
  obtain ⟨⟨ai, aj⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective a
  obtain ⟨⟨bi, bj⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective b
  simp only [baseMPO, cyclicEdgeWeightTensor, constantPairWeight,
    MPSTensor.finProdFinEquiv_divNat, MPSTensor.finProdFinEquiv_modNat]
  split_ifs <;> simp_all [Matrix.single] <;> aesop

/-- The cyclic-constant amplitude of the unnormalized two-symbol GHZ vector. -/
def ghzAmplitude (N : ℕ) (sigma : Fin N → I) : ℂ :=
  ∏ n : Fin N, if sigma n = sigma (finRotate N n) then 1 else 0

/-- The rank-one operator built from the unnormalized two-symbol GHZ vector.
At positive length its support is the span of the two constant words. -/
def unnormalizedGHZRankOne (N : ℕ) :
    Matrix (Fin N → I) (Fin N → I) ℂ :=
  Matrix.vecMulVec (ghzAmplitude N) (star (ghzAmplitude N))

/-- Every positive-length ambient MPO is the explicit unnormalized GHZ
rank-one operator. -/
theorem mpo_baseMPO_eq_unnormalizedGHZRankOne
    (N : ℕ) (hN : 0 < N) :
    mpo baseMPO N = unnormalizedGHZRankOne N := by
  letI : NeZero N := ⟨Nat.ne_of_gt hN⟩
  ext sigma tau
  rw [baseMPO_eq_cyclicEdgeWeightTensor, mpo_cyclicEdgeWeightTensor]
  change (∏ n : Fin N,
      constantPairWeight (sigma n) (tau n) (sigma (n + 1)) (tau (n + 1))) =
    ghzAmplitude N sigma * star (ghzAmplitude N tau)
  have hstar : star (ghzAmplitude N tau) = ghzAmplitude N tau := by
    unfold ghzAmplitude
    rw [star_prod]
    apply Finset.prod_congr rfl
    intro n _hn
    split <;> simp
  rw [hstar]
  unfold ghzAmplitude
  simp only [finRotate_apply]
  rw [← Finset.prod_mul_distrib]
  apply Finset.prod_congr rfl
  intro n _hn
  simp only [constantPairWeight]
  by_cases hs : sigma n = sigma (n + 1) <;>
    by_cases ht : tau n = tau (n + 1) <;> simp [hs, ht]

/-- The ambient base tensor generates positive operators at every nonempty
chain length. -/
theorem baseMPO_isMPDO : IsMPDO baseMPO := by
  intro N hN
  rw [mpo_baseMPO_eq_unnormalizedGHZRankOne N hN]
  exact Matrix.posSemidef_vecMulVec_self_star (ghzAmplitude N)

/-! ### Literal CPSV canonical form -/

/-- The bond-one normal block supported on one doubled physical symbol. -/
def baseSymbolTensor (a : Fin 4) : MPSTensor 4 1 :=
  fun i => if i = a then 1 else 0

private theorem baseSymbolTensor_transferMap (a : Fin 4) :
    MPSTensor.transferMap (baseSymbolTensor a) = LinearMap.id := by
  apply LinearMap.ext
  intro X
  ext x y
  fin_cases x
  fin_cases y
  simp [MPSTensor.transferMap_apply, baseSymbolTensor]

/-- Every symbol block in the four-block decomposition is a normal tensor. -/
theorem baseSymbolTensor_isNormalTensor (a : Fin 4) :
    MPSTensor.IsNormalTensor (baseSymbolTensor a) :=
  MPSTensor.isNormalTensor_of_bondDim_one_of_transferMap_eq_id
    (baseSymbolTensor a) (baseSymbolTensor_transferMap a)

/-- The four bond-one blocks used in the literal canonical form. -/
def baseSymbolBlocks : (a : Fin 4) → MPSTensor 4 1 :=
  baseSymbolTensor

/-- The doubled-index tensor of the ambient MPO is literally the direct sum of
its four bond-one symbol blocks, each with weight one. -/
theorem baseMPO_toMPSTensor_eq_symbolBlocks :
    baseMPO.toMPSTensor =
      MPSTensor.toTensorFromBlocks (fun _ : Fin 4 => (1 : ℂ)) baseSymbolBlocks := by
  let e : (Σ _k : Fin 4, Fin 1) ≃ Fin 4 := finSigmaFinEquiv
  have hflat (k : Fin 4) : e ⟨k, 0⟩ = k := by
    fin_cases k <;> rfl
  have hflat_symm (k : Fin 4) : e.symm k = ⟨k, 0⟩ := by
    apply e.injective
    rw [e.apply_symm_apply, hflat]
  funext p
  obtain ⟨⟨i, j⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective p
  ext x y
  simp only [baseMPO, toMPSTensor, MPSTensor.toTensorFromBlocks,
    baseSymbolBlocks, baseSymbolTensor, Matrix.reindex_apply, one_smul,
    MPSTensor.finProdFinEquiv_divNat, MPSTensor.finProdFinEquiv_modNat]
  change Matrix.single (finProdFinEquiv (i, j)) (finProdFinEquiv (i, j)) 1 x y =
    Matrix.blockDiagonal' (fun k : Fin 4 => baseSymbolTensor k (finProdFinEquiv (i, j)))
      (e.symm x) (e.symm y)
  rw [hflat_symm x, hflat_symm y]
  by_cases h : x = y
  · subst y
    by_cases hp : finProdFinEquiv (i, j) = x <;>
      simp [hp, baseSymbolTensor, Matrix.single]
  · rw [Matrix.blockDiagonal'_apply_ne _ _ _ h]
    simp [Matrix.single]
    aesop

/-- The ambient doubled-index MPS is in literal CPSV canonical form via the
four displayed bond-one symbol blocks. -/
theorem baseMPO_toMPSTensor_isCPSVCanonicalForm :
    MPSTensor.IsCPSVCanonicalForm baseMPO.toMPSTensor := by
  rw [baseMPO_toMPSTensor_eq_symbolBlocks]
  exact (MPSTensor.CPSVCanonicalFormData.ofBlocks
    (fun _ : Fin 4 => by simp)
    (fun _ : Fin 4 => (1 : ℂ)) baseSymbolBlocks
    (fun a => baseSymbolTensor_isNormalTensor a)).isCPSVCanonicalForm

/-! ### Raw retained cyclic-edge projections -/

/-- The source vertex of an encoded directed two-state edge. -/
def edgeSource (x : Fin 4) : I :=
  (finProdFinEquiv.symm x : I × I).1

/-- The target vertex of an encoded directed two-state edge. -/
def edgeTarget (x : Fin 4) : I :=
  (finProdFinEquiv.symm x : I × I).2

/-- The indicator that a word of directed two-state edges closes cyclically. -/
def retainedCyclicIndicator (N : ℕ) (sigma : Fin N → Fin 4) : ℂ :=
  ∏ n : Fin N,
    if edgeTarget (sigma n) = edgeSource (sigma (finRotate N n)) then 1 else 0

/-- The retained singleton's positive-length closed operators are diagonal
cyclic-edge indicators. -/
theorem mpo_verticalBNTMPO_singletonTensor_eq_diagonal
    (N : ℕ) (hN : 0 < N) :
    mpo (verticalBNTMPO singletonTensor) N =
      Matrix.diagonal (retainedCyclicIndicator N) := by
  letI : NeZero N := ⟨Nat.ne_of_gt hN⟩
  ext sigma tau
  rw [mpo_apply, mpoMatrixEntry, evalWord_ofFn]
  have hcyc := MPSTensor.trace_evalWord_eq_sum_cyclic singletonTensor
    (fun n => finProdFinEquiv (sigma n, tau n))
  rw [MPSTensor.evalWord_ofFn_eq_prod] at hcyc
  change (List.ofFn fun n => singletonTensor
      (finProdFinEquiv (sigma n, tau n))).prod.trace = _
  rw [hcyc]
  let g0 : Fin N → I := fun n => edgeSource (sigma n)
  rw [Fintype.sum_eq_single g0]
  · rw [Matrix.diagonal_apply]
    by_cases hst : sigma = tau
    · subst tau
      simp only [retainedCyclicIndicator]
      apply Finset.prod_congr rfl
      intro n _hn
      simp only [singletonTensor, Equiv.symm_apply_apply,
        Matrix.single, g0, finRotate_apply]
      split_ifs <;> simp_all [edgeSource, edgeTarget]
    · rw [if_neg hst]
      obtain ⟨n, hn⟩ := Function.ne_iff.mp hst
      apply Finset.prod_eq_zero (Finset.mem_univ n)
      simp [singletonTensor, hn]
  · intro g hg
    obtain ⟨n, hn⟩ := Function.ne_iff.mp hg
    apply Finset.prod_eq_zero (Finset.mem_univ n)
    dsimp [g0, edgeSource] at hn
    by_cases hs : sigma n = tau n
    · rw [← hs]
      simp [singletonTensor, Matrix.single]
      aesop
    · simp [singletonTensor, hs]

private lemma retainedCyclicIndicator_eq_zero_or_one
    (N : ℕ) (sigma : Fin N → Fin 4) :
    retainedCyclicIndicator N sigma = 0 ∨
      retainedCyclicIndicator N sigma = 1 := by
  classical
  by_cases h : ∀ n : Fin N,
      edgeTarget (sigma n) = edgeSource (sigma (finRotate N n))
  · right
    unfold retainedCyclicIndicator
    apply Finset.prod_eq_one
    intro n _hn
    simp [h n]
  · left
    push Not at h
    obtain ⟨n, hn⟩ := h
    unfold retainedCyclicIndicator
    apply Finset.prod_eq_zero (Finset.mem_univ n)
    rw [if_neg (by simpa only [finRotate_apply] using hn)]

/-- At every positive length the raw retained closed operator is Hermitian and
idempotent, hence an orthogonal projection in the matrix algebra indexed by
edge words. -/
theorem mpo_verticalBNTMPO_singletonTensor_isHermitian_and_idempotent
    (N : ℕ) (hN : 0 < N) :
    (mpo (verticalBNTMPO singletonTensor) N).IsHermitian ∧
      mpo (verticalBNTMPO singletonTensor) N *
        mpo (verticalBNTMPO singletonTensor) N =
          mpo (verticalBNTMPO singletonTensor) N := by
  rw [mpo_verticalBNTMPO_singletonTensor_eq_diagonal N hN]
  constructor
  · change (Matrix.diagonal (retainedCyclicIndicator N))ᴴ =
      Matrix.diagonal (retainedCyclicIndicator N)
    ext sigma tau
    by_cases hst : sigma = tau
    · subst tau
      rcases retainedCyclicIndicator_eq_zero_or_one N sigma with hzero | hone
      · simp [Matrix.conjTranspose_apply, hzero]
      · simp [Matrix.conjTranspose_apply, hone]
    · simp [Matrix.conjTranspose_apply, Matrix.diagonal_apply, hst, Ne.symm hst]
  · rw [Matrix.diagonal_mul_diagonal]
    apply congrArg Matrix.diagonal
    funext sigma
    rcases retainedCyclicIndicator_eq_zero_or_one N sigma with hzero | hone
    · simp [hzero]
    · simp [hone]

/-- The raw retained closed operator is a star projection at every positive
length. -/
theorem mpo_verticalBNTMPO_singletonTensor_isStarProjection
    (N : ℕ) (hN : 0 < N) :
    IsStarProjection (mpo (verticalBNTMPO singletonTensor) N) := by
  rw [isStarProjection_iff']
  have h := mpo_verticalBNTMPO_singletonTensor_isHermitian_and_idempotent N hN
  exact ⟨h.2, by simpa [Matrix.star_eq_conjTranspose] using h.1.eq⟩

/-- The coefficient-one multiplication law for the raw singleton retained
operator. -/
theorem raw_singleton_coefficient_one_algebra
    (L : ℕ) (hL : 0 < L) :
    mpo (verticalBNTMPO singletonTensor) L *
        mpo (verticalBNTMPO singletonTensor) L =
      ∑ _gamma : Fin 1, (1 : ℂ) •
        mpo (verticalBNTMPO singletonTensor) L := by
  rw [(mpo_verticalBNTMPO_singletonTensor_isHermitian_and_idempotent L hL).2]
  simp

end MPOTensor.BondTwoSingletonBaseModel
