/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.MPDO.BondTwoSingletonGramBoundary
import TNLean.MPS.MPDO.CyclicEdgeWeightTensor
import TNLean.Algebra.OrthogonalProjection

/-!
# An all-length positive base model for the bond-two singleton

This module packages the matrix-unit singleton retained tensor from
`BondTwoSingletonGramBoundary` as an ambient bond-four MPO.  Its ambient closed
operators are the unnormalized rank-one GHZ operators; these are kept distinct
from the diagonal cyclic-edge projections generated by the retained singleton.

The construction is an explicit test model motivated by arXiv:1606.00608,
Appendix C.4, lines 2048--2057.  It is not a tensor stated in the source.
-/

open scoped BigOperators ComplexOrder Matrix

noncomputable section

namespace MPOTensor.BondTwoSingletonBaseModel

open BondTwoSingletonGramBoundary

private abbrev I := Fin 2

/-- The ambient bond-four MPO.  Its physical letter `(i,j)` is the diagonal
matrix unit indexed by the same pair. -/
def baseMPO : MPOTensor 2 4 :=
  fun i j => Matrix.single (finProdFinEquiv (i, j)) (finProdFinEquiv (i, j)) 1

/-- The vertical tensor of the ambient model is exactly the retained singleton. -/
theorem verticalTensor_baseMPO : verticalTensor baseMPO = singletonTensor := by
  funext v i j
  obtain ⟨⟨x, y⟩, rfl⟩ :=
    (finProdFinEquiv : Fin 4 × Fin 4 ≃ Fin (4 * 4)).surjective v
  obtain ⟨⟨a, b⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective x
  obtain ⟨⟨c, d⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective y
  rw [verticalTensor_finProdFinEquiv]
  simp only [baseMPO, singletonTensor, Equiv.symm_apply_apply]
  split_ifs <;> simp_all [Matrix.single] <;> aesop

/-- The cyclic equality weight selecting one fixed ket--bra pair around the chain. -/
def constantPairWeight (i j i' j' : I) : ℂ :=
  if i = i' ∧ j = j' then 1 else 0

/-- The base MPO is the cyclic-edge tensor for the equality weight. -/
theorem baseMPO_eq_cyclicEdgeWeightTensor :
    baseMPO = cyclicEdgeWeightTensor constantPairWeight := by
  funext i j a b
  obtain ⟨⟨ai, aj⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective a
  obtain ⟨⟨bi, bj⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective b
  simp only [baseMPO, cyclicEdgeWeightTensor, constantPairWeight,
    MPSTensor.finProdFinEquiv_divNat, MPSTensor.finProdFinEquiv_modNat]
  split_ifs <;> simp_all [Matrix.single] <;> aesop

/-- The cyclic-constant amplitude of the unnormalized two-symbol GHZ vector. -/
def ghzAmplitude (N : ℕ) (sigma : Fin N → I) : ℂ :=
  ∏ n : Fin N, if sigma n = sigma (finRotate N n) then 1 else 0

/-- The rank-one operator built from the unnormalized two-symbol GHZ vector.
At positive length its support is the span of the two constant words. -/
def unnormalizedGHZRankOne (N : ℕ) :
    Matrix (Fin N → I) (Fin N → I) ℂ :=
  Matrix.vecMulVec (ghzAmplitude N) (star (ghzAmplitude N))

/-- Every positive-length ambient MPO is the explicit unnormalized GHZ
rank-one operator. -/
theorem mpo_baseMPO_eq_unnormalizedGHZRankOne
    (N : ℕ) (hN : 0 < N) :
    mpo baseMPO N = unnormalizedGHZRankOne N := by
  letI : NeZero N := ⟨Nat.ne_of_gt hN⟩
  ext sigma tau
  rw [baseMPO_eq_cyclicEdgeWeightTensor, mpo_cyclicEdgeWeightTensor]
  change (∏ n : Fin N,
      constantPairWeight (sigma n) (tau n) (sigma (n + 1)) (tau (n + 1))) =
    ghzAmplitude N sigma * star (ghzAmplitude N tau)
  have hstar : star (ghzAmplitude N tau) = ghzAmplitude N tau := by
    unfold ghzAmplitude
    rw [star_prod]
    apply Finset.prod_congr rfl
    intro n _hn
    split <;> simp
  rw [hstar]
  unfold ghzAmplitude
  simp only [finRotate_apply]
  rw [← Finset.prod_mul_distrib]
  apply Finset.prod_congr rfl
  intro n _hn
  simp only [constantPairWeight]
  by_cases hs : sigma n = sigma (n + 1) <;>
    by_cases ht : tau n = tau (n + 1) <;> simp [hs, ht]

/-- The ambient base tensor generates positive operators at every nonempty
chain length. -/
theorem baseMPO_isMPDO : IsMPDO baseMPO := by
  intro N hN
  rw [mpo_baseMPO_eq_unnormalizedGHZRankOne N hN]
  exact Matrix.posSemidef_vecMulVec_self_star (ghzAmplitude N)

end MPOTensor.BondTwoSingletonBaseModel
