/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.MPDO.BondTwoSingletonGramBoundary
import TNLean.MPS.MPDO.CyclicEdgeWeightTensor
import TNLean.MPS.MPDO.VerticalSectorCoordinates

/-!
# An all-length positive base model for the bond-two singleton

This module packages the matrix-unit singleton retained tensor from
`BondTwoSingletonGramBoundary` as an ambient bond-four MPO.  Its ambient closed
operators are the unnormalized rank-one GHZ operators; these are kept distinct
from the diagonal cyclic-edge projections generated by the retained singleton.

The construction is an explicit test model motivated by arXiv:1606.00608,
Appendix C.4, lines 2048--2057.  It is not a tensor stated in the source.

Closed MPO words of length zero evaluate to the identity on the bond space, so
their trace remembers the bond dimension.  Consequently the ambient and
retained formulas below are stated for positive lengths; explicit zero-length
theorems record the resulting factors four and two.
-/

open scoped BigOperators ComplexOrder Matrix

noncomputable section

namespace MPOTensor.BondTwoSingletonBaseModel

open BondTwoSingletonGramBoundary

private abbrev I := Fin 2

/-- The ambient bond-four MPO.  Its physical letter `(i,j)` is the diagonal
matrix unit indexed by the same pair. -/
def baseMPO : MPOTensor 2 4 :=
  fun i j ↦ Matrix.single (finProdFinEquiv (i, j)) (finProdFinEquiv (i, j)) 1

/-- The vertical tensor of the ambient model is exactly the retained singleton. -/
theorem verticalTensor_baseMPO : verticalTensor baseMPO = singletonTensor := by
  funext v i j
  obtain ⟨⟨x, y⟩, rfl⟩ :=
    (finProdFinEquiv : Fin 4 × Fin 4 ≃ Fin (4 * 4)).surjective v
  obtain ⟨⟨a, b⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective x
  obtain ⟨⟨c, d⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective y
  rw [verticalTensor_finProdFinEquiv]
  simp only [baseMPO, singletonTensor, Equiv.symm_apply_apply]
  split_ifs <;> simp_all [Matrix.single]
  all_goals aesop

/-- The cyclic equality weight requiring the ket--bra pair to be constant around the chain. -/
def constantPairWeight (i j i' j' : I) : ℂ :=
  if i = i' ∧ j = j' then 1 else 0

/-- The base MPO is the cyclic-edge tensor for the equality weight. -/
theorem baseMPO_eq_cyclicEdgeWeightTensor :
    baseMPO = cyclicEdgeWeightTensor constantPairWeight := by
  funext i j a b
  obtain ⟨⟨ai, aj⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective a
  obtain ⟨⟨bi, bj⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective b
  simp only [baseMPO, cyclicEdgeWeightTensor, constantPairWeight,
    MPSTensor.finProdFinEquiv_divNat, MPSTensor.finProdFinEquiv_modNat]
  split_ifs <;> simp_all [Matrix.single]
  all_goals aesop

/-- The cyclic-constant amplitude of the unnormalized two-symbol GHZ vector. -/
def ghzAmplitude (N : ℕ) (sigma : Fin N → I) : ℂ :=
  ∏ n : Fin N, if sigma n = sigma (finRotate N n) then 1 else 0

/-- The rank-one operator built from the unnormalized two-symbol GHZ vector.
At positive length its defining amplitude is supported on the two constant
words, and its range is the line spanned by their sum. -/
def unnormalizedGHZRankOne (N : ℕ) :
    Matrix (Fin N → I) (Fin N → I) ℂ :=
  Matrix.vecMulVec (ghzAmplitude N) (star (ghzAmplitude N))

/-- At length zero the closed ambient word is the bond-four identity, whose
trace gives the scalar four. -/
theorem mpo_baseMPO_zero : mpo baseMPO 0 = (4 : ℂ) • 1 := by
  ext sigma tau
  have h : sigma = tau := Subsingleton.elim _ _
  subst tau
  simp [mpo, mpoMatrixEntry, evalWord_nil, Matrix.trace]

/-- The empty GHZ amplitude instead gives the one-dimensional identity. -/
theorem unnormalizedGHZRankOne_zero : unnormalizedGHZRankOne 0 = 1 := by
  ext sigma tau
  have h : sigma = tau := Subsingleton.elim _ _
  subst tau
  simp [unnormalizedGHZRankOne, ghzAmplitude, Matrix.vecMulVec]

/-- Thus the ambient GHZ rank-one formula genuinely fails at length zero. -/
theorem mpo_baseMPO_zero_ne_unnormalizedGHZRankOne_zero :
    mpo baseMPO 0 ≠ unnormalizedGHZRankOne 0 := by
  rw [mpo_baseMPO_zero, unnormalizedGHZRankOne_zero]
  intro h
  have hentry := congrArg (fun A ↦ A default default) h
  norm_num at hentry

/-- Every positive-length ambient MPO is the explicit unnormalized GHZ
rank-one operator. -/
theorem mpo_baseMPO_eq_unnormalizedGHZRankOne
    (N : ℕ) (hN : 0 < N) :
    mpo baseMPO N = unnormalizedGHZRankOne N := by
  letI : NeZero N := ⟨Nat.ne_of_gt hN⟩
  ext sigma tau
  rw [baseMPO_eq_cyclicEdgeWeightTensor, mpo_cyclicEdgeWeightTensor]
  change (∏ n : Fin N,
      constantPairWeight (sigma n) (tau n) (sigma (n + 1)) (tau (n + 1))) =
    ghzAmplitude N sigma * star (ghzAmplitude N tau)
  have hstar : star (ghzAmplitude N tau) = ghzAmplitude N tau := by
    unfold ghzAmplitude
    rw [star_prod]
    apply Finset.prod_congr rfl
    intro n _hn
    split <;> simp
  rw [hstar]
  unfold ghzAmplitude
  simp only [finRotate_apply]
  rw [← Finset.prod_mul_distrib]
  apply Finset.prod_congr rfl
  intro n _hn
  simp only [constantPairWeight]
  by_cases hs : sigma n = sigma (n + 1) <;>
    by_cases ht : tau n = tau (n + 1) <;> simp [hs, ht]

/-- The ambient base tensor generates positive operators at every nonempty
chain length. -/
theorem baseMPO_isMPDO : IsMPDO baseMPO := by
  intro N hN
  rw [mpo_baseMPO_eq_unnormalizedGHZRankOne N hN]
  exact Matrix.posSemidef_vecMulVec_self_star (ghzAmplitude N)

/-- After the canonical identification of two-site words with ordered pairs,
the length-two ambient operator is the companion Bell projector from the
singleton Gram boundary. -/
theorem twoSite_baseMPO_eq_bellProjector :
    Matrix.reindex (finTwoArrowEquiv I) (finTwoArrowEquiv I)
      (mpo baseMPO 2) = bellProjector := by
  rw [mpo_baseMPO_eq_unnormalizedGHZRankOne 2 (by norm_num)]
  ext p q
  rcases p with ⟨p₀, p₁⟩
  rcases q with ⟨q₀, q₁⟩
  fin_cases p₀ <;> fin_cases p₁ <;> fin_cases q₀ <;> fin_cases q₁ <;>
    norm_num [Matrix.reindex_apply, unnormalizedGHZRankOne, ghzAmplitude,
      bellProjector, bellVector, Matrix.vecMulVec, finTwoArrowEquiv,
      piFinTwoEquiv_apply, finRotate_apply, Fin.prod_univ_two, Fin.add_def,
      Matrix.cons_val_zero, Matrix.cons_val_one]

/-! ### Literal CPSV canonical form -/

/-- The bond-one normal block supported on one doubled physical symbol. -/
def baseSymbolTensor (a : Fin 4) : MPSTensor 4 1 :=
  fun i ↦ if i = a then 1 else 0

private theorem baseSymbolTensor_transferMap (a : Fin 4) :
    MPSTensor.transferMap (baseSymbolTensor a) = LinearMap.id := by
  apply LinearMap.ext
  intro X
  ext x y
  fin_cases x
  fin_cases y
  simp [MPSTensor.transferMap_apply, baseSymbolTensor]

/-- Every symbol block in the four-block decomposition is a normal tensor. -/
theorem baseSymbolTensor_isNormalTensor (a : Fin 4) :
    MPSTensor.IsNormalTensor (baseSymbolTensor a) :=
  MPSTensor.isNormalTensor_of_bondDim_one_of_transferMap_eq_id
    (baseSymbolTensor a) (baseSymbolTensor_transferMap a)

/-- The four bond-one blocks used in the literal canonical form. -/
def baseSymbolBlocks : (a : Fin 4) → MPSTensor 4 1 :=
  baseSymbolTensor

/-- The doubled-index tensor of the ambient MPO is literally the direct sum of
its four bond-one symbol blocks, each with weight one. -/
theorem baseMPO_toMPSTensor_eq_symbolBlocks :
    baseMPO.toMPSTensor =
      MPSTensor.toTensorFromBlocks (fun _ : Fin 4 ↦ (1 : ℂ)) baseSymbolBlocks := by
  let e : (Σ _k : Fin 4, Fin 1) ≃ Fin 4 := finSigmaFinEquiv
  have hflat (k : Fin 4) : e ⟨k, 0⟩ = k := by
    fin_cases k <;> rfl
  have hflat_symm (k : Fin 4) : e.symm k = ⟨k, 0⟩ := by
    apply e.injective
    rw [e.apply_symm_apply, hflat]
  funext p
  obtain ⟨⟨i, j⟩, rfl⟩ :=
    (finProdFinEquiv : I × I ≃ Fin 4).surjective p
  ext x y
  simp only [baseMPO, toMPSTensor, MPSTensor.toTensorFromBlocks,
    baseSymbolBlocks, baseSymbolTensor, Matrix.reindex_apply, one_smul,
    MPSTensor.finProdFinEquiv_divNat, MPSTensor.finProdFinEquiv_modNat]
  change Matrix.single (finProdFinEquiv (i, j)) (finProdFinEquiv (i, j)) 1 x y =
    Matrix.blockDiagonal' (fun k : Fin 4 ↦ baseSymbolTensor k (finProdFinEquiv (i, j)))
      (e.symm x) (e.symm y)
  rw [hflat_symm x, hflat_symm y]
  by_cases h : x = y
  · subst y
    by_cases hp : finProdFinEquiv (i, j) = x <;>
      simp [hp, baseSymbolTensor, Matrix.single]
  · rw [Matrix.blockDiagonal'_apply_ne _ _ _ h]
    simp [Matrix.single]
    aesop

/-- The ambient doubled-index MPS is in literal CPSV canonical form via the
four displayed bond-one symbol blocks. -/
theorem baseMPO_toMPSTensor_isCPSVCanonicalForm :
    MPSTensor.IsCPSVCanonicalForm baseMPO.toMPSTensor := by
  rw [baseMPO_toMPSTensor_eq_symbolBlocks]
  exact (MPSTensor.CPSVCanonicalFormData.ofBlocks
    (fun _ : Fin 4 ↦ by simp)
    (fun _ : Fin 4 ↦ (1 : ℂ)) baseSymbolBlocks
    (fun a ↦ baseSymbolTensor_isNormalTensor a)).isCPSVCanonicalForm

/-! ### Raw retained cyclic-edge projections -/

/-- The source vertex of an encoded directed two-state edge. -/
def edgeSource (x : Fin 4) : I :=
  (finProdFinEquiv.symm x : I × I).1

/-- The target vertex of an encoded directed two-state edge. -/
def edgeTarget (x : Fin 4) : I :=
  (finProdFinEquiv.symm x : I × I).2

/-- The indicator that a word of directed two-state edges closes cyclically. -/
def retainedCyclicIndicator (N : ℕ) (sigma : Fin N → Fin 4) : ℂ :=
  ∏ n : Fin N,
    if edgeTarget (sigma n) = edgeSource (sigma (finRotate N n)) then 1 else 0

/-- At length zero the retained closed word is the bond-two identity, whose
trace gives the scalar two. -/
theorem mpo_verticalBNTMPO_singletonTensor_zero :
    mpo (verticalBNTMPO singletonTensor) 0 = (2 : ℂ) • 1 := by
  ext sigma tau
  have h : sigma = tau := Subsingleton.elim _ _
  subst tau
  simp [mpo, mpoMatrixEntry, evalWord_nil, Matrix.trace]

/-- The empty cyclic product is one, so its diagonal matrix is the identity. -/
theorem retainedCyclicIndicator_zero_diagonal :
    Matrix.diagonal (retainedCyclicIndicator 0) = 1 := by
  ext sigma tau
  have h : sigma = tau := Subsingleton.elim _ _
  subst tau
  simp [retainedCyclicIndicator]

/-- Thus the retained cyclic-indicator formula genuinely fails at length zero. -/
theorem mpo_verticalBNTMPO_singletonTensor_zero_ne_diagonal :
    mpo (verticalBNTMPO singletonTensor) 0 ≠
      Matrix.diagonal (retainedCyclicIndicator 0) := by
  rw [mpo_verticalBNTMPO_singletonTensor_zero,
    retainedCyclicIndicator_zero_diagonal]
  intro h
  have hentry := congrArg (fun A ↦ A default default) h
  norm_num at hentry

/-- The retained singleton's positive-length closed operators are diagonal
cyclic-edge indicators. -/
theorem mpo_verticalBNTMPO_singletonTensor_eq_diagonal
    (N : ℕ) (hN : 0 < N) :
    mpo (verticalBNTMPO singletonTensor) N =
      Matrix.diagonal (retainedCyclicIndicator N) := by
  letI : NeZero N := ⟨Nat.ne_of_gt hN⟩
  ext sigma tau
  rw [mpo_apply, mpoMatrixEntry, evalWord_ofFn]
  have hcyc := MPSTensor.trace_evalWord_eq_sum_cyclic singletonTensor
    (fun n ↦ finProdFinEquiv (sigma n, tau n))
  rw [MPSTensor.evalWord_ofFn_eq_prod] at hcyc
  change (List.ofFn fun n ↦ singletonTensor
      (finProdFinEquiv (sigma n, tau n))).prod.trace = _
  rw [hcyc]
  let g0 : Fin N → I := fun n ↦ edgeSource (sigma n)
  rw [Fintype.sum_eq_single g0]
  · rw [Matrix.diagonal_apply]
    by_cases hst : sigma = tau
    · subst tau
      simp only [retainedCyclicIndicator]
      apply Finset.prod_congr rfl
      intro n _hn
      simp only [singletonTensor, Equiv.symm_apply_apply,
        Matrix.single, g0, finRotate_apply]
      split_ifs <;> simp_all [edgeSource, edgeTarget]
    · rw [if_neg hst]
      obtain ⟨n, hn⟩ := Function.ne_iff.mp hst
      apply Finset.prod_eq_zero (Finset.mem_univ n)
      simp [singletonTensor, hn]
  · intro g hg
    obtain ⟨n, hn⟩ := Function.ne_iff.mp hg
    apply Finset.prod_eq_zero (Finset.mem_univ n)
    dsimp [g0, edgeSource] at hn
    by_cases hs : sigma n = tau n
    · rw [← hs]
      simp [singletonTensor, Matrix.single]
      aesop
    · simp [singletonTensor, hs]

private lemma retainedCyclicIndicator_eq_zero_or_one
    (N : ℕ) (sigma : Fin N → Fin 4) :
    retainedCyclicIndicator N sigma = 0 ∨
      retainedCyclicIndicator N sigma = 1 := by
  classical
  by_cases h : ∀ n : Fin N,
      edgeTarget (sigma n) = edgeSource (sigma (finRotate N n))
  · right
    unfold retainedCyclicIndicator
    apply Finset.prod_eq_one
    intro n _hn
    simp [h n]
  · left
    push Not at h
    obtain ⟨n, hn⟩ := h
    unfold retainedCyclicIndicator
    apply Finset.prod_eq_zero (Finset.mem_univ n)
    rw [if_neg (by simpa only [finRotate_apply] using hn)]

/-- At every positive length the raw retained closed operator is Hermitian and
idempotent, hence an orthogonal projection in the matrix algebra indexed by
edge words. -/
theorem mpo_verticalBNTMPO_singletonTensor_isHermitian_and_idempotent
    (N : ℕ) (hN : 0 < N) :
    (mpo (verticalBNTMPO singletonTensor) N).IsHermitian ∧
      mpo (verticalBNTMPO singletonTensor) N *
        mpo (verticalBNTMPO singletonTensor) N =
          mpo (verticalBNTMPO singletonTensor) N := by
  rw [mpo_verticalBNTMPO_singletonTensor_eq_diagonal N hN]
  constructor
  · change (Matrix.diagonal (retainedCyclicIndicator N))ᴴ =
      Matrix.diagonal (retainedCyclicIndicator N)
    ext sigma tau
    by_cases hst : sigma = tau
    · subst tau
      rcases retainedCyclicIndicator_eq_zero_or_one N sigma with hzero | hone
      · simp [Matrix.conjTranspose_apply, hzero]
      · simp [Matrix.conjTranspose_apply, hone]
    · simp [Matrix.conjTranspose_apply, hst, Ne.symm hst]
  · rw [Matrix.diagonal_mul_diagonal]
    apply congrArg Matrix.diagonal
    funext sigma
    rcases retainedCyclicIndicator_eq_zero_or_one N sigma with hzero | hone
    · simp [hzero]
    · simp [hone]

/-- The raw retained closed operator is a star projection at every positive
length. -/
theorem mpo_verticalBNTMPO_singletonTensor_isStarProjection
    (N : ℕ) (hN : 0 < N) :
    IsStarProjection (mpo (verticalBNTMPO singletonTensor) N) := by
  rw [isStarProjection_iff']
  have h := mpo_verticalBNTMPO_singletonTensor_isHermitian_and_idempotent N hN
  exact ⟨h.2, by simpa [Matrix.star_eq_conjTranspose] using h.1.eq⟩

/-- The coefficient-one multiplication law for the raw singleton retained
operator. -/
theorem raw_singleton_coefficient_one_algebra
    (L : ℕ) (hL : 0 < L) :
    mpo (verticalBNTMPO singletonTensor) L *
        mpo (verticalBNTMPO singletonTensor) L =
      ∑ _gamma : Fin 1, (1 : ℂ) •
        mpo (verticalBNTMPO singletonTensor) L := by
  rw [(mpo_verticalBNTMPO_singletonTensor_isHermitian_and_idempotent L hL).2]
  simp

/-! ### Normalized singleton -/

/-- The positive normalization scalar `sqrt (1/2)`. -/
def singletonScale : ℝ := Real.sqrt (1 / 2)

/-- The normalized singleton retained tensor. -/
def normalizedSingletonTensor : MPSTensor (4 * 4) 2 :=
  fun v ↦ (singletonScale : ℂ) • singletonTensor v

private lemma singletonScale_pos : 0 < singletonScale := by
  simp [singletonScale]

private lemma singletonScale_sq : singletonScale ^ 2 = 1 / 2 := by
  rw [singletonScale, Real.sq_sqrt]
  norm_num

private lemma singletonScale_star_mul :
    star ((singletonScale : ℝ) : ℂ) * (singletonScale : ℂ) = 1 / 2 := by
  rw [show star ((singletonScale : ℝ) : ℂ) = (singletonScale : ℂ) by simp]
  rw [← Complex.ofReal_mul, ← pow_two, singletonScale_sq]
  norm_num

private lemma singletonScale_mul :
    (singletonScale : ℂ) * (singletonScale : ℂ) = 1 / 2 := by
  simpa using singletonScale_star_mul

/-- The normalized singleton is left-canonical. -/
theorem normalizedSingletonTensor_isLeftCanonical :
    MPSTensor.IsLeftCanonical normalizedSingletonTensor := by
  unfold MPSTensor.IsLeftCanonical
  calc
    (∑ v : Fin (4 * 4),
        (normalizedSingletonTensor v)ᴴ * normalizedSingletonTensor v) =
        ∑ x : Fin 4,
          (normalizedSingletonTensor (finProdFinEquiv (x, x)))ᴴ *
            normalizedSingletonTensor (finProdFinEquiv (x, x)) := by
      rw [← Equiv.sum_comp
        (finProdFinEquiv : Fin 4 × Fin 4 ≃ Fin (4 * 4))]
      rw [Fintype.sum_prod_type]
      simp [normalizedSingletonTensor, singletonTensor]
    _ = ∑ ab : I × I,
          (normalizedSingletonTensor
            (finProdFinEquiv (finProdFinEquiv ab, finProdFinEquiv ab)))ᴴ *
          normalizedSingletonTensor
            (finProdFinEquiv (finProdFinEquiv ab, finProdFinEquiv ab)) :=
      (Equiv.sum_comp (finProdFinEquiv : I × I ≃ Fin 4)
        (fun x : Fin 4 ↦
          (normalizedSingletonTensor (finProdFinEquiv (x, x)))ᴴ *
            normalizedSingletonTensor (finProdFinEquiv (x, x)))).symm
    _ = 1 := by
      rw [Fintype.sum_prod_type]
      simp_rw [normalizedSingletonTensor, singletonTensor_diagonal]
      ext i j
      fin_cases i <;> fin_cases j <;>
        simp [Matrix.mul_apply, Matrix.conjTranspose_apply, Fin.sum_univ_two,
          Matrix.single, singletonScale_mul] <;> norm_num

/-- The normalized singleton is a CPSV normal tensor. -/
theorem normalizedSingletonTensor_isNormalTensor :
    MPSTensor.IsNormalTensor normalizedSingletonTensor := by
  have hs : ((singletonScale : ℝ) : ℂ) ≠ 0 := by
    exact_mod_cast ne_of_gt singletonScale_pos
  have hNormal : normalizedSingletonTensor.IsNormal :=
    (singletonTensor_isInjective.smul hs).isNormal
  exact MPSTensor.isNormalTensor_of_isNormal_leftCanonical
    normalizedSingletonTensor hNormal normalizedSingletonTensor_isLeftCanonical

/-- Closed normalized singleton operators differ from the raw cyclic-edge
projections by the geometric factor `singletonScale ^ L`. -/
theorem mpo_verticalBNTMPO_normalizedSingletonTensor
    (L : ℕ) :
    mpo (verticalBNTMPO normalizedSingletonTensor) L =
      ((singletonScale : ℂ) ^ L) •
        mpo (verticalBNTMPO singletonTensor) L := by
  ext sigma tau
  rw [← MPSTensor.mpv_toMPSTensor_pairConfig,
    verticalBNTMPO_toMPSTensor]
  change MPSTensor.mpv
      (fun v ↦ (singletonScale : ℂ) • singletonTensor v)
      (fun n ↦ finProdFinEquiv (sigma n, tau n)) = _
  rw [MPSTensor.mpv_smul]
  change (singletonScale : ℂ) ^ L *
      MPSTensor.mpv singletonTensor
        (fun n ↦ finProdFinEquiv (sigma n, tau n)) =
    (singletonScale : ℂ) ^ L *
      mpo (verticalBNTMPO singletonTensor) L sigma tau
  congr 1
  simpa only [verticalBNTMPO_toMPSTensor] using
    MPSTensor.mpv_toMPSTensor_pairConfig
      (verticalBNTMPO singletonTensor) sigma tau

/-- The normalized one-label operator algebra has coefficient
`singletonScale ^ L`. -/
theorem normalized_singleton_geometric_algebra
    (L : ℕ) (hL : 0 < L) :
    mpo (verticalBNTMPO normalizedSingletonTensor) L *
        mpo (verticalBNTMPO normalizedSingletonTensor) L =
      ((singletonScale : ℂ) ^ L) •
        mpo (verticalBNTMPO normalizedSingletonTensor) L := by
  rw [mpo_verticalBNTMPO_normalizedSingletonTensor,
    Matrix.smul_mul, Matrix.mul_smul,
    (mpo_verticalBNTMPO_singletonTensor_isHermitian_and_idempotent L hL).2]

/-- The one-dimensional positive chi family with diagonal entry
`singletonScale`. -/
def normalizedSingletonChi : DiagonalChiFamily (Fin 1) where
  dim _ _ _ := 1
  entry _ _ _ _ := singletonScale

/-- The canonical coefficient family of the normalized singleton chi. -/
def normalizedSingletonCoeffs : BNTLabelCoefficientFamily (Fin 1) :=
  BNTLabelCoefficientFamily.ofChi normalizedSingletonChi

theorem normalizedSingletonCoeffs_coeff
    (L : ℕ) (alpha beta gamma : Fin 1) :
    normalizedSingletonCoeffs.coeff L alpha beta gamma =
      (singletonScale : ℂ) ^ L := by
  simp [normalizedSingletonCoeffs, BNTLabelCoefficientFamily.ofChi,
    DiagonalChiFamily.tracePowerCoeff, normalizedSingletonChi]

/-- The normalized singleton family, indexed by its unique BNT label. -/
private def normalizedSingletonFamily :
    (alpha : Fin 1) → MPSTensor (4 * 4) 2 :=
  fun _ ↦ normalizedSingletonTensor

/-- The multiplicity weight reconstructing the raw singleton from its
normalized representative. -/
private def normalizedSingletonWeight : (alpha : Fin 1) → Fin 1 → ℂ :=
  fun _ _ ↦ (singletonScale : ℂ)⁻¹

private def retainedZeroLoopLetter : Fin (4 * 4) :=
  finProdFinEquiv
    (finProdFinEquiv ((0 : I), (0 : I)), finProdFinEquiv ((0 : I), (0 : I)))

private lemma normalizedSingletonTensor_mpv_zeroLoop
    (N : ℕ) (hN : 0 < N) :
    MPSTensor.mpv normalizedSingletonTensor
      (fun _ : Fin N ↦ retainedZeroLoopLetter) =
        (singletonScale : ℂ) ^ N := by
  rw [MPSTensor.mpv_const_eq_trace_pow]
  have hletter : normalizedSingletonTensor retainedZeroLoopLetter =
      (singletonScale : ℂ) • Matrix.single (0 : I) (0 : I) 1 := by
    rw [normalizedSingletonTensor, retainedZeroLoopLetter,
      singletonTensor_diagonal]
  rw [hletter, smul_pow]
  have hE : IsIdempotentElem (Matrix.single (0 : I) (0 : I) (1 : ℂ)) := by
    simp [IsIdempotentElem, Matrix.single_mul_single_same]
  rw [hE.pow_eq (Nat.ne_of_gt hN)]
  simp [Matrix.trace, Matrix.single]

/-- The unique normalized block is a CPSV basis of normal tensors for the raw
vertical singleton. -/
theorem normalizedSingleton_isCPSVBasis :
    MPSTensor.IsCPSVBasisOfNormalTensors singletonTensor
      (fun _ : Fin 1 ↦ ⟨2, normalizedSingletonTensor⟩) := by
  refine {
    blocks_normal := fun _ ↦ normalizedSingletonTensor_isNormalTensor
    spans_mpv := ?_
    eventually_li := ?_
  }
  · intro N _hN
    refine ⟨fun _ ↦ (singletonScale : ℂ)⁻¹ ^ N, ?_⟩
    intro sigma
    simp only [Finset.univ_unique, Fin.default_eq_zero, Finset.sum_singleton]
    change MPSTensor.mpv singletonTensor sigma =
      (singletonScale : ℂ)⁻¹ ^ N *
        MPSTensor.mpv (fun v ↦ (singletonScale : ℂ) • singletonTensor v) sigma
    rw [MPSTensor.mpv_smul]
    have hs : (singletonScale : ℂ) ≠ 0 := by
      exact_mod_cast ne_of_gt singletonScale_pos
    symm
    calc
      (singletonScale : ℂ)⁻¹ ^ N *
          ((singletonScale : ℂ) ^ N * MPSTensor.mpv singletonTensor sigma) =
        ((singletonScale : ℂ)⁻¹ ^ N * (singletonScale : ℂ) ^ N) *
          MPSTensor.mpv singletonTensor sigma := (mul_assoc _ _ _).symm
      _ = MPSTensor.mpv singletonTensor sigma := by
        rw [← mul_pow, inv_mul_cancel₀ hs, one_pow, one_mul]
  · refine ⟨0, ?_⟩
    intro N hN
    apply LinearIndependent.of_subsingleton (i := (0 : Fin 1))
    intro hzero
    have hcomponent := congrArg
      (fun v : MPSTensor.MPVSpace (4 * 4) N ↦
        v (fun _ : Fin N ↦ retainedZeroLoopLetter)) hzero
    have hs : (singletonScale : ℂ) ≠ 0 := by
      exact_mod_cast ne_of_gt singletonScale_pos
    have hpow : (singletonScale : ℂ) ^ N ≠ 0 := pow_ne_zero N hs
    apply hpow
    simpa only [MPSTensor.mpvState_apply,
      normalizedSingletonTensor_mpv_zeroLoop N hN, PiLp.zero_apply] using hcomponent

/-- The one-label weighted reconstruction recovers the raw singleton tensor. -/
theorem normalizedSingleton_verticalAssembledTensor :
    verticalAssembledTensor (fun _ : Fin 1 ↦ 2) (fun _ : Fin 1 ↦ 1)
      normalizedSingletonWeight normalizedSingletonFamily = singletonTensor := by
  let e : (Σ _k : Fin 1, Fin 2) ≃ Fin 2 := finSigmaFinEquiv
  have hsymm (i : Fin 2) : e.symm i = ⟨0, i⟩ := by
    apply e.injective
    rw [e.apply_symm_apply]
    ext
    exact (@finSigmaFinEquiv_one (fun _ : Fin 1 ↦ 2) ⟨(0 : Fin 1), i⟩).symm
  have hs : (singletonScale : ℂ) ≠ 0 := by
    exact_mod_cast ne_of_gt singletonScale_pos
  funext v
  ext i j
  simp only [verticalAssembledTensor, verticalCopyWeights, verticalCopyBlocks,
    verticalCopyDim, MPSTensor.toTensorFromBlocks, normalizedSingletonWeight,
    normalizedSingletonFamily, normalizedSingletonTensor]
  change (Matrix.reindex e e
      (Matrix.blockDiagonal' (fun _k : Fin 1 ↦
        (singletonScale : ℂ)⁻¹ •
          ((singletonScale : ℂ) • singletonTensor v)))) i j = singletonTensor v i j
  simp [Matrix.reindex_apply, hsymm, hs]

private abbrev singletonBondDim : Fin 1 → ℕ := fun _ ↦ 2
private abbrev singletonMultiplicity : Fin 1 → ℕ := fun _ ↦ 1
private abbrev SingletonRetainedCoordinate :=
  Fin (∑ q : Fin (∑ alpha : Fin 1, singletonMultiplicity alpha),
    verticalCopyDim singletonBondDim singletonMultiplicity q)

/-- The unique-label/unique-copy sector coordinate is canonically its bond
coordinate. -/
def singletonSectorCoordinateEquiv :
    (Σ alpha : Fin 1, Fin (singletonMultiplicity alpha) ×
      Fin (singletonBondDim alpha)) ≃ Fin 2 where
  toFun x := x.2.2
  invFun i := ⟨0, (0, i)⟩
  left_inv x := by
    rcases x with ⟨alpha, q, i⟩
    fin_cases alpha
    fin_cases q
    rfl
  right_inv _ := rfl

/-- Canonical equivalence between the dependent retained coordinates and the
original two-dimensional physical space. -/
def singletonRetainedCoordinateEquiv : SingletonRetainedCoordinate ≃ Fin 2 :=
  (verticalSectorFinEquiv singletonBondDim singletonMultiplicity).symm.trans
    singletonSectorCoordinateEquiv

private theorem singletonRetainedCoordinateEquiv_apply
    (x : SingletonRetainedCoordinate) :
    singletonRetainedCoordinateEquiv x = x := by
  fin_cases x <;> rfl

/-- The square coordinate-change matrix induced by the canonical retained
coordinate equivalence. -/
noncomputable def singletonVerticalCoisometry :
    Matrix SingletonRetainedCoordinate (Fin 2) ℂ :=
  Matrix.reindex singletonRetainedCoordinateEquiv.symm (Equiv.refl (Fin 2))
    (1 : Matrix (Fin 2) (Fin 2) ℂ)

private theorem singletonVerticalCoisometry_apply
    (x : SingletonRetainedCoordinate) (i : Fin 2) :
    singletonVerticalCoisometry x i =
      if singletonRetainedCoordinateEquiv x = i then 1 else 0 := by
  simp [singletonVerticalCoisometry, Matrix.reindex_apply, Matrix.one_apply]

/-- The canonical retained-coordinate matrix is a coisometry. -/
theorem singletonVerticalCoisometry_coisometry :
    singletonVerticalCoisometry * singletonVerticalCoisometryᴴ =
      (1 : Matrix SingletonRetainedCoordinate SingletonRetainedCoordinate ℂ) := by
  ext x y
  simp [Matrix.mul_apply, Matrix.conjTranspose_apply,
    singletonVerticalCoisometry_apply, Matrix.one_apply]

/-- Conjugation by the coordinate matrix reindexes an ambient matrix into the
retained coordinates. -/
theorem singletonVerticalCoisometry_conj
    (A : Matrix (Fin 2) (Fin 2) ℂ) :
    singletonVerticalCoisometry * A * singletonVerticalCoisometryᴴ =
      Matrix.reindex singletonRetainedCoordinateEquiv.symm
        singletonRetainedCoordinateEquiv.symm A := by
  ext x y
  simp [Matrix.mul_apply, Matrix.conjTranspose_apply,
    singletonVerticalCoisometry_apply, Matrix.reindex_apply]

private theorem singletonVerticalCoisometry_conjTranspose :
    (singletonVerticalCoisometryᴴ :
      Matrix (Fin 2) SingletonRetainedCoordinate ℂ) =
      Matrix.reindex (Equiv.refl (Fin 2))
        singletonRetainedCoordinateEquiv.symm
        (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  ext i x
  rw [Matrix.conjTranspose_apply, singletonVerticalCoisometry_apply]
  change star (if singletonRetainedCoordinateEquiv x = i then 1 else 0) =
    if i = singletonRetainedCoordinateEquiv x then 1 else 0
  by_cases h : singletonRetainedCoordinateEquiv x = i
  · simp [h]
  · simp [h, Ne.symm h]

private theorem singletonRetainedCoordinate_reindex_eq_self
    (A : Matrix (Fin 2) (Fin 2) ℂ) :
    Matrix.reindex singletonRetainedCoordinateEquiv.symm
      singletonRetainedCoordinateEquiv.symm A = A := by
  ext x y
  simp [Matrix.reindex_apply, singletonRetainedCoordinateEquiv_apply]

private theorem singletonVerticalCoisometry_conj_eq_self
    (A : Matrix (Fin 2) (Fin 2) ℂ) :
    singletonVerticalCoisometry * A * singletonVerticalCoisometryᴴ = A := by
  rw [singletonVerticalCoisometry_conj,
    singletonRetainedCoordinate_reindex_eq_self]

/-- Conjugating a retained-coordinate matrix back by the adjoint inverts the
canonical reindexing. -/
theorem singletonVerticalCoisometry_reconstruction
    (A : Matrix (Fin 2) (Fin 2) ℂ) :
    (singletonVerticalCoisometryᴴ :
        Matrix (Fin 2) SingletonRetainedCoordinate ℂ) *
        Matrix.reindex singletonRetainedCoordinateEquiv.symm
          singletonRetainedCoordinateEquiv.symm A *
      singletonVerticalCoisometry = A := by
  rw [singletonVerticalCoisometry_conjTranspose, singletonVerticalCoisometry]
  have hleft :
      Matrix.reindex (Equiv.refl (Fin 2)) singletonRetainedCoordinateEquiv.symm
          (1 : Matrix (Fin 2) (Fin 2) ℂ) *
        Matrix.reindex singletonRetainedCoordinateEquiv.symm
          singletonRetainedCoordinateEquiv.symm A =
      Matrix.reindex (Equiv.refl (Fin 2)) singletonRetainedCoordinateEquiv.symm
        ((1 : Matrix (Fin 2) (Fin 2) ℂ) * A) := by
    simpa only [Matrix.coe_reindexLinearEquiv] using
      Matrix.reindexLinearEquiv_mul ℂ ℂ
        (Equiv.refl (Fin 2)) singletonRetainedCoordinateEquiv.symm
        singletonRetainedCoordinateEquiv.symm
        (1 : Matrix (Fin 2) (Fin 2) ℂ) A
  rw [hleft]
  have hright :
      Matrix.reindex (Equiv.refl (Fin 2)) singletonRetainedCoordinateEquiv.symm
          ((1 : Matrix (Fin 2) (Fin 2) ℂ) * A) *
        Matrix.reindex singletonRetainedCoordinateEquiv.symm
          (Equiv.refl (Fin 2)) (1 : Matrix (Fin 2) (Fin 2) ℂ) =
      Matrix.reindex (Equiv.refl (Fin 2)) (Equiv.refl (Fin 2))
        (((1 : Matrix (Fin 2) (Fin 2) ℂ) * A) * 1) := by
    simpa only [Matrix.coe_reindexLinearEquiv] using
      Matrix.reindexLinearEquiv_mul ℂ ℂ
        (Equiv.refl (Fin 2)) singletonRetainedCoordinateEquiv.symm
        (Equiv.refl (Fin 2))
        ((1 : Matrix (Fin 2) (Fin 2) ℂ) * A)
        (1 : Matrix (Fin 2) (Fin 2) ℂ)
  rw [hright]
  simp [Matrix.reindex_apply]

/-- The normalized singleton carries the complete one-label coefficient,
positive-chi, product, and idempotent algebra data. -/
noncomputable def normalizedSingletonAlgebraClause :
    BNTAlgebraClause normalizedSingletonCoeffs
      (verticalBNTOperatorFamily normalizedSingletonFamily)
      (verticalBNTTraceScalarFamily normalizedSingletonWeight) := by
  refine {
    positiveChi := PositiveBNTLabelChiTracePowerForm.ofChi
      normalizedSingletonChi ?_
    sameLengthProduct := ?_
    idempotent := ?_
  }
  · intro alpha beta gamma q
    simpa [normalizedSingletonChi] using
      (Complex.zero_lt_real.mpr singletonScale_pos)
  · intro L hL alpha beta
    fin_cases alpha
    fin_cases beta
    simpa [normalizedSingletonFamily, normalizedSingletonCoeffs_coeff] using
      normalized_singleton_geometric_algebra L hL
  · intro gamma
    fin_cases gamma
    have hs : (singletonScale : ℂ) ≠ 0 := by
      exact_mod_cast ne_of_gt singletonScale_pos
    simp only [verticalBNTTraceScalarFamily_traceScalar,
      normalizedSingletonWeight, Finset.univ_unique, Fin.default_eq_zero,
      Finset.sum_singleton, normalizedSingletonCoeffs_coeff]
    field_simp

private theorem singletonMultiplicity_pos
    (alpha : Fin 1) : 0 < singletonMultiplicity alpha := by
  simp [singletonMultiplicity]

private theorem normalizedSingletonWeight_pos
    (alpha : Fin 1) (q : Fin (singletonMultiplicity alpha)) :
    (0 : ℂ) < normalizedSingletonWeight alpha q := by
  have hs : (0 : ℂ) < (singletonScale : ℂ) :=
    Complex.zero_lt_real.mpr singletonScale_pos
  simpa [normalizedSingletonWeight] using inv_pos.mpr hs

private theorem baseMPO_isCPSVBasis :
    MPSTensor.IsCPSVBasisOfNormalTensors (verticalTensor baseMPO)
      (fun alpha : Fin 1 ↦
        ⟨singletonBondDim alpha, normalizedSingletonFamily alpha⟩) := by
  rw [verticalTensor_baseMPO]
  exact normalizedSingleton_isCPSVBasis

private theorem baseMPO_vertical_forward (v : Fin (4 * 4)) :
    singletonVerticalCoisometry * verticalTensor baseMPO v *
        singletonVerticalCoisometryᴴ =
      verticalAssembledTensor singletonBondDim singletonMultiplicity
        normalizedSingletonWeight normalizedSingletonFamily v := by
  rw [verticalTensor_baseMPO, normalizedSingleton_verticalAssembledTensor]
  exact singletonVerticalCoisometry_conj_eq_self (singletonTensor v)

private theorem baseMPO_vertical_reconstruction (v : Fin (4 * 4)) :
    verticalTensor baseMPO v = singletonVerticalCoisometryᴴ *
        verticalAssembledTensor singletonBondDim singletonMultiplicity
          normalizedSingletonWeight normalizedSingletonFamily v *
      singletonVerticalCoisometry := by
  rw [verticalTensor_baseMPO]
  have hassembled :
      verticalAssembledTensor singletonBondDim singletonMultiplicity
          normalizedSingletonWeight normalizedSingletonFamily v =
        Matrix.reindex singletonRetainedCoordinateEquiv.symm
          singletonRetainedCoordinateEquiv.symm (singletonTensor v) := by
    rw [normalizedSingleton_verticalAssembledTensor,
      singletonRetainedCoordinate_reindex_eq_self]
  rw [hassembled]
  exact (singletonVerticalCoisometry_reconstruction (singletonTensor v)).symm

/-- The base MPO carries the genuine one-label tensor-attached BNT algebra
clause.  Its retained coordinates are related to the ambient bond coordinates
by the canonical permutation matrix `singletonVerticalCoisometry`. -/
noncomputable def baseMPOBNTAlgebraTensorClause :
    BNTAlgebraTensorClause baseMPO where
  labelCount := 1
  bondDim := singletonBondDim
  multiplicity := singletonMultiplicity
  weight := normalizedSingletonWeight
  tensor := normalizedSingletonFamily
  verticalCoisometry := singletonVerticalCoisometry
  multiplicity_pos := singletonMultiplicity_pos
  weight_pos := normalizedSingletonWeight_pos
  coisometry := singletonVerticalCoisometry_coisometry
  isCPSVBNT := baseMPO_isCPSVBasis
  forward := baseMPO_vertical_forward
  reconstruction := baseMPO_vertical_reconstruction
  coeffs := normalizedSingletonCoeffs
  algebraClause := normalizedSingletonAlgebraClause

/-- The singleton base MPO admits a tensor-attached BNT algebra clause. -/
theorem baseMPO_hasBNTAlgebraTensorClause :
    HasBNTAlgebraTensorClause baseMPO :=
  ⟨baseMPOBNTAlgebraTensorClause⟩

end MPOTensor.BondTwoSingletonBaseModel
