/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.ComplexSqrt
import TNLean.MPS.MPDO.LPDO
import TNLean.MPS.MPDO.LocalPurificationRFP

/-!
# Corrected operator for CPSV16 Example 4.10

This module defines the four-dimensional one-site matrix product density operator obtained by
applying, independently at each site, the corrected correlated left-right bit flip of probability
one quarter to the ring of Bell pairs in CPSV16 Example 4.10.

**Local fix (left-right correlated flip):** the channel printed at source lines 901--902 repeats
the left-qubit label. The tensor below uses one Pauli flip on each qubit of the same spin, as
required by the Bell-pair network and by the entropy values printed at line 904. See
`docs/paper-gaps/cpsv16_examples_4_10_4_11_entropy.tex`.

## Main definitions

* `purifier`: a two-outcome local purification of the corrected channel output.
* `M`: the corrected matrix product density operator tensor.

## Main results

* `M_isLPDO` and `M_isMPDO`: positivity of every positive-length periodic operator.
* `physTraceTransfer_M` and `M_isSourceZCL`: the exact source physical-trace relation.

## Reference

* Cirac--Perez-Garcia--Schuch--Verstraete, arXiv:1606.00608, Example 4.10,
  lines 897--905.
-/

open scoped Matrix BigOperators ComplexOrder

noncomputable section

namespace MPOTensor.CPSVExample410Operator

/-- The scalar attached to the no-flip and flip purification outcomes. Their squared moduli are
$3/4$ and $1/4$, respectively. CPSV16 Example 4.10, lines 897--905. -/
def channelCoeff (k : Fin 2) : ℂ :=
  if k = 0 then Real.sqrt 3 / 2 else 1 / 2

/-- The standard identification of one four-dimensional spin with its left and right qubits.
CPSV16 Example 4.10, lines 897--905. -/
def pairEquiv : Fin 4 ≃ Fin 2 × Fin 2 :=
  (finCongr (by norm_num : 4 = 2 * 2)).trans
    (finProdFinEquiv (m := 2) (n := 2)).symm

/-- Simultaneous bit flip of the two qubits belonging to one spin. CPSV16 Example 4.10,
lines 897--905. -/
def correlatedFlip (i : Fin 4) : Fin 4 :=
  pairEquiv.symm (1 - (pairEquiv i).1, 1 - (pairEquiv i).2)

/-- The pure spin-ancilla tensor whose ancillary trace applies the corrected correlated flip
channel to the ring of Bell pairs. The ancillary value zero records no flip and value one records
the left-right correlated flip. CPSV16 Example 4.10, lines 897--905. -/
def purifier (i : Fin 4) (k : Fin 2) : Matrix (Fin 2) (Fin 2) ℂ :=
  let q := if k = 0 then i else correlatedFlip i
  (channelCoeff k / Real.sqrt 2) •
    Matrix.single (pairEquiv q).1 (pairEquiv q).2 1

/-- One ancillary summand in the local purification contraction for CPSV16 Example 4.10,
lines 897--905. -/
def purifierTerm (i j : Fin 4) (k : Fin 2) : Matrix (Fin 2 × Fin 2) (Fin 2 × Fin 2) ℂ :=
  Matrix.kroneckerMap (fun x y : ℂ ↦ x * y) (purifier i k)
    ((purifier j k).map (starRingEnd ℂ))

/-- The corrected $p=1/4$ tensor for CPSV16 Example 4.10, lines 897--905, obtained by tracing
the two-valued channel ancilla of `purifier` at each site. This is distinct from the repeated-left
expression printed in the source. -/
def M : MPOTensor 4 4 := fun i j =>
  Matrix.submatrix (∑ k : Fin 2, purifierTerm i j k) pairEquiv pairEquiv

/-- The corrected tensor has the displayed local purification from CPSV16 Example 4.10,
lines 897--905. -/
theorem M_isLPDO : IsLPDO M := by
  refine ⟨2, 2, purifier, pairEquiv, fun i j ↦ ?_⟩
  rfl

/-- Every positive-length periodic operator generated by the corrected tensor is positive
semidefinite. CPSV16 Example 4.10, lines 897--905. -/
theorem M_isMPDO : IsMPDO M := M_isLPDO.isMPDO

/-- The rank-one virtual projector obtained by closing one physical site of the corrected tensor
from CPSV16 Example 4.10, lines 897--905. -/
def traceProjector : Matrix (Fin 4) (Fin 4) ℂ :=
  !![1 / 2, 0, 0, 1 / 2;
     0, 0, 0, 0;
     0, 0, 0, 0;
     1 / 2, 0, 0, 1 / 2]

/-- Closing the physical legs of the corrected tensor gives the Bell-pair rank-one projector.
CPSV16 Example 4.10, lines 897--905. -/
theorem physTraceTransfer_M : physTraceTransfer M = traceProjector := by
  have h0 : (finProdFinEquiv (m := 2) (n := 2)).symm (0 : Fin 4) = (0, 0) := by decide
  have h1 : (finProdFinEquiv (m := 2) (n := 2)).symm (1 : Fin 4) = (0, 1) := by decide
  have h2 : (finProdFinEquiv (m := 2) (n := 2)).symm (2 : Fin 4) = (1, 0) := by decide
  have h3 : (finProdFinEquiv (m := 2) (n := 2)).symm (3 : Fin 4) = (1, 1) := by decide
  have hsqrtTwoSq : ((↑(Real.sqrt 2) : ℂ) ^ 2) = 2 :=
    Complex.ofReal_sqrt_sq 2 (by positivity)
  have hsqrtThreeSq : ((↑(Real.sqrt 3) : ℂ) ^ 2) = 3 :=
    Complex.ofReal_sqrt_sq 3 (by positivity)
  have hsqrtTwoNe : (↑(Real.sqrt 2) : ℂ) ≠ 0 := by
    exact_mod_cast ne_of_gt (Real.sqrt_pos.2 (by norm_num : (0 : ℝ) < 2))
  ext a b
  fin_cases a <;> fin_cases b <;>
    simp [physTraceTransfer, M, purifierTerm, purifier, channelCoeff, correlatedFlip,
      pairEquiv, traceProjector, Matrix.submatrix_apply, Matrix.kroneckerMap_apply,
      h0, h1, h2, h3, Fin.sum_univ_two, Fin.sum_univ_four, map_ofNat] <;>
    norm_num [Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 3),
      Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 2)] <;>
    field_simp <;>
    ring_nf at hsqrtTwoSq hsqrtThreeSq ⊢ <;>
    rw [hsqrtTwoSq, hsqrtThreeSq] <;>
    norm_num

/-- The virtual closure of the corrected CPSV16 Example 4.10 tensor is idempotent; see lines
897--905. -/
theorem traceProjector_sq : traceProjector * traceProjector = traceProjector := by
  ext a b
  fin_cases a <;> fin_cases b <;>
    simp [traceProjector, Matrix.mul_apply, Fin.sum_univ_four] <;> norm_num

/-- The corrected tensor satisfies literal physical-trace idempotence. CPSV16 Example 4.10,
lines 897--905. -/
theorem physTraceTransfer_M_sq :
    physTraceTransfer M * physTraceTransfer M = physTraceTransfer M := by
  rw [physTraceTransfer_M, traceProjector_sq]

/-- The physical-trace transfer of the corrected CPSV16 Example 4.10 tensor is nonzero; see
lines 897--905. -/
theorem physTraceTransfer_M_ne_zero : physTraceTransfer M ≠ 0 := by
  rw [physTraceTransfer_M]
  intro h
  have h00 := congrArg (fun A : Matrix (Fin 4) (Fin 4) ℂ ↦ A 0 0) h
  norm_num [traceProjector] at h00

/-- The corrected tensor satisfies the source-facing physical-trace zero-correlation-length
relation, with literal normalization scale one. CPSV16 Example 4.10, lines 897--905. -/
theorem M_isSourceZCL : IsSourceZCL M :=
  isSourceZCL_of_physTraceTransfer_sq M physTraceTransfer_M_ne_zero physTraceTransfer_M_sq

end MPOTensor.CPSVExample410Operator
