/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.Core.CyclicTrace
import TNLean.MPS.MPDO.Defs

/-!
# Matrix-product tensors for cyclic nearest-neighbor weights

This file gives the elementary closed matrix-product representation of a
translation-invariant cyclic nearest-neighbor weight.  If
\(w(i,j;i',j')\) is a scalar weight on two consecutive ket--bra pairs, the
tensor defined below has bond dimension \(d^2\) and generates
\[
  \prod_{n=0}^{N-1}
    w(\sigma_n,\tau_n;\sigma_{n+1},\tau_{n+1}).
\]
The construction is independent of the chain length.  It is the final
finite-state step needed after a commuting two-site bond has been put in the
sector coordinates of equation `sigmaNK2`.

## Main declarations

* `MPOTensor.cyclicEdgeWeightTensor`
* `MPOTensor.mpo_cyclicEdgeWeightTensor`

## References

* arXiv:1606.00608, Appendix C.2, equation `sigmaNK2`, lines 1581--1589.
-/

open scoped BigOperators Matrix

namespace MPOTensor

variable {d : ℕ}

/-- The matrix-product tensor of a scalar cyclic nearest-neighbor weight.

The virtual index is a ket--bra pair.  At a site with physical pair `(i,j)`,
the incoming virtual pair is forced to be `(i,j)` and the outgoing pair
records the physical indices at the following site.  Closing the virtual
trace therefore leaves exactly one potentially nonzero virtual configuration.

Source: arXiv:1606.00608, Appendix C.2, equation `sigmaNK2`, lines
1581--1589. -/
noncomputable def cyclicEdgeWeightTensor
    (w : Fin d → Fin d → Fin d → Fin d → ℂ) :
    MPOTensor d (d * d) :=
  fun i j a b ↦
    if a = finProdFinEquiv (i, j) then w i j b.divNat b.modNat else 0

@[simp] theorem cyclicEdgeWeightTensor_apply_eq
    (w : Fin d → Fin d → Fin d → Fin d → ℂ)
    (i j i' j' : Fin d) :
    cyclicEdgeWeightTensor w i j (finProdFinEquiv (i, j))
        (finProdFinEquiv (i', j')) =
      w i j i' j' := by
  simp [cyclicEdgeWeightTensor]

/-- A cyclic nearest-neighbor weight is generated by one matrix-product
tensor of bond dimension `d * d`, independently of the chain length.

Source: arXiv:1606.00608, Appendix C.2, equation `sigmaNK2`, lines
1581--1589. -/
theorem mpo_cyclicEdgeWeightTensor
    (w : Fin d → Fin d → Fin d → Fin d → ℂ)
    {N : ℕ} [NeZero N] (sigma tau : Fin N → Fin d) :
    mpo (cyclicEdgeWeightTensor w) N sigma tau =
      ∏ n : Fin N, w (sigma n) (tau n) (sigma (n + 1)) (tau (n + 1)) := by
  rw [mpo_apply, mpoMatrixEntry]
  rw [MPOTensor.evalWord_ofFn]
  have h := MPSTensor.trace_evalWord_eq_sum_cyclic
    (cyclicEdgeWeightTensor w).toMPSTensor
    (fun n ↦ finProdFinEquiv (sigma n, tau n))
  rw [MPSTensor.evalWord_ofFn_eq_prod] at h
  have h' :
      (List.ofFn fun i ↦ cyclicEdgeWeightTensor w (sigma i) (tau i)).prod.trace =
        ∑ g : Fin N → Fin (d * d), ∏ v : Fin N,
          cyclicEdgeWeightTensor w (sigma v) (tau v) (g v) (g (v + 1)) := by
    simpa only [toMPSTensor, MPSTensor.finProdFinEquiv_divNat,
      MPSTensor.finProdFinEquiv_modNat] using h
  rw [h']
  let g0 : Fin N → Fin (d * d) :=
    fun n ↦ finProdFinEquiv (sigma n, tau n)
  rw [Fintype.sum_eq_single g0]
  · apply Finset.prod_congr rfl
    intro n _
    simp [g0, cyclicEdgeWeightTensor_apply_eq]
  · intro x hx
    have hne : ∃ n, x n ≠ g0 n := Function.ne_iff.mp hx
    obtain ⟨n, hn⟩ := hne
    apply Finset.prod_eq_zero (Finset.mem_univ n)
    rw [cyclicEdgeWeightTensor]
    rw [if_neg (by simpa [g0] using hn)]

end MPOTensor
