/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import TNLean.MPS.MPDO.Defs

/-!
# The direct sum of two matrix product operator tensors

The sum of two matrix product operator families is again a matrix product operator family: it
is generated by the tensor whose letters are the block-diagonal sums of the letters of the two
summands, on the bond space `Fin (D₁ + D₂)`. This file defines that direct sum and proves the
additivity of the operator family at every system size, the operator-level counterpart of the
multiplicativity of `MPOTensor.mulTensor`.

## Main definitions

* `MPOTensor.directSum`: the block-diagonal direct sum of two tensors.

## Main results

* `MPOTensor.evalWord_directSum`: word evaluation of the direct sum is the block-diagonal sum of
  the word evaluations.
* `MPOTensor.mpo_directSum`: the operator family of the direct sum is the sum of the operator
  families.
-/

open scoped Matrix

namespace MPOTensor

variable {d D₁ D₂ : ℕ}

/-- The direct sum of two matrix product operator tensors: every letter is the block-diagonal
sum of the two letters, the bond space `Fin (D₁ + D₂)` being identified with `Fin D₁ ⊕ Fin D₂`
by `finSumFinEquiv`. -/
noncomputable def directSum (M : MPOTensor d D₁) (N : MPOTensor d D₂) :
    MPOTensor d (D₁ + D₂) :=
  fun i j => (Matrix.fromBlocks (M i j) 0 0 (N i j)).submatrix finSumFinEquiv.symm
    finSumFinEquiv.symm

/-- Word evaluation of a direct sum is the block-diagonal sum of the word evaluations. -/
theorem evalWord_directSum (M : MPOTensor d D₁) (N : MPOTensor d D₂) :
    ∀ is js : List (Fin d), evalWord (directSum M N) is js =
      (Matrix.fromBlocks (evalWord M is js) 0 0 (evalWord N is js)).submatrix
        finSumFinEquiv.symm finSumFinEquiv.symm
  | [], [] => by
    simp only [evalWord_nil, Matrix.fromBlocks_one, Matrix.submatrix_one_equiv]
  | [], _ :: _ => by
    simp only [evalWord, Matrix.fromBlocks_zero, Matrix.submatrix_zero, Pi.zero_apply]
  | _ :: _, [] => by
    simp only [evalWord, Matrix.fromBlocks_zero, Matrix.submatrix_zero, Pi.zero_apply]
  | i :: is, j :: js => by
    rw [evalWord_cons, evalWord_cons, evalWord_cons, evalWord_directSum M N is js, directSum,
      Matrix.submatrix_mul_equiv, Matrix.fromBlocks_multiply]
    simp only [Matrix.mul_zero, Matrix.zero_mul, add_zero, zero_add]

/-- **Additivity of the operator family**: the operator of the direct sum is the sum of the two
operators, at every system size. -/
theorem mpo_directSum (M : MPOTensor d D₁) (N : MPOTensor d D₂) (L : ℕ) :
    mpo (directSum M N) L = mpo M L + mpo N L := by
  have htr : ∀ (X : Matrix (Fin D₁) (Fin D₁) ℂ) (Y : Matrix (Fin D₂) (Fin D₂) ℂ),
      Matrix.trace ((Matrix.fromBlocks X 0 0 Y).submatrix finSumFinEquiv.symm
        finSumFinEquiv.symm) = Matrix.trace X + Matrix.trace Y := by
    intro X Y
    simp only [Matrix.trace, Matrix.diag, Matrix.submatrix_apply]
    rw [finSumFinEquiv.symm.sum_comp fun j => Matrix.fromBlocks X 0 0 Y j j,
      Fintype.sum_sum_type]
    simp only [Matrix.fromBlocks_apply₁₁, Matrix.fromBlocks_apply₂₂]
  ext σ τ
  simp only [mpo_apply, mpoMatrixEntry, Matrix.add_apply, evalWord_directSum, htr]

end MPOTensor
