/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.MPDO.RFP

/-!
# Fusion-isometry formulation of the MPDO renormalization fixed point

This file records the **fusion-isometry** side of the equivalence stated in
arXiv:1606.00608 §4.5 (Cirac–Pérez-García–Schuch–Verstraete). In the notation
of the paper, a fusion isometry at blocked size `n` is a pair of linear maps
`T`, `S` between the physical space of `n` blocked sites and the corresponding
support algebra of the tensor, whose composites are idempotents on the two
sides. Iterated applications of `T` and `S` reproduce the doubled-tensor
transfer-map dynamics underlying the provisional `MPOTensor.IsRFP` predicate
in `TNLean/MPS/MPDO/RFP.lean`.

The development of the support-algebra API, blocked tensor powers, and
trace-preserving completely positive blocking maps required for the full
statement is deferred. In the present formulation:

* the physical space at blocked size `n` and the support algebra at blocked
  size `n` are both represented by `Matrix (Fin D) (Fin D) ℂ`, a stand-in for
  the genuine objects;
* the idempotence and compatibility conditions in `FusionIsometry` are stated
  as general linear-algebraic hypotheses, weaker than the paper's identities
  on a genuine support algebra;
* `IsRFP_MPDO_via_fusion_scaffold` asserts the existence, at every blocked
  size, of a fusion isometry related to the tensor `M` by the relation
  `FusionIsometry.CompatibleWith`. The latter is currently the trivial
  proposition `True`, so the predicate as a whole is satisfied by every
  `M`. The `_scaffold` suffix marks the predicate to prevent its use in
  nontrivial reasoning until the relation is tightened.

## Main declarations

* `FusionIsometry`: a pair `(T, S)` of linear maps at a fixed blocked size,
  together with an idempotence condition for `S ∘ₗ T` and a pointwise
  identity-on-support condition for `T ∘ₗ S`.
* `FusionIsometry.CompatibleWith`: relation between a fusion isometry and an
  MPO tensor, currently the trivial proposition `True`.
* `IsRFP_MPDO_via_fusion_scaffold`: the provisional RFP predicate built from a
  family of fusion isometries related to the tensor by `CompatibleWith`. The
  `_scaffold` suffix marks that the relation `CompatibleWith` is currently
  `True` and the predicate consequently vacuous.

## References

* [CPGSV17] arXiv:1606.00608, §4.5 and Appendix C.3
  (Cirac–Pérez-García–Schuch–Verstraete, Ann. Phys. 378, 100–149).
-/

open scoped Matrix BigOperators

namespace MPOTensor

variable {d D : ℕ}

/-- The *physical space at blocked size `n`*.

TODO (#611): replace with the exact `(Fin d → ℂ)^{⊗ n}` physical Hilbert
space, once tensor powers are available. The current definition uses
`Matrix (Fin D) (Fin D) ℂ` as a stand-in. -/
abbrev FusionPhysicalSpace (D : ℕ) : Type :=
  Matrix (Fin D) (Fin D) ℂ

/-- The *support algebra at blocked size `n`*.

TODO (#611): replace with the support algebra
`span { ρ^{(n)}(M) | ... } ⊂ M_{D²}`, once the support-algebra API is
available. The current definition uses `Matrix (Fin D) (Fin D) ℂ` as a
stand-in. -/
abbrev FusionSupportAlgebra (D : ℕ) : Type :=
  Matrix (Fin D) (Fin D) ℂ

/-- A **fusion isometry** at blocked size `n` for an MPO tensor of bond
dimension `D`.

In arXiv:1606.00608 §4.5 the corresponding object is a pair of linear maps
`T_n : (ℂ^d)^{⊗ n} → 𝒜_n` and `S_n : 𝒜_n → (ℂ^d)^{⊗ n}` realising a splitting
of the support algebra `𝒜_n` generated by the blocked tensor at blocked size
`n`. Under this typing the algebra composite `T_n ∘ S_n : 𝒜_n → 𝒜_n` is
the identity `id_{𝒜_n}`, while the physical composite
`S_n ∘ T_n : (ℂ^d)^{⊗ n} → (ℂ^d)^{⊗ n}` is the orthogonal projection onto
the image of `𝒜_n` inside the physical space. Equivalently, `S_n` is the
paper's isometry `V_n : 𝒜_n → (ℂ^d)^{⊗ n}` and `T_n` its adjoint `V_n^†`,
with `V_n^† V_n = id_{𝒜_n}` and `V_n V_n^†` the projector onto the image.

The present formulation uses `Matrix (Fin D) (Fin D) ℂ` for both
`FusionSupportAlgebra D` and `FusionPhysicalSpace D`, and weakens the
identities of the paper as follows:

* `support : FusionSupportAlgebra D → Prop` is a unary predicate standing in
  for the subspace cut out by `𝒜_n` inside the matrix algebra;
* `hST` asserts that `S ∘ₗ T` is idempotent on physical space, weaker than
  the paper's identity that `S ∘ T` is the orthogonal projection onto the
  image of `𝒜_n`;
* `hTSM` asserts pointwise that `(T ∘ₗ S) M = M` for every `M` satisfying the
  predicate `support`, weaker than the paper's identity `T ∘ S = id_{𝒜_n}`
  on a genuine subspace.

TODO (#611): tighten `support` to a `Submodule ℂ (Matrix …)` capturing
the span of blocked operator matrix elements, and tighten `hST`/`hTSM` to
the support-algebra identities of the paper. -/
structure FusionIsometry (d D n : ℕ) where
  /-- Forward fusion map `T_n` at blocked size `n`. -/
  T : FusionPhysicalSpace D →ₗ[ℂ] FusionSupportAlgebra D
  /-- Backward fusion map `S_n` at blocked size `n`. -/
  S : FusionSupportAlgebra D →ₗ[ℂ] FusionPhysicalSpace D
  /-- Predicate standing in for membership in the support algebra `𝒜_n`.
  TODO (#611): replace with a `Submodule ℂ (Matrix …)` cutting out the
  span of blocked operator matrix elements. -/
  support : FusionSupportAlgebra D → Prop
  /-- The composite `S ∘ₗ T` is idempotent on the physical space. Weaker
  than the paper's identity stating that `S ∘ T` is the orthogonal
  projection onto the image of `𝒜_n` in the physical space.
  TODO (#611): strengthen to the support-algebra identity of the paper. -/
  hST : S ∘ₗ T ∘ₗ S ∘ₗ T = S ∘ₗ T
  /-- On every element satisfying `support`, the composite `T ∘ₗ S` is the
  identity. Weaker than the paper's identity `T ∘ S = id_{𝒜_n}` on a
  genuine subspace.
  TODO (#611): replace the pointwise quantifier by an identity on a
  `Submodule ℂ (Matrix …)`. -/
  hTSM : ∀ M : FusionSupportAlgebra D, support M → (T ∘ₗ S) M = M

namespace FusionIsometry

variable {d D n : ℕ}

/-- Compatibility relation between a fusion isometry at blocked size `n` and
an MPO tensor `M`. In the final formulation this asserts that `T` and `S`
implement the splitting of the support algebra generated by the blocked
tensor `M^{[n]}`. The present definition is the trivial proposition `True`,
which is satisfied by every pair `(F, M)`.
TODO (#611): replace by the compatibility condition from §4.5 of
arXiv:1606.00608, expressed in terms of the blocked tensor generated by
`M`. -/
def CompatibleWith (_F : FusionIsometry d D n) (_M : MPOTensor d D) : Prop :=
  True

end FusionIsometry

/-- **Provisional fusion-isometry formulation of the MPDO renormalization
fixed point.**

In the paper (arXiv:1606.00608 §4.5) an MPDO tensor `M` is declared to be a
renormalization fixed point when the operators it generates at every blocked
size close under multiplication via a system of fusion isometries
compatible with `M`. The definition below asserts the existence of such a
family using the relation `FusionIsometry.CompatibleWith`.

The `_scaffold` suffix marks that `FusionIsometry.CompatibleWith` is
currently `True`: the predicate is consequently satisfied by every `M`, and
must not be used as a hypothesis or conclusion of any nontrivial result
until the relation is tightened.

TODO (#611): replace `FusionIsometry.CompatibleWith` with the
compatibility condition between `M` and its fusion isometries, add the
inter-level compatibility asking the size-`n+1` isometry to factor through
the size-`n` one, and drop the `_scaffold` suffix once the relation is no
longer trivial. -/
def IsRFP_MPDO_via_fusion_scaffold (M : MPOTensor d D) : Prop :=
  ∀ n : ℕ, ∃ F : FusionIsometry d D n, F.CompatibleWith M

end MPOTensor
