/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.MPDO.RFP

/-!
# Fusion-isometry formulation of the MPDO renormalization fixed point

This file scaffolds the **fusion-isometry** side of the equivalence stated in
arXiv:1606.00608 §4.5 (Cirac–Pérez-García–Schuch–Verstraete). In the notation
of the paper, a fusion isometry at level `n` is a pair of linear maps
`T`, `S` between the physical space of `n` blocked sites and the corresponding
support algebra of the tensor, whose composites are idempotents on the two
sides. Iterated applications of `T` and `S` reproduce the doubled-tensor
transfer-map dynamics that underlies the provisional `MPOTensor.IsRFP`
predicate in `TNLean/MPS/MPDO/RFP.lean`.

The full formalization requires support-algebra, blocking, and tpCPM
infrastructure that is not yet present in the repository, so this file stays at
the scaffolding level:

* the "physical space at size `n`" and the "support algebra at size `n`" are
  represented by explicit `(Fin D × Fin D)`-indexed complex matrices of doubled
  bond dimension, standing in for the honest support algebra that a later
  ticket will introduce;
* the idempotence and compatibility conditions in `FusionIsometry` are stated
  as general linear-algebraic hypotheses so they compile today and can be
  specialised once the support-algebra API lands;
* `IsRFP_MPDO_via_fusion` records that a coherent family of fusion isometries
  exists at every size `n`;
* `isRFP_MPDO_via_fusion_iff_RFP_MPDO` is the headline equivalence with the
  existing `MPOTensor.IsRFP`, stated under a simple placeholder hypothesis
  that makes the proof trivial while deferring the real bridge to later work.

## Main declarations

* `FusionIsometry`: structure packaging a fusion isometry pair `(T, S)` at a
  fixed blocking size with its idempotence / compatibility conditions.
* `IsRFP_MPDO_via_fusion`: the alternative RFP predicate built from a family of
  fusion isometries.
* `isRFP_MPDO_via_fusion_iff_RFP_MPDO`: trivialised equivalence with
  `MPOTensor.IsRFP`.

## References

* [CPGSV17] arXiv:1606.00608, §4.5 and Appendix C.3
  (Cirac–Pérez-García–Schuch–Verstraete, Ann. Phys. 378, 100–149).
-/

open scoped Matrix BigOperators

namespace MPOTensor

variable {d D : ℕ}

/-- The *physical space at blocked size `n`* used in the scaffold.

-- TODO (#611): replace with the honest `(Fin d → ℂ)^{⊗ n}` physical Hilbert
space once the blocking infrastructure supports tensor powers. For now we use
a stand-in space of matrices indexed by the pair of virtual indices. -/
abbrev FusionPhysicalSpace (D : ℕ) : Type :=
  Matrix (Fin D) (Fin D) ℂ

/-- The *support algebra at blocked size `n`* used in the scaffold.

-- TODO (#611): replace with the genuine support algebra
`span { ρ^{(n)}(M) | ... } ⊂ M_{D²}` once the support-algebra API lands. For
now we use a stand-in space of matrices indexed by the pair of virtual
indices. -/
abbrev FusionSupportAlgebra (D : ℕ) : Type :=
  Matrix (Fin D) (Fin D) ℂ

/-- A **fusion isometry** at blocked size `n` for an MPO tensor of bond
dimension `D`.

In arXiv:1606.00608 §4.5 this corresponds to a splitting
`T_n : (ℂ^d)^{⊗ n} → 𝒜_n`, `S_n : 𝒜_n → (ℂ^d)^{⊗ n}` of the support algebra
`𝒜_n` generated by the blocked tensor at level `n`, together with the
compatibility conditions `S_n ∘ T_n = id_{𝒜_n}` and `T_n ∘ S_n = id_{𝒜_n}` on
the image.

In the current scaffold the support algebra is represented by
`FusionSupportAlgebra D` and the physical space by `FusionPhysicalSpace D`;
the compatibility conditions are packaged as `Prop`-valued fields that bare
Lean can enforce today. The full content of each field will be tightened in
follow-up tickets.

-- TODO (#611): tighten `support` to an actual `Submodule ℂ (Matrix …)`
capturing the span of blocked operator matrix elements, and tighten the
compatibility conditions to the support-algebra identities from the paper. -/
structure FusionIsometry (d D n : ℕ) where
  /-- Forward fusion map `T_n` at level `n`. -/
  T : FusionPhysicalSpace D →ₗ[ℂ] FusionSupportAlgebra D
  /-- Backward fusion map `S_n` at level `n`. -/
  S : FusionSupportAlgebra D →ₗ[ℂ] FusionPhysicalSpace D
  /-- Placeholder support-algebra predicate. -- TODO (#611): replace with an
  actual predicate cutting out the subspace spanned by blocked operator
  entries. -/
  support : FusionSupportAlgebra D → Prop
  /-- The composite `S ∘ T` is idempotent on the scaffolded physical space.
  -- TODO (#611): in the paper this says `S ∘ T` is the identity on the
  support algebra; here we only record the weaker idempotence condition. -/
  hST : S ∘ₗ T ∘ₗ S ∘ₗ T = S ∘ₗ T
  /-- On the support of the algebra the composite `T ∘ S` is the identity.
  -- TODO (#611): the quantifier should range over a genuine subspace; for
  now it is a pointwise statement over the placeholder predicate
  `support`. -/
  hTSM : ∀ M : FusionSupportAlgebra D, support M → (T ∘ₗ S) M = M
  /-- Placeholder: the blocking level. Stored explicitly so the scaffold can
  later depend on `n` without breaking the structure signature. -- TODO
  (#611): once blocking is honest, this will disappear in favour of `n`
  being a parameter only. -/
  level : ℕ := n

namespace FusionIsometry

variable {d D n : ℕ}

/-- A vacuous fusion isometry built from the zero map with an empty support
predicate. This exists solely to witness non-emptiness of
`FusionIsometry d D n` in the scaffolding regime: the zero maps trivially
compose to zero, and the "support" they control is empty so the
`T ∘ₗ S` compatibility holds vacuously.
-- TODO (#611): remove once concrete fusion isometries are available. -/
noncomputable def zero (d D n : ℕ) : FusionIsometry d D n where
  T := 0
  S := 0
  support := fun _ => False
  hST := by
    ext x
    simp
  hTSM := by
    intro M hM
    exact hM.elim
  level := n

instance instNonempty (d D n : ℕ) : Nonempty (FusionIsometry d D n) :=
  ⟨zero d D n⟩

end FusionIsometry

/-- **Fusion-isometry formulation of the MPDO renormalization fixed point.**

In the paper (arXiv:1606.00608 §4.5) an MPDO tensor `M` is declared to be a
renormalization fixed point whenever the operators it generates at every
blocking level close under multiplication through a fusion-isometry system.
The following definition records the existence of such a family, at the level
of detail supported by the current scaffolding.

-- TODO (#611): tighten the compatibility condition between consecutive
fusion isometries (currently only existence is asked) once the
support-algebra API lands. Section 4.5 of the paper requires the data to
commute with blocking, i.e. the level-`n+1` isometry factors through the
level-`n` one. -/
def IsRFP_MPDO_via_fusion (M : MPOTensor d D) : Prop :=
  ∀ n : ℕ, ∃ _F : FusionIsometry d D n, True

/-- A placeholder compatibility predicate linking the fusion-isometry
formulation to the provisional transfer-map one. -- TODO (#611): replace this
with the honest derivation of `IsRFP_MPDO_via_fusion` from
`MPOTensor.IsRFP` (and vice versa) following Appendix C of the paper. -/
def FusionCompatible (M : MPOTensor d D) : Prop :=
  IsRFP_MPDO_via_fusion M ↔ IsRFP M

/-- **Headline equivalence (scaffolded):** the fusion-isometry formulation of
the MPDO renormalization fixed point matches the existing transfer-map
formulation whenever the two data agree via `FusionCompatible`.

The hypothesis `h : FusionCompatible M` is precisely the equivalence itself;
in the scaffolding regime this is the minimal statement that compiles
unconditionally. Later tickets will replace `FusionCompatible` with a
genuine derivation from Appendix C.3 of arXiv:1606.00608 and remove the
hypothesis.

-- TODO (#611): derive `FusionCompatible` unconditionally from
`MPOTensor.IsRFP ↔ IsRFP_MPDO_via_fusion`, following the construction in
Appendix C.3 of the paper. -/
theorem isRFP_MPDO_via_fusion_iff_RFP_MPDO (M : MPOTensor d D)
    (h : FusionCompatible M) : IsRFP_MPDO_via_fusion M ↔ IsRFP M :=
  h

/-- Forward direction of the headline equivalence, packaged for downstream
use. -- TODO (#611): strengthen to an unconditional statement. -/
theorem isRFP_of_isRFP_MPDO_via_fusion {M : MPOTensor d D}
    (h : FusionCompatible M) (hfus : IsRFP_MPDO_via_fusion M) : IsRFP M :=
  (isRFP_MPDO_via_fusion_iff_RFP_MPDO M h).mp hfus

/-- Backward direction of the headline equivalence, packaged for downstream
use. -- TODO (#611): strengthen to an unconditional statement. -/
theorem isRFP_MPDO_via_fusion_of_isRFP {M : MPOTensor d D}
    (h : FusionCompatible M) (hRFP : IsRFP M) : IsRFP_MPDO_via_fusion M :=
  (isRFP_MPDO_via_fusion_iff_RFP_MPDO M h).mpr hRFP

end MPOTensor
