/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import Mathlib.Data.Matrix.PEquiv
import TNLean.Channel.PartialTrace
import TNLean.MPS.MPDO.Defs

/-!
# The operator product of MPO tensors

The product of two MPO operator families is again an MPO operator family: it
is generated by the tensor whose letters contract the bra index of the first
factor with the ket index of the second and take the Kronecker product of the
bond spaces,
\[
  (M \cdot N)^{i k} = \sum_{j} M^{i j} \otimes N^{j k}.
\]
This file defines that product tensor and proves the multiplicativity of the
operator family, together with two word-product lemmas used by the fusion
identity of Theorem IV.13(iii): products of isometrically conjugated letters
telescope, and products of block-diagonal Kronecker letters with a fixed
left factor per block accumulate the fixed factor into a matrix power.

In the fusion identity the product tensor is applied to the vertically read
tensors of arXiv:1606.00608, Proposition IV.12: there the physical dimension
is the original bond dimension, and the tensor product of physical spaces in
the isometry statement of Theorem IV.13(iii) (lines 986--993) is the
Kronecker product of the bond spaces in the vertical reading.

## References

* [Cirac--Perez-Garcia--Schuch--Verstraete 2017] arXiv:1606.00608,
  Section 4.5, lines 962--993, and Appendix C.4, lines 2015--2065
-/

open scoped Matrix BigOperators ComplexOrder Kronecker
open Matrix

namespace Matrix

/-- Taking the Kronecker product with a nonempty identity matrix is injective. -/
theorem kronecker_one_injective {m n : Type*} {D : ℕ} (hD : 0 < D) :
    Function.Injective (fun A : Matrix m n ℂ =>
      A ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ)) := by
  intro A B h
  let z : Fin D := ⟨0, hD⟩
  ext x y
  have hEntry := congrArg (fun M => M (x, z) (y, z)) h
  simpa [one_apply, z] using hEntry

/-- Taking the Kronecker product with an identity matrix preserves matrix multiplication. -/
theorem mul_kronecker_one {l m n : Type*} [Fintype m]
    (A : Matrix l m ℂ) (B : Matrix m n ℂ) (D : ℕ) :
    (A * B) ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ) =
      (A ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ)) *
        (B ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ)) := by
  simpa only [one_mul] using mul_kronecker_mul A B
    (1 : Matrix (Fin D) (Fin D) ℂ) (1 : Matrix (Fin D) (Fin D) ℂ)

/-- A matrix product is the identity when its Kronecker amplification by a nonempty identity
matrix is the identity. -/
theorem mul_eq_one_of_kronecker_one {m n : Type*} [DecidableEq m] [Fintype n]
    {D : ℕ} (hD : 0 < D) (F : Matrix m n ℂ) (G : Matrix n m ℂ)
    (h : (F ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ)) *
      (G ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ)) = 1) :
    F * G = 1 := by
  apply kronecker_one_injective hD
  calc
    (F * G) ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ) =
        (F ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ)) *
          (G ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ)) := mul_kronecker_one F G D
    _ = 1 := h
    _ = (1 : Matrix m m ℂ) ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ) :=
      one_kronecker_one.symm

/-- A matrix has orthonormal rows when its Kronecker amplification by a nonempty identity matrix
has orthonormal rows. -/
theorem mul_conjTranspose_eq_one_of_kronecker_one
    {m n : Type*} [Fintype n] [DecidableEq m] {D : ℕ} (hD : 0 < D)
    (F : Matrix m n ℂ)
    (hF : (F ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ)) *
      (F ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ))ᴴ = 1) :
    F * Fᴴ = 1 := by
  apply mul_eq_one_of_kronecker_one hD F Fᴴ
  simpa only [conjTranspose_kronecker, conjTranspose_one] using hF

/-- A matrix has orthonormal columns when its Kronecker amplification by a nonempty identity
matrix has orthonormal columns. -/
theorem conjTranspose_mul_eq_one_of_kronecker_one
    {m n : Type*} [Fintype m] [DecidableEq n] {D : ℕ} (hD : 0 < D)
    (F : Matrix m n ℂ)
    (hF : (F ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ))ᴴ *
      (F ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ)) = 1) :
    Fᴴ * F = 1 := by
  apply mul_eq_one_of_kronecker_one hD Fᴴ F
  rw [conjTranspose_kronecker, conjTranspose_one] at hF
  exact hF

end Matrix

namespace MPOTensor

variable {d D D₁ D₂ D₃ : ℕ}

/-! ### The product tensor -/

/-- The product tensor of two MPO tensors: contract the bra index of the
first factor with the ket index of the second and take the Kronecker product
of the bond spaces, `(M · N)^{i k} = ∑ j, M^{i j} ⊗ N^{j k}`. The bond space
`Fin (D₁ * D₂)` is identified with `Fin D₁ × Fin D₂` via `finProdFinEquiv`.

The operator family of the product tensor is the product of the operator
families (`mpo_mulTensor`).

Source: arXiv:1606.00608, lines 986--993 of
`Papers/1606.00608/MPDO-22-12-17-2.tex` (the tensor generating
$O_L(M_\alpha)O_L(M_\beta)$). -/
noncomputable def mulTensor (M : MPOTensor d D₁) (N : MPOTensor d D₂) :
    MPOTensor d (D₁ * D₂) :=
  fun i k => (∑ j : Fin d, (M i j) ⊗ₖ (N j k)).submatrix
    finProdFinEquiv.symm finProdFinEquiv.symm

@[simp] lemma mulTensor_apply (M : MPOTensor d D₁) (N : MPOTensor d D₂)
    (i k : Fin d) :
    mulTensor M N i k = (∑ j : Fin d, (M i j) ⊗ₖ (N j k)).submatrix
      finProdFinEquiv.symm finProdFinEquiv.symm := rfl

/-- The canonical reassociation equivalence of three bond spaces,
\(((\mathbb C^{D_1}\otimes\mathbb C^{D_2})\otimes\mathbb C^{D_3})\) with
\(\mathbb C^{D_1}\otimes(\mathbb C^{D_2}\otimes\mathbb C^{D_3})\).

Source: arXiv:1606.00608, lines 995--999; arXiv:1511.08090, Section
``Associativity and the pentagon equation'', lines 237--251 of the source. -/
def mulTensorAssocEquiv (D₁ D₂ D₃ : ℕ) :
    Fin (D₁ * D₂ * D₃) ≃ Fin (D₁ * (D₂ * D₃)) :=
  finProdFinEquiv.symm |>.trans
    ((Equiv.prodCongr finProdFinEquiv.symm (Equiv.refl (Fin D₃))).trans
      ((Equiv.prodAssoc (Fin D₁) (Fin D₂) (Fin D₃)).trans
        ((Equiv.prodCongr (Equiv.refl (Fin D₁)) finProdFinEquiv).trans
          finProdFinEquiv)))

/-- The permutation matrix of `mulTensorAssocEquiv`, with rows indexed by the
left-associated bond space and columns by the right-associated bond space.

Source: arXiv:1606.00608, lines 995--999; arXiv:1511.08090, Section
``Associativity and the pentagon equation'', lines 237--251 of the source. -/
noncomputable def mulTensorAssocMatrix (D₁ D₂ D₃ : ℕ) :
    Matrix (Fin (D₁ * D₂ * D₃)) (Fin (D₁ * (D₂ * D₃))) ℂ :=
  (mulTensorAssocEquiv D₁ D₂ D₃).toPEquiv.toMatrix

/-- **Associativity of the MPO tensor product.** A right-associated product
letter, reindexed by the canonical bond reassociation on both indices, is the
corresponding left-associated product letter.

Source: arXiv:1606.00608, lines 995--999; arXiv:1511.08090, Section
``Associativity and the pentagon equation'', lines 237--251 of the source. -/
theorem mulTensor_assoc (M : MPOTensor d D₁) (N : MPOTensor d D₂)
    (P : MPOTensor d D₃) (i l : Fin d) :
    mulTensor (mulTensor M N) P i l =
      (mulTensor M (mulTensor N P) i l).submatrix
        (mulTensorAssocEquiv D₁ D₂ D₃) (mulTensorAssocEquiv D₁ D₂ D₃) := by
  rw [mulTensor_apply, mulTensor_apply]
  ext x y
  rcases finProdFinEquiv.surjective x with ⟨⟨x₁₂, x₃⟩, rfl⟩
  rcases finProdFinEquiv.surjective x₁₂ with ⟨⟨x₁, x₂⟩, rfl⟩
  rcases finProdFinEquiv.surjective y with ⟨⟨y₁₂, y₃⟩, rfl⟩
  rcases finProdFinEquiv.surjective y₁₂ with ⟨⟨y₁, y₂⟩, rfl⟩
  simp only [Matrix.submatrix_apply, Matrix.sum_apply, mulTensor_apply,
    mulTensorAssocEquiv, Equiv.trans_apply, Equiv.prodCongr_apply, Prod.map_apply,
    Equiv.refl_apply, Equiv.prodAssoc_apply]
  simp only [Equiv.symm_apply_apply, kroneckerMap_apply, submatrix_apply,
    Equiv.coe_refl, Prod.map_apply, id_eq]
  simp only [Matrix.sum_apply, Matrix.kronecker_apply]
  simp_rw [Finset.sum_mul, Finset.mul_sum]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun x _ => ?_
  simp only [mul_assoc]

/-- The product-tensor associator intertwines the letters belonging to the two
parenthesizations of a triple product.

Source: arXiv:1606.00608, lines 995--999; arXiv:1511.08090, Section
``Associativity and the pentagon equation'', lines 237--251 of the source. -/
theorem mulTensor_mul_assocMatrix (M : MPOTensor d D₁) (N : MPOTensor d D₂)
    (P : MPOTensor d D₃) (i l : Fin d) :
    mulTensor (mulTensor M N) P i l * mulTensorAssocMatrix D₁ D₂ D₃ =
      mulTensorAssocMatrix D₁ D₂ D₃ *
        mulTensor M (mulTensor N P) i l := by
  rw [mulTensor_assoc, mulTensorAssocMatrix, PEquiv.mul_toMatrix_toPEquiv,
    PEquiv.toMatrix_toPEquiv_mul]
  ext x y
  simp

/-- Word evaluation of the product tensor is a sum over the contracted middle
configurations of Kronecker products of word evaluations.

Source: arXiv:1606.00608, lines 986--993 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
theorem evalWord_mulTensor (M : MPOTensor d D₁) (N : MPOTensor d D₂)
    {L : ℕ} (σ τ : Fin L → Fin d) :
    evalWord (mulTensor M N) (List.ofFn σ) (List.ofFn τ) =
      (∑ ρ : Fin L → Fin d,
        (evalWord M (List.ofFn σ) (List.ofFn ρ)) ⊗ₖ
          (evalWord N (List.ofFn ρ) (List.ofFn τ))).submatrix
        finProdFinEquiv.symm finProdFinEquiv.symm := by
  induction L with
  | zero =>
    simp only [List.ofFn_zero, evalWord_nil, Fintype.sum_unique]
    rw [Matrix.kroneckerMap_one_one (· * ·) (fun _ => zero_mul _)
      (fun _ => mul_zero _) (one_mul 1), Matrix.submatrix_one_equiv]
  | succ n ih =>
    simp only [List.ofFn_succ, evalWord_cons]
    rw [mulTensor_apply]
    have ih_step := ih (σ ∘ Fin.succ) (τ ∘ Fin.succ)
    simp only [Function.comp_def] at ih_step
    rw [ih_step, Matrix.submatrix_mul_equiv _ _ _ finProdFinEquiv.symm _]
    congr 1
    rw [Finset.sum_mul]
    simp_rw [Finset.mul_sum, ← Matrix.mul_kronecker_mul]
    have reindex : ∀ (F : (Fin (n + 1) → Fin d) →
        Matrix (Fin D₁ × Fin D₂) (Fin D₁ × Fin D₂) ℂ),
        ∑ ρ, F ρ = ∑ j : Fin d, ∑ ρ' : Fin n → Fin d, F (Fin.cons j ρ') :=
      fun F => by
        rw [← Fintype.sum_prod_type']
        exact ((Fin.consEquiv (fun _ : Fin (n + 1) => Fin d)).sum_comp F).symm
    symm
    rw [reindex]
    refine Finset.sum_congr rfl fun j _ => Finset.sum_congr rfl fun ρ' _ => ?_
    simp only [Fin.cons_zero, Fin.cons_succ]

/-- **Multiplicativity of the operator family**: the MPO operator of the
product tensor is the product of the MPO operators,
$O_L(M \cdot N) = O_L(M)\,O_L(N)$.

Source: arXiv:1606.00608, lines 962--993 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
theorem mpo_mulTensor (M : MPOTensor d D₁) (N : MPOTensor d D₂) (L : ℕ) :
    mpo (mulTensor M N) L = mpo M L * mpo N L := by
  ext σ τ
  rw [Matrix.mul_apply]
  simp only [mpo_apply, mpoMatrixEntry]
  rw [evalWord_mulTensor, Matrix.trace_submatrix_equiv, Matrix.trace_sum]
  simp_rw [Matrix.trace_kronecker]

/-! ### Word products of conjugated and block-diagonal letters -/

/-- The product of isometrically conjugated matrices telescopes: for a
nonempty word of square matrices and `Uᴴ * U = 1`, the product of the
conjugated letters is the conjugated product.

This carries the isometry invariance of the operator family used in the
fusion identity of arXiv:1606.00608, Theorem IV.13(iii), lines 986--993 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
theorem listProd_conj_of_conjTranspose_mul_self {S : Type*} [Fintype S]
    [DecidableEq S] {b : ℕ} (U : Matrix S (Fin b) ℂ) (hU : Uᴴ * U = 1)
    {n : ℕ} (F : Fin (n + 1) → Matrix (Fin b) (Fin b) ℂ) :
    (List.ofFn fun l => U * F l * Uᴴ).prod = U * (List.ofFn F).prod * Uᴴ := by
  induction n with
  | zero => simp
  | succ m ih =>
    rw [List.ofFn_succ, List.prod_cons, List.ofFn_succ (f := F), List.prod_cons]
    have ih_step := ih (F ∘ Fin.succ)
    simp only [Function.comp_def] at ih_step
    rw [ih_step]
    simp only [Matrix.mul_assoc]
    rw [← Matrix.mul_assoc Uᴴ U, hU, Matrix.one_mul]

/-- The word product of block-diagonal Kronecker letters with a fixed left
factor per block: the fixed factors accumulate into a matrix power,
\[
  \prod_{l} \bigoplus_{\gamma} X_\gamma \otimes G_{\gamma,l}
    = \bigoplus_{\gamma} X_\gamma^{L} \otimes \prod_{l} G_{\gamma,l}.
\]
This carries the word evaluation of the fused tensor
$\oplus_\gamma \chi_{\alpha,\beta,\gamma} \otimes M_\gamma$ of
arXiv:1606.00608, Theorem IV.13(iii), lines 986--993 of
`Papers/1606.00608/MPDO-22-12-17-2.tex`. -/
theorem listProd_blockDiagonal'_kronecker {ι : Type*} [Fintype ι]
    [DecidableEq ι] {m n : ι → ℕ}
    (X : ∀ γ, Matrix (Fin (m γ)) (Fin (m γ)) ℂ)
    {L : ℕ} (G : ∀ γ, Fin L → Matrix (Fin (n γ)) (Fin (n γ)) ℂ) :
    (List.ofFn fun l => Matrix.blockDiagonal' fun γ => (X γ) ⊗ₖ (G γ l)).prod =
      Matrix.blockDiagonal' fun γ => ((X γ) ^ L) ⊗ₖ (List.ofFn (G γ)).prod := by
  induction L with
  | zero =>
    simp only [List.ofFn_zero, List.prod_nil, pow_zero]
    symm
    rw [show (fun γ => (1 : Matrix (Fin (m γ)) (Fin (m γ)) ℂ) ⊗ₖ
        (1 : Matrix (Fin (n γ)) (Fin (n γ)) ℂ)) = fun γ => 1 from ?_]
    · exact Matrix.blockDiagonal'_one
    · funext γ
      exact Matrix.kroneckerMap_one_one (· * ·) (fun _ => zero_mul _)
        (fun _ => mul_zero _) (one_mul 1)
  | succ k ih =>
    rw [List.ofFn_succ, List.prod_cons]
    have ih_step := ih (fun γ => (G γ) ∘ Fin.succ)
    simp only [Function.comp_def] at ih_step
    rw [ih_step, ← Matrix.blockDiagonal'_mul]
    congr 1
    funext γ
    rw [← Matrix.mul_kronecker_mul, ← pow_succ']
    congr 1
    rw [List.ofFn_succ (f := G γ), List.prod_cons]

end MPOTensor
