/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import QICLean.Algebra.FinSum
import TNLean.MPS.MPDO.VerticalCF

/-!
# Restricted per-copy horizontal canonical form

This module records a restricted horizontal decomposition in which every copy
participates separately in one simultaneous trace-separation identity, together
with the corresponding per-copy form of Lemma L from
Cirac--Perez-Garcia--Schuch--Verstraete, arXiv:1606.00608.

The paper instead groups gauge-equivalent copies of each minimal normal
representative before applying Lemma L (Appendix C.3, lines 1835--1858).  Thus
the per-copy trace-separation hypothesis here is strictly stronger than the
source's horizontal canonical form.  The distinction and its obstruction are
recorded in `docs/paper-gaps/cpgsv17_bicf_block_separation.tex`.
-/

open scoped Matrix BigOperators

namespace MPOTensor

variable {d D : ℕ}

/-- Restricted per-copy horizontal data for a family of blocks.

This is the stronger flattened hypothesis used by the older per-copy results
in this file: injective blocks, the left-canonical normalization, nonzero block
weights, and block-injective canonical form (biCF). -/
structure HorizontalCFData {r : ℕ} {dim : Fin r → ℕ}
    (μ : Fin r → ℂ) (A : (k : Fin r) → MPSTensor d (dim k)) : Prop where
  /-- Each block is algebraically injective. -/
  block_injective : ∀ k, Kraus.IsInjective (A k)
  /-- Each block is left-canonical. -/
  left_canonical : ∀ k, ∑ i : Fin d, (A k i)ᴴ * (A k i) = 1
  /-- No block weight vanishes. -/
  weight_ne_zero : ∀ k, μ k ≠ 0
  /-- There is a length `L` such that trace pairing against homogeneous
  length-`L` block products separates every tuple of block matrices.

  **Scope restriction (per-copy finite-word separation):** this field is not
  CPSV16 block-injective canonical form. The paper's definition is a literal
  one-letter simultaneous span, and its Lemma L first groups gauge-equivalent
  copies of one basis-of-normal-tensors representative. Requiring separation
  for the ungrouped family here is stronger and fails on repeated copies; see
  `docs/paper-gaps/cpgsv17_bicf_block_separation.tex`. -/
  finiteWordTraceSeparation : ∃ L : ℕ,
    ∀ (Δ : (k : Fin r) → Matrix (Fin (dim k)) (Fin (dim k)) ℂ),
    (∀ w : Fin L → Fin d,
        (∑ k : Fin r, Matrix.trace (Δ k * Kraus.evalWord (A k) (List.ofFn w))) = 0) →
    ∀ k, Δ k = 0

/-- **Lemma L** (arXiv:1606.00608, appendix): if two operators act identically
on the first site of every MPV generated by a canonical-form tensor, then their
insertions agree blockwise.

This is the precise blockwise statement needed in the proof of Proposition
IV.12. The weighted blockwise difference at the finite-word separation length
pairs to zero against every block word, so it vanishes on each block. -/
theorem blockwise_insert_eq_of_mpv_agree
    {r : ℕ} {dim : Fin r → ℕ} {μ : Fin r → ℂ}
    (A : (k : Fin r) → MPSTensor d (dim k))
    (hCF : HorizontalCFData (d := d) μ A)
    {Y Z : Matrix (Fin d) (Fin d) ℂ}
    (hAct :
      MPSTensor.FirstSiteActionAgree
        (MPSTensor.toTensorFromBlocks (d := d) (μ := μ) A) Y Z) :
    ∀ k, MPSTensor.insertedTensor Y (A k) = MPSTensor.insertedTensor Z (A k) := by
  -- Obtain the finite-word separation length `L`.
  obtain ⟨L, hL⟩ := hCF.finiteWordTraceSeparation
  intro k₀
  funext s
  -- Candidate witness: the blockwise difference weighted by `(μ k)^(L+1)`.
  set Δ : (k : Fin r) → Matrix (Fin (dim k)) (Fin (dim k)) ℂ := fun k =>
    (μ k) ^ (L + 1) • (MPSTensor.insertedTensor Y (A k) s -
      MPSTensor.insertedTensor Z (A k) s)
  -- Pairing with every length-`L` block word vanishes, so separation forces `Δ = 0`.
  have hΔzero : ∀ k, Δ k = 0 := by
    refine hL Δ (fun w => ?_)
    -- Specialize `hAct` at `σ := Fin.cons s w` (which has length `L + 1`).
    have hA := hAct L (Fin.cons s w)
    -- Simplify `σ 0 = s` and `Fin.cons i (σ ∘ Fin.succ) = Fin.cons i w`.
    have hsimp : ∀ i : Fin d,
        (Fin.cons i ((Fin.cons s w : Fin (L + 1) → Fin d) ∘ Fin.succ) :
            Fin (L + 1) → Fin d) = Fin.cons i w :=
      fun i => by simp [Function.comp_def, Fin.cons_succ]
    simp only [Fin.cons_zero, hsimp] at hA
    -- Rewriter: for any `W`, expand the MPV pairing on the LHS of `hA` into a
    -- blockwise trace pairing against `insertedTensor W (A k) s`.
    have htrans : ∀ W : Matrix (Fin d) (Fin d) ℂ,
        ∑ i : Fin d, W s i *
            MPSTensor.mpv
              (MPSTensor.toTensorFromBlocks (d := d) (μ := μ) A)
              (Fin.cons i w : Fin (L + 1) → Fin d) =
          ∑ k : Fin r, Matrix.trace
            ((μ k) ^ (L + 1) • MPSTensor.insertedTensor W (A k) s *
              Kraus.evalWord (A k) (List.ofFn w)) := by
      intro W
      -- Expand the assembled-tensor MPV block-by-block and fold
      -- `mpv (A k) (Fin.cons i w)` into `trace (A k i * Kraus.evalWord (A k) (List.ofFn w))`.
      have hExp : ∀ i : Fin d,
          MPSTensor.mpv
              (MPSTensor.toTensorFromBlocks (d := d) (μ := μ) A)
              (Fin.cons i w : Fin (L + 1) → Fin d) =
            ∑ k : Fin r, (μ k) ^ (L + 1) *
              Matrix.trace (A k i * Kraus.evalWord (A k) (List.ofFn w)) := by
        intro i
        rw [MPSTensor.mpv_toTensorFromBlocks_eq_sum]
        refine Finset.sum_congr rfl fun k _ => ?_
        have hof : List.ofFn (Fin.cons i w : Fin (L + 1) → Fin d)
            = i :: List.ofFn w := by
          simp [List.ofFn_succ, Fin.cons_zero, Fin.cons_succ]
        simp only [smul_eq_mul, MPSTensor.mpv, MPSTensor.coeff, hof,
          Kraus.evalWord_cons]
      simp_rw [hExp, Finset.mul_sum]
      rw [Finset.sum_comm]
      refine Finset.sum_congr rfl fun k _ => ?_
      calc ∑ i : Fin d, W s i *
                ((μ k) ^ (L + 1) *
                  Matrix.trace (A k i * Kraus.evalWord (A k) (List.ofFn w)))
            = (μ k) ^ (L + 1) * ∑ i : Fin d, W s i *
                Matrix.trace (A k i * Kraus.evalWord (A k) (List.ofFn w)) := by
              simpa only [mul_comm, mul_left_comm, mul_assoc] using
                Fintype.sum_mul_mul_eq_mul_sum_mul ((μ k) ^ (L + 1)) (W s)
                  (fun i => Matrix.trace
                    (A k i * Kraus.evalWord (A k) (List.ofFn w)))
        _   = (μ k) ^ (L + 1) * ∑ i : Fin d, Matrix.trace
                ((W s i • A k i) * Kraus.evalWord (A k) (List.ofFn w)) := by
              congr 1
              refine Finset.sum_congr rfl fun i _ => ?_
              rw [Matrix.smul_mul, Matrix.trace_smul, smul_eq_mul]
        _   = (μ k) ^ (L + 1) * Matrix.trace
                (∑ i : Fin d, (W s i • A k i) *
                    Kraus.evalWord (A k) (List.ofFn w)) := by
              rw [Matrix.trace_sum]
        _   = (μ k) ^ (L + 1) * Matrix.trace
                ((∑ i : Fin d, W s i • A k i) *
                  Kraus.evalWord (A k) (List.ofFn w)) := by
              rw [Finset.sum_mul]
        _   = (μ k) ^ (L + 1) * Matrix.trace
                (MPSTensor.insertedTensor W (A k) s *
                  Kraus.evalWord (A k) (List.ofFn w)) := rfl
        _   = Matrix.trace ((μ k) ^ (L + 1) •
                MPSTensor.insertedTensor W (A k) s *
                Kraus.evalWord (A k) (List.ofFn w)) := by
              rw [Matrix.smul_mul, Matrix.trace_smul, smul_eq_mul]
    -- Apply `htrans` to both sides of `hA`.
    rw [htrans Y, htrans Z] at hA
    -- Rewrite each `Δ k * E_k` trace as the difference of the `Y` and `Z` versions.
    have hsubtr : ∀ k : Fin r,
        Matrix.trace (Δ k * Kraus.evalWord (A k) (List.ofFn w)) =
          Matrix.trace ((μ k) ^ (L + 1) •
              MPSTensor.insertedTensor Y (A k) s *
              Kraus.evalWord (A k) (List.ofFn w)) -
            Matrix.trace ((μ k) ^ (L + 1) •
              MPSTensor.insertedTensor Z (A k) s *
              Kraus.evalWord (A k) (List.ofFn w)) := by
      intro k
      change Matrix.trace
          (((μ k) ^ (L + 1) • (MPSTensor.insertedTensor Y (A k) s -
              MPSTensor.insertedTensor Z (A k) s)) *
            Kraus.evalWord (A k) (List.ofFn w)) = _
      rw [smul_sub, sub_mul, Matrix.trace_sub]
    simp_rw [hsubtr]
    rw [Finset.sum_sub_distrib, sub_eq_zero]
    exact hA
  -- From `Δ k₀ = 0` and `(μ k₀)^(L+1) ≠ 0`, conclude the pointwise equality.
  have hk := hΔzero k₀
  have hμne : (μ k₀) ^ (L + 1) ≠ 0 := pow_ne_zero _ (hCF.weight_ne_zero k₀)
  have hdiff : MPSTensor.insertedTensor Y (A k₀) s -
      MPSTensor.insertedTensor Z (A k₀) s = 0 :=
    (smul_eq_zero.mp hk).resolve_left hμne
  exact sub_eq_zero.mp hdiff

end MPOTensor
