/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.FinSum
import TNLean.MPS.MPDO.VerticalCF

/-!
# Restricted per-copy horizontal canonical form

This module records a restricted horizontal decomposition in which every copy
participates separately in one simultaneous trace-separation identity.  It also
contains the corresponding per-copy form of Lemma L and its consequences for
the three contractions occurring in the proof of Proposition 4.13 of
Cirac--Perez-Garcia--Schuch--Verstraete, arXiv:1606.00608.

The paper instead groups gauge-equivalent copies of each minimal normal
representative before applying Lemma L (Appendix C.3, lines 1835--1858).  Thus
the per-copy trace-separation hypothesis here is strictly stronger than the
source's horizontal canonical form.  The distinction and its obstruction are
recorded in `docs/paper-gaps/cpgsv17_bicf_block_separation.tex`.
-/

open scoped Matrix BigOperators

namespace MPOTensor

variable {d D : ℕ}

/-- Restricted per-copy horizontal data for a family of blocks.

This is the stronger flattened hypothesis used by the older per-copy results
in this file: injective blocks, the left-canonical normalization, nonzero block
weights, and block-injective canonical form (biCF). -/
structure HorizontalCFData {r : ℕ} {dim : Fin r → ℕ}
    (μ : Fin r → ℂ) (A : (k : Fin r) → MPSTensor d (dim k)) : Prop where
  /-- Each block is algebraically injective. -/
  block_injective : ∀ k, MPSTensor.IsInjective (A k)
  /-- Each block is left-canonical. -/
  left_canonical : ∀ k, ∑ i : Fin d, (A k i)ᴴ * (A k i) = 1
  /-- No block weight vanishes. -/
  weight_ne_zero : ∀ k, μ k ≠ 0
  /-- **Block-injective canonical form** (biCF): there is a blocking length `L`
  such that the trace pairing against length-`L` block products is faithful
  across all blocks simultaneously. Concretely, if a tuple of block matrices
  `Δ k : Matrix (Fin (dim k)) (Fin (dim k)) ℂ` pairs to zero against every
  length-`L` block-diagonal product, then each `Δ k` vanishes individually.

  This is the block-decomposed surrogate for the block-injectivity proposition
  in Cirac--Perez-Garcia--Schuch--Verstraete, arXiv:1606.00608,
  lines 340--345: after blocking at most `3 D^5` spins,
  where `D` denotes the bond dimension in the paper (in this block-decomposed
  setting one may take `D` to be a global bound such as `⨆ k, dim k`).

  *Current repository status.* `TNLean/MPS/MPDO/BiCFDerivation.lean` now provides
  several exact routes to this field: from a full finite-length tuple-span
  witness (`WordTupleSpanTop`), from the abstract selector data
  (`PropBlockInjective`), and from the more concrete linear-independence criterion
  `wordEntryFamily`. What is still open is to derive one of those finite-length
  witnesses from the remaining canonical-form/BNT data alone, i.e. the actual
  block-injectivity proposition in Cirac--Perez-Garcia--Schuch--Verstraete,
  arXiv:1606.00608, lines 340--345.

  **Scope restriction (per-block separation):** the paper's Lemma L groups
  gauge-equivalent copies of one basis-of-normal-tensors representative before
  the trace-separation step; demanding `biCF` per block as here is strictly
  stronger and fails on such copies (`duplicateScalarBlocks_not_hasBiCF`,
  `docs/paper-gaps/cpgsv17_bicf_block_separation.tex`). -/
  biCF : ∃ L : ℕ, ∀ (Δ : (k : Fin r) → Matrix (Fin (dim k)) (Fin (dim k)) ℂ),
    (∀ w : Fin L → Fin d,
        (∑ k : Fin r, Matrix.trace (Δ k * MPSTensor.evalWord (A k) (List.ofFn w))) = 0) →
    ∀ k, Δ k = 0

/-- A per-copy horizontal decomposition of an MPO tensor.

This predicate retains the older flattened formulation in which every copy is
required to participate separately in one simultaneous trace-separation
identity.  It is stronger than the horizontal canonical form of
arXiv:1606.00608, equations `eq:II_ABasicTensors` and `decBSV`, lines 283--301,
when several copies have the same basis-of-normal-tensors representative.

**Scope restriction (per-copy separation):** the source groups the copies over
each minimal representative before applying Lemma L.  See
`docs/paper-gaps/cpgsv17_bicf_block_separation.tex`. -/
def IsPerCopyHorizontalCF (M : MPOTensor d D) : Prop :=
  ∃ (r : ℕ) (dim : Fin r → ℕ) (μ : Fin r → ℂ)
    (A : (k : Fin r) → MPSTensor (d * d) (dim k)),
    HorizontalCFData (d := d * d) μ A ∧
      MPSTensor.SameMPV₂Pos M.toMPSTensor
        (MPSTensor.toTensorFromBlocks (d := d * d) (μ := μ) A)

/-- **Lemma L** (arXiv:1606.00608, appendix): if two operators act identically
on the first site of every MPV generated by a canonical-form tensor, then their
insertions agree blockwise.

This is the precise blockwise statement needed in the proof of Proposition
IV.12. The proof consumes the `biCF` field of `HorizontalCFData` directly:
the weighted blockwise difference at the biCF blocking length pairs to zero
against every block word, so `biCF` forces it to vanish for each block.

**Scope restriction (per-block separation):** the source's Lemma L (lines
1835--1858) groups gauge-equivalent copies of one basis-of-normal-tensors
representative before separating, disposing of the weight sum by the
nonvanishing power-sum step of Lemma app_simple. The `biCF` hypothesis instead
demands trace separation per block, a strictly stronger condition that fails
on such copies (`duplicateScalarBlocks_not_hasBiCF`,
`docs/paper-gaps/cpgsv17_bicf_block_separation.tex`). -/
theorem blockwise_insert_eq_of_mpv_agree
    {r : ℕ} {dim : Fin r → ℕ} {μ : Fin r → ℂ}
    (A : (k : Fin r) → MPSTensor d (dim k))
    (hCF : HorizontalCFData (d := d) μ A)
    {Y Z : Matrix (Fin d) (Fin d) ℂ}
    (hAct :
      MPSTensor.FirstSiteActionAgree
        (MPSTensor.toTensorFromBlocks (d := d) (μ := μ) A) Y Z) :
    ∀ k, MPSTensor.insertedTensor Y (A k) = MPSTensor.insertedTensor Z (A k) := by
  -- Obtain the biCF blocking length `L`.
  obtain ⟨L, hL⟩ := hCF.biCF
  intro k₀
  funext s
  -- Candidate witness for biCF: the blockwise difference weighted by `(μ k)^(L+1)`.
  set Δ : (k : Fin r) → Matrix (Fin (dim k)) (Fin (dim k)) ℂ := fun k =>
    (μ k) ^ (L + 1) • (MPSTensor.insertedTensor Y (A k) s -
      MPSTensor.insertedTensor Z (A k) s)
  -- Show that `Δ` pairs to zero against every length-`L` block word, so biCF forces `Δ = 0`.
  have hΔzero : ∀ k, Δ k = 0 := by
    refine hL Δ (fun w => ?_)
    -- Specialize `hAct` at `σ := Fin.cons s w` (which has length `L + 1`).
    have hA := hAct L (Fin.cons s w)
    -- Simplify `σ 0 = s` and `Fin.cons i (σ ∘ Fin.succ) = Fin.cons i w`.
    have hsimp : ∀ i : Fin d,
        (Fin.cons i ((Fin.cons s w : Fin (L + 1) → Fin d) ∘ Fin.succ) :
            Fin (L + 1) → Fin d) = Fin.cons i w :=
      fun i => by simp [Function.comp_def, Fin.cons_succ]
    simp only [Fin.cons_zero, hsimp] at hA
    -- Rewriter: for any `W`, expand the MPV pairing on the LHS of `hA` into a
    -- blockwise trace pairing against `insertedTensor W (A k) s`.
    have htrans : ∀ W : Matrix (Fin d) (Fin d) ℂ,
        ∑ i : Fin d, W s i *
            MPSTensor.mpv
              (MPSTensor.toTensorFromBlocks (d := d) (μ := μ) A)
              (Fin.cons i w : Fin (L + 1) → Fin d) =
          ∑ k : Fin r, Matrix.trace
            ((μ k) ^ (L + 1) • MPSTensor.insertedTensor W (A k) s *
              MPSTensor.evalWord (A k) (List.ofFn w)) := by
      intro W
      -- Expand the assembled-tensor MPV block-by-block and fold
      -- `mpv (A k) (Fin.cons i w)` into `trace (A k i * evalWord (A k) (List.ofFn w))`.
      have hExp : ∀ i : Fin d,
          MPSTensor.mpv
              (MPSTensor.toTensorFromBlocks (d := d) (μ := μ) A)
              (Fin.cons i w : Fin (L + 1) → Fin d) =
            ∑ k : Fin r, (μ k) ^ (L + 1) *
              Matrix.trace (A k i * MPSTensor.evalWord (A k) (List.ofFn w)) := by
        intro i
        rw [MPSTensor.mpv_toTensorFromBlocks_eq_sum]
        refine Finset.sum_congr rfl fun k _ => ?_
        have hof : List.ofFn (Fin.cons i w : Fin (L + 1) → Fin d)
            = i :: List.ofFn w := by
          simp [List.ofFn_succ, Fin.cons_zero, Fin.cons_succ]
        simp only [smul_eq_mul, MPSTensor.mpv, MPSTensor.coeff, hof,
          MPSTensor.evalWord_cons]
      simp_rw [hExp, Finset.mul_sum]
      rw [Finset.sum_comm]
      refine Finset.sum_congr rfl fun k _ => ?_
      calc ∑ i : Fin d, W s i *
                ((μ k) ^ (L + 1) *
                  Matrix.trace (A k i * MPSTensor.evalWord (A k) (List.ofFn w)))
            = (μ k) ^ (L + 1) * ∑ i : Fin d, W s i *
                Matrix.trace (A k i * MPSTensor.evalWord (A k) (List.ofFn w)) := by
              simpa only [mul_comm, mul_left_comm, mul_assoc] using
                Fintype.sum_mul_mul_eq_mul_sum_mul ((μ k) ^ (L + 1)) (W s)
                  (fun i => Matrix.trace
                    (A k i * MPSTensor.evalWord (A k) (List.ofFn w)))
        _   = (μ k) ^ (L + 1) * ∑ i : Fin d, Matrix.trace
                ((W s i • A k i) * MPSTensor.evalWord (A k) (List.ofFn w)) := by
              congr 1
              refine Finset.sum_congr rfl fun i _ => ?_
              rw [Matrix.smul_mul, Matrix.trace_smul, smul_eq_mul]
        _   = (μ k) ^ (L + 1) * Matrix.trace
                (∑ i : Fin d, (W s i • A k i) *
                    MPSTensor.evalWord (A k) (List.ofFn w)) := by
              rw [Matrix.trace_sum]
        _   = (μ k) ^ (L + 1) * Matrix.trace
                ((∑ i : Fin d, W s i • A k i) *
                  MPSTensor.evalWord (A k) (List.ofFn w)) := by
              rw [Finset.sum_mul]
        _   = (μ k) ^ (L + 1) * Matrix.trace
                (MPSTensor.insertedTensor W (A k) s *
                  MPSTensor.evalWord (A k) (List.ofFn w)) := rfl
        _   = Matrix.trace ((μ k) ^ (L + 1) •
                MPSTensor.insertedTensor W (A k) s *
                MPSTensor.evalWord (A k) (List.ofFn w)) := by
              rw [Matrix.smul_mul, Matrix.trace_smul, smul_eq_mul]
    -- Apply `htrans` to both sides of `hA`.
    rw [htrans Y, htrans Z] at hA
    -- Rewrite each `Δ k * E_k` trace as the difference of the `Y` and `Z` versions.
    have hsubtr : ∀ k : Fin r,
        Matrix.trace (Δ k * MPSTensor.evalWord (A k) (List.ofFn w)) =
          Matrix.trace ((μ k) ^ (L + 1) •
              MPSTensor.insertedTensor Y (A k) s *
              MPSTensor.evalWord (A k) (List.ofFn w)) -
            Matrix.trace ((μ k) ^ (L + 1) •
              MPSTensor.insertedTensor Z (A k) s *
              MPSTensor.evalWord (A k) (List.ofFn w)) := by
      intro k
      change Matrix.trace
          (((μ k) ^ (L + 1) • (MPSTensor.insertedTensor Y (A k) s -
              MPSTensor.insertedTensor Z (A k) s)) *
            MPSTensor.evalWord (A k) (List.ofFn w)) = _
      rw [smul_sub, sub_mul, Matrix.trace_sub]
    simp_rw [hsubtr]
    rw [Finset.sum_sub_distrib, sub_eq_zero]
    exact hA
  -- From `Δ k₀ = 0` and `(μ k₀)^(L+1) ≠ 0`, conclude the pointwise equality.
  have hk := hΔzero k₀
  have hμne : (μ k₀) ^ (L + 1) ≠ 0 := pow_ne_zero _ (hCF.weight_ne_zero k₀)
  have hdiff : MPSTensor.insertedTensor Y (A k₀) s -
      MPSTensor.insertedTensor Z (A k₀) s = 0 :=
    (smul_eq_zero.mp hk).resolve_left hμne
  exact sub_eq_zero.mp hdiff

/-- **One-sided invariance becomes reduction, block by block.**

Let `Yleft`, `Ycorner`, and `Yright` encode respectively the first-site
coefficients of $PH^{(N)}$, $PH^{(N)}P$, and $H^{(N)}P$.  If the
one-sided invariance gives agreement of the first two actions, while positivity
gives agreement of the first and third actions, then Lemma L shows that the
opposite corner vanishes on every canonical-form block: the `Yright` insertion
equals the `Ycorner` insertion.

This is the tensor-block conclusion of the displayed equation in the proof
of Proposition 4.13 of arXiv:1606.00608, lines 1873--1887.  The two
hypotheses are precisely the coefficient-level equalities displayed in that
equation; they do not posit a vertical canonical decomposition.

**Scope restriction (per-block separation):** inherited from
`blockwise_insert_eq_of_mpv_agree` (`docs/paper-gaps/cpgsv17_bicf_block_separation.tex`). -/
theorem blockwise_opposite_insert_eq_of_mpv_agree
    {r : ℕ} {dim : Fin r → ℕ} {μ : Fin r → ℂ}
    (A : (k : Fin r) → MPSTensor d (dim k))
    (hCF : HorizontalCFData (d := d) μ A)
    {Yleft Ycorner Yright : Matrix (Fin d) (Fin d) ℂ}
    (hInv : MPSTensor.FirstSiteActionAgree
      (MPSTensor.toTensorFromBlocks (d := d) (μ := μ) A) Yleft Ycorner)
    (hPos : MPSTensor.FirstSiteActionAgree
      (MPSTensor.toTensorFromBlocks (d := d) (μ := μ) A) Yleft Yright) :
    ∀ k, MPSTensor.insertedTensor Yright (A k) =
      MPSTensor.insertedTensor Ycorner (A k) := by
  intro k
  calc
    MPSTensor.insertedTensor Yright (A k) =
        MPSTensor.insertedTensor Yleft (A k) :=
      (blockwise_insert_eq_of_mpv_agree A hCF hPos k).symm
    _ = MPSTensor.insertedTensor Ycorner (A k) :=
      blockwise_insert_eq_of_mpv_agree A hCF hInv k

/-- **The three contractions in Proposition 4.13, with their indices fixed.**

Suppose the horizontal doubled-index tensor of `M` has the displayed
block-diagonal canonical form.  The entrywise identities
$PH^{(N)} = PH^{(N)}P$ and $PH^{(N)} = H^{(N)}P$ then identify
the three abstract first-site matrices in Lemma L with `ketLeftAction P`,
`ketLeftBraRightAction P`, and `braRightAction P`.  Consequently the last two
insertions agree on every canonical-form block.

This formalizes the doubled-index rotation implicit in the displayed
equation of the proof of Proposition 4.13 of arXiv:1606.00608,
lines 1873--1887.  It does not prove that a one-sided invariant projection
for the vertically viewed tensor supplies the first entrywise identity.  The
corresponding invariant-projection conclusion is proved by
`IsHorizontalCF.hasInvariantProjectorClosure_verticalTensor`; the complete
horizontal-to-vertical implication is
`MPOTensor.verticalCF_of_horizontalCF`.

**Scope restriction (per-block separation):** inherited from
`blockwise_insert_eq_of_mpv_agree` via `blockwise_opposite_insert_eq_of_mpv_agree`
(`docs/paper-gaps/cpgsv17_bicf_block_separation.tex`). -/
theorem blockwise_opposite_insert_eq_of_rotated_mpo_entries
    {r : ℕ} {dim : Fin r → ℕ} {μ : Fin r → ℂ}
    (M : MPOTensor d D) (A : (k : Fin r) → MPSTensor (d * d) (dim k))
    (hCF : HorizontalCFData (d := d * d) μ A)
    (hM : MPSTensor.SameMPV₂Pos M.toMPSTensor
      (MPSTensor.toTensorFromBlocks (d := d * d) (μ := μ) A))
    (P : Matrix (Fin d) (Fin d) ℂ)
    (hInv : ∀ (N : ℕ) (ρ : Fin (N + 1) → Fin (d * d)),
      (∑ i : Fin d, P (ρ 0).divNat i *
        mpo M (N + 1) (Fin.cons i (fun n => (ρ (Fin.succ n)).divNat))
          (Fin.cons (ρ 0).modNat (fun n => (ρ (Fin.succ n)).modNat)) =
      ∑ i : Fin d, ∑ j : Fin d, P (ρ 0).divNat i *
        mpo M (N + 1) (Fin.cons i (fun n => (ρ (Fin.succ n)).divNat))
          (Fin.cons j (fun n => (ρ (Fin.succ n)).modNat)) * P j (ρ 0).modNat))
    (hComm : ∀ (N : ℕ) (ρ : Fin (N + 1) → Fin (d * d)),
      (∑ i : Fin d, P (ρ 0).divNat i *
        mpo M (N + 1) (Fin.cons i (fun n => (ρ (Fin.succ n)).divNat))
          (Fin.cons (ρ 0).modNat (fun n => (ρ (Fin.succ n)).modNat)) =
      ∑ j : Fin d,
        mpo M (N + 1)
          (Fin.cons (ρ 0).divNat (fun n => (ρ (Fin.succ n)).divNat))
          (Fin.cons j (fun n => (ρ (Fin.succ n)).modNat)) * P j (ρ 0).modNat)) :
    ∀ k, MPSTensor.insertedTensor (MPSTensor.braRightAction P) (A k) =
      MPSTensor.insertedTensor (MPSTensor.ketLeftBraRightAction P) (A k) := by
  apply blockwise_opposite_insert_eq_of_mpv_agree A hCF
  · exact MPSTensor.FirstSiteActionAgree.of_sameMPVPos hM
      (MPSTensor.firstSiteActionAgree_ketLeft_ketLeftBraRight M P hInv)
  · exact MPSTensor.FirstSiteActionAgree.of_sameMPVPos hM
      (MPSTensor.firstSiteActionAgree_ketLeft_braRight M P hComm)

end MPOTensor
