/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import Mathlib.LinearAlgebra.Matrix.Irreducible.Defs
import TNLean.Algebra.HermitianHelpers
import TNLean.Algebra.PerronFrobenius.PrimitiveAperiodic
import TNLean.MPS.MPDO.PhysicalSectorDirectedCut
import TNLean.MPS.MPDO.PhysicalSectorVirtualSpanning

/-!
# Active-sector trace matrices

This file defines the real trace matrix of a physical-sector factorization on
the nonzero-weight sector subtype. Positive semidefiniteness identifies its
positive entries with the nonzero neighboring operators.

The restriction concerns only the auxiliary trace matrix. The physical-sector
factorization continues to contain every summand of the middle physical
Hilbert space, including zero-weight summands.

Source: arXiv:1606.00608, Appendix C.2, Lemma C.4 (`propSN`), lines
1406--1471.
-/

open scoped ComplexOrder

namespace MPOTensor.PhysicalSectorFactorization

variable {d D : ℕ} {K : MPOTensor d D}

/-- The sectors carrying nonzero weight in a real sector-weight family. -/
abbrev ActiveSector (F : PhysicalSectorFactorization K)
    (p : Fin F.sectorCount → ℝ) :=
  {k : Fin F.sectorCount // p k ≠ 0}

/-- The entries of the virtual matrices belonging to active sectors. -/
abbrev ActiveSectorEntryIndex (F : PhysicalSectorFactorization K)
    (p : Fin F.sectorCount → ℝ) :=
  Σ k : F.ActiveSector p, F.SectorIndex k × F.SectorIndex k

/-- The one-site matrices belonging to nonzero-weight sectors. -/
noncomputable def activeSectorOneSiteMatrixFamily (F : PhysicalSectorFactorization K)
    (p : Fin F.sectorCount → ℝ) (q : F.ActiveSectorEntryIndex p) :
    Matrix (Fin D) (Fin D) ℂ :=
  F.oneSiteSectorMatrix q.1 q.2.1 q.2.2

/-- The one-site matrix of a sector entry is its sector virtual matrix.

This identifies the matrix family used in the directed-cut argument with the
matrix family used in the trace-pairing argument.

Source: arXiv:1606.00608, Appendix C.2, equations `AppUkU=rl` and `formK`,
lines 1383--1387 and 1434--1439. -/
@[simp] theorem oneSiteSectorMatrix_eq_sectorVirtualMatrix
    (F : PhysicalSectorFactorization K) (k : Fin F.sectorCount)
    (x y : F.SectorIndex k) :
    F.oneSiteSectorMatrix k x y = F.sectorVirtualMatrix k x y := by
  ext beta alpha
  simp [oneSiteSectorMatrix, sectorVirtualMatrix]

/-- The ambient sector indices represented by a set of nonzero-weight
sectors. -/
def activeSectorSet (F : PhysicalSectorFactorization K)
    (p : Fin F.sectorCount → ℝ) (S : Set (F.ActiveSector p)) :
    Set (Fin F.sectorCount) :=
  Subtype.val '' S

/-- The one-site matrix space generated by a set of nonzero-weight sectors.

This is the one-site sector space from the directed-cut argument, restricted
to the image of the given set of active sectors. -/
noncomputable abbrev activeSectorOneSiteSpace
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (S : Set (F.ActiveSector p)) :
    Submodule ℂ (Matrix (Fin D) (Fin D) ℂ) :=
  F.oneSiteSectorSpace (F.activeSectorSet p S)

/-- If inactive sectors have zero virtual matrices, spanning by all sector
virtual matrices reduces to spanning by the active sectors. -/
theorem activeSectorOneSiteMatrixFamily_span_eq_top
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (hspan : Submodule.span ℂ (Set.range F.sectorVirtualMatrixFamily) = ⊤)
    (hinactive : ∀ (k : Fin F.sectorCount), p k = 0 →
      ∀ x y : F.SectorIndex k, F.sectorVirtualMatrix k x y = 0) :
    Submodule.span ℂ (Set.range (F.activeSectorOneSiteMatrixFamily p)) = ⊤ := by
  apply top_unique
  rw [← hspan]
  apply Submodule.span_le.2
  rintro A ⟨q, rfl⟩
  change F.sectorVirtualMatrix q.1 q.2.1 q.2.2 ∈ _
  by_cases hq : p q.1 ≠ 0
  · apply Submodule.subset_span
    refine ⟨⟨⟨q.1, hq⟩, q.2⟩, ?_⟩
    change F.oneSiteSectorMatrix q.1 q.2.1 q.2.2 =
      F.sectorVirtualMatrix q.1 q.2.1 q.2.2
    exact F.oneSiteSectorMatrix_eq_sectorVirtualMatrix q.1 q.2.1 q.2.2
  · rw [hinactive q.1 (not_ne_iff.mp hq) q.2.1 q.2.2]
    exact Submodule.zero_mem _

/-- The virtual matrix spaces generated by a set of active sectors and its
complement together contain the span of all active-sector virtual matrices. -/
theorem activeSectorOneSiteSpace_sup_compl_eq_top
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (hspan : Submodule.span ℂ
      (Set.range (F.activeSectorOneSiteMatrixFamily p)) = ⊤)
    (S : Set (F.ActiveSector p)) :
    F.activeSectorOneSiteSpace p S ⊔
      F.activeSectorOneSiteSpace p Sᶜ = ⊤ := by
  apply top_unique
  rw [← hspan]
  apply Submodule.span_le.2
  rintro A ⟨q, rfl⟩
  by_cases hq : q.1 ∈ S
  · apply (le_sup_left : F.activeSectorOneSiteSpace p S ≤ _)
    apply Submodule.subset_span
    exact ⟨q.1, ⟨q.1, hq, rfl⟩, q.2.1, q.2.2, rfl⟩
  · apply (le_sup_right : F.activeSectorOneSiteSpace p Sᶜ ≤ _)
    apply Submodule.subset_span
    exact ⟨q.1, ⟨q.1, hq, rfl⟩, q.2.1, q.2.2, rfl⟩

/-- A set of active sectors containing a nonzero sector virtual matrix
generates a nonzero virtual matrix space. -/
theorem activeSectorOneSiteSpace_ne_bot
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (S : Set (F.ActiveSector p)) (k : F.ActiveSector p) (hk : k ∈ S)
    {x y : F.SectorIndex k} (hxy : F.sectorVirtualMatrix k x y ≠ 0) :
    F.activeSectorOneSiteSpace p S ≠ ⊥ := by
  intro hbot
  have hmem : F.sectorVirtualMatrix k x y ∈
      F.activeSectorOneSiteSpace p S := by
    apply Submodule.subset_span
    exact ⟨k, ⟨k, hk, rfl⟩, x, y,
      (F.oneSiteSectorMatrix_eq_sectorVirtualMatrix k x y).symm⟩
  rw [hbot, Submodule.mem_bot] at hmem
  exact hxy hmem

/-- If no neighboring edge runs from one set of active sectors to another,
then every product of their generated virtual matrix spaces vanishes. -/
theorem mul_eq_zero_of_mem_activeSectorOneSiteSpace
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (S T : Set (F.ActiveSector p))
    (hcut : ∀ k ∈ S, ∀ h ∈ T, F.neighboringOperator k h = 0)
    {A B : Matrix (Fin D) (Fin D) ℂ}
    (hA : A ∈ F.activeSectorOneSiteSpace p S)
    (hB : B ∈ F.activeSectorOneSiteSpace p T) :
    A * B = 0 := by
  apply F.oneSiteSectorSpace_mul_eq_zero
    (F.activeSectorSet p S) (F.activeSectorSet p T) _ hA hB
  rintro _ ⟨k, hk, rfl⟩ _ ⟨h, hh, rfl⟩
  exact hcut k hk h hh

/-- If active-sector virtual matrices span the full virtual matrix algebra and
each active sector contains a nonzero virtual matrix, then every active sector
is reachable from every other through nonzero neighboring operators.

The proof is the one-sided directed-cut argument of the source. If the sectors
reachable from `k` formed a proper set `S`, then the virtual matrix spaces
generated by `S` and its complement would be nonzero, would span the full
matrix algebra, and would have zero products from the first space to the
second. This contradicts the one-sided product obstruction.

Source: arXiv:1606.00608, Appendix C.2, lines 1452--1470. -/
theorem activeSector_reflTransGen_neighboringOperator_ne_zero
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (hspan : Submodule.span ℂ
      (Set.range (F.activeSectorOneSiteMatrixFamily p)) = ⊤)
    (hnonzero : ∀ k : F.ActiveSector p,
      ∃ x y : F.SectorIndex k, F.sectorVirtualMatrix k x y ≠ 0)
    (k h : F.ActiveSector p) :
    Relation.ReflTransGen
      (fun a b : F.ActiveSector p ↦ F.neighboringOperator a b ≠ 0) k h := by
  by_contra hreach
  let S : Set (F.ActiveSector p) := fun j ↦
    Relation.ReflTransGen
      (fun a b : F.ActiveSector p ↦ F.neighboringOperator a b ≠ 0) k j
  have hkS : k ∈ S := Relation.ReflTransGen.refl
  have hhS : h ∈ Sᶜ := hreach
  have hcut : ∀ a ∈ S, ∀ b ∈ Sᶜ, F.neighboringOperator a b = 0 := by
    intro a ha b hb
    by_contra hab
    exact hb (ha.tail hab)
  obtain ⟨kx, ky, hkxy⟩ := hnonzero k
  obtain ⟨hx, hy, hhxy⟩ := hnonzero h
  have hS : F.activeSectorOneSiteSpace p S ≠ ⊥ :=
    F.activeSectorOneSiteSpace_ne_bot p S k hkS hkxy
  have hSc : F.activeSectorOneSiteSpace p Sᶜ ≠ ⊥ :=
    F.activeSectorOneSiteSpace_ne_bot p Sᶜ h hhS hhxy
  have hmul : ∀ A ∈ F.activeSectorOneSiteSpace p S,
      ∀ B ∈ F.activeSectorOneSiteSpace p Sᶜ, A * B = 0 := by
    intro A hA B hB
    exact F.mul_eq_zero_of_mem_activeSectorOneSiteSpace
      p S Sᶜ hcut hA hB
  exact Matrix.submodule_sup_ne_top_of_mul_eq_zero
    (F.activeSectorOneSiteSpace p S)
    (F.activeSectorOneSiteSpace p Sᶜ) hS hSc hmul
    (F.activeSectorOneSiteSpace_sup_compl_eq_top p hspan S)

/-- Every active sector has an outgoing nonzero neighboring operator under
active-sector spanning and sector nonvanishing. -/
theorem exists_active_neighboringOperator_ne_zero
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (hspan : Submodule.span ℂ
      (Set.range (F.activeSectorOneSiteMatrixFamily p)) = ⊤)
    (hnonzero : ∀ k : F.ActiveSector p,
      ∃ x y : F.SectorIndex k, F.sectorVirtualMatrix k x y ≠ 0)
    (k : F.ActiveSector p) :
    ∃ h : F.ActiveSector p, F.neighboringOperator k h ≠ 0 := by
  by_contra hall
  push Not at hall
  obtain ⟨x, y, hxy⟩ := hnonzero k
  let A := F.sectorVirtualMatrix k x y
  have hmul : ∀ B ∈ Submodule.span ℂ
      (Set.range (F.activeSectorOneSiteMatrixFamily p)), A * B = 0 := by
    intro B hB
    induction hB using Submodule.span_induction with
    | mem B hB =>
        obtain ⟨q, rfl⟩ := hB
        simpa [A, activeSectorOneSiteMatrixFamily] using
          F.sectorVirtualMatrix_mul_eq_zero_of_neighboringOperator_eq_zero
            k q.1 (hall q.1) x y q.2.1 q.2.2
    | zero => simp
    | add B C _ _ hB hC => rw [mul_add, hB, hC, add_zero]
    | smul c B _ hB => rw [Algebra.mul_smul_comm, hB, smul_zero]
  have hone : (1 : Matrix (Fin D) (Fin D) ℂ) ∈
      Submodule.span ℂ (Set.range (F.activeSectorOneSiteMatrixFamily p)) := by
    rw [hspan]
    exact Submodule.mem_top
  have := hmul 1 hone
  rw [mul_one] at this
  exact hxy this

/-- The real trace matrix of the neighboring operators, restricted to the
nonzero-weight sector subtype.

**Scope restriction (inactive sectors):** the full physical sector decomposition is
unchanged. Only this auxiliary matrix is restricted, because every row and
column incident to a zero-weight sector vanishes after the source-faithful
reparameterization. See
`docs/paper-gaps/cpgsv17_mpdo_sal_zcl_eta_local_structure.tex`.

Source: arXiv:1606.00608, Appendix C.2, Lemma C.4 (`propSN`), lines
1451--1471. -/
noncomputable def activeSectorTraceMatrix (F : PhysicalSectorFactorization K)
    (p : Fin F.sectorCount → ℝ) :
    Matrix (F.ActiveSector p) (F.ActiveSector p) ℝ :=
  fun k h ↦ (F.neighboringOperator k h).trace.re

/-- Positive semidefinite neighboring operators give an entrywise
nonnegative active trace matrix. -/
theorem activeSectorTraceMatrix_nonneg (F : PhysicalSectorFactorization K)
    (p : Fin F.sectorCount → ℝ)
    (hpos : ∀ k h, (F.neighboringOperator k h).PosSemidef)
    (k h : F.ActiveSector p) :
    0 ≤ F.activeSectorTraceMatrix p k h := by
  exact (Complex.nonneg_iff.mp (hpos k h).trace_nonneg).1

/-- For positive semidefinite neighboring operators, an active trace-matrix
entry is positive exactly when the corresponding neighboring operator is
nonzero. -/
theorem activeSectorTraceMatrix_pos_iff (F : PhysicalSectorFactorization K)
    (p : Fin F.sectorCount → ℝ)
    (hpos : ∀ k h, (F.neighboringOperator k h).PosSemidef)
    (k h : F.ActiveSector p) :
    0 < F.activeSectorTraceMatrix p k h ↔
      F.neighboringOperator k h ≠ 0 := by
  constructor
  · intro h hzero
    simp [activeSectorTraceMatrix, hzero] at h
  · intro hne
    exact (Complex.lt_def.mp ((hpos k h).trace_pos_of_ne_zero hne)).1

/-- Every active sector belongs to a directed two-cycle when the active
sector virtual matrices span the full virtual matrix algebra and the sector
contains a nonzero virtual matrix.

Choose a nonzero virtual matrix `A` in sector `k`. Nondegeneracy of the trace
pairing and active-sector spanning give a virtual matrix `B` in an active
sector `h` such that `trace (A * B) ≠ 0`. Thus both `A * B` and `B * A` are
nonzero, the latter by cyclicity of the trace. Consequently the neighboring
operators from `k` to `h` and from `h` to `k` are nonzero.

This is the length-two closed-walk input in the primitivity argument of
arXiv:1606.00608, Appendix C.2, Lemma C.4 (`propSN`), lines 1452--1470.

**Scope restriction (periodicity):** the source removes periodic components by
blocking. Here the trace pairing instead supplies a closed walk of length two;
it is an auxiliary replacement to be paired with the length-three walk from
triangle closure. See
`docs/paper-gaps/cpgsv17_mpdo_sal_zcl_eta_local_structure.tex`. -/
theorem exists_active_two_cycle
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (hspan : Submodule.span ℂ
      (Set.range (F.activeSectorOneSiteMatrixFamily p)) = ⊤)
    (hnonzero : ∀ k : F.ActiveSector p,
      ∃ x y : F.SectorIndex k, F.sectorVirtualMatrix k x y ≠ 0)
    (k : F.ActiveSector p) :
    ∃ h : F.ActiveSector p,
      F.neighboringOperator k h ≠ 0 ∧ F.neighboringOperator h k ≠ 0 := by
  classical
  obtain ⟨x, y, hA⟩ := hnonzero k
  let A := F.sectorVirtualMatrix k x y
  obtain ⟨Y, htraceY⟩ : ∃ Y : Matrix (Fin D) (Fin D) ℂ,
      Matrix.trace (A * Y) ≠ 0 := by
    by_contra hall
    push Not at hall
    exact hA ((Matrix.trace_mul_right_eq_zero_iff A).mp hall)
  have hYmem : Y ∈ Submodule.span ℂ
      (Set.range (F.activeSectorOneSiteMatrixFamily p)) := by
    rw [hspan]
    exact Submodule.mem_top
  obtain ⟨c, hc⟩ :=
    (Submodule.mem_span_range_iff_exists_fun ℂ).mp hYmem
  have hsum : Matrix.trace
      (A * ∑ q, c q • F.activeSectorOneSiteMatrixFamily p q) ≠ 0 := by
    rw [hc]
    exact htraceY
  simp only [Matrix.mul_sum, Matrix.mul_smul, Matrix.trace_sum,
    Matrix.trace_smul] at hsum
  obtain ⟨q, hq⟩ : ∃ q : F.ActiveSectorEntryIndex p,
      c q * Matrix.trace
        (A * F.activeSectorOneSiteMatrixFamily p q) ≠ 0 := by
    by_contra hall
    push Not at hall
    exact hsum (Finset.sum_eq_zero fun q _ ↦ hall q)
  have htraceB : Matrix.trace
      (A * F.activeSectorOneSiteMatrixFamily p q) ≠ 0 :=
    right_ne_zero_of_mul hq
  have hAB : A * F.activeSectorOneSiteMatrixFamily p q ≠ 0 := by
    intro hzero
    apply htraceB
    rw [hzero, Matrix.trace_zero]
  have hBA : F.activeSectorOneSiteMatrixFamily p q * A ≠ 0 := by
    intro hzero
    apply htraceB
    rw [Matrix.trace_mul_comm, hzero, Matrix.trace_zero]
  refine ⟨q.1, ?_, ?_⟩
  · intro hzero
    apply hAB
    simpa [A, activeSectorOneSiteMatrixFamily] using
      F.sectorVirtualMatrix_mul_eq_zero_of_neighboringOperator_eq_zero
        k q.1 hzero x y q.2.1 q.2.2
  · intro hzero
    apply hBA
    simpa [A, activeSectorOneSiteMatrixFamily] using
      F.sectorVirtualMatrix_mul_eq_zero_of_neighboringOperator_eq_zero
        q.1 k hzero q.2.1 q.2.2 x y

/-- Every diagonal entry of the square of the active trace matrix is
strictly positive under positive semidefiniteness, active-sector spanning,
and sector nonvanishing.

The positive summand is supplied by the directed two-cycle through the given
sector. This is one of two coprime-period inputs; it does not assert that the
diagonal entry of the trace matrix itself is positive.

**Scope restriction (periodicity):** this length-two return is an auxiliary
substitute for the source's blocking of periodic components and must be
combined with the length-three return from triangle closure. See
`docs/paper-gaps/cpgsv17_mpdo_sal_zcl_eta_local_structure.tex`. -/
theorem activeSectorTraceMatrix_pow_two_diag_pos
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (hpos : ∀ k h, (F.neighboringOperator k h).PosSemidef)
    (hspan : Submodule.span ℂ
      (Set.range (F.activeSectorOneSiteMatrixFamily p)) = ⊤)
    (hnonzero : ∀ k : F.ActiveSector p,
      ∃ x y : F.SectorIndex k, F.sectorVirtualMatrix k x y ≠ 0)
    (k : F.ActiveSector p) :
    0 < ((F.activeSectorTraceMatrix p) ^ 2) k k := by
  obtain ⟨h, hkh, hhk⟩ := F.exists_active_two_cycle p hspan hnonzero k
  rw [pow_two, Matrix.mul_apply]
  apply Finset.sum_pos'
  · intro j _
    exact mul_nonneg
      (F.activeSectorTraceMatrix_nonneg p hpos k j)
      (F.activeSectorTraceMatrix_nonneg p hpos j k)
  · exact ⟨h, Finset.mem_univ h, mul_pos
      ((F.activeSectorTraceMatrix_pos_iff p hpos k h).2 hkh)
      ((F.activeSectorTraceMatrix_pos_iff p hpos h k).2 hhk)⟩

/-- Under positive semidefiniteness, active-sector spanning, and sector
nonvanishing, the active trace matrix is irreducible. -/
theorem activeSectorTraceMatrix_isIrreducible
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (hpos : ∀ k h, (F.neighboringOperator k h).PosSemidef)
    (hspan : Submodule.span ℂ
      (Set.range (F.activeSectorOneSiteMatrixFamily p)) = ⊤)
    (hnonzero : ∀ k : F.ActiveSector p,
      ∃ x y : F.SectorIndex k, F.sectorVirtualMatrix k x y ≠ 0) :
    Matrix.IsIrreducible (F.activeSectorTraceMatrix p) := by
  classical
  letI : Quiver (F.ActiveSector p) :=
    Matrix.toQuiver (F.activeSectorTraceMatrix p)
  refine ⟨F.activeSectorTraceMatrix_nonneg p hpos, ?_⟩
  have hconnected : Quiver.IsStronglyConnected (F.ActiveSector p) := by
    intro k h
    have hreach :=
      F.activeSector_reflTransGen_neighboringOperator_ne_zero p hspan hnonzero k h
    induction hreach with
    | refl => exact ⟨Quiver.Path.nil⟩
    | tail hab hbc ih =>
        exact ⟨ih.some.cons (PLift.up
          ((F.activeSectorTraceMatrix_pos_iff p hpos _ _).2 hbc))⟩
  cases isEmpty_or_nonempty (F.ActiveSector p) with
  | inl hempty =>
      intro k
      exact isEmptyElim k
  | inr hnonempty =>
      let k : F.ActiveSector p := Classical.choice hnonempty
      obtain ⟨h, hkh⟩ :=
        F.exists_active_neighboringOperator_ne_zero p hspan hnonzero k
      exact hconnected.isSStronglyConnected_of_hom
        (PLift.up ((F.activeSectorTraceMatrix_pos_iff p hpos k h).2 hkh))

/-- If every active nonzero edge closes through a third active sector, then
every diagonal entry of the cube of the active trace matrix is positive.

**Scope restriction (periodicity):** this length-three return is an auxiliary
substitute for the source's blocking of periodic components and is combined
with the length-two return above. See
`docs/paper-gaps/cpgsv17_mpdo_sal_zcl_eta_local_structure.tex`.

Source: arXiv:1606.00608, Appendix C.2, Lemma C.4 (`propSN`), lines
1452--1470. -/
theorem activeSectorTraceMatrix_pow_three_diag_pos
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (hpos : ∀ k h, (F.neighboringOperator k h).PosSemidef)
    (hspan : Submodule.span ℂ
      (Set.range (F.activeSectorOneSiteMatrixFamily p)) = ⊤)
    (hnonzero : ∀ k : F.ActiveSector p,
      ∃ x y : F.SectorIndex k, F.sectorVirtualMatrix k x y ≠ 0)
    (htriangle : ∀ {k h : F.ActiveSector p},
      F.neighboringOperator k h ≠ 0 →
        ∃ j : F.ActiveSector p,
          F.neighboringOperator h j ≠ 0 ∧
            F.neighboringOperator j k ≠ 0)
    (k : F.ActiveSector p) :
    0 < ((F.activeSectorTraceMatrix p) ^ 3) k k := by
  obtain ⟨h, hkh⟩ :=
    F.exists_active_neighboringOperator_ne_zero p hspan hnonzero k
  obtain ⟨j, hhj, hjk⟩ := htriangle hkh
  let T := F.activeSectorTraceMatrix p
  have hnonneg : ∀ a b, 0 ≤ T a b :=
    F.activeSectorTraceMatrix_nonneg p hpos
  have hpow2 : 0 < (T ^ 2) k j := by
    rw [pow_two, Matrix.mul_apply]
    apply Finset.sum_pos'
    · intro l _
      exact mul_nonneg (hnonneg k l) (hnonneg l j)
    · exact ⟨h, Finset.mem_univ h, mul_pos
        ((F.activeSectorTraceMatrix_pos_iff p hpos k h).2 hkh)
        ((F.activeSectorTraceMatrix_pos_iff p hpos h j).2 hhj)⟩
  rw [show T ^ 3 = T ^ 2 * T by rw [pow_succ], Matrix.mul_apply]
  apply Finset.sum_pos'
  · intro l _
    exact mul_nonneg (Matrix.pow_apply_nonneg hnonneg 2 k l) (hnonneg l k)
  · exact ⟨j, Finset.mem_univ j, mul_pos hpow2
      ((F.activeSectorTraceMatrix_pos_iff p hpos j k).2 hjk)⟩

/-- Active-sector spanning, sector nonvanishing, positive neighboring
operators, and triangle closure imply primitivity of the active trace matrix.

**Scope restriction (periodicity and triangle closure):** the common positive
power is obtained from closed walks of lengths two and three, under the
source-absent triangle-closure hypothesis, in place of the source's blocking
argument. See
`docs/paper-gaps/cpgsv17_mpdo_sal_zcl_eta_local_structure.tex`.

Source: arXiv:1606.00608, Appendix C.2, Lemma C.4 (`propSN`), lines
1451--1471. -/
theorem activeSectorTraceMatrix_isPrimitive
    (F : PhysicalSectorFactorization K) (p : Fin F.sectorCount → ℝ)
    (hpos : ∀ k h, (F.neighboringOperator k h).PosSemidef)
    (hspan : Submodule.span ℂ
      (Set.range (F.activeSectorOneSiteMatrixFamily p)) = ⊤)
    (hnonzero : ∀ k : F.ActiveSector p,
      ∃ x y : F.SectorIndex k, F.sectorVirtualMatrix k x y ≠ 0)
    (htriangle : ∀ {k h : F.ActiveSector p},
      F.neighboringOperator k h ≠ 0 →
        ∃ j : F.ActiveSector p,
          F.neighboringOperator h j ≠ 0 ∧
            F.neighboringOperator j k ≠ 0) :
    Matrix.IsPrimitive (F.activeSectorTraceMatrix p) :=
  (F.activeSectorTraceMatrix_isIrreducible p hpos hspan hnonzero)
    |>.isPrimitive_of_pow_two_diagonal_pos_of_pow_three_diagonal_pos
      (F.activeSectorTraceMatrix_pow_two_diag_pos p hpos hspan hnonzero)
      (F.activeSectorTraceMatrix_pow_three_diag_pos
        p hpos hspan hnonzero htriangle)

end MPOTensor.PhysicalSectorFactorization
