/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.MPDO.RFPViaTS
import TNLean.MPS.RFP.Defs

/-!
# Purification renormalization fixed points for MPDO tensors

This file states the purification renormalization fixed-point data from
arXiv:1606.00608 (Cirac--Perez-Garcia--Schuch--Verstraete), Definition 4.4
(paper label `def:Puri-RFP`, lines 756--764).

The source definition is global in the system size: an MPO tensor `M` is written
as the ancillary trace of a pure MPS density matrix

`rho_p^(N)(M) = tr_a(|Psi^(N)(A)><Psi^(N)(A)|)`

for every length `N`, with the purifying spin-ancilla tensor `A` a pure-state
RFP. This file encodes that equality as an equality of the finite-chain matrices
indexed by spin configurations.

The source text immediately after Definition 4.4 observes that tracing the
ancilla gives a trace-preserving completely positive map on the spin degrees of
freedom. This additional structure is recorded separately as
`IsPRFPWithTracePreservingSpinReduction`, so that the source-named predicate
`IsPRFP` remains the literal Definition 4.4 statement. The theorem equating
purification RFP with zero correlation length remains a separate open result.

## Main definitions

* `MPOTensor.purificationTensor`: the spin-ancilla MPS tensor.
* `MPOTensor.purificationDensity`: the finite-chain ancillary trace.
* `MPOTensor.HasGlobalPurificationEquation`: the equation `eq:MPDO-Puri-1`.
* `MPOTensor.HasPurificationRFPWitness`: the literal purification-RFP witness.
* `MPOTensor.IsPRFP`: the source purification-RFP predicate.
* `MPOTensor.IsPRFPWithTracePreservingSpinReduction`: the PRFP predicate
  together with the trace-preserving spin map.

## References

* [Cirac--Perez-Garcia--Schuch--Verstraete 2017] arXiv:1606.00608,
  `eq:MPDO-Puri-1` (line 751), Definition `def:Puri-RFP` (line 758), and the
  tpCPM discussion after tracing ancillas (lines 761--764).
-/

open scoped Matrix BigOperators

namespace MPOTensor

variable {d D : ℕ}

/-- The purifying spin-ancilla MPS tensor associated to a family
`A^{(i,k)}`. The physical index is the product of the spin index `i` and the
ancillary index `k`, as in arXiv:1606.00608, `Psipuri` and
`eq:MPDO-Puri-1`, lines 744--751. -/
def purificationTensor {d dK D' : ℕ}
    (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ) : MPSTensor (d * dK) D' :=
  fun p => A p.divNat p.modNat

/-- The finite-chain density matrix obtained by tracing the ancillary systems
of the pure spin-ancilla MPS generated by `A`.

For spin words `sigma` and `tau`, the matrix coefficient is

`sum_kappa psi_A(sigma,kappa) * conj psi_A(tau,kappa)`,

which is the coefficient form of arXiv:1606.00608, `eq:MPDO-Puri-1`
(line 751). -/
noncomputable def purificationDensity {d dK D' : ℕ}
    (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ) (N : ℕ) :
    Matrix (Fin N → Fin d) (Fin N → Fin d) ℂ :=
  Matrix.of fun σ τ =>
    ∑ κ : Fin N → Fin dK,
      MPSTensor.mpv (purificationTensor A) (fun n => finProdFinEquiv (σ n, κ n)) *
      star (MPSTensor.mpv (purificationTensor A) (fun n => finProdFinEquiv (τ n, κ n)))

/-- The global purification equation of arXiv:1606.00608, `eq:MPDO-Puri-1`
(line 751): for every chain length, the MPDO generated by `M` equals the
ancillary trace of the pure spin-ancilla MPS generated by `A`. -/
def HasGlobalPurificationEquation (M : MPOTensor d D)
    {dK D' : ℕ} (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ) : Prop :=
  ∀ N : ℕ, mpo M N = purificationDensity A N

/-- The literal purification-RFP witness from arXiv:1606.00608,
Definition `def:Puri-RFP` (lines 756--764): there is a purifying spin-ancilla
MPS tensor satisfying the global purification equation, and that purifying
tensor is a pure-state renormalization fixed point. -/
def HasPurificationRFPWitness (M : MPOTensor d D) : Prop :=
  ∃ (dK D' : ℕ) (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ),
    HasGlobalPurificationEquation M A ∧ MPSTensor.IsRFP (purificationTensor A)

/-- Purification renormalization fixed point in the sense of arXiv:1606.00608,
Definition `def:Puri-RFP` (lines 756--764): the tensor has a global
purification-RFP witness. -/
def IsPRFP (M : MPOTensor d D) : Prop :=
  HasPurificationRFPWitness M

/-- Purification RFP together with the trace-preserving spin structure recorded
after Definition `def:Puri-RFP` in arXiv:1606.00608, lines 761--764.

The first conjunct is the source purification-RFP predicate. The second conjunct
is the source mixed-state RFP condition via trace-preserving completely positive
maps on the physical degrees of freedom (`RFPMixedTS`, line 657), used here to
record the tpCPM structure obtained after tracing the ancillary index. -/
def IsPRFPWithTracePreservingSpinReduction (M : MPOTensor d D) : Prop :=
  IsPRFP M ∧ IsRFPViaTS M

/-- A purification RFP supplies the global purification-RFP witness. -/
theorem IsPRFP.hasPurificationRFPWitness {M : MPOTensor d D}
    (h : IsPRFP M) : HasPurificationRFPWitness M :=
  h

/-- A purification RFP with trace-preserving spin reduction carries the
purification-RFP predicate. -/
theorem IsPRFPWithTracePreservingSpinReduction.isPRFP {M : MPOTensor d D}
    (h : IsPRFPWithTracePreservingSpinReduction M) : IsPRFP M :=
  h.1

/-- A purification RFP with trace-preserving spin reduction carries the
trace-preserving-map mixed-state RFP
structure on the spin degrees of freedom. -/
theorem IsPRFPWithTracePreservingSpinReduction.isRFPViaTS {M : MPOTensor d D}
    (h : IsPRFPWithTracePreservingSpinReduction M) : IsRFPViaTS M :=
  h.2

/-- A purification-RFP witness contains a purifying tensor satisfying the global
purification equation. -/
theorem HasPurificationRFPWitness.hasGlobalPurificationEquation {M : MPOTensor d D}
    (h : HasPurificationRFPWitness M) :
    ∃ (dK D' : ℕ) (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ),
      HasGlobalPurificationEquation M A := by
  rcases h with ⟨dK, D', A, hglobal, _hRFP⟩
  exact ⟨dK, D', A, hglobal⟩

/-- A purification-RFP witness contains a pure-state RFP purifying tensor. -/
theorem HasPurificationRFPWitness.purifying_isRFP {M : MPOTensor d D}
    (h : HasPurificationRFPWitness M) :
    ∃ (dK D' : ℕ) (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ),
      MPSTensor.IsRFP (purificationTensor A) := by
  rcases h with ⟨dK, D', A, _hglobal, hRFP⟩
  exact ⟨dK, D', A, hRFP⟩

end MPOTensor
