/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.MPDO.RFPViaTS
import TNLean.MPS.RFP.Defs

/-!
# Purification renormalization fixed points for MPDO tensors

This file states the purification renormalization fixed-point data from
arXiv:1606.00608 (Cirac--Perez-Garcia--Schuch--Verstraete), Definition 4.4
(paper label `def:Puri-RFP`, lines 756--764).

The source definition is global in the system size: an MPO tensor `M` is written
at each positive chain length as the ancillary trace of a pure MPS density matrix

`rho_p^(N)(M) = tr_a(|Psi^(N)(A)><Psi^(N)(A)|)`

with the purifying spin-ancilla tensor `A` a pure-state RFP whose reduced
density is obtained by tracing the ancillary legs. This file encodes that
equality as an equality of the finite-chain matrices indexed by spin
configurations.

The source text immediately after Definition 4.4 observes that tracing the
ancilla gives a trace-preserving completely positive map on the spin degrees of
freedom. This additional structure is recorded separately as
`IsPRFPWithTracePreservingSpinReduction`, so that the source-named predicate
`IsPRFP` remains the literal Definition 4.4 statement. The theorem equating
purification RFP with zero correlation length remains a separate open result.

## Main definitions

* `MPOTensor.purificationTensor`: the spin-ancilla MPS tensor.
* `MPOTensor.purificationDensity`: the finite-chain ancillary trace.
* `MPOTensor.HasGlobalPurificationEquation`: the positive-length equation
  `eq:MPDO-Puri-1`.
* `MPOTensor.ancillaryTraceMap`: the spin map obtained by tracing the ancilla.
* `MPOTensor.HasTracePreservingSpinReduction`: the tpCPM condition for that map.
* `MPOTensor.HasPurificationRFPWitness`: the source purification-RFP witness.
* `MPOTensor.IsPRFP`: the source purification-RFP predicate.
* `MPOTensor.IsPRFPWithTracePreservingSpinReduction`: the PRFP predicate
  together with the trace-preserving spin map.

## References

* [Cirac--Perez-Garcia--Schuch--Verstraete 2017] arXiv:1606.00608,
  `eq:MPDO-Puri-1` (line 751), Definition `def:Puri-RFP` (line 758), and the
  tpCPM discussion after tracing ancillas (lines 761--764).
-/

open scoped Matrix BigOperators

namespace MPOTensor

variable {d D : ℕ}

/-- The purifying spin-ancilla MPS tensor associated to a family
`A^{(i,k)}`. The physical index is the product of the spin index `i` and the
ancillary index `k`, as in arXiv:1606.00608, `Psipuri` and
`eq:MPDO-Puri-1`, lines 744--751. -/
def purificationTensor {d dK D' : ℕ}
    (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ) : MPSTensor (d * dK) D' :=
  fun p => A p.divNat p.modNat

/-- The finite-chain density matrix obtained by tracing the ancillary systems
of the pure spin-ancilla MPS generated by `A`.

For spin words `sigma` and `tau`, the matrix coefficient is

`sum_kappa psi_A(sigma,kappa) * conj psi_A(tau,kappa)`,

which is the coefficient form of arXiv:1606.00608, `eq:MPDO-Puri-1`
(line 751). -/
noncomputable def purificationDensity {d dK D' : ℕ}
    (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ) (N : ℕ) :
    Matrix (Fin N → Fin d) (Fin N → Fin d) ℂ :=
  Matrix.of fun σ τ =>
    ∑ κ : Fin N → Fin dK,
      MPSTensor.mpv (purificationTensor A) (fun n => finProdFinEquiv (σ n, κ n)) *
      star (MPSTensor.mpv (purificationTensor A) (fun n => finProdFinEquiv (τ n, κ n)))

/-- The partial trace over the ancillary physical index. For a matrix on
spin--ancilla degrees of freedom it is the spin matrix

`(Tr_a X)_{ij} = ∑_k X_{(i,k),(j,k)}`.

This is the trace operation in arXiv:1606.00608, `eq:MPDO-Puri-1` (line 751),
and the source of the tpCPM mentioned in lines 761--764. -/
noncomputable def ancillaryTraceMap (d dK : ℕ) :
    Matrix (Fin d × Fin dK) (Fin d × Fin dK) ℂ →ₗ[ℂ] Matrix (Fin d) (Fin d) ℂ where
  toFun X := Matrix.of fun i j => ∑ k : Fin dK, X (i, k) (j, k)
  map_add' X Y := by
    ext i j
    simp [Finset.sum_add_distrib]
  map_smul' c X := by
    ext i j
    simp [Finset.mul_sum]

/-- The global purification equation of arXiv:1606.00608, `eq:MPDO-Puri-1`
(line 751): for every positive chain length, the MPDO generated by `M` equals
the ancillary trace of the pure spin-ancilla MPS generated by `A`. The
positive-length restriction avoids imposing an empty-chain bond-dimension
normalization absent from the source equation. -/
def HasGlobalPurificationEquation (M : MPOTensor d D)
    {dK D' : ℕ} (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ) : Prop :=
  ∀ N : ℕ, 0 < N → mpo M N = purificationDensity A N

/-- The post-ancilla spin reduction is trace-preserving and completely positive.
This records the tpCPM described after arXiv:1606.00608, Definition
`def:Puri-RFP` (lines 761--764), without imposing the two-map mixed-state RFP
condition of Definition 4.1. -/
def HasTracePreservingSpinReduction (d dK : ℕ) : Prop :=
  IsKrausCPTP (ancillaryTraceMap d dK)

/-- The purification-RFP witness from arXiv:1606.00608,
Definition `def:Puri-RFP` (lines 756--764): there is a purifying spin-ancilla
MPS tensor satisfying the global purification equation, and that purifying
tensor is a pure-state renormalization fixed point. -/
def HasPurificationRFPWitness (M : MPOTensor d D) : Prop :=
  ∃ (dK D' : ℕ) (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ),
    HasGlobalPurificationEquation M A ∧ MPSTensor.IsRFP (purificationTensor A)

/-- Purification renormalization fixed point in the sense of arXiv:1606.00608,
Definition `def:Puri-RFP` (lines 756--764): the tensor has a global
purification-RFP witness. -/
def IsPRFP (M : MPOTensor d D) : Prop :=
  HasPurificationRFPWitness M

/-- Purification RFP together with the trace-preserving spin structure recorded
after Definition `def:Puri-RFP` in arXiv:1606.00608, lines 761--764.

This is the source purification-RFP predicate together with the specific
trace-preserving completely positive map obtained by tracing the ancillary
physical index. It is not the two-map mixed-state RFP condition of Definition
4.1. -/
def IsPRFPWithTracePreservingSpinReduction (M : MPOTensor d D) : Prop :=
  ∃ (dK D' : ℕ) (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ),
    HasGlobalPurificationEquation M A ∧ MPSTensor.IsRFP (purificationTensor A) ∧
      HasTracePreservingSpinReduction d dK

/-- A purification RFP supplies the global purification-RFP witness. -/
theorem IsPRFP.hasPurificationRFPWitness {M : MPOTensor d D}
    (h : IsPRFP M) : HasPurificationRFPWitness M :=
  h

/-- A purification RFP with trace-preserving spin reduction carries the
purification-RFP predicate. -/
theorem IsPRFPWithTracePreservingSpinReduction.isPRFP {M : MPOTensor d D}
    (h : IsPRFPWithTracePreservingSpinReduction M) : IsPRFP M :=
  by
  rcases h with ⟨dK, D', A, hglobal, hRFP, _htrace⟩
  exact ⟨dK, D', A, hglobal, hRFP⟩

/-- A purification RFP with trace-preserving spin reduction carries the
post-ancilla tpCPM structure on the spin degrees of freedom. -/
theorem IsPRFPWithTracePreservingSpinReduction.hasTracePreservingSpinReduction
    {M : MPOTensor d D} (h : IsPRFPWithTracePreservingSpinReduction M) :
    ∃ dK : ℕ, HasTracePreservingSpinReduction d dK := by
  rcases h with ⟨dK, _D', _A, _hglobal, _hRFP, htrace⟩
  exact ⟨dK, htrace⟩

/-- A purification-RFP witness contains a purifying tensor satisfying the global
purification equation. -/
theorem HasPurificationRFPWitness.hasGlobalPurificationEquation {M : MPOTensor d D}
    (h : HasPurificationRFPWitness M) :
    ∃ (dK D' : ℕ) (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ),
      HasGlobalPurificationEquation M A := by
  rcases h with ⟨dK, D', A, hglobal, _hRFP⟩
  exact ⟨dK, D', A, hglobal⟩

/-- A purification-RFP witness contains a pure-state RFP purifying tensor. -/
theorem HasPurificationRFPWitness.purifying_isRFP {M : MPOTensor d D}
    (h : HasPurificationRFPWitness M) :
    ∃ (dK D' : ℕ) (A : Fin d → Fin dK → Matrix (Fin D') (Fin D') ℂ),
      MPSTensor.IsRFP (purificationTensor A) := by
  rcases h with ⟨dK, D', A, _hglobal, hRFP⟩
  exact ⟨dK, D', A, hRFP⟩

end MPOTensor
