/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.MPDO.RescalingStableLengthDependentRFP
import TNLean.MPS.RFP.BeigiLoopBNTIdentification

/-!
# The literal CPSV canonical form of `R.toMPSTensor`

This file proves `MPSTensor.IsCPSVCanonicalForm R.toMPSTensor` for the rescaling-stable
length-dependent example `R` of `TNLean.MPS.MPDO.RescalingStableLengthDependentRFP`
(arXiv:1606.00608, Section 2.3, lines 214--245 and eq. `II_CF1`).

The doubled-index tensor `R.toMPSTensor` has bond dimension `4` and `16` letters
`R p q`, `p q : Fin 4`.  Each letter is a rank-one bond matrix
`(25/32) • vecMulVec u_{pq} v_{pq}` (`R_eq_vecMulVec`), and as `(p, q)` ranges over all
`16` pairs the letters range exactly over the `16` scaled matrix units of the bond
algebra `Matrix (Fin 4) (Fin 4) ℂ` (`R_eq_single`): they span the full matrix algebra,
so `R.toMPSTensor` is algebraically injective (`R_toMPSTensor_isInjective`).

## The retained weight

The transfer map of `R.toMPSTensor` is rank one: `transferMap R.toMPSTensor X` is
always a scalar multiple of the fixed diagonal matrix
`fixedDiag = diag(sVal 0 ^ 2, sVal 1 ^ 2, sVal 2 ^ 2, sVal 3 ^ 2)`
(`transferMap_R_toMPSTensor_eq`), and this scalar, evaluated at `fixedDiag` itself, is
exactly `337/512` (`cFun_fixedDiag`). Consequently `transferMap R.toMPSTensor` is
idempotent up to the scalar `337/512`
(`transferMap_R_toMPSTensor_idem`), and the tensor
```
retainedBlock i = weight⁻¹ • R.toMPSTensor i,  weight = √(337/512)
```
has an exactly idempotent transfer map (`retainedBlock_isTransferIdempotent`): `weight`
is the unique positive real scalar making the retained block's transfer map spectral
radius equal to one, as required by the normal-tensor normalization of arXiv:1606.00608,
lines 224--235.

**Correction:** the module docstring of `RescalingStableLengthDependentRFP` speculated
the literal canonical-form weight was `(25/32)^2 = 625/1024` before this computation
was carried out; the exact value is the irrational `weight = √(337/512)` above.  `R` is
a project example, not a tensor stated in CPSV16 (see that file's module docstring), so
this numeric correction is internal bookkeeping (the weight is determined by
`transferMap R.toMPSTensor`'s own rank-one closed form, not by the already-displayed
scalar prefactor of `R`), not a deviation from the cited source.

`retainedBlock` is a CPSV normal tensor
(`retainedBlock_isNormalTensor`, via `MPSTensor.isNormalTensor_of_isNormal_isTransferIdempotent`
applied to its algebraic injectivity and idempotent transfer map), and
`R.toMPSTensor = weight • retainedBlock` pointwise (`R_toMPSTensor_eq_weight_smul_block`),
giving the literal CPSV canonical-form data with a single retained block occupying the
full ambient bond dimension `4` and a trivial (identity) coisometry
(`canonicalFormData`, `R_toMPSTensor_isCPSVCanonicalForm`).

## Main results

* `R_toMPSTensor_isInjective` : the `16` letters of `R.toMPSTensor` span the full bond
  matrix algebra.
* `retainedBlock_isNormalTensor` : the weight-normalized retained tensor is a CPSV
  normal tensor.
* `R_toMPSTensor_isCPSVCanonicalForm` : `R.toMPSTensor` is in literal CPSV canonical
  form.

## References

* [Cirac--Perez-Garcia--Schuch--Verstraete 2017] arXiv:1606.00608, Section 2.3,
  lines 214--245 and eq. `II_CF1`.
-/

open scoped Matrix BigOperators ComplexOrder Kronecker

noncomputable section

namespace MPOTensor.RescalingStableLengthDependentRFP

/-! ### The bond matrix units generated by `R` -/

/-- The nonzero value of the letter `A a` at its unique support point: `4/5` for the
diagonal letters `A 0`, `A 1`, and `3/5` for the off-diagonal letters `A 2`, `A 3`.

Project example; not from CPSV16. -/
def sVal : Fin 4 → ℂ
  | 0 => 4/5
  | 1 => 4/5
  | 2 => 3/5
  | 3 => 3/5

/-- The row of the letter `A a`'s unique support point.

Project example; not from CPSV16. -/
def aRow : Fin 4 → Fin 2
  | 0 => 0 | 1 => 1 | 2 => 0 | 3 => 1

/-- The column of the letter `A a`'s unique support point.

Project example; not from CPSV16. -/
def aCol : Fin 4 → Fin 2
  | 0 => 0 | 1 => 1 | 2 => 1 | 3 => 0

/-- `A a` evaluated at its own support point is its nonzero value `sVal a`. -/
lemma A_apply_aRow_aCol (a : Fin 4) : A a (aRow a) (aCol a) = sVal a := by
  fin_cases a <;> simp [A, aRow, aCol, sVal]

/-- A different letter vanishes at `A a`'s support point: the four letters are matrix
units supported at four pairwise-distinct positions. -/
lemma A_apply_ne_zero (a a' : Fin 4) (h : a ≠ a') :
    A a' (aRow a) (aCol a) = 0 := by
  fin_cases a <;> fin_cases a' <;> simp_all [A, aRow, aCol]

/-- Every letter's nonzero value is nonzero. -/
lemma sVal_ne_zero (a : Fin 4) : sVal a ≠ 0 := by fin_cases a <;> norm_num [sVal]

/-- **The letters of `R` are the scaled matrix units of the bond algebra.** For every
target bond matrix unit `(a0, b0)`, the physical letter `R p q` at
`p = bondEquiv (aRow a0, aRow b0)`, `q = bondEquiv (aCol a0, aCol b0)` is a nonzero
scalar multiple of `Matrix.single a0 b0 1`: the outer-product structure of
`R_eq_vecMulVec` collapses to a single matrix-unit letter because each factor `A a`,
`A b` is itself a scaled matrix unit.

Project example; not from CPSV16. -/
lemma R_eq_single (a0 b0 : Fin 4) :
    R (bondEquiv (aRow a0, aRow b0)) (bondEquiv (aCol a0, aCol b0)) =
      ((25/32 : ℂ) * sVal a0 * sVal b0) • Matrix.single a0 b0 (1 : ℂ) := by
  ext a b
  rw [R_apply, bondEquiv.symm_apply_apply, bondEquiv.symm_apply_apply]
  simp only [Matrix.smul_apply, smul_eq_mul, Matrix.single_apply]
  rw [Matrix.kroneckerMap_apply, Matrix.map_apply, starRingEnd_apply, A_star_eq]
  dsimp only
  by_cases ha : a = a0
  · subst ha
    rw [A_apply_aRow_aCol]
    by_cases hb : b = b0
    · subst hb
      rw [A_apply_aRow_aCol]
      simp only [true_and, if_true]
      ring
    · rw [A_apply_ne_zero b0 b (Ne.symm hb)]
      simp [Ne.symm hb]
  · rw [A_apply_ne_zero a0 a (Ne.symm ha)]
    simp [Ne.symm ha]

/-- The doubled-index letter at `finProdFinEquiv (p, q)` is exactly the MPO letter
`R p q`. -/
lemma toMPSTensor_R_apply (p q : Fin 4) :
    R.toMPSTensor (finProdFinEquiv (p, q)) = R p q := by
  unfold MPOTensor.toMPSTensor
  rw [MPSTensor.finProdFinEquiv_divNat, MPSTensor.finProdFinEquiv_modNat]

/-- **`R.toMPSTensor` is algebraically injective.** Its `16` letters span the full bond
matrix algebra `Matrix (Fin 4) (Fin 4) ℂ`: they are, up to nonzero scalars by
`R_eq_single`, exactly the standard matrix-unit basis of the bond space. -/
lemma R_toMPSTensor_isInjective : MPSTensor.IsInjective R.toMPSTensor := by
  unfold MPSTensor.IsInjective
  apply le_antisymm le_top
  rw [← (Matrix.stdBasis ℂ (Fin 4) (Fin 4)).span_eq]
  apply Submodule.span_le.mpr
  rintro M ⟨⟨a0, b0⟩, rfl⟩
  rw [Matrix.stdBasis_eq_single]
  have hc : (25/32 : ℂ) * sVal a0 * sVal b0 ≠ 0 := by
    have h25 : (25/32 : ℂ) ≠ 0 := by norm_num
    exact mul_ne_zero (mul_ne_zero h25 (sVal_ne_zero a0)) (sVal_ne_zero b0)
  have hmem : R (bondEquiv (aRow a0, aRow b0)) (bondEquiv (aCol a0, aCol b0)) ∈
      Submodule.span ℂ (Set.range R.toMPSTensor) := by
    have : R (bondEquiv (aRow a0, aRow b0)) (bondEquiv (aCol a0, aCol b0)) =
        R.toMPSTensor (finProdFinEquiv (bondEquiv (aRow a0, aRow b0),
          bondEquiv (aCol a0, aCol b0))) := (toMPSTensor_R_apply _ _).symm
    rw [this]
    exact Submodule.subset_span ⟨_, rfl⟩
  rw [R_eq_single] at hmem
  have := Submodule.smul_mem (Submodule.span ℂ (Set.range R.toMPSTensor))
    ((25/32 : ℂ) * sVal a0 * sVal b0)⁻¹ hmem
  rwa [smul_smul, inv_mul_cancel₀ hc, one_smul] at this

/-! ### The rank-one closed form of `transferMap R.toMPSTensor` -/

/-- Conjugating a matrix by a rank-one operator gives another rank-one operator, scaled
by the bilinear pairing of the second factor against the conjugated matrix. -/
private lemma vecMulVec_conj (n : Type*) [Fintype n]
    (u v : n → ℂ) (X : Matrix n n ℂ) :
    Matrix.vecMulVec u v * X * (Matrix.vecMulVec u v)ᴴ =
      (v ⬝ᵥ (X.mulVec (star v))) • Matrix.vecMulVec u (star u) := by
  ext i j
  simp only [Matrix.mul_apply, Matrix.vecMulVec_apply, Matrix.conjTranspose_apply,
    Matrix.smul_apply, smul_eq_mul, Matrix.mulVec, dotProduct, Pi.star_apply,
    Finset.mul_sum, Finset.sum_mul, star_mul']
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro k _
  apply Finset.sum_congr rfl
  intro x _
  ring

/-- The fixed diagonal matrix spanning the rank-one image of `transferMap R.toMPSTensor`
(`transferMap_R_toMPSTensor_eq`). -/
def fixedDiag : Matrix (Fin 4) (Fin 4) ℂ := Matrix.diagonal (fun a => (sVal a) ^ 2)

/-- **The closed form of `transferMap R.toMPSTensor`.** Every image is a scalar
multiple of the fixed matrix `fixedDiag`: the outer-product structure of `R p q`
(`R_eq_vecMulVec`, via `vecMulVec_conj`) reduces the doubled sum over the `16` letters
to a product of two single-letter Frobenius pairings, one contracting against
`fixedDiag` and the other against `X`'s diagonal entries. -/
lemma transferMap_R_toMPSTensor_eq (X : Matrix (Fin 4) (Fin 4) ℂ) :
    MPSTensor.transferMap R.toMPSTensor X =
      ((25/32 : ℂ) ^ 2 * ∑ b : Fin 4, (sVal b) ^ 2 * X b b) • fixedDiag := by
  rw [MPSTensor.transferMap_apply]
  rw [← Equiv.sum_comp (finProdFinEquiv : Fin 4 × Fin 4 ≃ Fin (4 * 4))
    (fun v => R.toMPSTensor v * X * (R.toMPSTensor v)ᴴ)]
  rw [Fintype.sum_prod_type]
  have hterm : ∀ p q : Fin 4,
      R.toMPSTensor (finProdFinEquiv (p, q)) * X * (R.toMPSTensor (finProdFinEquiv (p, q)))ᴴ =
      (25/32 : ℂ) ^ 2 •
        ((fun b => A b (bit2 p) (bit2 q)) ⬝ᵥ
          (X.mulVec (fun b => A b (bit2 p) (bit2 q)))) •
        Matrix.vecMulVec (fun a => A a (bit1 p) (bit1 q)) (fun a => A a (bit1 p) (bit1 q)) := by
    intro p q
    rw [toMPSTensor_R_apply, R_eq_vecMulVec p q, Matrix.conjTranspose_smul]
    simp only [smul_mul_assoc, mul_smul_comm, smul_smul]
    rw [vecMulVec_conj (Fin 4) (fun a => A a (bit1 p) (bit1 q)) (fun b => A b (bit2 p) (bit2 q)) X]
    have hstarv : star (fun b => A b (bit2 p) (bit2 q)) = fun b => A b (bit2 p) (bit2 q) := by
      funext b
      exact A_star_eq b (bit2 p) (bit2 q)
    have hstaru : star (fun a => A a (bit1 p) (bit1 q)) = fun a => A a (bit1 p) (bit1 q) := by
      funext a
      exact A_star_eq a (bit1 p) (bit1 q)
    rw [hstarv, hstaru, smul_smul]
    congr 1
    have hstar25 : star (25/32 : ℂ) = 25/32 := by
      rw [show (25/32 : ℂ) = ((25/32 : ℝ) : ℂ) by norm_num]
      exact Complex.conj_ofReal _
    rw [hstar25]
    ring
  simp_rw [hterm]
  ext a a'
  simp only [Fin.sum_univ_four, Matrix.sum_apply, Matrix.smul_apply, smul_eq_mul,
    dotProduct, Matrix.mulVec, bit1, bit2, fixedDiag, Matrix.diagonal_apply,
    A, sVal, Matrix.single_apply, Matrix.vecMulVec]
  fin_cases a <;> fin_cases a' <;> norm_num <;> ring

/-- The rank-one image scalar, evaluated at the fixed matrix `fixedDiag` itself, is
exactly `337/512`: `transferMap R.toMPSTensor` is idempotent up to this scalar
(`transferMap_R_toMPSTensor_idem`). -/
lemma cFun_fixedDiag :
    (25/32 : ℂ) ^ 2 * ∑ b : Fin 4, (sVal b) ^ 2 * fixedDiag b b = 337/512 := by
  simp only [fixedDiag, Matrix.diagonal_apply, Fin.sum_univ_four, sVal]
  norm_num

/-- `transferMap R.toMPSTensor` is idempotent up to the scalar `337/512`: applying it
twice to any `X` scales the single-application result by `337/512`, since every
application returns a scalar multiple of `fixedDiag` and `cFun_fixedDiag` gives the
scalar of the second application. -/
lemma transferMap_R_toMPSTensor_idem (X : Matrix (Fin 4) (Fin 4) ℂ) :
    MPSTensor.transferMap R.toMPSTensor (MPSTensor.transferMap R.toMPSTensor X) =
      (337/512 : ℂ) • MPSTensor.transferMap R.toMPSTensor X := by
  rw [transferMap_R_toMPSTensor_eq X, map_smul, transferMap_R_toMPSTensor_eq fixedDiag,
    cFun_fixedDiag, smul_smul, smul_smul, mul_comm]

/-! ### The retained normal block -/

/-- The literal-canonical-form weight `weight = √(337/512)`: the unique positive real
scalar making the retained block's transfer map exactly idempotent (hence
spectral-radius one, by `MPSTensor.isNormalTensor_of_isNormal_isTransferIdempotent`).

Corrects the `(25/32)^2 = 625/1024` guess of `RescalingStableLengthDependentRFP`'s
module docstring; see the module docstring above. -/
def weight : ℝ := Real.sqrt (337/512)

/-- `weight` is positive. -/
lemma weight_pos : 0 < weight := Real.sqrt_pos.mpr (by norm_num)

/-- `weight` is nonzero. -/
lemma weight_ne : weight ≠ 0 := weight_pos.ne'

/-- `weight ^ 2 = 337/512`, the reciprocal of the scalar `transferMap R.toMPSTensor` is
idempotent up to (`transferMap_R_toMPSTensor_idem`). -/
lemma weight_sq : weight ^ 2 = 337/512 := Real.sq_sqrt (by norm_num)

/-- `weight_sq`, cast to `ℂ`. -/
lemma weight_sq_C : (weight : ℂ) ^ 2 = 337/512 := by
  rw [← Complex.ofReal_pow, weight_sq]
  norm_num

/-- The retained normal block: `R.toMPSTensor` rescaled letterwise by `weight⁻¹`, the
single retained block of the literal CPSV canonical form
(`R_toMPSTensor_isCPSVCanonicalForm`). -/
def retainedBlock : MPSTensor 16 4 := fun i => (weight⁻¹ : ℂ) • R.toMPSTensor i

/-- `transferMap retainedBlock` is `(weight : ℂ)⁻¹ ^ 2` times `transferMap R.toMPSTensor`,
since the transfer map is quadratic in the tensor and `weight⁻¹` is real. -/
lemma retainedBlock_transferMap (X : Matrix (Fin 4) (Fin 4) ℂ) :
    MPSTensor.transferMap retainedBlock X =
      ((weight : ℂ)⁻¹ ^ 2) • MPSTensor.transferMap R.toMPSTensor X := by
  rw [MPSTensor.transferMap_apply, MPSTensor.transferMap_apply, Finset.smul_sum]
  apply Finset.sum_congr rfl
  intro i _
  change ((weight⁻¹ : ℂ) • R.toMPSTensor i) * X * ((weight⁻¹ : ℂ) • R.toMPSTensor i)ᴴ =
    ((weight : ℂ)⁻¹ ^ 2) • (R.toMPSTensor i * X * (R.toMPSTensor i)ᴴ)
  rw [Matrix.conjTranspose_smul]
  simp only [smul_mul_assoc, mul_smul_comm, smul_smul]
  have hstar : star (weight⁻¹ : ℂ) = (weight⁻¹ : ℂ) := by
    rw [show (weight⁻¹ : ℂ) = ((weight⁻¹ : ℝ) : ℂ) by norm_num]
    exact Complex.conj_ofReal _
  push_cast [hstar]
  ring_nf

/-- **`retainedBlock`'s transfer map is exactly idempotent.** Chasing the scalar through
`retainedBlock_transferMap` and `transferMap_R_toMPSTensor_idem`, the composite scalar
`(weight⁻¹)^2 * (weight⁻¹)^2 * (337/512)` equals `(weight⁻¹)^2` exactly because
`weight^2 = 337/512` (`weight_sq_C`). -/
lemma retainedBlock_isTransferIdempotent : MPSTensor.IsTransferIdempotent retainedBlock := by
  unfold MPSTensor.IsTransferIdempotent
  apply LinearMap.ext
  intro X
  rw [LinearMap.comp_apply]
  show MPSTensor.transferMap retainedBlock (MPSTensor.transferMap retainedBlock X) =
    MPSTensor.transferMap retainedBlock X
  rw [retainedBlock_transferMap, retainedBlock_transferMap, map_smul,
    transferMap_R_toMPSTensor_idem, smul_smul, smul_smul]
  congr 1
  have hw : (weight : ℂ) ≠ 0 := by exact_mod_cast weight_ne
  have hc : ((weight : ℂ)⁻¹ ^ 2) * (337/512) = 1 := by
    rw [← weight_sq_C]
    field_simp
  calc ((weight : ℂ)⁻¹ ^ 2 * (weight : ℂ)⁻¹ ^ 2 * (337/512))
      = (weight : ℂ)⁻¹ ^ 2 * (((weight : ℂ)⁻¹ ^ 2) * (337/512)) := by ring
    _ = (weight : ℂ)⁻¹ ^ 2 * 1 := by rw [hc]
    _ = (weight : ℂ)⁻¹ ^ 2 := by ring

/-- `retainedBlock`'s letters span the full bond matrix algebra, since they are nonzero
scalar multiples of `R.toMPSTensor`'s letters (`R_toMPSTensor_isInjective`). -/
lemma retainedBlock_isInjective : MPSTensor.IsInjective retainedBlock := by
  have hblock : retainedBlock = fun i => (weight⁻¹ : ℂ) • R.toMPSTensor i := rfl
  rw [hblock]
  refine R_toMPSTensor_isInjective.smul (inv_ne_zero ?_)
  exact_mod_cast weight_ne

/-- Algebraic normality (eventual block injectivity) follows from `1`-block
injectivity. -/
lemma retainedBlock_isNormal : MPSTensor.IsNormal retainedBlock :=
  retainedBlock_isInjective.isNormal

/-- **`retainedBlock` is a CPSV normal tensor.** -/
lemma retainedBlock_isNormalTensor : MPSTensor.IsNormalTensor retainedBlock :=
  MPSTensor.isNormalTensor_of_isNormal_isTransferIdempotent retainedBlock
    retainedBlock_isNormal retainedBlock_isTransferIdempotent

/-! ### Packaging the literal CPSV canonical form -/

/-- `R.toMPSTensor` is exactly `weight • retainedBlock`: the reconstruction equation of
the literal CPSV canonical form, with a trivial (identity) coisometry since the
retained block occupies the full ambient bond dimension. -/
lemma R_toMPSTensor_eq_weight_smul_retainedBlock (i : Fin 16) :
    R.toMPSTensor i = (weight : ℂ) • retainedBlock i := by
  change R.toMPSTensor i = (weight : ℂ) • ((weight⁻¹ : ℂ) • R.toMPSTensor i)
  rw [smul_smul]
  have hw : (weight : ℂ) ≠ 0 := by exact_mod_cast weight_ne
  rw [mul_inv_cancel₀ hw, one_smul]

/-- The `r = 1` weighted direct sum used for the literal reconstruction below reduces,
letter by letter, to the plain scalar multiple `weight • retainedBlock i`. -/
lemma toTensorFromBlocks_single_eq (i : Fin 16) :
    MPSTensor.toTensorFromBlocks (fun _ : Fin 1 => (weight : ℂ)) (fun _ : Fin 1 => retainedBlock)
        i =
      (weight : ℂ) • retainedBlock i := by
  let e : (Σ _k : Fin 1, Fin 4) ≃ Fin 4 := finSigmaFinEquiv
  have hflat (x : Fin 4) : e ⟨0, x⟩ = x := by fin_cases x <;> rfl
  have hflat_symm (x : Fin 4) : e.symm x = ⟨0, x⟩ := by
    apply e.injective
    rw [e.apply_symm_apply, hflat]
  unfold MPSTensor.toTensorFromBlocks
  ext a b
  change (Matrix.reindex e e)
      (Matrix.blockDiagonal' (fun _ : Fin 1 => (weight : ℂ) • retainedBlock i)) a b =
    ((weight : ℂ) • retainedBlock i) a b
  rw [Matrix.reindex_apply, Matrix.submatrix_apply, hflat_symm, hflat_symm]
  simp

/-- The literal CPSV canonical-form witness data for `R.toMPSTensor`: a single retained
normal block (`retainedBlock`) occupying the full ambient bond dimension `4`, weight
`weight`, and the trivial (identity) coisometry.

Source: arXiv:1606.00608, Section 2.3, lines 214--245 and eq. `II_CF1`. -/
noncomputable def canonicalFormData : MPSTensor.CPSVCanonicalFormData R.toMPSTensor where
  r := 1
  dim := fun _ => 4
  dim_pos := fun _ => by norm_num
  weights := fun _ => (weight : ℂ)
  blocks := fun _ => retainedBlock
  blocks_normal := fun _ => retainedBlock_isNormalTensor
  total_dim_le := by simp
  ambient_coisometry := (1 : Matrix (Fin 4) (Fin 4) ℂ)
  coisometric := by
    change (1 : Matrix (Fin 4) (Fin 4) ℂ) * (1 : Matrix (Fin 4) (Fin 4) ℂ)ᴴ = 1
    simp
  reconstruct := fun i => by
    rw [toTensorFromBlocks_single_eq]
    change R.toMPSTensor i =
      (1 : Matrix (Fin 4) (Fin 4) ℂ)ᴴ * ((weight : ℂ) • retainedBlock i) *
        (1 : Matrix (Fin 4) (Fin 4) ℂ)
    rw [Matrix.conjTranspose_one, Matrix.one_mul, Matrix.mul_one]
    exact R_toMPSTensor_eq_weight_smul_retainedBlock i

/-- **The literal CPSV canonical form of `R.toMPSTensor`.**

A single retained normal block occupying the full ambient bond dimension `4`, with
weight `weight = √(337/512)` (the unique positive scalar making the retained block's
transfer map idempotent, hence spectral-radius one).

Source: arXiv:1606.00608, Section 2.3, lines 214--245 and eq. `II_CF1`. -/
theorem R_toMPSTensor_isCPSVCanonicalForm :
    MPSTensor.IsCPSVCanonicalForm R.toMPSTensor :=
  ⟨canonicalFormData⟩

end MPOTensor.RescalingStableLengthDependentRFP
