/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.MPDO.PeriodicExclusion

/-!
# Vertically stacked layers of matrix product operators

This file formalizes the vertical stacking identity behind the powers
$[H^{(N)}]^p$ in the periodic-sector step of the proof of Proposition 4.13 of
arXiv:1606.00608, lines 1888--1893.  Placing one MPO layer on top of another
and contracting the shared physical index produces the MPO tensor
$$
  (M_1M_2)^{ij} = \sum_k M_1^{ik} \otimes M_2^{kj},
$$
whose density operator at every length is the product of the layers' density
operators: $H^{(N)}(M_1M_2) = H^{(N)}(M_1)H^{(N)}(M_2)$.  Iterating, the
$p$-fold vertical stack of a tensor generates $[H^{(N)}]^p$ for every $N$.

With this identity the invariant-projection argument of arXiv:1606.00608,
lines 1874--1887, applies to the stacked tensor: an
orthogonal projector that is one-sided invariant for every length-$p$ word of
the vertically viewed tensor commutes with $[H^{(N)}]^p$ at every length.
Combined with the all-length non-commutation family, this produces a
periodic-sector projector.  The passage from a nontrivial $p$-periodic vector
to an invariant, non-commuting projector — which the source draws from the
cyclic decomposition of the peripheral spectrum (Wolf 2012, Theorem 6.6) —
is the hypothesis `PeriodicVectorYieldsCyclicProjector`; granted it, the
vertically viewed tensor of a matrix product density operator has no
nontrivial $p$-periodic vectors.  The invariant projector itself, together
with its single-letter displacement, is constructed from the cyclic
decomposition in `TNLean/MPS/MPDO/CyclicProjector.lean`, which reduces this
hypothesis to the non-commutation family alone.

## Main definitions

* `idTensor`: the trivial-bond MPO tensor generating the identity operator;
  the empty vertical stack.
* `layerMul`: the vertical composition of two MPO layers.
* `stackedTensor`: the $p$-fold vertical stack of an MPO tensor.
* `PeriodicVectorYieldsCyclicProjector`: the hypothesis that a nontrivial
  $p$-periodic vector supplies an orthogonal projector invariant for every
  length-$p$ vertical word and non-commuting with every density operator.

## Main results

* `mpo_layerMul`: the density operator of two stacked layers is the product
  of the layers' density operators.
* `mpo_stackedTensor`: the density operator of $p$ stacked layers is
  $[H^{(N)}]^p$.
* `stackedTensor_ketLeftMul_invariant`: one-sided invariance for every
  length-$p$ vertical word gives one-sided invariance for the stacked tensor.
* `periodicVectorYieldsProjector_of_cyclic`: the cyclic-projector hypothesis
  implies the projector-supplying hypothesis of the periodic-sector step.
* `hasNoPeriodicVectors_verticalTensor_of_cyclicProjector`: granted the
  cyclic-projector hypothesis, a matrix product density operator has no
  nontrivial $p$-periodic vectors in the vertical direction.

## References

* [Cirac--Perez-Garcia--Schuch--Verstraete 2017] arXiv:1606.00608,
  Proposition 4.13, lines 1888--1893
* [M. Wolf, *Quantum Channels & Operations: Guided Tour*, Theorem 6.6]
-/

open scoped Matrix ComplexOrder BigOperators Kronecker

namespace MPOTensor

variable {d D D' : ℕ}

/-! ### The identity tensor and the layer product -/

/-- The MPO tensor with trivial bond whose letters are $\delta_{ij}$.  It
generates the identity operator at every system size (`mpo_idTensor`) and
serves as the empty vertical stack in `stackedTensor`. -/
noncomputable def idTensor (d : ℕ) : MPOTensor d 1 :=
  fun i j => if i = j then 1 else 0

/-- The identity tensor generates the identity operator at every system
size. -/
theorem mpo_idTensor (d N : ℕ) : mpo (idTensor d) N = 1 := by
  refine Matrix.ext fun σ τ => ?_
  simp only [mpo_apply, mpoMatrixEntry, evalWord_ofFn, Matrix.one_apply]
  by_cases h : σ = τ
  · subst h
    rw [if_pos rfl, List.prod_eq_one, Matrix.trace_one, Fintype.card_fin,
      Nat.cast_one]
    intro X hX
    obtain ⟨l, rfl⟩ := List.mem_ofFn.mp hX
    simp [idTensor]
  · rw [if_neg h]
    obtain ⟨l, hl⟩ : ∃ l, σ l ≠ τ l := Function.ne_iff.mp h
    have hzero : (0 : Matrix (Fin 1) (Fin 1) ℂ) ∈
        List.ofFn fun l => idTensor d (σ l) (τ l) :=
      List.mem_ofFn.mpr ⟨l, by simp [idTensor, hl]⟩
    rw [List.prod_eq_zero hzero, Matrix.trace_zero]

/-- The **vertical composition of two MPO layers**: stacking a layer of
$M$ on top of a layer of $M'$ and contracting the shared physical index gives
the MPO tensor $(MM')^{ij}=\sum_kM^{ik}\otimes M'^{kj}$ on the tensor product
of the virtual spaces.  Its density operator at every length is the product
of the layers' density operators (`mpo_layerMul`); the powers $[H^{(N)}]^p$
at arXiv:1606.00608, lines 1890--1891, are generated by
iterating this composition (`stackedTensor`). -/
noncomputable def layerMul (M : MPOTensor d D) (M' : MPOTensor d D') :
    MPOTensor d (D * D') :=
  fun i j => (∑ k : Fin d, M i k ⊗ₖ M' k j).submatrix
    (finProdFinEquiv.symm : Fin (D * D') ≃ Fin D × Fin D')
    (finProdFinEquiv.symm : Fin (D * D') ≃ Fin D × Fin D')

/-- The letters of the layer product in Kronecker form. -/
lemma layerMul_eq_kronecker (M : MPOTensor d D) (M' : MPOTensor d D')
    (i j : Fin d) :
    layerMul M M' i j = (∑ k : Fin d, M i k ⊗ₖ M' k j).submatrix
      (finProdFinEquiv.symm : Fin (D * D') ≃ Fin D × Fin D')
      (finProdFinEquiv.symm : Fin (D * D') ≃ Fin D × Fin D') :=
  rfl

/-- The letters of the layer product, entrywise on the paired bond
indices. -/
lemma layerMul_apply (M : MPOTensor d D) (M' : MPOTensor d D') (i j : Fin d)
    (a b : Fin (D * D')) :
    layerMul M M' i j a b =
      ∑ k : Fin d, M i k a.divNat b.divNat * M' k j a.modNat b.modNat := by
  simp [layerMul, Matrix.sum_apply]

/-- The word product of layer-product letters decomposes as a sum of
Kronecker products of the layers' word products, summed over the
configurations of the contracted physical index.  This is the technical
identity behind `mpo_layerMul`, in the pattern of the local-purification
decomposition. -/
lemma layerMul_prod_decomp (M : MPOTensor d D) (M' : MPOTensor d D')
    {N : ℕ} (σ τ : Fin N → Fin d) :
    (List.ofFn fun l => layerMul M M' (σ l) (τ l)).prod =
      (∑ κ : Fin N → Fin d,
        (List.ofFn fun l => M (σ l) (κ l)).prod ⊗ₖ
          (List.ofFn fun l => M' (κ l) (τ l)).prod).submatrix
        (finProdFinEquiv.symm : Fin (D * D') ≃ Fin D × Fin D')
        (finProdFinEquiv.symm : Fin (D * D') ≃ Fin D × Fin D') := by
  induction N with
  | zero =>
    simp only [List.ofFn_zero, List.prod_nil, Fintype.sum_unique]
    rw [Matrix.kroneckerMap_one_one (· * ·) (fun _ => zero_mul _)
      (fun _ => mul_zero _) (one_mul 1), Matrix.submatrix_one_equiv]
  | succ n ih =>
    simp only [List.ofFn_succ, List.prod_cons]
    rw [layerMul_eq_kronecker M M' (σ 0) (τ 0)]
    have ih_step := ih (σ ∘ Fin.succ) (τ ∘ Fin.succ)
    simp only [Function.comp_def] at ih_step
    rw [ih_step, Matrix.submatrix_mul_equiv _ _ _ finProdFinEquiv.symm _]
    congr 1
    rw [Finset.sum_mul]
    simp_rw [Finset.mul_sum, ← Matrix.mul_kronecker_mul]
    have reindex : ∀ F : (Fin (n + 1) → Fin d) →
        Matrix (Fin D × Fin D') (Fin D × Fin D') ℂ,
        ∑ κ, F κ = ∑ k : Fin d, ∑ κ' : Fin n → Fin d,
          F (Fin.cons k κ') := fun F => by
      rw [← Fintype.sum_prod_type']
      exact ((Fin.consEquiv fun _ : Fin (n + 1) => Fin d).sum_comp F).symm
    symm
    rw [reindex]
    simp only [Fin.cons_zero, Fin.cons_succ]

/-- **Two stacked layers generate the product of the density operators**:
$H^{(N)}(MM')=H^{(N)}(M)H^{(N)}(M')$ for every system size $N$.  Contracting
the shared physical index of the two layers matches the matrix product of
the generated operators; this is the identity behind the powers
$[H^{(N)}]^p$ at arXiv:1606.00608, lines 1890--1891. -/
theorem mpo_layerMul (M : MPOTensor d D) (M' : MPOTensor d D') (N : ℕ) :
    mpo (layerMul M M') N = mpo M N * mpo M' N := by
  refine Matrix.ext fun σ τ => ?_
  rw [Matrix.mul_apply]
  simp only [mpo_apply, mpoMatrixEntry, evalWord_ofFn]
  rw [layerMul_prod_decomp M M' σ τ, Matrix.trace_submatrix_equiv,
    Matrix.trace_sum]
  simp_rw [Matrix.trace_kronecker]

/-! ### The `p`-fold vertical stack -/

/-- The **$p$-fold vertical stack** of an MPO tensor: $p$ copies of the
layer placed on top of each other, with neighboring physical indices
contracted.  Its density operator at every length is $[H^{(N)}]^p$
(`mpo_stackedTensor`), the power appearing at arXiv:1606.00608,
lines 1890--1891. -/
noncomputable def stackedTensor (M : MPOTensor d D) : (p : ℕ) → MPOTensor d (D ^ p)
  | 0 => idTensor d
  | p + 1 => layerMul (stackedTensor M p) M

/-- **The stacked-layers identity**: the density operator of $p$ vertically
stacked layers is the $p$-th power of the single-layer density operator,
$H^{(N)}(M^{[p]})=[H^{(N)}(M)]^p$ for every $N$.  This is the
identity used implicitly at arXiv:1606.00608, lines
1890--1891, to interpret $[H^{(N)}]^p$ as the density operator of $p$
stacked layers. -/
theorem mpo_stackedTensor (M : MPOTensor d D) (p N : ℕ) :
    mpo (stackedTensor M p) N = mpo M N ^ p := by
  induction p with
  | zero =>
    calc mpo (stackedTensor M 0) N = 1 := mpo_idTensor d N
      _ = mpo M N ^ 0 := (pow_zero (mpo M N)).symm
  | succ p ih =>
    calc mpo (stackedTensor M (p + 1)) N
        = mpo (stackedTensor M p) N * mpo M N := mpo_layerMul (stackedTensor M p) M N
      _ = mpo M N ^ p * mpo M N := by rw [ih]
      _ = mpo M N ^ (p + 1) := (pow_succ (mpo M N) p).symm

/-- The vertical stack of a matrix product density operator is again a
matrix product density operator: powers of positive semidefinite matrices
are positive semidefinite. -/
protected theorem IsMPDO.stackedTensor {M : MPOTensor d D} (hM : IsMPDO M)
    (p : ℕ) : IsMPDO (stackedTensor M p) := by
  intro N hN
  rw [mpo_stackedTensor]
  exact (hM N hN).pow p

/-! ### Vertical letters of the stacked tensor -/

/-- Two MPO tensors with equal vertically viewed letters are equal. -/
theorem ext_of_verticalTensor {D₀ : ℕ} {X Y : MPOTensor d D₀}
    (h : ∀ v : Fin (D₀ * D₀), verticalTensor X v = verticalTensor Y v) :
    X = Y := by
  funext i j
  ext a b
  have h' : verticalTensor X (finProdFinEquiv (a, b)) i j =
      verticalTensor Y (finProdFinEquiv (a, b)) i j := by rw [h]
  simpa only [verticalTensor_apply, MPSTensor.finProdFinEquiv_divNat,
    MPSTensor.finProdFinEquiv_modNat] using h'

/-- The vertically viewed letters of the identity tensor are the identity
operator on the physical space. -/
theorem verticalTensor_idTensor (v : Fin (1 * 1)) :
    verticalTensor (idTensor d) v = 1 := by
  ext i j
  simp only [verticalTensor_apply, idTensor]
  by_cases h : i = j
  · subst h
    rw [if_pos rfl, Subsingleton.elim v.modNat v.divNat, Matrix.one_apply_eq,
      Matrix.one_apply_eq]
  · rw [if_neg h, Matrix.zero_apply, Matrix.one_apply_ne h]

/-- The vertically viewed letters of a layer product are the products of the
layers' vertically viewed letters: stacking layers concatenates the vertical
words (arXiv:1606.00608, line 943, for the vertical view). -/
theorem verticalTensor_layerMul (M : MPOTensor d D) (M' : MPOTensor d D')
    (v : Fin ((D * D') * (D * D'))) :
    verticalTensor (layerMul M M') v =
      verticalTensor M (finProdFinEquiv (v.divNat.divNat, v.modNat.divNat)) *
        verticalTensor M' (finProdFinEquiv (v.divNat.modNat, v.modNat.modNat)) := by
  ext i j
  rw [Matrix.mul_apply]
  simp only [verticalTensor_apply, layerMul_apply,
    MPSTensor.finProdFinEquiv_divNat, MPSTensor.finProdFinEquiv_modNat]

/-- Every vertically viewed letter of the $p$-fold stack is the evaluation
of a length-$p$ word of the vertically viewed tensor: stacking $p$ layers
concatenates $p$ vertical letters. -/
theorem exists_word_verticalTensor_stackedTensor (M : MPOTensor d D) :
    ∀ (p : ℕ) (v : Fin (D ^ p * D ^ p)),
      ∃ w : List (Fin (D * D)), w.length = p ∧
        verticalTensor (stackedTensor M p) v =
          MPSTensor.evalWord (verticalTensor M) w := by
  intro p
  induction p with
  | zero =>
    intro v
    exact ⟨[], rfl, verticalTensor_idTensor v⟩
  | succ p ih =>
    intro v
    obtain ⟨w, hlen, hw⟩ :=
      ih (finProdFinEquiv ((v.divNat.divNat : Fin (D ^ p)),
        (v.modNat.divNat : Fin (D ^ p))))
    refine ⟨w ++ [finProdFinEquiv ((v.divNat.modNat : Fin D),
      (v.modNat.modNat : Fin D))], by simp [hlen], ?_⟩
    rw [MPSTensor.evalWord_append]
    simp only [MPSTensor.evalWord_cons, MPSTensor.evalWord_nil, Matrix.mul_one]
    rw [← hw]
    exact verticalTensor_layerMul (stackedTensor M p) M v

/-- If a matrix $Q$ satisfies the one-sided invariance
$QA_w=QA_wQ$ for every length-$p$ word $w$ of the vertically viewed tensor,
then $Q$ is one-sided invariant for the $p$-fold stacked tensor in the sense
of the invariant-projection step, $QM^{[p]}=QM^{[p]}Q$.  This transfers the
invariance of a cyclic sector under $p$ vertical layers to the hypothesis at
arXiv:1606.00608, lines 1874--1887, applied to the stacked tensor. -/
theorem stackedTensor_ketLeftMul_invariant (M : MPOTensor d D) {p : ℕ}
    {Q : Matrix (Fin d) (Fin d) ℂ}
    (hQ : ∀ w : List (Fin (D * D)), w.length = p →
      Q * MPSTensor.evalWord (verticalTensor M) w =
        Q * MPSTensor.evalWord (verticalTensor M) w * Q) :
    (stackedTensor M p).ketLeftMul Q =
      ((stackedTensor M p).ketLeftMul Q).braRightMul Q := by
  refine ext_of_verticalTensor fun v => ?_
  rw [verticalTensor_braRightMul, verticalTensor_ketLeftMul]
  obtain ⟨w, hlen, hw⟩ := exists_word_verticalTensor_stackedTensor M p v
  rw [hw]
  exact hQ w hlen

/-! ### From cyclic-sector projectors to the periodic-sector projector -/

/-- An orthogonal projector that is one-sided invariant for every length-$p$
vertical word and fails to commute with the density operator at every length
is a periodic-sector projector: invariance transfers to the $p$-fold stacked
tensor, whose density operator is $[H^{(N)}]^p$, and the invariant-projection
argument of arXiv:1606.00608, lines 1874--1887, applied to the stacked tensor
gives the commutation family at lines 1890--1891. -/
noncomputable def periodicSectorProjectorOfCyclicData (M : MPOTensor d D)
    (hM : IsMPDO M) {p : ℕ} (hp : p ≠ 0) {Q : Matrix (Fin d) (Fin d) ℂ}
    (hQherm : Q.IsHermitian) (hQidem : IsIdempotentElem Q)
    (hQword : ∀ w : List (Fin (D * D)), w.length = p →
      Q * MPSTensor.evalWord (verticalTensor M) w =
        Q * MPSTensor.evalWord (verticalTensor M) w * Q)
    (hQnc : ∀ N : ℕ, ¬ Commute (firstSiteMatrix Q N) (mpo M (N + 1))) :
    PeriodicSectorProjector M p where
  Q := Q
  isHermitian := hQherm
  isIdempotentElem := hQidem
  p_ne_zero := hp
  not_commute := hQnc
  commute_pow := fun N => by
    have h := firstSiteMatrix_mul_mpo_comm (stackedTensor M p)
      (hM.stackedTensor p) hQherm (stackedTensor_ketLeftMul_invariant M hQword) N
    rw [mpo_stackedTensor] at h
    exact h

/-- **Hypothesis** (arXiv:1606.00608, lines 1889--1891, and Wolf 2012,
Theorem 6.6): every nontrivial $p$-periodic vector of the vertically viewed
tensor supplies an orthogonal projector $Q$ on the physical space that is
one-sided invariant for every length-$p$ word of the vertically viewed
tensor while failing to commute with the density operator $H^{(N)}$ at every
length.  A nontrivial $p$-periodic vector is presented as in
`MPSTensor.HasNoPeriodicVectors`: an irreducible restriction $B$ of the
vertically viewed tensor to a minimal invariant subspace, carrying a
positive-definite transfer eigenvector with positive eigenvalue $r$,
together with a transfer eigenvalue of modulus $r$ different from $r$.

The intended derivation takes $Q$ among the cyclic projections of the
peripheral spectrum of the vertical transfer map (Wolf 2012, Theorem 6.6):
each cyclic projection of a period-$p$ sector returns to itself after $p$
applications of the map — the one-sided word invariance — while its
nontrivial cyclic displacement under one layer prevents commutation with
$H^{(N)}$.  Compared with `PeriodicVectorYieldsProjector`, the commutation
of $Q$ with $[H^{(N)}]^p$ is no longer assumed: it is derived from the word
invariance through the stacked-layers identity
(`periodicSectorProjectorOfCyclicData`).

The projector, its word invariance, and its single-letter displacement are
constructed unconditionally in
`exists_displaced_invariant_projector_of_periodic_vector`
(`TNLean/MPS/MPDO/CyclicProjector.lean`); this hypothesis follows from the
non-commutation hypothesis `NoninvariantProjectorNoncommuting` through
`periodicVectorYieldsCyclicProjector_of_noncommutation`.  For a tensor in
normalized BNT-refined horizontal form, the direct theorem
`hasNoPeriodicVectors_verticalTensor_of_horizontalCF` avoids this stronger
all-length hypothesis by using one noncommuting length.  This hypothesis is
stronger than literal CPSV canonical form; the distinction is
recorded in `docs/paper-gaps/cpgsv17_periodic_sector_projector.tex`. -/
def PeriodicVectorYieldsCyclicProjector (M : MPOTensor d D) : Prop :=
  ∀ ⦃n : ℕ⦄ (V : Matrix (Fin d) (Fin n) ℂ) (B : MPSTensor (D * D) n)
    (ρ : Matrix (Fin n) (Fin n) ℂ) (r : ℝ),
    Vᴴ * V = 1 → (∀ v : Fin (D * D), verticalTensor M v * V = V * B v) →
    MPSTensor.IsIrreducibleTensor B → ρ.PosDef → 0 < r →
    MPSTensor.transferMap (d := D * D) (D := n) B ρ = (r : ℂ) • ρ →
    ∀ μ : ℂ,
      Module.End.HasEigenvalue (MPSTensor.transferMap (d := D * D) (D := n) B) μ →
      ‖μ‖ = r → μ ≠ (r : ℂ) →
      ∃ (p : ℕ) (Q : Matrix (Fin d) (Fin d) ℂ),
        p ≠ 0 ∧ Q.IsHermitian ∧ IsIdempotentElem Q ∧
        (∀ w : List (Fin (D * D)), w.length = p →
          Q * MPSTensor.evalWord (verticalTensor M) w =
            Q * MPSTensor.evalWord (verticalTensor M) w * Q) ∧
        ∀ N : ℕ, ¬ Commute (firstSiteMatrix Q N) (mpo M (N + 1))

/-- The cyclic-projector hypothesis implies the projector-supplying
hypothesis of the periodic-sector step: for a matrix product density
operator, the word invariance of the supplied projector yields its
commutation with $[H^{(N)}]^p$ at every length through the stacked-layers
identity, so the projector is a periodic-sector projector.  This reduces
the hypothesis of the periodic-sector step of the proof of Proposition 4.13
of arXiv:1606.00608, lines 1888--1893, to the cyclic-decomposition
statement. -/
theorem periodicVectorYieldsProjector_of_cyclic (M : MPOTensor d D)
    (hM : IsMPDO M) (hCyc : PeriodicVectorYieldsCyclicProjector M) :
    PeriodicVectorYieldsProjector M := by
  intro n V B ρ r hV hint hirr hρ hr hfix μ hμ hnorm hne
  obtain ⟨p, Q, hp, hherm, hidem, hword, hnc⟩ :=
    hCyc V B ρ r hV hint hirr hρ hr hfix μ hμ hnorm hne
  exact ⟨p, ⟨periodicSectorProjectorOfCyclicData M hM hp hherm hidem hword hnc⟩⟩

/-- The vertically viewed tensor of a matrix product density operator has no
nontrivial $p$-periodic vectors, granted that periodic vectors supply cyclic
projectors.  This is the periodic-sector step in the proof of Proposition
4.13 of arXiv:1606.00608, lines 1888--1893, with the commutation family
derived from the stacked-layers identity rather than assumed.

**Scope restriction (conditional on the supplied cyclic projector):** this
theorem retains the stronger all-length projector hypothesis.  Under normalized
BNT-refined horizontal form, `hasNoPeriodicVectors_verticalTensor_of_horizontalCF`
uses the same invariant projector at one noncommuting length.  This horizontal
hypothesis is stronger than literal CPSV canonical form. -/
theorem hasNoPeriodicVectors_verticalTensor_of_cyclicProjector
    (M : MPOTensor d D) (hM : IsMPDO M)
    (hCyc : PeriodicVectorYieldsCyclicProjector M) :
    MPSTensor.HasNoPeriodicVectors (verticalTensor M) :=
  hasNoPeriodicVectors_verticalTensor M hM
    (periodicVectorYieldsProjector_of_cyclic M hM hCyc)

end MPOTensor
