/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import QICLean.MPS.Core.Injectivity
import QICLean.Kraus.Wielandt.SpanGrowth.CumulativeSpan
import QICLean.MPS.Core.Word

/-!
# Cumulative word spans and TN injectivity

For an MPS tensor $A$, the exact word span $S_n(A)$ contains products of
length $n$, while the cumulative span $T_n(A)$ contains products of length at
most $n$. This file also relates these spaces to block injectivity and
normality.
-/

open scoped Matrix

namespace MPSTensor

variable {d D : ℕ}

/-! ### Word spans -/

/-- The span of all products of exactly `n` matrices from `A`. -/
def wordSpan (A : MPSTensor d D) (n : ℕ) :
    Submodule ℂ (Matrix (Fin D) (Fin D) ℂ) :=
  Kraus.wordSpan A n

/-- Every evaluated word belongs to the exact span at its length. -/
theorem evalWord_mem_wordSpan (A : MPSTensor d D) (w : List (Fin d)) :
    evalWord A w ∈ wordSpan A w.length :=
  Kraus.evalWord_mem_wordSpan A w

/-- Evaluation of a nonempty word splits into its first letter and suffix. -/
theorem evalWord_ofFn_succ (A : MPSTensor d D) {n : ℕ}
    (σ : Fin (n + 1) → Fin d) :
    evalWord A (List.ofFn σ) =
      A (σ 0) * evalWord A (List.ofFn (σ ∘ Fin.succ)) :=
  Kraus.evalWord_ofFn_succ A σ

/-- Every word of length `n + 1` factors through its first letter. -/
theorem wordSpan_succ_le_mul (A : MPSTensor d D) (n : ℕ) :
    wordSpan A (n + 1) ≤ Submodule.span ℂ (Set.range A) * wordSpan A n :=
  Kraus.wordSpan_succ_le_mul A n

/-- The length-`n + 1` word span factors by its first letter. -/
theorem wordSpan_succ_eq_mul_left (A : MPSTensor d D) (n : ℕ) :
    wordSpan A (n + 1) = Submodule.span ℂ (Set.range A) * wordSpan A n :=
  Kraus.wordSpan_succ_eq_mul_left A n

/-- The span of all products of at most `n` matrices from `A`. -/
def cumulativeSpan (A : MPSTensor d D) (n : ℕ) :
    Submodule ℂ (Matrix (Fin D) (Fin D) ℂ) :=
  Kraus.cumulativeSpan A n

/-- Every word of length at most `n` belongs to the cumulative span. -/
theorem mem_cumulativeSpan_generator (A : MPSTensor d D) {n : ℕ}
    {w : List (Fin d)} (hw : w.length ≤ n) :
    evalWord A w ∈ cumulativeSpan A n :=
  Kraus.mem_cumulativeSpan_generator A hw

/-- Exact word spans lie in every sufficiently large cumulative span. -/
theorem wordSpan_le_cumulativeSpan (A : MPSTensor d D) {m n : ℕ} (h : m ≤ n) :
    wordSpan A m ≤ cumulativeSpan A n :=
  Kraus.wordSpan_le_cumulativeSpan A h

/-- Cumulative word spans increase with the length bound. -/
theorem cumulativeSpan_mono (A : MPSTensor d D) (n : ℕ) :
    cumulativeSpan A n ≤ cumulativeSpan A (n + 1) :=
  Kraus.cumulativeSpan_mono A n

/-- Cumulative word spans are monotone in their length bound. -/
theorem cumulativeSpan_mono' (A : MPSTensor d D) {n m : ℕ} (h : n ≤ m) :
    cumulativeSpan A n ≤ cumulativeSpan A m :=
  Kraus.cumulativeSpan_mono' A h

/-- Stabilization makes the cumulative span invariant under left multiplication. -/
theorem left_mul_mem_cumulativeSpan (A : MPSTensor d D) {n : ℕ}
    (hstab : wordSpan A (n + 1) ≤ cumulativeSpan A n)
    (i : Fin d) (X : Matrix (Fin D) (Fin D) ℂ)
    (hX : X ∈ cumulativeSpan A n) :
    A i * X ∈ cumulativeSpan A n :=
  Kraus.left_mul_mem_cumulativeSpan A hstab i X hX

/-- Equality at consecutive lengths forces equality at all later lengths. -/
theorem cumulativeSpan_stable (A : MPSTensor d D) {n : ℕ}
    (h : cumulativeSpan A n = cumulativeSpan A (n + 1)) :
    ∀ m, n ≤ m → cumulativeSpan A m = cumulativeSpan A n :=
  Kraus.cumulativeSpan_stable A h

/-- The dimension of a cumulative word span is at most `D ^ 2`. -/
theorem cumulativeSpan_finrank_le (A : MPSTensor d D) (n : ℕ) :
    Module.finrank ℂ (cumulativeSpan A n) ≤ D ^ 2 :=
  Kraus.cumulativeSpan_finrank_le A n

/-- Strict growth of cumulative spans gives strict growth of dimensions. -/
theorem cumulativeSpan_finrank_strict_mono (A : MPSTensor d D) {n : ℕ}
    (h : cumulativeSpan A n < cumulativeSpan A (n + 1)) :
    Module.finrank ℂ (cumulativeSpan A n) <
      Module.finrank ℂ (cumulativeSpan A (n + 1)) :=
  Kraus.cumulativeSpan_finrank_strict_mono A h

/-- The identity matrix belongs to every cumulative word span. -/
theorem one_mem_cumulativeSpan (A : MPSTensor d D) (n : ℕ) :
    (1 : Matrix (Fin D) (Fin D) ℂ) ∈ cumulativeSpan A n :=
  Kraus.one_mem_cumulativeSpan A n

/-- The zero-length word span is generated by the identity matrix. -/
theorem wordSpan_zero (A : MPSTensor d D) :
    wordSpan A 0 = Submodule.span ℂ {(1 : Matrix (Fin D) (Fin D) ℂ)} :=
  Kraus.wordSpan_zero A

/-- Zero-length words are not full when the bond dimension is at least two. -/
theorem wordSpan_zero_ne_top_of_two_le [NeZero D]
    (A : MPSTensor d D) (hD : 2 ≤ D) :
    wordSpan A 0 ≠ (⊤ : Submodule ℂ (Matrix (Fin D) (Fin D) ℂ)) :=
  Kraus.wordSpan_zero_ne_top_of_two_le A hD

/-! ### Injectivity and normality -/

/-- Block injectivity at a positive length propagates to the next length. -/
theorem isNBlkInjective_succ_of_isNBlkInjective
    (A : MPSTensor d D) {L : ℕ} (hLpos : 0 < L)
    (hL : IsNBlkInjective A L) :
    IsNBlkInjective A (L + 1) := by
  change wordSpan A L = ⊤ at hL
  change wordSpan A (L + 1) = ⊤
  obtain ⟨n, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hLpos)
  have hprev_le : wordSpan A n ≤ wordSpan A (n + 1) := by
    rw [hL]
    exact le_top
  rw [wordSpan_succ_eq_mul_left A (n + 1)]
  apply eq_top_iff.mpr
  calc
    ⊤ = wordSpan A (n + 1) := hL.symm
    _ = Submodule.span ℂ (Set.range A) * wordSpan A n :=
      wordSpan_succ_eq_mul_left A n
    _ ≤ Submodule.span ℂ (Set.range A) * wordSpan A (n + 1) :=
      mul_le_mul' le_rfl hprev_le

/-- Block injectivity at a positive length propagates to every greater length. -/
theorem isNBlkInjective_of_le {A : MPSTensor d D} {L m : ℕ}
    (hLpos : 0 < L) (hL : IsNBlkInjective A L) (hLm : L ≤ m) :
    IsNBlkInjective A m := by
  induction m, hLm using Nat.le_induction with
  | base => exact hL
  | succ m hLm ih =>
      exact isNBlkInjective_succ_of_isNBlkInjective A
        (lt_of_lt_of_le hLpos hLm) ih

/-- Exact word-span fullness is block injectivity. -/
theorem wordSpan_eq_top_iff_isNBlkInjective (A : MPSTensor d D) (N : ℕ) :
    wordSpan A N = ⊤ ↔ IsNBlkInjective A N :=
  Iff.rfl

/-- Normality implies fullness of a cumulative word span. -/
theorem cumulativeSpan_eq_top_of_isNormal (A : MPSTensor d D)
    (hN : IsNormal A) : ∃ N, cumulativeSpan A N = ⊤ := by
  obtain ⟨N, _hNpos, hN⟩ := hN
  exact ⟨N, eq_top_iff.mpr (le_trans
    (eq_top_iff.mp ((wordSpan_eq_top_iff_isNBlkInjective A N).mpr hN))
    (wordSpan_le_cumulativeSpan A le_rfl))⟩

/-- Zero-block injectivity forces one-dimensional bond space. -/
theorem bondDim_eq_one_of_isNBlkInjective_zero [NeZero D]
    (A : MPSTensor d D) (hA : IsNBlkInjective A 0) :
    D = 1 := by
  by_contra hD_ne
  have hD_pos : 0 < D := NeZero.pos D
  have hD_ge : 2 ≤ D := by omega
  have htop : wordSpan A 0 =
      (⊤ : Submodule ℂ (Matrix (Fin D) (Fin D) ℂ)) :=
    (wordSpan_eq_top_iff_isNBlkInjective A 0).mpr hA
  exact wordSpan_zero_ne_top_of_two_le A hD_ge htop

end MPSTensor
