/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.FinOrderedProduct
import TNLean.MPS.Preparation.Sequential

/-!
# Sequential generation without an ancilla

A chain of `N ≥ 2` sites, each `ℂ^d` and initially in `|0⟩`, is acted on first
by an operation `U^{[1]}` on sites `1` and `2`, then by `U^{[2]}` on sites `2`
and `3`, and so on up to `U^{[N-1]}` on sites `N - 1` and `N`
(arXiv:quant-ph/0608197, section "Sequential generation without ancilla",
lines 1580--1586). The scheme is deterministic when every `U^{[k]}` is unitary and
probabilistic when the operations are arbitrary, the generated state then being
taken up to normalization.

## Indexing

As in `TNLean.MPS.Preparation.Sequential`, configurations `τ : Fin N → Fin d` are
indexed by ket position: source site `j` sits at position `N - j`. The operation
`U k` is the source's `U^{[k+1]}`, a matrix on `ℂ^d ⊗ ℂ^d` whose first tensor
factor is site `k + 1` and whose second is site `k + 2`. The chain length is
written `N = n + 2`.

**Local fix (N ≥ 2):** the scheme presupposes two sites, since its first operation
acts on sites `1` and `2`; read literally at `N = 1` it generates only `|0⟩`, and
the theorem fails. The statements here are for `N ≥ 2`, where the scheme is
defined as printed. Documented in
`docs/paper-gaps/pgvwc07_sequential_no_ancilla_two_sites.tex`.

## The generated state

Before `U^{[k]}` acts, the sites `k + 1, …, N` have not been touched and are still
in `|0⟩`, and after it site `k` is never touched again. Hence the chain state
after `U^{[k]}` is `|χ_k⟩ ⊗ |0⟩^{⊗(N-k-1)}`, where `χ_k` is a vector on sites
`1, …, k + 1`, `χ_1 = U^{[1]}|0,0⟩` and
`χ_k(…, i, β) = ∑_α ⟨i, β| U^{[k]} |α, 0⟩ χ_{k-1}(…, α)`. The definition
`MPSPreparation.noAncillaState` is this recursion.

## Main results

* `MPSPreparation.noAncillaState_eq_eval` — the identification
  of the site matrices with `⟨i, β| U^{[k]} |α, 0⟩` in the proof in the source
  (lines 1597--1603), as an ordered matrix product. The source writes these
  entries `A^{[k]}_{i,α,β}`; in the ket-position product used here they are the
  entries `(β, α)` of `MPSPreparation.pairStep`.
* `MPSPreparation.isProbabilisticallyGeneratedWithoutAncilla_iff` and
  `MPSPreparation.isDeterministicallyGeneratedWithoutAncilla_iff` — Theorem
  "Sequential generation without ancilla" (lines 1587--1593): the generated
  states are exactly the open-boundary MPS of bond dimension at most `d`,
  normalized in the deterministic case.

For the converse the source runs the deterministic scheme with an ancilla using
site `k + 1` as the ancilla and swapping sites. Here the converse is proved
directly: the successive decompositions of arXiv:quant-ph/0501096,
eq. `induction`, applied from the left end, give isometries `ℂ^d → ℂ^d ⊗ ℂ^d`
whose bond space is the next site, and their unitary extensions are the
operations `U^{[k]}`.

## References

* Pérez-García, Verstraete, Wolf, Cirac, *Matrix product state representations*,
  arXiv:quant-ph/0608197, lines 1580--1616 of
  `Papers/quant-ph_0608197/MPSarchive.tex`.
* Schön, Solano, Verstraete, Cirac, Wolf, *Sequential generation of entangled
  multiqubit states*, arXiv:quant-ph/0501096, eq. `induction`.
-/

open scoped Matrix

namespace MPSPreparation

open MPSChainTensor (eval eval_succ eval_succ')

variable {d : ℕ} [NeZero d]

/-! ### The scheme -/

/-- The chain state generated by the operations `U^{[1]}, …, U^{[n+1]}` on the
chain of `n + 2` sites in `|0⟩^{⊗(n+2)}` (arXiv:quant-ph/0608197, lines
1580--1586), at the ket-position configuration `τ`. The last operation `U^{[n+1]}`
acts on the sites at positions `1` and `0`, the first of which carries the
output `α` of the earlier operations; see the module docstring. -/
def noAncillaState : ∀ (n : ℕ), (Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ) →
    (Fin (n + 2) → Fin d) → ℂ
  | 0, U, τ => U 0 (τ 1, τ 0) (0, 0)
  | n + 1, U, τ => ∑ α, U (Fin.last (n + 1)) (τ 1, τ 0) (α, 0) *
      noAncillaState n (fun k => U k.castSucc) (Fin.cons α fun p => τ p.succ.succ)

/-- The probabilistic sequential scheme without ancilla of arXiv:quant-ph/0608197,
lines 1580--1586: `ψ` is the (unnormalized) state produced by arbitrary
operations `U^{[1]}, …, U^{[n+1]}` on neighboring sites. -/
def IsProbabilisticallyGeneratedWithoutAncilla {n : ℕ} (ψ : (Fin (n + 2) → Fin d) → ℂ) :
    Prop :=
  ∃ U : Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ, ψ = noAncillaState n U

/-- The deterministic sequential scheme without ancilla of arXiv:quant-ph/0608197,
lines 1580--1586: `ψ` is the state produced by unitaries `U^{[1]}, …, U^{[n+1]}`
on neighboring sites. -/
def IsDeterministicallyGeneratedWithoutAncilla {n : ℕ} (ψ : (Fin (n + 2) → Fin d) → ℂ) :
    Prop :=
  ∃ U : Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ,
    (∀ k, U k ∈ Matrix.unitaryGroup (Fin d × Fin d) ℂ) ∧ ψ = noAncillaState n U

/-- The site matrices `A_{i,βα} = ⟨i, β| U |α, 0⟩` of an operation on two
neighboring sites, arXiv:quant-ph/0608197, lines 1597--1600. The row index `β` is
the state passed to the next site, the column index `α` the state received from
the previous one. -/
def pairStep (U : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ) : Fin d → Matrix (Fin d) (Fin d) ℂ :=
  fun i β α => U (i, β) (α, 0)

/-- The generated state is an ordered matrix product with site matrices
`A^{[k]}_{i,βα} = ⟨i, β| U^{[k]} |α, 0⟩` (`MPSPreparation.pairStep`),
arXiv:quant-ph/0608197, lines 1597--1603, where the source writes the same entry
as `A^{[k]}_{i,α,β}`, with the received index `α` first. The source makes this identification for `k < N - 1` and obtains
the matrices of the last two sites from a singular value decomposition of
`U^{[N-1]}`; here all operations are treated uniformly, the first site of the ket
(position `0`) is read off from the output vector, and the input at the other
end is `|0⟩`. -/
theorem noAncillaState_eq_eval :
    ∀ (n : ℕ) (U : Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ)
      (τ : Fin (n + 2) → Fin d),
      noAncillaState n U τ =
        (eval (fun p => pairStep (U (Fin.rev p))) (fun p => τ p.succ) *ᵥ
          basisVecZero d) (τ 0)
  | 0, U, τ => by
    have hd : 0 < d := Nat.pos_of_neZero d
    rw [noAncillaState, mulVec_basisVecZero_apply hd]
    simp only [eval, Fin.prod_succ, Fin.prod_zero, Matrix.mul_one]
    rfl
  | n + 1, U, τ => by
    rw [noAncillaState]
    simp only [noAncillaState_eq_eval n, Fin.cons_zero, Fin.cons_succ]
    rw [eval_succ (fun p => pairStep (U (Fin.rev p))), ← Matrix.mulVec_mulVec]
    simp only [Fin.rev_zero, Fin.rev_succ]
    rw [Matrix.mulVec, dotProduct]
    rfl

/-! ### Generated states are open-boundary states -/

/-- A state of the form `τ ↦ (M₀(τ₁) ⋯ M_n(τ_{n+1}) v)(τ₀)` has an
open-boundary representation of bond dimension at most `d`: position `0` is
the boundary site `⟨τ₀|`. -/
theorem hasOBCRep_of_eq_eval {n : ℕ} (M : Fin (n + 1) → Fin d → Matrix (Fin d) (Fin d) ℂ)
    (v : Fin d → ℂ) {ψ : (Fin (n + 2) → Fin d) → ℂ}
    (h : ∀ τ, ψ τ = (eval M (fun p => τ p.succ) *ᵥ v) (τ 0)) : HasOBCRep d ψ := by
  classical
  have hd : 0 < d := Nat.pos_of_neZero d
  let P : Fin (n + 2) → Fin d → Matrix (Fin d) (Fin d) ℂ :=
    Fin.cons (fun j => rowMat (Pi.single j 1)) M
  obtain ⟨b, Q, r', hb0, hbD, -, hrow, hcol, hiso, -, hprod⟩ :=
    exists_isometric_chain (n + 2) 1 hd (rowMat (basisVecZero d))
      (isRowSupportedBelow_rowMat _) P v
  obtain ⟨B, hB, -⟩ := OBCChainTensor.exists_of_isometric_chain b hbD hb0 Q hrow hcol hiso r'
  refine ⟨B, funext fun τ => ?_⟩
  rw [h τ, hB, ← hprod, rowMat_mul_mulVec_zero hd, basisVecZero_dotProduct hd, eval_succ P,
    ← Matrix.mulVec_mulVec]
  simp [P, rowMat, Matrix.mulVec, dotProduct, Pi.single_apply]

/-- Every state generated by a probabilistic sequential scheme without ancilla is
an open-boundary MPS of bond dimension at most `d`: the forward direction of
Theorem "Sequential generation without ancilla" (arXiv:quant-ph/0608197,
lines 1587--1603). -/
theorem hasOBCRep_of_isProbabilisticallyGeneratedWithoutAncilla {n : ℕ}
    {ψ : (Fin (n + 2) → Fin d) → ℂ} (h : IsProbabilisticallyGeneratedWithoutAncilla ψ) :
    HasOBCRep d ψ := by
  obtain ⟨U, rfl⟩ := h
  exact hasOBCRep_of_eq_eval _ _ fun τ => noAncillaState_eq_eval n U τ

/-- The site matrices of a unitary satisfy `∑_i A_i^† A_i = 1`. -/
theorem isIsometryOn_pairStep {U : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ}
    (hU : U ∈ Matrix.unitaryGroup (Fin d × Fin d) ℂ) : IsIsometryOn d (pairStep U) := by
  intro α α' _ _
  have h := congrFun (congrFun (Matrix.mem_unitaryGroup_iff'.mp hU) (α, 0)) (α', 0)
  simp only [Matrix.mul_apply, Matrix.star_apply, Matrix.one_apply, Prod.mk.injEq, and_true,
    Fintype.sum_prod_type] at h
  rw [← h]
  rfl

omit [NeZero d] in
/-- The squared norm of a state `τ ↦ (w (τ₁, …))(τ₀)`. -/
theorem star_dotProduct_self_of_eq {n : ℕ} {ψ : (Fin (n + 2) → Fin d) → ℂ}
    (w : (Fin (n + 1) → Fin d) → Fin d → ℂ) (h : ∀ τ, ψ τ = w (fun p => τ p.succ) (τ 0)) :
    star ψ ⬝ᵥ ψ = ∑ τ', star (w τ') ⬝ᵥ w τ' := by
  rw [dotProduct]
  simp only [Pi.star_apply, h]
  exact Fintype.sum_fin_succ_pi (fun j τ' => star (w τ' j) * w τ' j)

/-- The states generated by the deterministic scheme without ancilla are
normalized (arXiv:quant-ph/0608197, lines 1580--1586: unitary operations on the
normalized initial product state). -/
theorem star_dotProduct_self_of_isDeterministicallyGeneratedWithoutAncilla {n : ℕ}
    {ψ : (Fin (n + 2) → Fin d) → ℂ} (h : IsDeterministicallyGeneratedWithoutAncilla ψ) :
    star ψ ⬝ᵥ ψ = 1 := by
  have hd : 0 < d := Nat.pos_of_neZero d
  obtain ⟨U, hU, rfl⟩ := h
  rw [star_dotProduct_self_of_eq
      (fun τ' => eval (fun p => pairStep (U (Fin.rev p))) τ' *ᵥ basisVecZero d)
      (noAncillaState_eq_eval n U),
    sum_normSq_eval_mulVec (fun _ => d) (fun p => pairStep (U (Fin.rev p)))
      (fun _ _ α _ hα => absurd α.isLt (by omega)) (fun p => isIsometryOn_pairStep (hU _))
      _ (fun β hβ => absurd β.isLt (by omega)),
    star_basisVecZero_dotProduct_self hd]

/-! ### Open-boundary states are generated -/

omit [NeZero d] in
/-- The successive decompositions of arXiv:quant-ph/0501096, eq. `induction`,
run on an open-boundary MPS of bond dimension at most `d` after its boundary
site at position `0`: the state is `τ ↦ (Q₀(τ₁) ⋯ Q_n(τ_{n+1}) r')(τ₀)` with
every `Q_p` isometric on its bond block. -/
theorem exists_isometric_chain_of_hasOBCRep {n : ℕ} {ψ : (Fin (n + 2) → Fin d) → ℂ}
    (h : HasOBCRep d ψ) :
    ∃ (b : Fin (n + 2) → ℕ) (Q : Fin (n + 1) → Fin d → Matrix (Fin d) (Fin d) ℂ)
      (r' : Fin d → ℂ),
      (∀ p i, IsRowSupportedBelow (b p.castSucc) (Q p i)) ∧
      (∀ p, IsIsometryOn (b p.succ) (Q p)) ∧ IsSupportedBelow (b (Fin.last (n + 1))) r' ∧
      ∀ τ, ψ τ = (eval Q (fun p => τ p.succ) *ᵥ r') (τ 0) := by
  obtain ⟨B, rfl⟩ := h
  have hd := B.bondBound_pos
  let Rm : Matrix (Fin d) (Fin d) ℂ := fun j γ => OBCChainTensor.zeroPad B 0 j ⟨0, hd⟩ γ
  obtain ⟨b, Q, r', -, -, -, hrow, -, hiso, hr', hprod⟩ :=
    exists_isometric_chain (n + 1) d le_rfl Rm (fun α _ hα => absurd α.isLt (by omega))
      (fun p => OBCChainTensor.zeroPad B p.succ) (basisVecZero d)
  refine ⟨b, Q, r', hrow, hiso, hr', fun τ => ?_⟩
  rw [← hprod, OBCChainTensor.coeff_eq_eval_zeroPad, eval_succ (OBCChainTensor.zeroPad B),
    mulVec_basisVecZero_apply hd,
    Matrix.mul_apply, Matrix.mul_apply]

/-- The chain of site matrices of operations `V p` equals the isometric chain `Q`
applied to `r'`, when `V p` agrees with `Q p` on the used bond block and the
operation at the far end (the first one applied) prepares `Q_n(i) r'` from
`|0⟩`. -/
theorem eval_pairStep_mulVec {n : ℕ} (b : Fin (n + 2) → ℕ)
    (Q : Fin (n + 1) → Fin d → Matrix (Fin d) (Fin d) ℂ)
    (hrow : ∀ p i, IsRowSupportedBelow (b p.castSucc) (Q p i)) (r' : Fin d → ℂ)
    (V : Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ)
    (hV : ∀ (p : Fin n) i β α, α.val < b p.succ.castSucc →
      pairStep (V p.castSucc) i β α = Q p.castSucc i β α)
    (hlast : ∀ i, pairStep (V (Fin.last n)) i *ᵥ basisVecZero d = Q (Fin.last n) i *ᵥ r')
    (τ' : Fin (n + 1) → Fin d) :
    eval (fun p => pairStep (V p)) τ' *ᵥ basisVecZero d = eval Q τ' *ᵥ r' := by
  rw [eval_succ', eval_succ' Q, ← Matrix.mulVec_mulVec, ← Matrix.mulVec_mulVec, hlast]
  exact eval_mulVec_congr (fun k => b k.castSucc) (fun p => Q p.castSucc)
    (fun p => pairStep (V p.castSucc)) (fun p i => hrow p.castSucc i)
    (fun p i β α hα => hV p i β α hα) _ ((hrow (Fin.last n) _).mulVec r') _

/-- Swapping the two output factors of an operation on `ℂ^d ⊗ ℂ^d`. -/
def swapRows (U : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ) :
    Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ :=
  fun x y => U x.swap y

omit [NeZero d] in
/-- Swapping the output factors preserves unitarity. -/
theorem swapRows_mem_unitaryGroup {U : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ}
    (hU : U ∈ Matrix.unitaryGroup (Fin d × Fin d) ℂ) :
    swapRows U ∈ Matrix.unitaryGroup (Fin d × Fin d) ℂ := by
  rw [Matrix.mem_unitaryGroup_iff'] at hU ⊢
  ext y z
  have h := congrFun (congrFun hU y) z
  rw [Matrix.mul_apply] at h ⊢
  rw [← h]
  exact Fintype.sum_equiv (Equiv.prodComm _ _) _ _ fun x => rfl

/-- Every open-boundary MPS of bond dimension at most `d` is generated by a
probabilistic sequential scheme without ancilla: the converse direction of
Theorem "Sequential generation without ancilla" for the probabilistic scheme
(arXiv:quant-ph/0608197, lines 1587--1593). -/
theorem isProbabilisticallyGeneratedWithoutAncilla_of_hasOBCRep {n : ℕ}
    {ψ : (Fin (n + 2) → Fin d) → ℂ} (h : HasOBCRep d ψ) :
    IsProbabilisticallyGeneratedWithoutAncilla ψ := by
  classical
  have hd : 0 < d := Nat.pos_of_neZero d
  obtain ⟨b, Q, r', hrow, -, -, hψ⟩ := exists_isometric_chain_of_hasOBCRep h
  let V : Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ := fun p x y =>
    if p = Fin.last n then (Q p x.1 *ᵥ r') x.2 else Q p x.1 x.2 y.1
  refine ⟨fun k => V (Fin.rev k), funext fun τ => ?_⟩
  rw [hψ, noAncillaState_eq_eval]
  simp only [Fin.rev_rev]
  rw [eval_pairStep_mulVec b Q hrow r' V (fun p i β α _ => by
      simp [V, pairStep, Fin.castSucc_ne_last]) (fun i => ?_)]
  funext β
  rw [mulVec_basisVecZero_apply hd]
  simp [V, pairStep]

/-- Every normalized open-boundary MPS of bond dimension at most `d` is generated
by a deterministic sequential scheme without ancilla: the converse direction of
Theorem "Sequential generation without ancilla" (arXiv:quant-ph/0608197,
lines 1587--1593 and 1605--1616). The operations are unitary extensions of the
isometries produced by the successive decompositions. -/
theorem isDeterministicallyGeneratedWithoutAncilla_of_hasOBCRep {n : ℕ}
    {ψ : (Fin (n + 2) → Fin d) → ℂ} (hψn : star ψ ⬝ᵥ ψ = 1) (h : HasOBCRep d ψ) :
    IsDeterministicallyGeneratedWithoutAncilla ψ := by
  classical
  have hd : 0 < d := Nat.pos_of_neZero d
  obtain ⟨b, Q, r', hrow, hiso, hr', hψ⟩ := exists_isometric_chain_of_hasOBCRep h
  have hr'n : star r' ⬝ᵥ r' = 1 := by
    rw [← hψn, star_dotProduct_self_of_eq (fun τ' => eval Q τ' *ᵥ r') hψ]
    exact (sum_normSq_eval_mulVec b Q hrow hiso r' hr').symm
  -- The first operation prepares `Q_n(i) r'` from `|0, 0⟩`.
  have hisoLast : IsIsometryOn 1 (fun i => Q (Fin.last n) i * colMat r') := by
    intro β β' hβ hβ'
    obtain rfl : β = ⟨0, hd⟩ := Fin.ext (Nat.lt_one_iff.mp hβ)
    obtain rfl : β' = ⟨0, hd⟩ := Fin.ext (Nat.lt_one_iff.mp hβ')
    simp only [mul_colMat_apply _ _ _ (⟨0, hd⟩ : Fin d) rfl]
    have h := sum_normSq_mulVec_of_isIsometryOn (hiso (Fin.last n))
      (v := r') (by rw [Fin.succ_last]; exact hr')
    rw [hr'n] at h
    simpa [dotProduct] using h
  have hext : ∀ p : Fin (n + 1), ∃ V ∈ Matrix.unitaryGroup (Fin d × Fin d) ℂ,
      (p ≠ Fin.last n → ∀ i β α, α.val < b p.succ → pairStep V i β α = Q p i β α) ∧
      (p = Fin.last n → ∀ i, pairStep V i *ᵥ basisVecZero d = Q p i *ᵥ r') := by
    intro p
    by_cases hp : p = Fin.last n
    · subst hp
      obtain ⟨U, hU, hUQ⟩ := exists_unitary_extension hisoLast
      refine ⟨swapRows U, swapRows_mem_unitaryGroup hU, fun h => absurd rfl h, fun _ i => ?_⟩
      funext β
      rw [mulVec_basisVecZero_apply hd]
      have := hUQ i β ⟨0, hd⟩ (by simp)
      rw [mul_colMat_apply _ _ _ _ rfl] at this
      simpa [pairStep, swapRows] using this
    · obtain ⟨U, hU, hUQ⟩ := exists_unitary_extension (hiso p)
      exact ⟨swapRows U, swapRows_mem_unitaryGroup hU,
        fun _ i β α hα => by simpa [pairStep, swapRows] using hUQ i β α hα,
        fun h => absurd h hp⟩
  choose V hV hVQ hVlast using hext
  refine ⟨fun k => V (Fin.rev k), fun k => hV _, funext fun τ => ?_⟩
  rw [hψ, noAncillaState_eq_eval]
  simp only [Fin.rev_rev]
  rw [eval_pairStep_mulVec b Q hrow r' V (fun p i β α hα => hVQ p.castSucc
    (Fin.castSucc_ne_last p) i β α (by rwa [Fin.succ_castSucc])) (hVlast _ rfl)]

/-- **Theorem "Sequential generation without ancilla", probabilistic scheme**
(arXiv:quant-ph/0608197, lines 1587--1593): on a chain of at least two sites, a
vector is generated, up to normalization, by a probabilistic sequential scheme
without ancilla iff it has an open-boundary MPS representation of bond dimension
at most `d`. -/
theorem isProbabilisticallyGeneratedWithoutAncilla_iff {n : ℕ}
    {ψ : (Fin (n + 2) → Fin d) → ℂ} :
    IsProbabilisticallyGeneratedWithoutAncilla ψ ↔ HasOBCRep d ψ :=
  ⟨hasOBCRep_of_isProbabilisticallyGeneratedWithoutAncilla,
    isProbabilisticallyGeneratedWithoutAncilla_of_hasOBCRep⟩

/-- **Theorem "Sequential generation without ancilla", deterministic scheme**
(arXiv:quant-ph/0608197, lines 1587--1593): on a chain of at least two sites, a
vector is generated by a deterministic sequential scheme without ancilla iff it
is normalized and has an open-boundary MPS representation of bond dimension at
most `d`. -/
theorem isDeterministicallyGeneratedWithoutAncilla_iff {n : ℕ}
    {ψ : (Fin (n + 2) → Fin d) → ℂ} :
    IsDeterministicallyGeneratedWithoutAncilla ψ ↔ star ψ ⬝ᵥ ψ = 1 ∧ HasOBCRep d ψ := by
  refine ⟨fun h => ⟨star_dotProduct_self_of_isDeterministicallyGeneratedWithoutAncilla h,
    hasOBCRep_of_isProbabilisticallyGeneratedWithoutAncilla ?_⟩,
    fun ⟨hn, h⟩ => isDeterministicallyGeneratedWithoutAncilla_of_hasOBCRep hn h⟩
  obtain ⟨U, -, rfl⟩ := h
  exact ⟨U, rfl⟩

end MPSPreparation
