/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.Preparation.CutRank
import TNLean.MPS.Preparation.SequentialTransition
import TNLean.Algebra.StackedIsometryCard

/-!
# Bond dimensions and minimal resources of sequential generation

After the successive-decomposition recipe of Schön, Solano, Verstraete, Cirac,
and Wolf (arXiv:quant-ph/0501096, eq. `induction`), the source bounds the size of
the isometries it produces: "Simple rank considerations show that
`V'_{[n-k]}` has dimension `2min[D,2^k] × min[D,2^{k+1}]`" (lines 200--202 of
`References/quant-ph_0501096/PhotoMPS.tex`, for qubits). This file proves the
statement for local dimension `d`, together with the mirror bound obtained by
running the recipe once from each end.

## Site order

The source writes the state as `⟨φ_F| V~_{[n]} ⋯ V~_{[1]} |φ_I⟩` (tilde over `V`) and starts the
decompositions at the `φ_F` end, with the `2 × 2` matrix `V'_{[n]}`. An
`OBCChainTensor` is read from site `0` to site `N - 1`, and
`OBCChainTensor.exists_isometric_coeff_eq` starts its sweep at site `0`, so site
`k` here is the source's `V'_{[n-k]}`, and the bond `k` of the chain (between
sites `k - 1` and `k`) is the bond of `V'_{[n-k]}` on the `φ_F` side. The source's
bound `min[D, 2^k]` therefore counts the `k` sites between that bond and the end
where the sweep starts: in the chain, bond `k` has dimension at most
`min(D, d^k)`.

## Main results

* `OBCChainTensor.bondDim_succ_le_mul` — a site with `∑_i A_i^† A_i = 1` has
  right bond at most `d` times its left bond; this is the rank consideration.
* `OBCChainTensor.bondDim_le_pow` — in an open chain whose sites except the last
  satisfy `∑_i A_i^† A_i = 1`, bond `k` has dimension at most `d^k`.
* `OBCChainTensor.exists_isometric_coeff_eq_le_pow` — the representation of
  `exists_isometric_coeff_eq` obeys the source's bound `min(D, d^k)`.
* `OBCChainTensor.reverse`, `OBCChainTensor.coeff_reverse` — reading an open
  chain from the other end.
* `OBCChainTensor.exists_isometric_coeff_eq_le_min` — running the recipe first
  from the right end and then from the left end gives a representation with the
  same isometric sites whose bond `k` is at most
  `min(D_k, d^k, d^{N-k})`, where `D_k ≤ D` is the bond of the given chain.
* `MPSPreparation.hasOBCRep_iff_cutRank_le` — on a chain of positive length and
  for `D ≥ 1`, a vector is an open-boundary MPS of bond dimension at most `D` iff
  its cut ranks are all at most `D`.
* `MPSPreparation.isProbabilisticallyGenerated_iff_cutRank_le`,
  `MPSPreparation.isDeterministicallyGenerated_iff_cutRank_le` — on a chain of
  positive length, the states generated with a `D`-dimensional ancilla are
  exactly those whose cut ranks are all at most `D` (normalized, in the
  deterministic case).
* `MPSPreparation.isLeast_isProbabilisticallyGenerated`,
  `MPSPreparation.isLeast_isDeterministicallyGenerated` — **minimal resources**:
  the least ancilla dimension that generates a state is its largest cut rank.
* `MPSPreparation.hasOBCRep_pow_half` and its corollaries
  `isProbabilisticallyGenerated_pow_half`, `isDeterministicallyGenerated_pow_half`,
  `isTransitionGenerated_pow_half` — for `d ≥ 1`, every state of `N ≥ 1` sites is
  an open-boundary MPS of bond dimension at most `d^{⌊N/2⌋}` and is generated by
  the probabilistic scheme with an ancilla of that dimension, and every normalized
  state is generated with it by the deterministic and the transition schemes.

## The printed size and minimal resources

The printed size `2min[D,2^k] × min[D,2^{k+1}]` is an upper bound and is not
minimal for low-rank states: a product state has cut rank one at every cut, so it
has a representation with all bonds one (a representation of the printed size
also exists, by adding unused virtual directions). The "minimal resources" of
arXiv:quant-ph/0608197, lines 1574--1577, are formalized through the cut ranks of
`TNLean.MPS.Preparation.CutRank`: the representation of
`OBCChainTensor.exists_coeff_eq_of_cutRank_le`, obtained by successive Schmidt
decompositions of the state, has every bond equal to the cut rank, and no
representation has a smaller bond at any cut.

**Scope restriction (existence part of `thm:OBC-Vidal`):** `hasOBCRep_pow_half` and its
corollaries prove that every state has an open-boundary representation with bond dimension at
most `d^{⌊N/2⌋}`; the gauge conditions 1--3 of arXiv:quant-ph/0608197, Theorem `thm:OBC-Vidal`
(lines 431--442), are not formalized. Both points are documented in
`docs/paper-gaps/ssvcw05_sequential_bond_upper_bound_scope.tex`
(https://sirui-lu.com/TNLean/paper-gaps/ssvcw05_sequential_bond_upper_bound_scope.pdf).

## References

* Schön, Solano, Verstraete, Cirac, Wolf, *Sequential generation of entangled
  multiqubit states*, Phys. Rev. Lett. 95, 110503 (2005), arXiv:quant-ph/0501096,
  eq. `induction` and lines 184--186 and 200--203 of
  `References/quant-ph_0501096/PhotoMPS.tex`.
* Pérez-García, Verstraete, Wolf, Cirac, *Matrix product state representations*,
  arXiv:quant-ph/0608197, lines 431--458 (Theorem `thm:OBC-Vidal`) and 1574--1577 of
  `Papers/quant-ph_0608197/MPSarchive.tex`: the proof of Theorem `Thm:seqwith`
  "also provides a \emph{recipe} for the generation of any given state (with
  minimal resources)".
-/

open scoped Matrix

namespace OBCChainTensor

variable {d D N : ℕ}

/-- A site of an open chain with `∑_i A_i^† A_i = 1` has right bond at most `d`
times its left bond, by `Matrix.card_le_mul_of_sum_conjTranspose_mul_eq_one`.

This is the step behind "Simple rank considerations show that `V'_{[n-k]}` has
dimension `2min[D,2^k] × min[D,2^{k+1}]`", arXiv:quant-ph/0501096, lines
200--202 of `References/quant-ph_0501096/PhotoMPS.tex`, for local dimension
`d`. -/
theorem bondDim_succ_le_mul (B : OBCChainTensor d D N) (p : Fin N)
    (hp : ∑ i, (B.tensor p i)ᴴ * B.tensor p i = 1) :
    B.bondDim p.succ ≤ B.bondDim p.castSucc * d :=
  Matrix.card_le_mul_of_sum_conjTranspose_mul_eq_one (B.tensor p) hp

/-- **Bond growth from the start of the sweep.** In an open chain of positive
local dimension whose sites, except possibly the last, satisfy
`∑_i A_i^† A_i = 1`, bond `k` has dimension at most `d^k`.

This is the bound `min[D, 2^k]` of arXiv:quant-ph/0501096, lines 200--202 of
`References/quant-ph_0501096/PhotoMPS.tex`, for local dimension `d`, in the site
order of `OBCChainTensor` (see the module docstring). -/
theorem bondDim_le_pow [NeZero d] {n : ℕ} (B : OBCChainTensor d D (n + 1))
    (hiso : ∀ p : Fin (n + 1), p ≠ Fin.last n → ∑ i, (B.tensor p i)ᴴ * B.tensor p i = 1)
    (k : Fin (n + 2)) : B.bondDim k ≤ d ^ (k : ℕ) := by
  induction k using Fin.induction with
  | zero => simp [B.left_dim]
  | succ p ih =>
    by_cases hp : p = Fin.last n
    · subst hp
      rw [Fin.succ_last, B.right_dim]
      exact Nat.one_le_pow _ _ (Nat.pos_of_ne_zero (NeZero.ne d))
    · calc B.bondDim p.succ ≤ B.bondDim p.castSucc * d := B.bondDim_succ_le_mul p (hiso p hp)
        _ ≤ d ^ (p : ℕ) * d := Nat.mul_le_mul_right _ (by simpa using ih)
        _ = d ^ ((p.succ : Fin (n + 2)) : ℕ) := by simp [pow_succ]

/-- **Resources of the successive-decomposition recipe.** Every open-boundary
chain state of positive local dimension has an open-boundary representation in
which every site except the last satisfies `∑_i A_i^† A_i = 1` and bond `k` has
dimension at most `min(D_k, d^k)`, where `D_k ≤ D` is the bond of the given
chain.

This is the recipe of arXiv:quant-ph/0501096, eq. `induction`, with the bound
"`V'_{[n-k]}` has dimension `2min[D,2^k] × min[D,2^{k+1}]`" (lines 200--202 of
`References/quant-ph_0501096/PhotoMPS.tex`) for local dimension `d`; bond `k` of
the chain is the `φ_F`-side bond of the source's `V'_{[n-k]}`. -/
theorem exists_isometric_coeff_eq_le_pow [NeZero d] {n : ℕ} (B : OBCChainTensor d D (n + 1)) :
    ∃ B' : OBCChainTensor d D (n + 1), B'.coeff = B.coeff ∧
      (∀ k, B'.bondDim k ≤ B.bondDim k) ∧ (∀ k, B'.bondDim k ≤ d ^ (k : ℕ)) ∧
      ∀ p : Fin (n + 1), p ≠ Fin.last n → ∑ i, (B'.tensor p i)ᴴ * B'.tensor p i = 1 := by
  obtain ⟨B', hB', hbond, hiso⟩ := B.exists_isometric_coeff_eq
  exact ⟨B', hB', hbond, B'.bondDim_le_pow hiso, hiso⟩

/-- The open chain read from the other end: bond `k` is the bond `N - k` of the
given chain, and the site matrices are transposed. This auxiliary operation is
not in the sources; it is used to run the recipe of arXiv:quant-ph/0501096,
eq. `induction`, starting from the other end of the chain. -/
def reverse (B : OBCChainTensor d D N) : OBCChainTensor d D N where
  bondDim k := B.bondDim k.rev
  bondDim_le k := B.bondDim_le _
  left_dim := by simpa using B.right_dim
  right_dim := by simpa using B.left_dim
  tensor p i α β :=
    B.tensor p.rev i (Fin.cast (by rw [Fin.rev_succ]) β) (Fin.cast (by rw [Fin.rev_castSucc]) α)

/-- Bond `k` of the reversed chain is bond `N - k` of the given chain. -/
@[simp] theorem bondDim_reverse (B : OBCChainTensor d D N) (k : Fin (N + 1)) :
    B.reverse.bondDim k = B.bondDim k.rev := rfl

/-- The coefficients of the reversed chain are those of the given chain at the
reversed configuration. -/
theorem coeff_reverse (B : OBCChainTensor d D N) (σ : Fin N → Fin d) :
    B.reverse.coeff σ = B.coeff fun p => σ p.rev := by
  let e : ((k : Fin (N + 1)) → Fin (B.bondDim k)) ≃
      ((k : Fin (N + 1)) → Fin (B.bondDim k.rev)) :=
    { toFun := fun β k => β k.rev
      invFun := fun α k => Fin.cast (by rw [Fin.rev_rev]) (α k.rev)
      left_inv := fun β => by
        funext k
        have key : ∀ {q q' : Fin (N + 1)} (h : q = q') (hc : B.bondDim q = B.bondDim q'),
            Fin.cast hc (β q) = β q' := by
          rintro _ _ rfl _; rfl
        exact key (Fin.rev_rev k) _
      right_inv := fun α => by
        funext k
        have key : ∀ q, q = k → ∀ (hc : B.bondDim q.rev = B.bondDim k.rev),
            Fin.cast hc (α q) = α k := by
          rintro q rfl hc; rfl
        exact key k.rev.rev (Fin.rev_rev k) _ }
  refine (Fintype.sum_equiv e _ _ fun β => ?_).symm
  rw [← Equiv.prod_comp (Fin.revPerm : Equiv.Perm (Fin N))]
  refine Finset.prod_congr rfl fun p _ => ?_
  have key : ∀ {q q' : Fin (N + 1)} (h : q = q') (hc : B.bondDim q = B.bondDim q'),
      Fin.cast hc (β q) = β q' := by
    rintro _ _ rfl _; rfl
  simp only [Fin.revPerm_apply, Fin.rev_rev, reverse, e, Equiv.coe_fn_mk]
  rw [key (Fin.rev_succ p) _, key (Fin.rev_castSucc p) _]
  rfl

/-- **Resources of the recipe run from both ends.** Every open-boundary chain
state of positive local dimension has an open-boundary representation in which
every site except the last satisfies `∑_i A_i^† A_i = 1` and bond `k` has
dimension at most `min(D_k, d^k, d^{N-k})`, where `D_k ≤ D` is the bond of the
given chain and `N = n + 1` is the length.

The bound `d^k` is the one of arXiv:quant-ph/0501096, lines 200--202 of
`References/quant-ph_0501096/PhotoMPS.tex`, counted from the end where the
sweep starts. The bound `d^{N-k}` comes from first running the same recipe from
the other end; the source states only the one-sided bound. -/
theorem exists_isometric_coeff_eq_le_min [NeZero d] {n : ℕ} (B : OBCChainTensor d D (n + 1)) :
    ∃ B' : OBCChainTensor d D (n + 1), B'.coeff = B.coeff ∧
      (∀ k, B'.bondDim k ≤ B.bondDim k) ∧ (∀ k, B'.bondDim k ≤ d ^ (k : ℕ)) ∧
      (∀ k : Fin (n + 2), B'.bondDim k ≤ d ^ (n + 1 - k)) ∧
      ∀ p : Fin (n + 1), p ≠ Fin.last n → ∑ i, (B'.tensor p i)ᴴ * B'.tensor p i = 1 := by
  obtain ⟨C, hC, hCbond, hCpow, -⟩ := B.reverse.exists_isometric_coeff_eq_le_pow
  obtain ⟨B', hB', hbond, hpow, hiso⟩ := C.reverse.exists_isometric_coeff_eq_le_pow
  refine ⟨B', ?_, fun k => ?_, hpow, fun k => ?_, hiso⟩
  · funext σ
    rw [hB', coeff_reverse, hC, coeff_reverse]
    simp
  · refine (hbond k).trans ?_
    simpa using hCbond k.rev
  · refine (hbond k).trans ?_
    simpa [Fin.val_rev] using hCpow k.rev

end OBCChainTensor

/-! ### Minimal resources -/

namespace MPSPreparation

variable {d D N : ℕ}

/-- **Open-boundary representations from cut ranks.** On a chain of positive length, a vector
is an open-boundary MPS of positive bond dimension at most `D` iff all its cut ranks are at most
`D`: arXiv:quant-ph/0608197, lines 456--458 ("any state for which `max_m rank(ρ_m) ≤ D` can be
written as a MPS of bond dimension `D`"), together with its converse. -/
theorem hasOBCRep_iff_cutRank_le (hN : 0 < N) (hD : 0 < D) {ψ : (Fin N → Fin d) → ℂ} :
    HasOBCRep D ψ ↔ ∀ k : Fin (N + 1), cutRank ψ k ≤ D := by
  constructor
  · rintro ⟨B, rfl⟩ k
    exact (B.cutRank_coeff_le k).trans (B.bondDim_le k)
  · intro h
    by_cases hψ : ψ = 0
    · subst hψ
      exact hasOBCRep_zero hN hD
    · obtain ⟨n, rfl⟩ : ∃ n, N = n + 1 := ⟨N - 1, by omega⟩
      obtain ⟨B, hB, -⟩ := OBCChainTensor.exists_coeff_eq_of_cutRank_le hψ h
      exact ⟨B, hB.symm⟩

/-- **Probabilistic generation from cut ranks.** On a chain of positive length, a vector is
generated by a probabilistic sequential scheme with a `D`-dimensional ancilla iff all its cut
ranks are at most `D` (arXiv:quant-ph/0608197, Theorem `Thm:seqwith` and lines 456--458). -/
theorem isProbabilisticallyGenerated_iff_cutRank_le (hN : 0 < N) {ψ : (Fin N → Fin d) → ℂ} :
    IsProbabilisticallyGenerated D ψ ↔ ∀ k : Fin (N + 1), cutRank ψ k ≤ D := by
  rcases Nat.eq_zero_or_pos D with rfl | hD
  · constructor
    · rintro ⟨A, φI, φF, rfl⟩ k
      have h0 : seqAmplitude φF φI A = 0 := funext fun τ => by simp [seqAmplitude, dotProduct]
      rw [h0, cutRank, show cutMatrix (0 : (Fin N → Fin d) → ℂ) k = 0 from rfl,
        Matrix.rank_zero]
    · intro h
      have hψ : ψ = 0 := by
        by_contra hψ
        have := h 0
        rw [Fin.val_zero, cutRank_zero_eq_one hψ] at this
        omega
      exact ⟨fun _ _ => 0, 0, 0, funext fun τ => by simp [hψ, seqAmplitude, dotProduct]⟩
  · rw [isProbabilisticallyGenerated_iff hN hD, hasOBCRep_iff_cutRank_le hN hD]

/-- **Deterministic generation from cut ranks.** On a chain of positive length, a vector is
generated by a deterministic sequential scheme with a `D`-dimensional ancilla iff it is
normalized and all its cut ranks are at most `D` (arXiv:quant-ph/0608197, Theorem `Thm:seqwith`
and lines 456--458). -/
theorem isDeterministicallyGenerated_iff_cutRank_le [NeZero d] (hN : 0 < N)
    {ψ : (Fin N → Fin d) → ℂ} :
    IsDeterministicallyGenerated D ψ ↔ star ψ ⬝ᵥ ψ = 1 ∧ ∀ k : Fin (N + 1), cutRank ψ k ≤ D := by
  constructor
  · intro h
    exact ⟨star_dotProduct_self_of_isDeterministicallyGenerated h,
      (isProbabilisticallyGenerated_iff_cutRank_le hN).mp
        (isProbabilisticallyGenerated_of_isDeterministicallyGenerated h)⟩
  · rintro ⟨hn, h⟩
    exact (isDeterministicallyGenerated_iff_isProbabilisticallyGenerated hn).mpr
      ((isProbabilisticallyGenerated_iff_cutRank_le hN).mpr h)

/-- **Minimal resources, probabilistic scheme.** On a chain of positive length, the least
dimension of an ancilla that generates a vector by a probabilistic sequential scheme is its
largest cut rank: the "minimal resources" of arXiv:quant-ph/0608197, lines 1574--1577. -/
theorem isLeast_isProbabilisticallyGenerated (hN : 0 < N) (ψ : (Fin N → Fin d) → ℂ) :
    IsLeast {D | IsProbabilisticallyGenerated D ψ}
      (Finset.univ.sup fun k : Fin (N + 1) => cutRank ψ k) :=
  ⟨(isProbabilisticallyGenerated_iff_cutRank_le hN).mpr fun k =>
      Finset.le_sup (f := fun k : Fin (N + 1) => cutRank ψ k) (Finset.mem_univ k),
    fun _ hD => Finset.sup_le fun k _ => (isProbabilisticallyGenerated_iff_cutRank_le hN).mp hD k⟩

/-- **Minimal resources, deterministic scheme.** On a chain of positive length, the least
dimension of an ancilla that generates a normalized vector by a deterministic sequential scheme
is its largest cut rank: the "minimal resources" of arXiv:quant-ph/0608197, lines 1574--1577. -/
theorem isLeast_isDeterministicallyGenerated [NeZero d] (hN : 0 < N)
    {ψ : (Fin N → Fin d) → ℂ} (hψ : star ψ ⬝ᵥ ψ = 1) :
    IsLeast {D | IsDeterministicallyGenerated D ψ}
      (Finset.univ.sup fun k : Fin (N + 1) => cutRank ψ k) :=
  ⟨(isDeterministicallyGenerated_iff_cutRank_le hN).mpr ⟨hψ, fun k =>
      Finset.le_sup (f := fun k : Fin (N + 1) => cutRank ψ k) (Finset.mem_univ k)⟩,
    fun _ hD => Finset.sup_le fun k _ =>
      ((isDeterministicallyGenerated_iff_cutRank_le hN).mp hD).2 k⟩

/-! ### Every state is sequentially generated -/

/-- **Every state is an open-boundary MPS.** Every vector on `N ≥ 1` sites has an open-boundary
representation of bond dimension at most `d^{⌊N/2⌋}`: the existence part of
arXiv:quant-ph/0608197, Theorem `thm:OBC-Vidal` (lines 431--434), and the premise of
arXiv:quant-ph/0501096, lines 184--186 ("every state has a MPS representation"). -/
theorem hasOBCRep_pow_half [NeZero d] (hN : 0 < N) (ψ : (Fin N → Fin d) → ℂ) :
    HasOBCRep (d ^ (N / 2)) ψ :=
  (hasOBCRep_iff_cutRank_le hN (pow_pos (NeZero.pos d) _)).mpr fun k => cutRank_le_pow_half ψ k

/-- **Every state is probabilistically generated** with an ancilla of dimension `d^{⌊N/2⌋}`:
the "general recipe for its sequential generation" of arXiv:quant-ph/0501096, lines 184--186. -/
theorem isProbabilisticallyGenerated_pow_half [NeZero d] (hN : 0 < N)
    (ψ : (Fin N → Fin d) → ℂ) : IsProbabilisticallyGenerated (d ^ (N / 2)) ψ :=
  (isProbabilisticallyGenerated_iff_cutRank_le hN).mpr fun k => cutRank_le_pow_half ψ k

/-- **Every normalized state is deterministically generated** with an ancilla of dimension
`d^{⌊N/2⌋}` (arXiv:quant-ph/0501096, lines 184--186; arXiv:quant-ph/0608197,
Theorem `Thm:seqwith` and Theorem `thm:OBC-Vidal`). -/
theorem isDeterministicallyGenerated_pow_half [NeZero d] (hN : 0 < N)
    {ψ : (Fin N → Fin d) → ℂ} (hψ : star ψ ⬝ᵥ ψ = 1) :
    IsDeterministicallyGenerated (d ^ (N / 2)) ψ :=
  (isDeterministicallyGenerated_iff_cutRank_le hN).mpr ⟨hψ, fun k => cutRank_le_pow_half ψ k⟩

/-- **Every normalized state is generated by a transition scheme** with ancilla
`ℂ^{d^{⌊N/2⌋}} ⊗ ℂ^d` (arXiv:quant-ph/0501096, lines 184--186 and 412--415;
arXiv:quant-ph/0608197, Theorem `Thm:seqwith`). -/
theorem isTransitionGenerated_pow_half [NeZero d] (hN : 0 < N)
    {ψ : (Fin N → Fin d) → ℂ} (hψ : star ψ ⬝ᵥ ψ = 1) :
    IsTransitionGenerated (d ^ (N / 2)) ψ :=
  isTransitionGenerated_iff_isDeterministicallyGenerated.mpr
    (isDeterministicallyGenerated_pow_half hN hψ)

end MPSPreparation
