/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.FinOrderedProduct
import TNLean.Algebra.UnitaryMulVecInner
import TNLean.MPS.Preparation.Sequential
import Mathlib.LinearAlgebra.Matrix.Kronecker

/-!
# The deterministic transition scheme for sequential generation

For qubit chains (`d = 2`) the third sequential scheme of
arXiv:quant-ph/0608197 (lines 1555--1567) enlarges the ancilla to
`ℂ^D ⊗ ℂ^2 = ℂ^D ⊕ ℂ^D`, the second factor being a tag qubit, and fixes the
interaction between ancilla and site to
\[
  |\varphi\rangle|1\rangle|0\rangle_B \mapsto |\varphi\rangle|0\rangle|1\rangle_B,
  \qquad
  |\varphi\rangle|0\rangle|0\rangle_B \mapsto |\varphi\rangle|0\rangle|0\rangle_B .
\]
Arbitrary unitaries on the ancilla are allowed in every step, and the ancilla
must decouple after the last step. In arXiv:quant-ph/0501096 this interaction is
the "`D`-standard map" `T`, which "effectively interchanges the tag-qubit with the
time-bin qubit", and a step is the operation of eq. `IsofromT`,
`V|φ⟩ = ⟨0|_T T (U_A (|φ⟩|0⟩_T) |0⟩_B)`.

This file treats sites of any local dimension `d`, as in arXiv:quant-ph/0501096,
lines 412--415 ("the presented ideas and proofs apply to any multi-qudit state with
`H_B ≅ ℂ^d`"): the tag is a qudit, the ancilla is `ℂ^D ⊗ ℂ^d`, and the fixed
interaction sends `|φ⟩|t⟩|0⟩_B ↦ |φ⟩|0⟩|t⟩_B` for every tag `t`. For `d = 2` this is the
interaction of the source (`MPSPreparation.isTransitionInteraction_two_iff`).

Since every site starts in `|0⟩`, only the action of the interaction on site
inputs `|0⟩` enters. A step with ancilla unitary `W` therefore acts as the
operation `transitionStep W i`, sending the ancilla state `|y⟩` to
`∑_x (transitionStep W i) x y |x⟩` with the site in `|i⟩`
(`transitionStep_eq_of_isTransitionInteraction`).

## Main definitions

* `MPSPreparation.IsTransitionInteraction` — the fixed interaction of the source.
* `MPSPreparation.transitionStep` — one step of the scheme on a site in `|0⟩`.
* `MPSPreparation.IsTransitionGenerated` — scheme 3 of the source.

## Main results

* `MPSPreparation.isTransitionGenerated_iff_isDeterministicallyGenerated` — the
  transition scheme with ancilla `ℂ^D ⊗ ℂ^d` and the deterministic scheme with a
  `D`-dimensional ancilla generate the same vectors.
* `MPSPreparation.isTransitionGenerated_iff` — the transition part of Theorem
  `Thm:seqwith` (lines 1569--1573): on a chain of positive length, a vector is
  generated by the deterministic transition scheme with ancilla `ℂ^D ⊗ ℂ^d` iff
  it is normalized and an open-boundary MPS of bond dimension at most `D`.

The proof passes through the deterministic scheme with a `D`-dimensional ancilla
(`MPSPreparation.isDeterministicallyGenerated_iff`). After the interaction the
tag is always `|0⟩`, so only a `D`-dimensional part of the ancilla carries
the bond; conversely, a unitary `U` on ancilla ⊗ site is realized by the ancilla
unitary `U` on `ℂ^D ⊗ ℂ^d` followed by the interaction, which is the argument
around arXiv:quant-ph/0501096, eq. `IsofromT`.

**Local fix (N ≥ 1):** `isTransitionGenerated_iff` is stated for chains of
positive length. On the empty chain the only open-boundary coefficient is the
empty product `1`, while a generated vector is any scalar of modulus one, so the set
equality of arXiv:quant-ph/0608197, Theorem `Thm:seqwith` (lines 1569--1573),
which carries no bound on `N`, is read for `N ≥ 1`. Documented in
`docs/paper-gaps/pgvwc07_sequential_with_ancilla_positive_length.tex`
(https://sirui-lu.com/TNLean/paper-gaps/pgvwc07_sequential_with_ancilla_positive_length.pdf).

## References

* Pérez-García, Verstraete, Wolf, Cirac, *Matrix product state representations*,
  arXiv:quant-ph/0608197, lines 1555--1573 of
  `Papers/quant-ph_0608197/MPSarchive.tex`.
* Schön, Solano, Verstraete, Cirac, Wolf, *Sequential generation of entangled
  multiqubit states*, arXiv:quant-ph/0501096, eq. `IsofromT` and the paragraph
  around it, and lines 412--415 of `References/quant-ph_0501096/PhotoMPS.tex`.
-/

open scoped Matrix Kronecker

namespace MPSPreparation

open MPSChainTensor (eval_succ')

variable {d D N : ℕ}

/-! ### The fixed interaction and one step -/

/-- The vector `|φ⟩|t⟩|j⟩` of ancilla `ℂ^D`, tag qudit, and site qudit. -/
def ancillaTagSiteVec (φ : Fin D → ℂ) (t j : Fin d) : (Fin D × Fin d) × Fin d → ℂ :=
  fun x => if x.1.2 = t ∧ x.2 = j then φ x.1.1 else 0

/-- The fixed interaction of the deterministic transition scheme for sites `ℂ^d`
with a tag qudit: `|φ⟩|t⟩|0⟩ ↦ |φ⟩|0⟩|t⟩` for every tag `t`, the interchange of the
tag with the site of arXiv:quant-ph/0501096 (the `D`-standard map `T`, extended to
qudits as in lines 412--415). For `d = 2` this is the interaction
`|φ⟩|1⟩|0⟩ ↦ |φ⟩|0⟩|1⟩`, `|φ⟩|0⟩|0⟩ ↦ |φ⟩|0⟩|0⟩` of arXiv:quant-ph/0608197,
lines 1560--1566 (`MPSPreparation.isTransitionInteraction_two_iff`). The action on
site inputs other than `|0⟩` is not specified by the sources and plays no role,
since every site starts in `|0⟩`. -/
def IsTransitionInteraction [NeZero d]
    (T : Matrix ((Fin D × Fin d) × Fin d) ((Fin D × Fin d) × Fin d) ℂ) : Prop :=
  ∀ (φ : Fin D → ℂ) (t : Fin d), T *ᵥ ancillaTagSiteVec φ t 0 = ancillaTagSiteVec φ 0 t

/-- For qubits the interaction is the one printed in arXiv:quant-ph/0608197,
lines 1560--1566: `|φ⟩|1⟩|0⟩ ↦ |φ⟩|0⟩|1⟩` and `|φ⟩|0⟩|0⟩ ↦ |φ⟩|0⟩|0⟩`. -/
theorem isTransitionInteraction_two_iff
    {T : Matrix ((Fin D × Fin 2) × Fin 2) ((Fin D × Fin 2) × Fin 2) ℂ} :
    IsTransitionInteraction T ↔ ∀ φ : Fin D → ℂ,
      T *ᵥ ancillaTagSiteVec φ 1 0 = ancillaTagSiteVec φ 0 1 ∧
        T *ᵥ ancillaTagSiteVec φ 0 0 = ancillaTagSiteVec φ 0 0 := by
  refine ⟨fun h φ => ⟨h φ 1, h φ 0⟩, fun h φ t => ?_⟩
  fin_cases t
  · exact (h φ).2
  · exact (h φ).1

/-- One step of the deterministic transition scheme on a site in `|0⟩`: the
ancilla unitary `W` followed by the fixed interaction, with the site left in
`|i⟩`. Its entries are `⟨x, i| T (W ⊗ 1) |y, 0⟩`
(`transitionStep_eq_of_isTransitionInteraction`); this is the operation of
arXiv:quant-ph/0501096, eq. `IsofromT`, before the projection on the tag qudit. -/
def transitionStep [NeZero d] (W : Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ) (i : Fin d) :
    Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ :=
  fun x y => if x.2 = 0 then W (x.1, i) y else 0

/-- The step `transitionStep W` is the fixed interaction after the ancilla
unitary, applied to a site in `|0⟩` (arXiv:quant-ph/0608197, lines 1560--1567;
arXiv:quant-ph/0501096, eq. `IsofromT`). -/
theorem transitionStep_eq_of_isTransitionInteraction [NeZero d]
    {T : Matrix ((Fin D × Fin d) × Fin d) ((Fin D × Fin d) × Fin d) ℂ}
    (hT : IsTransitionInteraction T) (W : Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ)
    (i : Fin d) (x y : Fin D × Fin d) :
    (T * (W ⊗ₖ (1 : Matrix (Fin d) (Fin d) ℂ))) (x, i) (y, 0) = transitionStep W i x y := by
  classical
  -- The columns of `T` at site input `|0⟩`.
  have hcol : ∀ (z : Fin D × Fin d), T (x, i) (z, 0) =
      if x.2 = 0 ∧ x.1 = z.1 ∧ i = z.2 then 1 else 0 := by
    rintro ⟨α, t⟩
    have h := congrFun (hT (Pi.single α 1) t) (x, i)
    have hlhs : (T *ᵥ ancillaTagSiteVec (Pi.single α 1) t 0) (x, i) = T (x, i) ((α, t), 0) := by
      rw [Matrix.mulVec, dotProduct, Finset.sum_eq_single ((α, t), 0)]
      · simp [ancillaTagSiteVec]
      · rintro ⟨⟨α', t'⟩, j⟩ _ hne
        simp only [ancillaTagSiteVec]
        split_ifs with h1
        · obtain ⟨rfl, rfl⟩ := h1
          by_cases hα : α' = α
          · subst hα; exact absurd rfl hne
          · simp [hα]
        · simp
      · simp
    rw [hlhs] at h
    rw [h]
    simp only [ancillaTagSiteVec, Pi.single_apply]
    by_cases h0 : x.2 = 0 <;> by_cases h1 : x.1 = α <;> by_cases h2 : i = t <;>
      simp [h0, h1, h2]
  rw [Matrix.mul_apply, Fintype.sum_prod_type, Finset.sum_congr rfl fun z _ =>
    Finset.sum_eq_single (0 : Fin d) (fun j _ hj => by
      simp [Matrix.kroneckerMap_apply, hj]) (by simp)]
  simp only [hcol, Matrix.kroneckerMap_apply, Matrix.one_apply_eq, mul_one, transitionStep]
  split_ifs with h0
  · rw [Finset.sum_eq_single (x.1, i)]
    · simp [h0]
    · rintro ⟨α, t⟩ _ hne
      have : ¬(x.2 = 0 ∧ x.1 = α ∧ i = t) := by
        rintro ⟨-, h1, h2⟩
        exact hne (Prod.ext h1.symm h2.symm)
      simp [this]
    · simp
  · simp [h0]

/-- The joint state of ancilla `ℂ^D ⊗ ℂ^d` after the steps with ancilla
unitaries `W^{[1]}, …, W^{[N]}`, starting from `|φ_I⟩ ⊗ |0⟩^{⊗N}`: the ancilla
component at the ket-position configuration `τ`, in the indexing of
`MPSPreparation.jointState` (`W k` is the unitary of step `k + 1`). -/
def transitionJointState [NeZero d] (W : Fin N → Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ)
    (φI : Fin D × Fin d → ℂ) (τ : Fin N → Fin d) : Fin D × Fin d → ℂ :=
  Fin.prod (fun p => transitionStep (W (Fin.rev p)) (τ p)) *ᵥ φI

/-- Scheme 3 of arXiv:quant-ph/0608197 (deterministic transition schemes,
lines 1555--1567), with sites `ℂ^d` and a tag qudit as in arXiv:quant-ph/0501096,
lines 412--415: the ancilla `ℂ^D ⊗ ℂ^d` starts in a normalized state `φ_I`, every
step is an arbitrary ancilla unitary `W^{[k]}` followed by the fixed interaction,
and after the last step the joint state factorizes as `|φ_F⟩ ⊗ |ψ⟩` with `φ_F`
normalized. For `d = 2` this is the scheme of the source. -/
def IsTransitionGenerated [NeZero d] (D : ℕ) (ψ : (Fin N → Fin d) → ℂ) : Prop :=
  ∃ (W : Fin N → Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ) (φI φF : Fin D × Fin d → ℂ),
    (∀ k, W k ∈ Matrix.unitaryGroup (Fin D × Fin d) ℂ) ∧ star φI ⬝ᵥ φI = 1 ∧
      star φF ⬝ᵥ φF = 1 ∧ ∀ τ, transitionJointState W φI τ = ψ τ • φF

/-! ### Factoring a step through the tag-zero subspace -/

/-- The embedding `ℂ^D → ℂ^D ⊗ ℂ^d`, `|φ⟩ ↦ |φ⟩|0⟩`. -/
private def tagZeroEmbed [NeZero d] (D : ℕ) : Matrix (Fin D × Fin d) (Fin D) ℂ :=
  fun x β => if x.2 = 0 ∧ x.1 = β then 1 else 0

/-- The rows `(α, i)` of an ancilla unitary, as a map `ℂ^D ⊗ ℂ^d → ℂ^D`. -/
private def rowsAt (W : Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ) (i : Fin d) :
    Matrix (Fin D) (Fin D × Fin d) ℂ :=
  fun α y => W (α, i) y

/-- A step factors as `S_i(W) = E R_i` through the tag-zero embedding `E`,
`E|φ⟩ = |φ⟩|0⟩`, with `(R_i)_{α,y} = W_{(α,i),y}`. -/
private theorem transitionStep_eq_mul [NeZero d] (W : Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ)
    (i : Fin d) :
    transitionStep W i = tagZeroEmbed D * rowsAt W i := by
  ext x y
  rw [Matrix.mul_apply, Finset.sum_eq_single x.1]
  · by_cases h : x.2 = 0 <;> simp [transitionStep, tagZeroEmbed, rowsAt, h]
  · intro β _ hβ
    simp [tagZeroEmbed, Ne.symm hβ]
  · simp

/-- On the tag-zero subspace the rows `R_i` of `W` give the step matrices of
the deterministic scheme: `R_i E` is `MPSPreparation.stepMatrix W i`. -/
private theorem rowsAt_mul_tagZeroEmbed [NeZero d] (W : Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ)
    (i : Fin d) :
    rowsAt W i * tagZeroEmbed D = stepMatrix W i := by
  ext α β
  rw [Matrix.mul_apply, Finset.sum_eq_single (β, 0)]
  · simp [tagZeroEmbed, rowsAt, stepMatrix]
  · rintro ⟨γ, t⟩ _ hne
    have : ¬(t = 0 ∧ γ = β) := by
      rintro ⟨h1, h2⟩
      exact hne (Prod.ext h2 h1)
    simp [tagZeroEmbed, this]
  · simp

/-- The coordinates of `E v = |v⟩|0⟩`. -/
private theorem tagZeroEmbed_mulVec_apply [NeZero d] (v : Fin D → ℂ) (x : Fin D × Fin d) :
    (tagZeroEmbed (d := d) D *ᵥ v) x = if x.2 = 0 then v x.1 else 0 := by
  rw [Matrix.mulVec, dotProduct, Finset.sum_eq_single x.1]
  · by_cases h : x.2 = 0 <;> simp [tagZeroEmbed, h]
  · intro β _ hβ
    simp [tagZeroEmbed, Ne.symm hβ]
  · simp

/-- The tag-zero embedding `E` is an isometry: `‖E v‖² = ‖v‖²`. -/
private theorem star_tagZeroEmbed_mulVec_dotProduct [NeZero d] (v : Fin D → ℂ) :
    star (tagZeroEmbed (d := d) D *ᵥ v) ⬝ᵥ (tagZeroEmbed D *ᵥ v) = star v ⬝ᵥ v := by
  simp only [dotProduct, Fintype.sum_prod_type, Pi.star_apply, tagZeroEmbed_mulVec_apply]
  refine Finset.sum_congr rfl fun α _ => ?_
  rw [Finset.sum_eq_single (0 : Fin d) (fun t _ ht => by simp [ht]) (by simp)]
  simp

/-! ### From the transition scheme to the deterministic scheme -/

/-- Every state generated by the transition scheme is generated by the
deterministic scheme with a `D`-dimensional ancilla: after the interaction the
tag qudit is `|0⟩`, so the bond lives in `ℂ^D ⊗ |0⟩` (arXiv:quant-ph/0608197,
lines 1555--1573; arXiv:quant-ph/0501096, eq. `IsofromT`). -/
theorem isDeterministicallyGenerated_of_isTransitionGenerated [NeZero d]
    {ψ : (Fin N → Fin d) → ℂ}
    (h : IsTransitionGenerated D ψ) : IsDeterministicallyGenerated D ψ := by
  classical
  obtain ⟨W, φI, φF, hW, hI, hF, hJ⟩ := h
  have hD : 0 < D := by
    rcases Nat.eq_zero_or_pos D with h0 | h0
    · subst h0; simp [dotProduct] at hI
    · exact h0
  cases N with
  | zero =>
    have hφ : φI = ψ Fin.elim0 • φF := by
      have := hJ Fin.elim0
      simpa [transitionJointState] using this
    have hψ : star (ψ Fin.elim0) * ψ Fin.elim0 = 1 := by
      rw [← hI, hφ, star_smul, smul_dotProduct, dotProduct_smul, hF]
      simp [mul_comm]
    refine ⟨fun k => Fin.elim0 k, ψ Fin.elim0 • basisVecZero D, basisVecZero D,
      fun k => Fin.elim0 k, ?_, star_basisVecZero_dotProduct_self hD, fun τ => ?_⟩
    · rw [star_smul_basisVecZero_dotProduct_self hD, hψ]
    · rw [show τ = Fin.elim0 from Subsingleton.elim _ _]
      simp [jointState]
  | succ n =>
    -- The first step acts on `φ_I`; its output lies in `ℂ^D ⊗ |0⟩`.
    let v : Fin d → Fin D → ℂ := fun i => rowsAt (W 0) i *ᵥ φI
    have hv : ∑ i, star (v i) ⬝ᵥ v i = 1 := by
      rw [← hI, ← Matrix.star_mulVec_dotProduct_mulVec_of_mem_unitary (hW 0) φI φI, dotProduct,
        Fintype.sum_prod_type, Finset.sum_comm]
      rfl
    have hiso : IsIsometryOn 1 (fun i => colMat (v i)) := by
      intro β β' hβ hβ'
      obtain rfl : β = ⟨0, hD⟩ := Fin.ext (Nat.lt_one_iff.mp hβ)
      obtain rfl : β' = ⟨0, hD⟩ := Fin.ext (Nat.lt_one_iff.mp hβ')
      simpa [colMat, dotProduct] using hv
    obtain ⟨U₀, hU₀, hU₀v⟩ := exists_unitary_extension hiso
    let U : Fin (n + 1) → Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ :=
      fun k => if k = 0 then U₀ else W k
    have hU : ∀ k, U k ∈ Matrix.unitaryGroup (Fin D × Fin d) ℂ := fun k => by
      simp only [U]; split_ifs
      · exact hU₀
      · exact hW k
    have hfirst : ∀ i, stepMatrix U₀ i *ᵥ basisVecZero D = v i := fun i => by
      funext α
      rw [mulVec_basisVecZero_apply hD]
      simpa [colMat, stepMatrix] using hU₀v i α ⟨0, hD⟩ (by simp)
    -- The transition joint state is the embedding of the `D`-dimensional one.
    have hemb : ∀ τ, transitionJointState W φI τ =
        tagZeroEmbed (d := d) D *ᵥ jointState U (basisVecZero D) τ := fun τ => by
      have hrest : (fun p : Fin n => stepMatrix (U (Fin.rev p.castSucc))) =
          fun p => stepMatrix (W (Fin.rev p.castSucc)) := by
        funext p
        simp [U, Fin.rev_castSucc, Fin.succ_ne_zero]
      rw [jointState, eval_succ', ← Matrix.mulVec_mulVec]
      simp only [hrest, Fin.rev_last, U, ↓reduceIte]
      rw [hfirst, transitionJointState, Fin.prod_succ']
      simp only [transitionStep_eq_mul, Fin.rev_last]
      rw [← Matrix.mul_assoc, Fin.prod_mul_mul_eq, Matrix.mul_assoc, ← Matrix.mulVec_mulVec,
        ← Matrix.mulVec_mulVec]
      simp only [rowsAt_mul_tagZeroEmbed]
      rfl
    -- The `D`-dimensional joint state decouples onto the tag-zero part of `φ_F`.
    let φF' : Fin D → ℂ := fun α => φF (α, 0)
    have hJ' : ∀ τ, jointState U (basisVecZero D) τ = ψ τ • φF' := fun τ => by
      funext α
      have := congrFun (hJ τ) (α, 0)
      rw [hemb, tagZeroEmbed_mulVec_apply] at this
      simpa [φF'] using this
    have hnorm : ∑ τ, star (jointState U (basisVecZero D) τ) ⬝ᵥ
        jointState U (basisVecZero D) τ = 1 := by
      rw [← star_basisVecZero_dotProduct_self hD]
      exact sum_normSq_eval_mulVec (fun _ => D) (fun p => stepMatrix (U (Fin.rev p)))
        (fun _ _ α _ hα => absurd α.isLt (by omega))
        (fun p => isIsometryOn_stepMatrix (hU _)) _ (fun β hβ => absurd β.isLt (by omega))
    obtain ⟨τ₀, hτ₀⟩ : ∃ τ, ψ τ ≠ 0 := by
      by_contra hcon
      simp only [ne_eq, not_exists, not_not] at hcon
      simp [hJ', hcon, dotProduct] at hnorm
    have hF1 : ∀ t ≠ 0, ∀ α, φF (α, t) = 0 := fun t ht α => by
      have := congrFun (hJ τ₀) (α, t)
      rw [hemb, tagZeroEmbed_mulVec_apply, ite_eq_right ht] at this
      simp only [Pi.smul_apply, smul_eq_mul] at this
      exact (mul_eq_zero.mp this.symm).resolve_left hτ₀
    have hF' : star φF' ⬝ᵥ φF' = 1 := by
      rw [← hF, dotProduct, dotProduct, Fintype.sum_prod_type]
      refine Finset.sum_congr rfl fun α _ => ?_
      rw [Finset.sum_eq_single (0 : Fin d) (fun t _ ht => by simp [hF1 t ht]) (by simp)]
      rfl
    exact ⟨U, basisVecZero D, φF', hU, star_basisVecZero_dotProduct_self hD, hF', hJ'⟩

/-! ### From the deterministic scheme to the transition scheme -/

/-- Every state generated by the deterministic scheme with a `D`-dimensional
ancilla is generated by the transition scheme: the unitary `U^{[k]}` on
ancilla ⊗ site is used as the ancilla unitary on `ℂ^D ⊗ ℂ^d` and followed by the
fixed interaction, which moves the tag qudit onto the site
(arXiv:quant-ph/0501096, eq. `IsofromT`; arXiv:quant-ph/0608197, lines
1555--1573). -/
theorem isTransitionGenerated_of_isDeterministicallyGenerated [NeZero d]
    {ψ : (Fin N → Fin d) → ℂ}
    (h : IsDeterministicallyGenerated D ψ) : IsTransitionGenerated D ψ := by
  classical
  obtain ⟨U, φI, φF, hU, hI, hF, hJ⟩ := h
  refine ⟨U, tagZeroEmbed D *ᵥ φI, tagZeroEmbed D *ᵥ φF, hU,
    by rw [star_tagZeroEmbed_mulVec_dotProduct, hI],
    by rw [star_tagZeroEmbed_mulVec_dotProduct, hF], fun τ => ?_⟩
  rw [transitionJointState, Matrix.mulVec_mulVec]
  simp only [transitionStep_eq_mul]
  rw [Fin.prod_mul_mul_eq, ← Matrix.mulVec_mulVec]
  simp only [rowsAt_mul_tagZeroEmbed]
  rw [show Fin.prod (fun p => stepMatrix (U (Fin.rev p)) (τ p)) *ᵥ φI =
    jointState U φI τ from rfl, hJ, Matrix.mulVec_smul]

/-- The deterministic transition scheme with ancilla `ℂ^D ⊗ ℂ^d` and the deterministic scheme
with a `D`-dimensional ancilla generate the same vectors (arXiv:quant-ph/0501096, eq. `IsofromT`
and the paragraph after it; arXiv:quant-ph/0608197, lines 1555--1573). -/
theorem isTransitionGenerated_iff_isDeterministicallyGenerated [NeZero d]
    {ψ : (Fin N → Fin d) → ℂ} :
    IsTransitionGenerated D ψ ↔ IsDeterministicallyGenerated D ψ :=
  ⟨isDeterministicallyGenerated_of_isTransitionGenerated,
    isTransitionGenerated_of_isDeterministicallyGenerated⟩

/-- **Theorem `Thm:seqwith`, deterministic transition scheme**
(arXiv:quant-ph/0608197, lines 1555--1573, with sites `ℂ^d` and a tag qudit as in
arXiv:quant-ph/0501096, lines 412--415): on a chain of positive length, a vector
is generated by the deterministic transition scheme with ancilla `ℂ^D ⊗ ℂ^d` iff it
is normalized and has an open-boundary MPS representation of bond dimension at most
`D`. For `d = 2` this is the statement of the source. -/
theorem isTransitionGenerated_iff [NeZero d] (hN : 0 < N) {ψ : (Fin N → Fin d) → ℂ} :
    IsTransitionGenerated D ψ ↔ star ψ ⬝ᵥ ψ = 1 ∧ HasOBCRep D ψ := by
  rw [isTransitionGenerated_iff_isDeterministicallyGenerated, isDeterministicallyGenerated_iff hN]

end MPSPreparation
