/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.FinOrderedProduct
import TNLean.MPS.Preparation.Sequential
import Mathlib.LinearAlgebra.Matrix.Kronecker

/-!
# The deterministic transition scheme for sequential generation

For qubit chains (`d = 2`) the third sequential scheme of
arXiv:quant-ph/0608197 (lines 1555--1567) enlarges the ancilla to
`ℂ^D ⊗ ℂ^2 = ℂ^D ⊕ ℂ^D`, the second factor being a tag qubit, and fixes the
interaction between ancilla and site to
\[
  |\varphi\rangle|1\rangle|0\rangle_B \mapsto |\varphi\rangle|0\rangle|1\rangle_B,
  \qquad
  |\varphi\rangle|0\rangle|0\rangle_B \mapsto |\varphi\rangle|0\rangle|0\rangle_B .
\]
Arbitrary unitaries on the ancilla are allowed in every step, and the ancilla
must decouple after the last step. In arXiv:quant-ph/0501096 this interaction is
the "`D`-standard map" `T`, and a step is the operation of eq. `IsofromT`,
`V|φ⟩ = ⟨0|_T T (U_A (|φ⟩|0⟩_T) |0⟩_B)`.

Since every site starts in `|0⟩`, only the action of the interaction on site
inputs `|0⟩` enters. A step with ancilla unitary `W` therefore acts as the
operation `transitionStep W i`, sending the ancilla state `|y⟩` to
`∑_x (transitionStep W i) x y |x⟩` with the site in `|i⟩`
(`transitionStep_eq_of_isTransitionInteraction`).

## Main definitions

* `MPSPreparation.IsTransitionInteraction` — the fixed interaction of the source.
* `MPSPreparation.transitionStep` — one step of the scheme on a site in `|0⟩`.
* `MPSPreparation.IsTransitionGenerated` — scheme 3 of the source.

## Main results

* `MPSPreparation.isTransitionGenerated_iff` — the transition part of Theorem
  `Thm:seqwith` (lines 1569--1573): a vector is generated by the deterministic
  transition scheme with ancilla `ℂ^D ⊗ ℂ^2` iff it is normalized and, up to a
  nonzero scalar, an open-boundary MPS of bond dimension at most `D`.

The proof passes through the deterministic scheme with a `D`-dimensional ancilla
(`MPSPreparation.isDeterministicallyGenerated_iff`). After the interaction the
tag qubit is always `|0⟩`, so only a `D`-dimensional part of the ancilla carries
the bond; conversely, a unitary `U` on ancilla ⊗ site is realized by the ancilla
unitary `U` on `ℂ^D ⊗ ℂ^2` followed by the interaction, which is the argument
around arXiv:quant-ph/0501096, eq. `IsofromT`.

## References

* Pérez-García, Verstraete, Wolf, Cirac, *Matrix product state representations*,
  arXiv:quant-ph/0608197, lines 1555--1573 of
  `Papers/quant-ph_0608197/MPSarchive.tex`.
* Schön, Solano, Verstraete, Cirac, Wolf, *Sequential generation of entangled
  multiqubit states*, arXiv:quant-ph/0501096, eq. `IsofromT` and the paragraph
  around it.
-/

open scoped Matrix Kronecker

namespace MPSPreparation

open MPSChainTensor (eval_succ')

variable {D N : ℕ}

/-! ### The fixed interaction and one step -/

/-- The vector `|φ⟩|t⟩|j⟩` of ancilla `ℂ^D`, tag qubit, and site qubit. -/
def ancillaTagSiteVec (φ : Fin D → ℂ) (t j : Fin 2) : (Fin D × Fin 2) × Fin 2 → ℂ :=
  fun x => if x.1.2 = t ∧ x.2 = j then φ x.1.1 else 0

/-- The fixed interaction of the deterministic transition scheme,
arXiv:quant-ph/0608197, lines 1560--1566 (the `D`-standard map `T` of
arXiv:quant-ph/0501096): `|φ⟩|1⟩|0⟩ ↦ |φ⟩|0⟩|1⟩` and `|φ⟩|0⟩|0⟩ ↦ |φ⟩|0⟩|0⟩`.
The action on site inputs `|1⟩` is not specified by the source and plays no role,
since every site starts in `|0⟩`. -/
def IsTransitionInteraction
    (T : Matrix ((Fin D × Fin 2) × Fin 2) ((Fin D × Fin 2) × Fin 2) ℂ) : Prop :=
  ∀ φ : Fin D → ℂ, T *ᵥ ancillaTagSiteVec φ 1 0 = ancillaTagSiteVec φ 0 1 ∧
    T *ᵥ ancillaTagSiteVec φ 0 0 = ancillaTagSiteVec φ 0 0

/-- One step of the deterministic transition scheme on a site in `|0⟩`: the
ancilla unitary `W` followed by the fixed interaction, with the site left in
`|i⟩`. Its entries are `⟨x, i| T (W ⊗ 1) |y, 0⟩`
(`transitionStep_eq_of_isTransitionInteraction`); this is the operation of
arXiv:quant-ph/0501096, eq. `IsofromT`, before the projection on the tag qubit. -/
def transitionStep (W : Matrix (Fin D × Fin 2) (Fin D × Fin 2) ℂ) (i : Fin 2) :
    Matrix (Fin D × Fin 2) (Fin D × Fin 2) ℂ :=
  fun x y => if x.2 = 0 then W (x.1, i) y else 0

/-- The step `transitionStep W` is the fixed interaction after the ancilla
unitary, applied to a site in `|0⟩` (arXiv:quant-ph/0608197, lines 1560--1567;
arXiv:quant-ph/0501096, eq. `IsofromT`). -/
theorem transitionStep_eq_of_isTransitionInteraction
    {T : Matrix ((Fin D × Fin 2) × Fin 2) ((Fin D × Fin 2) × Fin 2) ℂ}
    (hT : IsTransitionInteraction T) (W : Matrix (Fin D × Fin 2) (Fin D × Fin 2) ℂ)
    (i : Fin 2) (x y : Fin D × Fin 2) :
    (T * (W ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ))) (x, i) (y, 0) = transitionStep W i x y := by
  classical
  -- The columns of `T` at site input `|0⟩`.
  have hcol : ∀ (z : Fin D × Fin 2), T (x, i) (z, 0) =
      if x.2 = 0 ∧ x.1 = z.1 ∧ i = z.2 then 1 else 0 := by
    rintro ⟨α, t⟩
    have key : ∀ t' : Fin 2, T *ᵥ ancillaTagSiteVec (Pi.single α 1) t' 0 =
        ancillaTagSiteVec (Pi.single α 1) 0 t' := by
      intro t'
      fin_cases t'
      · exact (hT _).2
      · exact (hT _).1
    have h := congrFun (key t) (x, i)
    have hlhs : (T *ᵥ ancillaTagSiteVec (Pi.single α 1) t 0) (x, i) = T (x, i) ((α, t), 0) := by
      rw [Matrix.mulVec, dotProduct, Finset.sum_eq_single ((α, t), 0)]
      · simp [ancillaTagSiteVec]
      · rintro ⟨⟨α', t'⟩, j⟩ _ hne
        simp only [ancillaTagSiteVec]
        split_ifs with h1
        · obtain ⟨rfl, rfl⟩ := h1
          by_cases hα : α' = α
          · subst hα; exact absurd rfl hne
          · simp [hα]
        · simp
      · simp
    rw [hlhs] at h
    rw [h]
    simp only [ancillaTagSiteVec, Pi.single_apply]
    by_cases h0 : x.2 = 0 <;> by_cases h1 : x.1 = α <;> by_cases h2 : i = t <;>
      simp [h0, h1, h2]
  rw [Matrix.mul_apply, Fintype.sum_prod_type, Finset.sum_congr rfl fun z _ =>
    Finset.sum_eq_single (0 : Fin 2) (fun j _ hj => by
      simp [Matrix.kroneckerMap_apply, hj]) (by simp)]
  simp only [hcol, Matrix.kroneckerMap_apply, Matrix.one_apply_eq, mul_one, transitionStep]
  split_ifs with h0
  · rw [Finset.sum_eq_single (x.1, i)]
    · simp [h0]
    · rintro ⟨α, t⟩ _ hne
      have : ¬(x.2 = 0 ∧ x.1 = α ∧ i = t) := by
        rintro ⟨-, h1, h2⟩
        exact hne (Prod.ext h1.symm h2.symm)
      simp [this]
    · simp
  · simp [h0]

/-- The joint state of ancilla `ℂ^D ⊗ ℂ^2` after the steps with ancilla
unitaries `W^{[1]}, …, W^{[N]}`, starting from `|φ_I⟩ ⊗ |0⟩^{⊗N}`: the ancilla
component at the ket-position configuration `τ`, in the indexing of
`MPSPreparation.jointState` (`W k` is the unitary of step `k + 1`). -/
def transitionJointState (W : Fin N → Matrix (Fin D × Fin 2) (Fin D × Fin 2) ℂ)
    (φI : Fin D × Fin 2 → ℂ) (τ : Fin N → Fin 2) : Fin D × Fin 2 → ℂ :=
  Fin.prod (fun p => transitionStep (W (Fin.rev p)) (τ p)) *ᵥ φI

/-- Scheme 3 of arXiv:quant-ph/0608197 (deterministic transition schemes,
lines 1555--1567), for `d = 2`: the ancilla `ℂ^D ⊗ ℂ^2` starts in a normalized
state `φ_I`, every step is an arbitrary ancilla unitary `W^{[k]}` followed by the
fixed interaction, and after the last step the joint state factorizes as
`|φ_F⟩ ⊗ |ψ⟩` with `φ_F` normalized. -/
def IsTransitionGenerated (D : ℕ) (ψ : (Fin N → Fin 2) → ℂ) : Prop :=
  ∃ (W : Fin N → Matrix (Fin D × Fin 2) (Fin D × Fin 2) ℂ) (φI φF : Fin D × Fin 2 → ℂ),
    (∀ k, W k ∈ Matrix.unitaryGroup (Fin D × Fin 2) ℂ) ∧ star φI ⬝ᵥ φI = 1 ∧
      star φF ⬝ᵥ φF = 1 ∧ ∀ τ, transitionJointState W φI τ = ψ τ • φF

/-! ### Factoring a step through the tag-zero subspace -/

/-- The embedding `ℂ^D → ℂ^D ⊗ ℂ^2`, `|φ⟩ ↦ |φ⟩|0⟩`. -/
def tagZeroEmbed (D : ℕ) : Matrix (Fin D × Fin 2) (Fin D) ℂ :=
  fun x β => if x.2 = 0 ∧ x.1 = β then 1 else 0

/-- The rows `(α, i)` of an ancilla unitary, as a map `ℂ^D ⊗ ℂ^2 → ℂ^D`. -/
def rowsAt (W : Matrix (Fin D × Fin 2) (Fin D × Fin 2) ℂ) (i : Fin 2) :
    Matrix (Fin D) (Fin D × Fin 2) ℂ :=
  fun α y => W (α, i) y

/-- A step factors as `S_i(W) = E R_i` through the tag-zero embedding `E`,
`E|φ⟩ = |φ⟩|0⟩`, with `(R_i)_{α,y} = W_{(α,i),y}`. -/
theorem transitionStep_eq_mul (W : Matrix (Fin D × Fin 2) (Fin D × Fin 2) ℂ) (i : Fin 2) :
    transitionStep W i = tagZeroEmbed D * rowsAt W i := by
  ext x y
  rw [Matrix.mul_apply, Finset.sum_eq_single x.1]
  · by_cases h : x.2 = 0 <;> simp [transitionStep, tagZeroEmbed, rowsAt, h]
  · intro β _ hβ
    simp [tagZeroEmbed, Ne.symm hβ]
  · simp

/-- On the tag-zero subspace the rows `R_i` of `W` give the step matrices of
the deterministic scheme: `R_i E` is `MPSPreparation.stepMatrix W i`. -/
theorem rowsAt_mul_tagZeroEmbed (W : Matrix (Fin D × Fin 2) (Fin D × Fin 2) ℂ) (i : Fin 2) :
    rowsAt W i * tagZeroEmbed D = stepMatrix W i := by
  ext α β
  rw [Matrix.mul_apply, Finset.sum_eq_single (β, 0)]
  · simp [tagZeroEmbed, rowsAt, stepMatrix]
  · rintro ⟨γ, t⟩ _ hne
    have : ¬(t = 0 ∧ γ = β) := by
      rintro ⟨h1, h2⟩
      exact hne (Prod.ext h2 h1)
    simp [tagZeroEmbed, this]
  · simp

/-- The coordinates of `E v = |v⟩|0⟩`. -/
theorem tagZeroEmbed_mulVec_apply (v : Fin D → ℂ) (x : Fin D × Fin 2) :
    (tagZeroEmbed D *ᵥ v) x = if x.2 = 0 then v x.1 else 0 := by
  rw [Matrix.mulVec, dotProduct, Finset.sum_eq_single x.1]
  · by_cases h : x.2 = 0 <;> simp [tagZeroEmbed, h]
  · intro β _ hβ
    simp [tagZeroEmbed, Ne.symm hβ]
  · simp

/-- The tag-zero embedding `E` is an isometry: `‖E v‖² = ‖v‖²`. -/
theorem star_tagZeroEmbed_mulVec_dotProduct (v : Fin D → ℂ) :
    star (tagZeroEmbed D *ᵥ v) ⬝ᵥ (tagZeroEmbed D *ᵥ v) = star v ⬝ᵥ v := by
  simp only [dotProduct, Fintype.sum_prod_type, Pi.star_apply, tagZeroEmbed_mulVec_apply,
    Fin.sum_univ_two]
  simp

/-! ### From the transition scheme to the deterministic scheme -/

/-- Every state generated by the transition scheme is generated by the
deterministic scheme with a `D`-dimensional ancilla: after the interaction the
tag qubit is `|0⟩`, so the bond lives in `ℂ^D ⊗ |0⟩` (arXiv:quant-ph/0608197,
lines 1555--1573; arXiv:quant-ph/0501096, eq. `IsofromT`). -/
theorem isDeterministicallyGenerated_of_isTransitionGenerated {ψ : (Fin N → Fin 2) → ℂ}
    (h : IsTransitionGenerated D ψ) : IsDeterministicallyGenerated D ψ := by
  classical
  obtain ⟨W, φI, φF, hW, hI, hF, hJ⟩ := h
  have hD : 0 < D := by
    rcases Nat.eq_zero_or_pos D with h0 | h0
    · subst h0; simp [dotProduct] at hI
    · exact h0
  cases N with
  | zero =>
    have hφ : φI = ψ Fin.elim0 • φF := by
      have := hJ Fin.elim0
      simpa [transitionJointState] using this
    have hψ : star (ψ Fin.elim0) * ψ Fin.elim0 = 1 := by
      rw [← hI, hφ, star_smul, smul_dotProduct, dotProduct_smul, hF]
      simp [mul_comm]
    refine ⟨fun k => Fin.elim0 k, ψ Fin.elim0 • basisVecZero D, basisVecZero D,
      fun k => Fin.elim0 k, ?_, star_basisVecZero_dotProduct_self hD, fun τ => ?_⟩
    · rw [star_smul_basisVecZero_dotProduct_self hD, hψ]
    · rw [show τ = Fin.elim0 from Subsingleton.elim _ _]
      simp [jointState]
  | succ n =>
    -- The first step acts on `φ_I`; its output lies in `ℂ^D ⊗ |0⟩`.
    let v : Fin 2 → Fin D → ℂ := fun i => rowsAt (W 0) i *ᵥ φI
    have hv : ∑ i, star (v i) ⬝ᵥ v i = 1 := by
      rw [← hI, ← Matrix.star_mulVec_dotProduct_of_mem_unitaryGroup (hW 0) φI, dotProduct,
        Fintype.sum_prod_type, Finset.sum_comm]
      rfl
    have hiso : IsIsometryOn 1 (fun i => colMat (v i)) := by
      intro β β' hβ hβ'
      obtain rfl : β = ⟨0, hD⟩ := Fin.ext (Nat.lt_one_iff.mp hβ)
      obtain rfl : β' = ⟨0, hD⟩ := Fin.ext (Nat.lt_one_iff.mp hβ')
      simpa [colMat, dotProduct] using hv
    obtain ⟨U₀, hU₀, hU₀v⟩ := exists_unitary_extension hiso
    let U : Fin (n + 1) → Matrix (Fin D × Fin 2) (Fin D × Fin 2) ℂ :=
      fun k => if k = 0 then U₀ else W k
    have hU : ∀ k, U k ∈ Matrix.unitaryGroup (Fin D × Fin 2) ℂ := fun k => by
      simp only [U]; split_ifs
      · exact hU₀
      · exact hW k
    have hfirst : ∀ i, stepMatrix U₀ i *ᵥ basisVecZero D = v i := fun i => by
      funext α
      rw [mulVec_basisVecZero_apply hD]
      simpa [colMat, stepMatrix] using hU₀v i α ⟨0, hD⟩ (by simp)
    -- The transition joint state is the embedding of the `D`-dimensional one.
    have hemb : ∀ τ, transitionJointState W φI τ =
        tagZeroEmbed D *ᵥ jointState U (basisVecZero D) τ := fun τ => by
      have hrest : (fun p : Fin n => stepMatrix (U (Fin.rev p.castSucc))) =
          fun p => stepMatrix (W (Fin.rev p.castSucc)) := by
        funext p
        simp [U, Fin.rev_castSucc, Fin.succ_ne_zero]
      rw [jointState, eval_succ', ← Matrix.mulVec_mulVec]
      simp only [hrest, Fin.rev_last, U, ↓reduceIte]
      rw [hfirst, transitionJointState, Fin.prod_succ']
      simp only [transitionStep_eq_mul, Fin.rev_last]
      rw [← Matrix.mul_assoc, Fin.prod_mul_mul_eq, Matrix.mul_assoc, ← Matrix.mulVec_mulVec,
        ← Matrix.mulVec_mulVec]
      simp only [rowsAt_mul_tagZeroEmbed]
      rfl
    -- The `D`-dimensional joint state decouples onto the tag-zero part of `φ_F`.
    let φF' : Fin D → ℂ := fun α => φF (α, 0)
    have hJ' : ∀ τ, jointState U (basisVecZero D) τ = ψ τ • φF' := fun τ => by
      funext α
      have := congrFun (hJ τ) (α, 0)
      rw [hemb, tagZeroEmbed_mulVec_apply] at this
      simpa [φF'] using this
    have hnorm : ∑ τ, star (jointState U (basisVecZero D) τ) ⬝ᵥ
        jointState U (basisVecZero D) τ = 1 := by
      rw [← star_basisVecZero_dotProduct_self hD]
      exact sum_normSq_eval_mulVec (fun _ => D) (fun p => stepMatrix (U (Fin.rev p)))
        (fun _ _ α _ hα => absurd α.isLt (by omega))
        (fun p => isIsometryOn_stepMatrix (hU _)) _ (fun β hβ => absurd β.isLt (by omega))
    obtain ⟨τ₀, hτ₀⟩ : ∃ τ, ψ τ ≠ 0 := by
      by_contra hcon
      simp only [ne_eq, not_exists, not_not] at hcon
      simp [hJ', hcon, dotProduct] at hnorm
    have hF1 : ∀ α, φF (α, 1) = 0 := fun α => by
      have := congrFun (hJ τ₀) (α, 1)
      rw [hemb, tagZeroEmbed_mulVec_apply] at this
      simp only [Pi.smul_apply, smul_eq_mul] at this
      exact (mul_eq_zero.mp this.symm).resolve_left hτ₀ |>.symm ▸ rfl
    have hF' : star φF' ⬝ᵥ φF' = 1 := by
      rw [← hF]
      simp [dotProduct, Fintype.sum_prod_type, Fin.sum_univ_two, hF1, φF']
    exact ⟨U, basisVecZero D, φF', hU, star_basisVecZero_dotProduct_self hD, hF', hJ'⟩

/-! ### From the deterministic scheme to the transition scheme -/

/-- Every state generated by the deterministic scheme with a `D`-dimensional
ancilla is generated by the transition scheme: the unitary `U^{[k]}` on
ancilla ⊗ site is used as the ancilla unitary on `ℂ^D ⊗ ℂ^2` and followed by the
fixed interaction, which moves the tag qubit onto the site
(arXiv:quant-ph/0501096, eq. `IsofromT`; arXiv:quant-ph/0608197, lines
1555--1573). -/
theorem isTransitionGenerated_of_isDeterministicallyGenerated {ψ : (Fin N → Fin 2) → ℂ}
    (h : IsDeterministicallyGenerated D ψ) : IsTransitionGenerated D ψ := by
  classical
  obtain ⟨U, φI, φF, hU, hI, hF, hJ⟩ := h
  refine ⟨U, tagZeroEmbed D *ᵥ φI, tagZeroEmbed D *ᵥ φF, hU,
    by rw [star_tagZeroEmbed_mulVec_dotProduct, hI],
    by rw [star_tagZeroEmbed_mulVec_dotProduct, hF], fun τ => ?_⟩
  rw [transitionJointState, Matrix.mulVec_mulVec]
  simp only [transitionStep_eq_mul]
  rw [Fin.prod_mul_mul_eq, ← Matrix.mulVec_mulVec]
  simp only [rowsAt_mul_tagZeroEmbed]
  rw [show Fin.prod (fun p => stepMatrix (U (Fin.rev p)) (τ p)) *ᵥ φI =
    jointState U φI τ from rfl, hJ, Matrix.mulVec_smul]

/-- **Theorem `Thm:seqwith`, deterministic transition scheme**
(arXiv:quant-ph/0608197, lines 1555--1573): for `d = 2`, a vector is generated by
the deterministic transition scheme with ancilla `ℂ^D ⊗ ℂ^2` iff it is
normalized and, up to a nonzero scalar, has an open-boundary MPS representation
of bond dimension at most `D`. -/
theorem isTransitionGenerated_iff {ψ : (Fin N → Fin 2) → ℂ} :
    IsTransitionGenerated D ψ ↔ star ψ ⬝ᵥ ψ = 1 ∧ ∃ c : ℂ, c ≠ 0 ∧ HasOBCRep D (c • ψ) := by
  rw [← isDeterministicallyGenerated_iff]
  exact ⟨isDeterministicallyGenerated_of_isTransitionGenerated,
    isTransitionGenerated_of_isDeterministicallyGenerated⟩

end MPSPreparation
