/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.Preparation.IsometricChain

/-!
# Sequential generation of matrix product states with an ancilla

A spin chain of `N` sites, each initially in `|0⟩ ∈ ℂ^d`, interacts one site at a
time with a `D`-dimensional ancilla prepared in `|φ_I⟩`. The operation at step
`k` sends `|β⟩|0⟩` to `∑_{i,α} A^{[k]}_{i,αβ} |α, i⟩`. After all `N` steps the
ancilla is projected on `|φ_F⟩`, and the chain is left in the state of
arXiv:quant-ph/0608197, eq. `OBCMPSgen`,
\[
  |\psi\rangle = \sum_{i_1,\dots,i_N}
    \langle\varphi_F| A^{[N]}_{i_N} \cdots A^{[1]}_{i_1} |\varphi_I\rangle
    |i_N \cdots i_1\rangle .
\]

## Indexing

Step labels are `k : Fin N`, with `A k` the source's `A^{[k+1]}`. States are
functions on configurations `τ : Fin N → Fin d` indexed by *ket position*:
`τ p` is the `p`-th tensor factor of the ket `|i_N ⋯ i_1⟩` read from the left,
so `τ p = i_{N-p}` is the site produced at step `N - p`, that is by
`A (Fin.rev p)`. With this convention the matrix at ket position `p` is at
position `p` of the product, and a generated state is literally an
open-boundary chain `OBCChainTensor.coeff` (arXiv:quant-ph/0608197,
eq. `eq.vidal`) in the same coordinates.

## Main definitions

* `MPSPreparation.seqAmplitude` — the state of eq. `OBCMPSgen`.
* `MPSPreparation.IsProbabilisticallyGenerated` — scheme 1 (probabilistic):
  arbitrary operations and a final projection on `|φ_F⟩`.
* `MPSPreparation.IsDeterministicallyGenerated` — scheme 2 (deterministic):
  unitary interactions `U^{[k]}` on ancilla ⊗ site, a normalized initial
  ancilla state, and decoupling of the ancilla in the last step.
* `MPSPreparation.HasOBCRep` — the state is an open-boundary MPS with bond
  dimension at most `D`.

## Main results

Theorem `Thm:seqwith` of arXiv:quant-ph/0608197 (lines 1570--1574) for the
probabilistic and deterministic schemes:

* `MPSPreparation.isProbabilisticallyGenerated_iff` — a nonzero vector is
  generated by the probabilistic scheme iff it is, up to a nonzero scalar, an
  open-boundary MPS of bond dimension at most `D`.
* `MPSPreparation.isDeterministicallyGenerated_iff` — a vector is generated by
  the deterministic scheme iff it is normalized and, up to a nonzero scalar, an
  open-boundary MPS of bond dimension at most `D`.

The scalar only matters at `N = 0`, where the open-boundary coefficient is the
empty product `1`; states are rays, and the source's "(up to normalization)"
(line 1540) is this freedom.

The deterministic transition scheme (scheme 3, `d = 2`, a fixed interaction) and
the theorem on sequential generation without ancilla (lines 1590--1616) are not
formalized here.

## References

* Pérez-García, Verstraete, Wolf, Cirac, *Matrix product state representations*,
  arXiv:quant-ph/0608197, section "Generation of MPS", lines 1504--1583 of
  `Papers/quant-ph_0608197/MPSarchive.tex` (eq. `OBCMPSgen`, Theorem
  `Thm:seqwith`).
* Schön, Solano, Verstraete, Cirac, Wolf, *Sequential generation of entangled
  multiqubit states*, arXiv:quant-ph/0501096, eqs. `MPSiso`, `MPS`, `induction`.
-/

open scoped BigOperators Matrix

namespace MPSPreparation

variable {d D N : ℕ}

/-- The state of arXiv:quant-ph/0608197, eq. `OBCMPSgen` (lines 1541--1546):
`⟨φ_F| A^{[N]}_{i_N} ⋯ A^{[1]}_{i_1} |φ_I⟩` at the ket-position configuration
`τ`, where `τ p = i_{N-p}` and `A k = A^{[k+1]}`. -/
def seqAmplitude (φF φI : Fin D → ℂ) (A : Fin N → Fin d → Matrix (Fin D) (Fin D) ℂ)
    (τ : Fin N → Fin d) : ℂ :=
  star φF ⬝ᵥ (chainProd (fun p => A (Fin.rev p)) τ *ᵥ φI)

/-- Scheme 1 of arXiv:quant-ph/0608197 (probabilistic schemes, lines 1549--1550):
the vector `ψ` is the state of eq. `OBCMPSgen` for some operations
`A^{[1]}, …, A^{[N]}` on a `D`-dimensional ancilla, some initial ancilla state
`φ_I`, and some final projection `φ_F`. The source's "up to normalization"
(line 1540) is kept: `ψ` is the unnormalized post-measurement vector. -/
def IsProbabilisticallyGenerated (D : ℕ) (ψ : (Fin N → Fin d) → ℂ) : Prop :=
  ∃ (A : Fin N → Fin d → Matrix (Fin D) (Fin D) ℂ) (φI φF : Fin D → ℂ),
    ψ = seqAmplitude φF φI A

/-- The operation on the ancilla induced by a unitary `U` on ancilla ⊗ site
acting on the site state `|0⟩`: `A_{i,αβ} = ⟨α, i| U |β, 0⟩`
(arXiv:quant-ph/0608197, lines 1529--1533). -/
def stepMatrix [NeZero d] (U : Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ) :
    Fin d → Matrix (Fin D) (Fin D) ℂ :=
  fun i α β => U (α, i) (β, 0)

/-- The ancilla component of the joint ancilla-chain state after the unitaries
`U^{[1]}, …, U^{[N]}` have acted on `|φ_I⟩ ⊗ |0⟩^{⊗N}`: the joint state is
`∑_{α, τ} (jointState U φI τ α) |α⟩ ⊗ |τ⟩` (arXiv:quant-ph/0608197,
lines 1529--1541; arXiv:quant-ph/0501096, the state
`V_{[n]} ⋯ V_{[1]} |φ_I⟩`). -/
def jointState [NeZero d] (U : Fin N → Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ)
    (φI : Fin D → ℂ) (τ : Fin N → Fin d) : Fin D → ℂ :=
  chainProd (fun p => stepMatrix (U (Fin.rev p))) τ *ᵥ φI

/-- Scheme 2 of arXiv:quant-ph/0608197 (deterministic schemes, lines 1551--1552):
the interactions are unitaries `U^{[k]}` on ancilla ⊗ site, the ancilla starts
in a normalized state `φ_I`, and after the last step the joint state factorizes
as `|φ_F⟩ ⊗ |ψ⟩` with `φ_F` normalized ("the ancilla must decouple in the last
step, without measurement"). -/
def IsDeterministicallyGenerated [NeZero d] (D : ℕ) (ψ : (Fin N → Fin d) → ℂ) : Prop :=
  ∃ (U : Fin N → Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ) (φI φF : Fin D → ℂ),
    (∀ k, U k ∈ Matrix.unitaryGroup (Fin D × Fin d) ℂ) ∧ star φI ⬝ᵥ φI = 1 ∧
      star φF ⬝ᵥ φF = 1 ∧ ∀ τ α, jointState U φI τ α = φF α * ψ τ

/-- The vector `ψ` is an open-boundary MPS with bond dimension at most `D`,
arXiv:quant-ph/0608197, eq. `eq.vidal` (lines 419--429). -/
def HasOBCRep (D : ℕ) (ψ : (Fin N → Fin d) → ℂ) : Prop :=
  ∃ B : OBCChainTensor d D N, ψ = B.coeff

private theorem chainProd_rev_rev (A : Fin N → Fin d → Matrix (Fin D) (Fin D) ℂ) :
    (fun p => A (Fin.rev (Fin.rev p))) = A := by
  funext p; simp

private theorem star_basisVecZero_dotProduct_self (hD : 0 < D) :
    star (basisVecZero D) ⬝ᵥ basisVecZero D = 1 := by
  rw [star_basisVecZero, basisVecZero_dotProduct hD]; simp [basisVecZero]

/-- The open-boundary chain of length zero with all bonds one-dimensional. -/
private def obcZero (hD : 0 < D) : OBCChainTensor d D 0 where
  bondDim := fun _ => 1
  bondDim_le := fun _ => hD
  left_dim := rfl
  right_dim := rfl
  tensor := fun p => Fin.elim0 p

/-- Every state of eq. `OBCMPSgen` is, up to a nonzero scalar, an open-boundary
MPS of bond dimension at most `D`: the forward direction of Theorem
`Thm:seqwith` for the probabilistic scheme (arXiv:quant-ph/0608197,
lines 1536--1546 and 1570--1574). -/
theorem exists_hasOBCRep_of_isProbabilisticallyGenerated {ψ : (Fin N → Fin d) → ℂ}
    (hψ : ψ ≠ 0) (h : IsProbabilisticallyGenerated D ψ) :
    ∃ c : ℂ, c ≠ 0 ∧ HasOBCRep D (c • ψ) := by
  obtain ⟨A, φI, φF, rfl⟩ := h
  have hD : 0 < D := by
    rcases Nat.eq_zero_or_pos D with h0 | h0
    · subst h0
      exact absurd (funext fun τ => by simp [seqAmplitude, dotProduct]) hψ
    · exact h0
  cases N with
  | zero =>
    have hne : seqAmplitude φF φI A Fin.elim0 ≠ 0 := by
      intro h0; apply hψ; funext τ
      rw [show τ = Fin.elim0 from Subsingleton.elim _ _, h0]; rfl
    refine ⟨(seqAmplitude φF φI A Fin.elim0)⁻¹, inv_ne_zero hne, obcZero hD, funext fun τ => ?_⟩
    rw [show τ = Fin.elim0 from Subsingleton.elim _ _]
    simp [inv_mul_cancel₀ hne]
  | succ n =>
    obtain ⟨b, Q, r', hb0, hbD, hrow, hcol, hiso, -, hprod⟩ :=
      exists_isometric_chain (n + 1) 1 hD (rowMat (star φF)) (rowSupp_rowMat _)
        (fun p => A (Fin.rev p)) φI
    obtain ⟨B, hB, -⟩ := OBCChainTensor.exists_of_isometric_chain b hbD hb0 Q hrow hcol hiso r'
    refine ⟨1, one_ne_zero, B, funext fun τ => ?_⟩
    rw [hB, ← hprod, rowMat_mul_mulVec_zero hD]
    simp [seqAmplitude]

/-- Every open-boundary MPS of bond dimension at most `D` is a state of
eq. `OBCMPSgen` with `D × D` matrices: the converse direction of Theorem
`Thm:seqwith` for the probabilistic scheme (arXiv:quant-ph/0608197,
lines 1570--1574). -/
theorem isProbabilisticallyGenerated_of_hasOBCRep {ψ : (Fin N → Fin d) → ℂ} {c : ℂ}
    (hc : c ≠ 0) (h : HasOBCRep D (c • ψ)) : IsProbabilisticallyGenerated D ψ := by
  obtain ⟨B, hB⟩ := h
  have hD := B.pos_bound
  refine ⟨fun k => OBCChainTensor.zeroPad B (Fin.rev k), c⁻¹ • basisVecZero D, basisVecZero D,
    funext fun τ => ?_⟩
  have hτ := congrFun hB τ
  rw [OBCChainTensor.coeff_eq_chainProd_zeroPad] at hτ
  simp only [Pi.smul_apply, smul_eq_mul] at hτ
  rw [seqAmplitude, chainProd_rev_rev (fun p => OBCChainTensor.zeroPad B p),
    Matrix.mulVec_smul, dotProduct_smul, star_basisVecZero, basisVecZero_dotProduct hD,
    mulVec_basisVecZero_apply hD, ← hτ, smul_eq_mul, ← mul_assoc, inv_mul_cancel₀ hc, one_mul]

/-- **Theorem `Thm:seqwith`, probabilistic scheme** (arXiv:quant-ph/0608197,
lines 1570--1574): a nonzero vector is generated by a probabilistic sequential
scheme with a `D`-dimensional ancilla iff, up to a nonzero scalar, it has an
open-boundary MPS representation of bond dimension at most `D`. -/
theorem isProbabilisticallyGenerated_iff {ψ : (Fin N → Fin d) → ℂ} (hψ : ψ ≠ 0) :
    IsProbabilisticallyGenerated D ψ ↔ ∃ c : ℂ, c ≠ 0 ∧ HasOBCRep D (c • ψ) :=
  ⟨exists_hasOBCRep_of_isProbabilisticallyGenerated hψ,
    fun ⟨_, hc, h⟩ => isProbabilisticallyGenerated_of_hasOBCRep hc h⟩

theorem isIsometryOn_stepMatrix [NeZero d] {U : Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ}
    (hU : U ∈ Matrix.unitaryGroup (Fin D × Fin d) ℂ) : IsIsometryOn D (stepMatrix U) := by
  intro β β' _ _
  have h := congrFun (congrFun (Matrix.mem_unitaryGroup_iff'.mp hU) (β, 0)) (β', 0)
  simp only [Matrix.mul_apply, Matrix.star_apply, Matrix.one_apply, Prod.mk.injEq, and_true,
    Fintype.sum_prod_type] at h
  rw [Finset.sum_comm, ← h]
  rfl

/-- The states generated by the deterministic scheme are normalized
(arXiv:quant-ph/0608197, lines 1529--1541: unitary interactions and a
normalized initial ancilla state). -/
theorem star_dotProduct_self_of_isDeterministicallyGenerated [NeZero d]
    {ψ : (Fin N → Fin d) → ℂ} (h : IsDeterministicallyGenerated D ψ) :
    star ψ ⬝ᵥ ψ = 1 := by
  obtain ⟨U, φI, φF, hU, hI, hF, hJ⟩ := h
  have hnorm := sum_normSq_chainProd_mulVec (fun _ => D)
    (fun p => stepMatrix (U (Fin.rev p))) (fun _ _ α _ hα => absurd α.isLt (by omega))
    (fun p => isIsometryOn_stepMatrix (hU _)) φI (fun β hβ => absurd β.isLt (by omega))
  rw [hI] at hnorm
  rw [← hnorm]
  simp only [dotProduct, Pi.star_apply]
  refine Finset.sum_congr rfl fun τ _ => ?_
  have hJτ : chainProd (fun p => stepMatrix (U (Fin.rev p))) τ *ᵥ φI = fun α => φF α * ψ τ :=
    funext (hJ τ)
  rw [hJτ]
  simp only [star_mul']
  have hF' : ∑ α, star (φF α) * φF α = 1 := hF
  calc star (ψ τ) * ψ τ = (∑ α, star (φF α) * φF α) * (star (ψ τ) * ψ τ) := by rw [hF', one_mul]
    _ = _ := by rw [Finset.sum_mul]; exact Finset.sum_congr rfl fun α _ => by ring

/-- A deterministically generated state is also probabilistically generated,
with the operations `A^{[k]}_{i,αβ} = ⟨α, i| U^{[k]} |β, 0⟩` and the
projection on the decoupled ancilla state (arXiv:quant-ph/0608197,
lines 1529--1541). -/
theorem isProbabilisticallyGenerated_of_isDeterministicallyGenerated [NeZero d]
    {ψ : (Fin N → Fin d) → ℂ} (h : IsDeterministicallyGenerated D ψ) :
    IsProbabilisticallyGenerated D ψ := by
  obtain ⟨U, φI, φF, -, -, hF, hJ⟩ := h
  refine ⟨fun k => stepMatrix (U k), φI, φF, funext fun τ => ?_⟩
  have hJτ : chainProd (fun p => stepMatrix (U (Fin.rev p))) τ *ᵥ φI = fun α => φF α * ψ τ :=
    funext (hJ τ)
  simp only [seqAmplitude, hJτ, dotProduct, Pi.star_apply]
  have hF' : ∑ α, star (φF α) * φF α = 1 := hF
  calc ψ τ = (∑ α, star (φF α) * φF α) * ψ τ := by rw [hF', one_mul]
    _ = _ := by rw [Finset.sum_mul]; exact Finset.sum_congr rfl fun α _ => by ring

/-- Every normalized open-boundary MPS of bond dimension at most `D` (up to a
nonzero scalar) is generated by the deterministic scheme: the substantive
direction of Theorem `Thm:seqwith` (arXiv:quant-ph/0608197, lines 1570--1583).
The proof is the successive-decomposition recipe of arXiv:quant-ph/0501096,
eq. `induction`, followed by extension of the isometries to unitaries on
ancilla ⊗ site; the ancilla decouples because the first bond of the resulting
chain is one-dimensional. -/
theorem isDeterministicallyGenerated_of_hasOBCRep [NeZero d] {ψ : (Fin N → Fin d) → ℂ}
    (hψ : star ψ ⬝ᵥ ψ = 1) {c : ℂ} (hc : c ≠ 0) (h : HasOBCRep D (c • ψ)) :
    IsDeterministicallyGenerated D ψ := by
  obtain ⟨B, hB⟩ := h
  have hD := B.pos_bound
  cases N with
  | zero =>
    have hψ' : star (ψ Fin.elim0) * ψ Fin.elim0 = 1 := by
      rw [dotProduct, Fintype.sum_subsingleton _ Fin.elim0] at hψ
      exact hψ
    refine ⟨fun k => Fin.elim0 k, ψ Fin.elim0 • basisVecZero D, basisVecZero D,
      fun k => Fin.elim0 k, ?_,
      star_basisVecZero_dotProduct_self hD, fun τ α => ?_⟩
    · rw [star_smul, smul_dotProduct, dotProduct_smul, star_basisVecZero_dotProduct_self hD]
      simpa [mul_comm] using hψ'
    · rw [show τ = Fin.elim0 from Subsingleton.elim _ _]
      simp [jointState, mul_comm]
  | succ n =>
    obtain ⟨b, Q, r', hb0, hbD, hrow, hcol, hiso, hr', hprod⟩ :=
      exists_isometric_chain (n + 1) 1 hD (rowMat (c⁻¹ • basisVecZero D)) (rowSupp_rowMat _)
        (fun p => OBCChainTensor.zeroPad B p) (basisVecZero D)
    -- The chain output is `ψ τ • |0⟩`.
    have hout : ∀ τ, chainProd Q τ *ᵥ r' = fun α => basisVecZero D α * ψ τ := by
      intro τ
      funext α
      by_cases hα : α.val = 0
      · have hα' : α = ⟨0, hD⟩ := Fin.ext hα
        subst hα'
        rw [← hprod, rowMat_mul_mulVec_zero hD]
        have hτ := congrFun hB τ
        rw [OBCChainTensor.coeff_eq_chainProd_zeroPad] at hτ
        simp only [Pi.smul_apply, smul_eq_mul] at hτ
        rw [smul_dotProduct, basisVecZero_dotProduct hD, mulVec_basisVecZero_apply hD, ← hτ,
          smul_eq_mul, ← mul_assoc, inv_mul_cancel₀ hc, one_mul]
        simp [basisVecZero]
      · have := vecSupp_chainProd_mulVec b Q hrow r' hr' τ α (by rw [hb0]; omega)
        rw [this]
        simp [basisVecZero, hα]
    -- Unitary extensions of the isometric sites.
    have hext : ∀ p, ∃ U ∈ Matrix.unitaryGroup (Fin D × Fin d) ℂ,
        ∀ i α β, β.val < b p.succ → U (α, i) (β, 0) = Q p i α β :=
      fun p => exists_unitary_extension (hiso p)
    choose U hU hUQ using hext
    have hjoint : ∀ τ, chainProd (fun p => stepMatrix (U p)) τ *ᵥ r' = chainProd Q τ *ᵥ r' :=
      chainProd_mulVec_congr b Q (fun p => stepMatrix (U p)) hrow
        (fun p i α β h => hUQ p i α β h) r' hr'
    have hr'norm : star r' ⬝ᵥ r' = 1 := by
      rw [← sum_normSq_chainProd_mulVec b Q hrow hiso r' hr', ← hψ]
      simp only [hout, dotProduct, Pi.star_apply, star_mul']
      refine Finset.sum_congr rfl fun τ _ => ?_
      rw [Finset.sum_eq_single ⟨0, hD⟩]
      · simp [basisVecZero]
      · intro b _ hb
        have : b.val ≠ 0 := fun h => hb (Fin.ext h)
        simp [basisVecZero, this]
      · simp
    refine ⟨fun k => U (Fin.rev k), r', basisVecZero D, fun k => hU _, hr'norm,
      star_basisVecZero_dotProduct_self hD, fun τ α => ?_⟩
    have := chainProd_rev_rev (fun p => stepMatrix (U p))
    simp only [jointState] at *
    rw [show (fun p => stepMatrix (U (Fin.rev (Fin.rev p)))) = fun p => stepMatrix (U p) from this,
      hjoint, hout]

/-- **Theorem `Thm:seqwith`, deterministic scheme** (arXiv:quant-ph/0608197,
lines 1570--1583): a vector is generated by a deterministic sequential scheme
with a `D`-dimensional ancilla (unitary interactions, ancilla decoupling in the
last step) iff it is normalized and, up to a nonzero scalar, has an
open-boundary MPS representation of bond dimension at most `D`. -/
theorem isDeterministicallyGenerated_iff [NeZero d] {ψ : (Fin N → Fin d) → ℂ} :
    IsDeterministicallyGenerated D ψ ↔
      star ψ ⬝ᵥ ψ = 1 ∧ ∃ c : ℂ, c ≠ 0 ∧ HasOBCRep D (c • ψ) := by
  constructor
  · intro h
    have hn := star_dotProduct_self_of_isDeterministicallyGenerated h
    refine ⟨hn, exists_hasOBCRep_of_isProbabilisticallyGenerated ?_
      (isProbabilisticallyGenerated_of_isDeterministicallyGenerated h)⟩
    rintro rfl
    simp [dotProduct] at hn
  · rintro ⟨hn, c, hc, h⟩
    exact isDeterministicallyGenerated_of_hasOBCRep hn hc h

/-- For normalized vectors the deterministic and probabilistic schemes generate
the same states (arXiv:quant-ph/0608197, Theorem `Thm:seqwith`,
lines 1570--1574). -/
theorem isDeterministicallyGenerated_iff_isProbabilisticallyGenerated [NeZero d]
    {ψ : (Fin N → Fin d) → ℂ} (hψ : star ψ ⬝ᵥ ψ = 1) :
    IsDeterministicallyGenerated D ψ ↔ IsProbabilisticallyGenerated D ψ := by
  have hne : ψ ≠ 0 := by rintro rfl; simp [dotProduct] at hψ
  rw [isDeterministicallyGenerated_iff, isProbabilisticallyGenerated_iff hne]
  exact ⟨fun h => h.2, fun h => ⟨hψ, h⟩⟩

end MPSPreparation
