/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.Algebra.FinOrderedProduct
import TNLean.Algebra.IsometryUnitaryExtension
import TNLean.MPS.Preparation.Sequential
import Mathlib.LinearAlgebra.Matrix.Kronecker

/-!
# Sequential generation without an ancilla

A chain of `N ≥ 2` sites, each `ℂ^d` and initially in `|0⟩`, is acted on first
by an operation `U^{[1]}` on sites `1` and `2`, then by `U^{[2]}` on sites `2`
and `3`, and so on up to `U^{[N-1]}` on sites `N - 1` and `N`
(arXiv:quant-ph/0608197, section "Sequential generation without ancilla",
lines 1580--1586). The scheme is deterministic when every `U^{[k]}` is unitary and
probabilistic when the operations are arbitrary, the generated state then being
taken up to normalization.

## Indexing

As in `TNLean.MPS.Preparation.Sequential`, configurations `τ : Fin N → Fin d` are
indexed by ket position: source site `j` sits at position `N - j`. The operation
`U k` is the source's `U^{[k+1]}`, a matrix on `ℂ^d ⊗ ℂ^d` whose first tensor
factor is site `k + 1` and whose second is site `k + 2`. The chain length is
written `N = n + 2`.

**Local fix (N ≥ 2):** the scheme presupposes two sites, since its first operation
acts on sites `1` and `2`; read literally at `N = 1` it generates only `|0⟩`, and
the theorem fails. The statements here are for `N ≥ 2`, where the scheme is
defined as printed. Documented in
`docs/paper-gaps/pgvwc07_sequential_no_ancilla_two_sites.tex`.

## The generated state

Before `U^{[k]}` acts, the sites `k + 1, …, N` have not been touched and are still
in `|0⟩`, and after it site `k` is never touched again. Hence the chain state
after `U^{[k]}` is `|χ_k⟩ ⊗ |0⟩^{⊗(N-k-1)}`, where `χ_k` is a vector on sites
`1, …, k + 1`, `χ_1 = U^{[1]}|0,0⟩` and
`χ_k(…, i, β) = ∑_α ⟨i, β| U^{[k]} |α, 0⟩ χ_{k-1}(…, α)`. The definition
`MPSPreparation.noAncillaState` is this recursion.

## Main results

* `MPSPreparation.noAncillaState_eq_jointState` — the scheme without an ancilla is
  the scheme with a `d`-dimensional ancilla of `TNLean.MPS.Preparation.Sequential`
  run with the operations `U^{[k]}` with swapped outputs, the ancilla being the
  next site and read out as the site at position `0`. The induced matrices
  `⟨β, i| SWAP U^{[k]} |α, 0⟩ = ⟨i, β| U^{[k]} |α, 0⟩` are the identification
  `A^{[k]}_{i,βα} = ⟨i, β| U^{[k]} |α, 0⟩` of the proof in the source
  (lines 1597--1603); the source writes this entry as `A^{[k]}_{i,α,β}`, with the
  received index `α` first.
* `MPSPreparation.hasOBCRep_iff_exists_eq_jointState`,
  `MPSPreparation.hasOBCRep_and_norm_iff_exists_unitary_eq_jointState` — the
  states read out from the scheme with a `d`-dimensional ancilla in this way are
  exactly the open-boundary MPS of bond dimension at most `d`, normalized for
  unitary operations and a normalized initial ancilla state.
* `MPSPreparation.isProbabilisticallyGeneratedWithoutAncilla_iff` and
  `MPSPreparation.isDeterministicallyGeneratedWithoutAncilla_iff` — Theorem
  "Sequential generation without ancilla" (lines 1589--1595): the generated
  states are exactly the open-boundary MPS of bond dimension at most `d`,
  normalized in the deterministic case.

As in the source, the converse uses the scheme with an ancilla with site `k + 1`
as the ancilla of the `k`-th step (lines 1608--1615): the successive
decompositions of arXiv:quant-ph/0501096, eq. `induction`, applied after the
boundary site at position `0`, give isometries `ℂ^d → ℂ^d ⊗ ℂ^d`, their unitary
extensions are the operations, and the initial ancilla state is absorbed into the
first operation.

## References

* Pérez-García, Verstraete, Wolf, Cirac, *Matrix product state representations*,
  arXiv:quant-ph/0608197, lines 1580--1616 of
  `Papers/quant-ph_0608197/MPSarchive.tex`.
* Schön, Solano, Verstraete, Cirac, Wolf, *Sequential generation of entangled
  multiqubit states*, arXiv:quant-ph/0501096, eq. `induction`.
-/

open scoped Matrix Kronecker

namespace MPSPreparation

open MPSChainTensor (eval eval_succ eval_succ')

variable {d : ℕ} [NeZero d]

/-! ### The scheme -/

/-- The chain state generated by the operations `U^{[1]}, …, U^{[n+1]}` on the
chain of `n + 2` sites in `|0⟩^{⊗(n+2)}` (arXiv:quant-ph/0608197, lines
1580--1586), at the ket-position configuration `τ`. The last operation `U^{[n+1]}`
acts on the sites at positions `1` and `0`, the first of which carries the
output `α` of the earlier operations; see the module docstring. -/
def noAncillaState : ∀ (n : ℕ), (Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ) →
    (Fin (n + 2) → Fin d) → ℂ
  | 0, U, τ => U 0 (τ 1, τ 0) (0, 0)
  | n + 1, U, τ => ∑ α, U (Fin.last (n + 1)) (τ 1, τ 0) (α, 0) *
      noAncillaState n (fun k => U k.castSucc) (Fin.cons α fun p => τ p.succ.succ)

/-- The probabilistic sequential scheme without ancilla of arXiv:quant-ph/0608197,
lines 1580--1586: `ψ` is the (unnormalized) state produced by arbitrary
operations `U^{[1]}, …, U^{[n+1]}` on neighboring sites. -/
def IsProbabilisticallyGeneratedWithoutAncilla {n : ℕ} (ψ : (Fin (n + 2) → Fin d) → ℂ) :
    Prop :=
  ∃ U : Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ, ψ = noAncillaState n U

/-- The deterministic sequential scheme without ancilla of arXiv:quant-ph/0608197,
lines 1580--1586: `ψ` is the state produced by unitaries `U^{[1]}, …, U^{[n+1]}`
on neighboring sites. -/
def IsDeterministicallyGeneratedWithoutAncilla {n : ℕ} (ψ : (Fin (n + 2) → Fin d) → ℂ) :
    Prop :=
  ∃ U : Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ,
    (∀ k, U k ∈ Matrix.unitaryGroup (Fin d × Fin d) ℂ) ∧ ψ = noAncillaState n U

/-- Swapping the two output factors of an operation on `ℂ^d ⊗ ℂ^d`. -/
def swapRows (U : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ) :
    Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ :=
  fun x y => U x.swap y

omit [NeZero d] in
/-- Swapping the output factors twice is the identity. -/
@[simp] theorem swapRows_swapRows (U : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ) :
    swapRows (swapRows U) = U :=
  rfl

omit [NeZero d] in
/-- Swapping the output factors preserves unitarity. -/
theorem swapRows_mem_unitaryGroup {U : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ}
    (hU : U ∈ Matrix.unitaryGroup (Fin d × Fin d) ℂ) :
    swapRows U ∈ Matrix.unitaryGroup (Fin d × Fin d) ℂ := by
  rw [Matrix.mem_unitaryGroup_iff'] at hU ⊢
  ext y z
  have h := congrFun (congrFun hU y) z
  rw [Matrix.mul_apply] at h ⊢
  rw [← h]
  exact Fintype.sum_equiv (Equiv.prodComm _ _) _ _ fun x => rfl

/-- **The scheme without an ancilla is the scheme with a `d`-dimensional ancilla.** The state
generated by the operations `U^{[k]}` is the joint state of the scheme with an ancilla
`ℂ^d` (`MPSPreparation.jointState`) for the operations with swapped outputs, started in `|0⟩`
and read out as the site at position `0`: the ancilla of the `k`-th step is the site `k + 1`
(arXiv:quant-ph/0608197, lines 1608--1615). The induced matrices
`⟨β, i| SWAP U^{[k]} |α, 0⟩ = ⟨i, β| U^{[k]} |α, 0⟩` are those of lines 1597--1603, where the
source writes the same entry as `A^{[k]}_{i,α,β}`, with the received index `α` first. -/
theorem noAncillaState_eq_jointState :
    ∀ (n : ℕ) (U : Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ)
      (τ : Fin (n + 2) → Fin d),
      noAncillaState n U τ =
        jointState (fun k => swapRows (U k)) (basisVecZero d) (fun p => τ p.succ) (τ 0)
  | 0, U, τ => by
    have hd : 0 < d := Nat.pos_of_neZero d
    rw [noAncillaState, jointState, mulVec_basisVecZero_apply hd]
    simp only [eval, Fin.prod_succ, Fin.prod_zero, Matrix.mul_one]
    rfl
  | n + 1, U, τ => by
    rw [noAncillaState]
    simp only [noAncillaState_eq_jointState n, Fin.cons_zero, Fin.cons_succ, jointState]
    rw [eval_succ (fun p => stepMatrix (swapRows (U (Fin.rev p)))), ← Matrix.mulVec_mulVec]
    simp only [Fin.rev_zero, Fin.rev_succ]
    rw [Matrix.mulVec, dotProduct]
    rfl

/-! ### The scheme with a `d`-dimensional ancilla read out as a site -/

/-- A state of the form `τ ↦ (M₀(τ₁) ⋯ M_n(τ_{n+1}) v)(τ₀)` has an
open-boundary representation of bond dimension at most `d`: position `0` is
the boundary site `⟨τ₀|`. -/
theorem hasOBCRep_of_eq_eval {n : ℕ} (M : Fin (n + 1) → Fin d → Matrix (Fin d) (Fin d) ℂ)
    (v : Fin d → ℂ) {ψ : (Fin (n + 2) → Fin d) → ℂ}
    (h : ∀ τ, ψ τ = (eval M (fun p => τ p.succ) *ᵥ v) (τ 0)) : HasOBCRep d ψ := by
  classical
  have hd : 0 < d := Nat.pos_of_neZero d
  let P : Fin (n + 2) → Fin d → Matrix (Fin d) (Fin d) ℂ :=
    Fin.cons (fun j => rowMat (Pi.single j 1)) M
  obtain ⟨b, Q, r', hb0, hbD, -, hrow, hcol, hiso, -, hprod⟩ :=
    exists_isometric_chain (n + 2) 1 hd (rowMat (basisVecZero d))
      (isRowSupportedBelow_rowMat _) P v
  obtain ⟨B, hB, -⟩ := OBCChainTensor.exists_of_isometric_chain b hbD hb0 Q hrow hcol hiso r'
  refine ⟨B, funext fun τ => ?_⟩
  rw [h τ, hB, ← hprod, rowMat_mul_mulVec_zero hd, basisVecZero_dotProduct hd, eval_succ P,
    ← Matrix.mulVec_mulVec]
  simp [P, rowMat, Matrix.mulVec, dotProduct, Pi.single_apply]

omit [NeZero d] in
/-- The squared norm of a state `τ ↦ (w (τ₁, …))(τ₀)`. -/
theorem star_dotProduct_self_of_eq {n : ℕ} {ψ : (Fin (n + 2) → Fin d) → ℂ}
    (w : (Fin (n + 1) → Fin d) → Fin d → ℂ) (h : ∀ τ, ψ τ = w (fun p => τ p.succ) (τ 0)) :
    star ψ ⬝ᵥ ψ = ∑ τ', star (w τ') ⬝ᵥ w τ' := by
  rw [dotProduct]
  simp only [Pi.star_apply, h]
  exact Fintype.sum_fin_succ_pi (fun j τ' => star (w τ' j) * w τ' j)

omit [NeZero d] in
/-- The successive decompositions of arXiv:quant-ph/0501096, eq. `induction`,
run on an open-boundary MPS of bond dimension at most `d` after its boundary
site at position `0`: the state is `τ ↦ (Q₀(τ₁) ⋯ Q_n(τ_{n+1}) r')(τ₀)` with
every `Q_p` isometric on its bond block. -/
theorem exists_isometric_chain_of_hasOBCRep {n : ℕ} {ψ : (Fin (n + 2) → Fin d) → ℂ}
    (h : HasOBCRep d ψ) :
    ∃ (b : Fin (n + 2) → ℕ) (Q : Fin (n + 1) → Fin d → Matrix (Fin d) (Fin d) ℂ)
      (r' : Fin d → ℂ),
      (∀ p i, IsRowSupportedBelow (b p.castSucc) (Q p i)) ∧
      (∀ p, IsIsometryOn (b p.succ) (Q p)) ∧ IsSupportedBelow (b (Fin.last (n + 1))) r' ∧
      ∀ τ, ψ τ = (eval Q (fun p => τ p.succ) *ᵥ r') (τ 0) := by
  obtain ⟨B, rfl⟩ := h
  have hd := B.bondBound_pos
  let Rm : Matrix (Fin d) (Fin d) ℂ := fun j γ => OBCChainTensor.zeroPad B 0 j ⟨0, hd⟩ γ
  obtain ⟨b, Q, r', -, -, -, hrow, -, hiso, hr', hprod⟩ :=
    exists_isometric_chain (n + 1) d le_rfl Rm (fun α _ hα => absurd α.isLt (by omega))
      (fun p => OBCChainTensor.zeroPad B p.succ) (basisVecZero d)
  refine ⟨b, Q, r', hrow, hiso, hr', fun τ => ?_⟩
  rw [← hprod, OBCChainTensor.coeff_eq_eval_zeroPad, eval_succ (OBCChainTensor.zeroPad B),
    mulVec_basisVecZero_apply hd,
    Matrix.mul_apply, Matrix.mul_apply]

/-- **Probabilistic scheme with the ancilla read out as a site.** The states
`τ ↦ (A^{σ₁⋯σ_{n+1}} φ_I)(τ₀)` of the scheme with a `d`-dimensional ancilla and `n + 1` steps,
read out as the site at position `0`, are exactly the open-boundary MPS of bond dimension at most
`d` on `n + 2` sites (arXiv:quant-ph/0608197, lines 1597--1615). -/
theorem hasOBCRep_iff_exists_eq_jointState {n : ℕ} {ψ : (Fin (n + 2) → Fin d) → ℂ} :
    HasOBCRep d ψ ↔ ∃ (U : Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ)
      (φI : Fin d → ℂ), ∀ τ, ψ τ = jointState U φI (fun p => τ p.succ) (τ 0) := by
  constructor
  · intro h
    obtain ⟨b, Q, r', -, -, -, hψ⟩ := exists_isometric_chain_of_hasOBCRep h
    refine ⟨fun k x y => Q (Fin.rev k) x.2 x.1 y.1, r', fun τ => ?_⟩
    rw [hψ]
    simp only [jointState, Fin.rev_rev]
    rfl
  · rintro ⟨U, φI, hψ⟩
    exact hasOBCRep_of_eq_eval _ φI hψ

/-- **Deterministic scheme with the ancilla read out as a site.** The states
`τ ↦ (A^{σ₁⋯σ_{n+1}} φ_I)(τ₀)` of the scheme with a `d`-dimensional ancilla, `n + 1` unitary
steps and a normalized initial ancilla state, read out as the site at position `0`, are exactly
the normalized open-boundary MPS of bond dimension at most `d` on `n + 2` sites
(arXiv:quant-ph/0608197, lines 1597--1615). -/
theorem hasOBCRep_and_norm_iff_exists_unitary_eq_jointState {n : ℕ}
    {ψ : (Fin (n + 2) → Fin d) → ℂ} :
    star ψ ⬝ᵥ ψ = 1 ∧ HasOBCRep d ψ ↔
      ∃ U : Fin (n + 1) → Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ,
        (∀ k, U k ∈ Matrix.unitaryGroup (Fin d × Fin d) ℂ) ∧ ∃ φI : Fin d → ℂ,
          star φI ⬝ᵥ φI = 1 ∧ ∀ τ, ψ τ = jointState U φI (fun p => τ p.succ) (τ 0) := by
  constructor
  · rintro ⟨hn, h⟩
    obtain ⟨b, Q, r', hrow, hiso, hr', hψ⟩ := exists_isometric_chain_of_hasOBCRep h
    have hext : ∀ p, ∃ V ∈ Matrix.unitaryGroup (Fin d × Fin d) ℂ,
        ∀ i α β, β.val < b p.succ → V (α, i) (β, 0) = Q p i α β :=
      fun p => exists_unitary_extension (hiso p)
    choose V hV hVQ using hext
    refine ⟨fun k => V (Fin.rev k), fun k => hV _, r', ?_, fun τ => ?_⟩
    · rw [← hn, star_dotProduct_self_of_eq (fun τ' => eval Q τ' *ᵥ r') hψ]
      exact (sum_normSq_eval_mulVec b Q hrow hiso r' hr').symm
    · rw [hψ]
      simp only [jointState, Fin.rev_rev]
      rw [eval_mulVec_congr b Q (fun p => stepMatrix (V p)) hrow
        (fun p i α β h => hVQ p i α β h) r' hr']
  · rintro ⟨U, hU, φI, hI, hψ⟩
    refine ⟨?_, hasOBCRep_of_eq_eval _ φI hψ⟩
    rw [star_dotProduct_self_of_eq (jointState U φI) hψ, ← hI]
    exact sum_normSq_eval_mulVec (fun _ => d) (fun p => stepMatrix (U (Fin.rev p)))
      (fun _ _ α _ hα => absurd α.isLt (by omega)) (fun p => isIsometryOn_stepMatrix (hU _)) _
      (fun β hβ => absurd β.isLt (by omega))

/-! ### Starting the ancilla in `|0⟩` -/

omit [NeZero d] in
/-- Preceding a step by `W` on the ancilla multiplies its induced matrices by `W` on the right. -/
theorem stepMatrix_mul_kronecker_one [NeZero d] {D : ℕ}
    (U : Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ) (W : Matrix (Fin D) (Fin D) ℂ) (i : Fin d) :
    stepMatrix (U * (W ⊗ₖ (1 : Matrix (Fin d) (Fin d) ℂ))) i = stepMatrix U i * W := by
  ext α β
  simp only [stepMatrix, Matrix.mul_apply, Matrix.kroneckerMap_apply, Fintype.sum_prod_type]
  refine Finset.sum_congr rfl fun γ _ => ?_
  rw [Finset.sum_eq_single (0 : Fin d) (fun j _ hj => by simp [Matrix.one_apply_ne hj])
    (by simp)]
  simp

omit [NeZero d] in
/-- Absorbing an operation `W` on the initial ancilla state into the first step. -/
theorem jointState_update_zero [NeZero d] {D n : ℕ}
    (U : Fin (n + 1) → Matrix (Fin D × Fin d) (Fin D × Fin d) ℂ) (W : Matrix (Fin D) (Fin D) ℂ)
    (φ : Fin D → ℂ) (τ : Fin (n + 1) → Fin d) :
    jointState (Function.update U 0 (U 0 * (W ⊗ₖ (1 : Matrix (Fin d) (Fin d) ℂ)))) φ τ =
      jointState U (W *ᵥ φ) τ := by
  have hrest : (fun p : Fin n => stepMatrix
      (Function.update U 0 (U 0 * (W ⊗ₖ (1 : Matrix (Fin d) (Fin d) ℂ))) (Fin.rev p.castSucc))) =
      fun p => stepMatrix (U (Fin.rev p.castSucc)) := by
    funext p
    rw [Function.update_of_ne (by simp [Fin.rev_castSucc, Fin.succ_ne_zero])]
  simp only [jointState]
  rw [eval_succ', eval_succ' (fun p => stepMatrix (U (Fin.rev p))), hrest, Fin.rev_last,
    Function.update_self, stepMatrix_mul_kronecker_one, ← Matrix.mul_assoc,
    ← Matrix.mulVec_mulVec]

/-- A unitary sending `|0⟩` to a given unit vector. -/
private theorem exists_unitary_mulVec_basisVecZero {φ : Fin d → ℂ} (hφ : star φ ⬝ᵥ φ = 1) :
    ∃ W ∈ Matrix.unitaryGroup (Fin d) ℂ, W *ᵥ basisVecZero d = φ := by
  classical
  have hd : 0 < d := Nat.pos_of_neZero d
  have hV : (Matrix.of fun (i : Fin d) (_ : Unit) => φ i).IsIsometry := by
    ext
    simpa [Matrix.mul_apply, dotProduct, mul_comm] using hφ
  obtain ⟨W, hW, hWφ⟩ := Matrix.exists_mem_unitaryGroup_apply_embedding_eq hV
    ⟨fun _ => (⟨0, hd⟩ : Fin d), fun _ _ _ => rfl⟩
  refine ⟨W, hW, funext fun i => ?_⟩
  rw [mulVec_basisVecZero_apply hd]
  simpa using hWφ i ()

/-! ### Theorem "Sequential generation without ancilla" -/

/-- **Theorem "Sequential generation without ancilla", probabilistic scheme**
(arXiv:quant-ph/0608197, lines 1589--1595): on a chain of at least two sites, a
vector is generated, up to normalization, by a probabilistic sequential scheme
without ancilla iff it has an open-boundary MPS representation of bond dimension
at most `d`. -/
theorem isProbabilisticallyGeneratedWithoutAncilla_iff {n : ℕ}
    {ψ : (Fin (n + 2) → Fin d) → ℂ} :
    IsProbabilisticallyGeneratedWithoutAncilla ψ ↔ HasOBCRep d ψ := by
  rw [hasOBCRep_iff_exists_eq_jointState]
  constructor
  · rintro ⟨U, rfl⟩
    exact ⟨_, _, noAncillaState_eq_jointState n U⟩
  · rintro ⟨U, φI, hψ⟩
    let U' := Function.update U 0 (U 0 * (colMat φI ⊗ₖ (1 : Matrix (Fin d) (Fin d) ℂ)))
    refine ⟨fun k => swapRows (U' k), funext fun τ => ?_⟩
    rw [hψ, noAncillaState_eq_jointState]
    simp only [swapRows_swapRows, U', jointState_update_zero]
    congr 2
    funext α
    rw [mulVec_basisVecZero_apply (Nat.pos_of_neZero d), colMat]
    simp

/-- **Theorem "Sequential generation without ancilla", deterministic scheme**
(arXiv:quant-ph/0608197, lines 1589--1595 and 1608--1615): on a chain of at least two sites, a
vector is generated by a deterministic sequential scheme without ancilla iff it
is normalized and has an open-boundary MPS representation of bond dimension at
most `d`. -/
theorem isDeterministicallyGeneratedWithoutAncilla_iff {n : ℕ}
    {ψ : (Fin (n + 2) → Fin d) → ℂ} :
    IsDeterministicallyGeneratedWithoutAncilla ψ ↔ star ψ ⬝ᵥ ψ = 1 ∧ HasOBCRep d ψ := by
  rw [hasOBCRep_and_norm_iff_exists_unitary_eq_jointState]
  constructor
  · rintro ⟨U, hU, rfl⟩
    exact ⟨_, fun k => swapRows_mem_unitaryGroup (hU k), _,
      star_basisVecZero_dotProduct_self (Nat.pos_of_neZero d), noAncillaState_eq_jointState n U⟩
  · rintro ⟨U, hU, φI, hI, hψ⟩
    obtain ⟨W, hW, hWφ⟩ := exists_unitary_mulVec_basisVecZero hI
    let U' := Function.update U 0 (U 0 * (W ⊗ₖ (1 : Matrix (Fin d) (Fin d) ℂ)))
    have hU' : ∀ k, U' k ∈ Matrix.unitaryGroup (Fin d × Fin d) ℂ := fun k => by
      by_cases hk : k = 0
      · subst hk
        simp only [U', Function.update_self]
        exact Submonoid.mul_mem _ (hU 0) (Matrix.kronecker_mem_unitary hW (one_mem _))
      · simp only [U', Function.update_of_ne hk]
        exact hU k
    refine ⟨fun k => swapRows (U' k), fun k => swapRows_mem_unitaryGroup (hU' k),
      funext fun τ => ?_⟩
    rw [hψ, noAncillaState_eq_jointState]
    simp only [swapRows_swapRows, U', jointState_update_zero, hWφ]

end MPSPreparation
