/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.Symmetry.InfinitesimalPhysicalCovariance
import QICLean.Analysis.KroneckerExponential
import QICLean.Analysis.CoisometricCompression

/-!
# Coherent continuous physical covariance

Source: arXiv:0802.0447, lines 331–359.
The construction fixes one generator. It does not make unrelated pointwise
choices of Kraus-unitary extensions and imposes no Kraus-independence condition.
-/

open scoped Matrix BigOperators Kronecker Matrix.Norms.L2Operator
open NormedSpace
namespace MPSTensor
variable {d D : ℕ}

/-- Hermitian virtual matrices induce Hermitian doubled generators.
Source: arXiv:0802.0447, lines 352–359. -/
theorem rowAdjointGenerator_isHermitian
    (H : Matrix (Fin D) (Fin D) ℂ) (hH : H.IsHermitian) :
    (rowAdjointGenerator H).IsHermitian := by
  have hconj : (H.map (starRingEnd ℂ)).IsHermitian :=
    hH.map (starRingEnd ℂ) (fun _ => rfl)
  change (rowAdjointGenerator H)ᴴ = rowAdjointGenerator H
  simp only [rowAdjointGenerator, Matrix.conjTranspose_sub,
    Matrix.conjTranspose_kronecker, Matrix.conjTranspose_one, hH.eq, hconj.eq]

/-- The doubled finite action is exactly virtual conjugation on each Kraus
column. Source: arXiv:0802.0447, lines 331–350. -/
theorem doubledVirtual_mul_krausRowMatrix_apply
    (A : MPSTensor d D) (V : Matrix (Fin D) (Fin D) ℂ)
    (a b : Fin D) (i : Fin d) :
    ((V ⊗ₖ V.map (starRingEnd ℂ)) * krausRowMatrix A) (a, b) i =
      (V * A i * Vᴴ) a b := by
  simp only [Matrix.mul_apply, krausRowMatrix, Fintype.sum_prod_type,
    Matrix.kronecker_apply, Matrix.map_apply, Matrix.conjTranspose_apply,
    Finset.sum_mul]
  rw [Finset.sum_comm]
  simp only [starRingEnd_apply, mul_comm, mul_assoc]

/-- The physical exponential generated by the transpose lift intertwines
with the virtual exponential at every real parameter.
Source: arXiv:0802.0447, lines 343–359. -/
theorem condC1_hermitianUnitaryPath_of_intertwiner
    (A : MPSTensor d D) (H : Matrix (Fin D) (Fin D) ℂ)
    (K₀ : Matrix (Fin d) (Fin d) ℂ)
    (hFK : krausRowMatrix A * K₀ = rowAdjointGenerator H * krausRowMatrix A)
    (t : ℝ) :
    CondC1 A (Matrix.hermitianUnitaryPath K₀ᵀ t)
      (Matrix.hermitianUnitaryPath H t) := by
  have hscaled : krausRowMatrix A * (t • (Complex.I • K₀)) =
      (t • (Complex.I • rowAdjointGenerator H)) * krausRowMatrix A := by
    simpa only [Matrix.mul_smul, Matrix.smul_mul] using
      congrArg (fun M => t • (Complex.I • M)) hFK
  have he := Matrix.mul_exp_eq_exp_mul_of_mul_eq _ _ _ hscaled
  rw [show rowAdjointGenerator H =
    H ⊗ₖ (1 : Matrix (Fin D) (Fin D) ℂ) -
      (1 : Matrix (Fin D) (Fin D) ℂ) ⊗ₖ H.map (starRingEnd ℂ) from rfl,
    Matrix.exp_rowCommutator] at he
  have ht : Matrix.hermitianUnitaryPath K₀ᵀ t =
      (Matrix.hermitianUnitaryPath K₀ t)ᵀ := by
    simp only [Matrix.hermitianUnitaryPath, ← Matrix.exp_transpose,
      Matrix.transpose_smul]
  intro i
  ext a b
  rw [ht, ← krausRowMatrix_mul_apply]
  change (krausRowMatrix A * exp (t • (Complex.I • K₀))) (a, b) i = _
  rw [he, doubledVirtual_mul_krausRowMatrix_apply]

/-- The infinitesimal transfer criterion produces one Hermitian physical
generator and hence a coherent continuous physical action.
Source: arXiv:0802.0447, lines 352–359. Scalar virtual matrices are still
allowed here; effective nontriviality is asserted only in the final theorem. -/
theorem exists_hermitian_physical_generator
    (A : MPSTensor d D) (H : Matrix (Fin D) (Fin D) ℂ) (hH : H.IsHermitian)
    (hComm : Commute (rowAdjointGenerator H) (rowTransferMatrix A)) :
    ∃ K : Matrix (Fin d) (Fin d) ℂ,
      K.IsHermitian ∧
      (∀ i, ∑ j, K i j • A j = H * A i - A i * H) ∧
      ∀ t : ℝ, CondC1 A (Matrix.hermitianUnitaryPath K t)
        (Matrix.hermitianUnitaryPath H t) := by
  have hGram := (commute_rowTransferMatrix_iff_commute_krausGram A H hH).mp hComm
  obtain ⟨K₀, hK₀, hFK, _⟩ :=
    Matrix.exists_hermitian_intertwiner_of_commute_mul_conjTranspose
      (krausRowMatrix A) (rowAdjointGenerator H) (rowAdjointGenerator_isHermitian H hH)
      hGram
  refine ⟨K₀ᵀ, ?_, infinitesimal_physical_covariance_of_intertwiner A H hH K₀ hFK,
    condC1_hermitianUnitaryPath_of_intertwiner A H K₀ hFK⟩
  exact hK₀.transpose

end MPSTensor
