/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.Symmetry.GappedInteractionPath
import TNLean.MPS.Symmetry.Defs
import TNLean.MPS.ParentHamiltonian.Defs

/-!
# Symmetric phases within continuous exact MPS families

The phase condition is stated in terms of physical interactions and their
ground-state lines. Blocking, scalar changes of the endpoint on-site actions,
and isometric inclusion of the whole endpoint physical spaces are allowed.
No virtual representation or factor system occurs in the condition.

**Scope restriction (continuous exact MPS ground states):** The additional
MPS condition concerns the regime of arXiv:1010.3732, Section II.F.2,
lines 930–954, rather than arbitrary gapped Hamiltonian paths. A continuous
finite-dimensional tensor family represents the ground lines, while its
minimal injective bond dimension may change. The implication from a physical
gap to continuous canonical bond data is not included as an assumption;
its proof remains open, as recorded in
`docs/paper-gaps/spc11_spt_interpolation_upper_range.tex`.
-/

open scoped Matrix

namespace MPSTensor

/-- Equality of the lines generated by the matrix product vectors at every
positive chain length. Normalization may depend on the chain length.
Source context: arXiv:1010.3732, Section II.F.2, lines 930–954. -/
def SamePositiveMpvRay {d D₀ D₁ : ℕ} (A : MPSTensor d D₀)
    (B : MPSTensor d D₁) : Prop :=
  ∀ N : ℕ, 0 < N →
    Submodule.span ℂ {(mpv A : (Fin N → Fin d) → ℂ)} =
      Submodule.span ℂ {(mpv B : (Fin N → Fin d) → ℂ)}

/-- Reflexivity of positive-length MPS ray equality. -/
theorem SamePositiveMpvRay.refl {d D : ℕ} (A : MPSTensor d D) :
    SamePositiveMpvRay A A := fun _ _ => rfl

/-- Symmetry of positive-length MPS ray equality. -/
theorem SamePositiveMpvRay.symm {d D₀ D₁ : ℕ}
    {A : MPSTensor d D₀} {B : MPSTensor d D₁}
    (h : SamePositiveMpvRay A B) : SamePositiveMpvRay B A :=
  fun N hN => (h N hN).symm

/-- Transitivity of positive-length MPS ray equality. -/
theorem SamePositiveMpvRay.trans {d D₀ D₁ D₂ : ℕ}
    {A : MPSTensor d D₀} {B : MPSTensor d D₁} {C : MPSTensor d D₂}
    (hAB : SamePositiveMpvRay A B) (hBC : SamePositiveMpvRay B C) :
    SamePositiveMpvRay A C := fun N hN => (hAB N hN).trans (hBC N hN)

/-- A continuous exact MPS realization of the unique ground lines of a
physical interaction path. The common tensor dimension is only an ambient
bound: the injective representative at each parameter can have a different
positive bond dimension. Source context: arXiv:1010.3732, Section II.F.2,
lines 930–954 and Appendix C, lines 2653–2717. -/
structure ExactMPSGroundPath {G : Type} [Group G] {d : ℕ}
    {U : G →* Matrix.unitaryGroup (Fin d) ℂ}
    {h₀ h₁ : MPOTensor.ChainOperator d 2}
    (P : SymmetricGappedInteractionPath U h₀ h₁) where
  /-- Finite common ambient bond dimension; source Section II.F.2. -/
  bondDimension : ℕ
  /-- The ambient dimension is nonzero; source Section II.F.2. -/
  bondDimension_pos : 0 < bondDimension
  /-- Tensors representing the ground-state rays; source lines 930–954. -/
  tensor : ℝ → MPSTensor d bondDimension
  /-- Continuity of the exact MPS family; source lines 930–954. -/
  continuous : ContinuousOn tensor (Set.Icc (0 : ℝ) 1)
  /-- A nonzero one-site injective representative of each ray family after
  the chosen blocking. Its dimension need not be locally constant.
  Source context: Section II.F.2 and Appendix C, lines 2653–2717. -/
  injective_representative : ∀ γ ∈ Set.Icc (0 : ℝ) 1,
    ∃ D : ℕ, 0 < D ∧ D ≤ bondDimension ∧ ∃ A : MPSTensor d D,
      Kraus.IsInjective A ∧ SamePositiveMpvRay (tensor γ) A
  /-- The periodic vectors are nonzero at every positive length; source
  Section II.F.2, the unique ground-state MPS. -/
  nonzero : ∀ γ ∈ Set.Icc (0 : ℝ) 1, ∀ N : ℕ, 0 < N →
    (mpv (tensor γ) : (Fin N → Fin d) → ℂ) ≠ 0
  /-- At every ring length at least two, the least-energy eigenspace is
  exactly the MPS line. No exact symmetry of the tensor is assumed.
  Source: Section II.F.2, lines 930–954. -/
  ground_line : ∀ γ ∈ Set.Icc (0 : ℝ) 1, ∀ (N : ℕ) (hN : 2 ≤ N),
    ∃ E : ℝ,
      (E : ℂ) ∈ spectrum ℂ (interactionHamiltonian (P.interaction γ) hN) ∧
      (∀ z ∈ spectrum ℂ (interactionHamiltonian (P.interaction γ) hN), E ≤ z.re) ∧
      LinearMap.ker (Matrix.toEuclideanLin
        (interactionHamiltonian (P.interaction γ) hN - (E : ℂ) • 1)) =
        Submodule.span ℂ
          {(WithLp.linearEquiv 2 ℂ ((Fin N → Fin d) → ℂ)).symm (mpv (tensor γ))}

/-- Parameter reversal preserves an exact MPS ground-state realization.
Source context: arXiv:1010.3732, Sections II.C and II.F.2. -/
def ExactMPSGroundPath.reverse {G : Type} [Group G] {d : ℕ}
    {U : G →* Matrix.unitaryGroup (Fin d) ℂ}
    {h₀ h₁ : MPOTensor.ChainOperator d 2}
    {P : SymmetricGappedInteractionPath U h₀ h₁} (Q : ExactMPSGroundPath P) :
    ExactMPSGroundPath P.reverse where
  bondDimension := Q.bondDimension
  bondDimension_pos := Q.bondDimension_pos
  tensor γ := Q.tensor (1 - γ)
  continuous := Q.continuous.comp
    (continuous_const.sub continuous_id).continuousOn
    (fun _ hγ => Set.Icc.one_sub_mem hγ)
  injective_representative _γ hγ := Q.injective_representative _ (Set.Icc.one_sub_mem hγ)
  nonzero _γ hγ := Q.nonzero _ (Set.Icc.one_sub_mem hγ)
  ground_line _γ hγ := Q.ground_line _ (Set.Icc.one_sub_mem hγ)

/-- Independent symmetric phase equivalence in the continuous exact MPS
regime, with a common blocking length, endpoint character changes, and full
orthogonal physical isometries. The endpoints are the canonical two-site parents of
the blocked, included tensors. Source: arXiv:1010.3732, Sections II.C.1–2,
lines 407–466, including the orthogonal endpoint summands in lines 447–465,
and Section II.F.2, lines 930–954.

This predicate does not assert the classification theorem or impose a
continuous virtual action. -/
def IsSameExactMPSGappedPhase {G : Type} [Group G] {d₀ d₁ D₀ D₁ : ℕ}
    (A₀ : MPSTensor d₀ D₀) (A₁ : MPSTensor d₁ D₁)
    (U₀ : G →* Matrix.unitaryGroup (Fin d₀) ℂ)
    (U₁ : G →* Matrix.unitaryGroup (Fin d₁) ℂ) : Prop :=
  ∃ k : ℕ, 0 < k ∧ ∃ m : ℕ,
    ∃ U : G →* Matrix.unitaryGroup (Fin m) ℂ,
    ∃ χ₀ χ₁ : G →* ℂ,
    (∀ g, ‖χ₀ g‖ = 1) ∧ (∀ g, ‖χ₁ g‖ = 1) ∧
    ∃ E₀ : Matrix (Fin m) (Fin (blockPhysDim d₀ k)) ℂ,
    ∃ E₁ : Matrix (Fin m) (Fin (blockPhysDim d₁ k)) ℂ,
    E₀ᴴ * E₀ = 1 ∧ E₁ᴴ * E₁ = 1 ∧ E₀ᴴ * E₁ = 0 ∧
    (∀ g, (U g : Matrix (Fin m) (Fin m) ℂ) * E₀ =
      E₀ * (χ₀ g • blockKron k (U₀ g))) ∧
    (∀ g, (U g : Matrix (Fin m) (Fin m) ℂ) * E₁ =
      E₁ * (χ₁ g • blockKron k (U₁ g))) ∧
    ∃ P : SymmetricGappedInteractionPath U
      (LinearMap.toMatrix' (parentInteraction (rotatePhysical E₀ (blockTensor A₀ k)) 2))
      (LinearMap.toMatrix' (parentInteraction (rotatePhysical E₁ (blockTensor A₁ k)) 2)),
    ∃ Q : ExactMPSGroundPath P,
      SamePositiveMpvRay (Q.tensor 0) (rotatePhysical E₀ (blockTensor A₀ k)) ∧
      SamePositiveMpvRay (Q.tensor 1) (rotatePhysical E₁ (blockTensor A₁ k))

/-- Symmetry of the independent exact MPS phase condition follows by
reversing the physical path and exchanging the endpoint inclusions.
Source context: arXiv:1010.3732, Sections II.C.1–2 and II.F.2. -/
theorem IsSameExactMPSGappedPhase.symm {G : Type} [Group G] {d₀ d₁ D₀ D₁ : ℕ}
    {A₀ : MPSTensor d₀ D₀} {A₁ : MPSTensor d₁ D₁}
    {U₀ : G →* Matrix.unitaryGroup (Fin d₀) ℂ}
    {U₁ : G →* Matrix.unitaryGroup (Fin d₁) ℂ}
    (h : IsSameExactMPSGappedPhase A₀ A₁ U₀ U₁) :
    IsSameExactMPSGappedPhase A₁ A₀ U₁ U₀ := by
  rcases h with ⟨k, hk, m, U, χ₀, χ₁, hχ₀, hχ₁, E₀, E₁,
    hE₀, hE₁, hEorth, hCov₀, hCov₁, P, Q, hQ₀, hQ₁⟩
  have hEorth' : E₁ᴴ * E₀ = 0 := by
    simpa only [Matrix.conjTranspose_mul, Matrix.conjTranspose_conjTranspose,
      Matrix.conjTranspose_zero] using congrArg Matrix.conjTranspose hEorth
  refine ⟨k, hk, m, U, χ₁, χ₀, hχ₁, hχ₀, E₁, E₀,
    hE₁, hE₀, hEorth', hCov₁, hCov₀, P.reverse, Q.reverse, ?_, ?_⟩
  · simpa only [ExactMPSGroundPath.reverse, sub_zero] using hQ₁
  · simpa only [ExactMPSGroundPath.reverse, sub_self] using hQ₀

end MPSTensor
