/-
Copyright (c) 2025 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.ParentHamiltonian.Basic
import TNLean.MPS.ParentHamiltonian.CyclicWindow
import TNLean.Algebra.TracePairing
import TNLean.Wielandt.SpanGrowth.CumulativeToWordSpan

/-!
# Unique ground state for injective MPS parent Hamiltonians

For an injective MPS tensor `A` on a periodic chain, the expected parent-Hamiltonian
ground space is spanned by the MPV state
`σ ↦ tr(A^{σ₀} ⋯ A^{σ_{N-1}})`.

## Overview

The proof combines the intersection property from `IntersectionProperty.lean`
with the periodic boundary condition:

1. **Open chain**: By iterated application of the intersection property,
   any state satisfying all local ground-space conditions has the form
   `ψ(σ) = tr(A^σ · X)` for some boundary matrix `X ∈ M_D(ℂ)`.
   This yields a `D²`-dimensional space.

2. **Periodic chain**: The wrapping window condition (connecting the last and
   first sites) constrains `X`. For injective `A`, the matrices `{A^i}` span
   `M_D(ℂ)`, so the commutation condition forces `X ∝ I`, yielding a
   one-dimensional ground space spanned by the MPV.

## Main results

* `MPSTensor.mpvSubmodule` — the subspace spanned by the MPV
* `MPSTensor.mpv_mem_groundSpace` — the MPV lies in the ground space
* `MPSTensor.chainGroundSpace` — the periodic-chain ground space as intersection
  of cyclic window ground submodules
* `MPSTensor.groundSpace_unique_periodic` — uniqueness on the periodic chain
* `MPSTensor.parentHamiltonian_unique_gs_injective` — uniqueness for `2L₀` sites
* `MPSTensor.parentHamiltonian_unique_gs_normal` — optimal uniqueness for `L₀+1` sites

## References

* [CPGSV21] arXiv:2011.12127, lines 2013–2094 (full argument)
* [FNW92] Sections 3–4
* [PGVWC07] arXiv:quant-ph/0608197, Sections 5–6
-/

open scoped Matrix BigOperators

namespace MPSTensor

variable {d D : ℕ}

/-! ### The MPV submodule -/

/-- The submodule spanned by the MPV state.

On the periodic chain, the MPV state is `σ ↦ tr(A^{σ₀} ⋯ A^{σ_{N-1}})`,
which corresponds to the ground-space map applied to the identity:
`mpv A = groundSpaceMap A N 1`. -/
noncomputable def mpvSubmodule (A : MPSTensor d D) (N : ℕ) :
    Submodule ℂ (NSiteSpace d N) :=
  Submodule.span ℂ {mpv A}

/-- The MPV is the ground-space map applied to the identity matrix. -/
theorem mpv_eq_groundSpaceMap_one (A : MPSTensor d D) (N : ℕ) :
    (mpv A : NSiteSpace d N) = groundSpaceMap A N 1 := by
  ext σ
  simp [mpv, coeff, groundSpaceMap_apply]

/-- The MPV state lies in the ground space `G_N(A)` for any `N`. -/
theorem mpv_mem_groundSpace (A : MPSTensor d D) (N : ℕ) :
    (mpv A : NSiteSpace d N) ∈ groundSpace A N := by
  rw [groundSpace, LinearMap.mem_range]
  exact ⟨1, by ext σ; simp [groundSpaceMap_apply, mpv, coeff]⟩

/-! ### Periodic chain ground space

On a periodic chain of `N` sites, the ground space of the parent Hamiltonian
is the set of states whose restriction to every cyclic window of `L` consecutive
sites lies in `G_L(A)`.

The full periodic-chain window restriction still depends on the chain-level
embedding API. We therefore expose only the chain ground-space interface for
now, and will define it from local window constraints once the operator
formalization lands. -/

-- TODO(parent-hamiltonian): define `chainGroundSpace` as the intersection of
-- cyclic window ground submodules once the periodic window embedding API lands.

/-- The periodic chain ground space: the set of states `ψ` on `N` sites such
that every cyclic window of `L` consecutive sites restricts into `G_L(A)`.

When `N = 0` or `L > N`, we return `⊤` as a degenerate convention. -/
noncomputable def chainGroundSpace (A : MPSTensor d D) (L N : ℕ) :
    Submodule ℂ (NSiteSpace d N) :=
  if hN : 0 < N ∧ L ≤ N then
    ⨅ (i : Fin N) (τ : Fin N → Fin d),
      (groundSpace A L).comap (cyclicRestrictₗ hN.1 L i τ)
  else ⊤

/-- The MPV state is in the chain ground space.

The proof uses trace cyclicity: for each cyclic window at position `i`, the
restriction of the MPV to that window equals `groundSpaceMap A L X_τ` where
`X_τ` is the product of `A`-matrices at outside positions.

**Status**: requires cyclic list decomposition and trace cyclicity argument. -/
theorem mpv_mem_chainGroundSpace (A : MPSTensor d D) (L N : ℕ)
    (hN : 0 < N) (hLN : L ≤ N) :
    (mpv A : NSiteSpace d N) ∈ chainGroundSpace A L N := by
  rw [chainGroundSpace, dif_pos ⟨hN, hLN⟩]
  simp only [Submodule.mem_iInf, Submodule.mem_comap]
  intro i τ
  simpa [cyclicRestrictₗ_apply, cyclicCfg, replaceWindow] using
    mpv_window_mem_groundSpace A L N hLN i τ

/-! ### Unique ground state -/

/-- A submodule has a unique ground state (up to scalar) if its dimension is exactly 1. -/
def HasUniqueGroundState {V : Type*} [AddCommGroup V] [Module ℂ V]
    (S : Submodule ℂ V) : Prop :=
  Module.finrank ℂ S = 1

/-- Characterization: a unique ground state is generated by a single nonzero vector. -/
theorem hasUniqueGroundState_iff_proportional {V : Type*} [AddCommGroup V] [Module ℂ V]
    {S : Submodule ℂ V} [FiniteDimensional ℂ S] :
    HasUniqueGroundState S ↔
      ∃ ψ₀ : S, ψ₀ ≠ 0 ∧ ∀ ψ : S, ∃ c : ℂ, ψ = c • ψ₀ := by
  constructor
  · intro hS
    have hpos : 0 < Module.finrank ℂ S := by
      rw [hS]
      norm_num
    obtain ⟨ψ₀, hψ₀⟩ := Module.finrank_pos_iff_exists_ne_zero.mp hpos
    refine ⟨ψ₀, hψ₀, ?_⟩
    have hgen : ∀ ψ : S, ∃ c : ℂ, c • ψ₀ = ψ :=
      (finrank_eq_one_iff_of_nonzero' ψ₀ hψ₀).mp hS
    intro ψ
    obtain ⟨c, hc⟩ := hgen ψ
    exact ⟨c, hc.symm⟩
  · rintro ⟨ψ₀, hψ₀, hgen⟩
    exact (finrank_eq_one_iff_of_nonzero' ψ₀ hψ₀).2 fun ψ => by
      obtain ⟨c, hc⟩ := hgen ψ
      exact ⟨c, hc.symm⟩

/-! ### Helper: MPV nonvanishing for block-injective tensors -/

/-- If all products of some positive length `k` are zero and `A` is `L₀`-block-injective
with `L₀ > 0`, we reach a contradiction.

**Descent argument**: if `k ≤ L₀`, factor every length-`L₀` word through a zero
length-`k` prefix; if `k > L₀`, use `wordSpan A L₀ = M_D` with `M = 1` to show
all length-(`k − L₀`) products are zero, then recurse. -/
private theorem allZero_contradiction [NeZero D]
    {A : MPSTensor d D} {L₀ : ℕ} (hInj : IsNBlkInjective A L₀) (hL₀ : 0 < L₀)
    {k : ℕ} (hk : 0 < k)
    (hzero : ∀ w : List (Fin d), w.length = k → evalWord A w = 0) : False := by
  have hws : wordSpan A L₀ = ⊤ := (wordSpan_eq_top_iff_isNBlkInjective A L₀).mpr hInj
  -- Strong induction on k.
  suffices ∀ k, 0 < k → (∀ w : List (Fin d), w.length = k → evalWord A w = 0) → False from
    this k hk hzero
  intro k
  induction k using Nat.strongRecOn with
  | ind k ih =>
    intro hk_pos hk_zero
    by_cases hkL : k ≤ L₀
    · -- Case k ≤ L₀: factor every length-L₀ word as (take k) ++ (drop k).
      have hws_bot : wordSpan A L₀ = ⊥ := by
        rw [eq_bot_iff, wordSpan]
        apply Submodule.span_le.mpr
        rintro _ ⟨σ, rfl⟩
        rw [SetLike.mem_coe, Submodule.mem_bot]
        have hsplit := List.take_append_drop k (List.ofFn σ)
        have htake_len : (List.take k (List.ofFn σ)).length = k := by
          rw [List.length_take]; simp; omega
        calc evalWord A (List.ofFn σ)
            = evalWord A (List.take k (List.ofFn σ) ++
                List.drop k (List.ofFn σ)) := by rw [hsplit]
          _ = evalWord A (List.take k (List.ofFn σ)) *
                evalWord A (List.drop k (List.ofFn σ)) := evalWord_append ..
          _ = 0 * evalWord A (List.drop k (List.ofFn σ)) := by
                rw [hk_zero _ htake_len]
          _ = 0 := zero_mul _
      exact absurd (hws ▸ hws_bot) top_ne_bot
    · -- Case k > L₀: use span = M_D and M = 1 to descend to k - L₀.
      push Not at hkL
      have hkL₀_pos : 0 < k - L₀ := by omega
      apply ih (k - L₀) (by omega) hkL₀_pos
      intro w₂ hw₂
      -- For each σ₁ of length L₀: evalWord A (ofFn σ₁) * evalWord A w₂ = 0.
      have hmul_zero : ∀ σ₁ : Fin L₀ → Fin d,
          evalWord A (List.ofFn σ₁) * evalWord A w₂ = 0 := by
        intro σ₁
        have hlen : (List.ofFn σ₁ ++ w₂).length = k := by simp [hw₂]; omega
        have := hk_zero _ hlen
        rwa [evalWord_append] at this
      -- The map M ↦ M * evalWord A w₂ vanishes on wordSpan A L₀ = ⊤.
      have hright : LinearMap.mulRight ℂ (evalWord A w₂) = 0 := by
        apply LinearMap.ext_on_range
          (v := fun σ : Fin L₀ → Fin d => evalWord A (List.ofFn σ))
          (hv := by rwa [← wordSpan])
        intro σ₁
        simp [LinearMap.mulRight_apply, hmul_zero σ₁]
      -- Taking M = 1: evalWord A w₂ = 0.
      have h1 : (1 : Matrix (Fin D) (Fin D) ℂ) * evalWord A w₂ = 0 :=
        show LinearMap.mulRight ℂ (evalWord A w₂) 1 = 0 by rw [hright]; simp
      simpa using h1

/-- For a block-injective tensor, the MPV is nonzero on chains of sufficient length.

Assuming `mpv = 0` (all trace products of length `N` vanish), factor through
`wordSpan A L₀ = M_D` to force all length-(`N − L₀`) products to zero, then
`allZero_contradiction` gives the contradiction. -/
theorem mpv_ne_zero_of_isNBlkInjective {A : MPSTensor d D} [NeZero D]
    {L₀ : ℕ} (hInj : IsNBlkInjective A L₀) (hL₀ : 0 < L₀)
    {N : ℕ} (hN : L₀ + 1 ≤ N) :
    (mpv A : NSiteSpace d N) ≠ 0 := by
  have hws : wordSpan A L₀ = ⊤ := (wordSpan_eq_top_iff_isNBlkInjective A L₀).mpr hInj
  intro hzero
  -- mpv = 0 means tr(evalWord A (List.ofFn σ)) = 0 for all σ : Fin N → Fin d.
  have htr_zero : ∀ σ : Fin N → Fin d,
      Matrix.trace (evalWord A (List.ofFn σ)) = 0 := by
    intro σ; simpa [mpv, coeff] using congrFun hzero σ
  -- All products of length (N - L₀) are zero by trace nondegeneracy.
  have hprod_zero : ∀ w₂ : List (Fin d), w₂.length = N - L₀ →
      evalWord A w₂ = 0 := by
    intro w₂ hw₂
    -- Show ∀ M, tr(evalWord A w₂ * M) = 0 to get evalWord A w₂ = 0.
    apply trace_mul_right_eq_zero
    intro M
    -- The functional P ↦ tr(P * evalWord A w₂) vanishes on wordSpan A L₀ = ⊤.
    have hφ : (Matrix.traceLinearMap (Fin D) ℂ ℂ).comp
        (LinearMap.mulRight ℂ (evalWord A w₂)) = 0 := by
      apply LinearMap.ext_on_range
        (v := fun σ : Fin L₀ → Fin d => evalWord A (List.ofFn σ))
        (hv := by rwa [← wordSpan])
      intro σ₁
      simp only [LinearMap.comp_apply, LinearMap.mulRight_apply,
        Matrix.traceLinearMap_apply]
      -- tr(evalWord A (List.ofFn σ₁) * evalWord A w₂) = tr(evalWord A (σ₁ ++ w₂))
      rw [← evalWord_append]
      -- This is a trace of a length-N word product, hence 0.
      have hlen : (List.ofFn σ₁ ++ w₂).length = N := by simp [hw₂]; omega
      let σ' : Fin N → Fin d :=
        fun i => (List.ofFn σ₁ ++ w₂).get ⟨i.val, hlen.symm ▸ i.isLt⟩
      have hw_eq : List.ofFn σ' = List.ofFn σ₁ ++ w₂ := by
        apply List.ext_get
        · simp [hw₂]; omega
        · intro i h1 h2; simp [σ']
      rw [← hw_eq]
      exact htr_zero σ'
    -- From hφ: ∀ P, tr(P * evalWord A w₂) = 0. By trace commutativity:
    calc Matrix.trace (evalWord A w₂ * M)
        = Matrix.trace (M * evalWord A w₂) := Matrix.trace_mul_comm ..
      _ = 0 := by
          simpa [Matrix.traceLinearMap_apply] using congrArg (· M) hφ
  exact allZero_contradiction hInj hL₀ (by omega : 0 < N - L₀) hprod_zero

/-! ### Uniqueness theorems -/

/-! ### Helper: NeZero d from IsInjective -/

/-- An injective MPS tensor on `D ≥ 1` bond dimension implies `d ≥ 1`. -/
theorem neZero_d_of_isInjective {A : MPSTensor d D} [NeZero D]
    (hA : IsInjective A) : NeZero d := by
  by_contra h
  simp only [not_neZero] at h
  subst h
  have hempty : Set.range A = ∅ := Set.range_eq_empty_iff.mpr inferInstance
  rw [IsInjective, hempty, Submodule.span_empty] at hA
  exact bot_ne_top hA

/-! ### Helper: wordSpan monotonicity from injectivity -/

/-- For an injective tensor, `wordSpan A k = ⊤` for all `k ≥ 1`. -/
theorem wordSpan_eq_top_of_isInjective {A : MPSTensor d D}
    (hA : IsInjective A) {k : ℕ} (hk : 0 < k) :
    wordSpan A k = ⊤ := by
  have hword1 : wordSpan A 1 = ⊤ := by
    have hRange :
        Set.range (fun σ : Fin 1 → Fin d => evalWord A (List.ofFn σ)) = Set.range A := by
      ext M
      constructor
      · rintro ⟨σ, rfl⟩; exact ⟨σ 0, by simp [evalWord]⟩
      · rintro ⟨i, rfl⟩; exact ⟨fun _ => i, by simp [evalWord]⟩
    change Submodule.span ℂ (Set.range fun σ : Fin 1 → Fin d =>
      evalWord A (List.ofFn σ)) = ⊤
    rw [hRange]; exact hA
  have hone : (1 : Matrix (Fin D) (Fin D) ℂ) ∈ wordSpan A 1 := by
    rw [hword1]; exact Submodule.mem_top
  exact eq_top_iff.mpr (by
    simpa [hword1] using wordSpan_mono'_of_one_mem_wordSpan_one A hone (by omega : 1 ≤ k))

/-! ### Helper: vanishing on all word products implies zero -/

/-- If `X` has the property that `tr(evalWord A w * X) = 0` for all words of
length `k` (with `k ≥ 1` and `A` injective), then `X = 0`. -/
theorem eq_zero_of_trace_evalWord_mul_eq_zero {A : MPSTensor d D}
    (hA : IsInjective A) {k : ℕ} (hk : 0 < k)
    {X : Matrix (Fin D) (Fin D) ℂ}
    (h : ∀ σ : Fin k → Fin d,
      Matrix.trace (evalWord A (List.ofFn σ) * X) = 0) :
    X = 0 := by
  have hwordK : wordSpan A k = ⊤ := wordSpan_eq_top_of_isInjective hA hk
  have hφ :
      (Matrix.traceLinearMap (Fin D) ℂ ℂ).comp (LinearMap.mulRight ℂ X) = 0 := by
    apply LinearMap.ext_on_range
      (v := fun σ : Fin k → Fin d => evalWord A (List.ofFn σ))
    · simpa [wordSpan] using hwordK
    · intro σ
      simp [Matrix.traceLinearMap_apply, h σ]
  exact trace_mul_right_eq_zero fun N => by
    have hNX : Matrix.trace (N * X) = 0 := by
      simpa [Matrix.traceLinearMap_apply] using congrArg (fun f => f N) hφ
    calc Matrix.trace (X * N) = Matrix.trace (N * X) := Matrix.trace_mul_comm X N
    _ = 0 := hNX

/-! ### Uniqueness theorems -/

/-- At the wrapping position `N-1`, the cyclic config's last site is `σ_w 0`. -/
private theorem cyclicCfg_last_eq {N L : ℕ} (hN : 2 ≤ N) (hLN : L ≤ N) (hL : 1 < L)
    (σ_w : Fin L → Fin d) (τ : Fin N → Fin d) :
    cyclicCfg (by omega : 0 < N) L ⟨N - 1, by omega⟩ σ_w τ ⟨N - 1, by omega⟩ =
      σ_w ⟨0, by omega⟩ := by
  simp only [cyclicCfg]
  have hval : (N - 1 : ℕ) + N - (N - 1 : ℕ) = N := by omega
  have hoffset : ((N - 1) + N - (N - 1)) % N = 0 := by
    rw [hval]; exact Nat.mod_self N
  rw [dif_pos (show ((N - 1) + N - (N - 1)) % N < L by rw [hoffset]; omega)]
  congr 1; ext; simp

/-- At the wrapping position `N-1`, sites `0..L-2` get `σ_w(1)..σ_w(L-1)`. -/
private theorem cyclicCfg_window_site {N L : ℕ} (hN : 2 ≤ N) (_hLN : L ≤ N) (hL : 1 < L)
    (σ_w : Fin L → Fin d) (τ : Fin N → Fin d)
    {k : ℕ} (hk : k < L - 1) :
    cyclicCfg (by omega : 0 < N) L ⟨N - 1, by omega⟩ σ_w τ ⟨k, by omega⟩ =
      σ_w ⟨k + 1, by omega⟩ := by
  simp only [cyclicCfg]
  have hoffset : (k + N - (N - 1)) % N = k + 1 := by
    have : k + N - (N - 1) = k + 1 := by omega
    rw [this, Nat.mod_eq_of_lt (by omega)]
  rw [dif_pos (show (k + N - (N - 1)) % N < L by rw [hoffset]; omega)]
  congr 1; ext; simp [hoffset]

/-- At the wrapping position `N-1`, complement sites get τ values. -/
private theorem cyclicCfg_complement_site {N L : ℕ} (hN : 2 ≤ N) (_hLN : L ≤ N) (hL : 1 < L)
    (σ_w : Fin L → Fin d) (τ : Fin N → Fin d)
    {k : ℕ} (hk1 : L - 1 ≤ k) (hk2 : k < N - 1) :
    cyclicCfg (by omega : 0 < N) L ⟨N - 1, by omega⟩ σ_w τ ⟨k, by omega⟩ =
      τ ⟨k, by omega⟩ := by
  simp only [cyclicCfg]
  have hoffset : (k + N - (N - 1)) % N = k + 1 := by
    have : k + N - (N - 1) = k + 1 := by omega
    rw [this, Nat.mod_eq_of_lt (by omega)]
  rw [dif_neg (show ¬((k + N - (N - 1)) % N < L) by rw [hoffset]; omega)]

/-- The evalWord of the cyclic config at position `M` (= `N-1`) on `M+1` sites
decomposes as `evalWord(init) * A(σ_w(0))` where `init` covers sites `0..M-1`. -/
private theorem evalWord_cyclicCfg_snoc {A : MPSTensor d D}
    {M L : ℕ} (hM : 1 ≤ M) (hLN : L ≤ M + 1) (hL : 1 < L)
    (σ_w : Fin L → Fin d) (τ : Fin (M + 1) → Fin d) :
    evalWord A (List.ofFn (cyclicCfg (by omega : 0 < M + 1) L ⟨M, by omega⟩ σ_w τ)) =
    evalWord A (List.ofFn (fun k : Fin M =>
      cyclicCfg (by omega : 0 < M + 1) L ⟨M, by omega⟩ σ_w τ
        (Fin.castSucc k))) *
    A (σ_w ⟨0, by omega⟩) := by
  set cfg := cyclicCfg (by omega : 0 < M + 1) L ⟨M, by omega⟩ σ_w τ
  -- cfg = Fin.snoc init (σ_w 0)
  have hsnoc : cfg = Fin.snoc (fun k : Fin M => cfg (Fin.castSucc k))
      (σ_w ⟨0, by omega⟩) := by
    funext ⟨k, hk⟩
    by_cases hkM : k < M
    · have : (⟨k, hk⟩ : Fin (M + 1)) = Fin.castSucc ⟨k, hkM⟩ := by
        ext; simp [Fin.castSucc]
      rw [this, Fin.snoc_castSucc]
    · have : (⟨k, hk⟩ : Fin (M + 1)) = Fin.last M := by
        ext; simp [Fin.last]; omega
      rw [this, Fin.snoc_last]
      exact cyclicCfg_last_eq (by omega) hLN hL σ_w τ
  rw [show List.ofFn cfg = List.ofFn (Fin.snoc (fun k : Fin M => cfg (Fin.castSucc k))
      (σ_w ⟨0, by omega⟩)) from by rw [← hsnoc]]
  rw [evalWord_ofFn_snoc]

/-- The init part of the cyclic config at position M decomposes into
tail (window sites 1..L-1) and complement (sites L-1..M-1). -/
private theorem init_evalWord_split {A : MPSTensor d D}
    {M L : ℕ} (hM : 1 ≤ M) (hLN : L ≤ M + 1) (hL : 1 < L)
    (σ_w : Fin L → Fin d) (τ : Fin (M + 1) → Fin d) :
    evalWord A (List.ofFn (fun k : Fin M =>
      cyclicCfg (by omega : 0 < M + 1) L ⟨M, by omega⟩ σ_w τ (Fin.castSucc k))) =
    evalWord A (List.ofFn (fun k : Fin (L - 1) => σ_w ⟨k.val + 1, by omega⟩)) *
    evalWord A (List.ofFn (fun k : Fin (M + 1 - L) =>
      τ ⟨k.val + L - 1, by omega⟩)) := by
  rw [← evalWord_append]
  congr 1
  apply List.ext_getElem
  · simp only [List.length_ofFn, List.length_append]; omega
  · intro k hk1 hk2
    simp only [List.length_ofFn] at hk1
    simp only [List.getElem_ofFn]
    by_cases hkL : k < L - 1
    · -- Window site: init(k) = σ_w(k+1)
      rw [List.getElem_append_left (by simp only [List.length_ofFn]; exact hkL),
          List.getElem_ofFn]
      exact cyclicCfg_window_site (by omega) (by omega) hL σ_w τ hkL
    · -- Complement site: init(k) = τ(k)
      rw [List.getElem_append_right (by simp only [List.length_ofFn]; omega),
          List.getElem_ofFn]
      simp only [List.length_ofFn]
      have hcomp := cyclicCfg_complement_site (by omega : 2 ≤ M + 1) hLN hL σ_w τ
        (show L - 1 ≤ k from by omega) (show k < M from by omega)
      -- hcomp is about cyclicCfg ... ⟨k, _⟩, we need it about Fin.castSucc ⟨k, _⟩
      have : (Fin.castSucc (⟨k, by omega⟩ : Fin M) : Fin (M + 1)) =
          ⟨k, by omega⟩ := by ext; simp [Fin.castSucc]
      rw [this] at *
      -- The complement site: cyclicCfg returns τ(k)
      -- After unfolding, offset = k+1 ≥ L, so returns τ
      unfold cyclicCfg
      simp only []
      have hoffset : (k + (M + 1) - M) % (M + 1) = k + 1 := by
        have : k + (M + 1) - M = k + 1 := by omega
        rw [this, Nat.mod_eq_of_lt (by omega)]
      rw [dif_neg (by rw [hoffset]; omega)]
      congr 1; ext; simp; omega

set_option maxHeartbeats 800000 in
private theorem wrapping_window_matEq {A : MPSTensor d D} [NeZero D]
    (hA : IsInjective A) {L : ℕ} (hL : 1 < L) {M : ℕ} (hM : 1 ≤ M) (hLN : L ≤ M + 1)
    {X : Matrix (Fin D) (Fin D) ℂ}
    (Y : (Fin (M + 1) → Fin d) → Matrix (Fin D) (Fin D) ℂ)
    (hY : ∀ τ σ_w, Matrix.trace (evalWord A (List.ofFn
          (cyclicCfg (by omega : 0 < M + 1) L ⟨M, by omega⟩ σ_w τ)) * X) =
        Matrix.trace (evalWord A (List.ofFn σ_w) * Y τ)) :
    ∀ (σ_tail : Fin (L - 1) → Fin d) (τ : Fin (M + 1) → Fin d),
      X * evalWord A (List.ofFn σ_tail) *
        evalWord A (List.ofFn (fun k : Fin (M + 1 - L) =>
          τ ⟨k.val + L - 1, by omega⟩)) =
      evalWord A (List.ofFn σ_tail) * Y τ := by
  -- Trace rotation FIRST (before mkσ to avoid whnf blowup)
  have hTraceRot : ∀ (σ_w : Fin L → Fin d) (τ : Fin (M + 1) → Fin d),
      Matrix.trace (A (σ_w ⟨0, by omega⟩) * X *
        evalWord A (List.ofFn (fun k : Fin M =>
          cyclicCfg (by omega : 0 < M + 1) L ⟨M, by omega⟩ σ_w τ (Fin.castSucc k)))) =
      Matrix.trace (evalWord A (List.ofFn σ_w) * Y τ) := by
    intro σ_w τ
    set P := evalWord A (List.ofFn (fun k : Fin M =>
      cyclicCfg (by omega : 0 < M + 1) L ⟨M, by omega⟩ σ_w τ (Fin.castSucc k)))
    set Aj := A (σ_w ⟨0, by omega⟩)
    calc Matrix.trace (Aj * X * P)
        = Matrix.trace (P * (Aj * X)) := Matrix.trace_mul_comm (Aj * X) P
      _ = Matrix.trace (P * Aj * X) := by rw [← Matrix.mul_assoc]
      _ = Matrix.trace (evalWord A (List.ofFn
            (cyclicCfg (by omega : 0 < M + 1) L ⟨M, by omega⟩ σ_w τ)) * X) := by
          rw [← evalWord_cyclicCfg_snoc hM (by omega) hL σ_w τ]
      _ = Matrix.trace (evalWord A (List.ofFn σ_w) * Y τ) := hY τ σ_w
  -- Build σ_w from j and σ_tail
  let mkσ (j : Fin d) (σ_tail : Fin (L - 1) → Fin d) : Fin L → Fin d :=
    fun k => if h : k.val = 0 then j else σ_tail ⟨k.val - 1, by omega⟩
  -- Properties of mkσ
  have mkσ_zero : ∀ j σ_tail, mkσ j σ_tail ⟨0, by omega⟩ = j := by
    intro j σ_tail; simp [mkσ]
  have mkσ_tail_eq : ∀ j σ_tail,
      (fun k : Fin (L - 1) => (mkσ j σ_tail) ⟨k.val + 1, by omega⟩) = σ_tail := by
    intro j σ_tail; ext ⟨k, hk⟩
    simp [mkσ]
  have mkσ_evalWord : ∀ j σ_tail,
      evalWord A (List.ofFn (mkσ j σ_tail)) =
      A j * evalWord A (List.ofFn σ_tail) := by
    intro j σ_tail
    have hlist : List.ofFn (mkσ j σ_tail) = [j] ++ List.ofFn σ_tail := by
      apply List.ext_getElem
      · simp [List.length_ofFn]; omega
      · intro k hk1 hk2
        simp only [List.length_ofFn] at hk1
        simp only [List.getElem_ofFn]
        by_cases hk0 : k = 0
        · subst hk0; simp [mkσ]
        · rw [List.getElem_append_right (by simp; omega)]
          simp only [List.length_cons, List.length_nil]
          rw [List.getElem_ofFn]
          simp [mkσ, show k ≠ 0 from hk0]
    rw [hlist, evalWord_append]; simp [evalWord_cons, evalWord_nil]
  -- Matrix equation via groundSpaceMap_injective on 1 site
  intro σ_tail τ
  apply groundSpaceMap_injective hA (show 0 < 1 from by omega)
  ext σ₁
  simp only [groundSpaceMap_apply]
  rw [show List.ofFn σ₁ = [σ₁ 0] from by
    apply List.ext_getElem <;> simp]
  simp only [evalWord_cons, evalWord_nil, mul_one]
  have key := hTraceRot (mkσ (σ₁ 0) σ_tail) τ
  rw [mkσ_zero] at key
  rw [init_evalWord_split hM (by omega) hL (mkσ (σ₁ 0) σ_tail) τ] at key
  rw [mkσ_tail_eq] at key
  rw [mkσ_evalWord] at key
  rw [Matrix.mul_assoc (A (σ₁ 0)) X, ← Matrix.mul_assoc X,
      Matrix.mul_assoc (A (σ₁ 0))] at key
  exact key

set_option maxHeartbeats 800000 in
private theorem boundary_matrix_commutes {A : MPSTensor d D} [NeZero D]
    (hA : IsInjective A) {L N : ℕ} (hN : 2 ≤ N) (hL : 1 < L) (hLN : L ≤ N)
    {X : Matrix (Fin D) (Fin D) ℂ}
    (hψ : ∀ (i : Fin N) (τ : Fin N → Fin d),
      cyclicRestrictₗ (by omega : 0 < N) L i τ (groundSpaceMap A N X) ∈
        groundSpace A L) :
    ∀ j : Fin d, X * A j = A j * X := by
  obtain ⟨M, rfl⟩ : ∃ M, N = M + 1 := ⟨N - 1, by omega⟩
  have hM : 1 ≤ M := by omega
  have hN0 : 0 < M + 1 := by omega
  -- Extract Y_τ from wrapping window ground space membership
  have hGS : ∀ τ : Fin (M + 1) → Fin d, ∃ Y : Matrix (Fin D) (Fin D) ℂ,
      ∀ σ_w : Fin L → Fin d,
        Matrix.trace (evalWord A (List.ofFn
          (cyclicCfg hN0 L ⟨M, by omega⟩ σ_w τ)) * X) =
        Matrix.trace (evalWord A (List.ofFn σ_w) * Y) := by
    intro τ
    have hmem := hψ ⟨M, by omega⟩ τ
    rw [groundSpace, LinearMap.mem_range] at hmem
    obtain ⟨Y, hY⟩ := hmem
    refine ⟨Y, fun σ_w => ?_⟩
    have : cyclicRestrictₗ hN0 L ⟨M, by omega⟩ τ (groundSpaceMap A (M + 1) X) σ_w =
        groundSpaceMap A L Y σ_w := by rw [← hY]
    simp only [cyclicRestrictₗ_apply, groundSpaceMap_apply] at this
    exact this
  choose Y hY using hGS
  -- Matrix equation from wrapping_window_matEq
  have hMatEq := wrapping_window_matEq hA hL hM (by omega) Y (fun τ σ_w => hY τ σ_w)
  -- Extend to all M₁ via spanning in σ_tail (wordSpan(L-1) = ⊤)
  have hMatEq2 : ∀ (M₁ : Matrix (Fin D) (Fin D) ℂ) (τ : Fin (M + 1) → Fin d),
      X * M₁ * evalWord A (List.ofFn (fun k : Fin (M + 1 - L) =>
        τ ⟨k.val + L - 1, by omega⟩)) = M₁ * Y τ := by
    intro M₁ τ
    have hfg : (LinearMap.mulLeft ℂ X).comp
        (LinearMap.mulRight ℂ (evalWord A (List.ofFn (fun k : Fin (M + 1 - L) =>
          τ ⟨k.val + L - 1, by omega⟩)))) =
        LinearMap.mulRight ℂ (Y τ) := by
      apply LinearMap.ext_on_range
        (v := fun σ : Fin (L - 1) → Fin d => evalWord A (List.ofFn σ))
      · simpa [wordSpan] using wordSpan_eq_top_of_isInjective hA (by omega : 0 < L - 1)
      · intro σ_tail
        simp only [LinearMap.comp_apply, LinearMap.mulLeft_apply,
                    LinearMap.mulRight_apply]
        rw [← Matrix.mul_assoc]; exact hMatEq σ_tail τ
    have := congrArg (· M₁) hfg
    simp only [LinearMap.comp_apply, LinearMap.mulLeft_apply,
               LinearMap.mulRight_apply] at this
    rw [← Matrix.mul_assoc] at this; exact this
  -- Y τ = X * compProd(τ) (take M₁ = 1)
  have hYeq : ∀ τ : Fin (M + 1) → Fin d,
      Y τ = X * evalWord A (List.ofFn (fun k : Fin (M + 1 - L) =>
        τ ⟨k.val + L - 1, by omega⟩)) := by
    intro τ; have := hMatEq2 1 τ; rw [mul_one, one_mul] at this; exact this.symm
  -- (X * M₁ - M₁ * X) * compProd(τ) = 0 for all M₁, τ
  have hCommComp : ∀ (M₁ : Matrix (Fin D) (Fin D) ℂ) (τ : Fin (M + 1) → Fin d),
      (X * M₁ - M₁ * X) * evalWord A (List.ofFn (fun k : Fin (M + 1 - L) =>
        τ ⟨k.val + L - 1, by omega⟩)) = 0 := by
    intro M₁ τ
    have h1 := hMatEq2 M₁ τ
    rw [hYeq τ, ← Matrix.mul_assoc] at h1
    rw [sub_mul, sub_eq_zero]; exact h1
  -- Conclude: X * M₁ = M₁ * X
  haveI : NeZero d := neZero_d_of_isInjective hA
  have hd : 0 < d := Nat.pos_of_ne_zero (NeZero.ne d)
  have hComm : ∀ M₁ : Matrix (Fin D) (Fin D) ℂ, X * M₁ = M₁ * X := by
    intro M₁
    by_cases hML : M + 1 = L
    · have h0 : M + 1 - L = 0 := by omega
      have := hCommComp M₁ (fun _ => ⟨0, hd⟩)
      simp only [h0, List.ofFn_zero, evalWord_nil, mul_one] at this
      exact sub_eq_zero.mp this
    · have hML' : 0 < M + 1 - L := by omega
      have hφ : LinearMap.mulLeft ℂ (X * M₁ - M₁ * X) = 0 := by
        apply LinearMap.ext_on_range
          (v := fun f : Fin (M + 1 - L) → Fin d => evalWord A (List.ofFn f))
        · simpa [wordSpan] using wordSpan_eq_top_of_isInjective hA hML'
        · intro f
          simp only [LinearMap.mulLeft_apply, LinearMap.zero_apply]
          let τ₀ : Fin (M + 1) → Fin d := fun k =>
            if h : L - 1 ≤ k.val ∧ k.val < M
            then f ⟨k.val - (L - 1), by omega⟩
            else ⟨0, hd⟩
          have hτ₀ : (fun k : Fin (M + 1 - L) => τ₀ ⟨k.val + L - 1, by omega⟩) = f := by
            ext ⟨k, hk⟩; simp only [τ₀]
            rw [dif_pos ⟨by omega, by omega⟩]
            congr 2; ext1; dsimp only; omega
          rw [← hτ₀]; exact hCommComp M₁ τ₀
      have := congrArg (· 1) hφ
      simp only [LinearMap.mulLeft_apply, mul_one, LinearMap.zero_apply] at this
      exact sub_eq_zero.mp this
  intro j; exact hComm (A j)

/-- On a periodic chain, the injective parent-Hamiltonian ground space
coincides with the span of the MPV when the window size satisfies `L ≥ 2`.

For injective tensors, the open-chain intersection argument requires only
a window of at least `2` sites. -/
theorem chainGroundSpace_eq_mpvSubmodule {A : MPSTensor d D} [NeZero D]
    (hA : IsInjective A) {L N : ℕ} (hN : 2 ≤ N) (hL : 1 < L) (hLN : L ≤ N) :
    chainGroundSpace A L N = mpvSubmodule A N := by
  have hN0 : 0 < N := by omega
  haveI : NeZero d := neZero_d_of_isInjective hA
  apply le_antisymm
  · -- ⊆ direction: chainGroundSpace ≤ mpvSubmodule
    intro ψ hψ
    rw [chainGroundSpace, dif_pos ⟨hN0, hLN⟩] at hψ
    simp only [Submodule.mem_iInf, Submodule.mem_comap] at hψ
    -- Step 1: ψ ∈ groundSpace A N (via non-wrapping windows)
    have hψGS : ψ ∈ groundSpace A N := by
      apply contiguous_mem_groundSpace hA hL hLN
      intro s hs τ
      rw [← cyclicRestrictₗ_eq_contiguousRestrictₗ hN0 hLN (show (⟨s, by omega⟩ : Fin N).val + L ≤ N from hs)]
      exact hψ ⟨s, by omega⟩ τ
    -- Step 2: ψ = groundSpaceMap A N X for some X
    rw [groundSpace, LinearMap.mem_range] at hψGS
    obtain ⟨X, hX⟩ := hψGS
    -- Step 3: X commutes with all A j (wrapping window constraint)
    have hComm : ∀ j : Fin d, X * A j = A j * X := by
      apply boundary_matrix_commutes hA hN hL hLN
      intro i τ
      rw [show groundSpaceMap A N X = ψ from hX]
      exact hψ i τ
    -- Step 4: X is scalar (center argument)
    have hCenter : X ∈ Set.center (Matrix (Fin D) (Fin D) ℂ) := by
      rw [Semigroup.mem_center_iff]
      intro M
      have hext : LinearMap.mulLeft ℂ X = LinearMap.mulRight ℂ X := by
        apply LinearMap.ext_on_range (v := A) (hv := hA.span_eq_top)
        intro j
        simp only [LinearMap.mulLeft_apply, LinearMap.mulRight_apply]
        exact hComm j
      have := LinearMap.congr_fun hext M
      simp only [LinearMap.mulLeft_apply, LinearMap.mulRight_apply] at this
      exact this.symm
    rw [Matrix.center_eq_range] at hCenter
    obtain ⟨c, hc⟩ := hCenter
    have hX_eq : X = c • (1 : Matrix (Fin D) (Fin D) ℂ) := by
      rw [← hc, Matrix.scalar_apply, ← Matrix.smul_one_eq_diagonal]
    -- Step 5: ψ = c • mpv A
    rw [mpvSubmodule]
    rw [Submodule.mem_span_singleton]
    refine ⟨c, ?_⟩
    rw [← hX]
    ext σ
    simp only [groundSpaceMap_apply, Pi.smul_apply, smul_eq_mul, mpv, coeff]
    rw [hX_eq, Algebra.mul_smul_comm, mul_one, Matrix.trace_smul, smul_eq_mul]
  · -- ⊇ direction: mpvSubmodule ≤ chainGroundSpace
    intro ψ hψ
    rw [mpvSubmodule, Submodule.mem_span_singleton] at hψ
    obtain ⟨c, rfl⟩ := hψ
    exact Submodule.smul_mem _ c (mpv_mem_chainGroundSpace A L N hN0 hLN)

/-- On a periodic chain, the normal parent-Hamiltonian ground space coincides
with the span of the MPV with the reduced window `L > L₀` (instead of `2L₀`).

The normality hypothesis enables the range reduction from `2L₀` to `L₀ + 1`
via the structure theory of normal MPS (peripheral spectrum, canonical form).
See [CPGSV21] arXiv:2011.12127 §IV.C. -/
-- TODO(parent-hamiltonian): derive using the normal-form range reduction and
-- the cyclic-window definition of `chainGroundSpace`.
theorem chainGroundSpace_eq_mpvSubmodule_normal {A : MPSTensor d D} [NeZero D]
    (_hA : IsNormal A) {L₀ : ℕ} (_hInj : IsNBlkInjective A L₀)
    {L N : ℕ} (_hN : 2 ≤ N) (_hL : L₀ < L) (_hLN : L ≤ N) :
    chainGroundSpace A L N = mpvSubmodule A N := by
  sorry

/-- **Unique ground state on the periodic chain** for injective MPS.

For an injective tensor `A` on a periodic chain of `N ≥ 2` sites, the chain ground
space is one-dimensional, spanned by the MPV.

The proof uses the intersection property iteratively:
1. From the intersection property, any state in the chain ground space has the form
   `ψ(σ) = tr(A^σ · X)` for some `X ∈ M_D(ℂ)`.
2. The wrapping window condition (window crossing the periodic boundary) constrains
   `X` to commute with all `A^i`.
3. For injective `A`, the center of `span{A^i} = M_D(ℂ)` consists only of scalars,
   so `X = c · I` and `ψ = c · mpv A`. -/
theorem groundSpace_unique_periodic {A : MPSTensor d D} [NeZero D] (hA : IsInjective A)
    {L N : ℕ} (hN : 2 ≤ N) (hL : 1 < L) (hLN : L ≤ N) :
    HasUniqueGroundState (chainGroundSpace A L N) := by
  rw [HasUniqueGroundState, chainGroundSpace_eq_mpvSubmodule hA hN hL hLN]
  have hmpv : (mpv A : NSiteSpace d N) ≠ 0 := by
    intro hzero
    have hEq :
        groundSpaceMap A N (1 : Matrix (Fin D) (Fin D) ℂ) =
          groundSpaceMap A N (0 : Matrix (Fin D) (Fin D) ℂ) := by
      simpa [mpv_eq_groundSpaceMap_one A N] using hzero
    have h10 : (1 : Matrix (Fin D) (Fin D) ℂ) = 0 :=
      (groundSpaceMap_injective hA (by omega : 0 < N)) hEq
    exact one_ne_zero h10
  simpa [mpvSubmodule] using finrank_span_singleton (K := ℂ) hmpv

/-- **Unique ground state for `L₀`-block-injective tensors on `2L₀` sites**.

If `A` is `L₀`-block-injective with `L₀ > 0`, the parent Hamiltonian with
interaction range `2L₀` on a periodic chain of `N ≥ 2L₀` sites has a unique
ground state.

**Proof sketch**: Rewrite via `chainGroundSpace_eq_mpvSubmodule` (sorry'd),
then use `mpv_ne_zero_of_isNBlkInjective` to show the MPV submodule is 1D. -/
-- TODO(parent-hamiltonian): remove sorry once `chainGroundSpace_eq_mpvSubmodule`
-- is proved. The reduction is:
--   rw [HasUniqueGroundState,
--     chainGroundSpace_eq_mpvSubmodule hA (by omega) (le_refl _) hN]
--   have hmpv := mpv_ne_zero_of_isNBlkInjective hA hL₀ (by omega)
--   simpa [mpvSubmodule] using finrank_span_singleton (K := ℂ) hmpv
theorem parentHamiltonian_unique_gs_injective {A : MPSTensor d D} [NeZero D]
    {L₀ : ℕ} (hA : IsNBlkInjective A L₀) (hL₀ : 0 < L₀)
    {N : ℕ} (hN : 2 * L₀ ≤ N) :
    HasUniqueGroundState (chainGroundSpace A (2 * L₀) N) := by
  sorry

/-- **Optimal unique ground state for normal tensors on `L₀ + 1` sites**.

If `A` is normal and `L₀`-block-injective with `L₀ > 0`, the interaction range
can be reduced from `2L₀` to `L₀ + 1`. The chain ground space with window
`L₀ + 1` on `N ≥ L₀ + 1` sites has a unique ground state.

**Proof sketch**: Rewrite via `chainGroundSpace_eq_mpvSubmodule_normal` (sorry'd),
then use `mpv_ne_zero_of_isNBlkInjective` to show the MPV submodule is 1D. -/
-- TODO(parent-hamiltonian): remove sorry once `chainGroundSpace_eq_mpvSubmodule_normal`
-- is proved. The reduction is:
--   rw [HasUniqueGroundState,
--     chainGroundSpace_eq_mpvSubmodule_normal hA hInj (by omega) (by omega) hN]
--   have hmpv := mpv_ne_zero_of_isNBlkInjective hInj hL₀ hN
--   simpa [mpvSubmodule] using finrank_span_singleton (K := ℂ) hmpv
theorem parentHamiltonian_unique_gs_normal {A : MPSTensor d D} [NeZero D]
    {L₀ : ℕ} (hA : IsNormal A) (hInj : IsNBlkInjective A L₀) (hL₀ : 0 < L₀)
    {N : ℕ} (hN : L₀ + 1 ≤ N) :
    HasUniqueGroundState (chainGroundSpace A (L₀ + 1) N) := by
  sorry

end MPSTensor
