/-
Copyright (c) 2025 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.MPS.ParentHamiltonian.Basic
import TNLean.MPS.ParentHamiltonian.CyclicWindow

/-!
# Unique ground state for injective MPS parent Hamiltonians

For an injective MPS tensor `A` on a periodic chain, the expected parent-Hamiltonian
ground space is spanned by the MPV state
`σ ↦ tr(A^{σ₀} ⋯ A^{σ_{N-1}})`.

## Overview

The proof combines the intersection property from `IntersectionProperty.lean`
with the periodic boundary condition:

1. **Open chain**: By iterated application of the intersection property,
   any state satisfying all local ground-space conditions has the form
   `ψ(σ) = tr(A^σ · X)` for some boundary matrix `X ∈ M_D(ℂ)`.
   This yields a `D²`-dimensional space.

2. **Periodic chain**: The wrapping window condition (connecting the last and
   first sites) constrains `X`. For injective `A`, the matrices `{A^i}` span
   `M_D(ℂ)`, so the commutation condition forces `X ∝ I`, yielding a
   one-dimensional ground space spanned by the MPV.

## Main results

* `MPSTensor.mpvSubmodule` — the subspace spanned by the MPV
* `MPSTensor.mpv_mem_groundSpace` — the MPV lies in the ground space
* `MPSTensor.chainGroundSpace` — the periodic-chain ground space as intersection
  of cyclic window ground submodules
* `MPSTensor.groundSpace_unique_periodic` — uniqueness on the periodic chain
* `MPSTensor.parentHamiltonian_unique_gs_injective` — uniqueness for `2L₀` sites
* `MPSTensor.parentHamiltonian_unique_gs_normal` — optimal uniqueness for `L₀+1` sites

## References

* [CPGSV21] arXiv:2011.12127, lines 2013–2094 (full argument)
* [FNW92] Sections 3–4
* [PGVWC07] arXiv:quant-ph/0608197, Sections 5–6
-/

open scoped Matrix BigOperators

namespace MPSTensor

variable {d D : ℕ}

/-! ### The MPV submodule -/

/-- The submodule spanned by the MPV state.

On the periodic chain, the MPV state is `σ ↦ tr(A^{σ₀} ⋯ A^{σ_{N-1}})`,
which corresponds to the ground-space map applied to the identity:
`mpv A = groundSpaceMap A N 1`. -/
noncomputable def mpvSubmodule (A : MPSTensor d D) (N : ℕ) :
    Submodule ℂ (NSiteSpace d N) :=
  Submodule.span ℂ {mpv A}

/-- The MPV is the ground-space map applied to the identity matrix. -/
theorem mpv_eq_groundSpaceMap_one (A : MPSTensor d D) (N : ℕ) :
    (mpv A : NSiteSpace d N) = groundSpaceMap A N 1 := by
  ext σ
  simp [mpv, coeff, groundSpaceMap_apply]

/-- The MPV state lies in the ground space `G_N(A)` for any `N`. -/
theorem mpv_mem_groundSpace (A : MPSTensor d D) (N : ℕ) :
    (mpv A : NSiteSpace d N) ∈ groundSpace A N := by
  rw [groundSpace, LinearMap.mem_range]
  exact ⟨1, by ext σ; simp [groundSpaceMap_apply, mpv, coeff]⟩

/-! ### Periodic chain ground space

On a periodic chain of `N` sites, the ground space of the parent Hamiltonian
is the set of states whose restriction to every cyclic window of `L` consecutive
sites lies in `G_L(A)`.

The full periodic-chain window restriction still depends on the chain-level
embedding API. We therefore expose only the chain ground-space interface for
now, and will define it from local window constraints once the operator
formalization lands. -/

-- TODO(parent-hamiltonian): define `chainGroundSpace` as the intersection of
-- cyclic window ground submodules once the periodic window embedding API lands.

/-- The periodic chain ground space: the set of states `ψ` on `N` sites such
that every cyclic window of `L` consecutive sites restricts into `G_L(A)`.

When `N = 0` or `L > N`, we return `⊤` as a degenerate convention. -/
noncomputable def chainGroundSpace (A : MPSTensor d D) (L N : ℕ) :
    Submodule ℂ (NSiteSpace d N) :=
  if hN : 0 < N ∧ L ≤ N then
    ⨅ (i : Fin N) (τ : Fin N → Fin d),
      (groundSpace A L).comap (cyclicRestrictₗ hN.1 L i τ)
  else ⊤

/-- The MPV state is in the chain ground space.

The proof uses trace cyclicity: for each cyclic window at position `i`, the
restriction of the MPV to that window equals `groundSpaceMap A L X_τ` where
`X_τ` is the product of `A`-matrices at outside positions.

**Status**: requires cyclic list decomposition and trace cyclicity argument. -/
theorem mpv_mem_chainGroundSpace (A : MPSTensor d D) (L N : ℕ)
    (hN : 0 < N) (hLN : L ≤ N) :
    (mpv A : NSiteSpace d N) ∈ chainGroundSpace A L N := by
  rw [chainGroundSpace, dif_pos ⟨hN, hLN⟩]
  simp only [Submodule.mem_iInf, Submodule.mem_comap]
  intro i τ
  simpa [cyclicRestrictₗ_apply, cyclicCfg, replaceWindow] using
    mpv_window_mem_groundSpace A L N hLN i τ

/-! ### Unique ground state -/

/-- A submodule has a unique ground state (up to scalar) if its dimension is exactly 1. -/
def HasUniqueGroundState {V : Type*} [AddCommGroup V] [Module ℂ V]
    (S : Submodule ℂ V) : Prop :=
  Module.finrank ℂ S = 1

/-- Characterization: a unique ground state is generated by a single nonzero vector. -/
theorem hasUniqueGroundState_iff_proportional {V : Type*} [AddCommGroup V] [Module ℂ V]
    {S : Submodule ℂ V} [FiniteDimensional ℂ S] :
    HasUniqueGroundState S ↔
      ∃ ψ₀ : S, ψ₀ ≠ 0 ∧ ∀ ψ : S, ∃ c : ℂ, ψ = c • ψ₀ := by
  constructor
  · intro hS
    have hpos : 0 < Module.finrank ℂ S := by
      rw [hS]
      norm_num
    obtain ⟨ψ₀, hψ₀⟩ := Module.finrank_pos_iff_exists_ne_zero.mp hpos
    refine ⟨ψ₀, hψ₀, ?_⟩
    have hgen : ∀ ψ : S, ∃ c : ℂ, c • ψ₀ = ψ :=
      (finrank_eq_one_iff_of_nonzero' ψ₀ hψ₀).mp hS
    intro ψ
    obtain ⟨c, hc⟩ := hgen ψ
    exact ⟨c, hc.symm⟩
  · rintro ⟨ψ₀, hψ₀, hgen⟩
    exact (finrank_eq_one_iff_of_nonzero' ψ₀ hψ₀).2 fun ψ => by
      obtain ⟨c, hc⟩ := hgen ψ
      exact ⟨c, hc.symm⟩

/-! ### Helper: MPV nonvanishing for block-injective tensors -/

/-- If all products of some positive length `k` are zero and `A` is `L₀`-block-injective
with `L₀ > 0`, we reach a contradiction.

**Descent argument**: if `k ≤ L₀`, factor every length-`L₀` word through a zero
length-`k` prefix; if `k > L₀`, use `wordSpan A L₀ = M_D` with `M = 1` to show
all length-(`k − L₀`) products are zero, then recurse. -/
private theorem allZero_contradiction [NeZero D]
    {A : MPSTensor d D} {L₀ : ℕ} (hInj : IsNBlkInjective A L₀) (hL₀ : 0 < L₀)
    {k : ℕ} (hk : 0 < k)
    (hzero : ∀ w : List (Fin d), w.length = k → evalWord A w = 0) : False := by
  have hws : wordSpan A L₀ = ⊤ := (wordSpan_eq_top_iff_isNBlkInjective A L₀).mpr hInj
  -- Strong induction on k.
  suffices ∀ k, 0 < k → (∀ w : List (Fin d), w.length = k → evalWord A w = 0) → False from
    this k hk hzero
  intro k
  induction k using Nat.strongRecOn with
  | ind k ih =>
    intro hk_pos hk_zero
    by_cases hkL : k ≤ L₀
    · -- Case k ≤ L₀: factor every length-L₀ word as (take k) ++ (drop k).
      have hws_bot : wordSpan A L₀ = ⊥ := by
        rw [eq_bot_iff, wordSpan]
        apply Submodule.span_le.mpr
        rintro _ ⟨σ, rfl⟩
        rw [SetLike.mem_coe, Submodule.mem_bot]
        have hsplit := List.take_append_drop k (List.ofFn σ)
        have htake_len : (List.take k (List.ofFn σ)).length = k := by
          rw [List.length_take]; simp; omega
        calc evalWord A (List.ofFn σ)
            = evalWord A (List.take k (List.ofFn σ) ++
                List.drop k (List.ofFn σ)) := by rw [hsplit]
          _ = evalWord A (List.take k (List.ofFn σ)) *
                evalWord A (List.drop k (List.ofFn σ)) := evalWord_append ..
          _ = 0 * evalWord A (List.drop k (List.ofFn σ)) := by
                rw [hk_zero _ htake_len]
          _ = 0 := zero_mul _
      exact absurd (hws ▸ hws_bot) top_ne_bot
    · -- Case k > L₀: use span = M_D and M = 1 to descend to k - L₀.
      push Not at hkL
      have hkL₀_pos : 0 < k - L₀ := by omega
      apply ih (k - L₀) (by omega) hkL₀_pos
      intro w₂ hw₂
      -- For each σ₁ of length L₀: evalWord A (ofFn σ₁) * evalWord A w₂ = 0.
      have hmul_zero : ∀ σ₁ : Fin L₀ → Fin d,
          evalWord A (List.ofFn σ₁) * evalWord A w₂ = 0 := by
        intro σ₁
        have hlen : (List.ofFn σ₁ ++ w₂).length = k := by simp [hw₂]; omega
        have := hk_zero _ hlen
        rwa [evalWord_append] at this
      -- The map M ↦ M * evalWord A w₂ vanishes on wordSpan A L₀ = ⊤.
      have hright : LinearMap.mulRight ℂ (evalWord A w₂) = 0 := by
        apply LinearMap.ext_on_range
          (v := fun σ : Fin L₀ → Fin d => evalWord A (List.ofFn σ))
          (hv := by rwa [← wordSpan])
        intro σ₁
        simp [LinearMap.mulRight_apply, hmul_zero σ₁]
      -- Taking M = 1: evalWord A w₂ = 0.
      have h1 : (1 : Matrix (Fin D) (Fin D) ℂ) * evalWord A w₂ = 0 :=
        show LinearMap.mulRight ℂ (evalWord A w₂) 1 = 0 by rw [hright]; simp
      simpa using h1

/-- For a block-injective tensor, the MPV is nonzero on chains of sufficient length.

Assuming `mpv = 0` (all trace products of length `N` vanish), factor through
`wordSpan A L₀ = M_D` to force all length-(`N − L₀`) products to zero, then
`allZero_contradiction` gives the contradiction. -/
theorem mpv_ne_zero_of_isNBlkInjective {A : MPSTensor d D} [NeZero D]
    {L₀ : ℕ} (hInj : IsNBlkInjective A L₀) (hL₀ : 0 < L₀)
    {N : ℕ} (hN : L₀ + 1 ≤ N) :
    (mpv A : NSiteSpace d N) ≠ 0 := by
  have hws : wordSpan A L₀ = ⊤ := (wordSpan_eq_top_iff_isNBlkInjective A L₀).mpr hInj
  intro hzero
  -- mpv = 0 means tr(evalWord A (List.ofFn σ)) = 0 for all σ : Fin N → Fin d.
  have htr_zero : ∀ σ : Fin N → Fin d,
      Matrix.trace (evalWord A (List.ofFn σ)) = 0 := by
    intro σ; simpa [mpv, coeff] using congrFun hzero σ
  -- All products of length (N - L₀) are zero by trace nondegeneracy.
  have hprod_zero : ∀ w₂ : List (Fin d), w₂.length = N - L₀ →
      evalWord A w₂ = 0 := by
    intro w₂ hw₂
    -- Show ∀ M, tr(evalWord A w₂ * M) = 0 to get evalWord A w₂ = 0.
    apply trace_mul_right_eq_zero
    intro M
    -- The functional P ↦ tr(P * evalWord A w₂) vanishes on wordSpan A L₀ = ⊤.
    have hφ : (Matrix.traceLinearMap (Fin D) ℂ ℂ).comp
        (LinearMap.mulRight ℂ (evalWord A w₂)) = 0 := by
      apply LinearMap.ext_on_range
        (v := fun σ : Fin L₀ → Fin d => evalWord A (List.ofFn σ))
        (hv := by rwa [← wordSpan])
      intro σ₁
      simp only [LinearMap.comp_apply, LinearMap.mulRight_apply,
        Matrix.traceLinearMap_apply]
      -- tr(evalWord A (List.ofFn σ₁) * evalWord A w₂) = tr(evalWord A (σ₁ ++ w₂))
      rw [← evalWord_append]
      -- This is a trace of a length-N word product, hence 0.
      have hlen : (List.ofFn σ₁ ++ w₂).length = N := by simp [hw₂]; omega
      let σ' : Fin N → Fin d :=
        fun i => (List.ofFn σ₁ ++ w₂).get ⟨i.val, hlen.symm ▸ i.isLt⟩
      have hw_eq : List.ofFn σ' = List.ofFn σ₁ ++ w₂ := by
        apply List.ext_get
        · simp [hw₂]; omega
        · intro i h1 h2; simp [σ']
      rw [← hw_eq]
      exact htr_zero σ'
    -- From hφ: ∀ P, tr(P * evalWord A w₂) = 0. By trace commutativity:
    calc Matrix.trace (evalWord A w₂ * M)
        = Matrix.trace (M * evalWord A w₂) := Matrix.trace_mul_comm ..
      _ = 0 := by
          simpa [Matrix.traceLinearMap_apply] using congrArg (· M) hφ
  exact allZero_contradiction hInj hL₀ (by omega : 0 < N - L₀) hprod_zero

/-! ### Uniqueness theorems -/

/-- On a periodic chain, the block-injective parent-Hamiltonian ground space
coincides with the span of the MPV when the window size satisfies `L ≥ 2L₀`.

For `L₀`-block-injective tensors, the blocked tensor `A^[L₀]` is injective,
and the standard open-chain intersection argument requires a window of at
least `2` blocks, giving `L ≥ 2L₀`. -/
-- TODO(parent-hamiltonian): derive from cyclic-window `chainGroundSpace` definition
-- and the proved open-chain intersection property.
theorem chainGroundSpace_eq_mpvSubmodule {A : MPSTensor d D} [NeZero D]
    {L₀ : ℕ} (hA : IsNBlkInjective A L₀)
    {L N : ℕ} (hN : 2 ≤ N) (hL : 2 * L₀ ≤ L) (hLN : L ≤ N) :
    chainGroundSpace A L N = mpvSubmodule A N := by
  sorry

/-- On a periodic chain, the normal parent-Hamiltonian ground space coincides
with the span of the MPV with the reduced window `L > L₀` (instead of `2L₀`).

The normality hypothesis enables the range reduction from `2L₀` to `L₀ + 1`
via the structure theory of normal MPS (peripheral spectrum, canonical form).
See [CPGSV21] arXiv:2011.12127 §IV.C. -/
-- TODO(parent-hamiltonian): derive using the normal-form range reduction and
-- the cyclic-window definition of `chainGroundSpace`.
theorem chainGroundSpace_eq_mpvSubmodule_normal {A : MPSTensor d D} [NeZero D]
    (_hA : IsNormal A) {L₀ : ℕ} (hInj : IsNBlkInjective A L₀)
    {L N : ℕ} (hN : 2 ≤ N) (hL : L₀ < L) (hLN : L ≤ N) :
    chainGroundSpace A L N = mpvSubmodule A N := by
  sorry

/-- **Unique ground state on the periodic chain** for injective MPS.

For an injective tensor `A` on a periodic chain of `N ≥ 2` sites, the chain ground
space is one-dimensional, spanned by the MPV.

The proof uses the intersection property iteratively:
1. From the intersection property, any state in the chain ground space has the form
   `ψ(σ) = tr(A^σ · X)` for some `X ∈ M_D(ℂ)`.
2. The wrapping window condition (window crossing the periodic boundary) constrains
   `X` to commute with all `A^i`.
3. For injective `A`, the center of `span{A^i} = M_D(ℂ)` consists only of scalars,
   so `X = c · I` and `ψ = c · mpv A`. -/
theorem groundSpace_unique_periodic {A : MPSTensor d D} [NeZero D] (hA : IsInjective A)
    {L N : ℕ} (hN : 2 ≤ N) (hL : 1 < L) (hLN : L ≤ N) :
    HasUniqueGroundState (chainGroundSpace A L N) := by
  -- IsInjective A gives IsNBlkInjective A 1 (1-block injectivity).
  have hInj1 : IsNBlkInjective A 1 := by
    rw [← wordSpan_eq_top_iff_isNBlkInjective, wordSpan]
    have hrange : Set.range (fun σ : Fin 1 → Fin d => evalWord A (List.ofFn σ))
        = Set.range A := by
      ext M; constructor
      · rintro ⟨σ, rfl⟩; exact ⟨σ 0, by simp [evalWord]⟩
      · rintro ⟨i, rfl⟩; exact ⟨fun _ => i, by simp [evalWord]⟩
    rw [hrange]; exact hA
  rw [HasUniqueGroundState, chainGroundSpace_eq_mpvSubmodule hInj1 hN (by omega) hLN]
  have hmpv : (mpv A : NSiteSpace d N) ≠ 0 := by
    intro hzero
    have hEq :
        groundSpaceMap A N (1 : Matrix (Fin D) (Fin D) ℂ) =
          groundSpaceMap A N (0 : Matrix (Fin D) (Fin D) ℂ) := by
      simpa [mpv_eq_groundSpaceMap_one A N] using hzero
    have h10 : (1 : Matrix (Fin D) (Fin D) ℂ) = 0 :=
      (groundSpaceMap_injective hA (by omega : 0 < N)) hEq
    exact one_ne_zero h10
  simpa [mpvSubmodule] using finrank_span_singleton (K := ℂ) hmpv

/-- **Unique ground state for `L₀`-block-injective tensors on `2L₀` sites**.

If `A` is `L₀`-block-injective with `L₀ > 0`, the parent Hamiltonian with
interaction range `2L₀` on a periodic chain of `N ≥ 2L₀` sites has a unique
ground state.

**Proof sketch**: Rewrite via `chainGroundSpace_eq_mpvSubmodule` (sorry'd),
then use `mpv_ne_zero_of_isNBlkInjective` to show the MPV submodule is 1D. -/
-- TODO(parent-hamiltonian): remove sorry once `chainGroundSpace_eq_mpvSubmodule`
-- is proved. The reduction is:
--   rw [HasUniqueGroundState,
--     chainGroundSpace_eq_mpvSubmodule hA (by omega) (le_refl _) hN]
--   have hmpv := mpv_ne_zero_of_isNBlkInjective hA hL₀ (by omega)
--   simpa [mpvSubmodule] using finrank_span_singleton (K := ℂ) hmpv
theorem parentHamiltonian_unique_gs_injective {A : MPSTensor d D} [NeZero D]
    {L₀ : ℕ} (hA : IsNBlkInjective A L₀) (hL₀ : 0 < L₀)
    {N : ℕ} (hN : 2 * L₀ ≤ N) :
    HasUniqueGroundState (chainGroundSpace A (2 * L₀) N) := by
  sorry

/-- **Optimal unique ground state for normal tensors on `L₀ + 1` sites**.

If `A` is normal and `L₀`-block-injective with `L₀ > 0`, the interaction range
can be reduced from `2L₀` to `L₀ + 1`. The chain ground space with window
`L₀ + 1` on `N ≥ L₀ + 1` sites has a unique ground state.

**Proof sketch**: Rewrite via `chainGroundSpace_eq_mpvSubmodule_normal` (sorry'd),
then use `mpv_ne_zero_of_isNBlkInjective` to show the MPV submodule is 1D. -/
-- TODO(parent-hamiltonian): remove sorry once `chainGroundSpace_eq_mpvSubmodule_normal`
-- is proved. The reduction is:
--   rw [HasUniqueGroundState,
--     chainGroundSpace_eq_mpvSubmodule_normal hA hInj (by omega) (by omega) hN]
--   have hmpv := mpv_ne_zero_of_isNBlkInjective hInj hL₀ hN
--   simpa [mpvSubmodule] using finrank_span_singleton (K := ℂ) hmpv
theorem parentHamiltonian_unique_gs_normal {A : MPSTensor d D} [NeZero D]
    {L₀ : ℕ} (hA : IsNormal A) (hInj : IsNBlkInjective A L₀) (hL₀ : 0 < L₀)
    {N : ℕ} (hN : L₀ + 1 ≤ N) :
    HasUniqueGroundState (chainGroundSpace A (L₀ + 1) N) := by
  sorry

end MPSTensor
