/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.
-- Import architecture: docs/import_structure.md.
-- Generated aggregator module: TNLean.Circuit.Teleportation

import TNLean.Circuit.Teleportation.Chains
import TNLean.Circuit.Teleportation.Hop
import TNLean.Circuit.Teleportation.LongRangeGates
import TNLean.Circuit.Teleportation.RegisterGates
import TNLean.Circuit.Teleportation.Round
