title: Fundamental Theorem of Matrix Product States
description: A formal verification in Lean 4 using Mathlib
baseurl: "/TNLean"
url: "https://lionsr.github.io"
github_username: LionSR
repository: LionSR/TNLean

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
