/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.AnomalousCondensationZ2Z2Unitary
import TNLean.MPS.MPU.GroupCocycleMPO.Instances

/-!
# Anomalous `ℤ₂ × ℤ₂` symmetry: the two-qubit tensors against the cocycle construction

**Source.** Garre-Rubio, Lootens, Molnár 2023 (arXiv:2203.12563), subsubsection "Periodic
boundary condition case", `Papers/2203.12563/REsubmission.tex` lines 2200–2224: for a finite
group `G` and a three-cocycle `ω`, the operators `U_g` generated by the bond-`|G|` tensor
`T̂_g` form a periodic matrix product operator representation of `G`. The same file, subsubsection
"MPO algebras representing `ℤ₂ × ℤ₂`", lines 1845–1888: the type-II three-cocycle
`ω_II(a b^i, a^j b, a^k b) = −1`, all other values `+1` (line 1848), which in the coordinates
`a = (1,0)`, `b = (0,1)` is `(−1)^{a₁ b₂ c₂}`, of class `(0,0,1)` in the table of lines
1856–1872, and a periodic single-qubit realization of that class,
`U_a = ∏_i CZ_{i,i+1} Z_i`, `U_b = ∏_i X_i` (line 1884). Garre-Rubio, Schuch 2024
(arXiv:2405.00439), Section IV.A, `Papers/2405.00439/MPU-DW.tex` line 1684: matrix product
unitary representations `U_g U_h = U_{gh}`, `U_e = 1`. Neither source prints the two-qubit
tensors used here.

**Formalized here.** The periodic operators of the two-qubit tensors `symTensor g` of
`AnomalousCondensationZ2Z2` are those of the construction of arXiv:2203.12563 for the mixed
type-II cocycle `ω(a,b,c) = (−1)^{a₁ b₂ c₂}`, followed by an on-site dressing: for every group
element `g = (g₁, g₂)` and every positive chain length `N`,
`U_g^{sym} = U_g^{ω} · (∏_i Z_i^{(2)})^{g₁}`, where `Z_i^{(2)}` is the Pauli `Z` on the second
qubit of site `i`, applied first. The dressing is trivial for `g ∈ {e, y}` and is a product
of single-site unitaries. Moving it to the left of `U_g^{ω}` costs the sign `(−1)^{g₁ g₂ N}`,
since the shift adds `g₂` to every second qubit. The dressed family
multiplies only up to the signs `λ(g,h)^N` of `mpo_symTensor_mul`, so on odd rings `symTensor`
is a projective, not an exact, representation; that fusion rule is kept as it is.

## Main definitions

* `Z2Z2Condensation.secondZDressing`: the diagonal operator `(∏_i Z_i^{(2)})^{g₁}`.

## Main results

* `Z2Z2Condensation.gmul_kleinEquiv`: the multiplication table `gmul` is the group law of
  `ℤ₂ × ℤ₂` in the basis `2 a₁ + a₂`.
* `Z2Z2Condensation.mpo_symTensor_eq_groupCocycle`: `U_g^{sym} = U_g^{ω} · (∏_i Z_i^{(2)})^{g₁}`.

## References
- [arXiv:2203.12563](https://arxiv.org/abs/2203.12563) -- Garre-Rubio, Lootens, Molnár,
  *Classifying phases protected by matrix product operator symmetries using matrix product
  states*
- [arXiv:2405.00439](https://arxiv.org/abs/2405.00439) -- Garre-Rubio, Schuch,
  *Fractional domain wall statistics in spin chains with anomalous symmetries*

## Provenance
The tensors `symTensor g` are representatives constructed in this development of the mixed
type-II class, recorded with their exact checks in
`Notes/OpenProblemsTN/checks/asym_z2z2_typeIII_data.md`, Sections 1–3; these are verification
records, not the source.
-/

noncomputable section

open scoped BigOperators Matrix

namespace Z2Z2Condensation

open MPOTensor MPOTensor.GroupCocycle TNLean.Algebra.ScalarThreeCochain

/-- The site label `kleinEquiv h` of a group element `h = (h₁, h₂)` is `2 h₁ + h₂`, and the
table `gmul` is the group law in these labels. -/
theorem gmul_kleinEquiv (g : Multiplicative (ZMod 2 × ZMod 2)) (a : Fin 4) :
    gmul (kleinEquiv g) a = kleinEquiv (g * kleinEquiv.symm a) := by
  revert g a
  decide

/-- The diagonal dressing `(∏_i Z_i^{(2)})^{g₁}` on a periodic chain of two-qubit sites: the
sign `(−1)^{g₁ ∑_i t_{i,2}}` on the configuration `t`, where `t_{i,2} = (t i).val % 2` is the
second qubit of site `i`. -/
def secondZDressing (g : Multiplicative (ZMod 2 × ZMod 2)) (N : ℕ) :
    Matrix (Fin N → Fin 4) (Fin N → Fin 4) ℂ :=
  Matrix.diagonal fun t ↦ (-1 : ℂ) ^ ((Multiplicative.toAdd g).1.val * ∑ i, (t i).val % 2)

private theorem neg_one_pow_congr {m n : ℕ} (h : m % 2 = n % 2) : (-1 : ℂ) ^ m = (-1) ^ n := by
  rw [neg_one_pow_eq_pow_mod_two, h, ← neg_one_pow_eq_pow_mod_two]

/-- The sitewise sign identity: the controlled-`Z` sign of the two-qubit tensor on the pair
`(a, b)` is the cocycle gate sign `(−1)^{g₁ b₂ (a₂ − b₂)}` times the `Z` sign `(−1)^{g₁ b₂}`. -/
private theorem site_sign (g : Multiplicative (ZMod 2 × ZMod 2)) (a b : Fin 4) :
    (-1 : ℂ) ^ ((kleinEquiv g).val / 2 * (a.val % 2 * (b.val % 2))) =
      (-1) ^ ((Multiplicative.toAdd g).1 * (Multiplicative.toAdd (kleinEquiv.symm b)).2 *
          ((Multiplicative.toAdd (kleinEquiv.symm a)).2 -
            (Multiplicative.toAdd (kleinEquiv.symm b)).2)).val *
        (-1) ^ ((Multiplicative.toAdd g).1.val * (b.val % 2)) := by
  rw [← pow_add]
  apply neg_one_pow_congr
  revert g a b
  decide

variable {N : ℕ} [NeZero N]

/-- **The two-qubit tensors are the cocycle construction for `(−1)^{a₁ b₂ c₂}`, dressed by
`(∏_i Z_i^{(2)})^{g₁}`**: on every nonempty periodic chain,
`U_g^{sym} = U_g^{ω} · (∏_i Z_i^{(2)})^{g₁}`, with the dressing applied first.

Bridge: arXiv:2203.12563, lines 2204–2222 (the operators `U_g` of the construction), for the
type-II cocycle `ω(a,b,c) = (−1)^{a₁ b₂ c₂}` of `ℤ₂ × ℤ₂` (line 1848). -/
theorem mpo_symTensor_eq_groupCocycle (g : Multiplicative (ZMod 2 × ZMod 2)) :
    mpo (symTensor (kleinEquiv g)) N =
      mpo (tensor kleinEquiv kleinCocycle g) N * secondZDressing g N := by
  ext s t
  rw [secondZDressing, Matrix.mul_diagonal, mpo_symTensor_apply, mpo_tensor_klein_apply]
  have hshift : physicalShift (kleinEquiv g) N t = shift kleinEquiv g N t := by
    funext i
    exact gmul_kleinEquiv g (t i)
  rw [hshift]
  split_ifs
  · have hsum : ∑ i : Fin N, (t i).val % 2 = ∑ i : Fin N, (t (i + 1)).val % 2 :=
      (Fintype.sum_equiv (Equiv.addRight 1) _ _ fun i ↦ rfl).symm
    rw [secondCZExponent, hsum]
    simp only [Finset.mul_sum, ← Finset.prod_pow_eq_pow_sum, ← Finset.prod_mul_distrib]
    exact Finset.prod_congr rfl fun i _ ↦ site_sign g (t i) (t (i + 1))
  · simp

end Z2Z2Condensation
