/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.AnomalousCondensationZ2Z2NonSplit
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.AnomalousCondensationZ2Z2Split
import TNLean.MPS.Core.ScaledNormality
import TNLean.MPS.MPDO.DirectSum
import TNLean.MPS.MPDO.OperatorProduct

/-!
# The condensation defect of the anomalous `ℤ/2 × ℤ/2` symmetry

The condensation defect of the anomalous `ℤ/2 × ℤ/2` symmetry is the periodic operator family
`A_L = U_e + U_x + U_y + U_xy`, generated by the direct-sum tensor
`N = M_e ⊕ M_x ⊕ M_y ⊕ M_xy` of bond dimension six
(`Notes/OpenProblemsTN/checks/asym_z2z2_typeIII_data.md`, Sections 2 and 4). This file derives
the operator-level physics from the sixteen pair-block compression data of the companion
files:

* the periodic fusion rules `U_g U_h = λ(g,h)^L U_{gh}` with the sign `λ(g,h) = (-1)^{g_1 h_2}`,
  so that on odd rings `U_x` and `U_y` anticommute and the four operators form a projective
  representation of `ℤ/2 × ℤ/2` (the data file, Section 2, records `λ` as a `ℤ/2`-valued
  two-cocycle of the Pauli class; no cocycle class is computed here);
* the length-dependent operator identity `A_L² = (3 + (-1)^L) A_L`, so that `A_L / 4` is a
  projector exactly on even rings: on odd rings the anomalous symmetry cannot be condensed by
  its defect;
* the word-trace identity of the stacked tensor `N ⊗ N` of bond dimension thirty-six, and the
  resulting multi-block compression datum of Theorem 7.7 with sixteen slots, one per pair
  `(g, h)`, carrying `λ(g,h) M_{gh}`, and `z = 36 - 24 = 12` zero slots.

The existence of the assembled datum is obtained from the general theorem
`MPSTensor.exists_multiBlockCompression_of_isNormal`; its fine structure, the explicit
integer gauges, the vanishing remainders of the twelve split blocks and the non-split
extensions of the four blocks with two factors from `{x, xy}`, is the content of the per-pair
data of the companion files.

The word-trace identities that turn each pair-block compression datum into a periodic fusion
rule (`MPOTensor.mpo_eq_of_trace_evalWord_toMPSTensor`,
`MPOTensor.mpo_eq_pow_smul_of_trace_evalWord_toMPSTensor`, and
`MPSTensor.trace_evalWord_smul`) are general MPO/MPS infrastructure with no reference to this
example, and live in `TNLean.MPS.MPDO.OperatorProduct`.

## Main results

* `Z2Z2Condensation.mpo_x_mul_y`, ...: the sixteen periodic fusion rules.
* `Z2Z2Condensation.mpo_condensationTensor_sq`: `A_L² = (3 + (-1)^L) A_L`.
* `Z2Z2Condensation.condensation_quarter_sq_eq_self_iff_even`: `A_L / 4` is a projector if and
  only if `L` is even.
* `Z2Z2Condensation.condensationSquare_trace_evalWord`,
  `Z2Z2Condensation.exists_condensationSquare_compression`,
  `Z2Z2Condensation.condensationSquare_compression_z`: the assembled compression datum of the
  stacked defect tensor, with sixteen weighted slots and twelve zero slots.
-/

noncomputable section

open scoped Matrix

namespace Z2Z2Condensation

open MPSTensor MPOTensor

/-! ### The periodic fusion rules -/

/-- **`U_e U_e = U_e`.** -/
theorem mpo_e_mul_e (L : ℕ) (hL : 0 < L) : mpo eTensor L * mpo eTensor L = mpo eTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor eE_trace_evalWord hL

/-- **`U_e U_y = U_y`.** -/
theorem mpo_e_mul_y (L : ℕ) (hL : 0 < L) : mpo eTensor L * mpo yTensor L = mpo yTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor eY_trace_evalWord hL

/-- **`U_e U_x = U_x`.** -/
theorem mpo_e_mul_x (L : ℕ) (hL : 0 < L) : mpo eTensor L * mpo xTensor L = mpo xTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor eX_trace_evalWord hL

/-- **`U_e U_xy = U_xy`.** -/
theorem mpo_e_mul_xy (L : ℕ) (hL : 0 < L) :
    mpo eTensor L * mpo xyTensor L = mpo xyTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor eXy_trace_evalWord hL

/-- **`U_y U_e = U_y`.** -/
theorem mpo_y_mul_e (L : ℕ) (hL : 0 < L) : mpo yTensor L * mpo eTensor L = mpo yTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor yE_trace_evalWord hL

/-- **`U_y U_y = U_e`.** -/
theorem mpo_y_mul_y (L : ℕ) (hL : 0 < L) : mpo yTensor L * mpo yTensor L = mpo eTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor yY_trace_evalWord hL

/-- **`U_y U_x = U_xy`.** -/
theorem mpo_y_mul_x (L : ℕ) (hL : 0 < L) :
    mpo yTensor L * mpo xTensor L = mpo xyTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor yX_trace_evalWord hL

/-- **`U_y U_xy = U_x`.** -/
theorem mpo_y_mul_xy (L : ℕ) (hL : 0 < L) :
    mpo yTensor L * mpo xyTensor L = mpo xTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor yXy_trace_evalWord hL

/-- **`U_x U_e = U_x`.** -/
theorem mpo_x_mul_e (L : ℕ) (hL : 0 < L) : mpo xTensor L * mpo eTensor L = mpo xTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor xE_trace_evalWord hL

/-- **`U_x U_y = (-1)^L U_xy`** (data file, Section 2). -/
theorem mpo_x_mul_y (L : ℕ) (hL : 0 < L) :
    mpo xTensor L * mpo yTensor L = (-1 : ℂ) ^ L • mpo xyTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_pow_smul_of_trace_evalWord_toMPSTensor (-1) xY_trace_evalWord hL

/-- **`U_x U_x = U_e`.** -/
theorem mpo_x_mul_x (L : ℕ) (hL : 0 < L) : mpo xTensor L * mpo xTensor L = mpo eTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor xX_trace_evalWord hL

/-- **`U_x U_xy = (-1)^L U_y`** (data file, Section 2). -/
theorem mpo_x_mul_xy (L : ℕ) (hL : 0 < L) :
    mpo xTensor L * mpo xyTensor L = (-1 : ℂ) ^ L • mpo yTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_pow_smul_of_trace_evalWord_toMPSTensor (-1) xXy_trace_evalWord hL

/-- **`U_xy U_e = U_xy`.** -/
theorem mpo_xy_mul_e (L : ℕ) (hL : 0 < L) :
    mpo xyTensor L * mpo eTensor L = mpo xyTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor xyE_trace_evalWord hL

/-- **`U_xy U_y = (-1)^L U_x`** (data file, Section 2). -/
theorem mpo_xy_mul_y (L : ℕ) (hL : 0 < L) :
    mpo xyTensor L * mpo yTensor L = (-1 : ℂ) ^ L • mpo xTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_pow_smul_of_trace_evalWord_toMPSTensor (-1) xyY_trace_evalWord hL

/-- **`U_xy U_x = U_y`.** -/
theorem mpo_xy_mul_x (L : ℕ) (hL : 0 < L) :
    mpo xyTensor L * mpo xTensor L = mpo yTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_of_trace_evalWord_toMPSTensor xyX_trace_evalWord hL

/-- **`U_xy U_xy = (-1)^L U_e`** (data file, Section 2): the restriction of the symmetry to the
diagonal element `xy` is the CZX symmetry of Example D of the P5 note. -/
theorem mpo_xy_mul_xy (L : ℕ) (hL : 0 < L) :
    mpo xyTensor L * mpo xyTensor L = (-1 : ℂ) ^ L • mpo eTensor L := by
  rw [← mpo_mulTensor]
  exact mpo_eq_pow_smul_of_trace_evalWord_toMPSTensor (-1) xyXy_trace_evalWord hL

/-- **On odd rings the operators `U_x` and `U_y` anticommute**: `U_x U_y = -U_y U_x`, so the
four operators form a projective representation of `ℤ/2 × ℤ/2` (data file, Section 2). -/
theorem mpo_x_mul_y_eq_neg_of_odd {L : ℕ} (hL : Odd L) :
    mpo xTensor L * mpo yTensor L = -(mpo yTensor L * mpo xTensor L) := by
  rw [mpo_x_mul_y L hL.pos, mpo_y_mul_x L hL.pos, hL.neg_one_pow, neg_one_smul]

/-! ### The condensation defect -/

/-- The tensor of the condensation defect `A = U_e + U_x + U_y + U_xy`: the direct sum
`M_e ⊕ M_x ⊕ M_y ⊕ M_xy` of bond dimension six (data file, Section 4). -/
def condensationTensor : MPOTensor 4 6 :=
  directSum (directSum (directSum eTensor xTensor) yTensor) xyTensor

/-- The condensation defect is the sum of the four symmetry operators. -/
theorem mpo_condensationTensor (L : ℕ) :
    mpo condensationTensor L =
      mpo eTensor L + mpo xTensor L + mpo yTensor L + mpo xyTensor L := by
  simp only [condensationTensor, mpo_directSum]

/-- **The condensation defect squares to `(3 + (-1)^L)` times itself** (data file, Section 2):
each `U_k` receives the four weights `{+1, +1, +1, -1}` from the four pairs `(g, h)` with
`gh = k`. -/
theorem mpo_condensationTensor_sq (L : ℕ) (hL : 0 < L) :
    mpo condensationTensor L ^ 2 = (3 + (-1 : ℂ) ^ L) • mpo condensationTensor L := by
  rw [sq, mpo_condensationTensor]
  simp only [add_mul, mul_add, mpo_e_mul_e L hL, mpo_e_mul_x L hL, mpo_e_mul_y L hL,
    mpo_e_mul_xy L hL, mpo_x_mul_e L hL, mpo_x_mul_x L hL, mpo_x_mul_y L hL, mpo_x_mul_xy L hL,
    mpo_y_mul_e L hL, mpo_y_mul_x L hL, mpo_y_mul_y L hL, mpo_y_mul_xy L hL, mpo_xy_mul_e L hL,
    mpo_xy_mul_x L hL, mpo_xy_mul_y L hL, mpo_xy_mul_xy L hL]
  module

/-- The all-zero diagonal entry of the condensation defect is `1`: only the identity
contributes to it. -/
theorem mpo_condensationTensor_apply_zero (L : ℕ) (hL : 0 < L) :
    mpo condensationTensor L (fun _ => 0) (fun _ => 0) = 1 := by
  have he : eTensor 0 0 = 1 := by
    have h0 : eIntTensor 0 0 = 1 := by decide
    rw [eTensor, h0, complexOfInt_one]
  have hx : xTensor 0 0 = 0 := by
    have h0 : xIntTensor 0 0 = 0 := by decide
    rw [xTensor, h0, complexOfInt_zero]
  have hy : yTensor 0 0 = 0 := by
    have h0 : yIntTensor 0 0 = 0 := by decide
    rw [yTensor, h0, complexOfInt_zero]
  have hxy : xyTensor 0 0 = 0 := by
    have h0 : xyIntTensor 0 0 = 0 := by decide
    rw [xyTensor, h0, complexOfInt_zero]
  rw [mpo_condensationTensor]
  simp only [Matrix.add_apply, mpo_apply, mpoMatrixEntry]
  rw [evalWord_ofFn, evalWord_ofFn, evalWord_ofFn, evalWord_ofFn]
  simp only [he, hx, hy, hxy, List.ofFn_const, List.prod_replicate, one_pow, zero_pow hL.ne',
    Matrix.trace_one, Matrix.trace_zero, Fintype.card_fin, Nat.cast_one, add_zero]

/-- The condensation defect is nonzero on every ring. -/
theorem mpo_condensationTensor_ne_zero (L : ℕ) (hL : 0 < L) : mpo condensationTensor L ≠ 0 := by
  intro h
  have := mpo_condensationTensor_apply_zero L hL
  rw [h, Matrix.zero_apply] at this
  exact zero_ne_one this

/-- **The condensation defect closes exactly on even rings**: `A_L / 4` is a projector if and
only if `L` is even (data file, Section 2). On odd rings the anomalous symmetry cannot be
condensed by its defect. -/
theorem condensation_quarter_sq_eq_self_iff_even (L : ℕ) (hL : 0 < L) :
    ((4 : ℂ)⁻¹ • mpo condensationTensor L) ^ 2 = (4 : ℂ)⁻¹ • mpo condensationTensor L ↔
      Even L := by
  rw [smul_pow, mpo_condensationTensor_sq L hL, smul_smul]
  constructor
  · intro h
    by_contra hodd
    rw [Nat.not_even_iff_odd] at hodd
    rw [hodd.neg_one_pow] at h
    have hzero : ((4 : ℂ)⁻¹ ^ 2 * (3 + -1) - (4 : ℂ)⁻¹) • mpo condensationTensor L = 0 := by
      rw [sub_smul, h, sub_self]
    have hc : (4 : ℂ)⁻¹ ^ 2 * (3 + -1) - (4 : ℂ)⁻¹ ≠ 0 := by norm_num
    exact mpo_condensationTensor_ne_zero L hL ((smul_eq_zero.mp hzero).resolve_left hc)
  · intro heven
    rw [heven.neg_one_pow]
    congr 1
    norm_num

/-! ### The assembled compression datum of the stacked defect -/

/-- The bond dimension of the tensor of `U_g`, for the group elements `e, y, x, xy` indexed by
their site labels `0, 1, 2, 3`. -/
def bondDim : Fin 4 → ℕ
  | 0 => 1
  | 1 => 1
  | 2 => 2
  | 3 => 2

/-- The four symmetry tensors indexed by the group elements. -/
def symTensor : (g : Fin 4) → MPOTensor 4 (bondDim g)
  | 0 => eTensor
  | 1 => yTensor
  | 2 => xTensor
  | 3 => xyTensor

/-- The four symmetry tensors over the pair alphabet, indexed by the group elements. -/
def symMPS : (g : Fin 4) → MPSTensor 16 (bondDim g)
  | 0 => eMPS
  | 1 => yMPS
  | 2 => xMPS
  | 3 => xyMPS

theorem symMPS_eq_toMPSTensor (g : Fin 4) : symMPS g = (symTensor g).toMPSTensor := by
  fin_cases g <;> rfl

/-- The group law of `ℤ/2 × ℤ/2` on the site labels: the bitwise sum. -/
def gmul : Fin 4 → Fin 4 → Fin 4
  | 0, h => h
  | 1, 0 => 1
  | 1, 1 => 0
  | 1, 2 => 3
  | 1, 3 => 2
  | 2, 0 => 2
  | 2, 1 => 3
  | 2, 2 => 0
  | 2, 3 => 1
  | 3, 0 => 3
  | 3, 1 => 2
  | 3, 2 => 1
  | 3, 3 => 0

/-- The periodic fusion sign `λ(g,h) = (-1)^{g_1 h_2}` (data file, Section 2). -/
def fusionSign : Fin 4 → Fin 4 → ℂ
  | 2, 1 => -1
  | 2, 3 => -1
  | 3, 1 => -1
  | 3, 3 => -1
  | _, _ => 1

theorem fusionSign_ne_zero (g h : Fin 4) : fusionSign g h ≠ 0 := by
  fin_cases g <;> fin_cases h <;> simp [fusionSign]

/-- Every symmetry tensor is normal. -/
theorem symMPS_isNormal (g : Fin 4) : Kraus.IsNormal (symMPS g) := by
  fin_cases g
  exacts [eMPS_isNormal, yMPS_isNormal, xMPS_isNormal, xyMPS_isNormal]

/-- **The periodic fusion table**: `U_g U_h = λ(g,h)^L U_{gh}` for all sixteen pairs (data
file, Section 2). -/
theorem mpo_symTensor_mul (g h : Fin 4) (L : ℕ) (hL : 0 < L) :
    mpo (symTensor g) L * mpo (symTensor h) L =
      fusionSign g h ^ L • mpo (symTensor (gmul g h)) L := by
  fin_cases g <;> fin_cases h <;> simp only [symTensor, gmul, fusionSign, one_pow, one_smul]
  exacts [mpo_e_mul_e L hL, mpo_e_mul_y L hL, mpo_e_mul_x L hL, mpo_e_mul_xy L hL,
    mpo_y_mul_e L hL, mpo_y_mul_y L hL, mpo_y_mul_x L hL, mpo_y_mul_xy L hL,
    mpo_x_mul_e L hL, mpo_x_mul_y L hL, mpo_x_mul_x L hL, mpo_x_mul_xy L hL,
    mpo_xy_mul_e L hL, mpo_xy_mul_y L hL, mpo_xy_mul_x L hL, mpo_xy_mul_xy L hL]

theorem mpo_condensationTensor_eq_sum (L : ℕ) :
    mpo condensationTensor L = ∑ g, mpo (symTensor g) L := by
  rw [mpo_condensationTensor, Fin.sum_univ_four]
  change mpo eTensor L + mpo xTensor L + mpo yTensor L + mpo xyTensor L =
    mpo eTensor L + mpo yTensor L + mpo xTensor L + mpo xyTensor L
  abel

/-- The stacked tensor `N ⊗ N` of the condensation defect, of bond dimension thirty-six, over
the pair alphabet. -/
def condensationSquare : MPSTensor 16 36 :=
  (mulTensor condensationTensor condensationTensor).toMPSTensor

/-- The sixteen slots of the assembled datum: the pairs `(g, h)` of group elements. -/
abbrev pairSlots : Finset (Fin 4 × Fin 4) := Finset.univ

/-- The bond dimension of the target of the pair `(g, h)`: that of `U_{gh}`. -/
def pairDim (p : Fin 4 × Fin 4) : ℕ := bondDim (gmul p.1 p.2)

/-- The target of the pair `(g, h)`: the tensor of `U_{gh}` carried with the weight `λ(g,h)`
(data file, Section 4). -/
def pairTarget (p : Fin 4 × Fin 4) : MPSTensor 16 (pairDim p) :=
  fusionSign p.1 p.2 • symMPS (gmul p.1 p.2)

/-- Every target of the assembled datum is normal. -/
theorem pairTarget_isNormal (p : Fin 4 × Fin 4) : Kraus.IsNormal (pairTarget p) :=
  (isNormal_smul_iff (fusionSign_ne_zero _ _) _).2 (symMPS_isNormal _)

/-- **The word-trace identity of the stacked defect tensor** (data file, Section 4): the trace
of every nonempty word of `N ⊗ N` is the sum over the sixteen pairs of `λ(g,h)^L` times the
trace of the word of `M_{gh}`. -/
theorem condensationSquare_trace_evalWord (w : List (Fin 16)) (hw : w ≠ []) :
    Matrix.trace (Kraus.evalWord condensationSquare w) =
      ∑ p ∈ pairSlots, Matrix.trace (Kraus.evalWord (pairTarget p) w) := by
  have hL : 0 < w.length := List.length_pos_of_ne_nil hw
  rw [condensationSquare, trace_evalWord_toMPSTensor, mpo_mulTensor,
    mpo_condensationTensor_eq_sum, Finset.sum_mul_sum]
  simp only [Matrix.sum_apply]
  rw [show pairSlots = Finset.univ from rfl, Fintype.sum_prod_type]
  refine Finset.sum_congr rfl fun g _ => Finset.sum_congr rfl fun h _ => ?_
  have h1 := trace_evalWord_toMPSTensor (symTensor (gmul g h)) w
  rw [← symMPS_eq_toMPSTensor] at h1
  have h2 := trace_evalWord_smul (fusionSign g h) (symMPS (gmul g h)) w
  rw [mpo_symTensor_mul g h w.length hL, Matrix.smul_apply, smul_eq_mul]
  exact (congrArg (fun t => fusionSign g h ^ w.length * t) h1.symm).trans h2.symm

/-- **The assembled multi-block compression datum of the stacked defect tensor** (P5 note,
Theorem 7.7; data file, Section 4): `N ⊗ N` compresses onto the sixteen weighted targets
`λ(g,h) M_{gh}`. -/
theorem exists_condensationSquare_compression :
    Nonempty (MultiBlockCompression condensationSquare pairSlots pairTarget) := by
  have hD : ∀ p : Fin 4 × Fin 4, 0 < pairDim p := by decide
  exact exists_multiBlockCompression_of_isNormal pairSlots pairTarget
    (fun p _ => pairTarget_isNormal p) (fun p _ => hD p) condensationSquare
    condensationSquare_trace_evalWord

/-- **The number of zero slots of the assembled datum is twelve**: `36 = 4 (1 + 2 + 1 + 2) + 12`
(data file, Section 4; P5 note, Theorem 7.7(vii)). -/
theorem condensationSquare_compression_z
    (P : MultiBlockCompression condensationSquare pairSlots pairTarget) : P.z = 12 := by
  have h := P.dim_eq
  have hsum : ∑ p ∈ pairSlots, pairDim p = 24 := by decide
  omega

end Z2Z2Condensation
