/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import Mathlib.Analysis.Real.Sqrt
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.ExplicitGauge
import TNLean.MPS.MPDO.OperatorProduct

/-!
# The ring of Eisenstein integers

The tensors of the `ℤ/3` matrix product operator symmetries have entries in the cyclotomic
field `ℚ(ω)`, where `ω = e^{2πi/3}` is a primitive cube root of unity and satisfies
`ω² + ω + 1 = 0`. The entries are in fact all integral: every one of them is a `ℤ`-linear
combination of `1` and `ω`, and so are the gauges and their inverses, which are unimodular.

This file builds the exact arithmetic of that ring in two layers, following
`GoldenRing.lean`.

The computational layer is `EisensteinInt`, the ring `ℤ[ω]` presented by the two integer
coordinates of an element in the basis `1, ω`, with the multiplication obtained by reducing
`ω² = -1 - ω`. Equality of Eisenstein integers is decidable, so every matrix identity between
explicit matrices over `ℤ[ω]` is decidable, exactly as an identity between integer matrices is.
Mathlib's `Zsqrtd (-3)` is the ring `ℤ[√-3]`, a subring of index two in `ℤ[ω]` that does not
contain `ω` itself, so a dedicated structure is used.

The algebraic layer identifies those coordinates with the actual complex number
`ω = (-1 + i√3)/2`. The ring homomorphism `eisensteinToComplex` is the embedding along which a
matrix over `ℤ[ω]` becomes a complex matrix, and identities proved by decision over `ℤ[ω]`
transport to the complex matrices. The embedding is injective, so a nonzero Eisenstein integer
stays nonzero in `ℂ`; this is what allows a matrix unit scaled by `ω - 1` to be divided back.

## Main definitions

* `EisensteinInt`: the ring `ℤ[ω]` in coordinates.
* `EisensteinInt.omega`: the generator `ω`.
* `eisensteinOmega`: the complex number `(-1 + i√3)/2`.
* `eisensteinToComplex`: the embedding of `ℤ[ω]` into the complex numbers.
* `MPSTensor.complexOfEisenstein`: the entrywise image of a matrix over `ℤ[ω]` in the complex
  matrices.
* `MPSTensor.mulEisensteinTensor`: the bond-space product of two tensors over `ℤ[ω]`.
* `MPSTensor.evalWordEisenstein`: word evaluation of a tensor over `ℤ[ω]`.

## Main results

* `EisensteinInt.omega_quadratic`, `eisensteinOmega_quadratic`: the relation `ω² + ω + 1 = 0`
  in the two models.
* `eisensteinMulRule`: the multiplication rule of `ℤ[ω]` in any commutative ring carrying a root
  of `X² + X + 1`.
* `eisensteinToComplex_injective`, `MPSTensor.complexOfEisenstein_injective`: the embedding is
  injective, on scalars and on matrices.
* `MPSTensor.complexOfEisenstein_mul`, `MPSTensor.complexOfEisenstein_one`: the embedding of
  matrices is multiplicative and unital.
* `MPSTensor.mulTensor_complexOfEisenstein`, `MPSTensor.evalWord_complexOfEisenstein`: the
  bond-space product and word evaluation commute with the embedding.
-/

open scoped Matrix Kronecker

/-- An Eisenstein integer: the element `c₀ + c₁ ω` of the ring `ℤ[ω]` generated by the
primitive cube root of unity `ω = e^{2πi/3}`. -/
structure EisensteinInt where
  /-- the coordinate of `1` -/
  c0 : ℤ
  /-- the coordinate of `ω` -/
  c1 : ℤ
  deriving DecidableEq

namespace EisensteinInt

@[ext] theorem ext' {x y : EisensteinInt} (h0 : x.c0 = y.c0) (h1 : x.c1 = y.c1) : x = y := by
  cases x; cases y; simp_all

instance : Zero EisensteinInt := ⟨⟨0, 0⟩⟩

instance : One EisensteinInt := ⟨⟨1, 0⟩⟩

instance : Add EisensteinInt := ⟨fun x y => ⟨x.c0 + y.c0, x.c1 + y.c1⟩⟩

instance : Neg EisensteinInt := ⟨fun x => ⟨-x.c0, -x.c1⟩⟩

instance : Sub EisensteinInt := ⟨fun x y => ⟨x.c0 - y.c0, x.c1 - y.c1⟩⟩

/-- Multiplication of Eisenstein integers: the product of two linear polynomials in `ω`,
reduced by `ω² = -1 - ω`. -/
instance : Mul EisensteinInt :=
  ⟨fun x y => ⟨x.c0 * y.c0 - x.c1 * y.c1, x.c0 * y.c1 + x.c1 * y.c0 - x.c1 * y.c1⟩⟩

theorem zero_def : (0 : EisensteinInt) = ⟨0, 0⟩ := rfl

theorem one_def : (1 : EisensteinInt) = ⟨1, 0⟩ := rfl

theorem add_def (x y : EisensteinInt) : x + y = ⟨x.c0 + y.c0, x.c1 + y.c1⟩ := rfl

theorem neg_def (x : EisensteinInt) : -x = ⟨-x.c0, -x.c1⟩ := rfl

theorem sub_def (x y : EisensteinInt) : x - y = ⟨x.c0 - y.c0, x.c1 - y.c1⟩ := rfl

theorem mul_def (x y : EisensteinInt) :
    x * y = ⟨x.c0 * y.c0 - x.c1 * y.c1, x.c0 * y.c1 + x.c1 * y.c0 - x.c1 * y.c1⟩ := rfl

instance : CommRing EisensteinInt where
  nsmul := nsmulRec
  zsmul := zsmulRec
  add_assoc _ _ _ := by ext <;> simp [add_def] <;> ring
  zero_add _ := by ext <;> simp [add_def, zero_def]
  add_zero _ := by ext <;> simp [add_def, zero_def]
  add_comm _ _ := by ext <;> simp [add_def] <;> ring
  neg_add_cancel _ := by ext <;> simp [add_def, neg_def, zero_def]
  sub_eq_add_neg _ _ := by ext <;> simp [add_def, neg_def, sub_def] <;> ring
  mul_assoc _ _ _ := by ext <;> simp [mul_def] <;> ring
  one_mul _ := by ext <;> simp [mul_def, one_def]
  mul_one _ := by ext <;> simp [mul_def, one_def]
  left_distrib _ _ _ := by ext <;> simp [mul_def, add_def] <;> ring
  right_distrib _ _ _ := by ext <;> simp [mul_def, add_def] <;> ring
  zero_mul _ := by ext <;> simp [mul_def, zero_def]
  mul_zero _ := by ext <;> simp [mul_def, zero_def]
  mul_comm _ _ := by ext <;> simp [mul_def] <;> ring

/-- The generator `ω = e^{2πi/3}` of the ring of Eisenstein integers. -/
def omega : EisensteinInt := ⟨0, 1⟩

theorem omega_quadratic : omega ^ 2 + omega + 1 = 0 := by decide

theorem omega_pow_three : omega ^ 3 = 1 := by decide

theorem omega_sub_one_ne_zero : omega - 1 ≠ 0 := by decide

end EisensteinInt

/-- **The multiplication rule of `ℤ[ω]`**: in any commutative ring carrying a root `s` of
`X² + X + 1`, the product of two `ℤ`-linear combinations of `1, s` is the combination prescribed
by `EisensteinInt.mul_def`. -/
theorem eisensteinMulRule {A : Type*} [CommRing A] {s : A} (hs : s ^ 2 + s + 1 = 0)
    (a0 a1 b0 b1 : ℤ) :
    ((a0 : A) + (a1 : A) * s) * ((b0 : A) + (b1 : A) * s) =
      ((a0 * b0 - a1 * b1 : ℤ) : A) + ((a0 * b1 + a1 * b0 - a1 * b1 : ℤ) : A) * s := by
  push_cast
  linear_combination ((a1 : A) * (b1 : A)) * hs

/-- The primitive cube root of unity `ω = (-1 + i√3)/2` as a complex number. -/
noncomputable def eisensteinOmega : ℂ := (-1 / 2 : ℂ) + ((Real.sqrt 3 / 2 : ℝ) : ℂ) * Complex.I

theorem eisensteinOmega_quadratic : eisensteinOmega ^ 2 + eisensteinOmega + 1 = 0 := by
  have hs : ((Real.sqrt 3 : ℝ) : ℂ) ^ 2 = 3 := by
    rw [← Complex.ofReal_pow, Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 3)]
    norm_num
  unfold eisensteinOmega
  push_cast
  linear_combination (1 / 4 : ℂ) * Complex.I ^ 2 * hs + (3 / 4 : ℂ) * Complex.I_sq

theorem eisensteinOmega_re : eisensteinOmega.re = -1 / 2 := by
  simp [eisensteinOmega]

theorem eisensteinOmega_im : eisensteinOmega.im = Real.sqrt 3 / 2 := by
  simp [eisensteinOmega]

/-- The exact embedding of the Eisenstein integers into the complex numbers,
`ω ↦ (-1 + i√3)/2`. -/
noncomputable def eisensteinToComplex : EisensteinInt →+* ℂ where
  toFun x := (x.c0 : ℂ) + (x.c1 : ℂ) * eisensteinOmega
  map_one' := by simp [EisensteinInt.one_def]
  map_mul' x y := by
    simp only [EisensteinInt.mul_def]
    exact (eisensteinMulRule eisensteinOmega_quadratic x.c0 x.c1 y.c0 y.c1).symm
  map_zero' := by simp [EisensteinInt.zero_def]
  map_add' x y := by simp only [EisensteinInt.add_def]; push_cast; ring

theorem eisensteinToComplex_apply (x : EisensteinInt) :
    eisensteinToComplex x = (x.c0 : ℂ) + (x.c1 : ℂ) * eisensteinOmega := rfl

@[simp] theorem eisensteinToComplex_omega :
    eisensteinToComplex EisensteinInt.omega = eisensteinOmega := by
  simp [eisensteinToComplex_apply, EisensteinInt.omega]

/-- The embedding of the Eisenstein integers is injective: `1` and `ω` are linearly independent
over the rationals because `ω` has the nonzero imaginary part `√3/2`. -/
theorem eisensteinToComplex_injective : Function.Injective eisensteinToComplex := by
  refine (injective_iff_map_eq_zero _).2 fun x hx => ?_
  have hre := congrArg Complex.re hx
  have him := congrArg Complex.im hx
  simp only [eisensteinToComplex_apply, Complex.add_re, Complex.add_im, Complex.mul_re,
    Complex.mul_im, Complex.intCast_re, Complex.intCast_im, eisensteinOmega_re,
    eisensteinOmega_im, Complex.zero_re, Complex.zero_im, zero_mul, add_zero, zero_add,
    sub_zero] at hre him
  have h3 : (0 : ℝ) < Real.sqrt 3 := Real.sqrt_pos.2 (by norm_num)
  have hc1 : (x.c1 : ℝ) = 0 := by
    rcases mul_eq_zero.1 him with h | h
    · exact h
    · linarith
  have hc0 : (x.c0 : ℝ) = 0 := by
    rw [hc1] at hre
    linarith
  rw [EisensteinInt.zero_def]
  ext
  · exact_mod_cast hc0
  · exact_mod_cast hc1

theorem eisensteinToComplex_ne_zero {x : EisensteinInt} (hx : x ≠ 0) :
    eisensteinToComplex x ≠ 0 :=
  fun h => hx (eisensteinToComplex_injective (h.trans (map_zero _).symm))

namespace MPSTensor

/-- The entrywise image of a matrix over the Eisenstein integers in the complex matrices. -/
noncomputable def complexOfEisenstein {m n : Type*} (X : Matrix m n EisensteinInt) :
    Matrix m n ℂ :=
  X.map eisensteinToComplex

@[simp] theorem complexOfEisenstein_apply {m n : Type*} (X : Matrix m n EisensteinInt) (i : m)
    (j : n) : complexOfEisenstein X i j = eisensteinToComplex (X i j) := rfl

theorem complexOfEisenstein_mul {m n o : Type*} [Fintype n] (X : Matrix m n EisensteinInt)
    (Y : Matrix n o EisensteinInt) :
    complexOfEisenstein (X * Y) = complexOfEisenstein X * complexOfEisenstein Y := by
  ext i j
  simp only [complexOfEisenstein_apply, Matrix.mul_apply, map_sum, map_mul]

theorem complexOfEisenstein_one {n : Type*} [DecidableEq n] :
    complexOfEisenstein (1 : Matrix n n EisensteinInt) = 1 := by
  ext i j
  simp only [complexOfEisenstein_apply, Matrix.one_apply]
  split <;> simp

theorem complexOfEisenstein_zero {m n : Type*} :
    complexOfEisenstein (0 : Matrix m n EisensteinInt) = 0 := by
  ext i j
  simp

theorem complexOfEisenstein_add {m n : Type*} (X Y : Matrix m n EisensteinInt) :
    complexOfEisenstein (X + Y) = complexOfEisenstein X + complexOfEisenstein Y := by
  ext i j
  simp

theorem complexOfEisenstein_sub {m n : Type*} (X Y : Matrix m n EisensteinInt) :
    complexOfEisenstein (X - Y) = complexOfEisenstein X - complexOfEisenstein Y := by
  ext i j
  simp

theorem complexOfEisenstein_sum {m n κ : Type*} (t : Finset κ) (f : κ → Matrix m n EisensteinInt) :
    complexOfEisenstein (∑ x ∈ t, f x) = ∑ x ∈ t, complexOfEisenstein (f x) := by
  ext i j
  simp [Matrix.sum_apply]

theorem complexOfEisenstein_single {m n : Type*} [DecidableEq m] [DecidableEq n] (i : m) (j : n) :
    complexOfEisenstein (Matrix.single i j (1 : EisensteinInt)) = Matrix.single i j (1 : ℂ) := by
  ext a b
  simp only [complexOfEisenstein_apply, Matrix.single_apply]
  split <;> simp

theorem complexOfEisenstein_smul {m n : Type*} (c : EisensteinInt) (X : Matrix m n EisensteinInt) :
    complexOfEisenstein (c • X) = eisensteinToComplex c • complexOfEisenstein X := by
  ext i j
  simp [Matrix.smul_apply]

theorem complexOfEisenstein_submatrix {m n m' n' : Type*} (X : Matrix m n EisensteinInt)
    (f : m' → m) (g : n' → n) :
    complexOfEisenstein (X.submatrix f g) = (complexOfEisenstein X).submatrix f g := rfl

theorem complexOfEisenstein_transpose {m n : Type*} (X : Matrix m n EisensteinInt) :
    complexOfEisenstein Xᵀ = (complexOfEisenstein X)ᵀ := rfl

theorem complexOfEisenstein_injective {m n : Type*} :
    Function.Injective (complexOfEisenstein (m := m) (n := n)) := by
  intro X Y h
  funext i j
  exact eisensteinToComplex_injective (congrFun (congrFun h i) j)

theorem complexOfEisenstein_ne_zero {m n : Type*} {X : Matrix m n EisensteinInt} (hX : X ≠ 0) :
    complexOfEisenstein X ≠ 0 :=
  fun h => hX (complexOfEisenstein_injective (h.trans complexOfEisenstein_zero.symm))

theorem complexOfEisenstein_blockDiagonal' {o : Type*} [DecidableEq o] {m' : o → Type*}
    (M : ∀ k, Matrix (m' k) (m' k) EisensteinInt) :
    complexOfEisenstein (Matrix.blockDiagonal' M) =
      Matrix.blockDiagonal' fun k => complexOfEisenstein (M k) :=
  Matrix.blockDiagonal'_map M _ (map_zero _)

variable {d D D₁ D₂ : ℕ}

/-- Word evaluation of a tensor over the Eisenstein integers. -/
def evalWordEisenstein (A : Fin d → Matrix (Fin D) (Fin D) EisensteinInt) :
    List (Fin d) → Matrix (Fin D) (Fin D) EisensteinInt
  | [] => 1
  | i :: w => A i * evalWordEisenstein A w

/-- Word evaluation commutes with the entrywise embedding of the Eisenstein integers. -/
theorem evalWord_complexOfEisenstein (A : Fin d → Matrix (Fin D) (Fin D) EisensteinInt)
    (w : List (Fin d)) :
    Kraus.evalWord (fun i => complexOfEisenstein (A i)) w =
      complexOfEisenstein (evalWordEisenstein A w) := by
  induction w with
  | nil => rw [Kraus.evalWord, evalWordEisenstein, complexOfEisenstein_one]
  | cons i w ih => rw [Kraus.evalWord, evalWordEisenstein, ih, complexOfEisenstein_mul]

/-- The bond-space product of two tensors over the Eisenstein integers,
`(M · N)^{ik} = ∑_j M^{ij} ⊗ N^{jk}`, in the bond order of `finProdFinEquiv`. -/
def mulEisensteinTensor (M : Fin d → Fin d → Matrix (Fin D₁) (Fin D₁) EisensteinInt)
    (N : Fin d → Fin d → Matrix (Fin D₂) (Fin D₂) EisensteinInt) (i k : Fin d) :
    Matrix (Fin (D₁ * D₂)) (Fin (D₁ * D₂)) EisensteinInt :=
  (∑ j : Fin d, (M i j) ⊗ₖ (N j k)).submatrix finProdFinEquiv.symm finProdFinEquiv.symm

/-- The bond-space product commutes with the entrywise embedding of the Eisenstein integers. -/
theorem mulTensor_complexOfEisenstein (M : Fin d → Fin d → Matrix (Fin D₁) (Fin D₁) EisensteinInt)
    (N : Fin d → Fin d → Matrix (Fin D₂) (Fin D₂) EisensteinInt) (i k : Fin d) :
    MPOTensor.mulTensor (fun i j => complexOfEisenstein (M i j))
        (fun i j => complexOfEisenstein (N i j)) i k =
      complexOfEisenstein (mulEisensteinTensor M N i k) := by
  ext x y
  simp only [MPOTensor.mulTensor_apply, mulEisensteinTensor, Matrix.submatrix_apply,
    Matrix.sum_apply, Matrix.kroneckerMap_apply, complexOfEisenstein_apply, map_sum, map_mul]

end MPSTensor
