/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import Mathlib.Analysis.Real.Sqrt
import Mathlib.NumberTheory.Real.GoldenRatio
import Mathlib.RingTheory.AdjoinRoot
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.ExplicitGauge
import TNLean.MPS.MPDO.OperatorProduct

/-!
# The ring of golden integers

The tensors of the Fibonacci string-net matrix product operator algebra have entries in the
degree-four field `ℚ(σ)`, where `σ = φ^{-1/2}` is the inverse square root of the golden ratio and
satisfies the quartic relation `σ⁴ + σ² - 1 = 0`. The entries are in fact all integral: every one
of them is a `ℤ`-linear combination of `1, σ, σ², σ³`, because the golden ratio is a unit of that
ring, `φ = 1 + σ²` and `φ⁻¹ = σ²`.

This file builds the exact arithmetic of that ring in two layers.

The computational layer is `GoldenInt`, the ring `ℤ[σ]` presented by the four integer
coordinates of an element in the basis `1, σ, σ², σ³`, with the multiplication obtained by
reducing `σ⁴ = 1 - σ²`, `σ⁵ = σ - σ³` and `σ⁶ = 2σ² - 1`. Equality of golden integers is
decidable, so every matrix identity between explicit matrices over `ℤ[σ]` is decidable, exactly
as an identity between integer matrices is.

The algebraic layer identifies those coordinates with an actual algebraic number. The quotient
`ℚ[X] ⧸ (X⁴ + X² - 1)` receives `ℤ[σ]` by a ring homomorphism, and it maps to `ℂ` by sending the
class of `X` to the positive real root `√((√5 - 1)/2)`. The composite `goldenToComplex` is the
embedding along which a matrix over `ℤ[σ]` becomes a complex matrix, and identities proved by
decision over `ℤ[σ]` transport to the complex matrices.

## Main definitions

* `GoldenInt`: the ring `ℤ[σ]` in coordinates.
* `GoldenInt.sigma`: the generator `σ = φ^{-1/2}`.
* `goldenPoly`, `GoldenAdjoin`, `adjoinSigma`: the quartic, the quotient ring it presents, and
  the class of `X` in it.
* `GoldenInt.toAdjoin`, `goldenAdjoinToComplex`, `goldenToComplex`: the two layers of the
  embedding and their composite.
* `MPSTensor.complexOfGolden`: the entrywise image of a matrix over `ℤ[σ]` in the complex
  matrices.
* `MPSTensor.mulGoldenTensor`: the bond-space product of two tensors over `ℤ[σ]`.
* `MPSTensor.evalWordGolden`: word evaluation of a tensor over `ℤ[σ]`.

## Main results

* `GoldenInt.sigma_quartic`, `adjoinSigma_quartic`, `goldenSigmaReal_quartic`: the quartic
  relation in the three models.
* `goldenSigmaReal_sq`, `goldenSigmaReal_eq_inv_sqrt_goldenRatio`: `σ² = φ⁻¹` and `σ = 1/√φ`
  for the golden ratio `φ`.
* `goldenMulRule`: the multiplication rule of `ℤ[σ]` in any commutative ring carrying a root of
  the quartic.
* `MPSTensor.complexOfGolden_mul`, `MPSTensor.complexOfGolden_one`: the embedding of matrices is
  multiplicative and unital.
* `MPSTensor.mulTensor_complexOfGolden`, `MPSTensor.evalWord_complexOfGolden`: the bond-space
  product and word evaluation commute with the embedding.
-/

open scoped Matrix Kronecker

/-- A golden integer: the element `c0 + c1 σ + c2 σ² + c3 σ³` of the ring `ℤ[σ]` generated by
`σ = φ^{-1/2}`, the inverse square root of the golden ratio. -/
structure GoldenInt where
  /-- the coordinate of `1` -/
  c0 : ℤ
  /-- the coordinate of `σ` -/
  c1 : ℤ
  /-- the coordinate of `σ ^ 2` -/
  c2 : ℤ
  /-- the coordinate of `σ ^ 3` -/
  c3 : ℤ
  deriving DecidableEq

namespace GoldenInt

@[ext] theorem ext' {x y : GoldenInt} (h0 : x.c0 = y.c0) (h1 : x.c1 = y.c1) (h2 : x.c2 = y.c2)
    (h3 : x.c3 = y.c3) : x = y := by
  cases x; cases y; simp_all

instance : Zero GoldenInt := ⟨⟨0, 0, 0, 0⟩⟩

instance : One GoldenInt := ⟨⟨1, 0, 0, 0⟩⟩

instance : Add GoldenInt :=
  ⟨fun x y => ⟨x.c0 + y.c0, x.c1 + y.c1, x.c2 + y.c2, x.c3 + y.c3⟩⟩

instance : Neg GoldenInt := ⟨fun x => ⟨-x.c0, -x.c1, -x.c2, -x.c3⟩⟩

instance : Sub GoldenInt :=
  ⟨fun x y => ⟨x.c0 - y.c0, x.c1 - y.c1, x.c2 - y.c2, x.c3 - y.c3⟩⟩

/-- Multiplication of golden integers: the product of two polynomials in `σ` of degree at most
three, reduced by `σ⁴ = 1 - σ²`, `σ⁵ = σ - σ³` and `σ⁶ = 2σ² - 1`. -/
instance : Mul GoldenInt :=
  ⟨fun x y =>
    ⟨x.c0 * y.c0 + (x.c1 * y.c3 + x.c2 * y.c2 + x.c3 * y.c1) - x.c3 * y.c3,
      x.c0 * y.c1 + x.c1 * y.c0 + (x.c2 * y.c3 + x.c3 * y.c2),
      x.c0 * y.c2 + x.c1 * y.c1 + x.c2 * y.c0 - (x.c1 * y.c3 + x.c2 * y.c2 + x.c3 * y.c1) +
        2 * (x.c3 * y.c3),
      x.c0 * y.c3 + x.c1 * y.c2 + x.c2 * y.c1 + x.c3 * y.c0 - (x.c2 * y.c3 + x.c3 * y.c2)⟩⟩

theorem zero_def : (0 : GoldenInt) = ⟨0, 0, 0, 0⟩ := rfl

theorem one_def : (1 : GoldenInt) = ⟨1, 0, 0, 0⟩ := rfl

theorem add_def (x y : GoldenInt) :
    x + y = ⟨x.c0 + y.c0, x.c1 + y.c1, x.c2 + y.c2, x.c3 + y.c3⟩ := rfl

theorem neg_def (x : GoldenInt) : -x = ⟨-x.c0, -x.c1, -x.c2, -x.c3⟩ := rfl

theorem sub_def (x y : GoldenInt) :
    x - y = ⟨x.c0 - y.c0, x.c1 - y.c1, x.c2 - y.c2, x.c3 - y.c3⟩ := rfl

theorem mul_def (x y : GoldenInt) :
    x * y =
      ⟨x.c0 * y.c0 + (x.c1 * y.c3 + x.c2 * y.c2 + x.c3 * y.c1) - x.c3 * y.c3,
        x.c0 * y.c1 + x.c1 * y.c0 + (x.c2 * y.c3 + x.c3 * y.c2),
        x.c0 * y.c2 + x.c1 * y.c1 + x.c2 * y.c0 - (x.c1 * y.c3 + x.c2 * y.c2 + x.c3 * y.c1) +
          2 * (x.c3 * y.c3),
        x.c0 * y.c3 + x.c1 * y.c2 + x.c2 * y.c1 + x.c3 * y.c0 -
          (x.c2 * y.c3 + x.c3 * y.c2)⟩ := rfl

instance : CommRing GoldenInt where
  nsmul := nsmulRec
  zsmul := zsmulRec
  add_assoc _ _ _ := by ext <;> simp [add_def] <;> ring
  zero_add _ := by ext <;> simp [add_def, zero_def]
  add_zero _ := by ext <;> simp [add_def, zero_def]
  add_comm _ _ := by ext <;> simp [add_def] <;> ring
  neg_add_cancel _ := by ext <;> simp [add_def, neg_def, zero_def]
  sub_eq_add_neg _ _ := by ext <;> simp [add_def, neg_def, sub_def] <;> ring
  mul_assoc _ _ _ := by ext <;> simp [mul_def] <;> ring
  one_mul _ := by ext <;> simp [mul_def, one_def]
  mul_one _ := by ext <;> simp [mul_def, one_def]
  left_distrib _ _ _ := by ext <;> simp [mul_def, add_def] <;> ring
  right_distrib _ _ _ := by ext <;> simp [mul_def, add_def] <;> ring
  zero_mul _ := by ext <;> simp [mul_def, zero_def]
  mul_zero _ := by ext <;> simp [mul_def, zero_def]
  mul_comm _ _ := by ext <;> simp [mul_def] <;> ring

/-- The generator `σ = φ^{-1/2}` of the ring of golden integers. -/
def sigma : GoldenInt := ⟨0, 1, 0, 0⟩

theorem sigma_quartic : sigma ^ 4 + sigma ^ 2 - 1 = 0 := by decide

end GoldenInt

/-- The quartic `X⁴ + X² - 1` satisfied by `σ = φ^{-1/2}`. -/
noncomputable def goldenPoly : Polynomial ℚ := Polynomial.X ^ 4 + Polynomial.X ^ 2 - 1

/-- The ring `ℚ[X] ⧸ (X⁴ + X² - 1)`, the exact algebraic model of `ℚ(σ)`. -/
abbrev GoldenAdjoin : Type := AdjoinRoot goldenPoly

/-- The class of `X` in `ℚ[X] ⧸ (X⁴ + X² - 1)`, that is `σ = φ^{-1/2}`. -/
noncomputable def adjoinSigma : GoldenAdjoin := AdjoinRoot.root goldenPoly

theorem adjoinSigma_quartic : adjoinSigma ^ 4 + adjoinSigma ^ 2 - 1 = 0 := by
  have h : Polynomial.aeval adjoinSigma goldenPoly = 0 := by
    rw [adjoinSigma, AdjoinRoot.aeval_eq, AdjoinRoot.mk_self]
  simpa [goldenPoly] using h

/-- **The multiplication rule of `ℤ[σ]`**: in any commutative ring carrying a root `s` of the
quartic `X⁴ + X² - 1`, the product of two `ℤ`-linear combinations of `1, s, s², s³` is the
combination prescribed by `GoldenInt.mul_def`. -/
theorem goldenMulRule {A : Type*} [CommRing A] {s : A} (hs : s ^ 4 + s ^ 2 - 1 = 0)
    (a0 a1 a2 a3 b0 b1 b2 b3 : ℤ) :
    ((a0 : A) + (a1 : A) * s + (a2 : A) * s ^ 2 + (a3 : A) * s ^ 3) *
        ((b0 : A) + (b1 : A) * s + (b2 : A) * s ^ 2 + (b3 : A) * s ^ 3) =
      ((a0 * b0 + (a1 * b3 + a2 * b2 + a3 * b1) - a3 * b3 : ℤ) : A) +
        ((a0 * b1 + a1 * b0 + (a2 * b3 + a3 * b2) : ℤ) : A) * s +
        ((a0 * b2 + a1 * b1 + a2 * b0 - (a1 * b3 + a2 * b2 + a3 * b1) + 2 * (a3 * b3) : ℤ) : A) *
          s ^ 2 +
        ((a0 * b3 + a1 * b2 + a2 * b1 + a3 * b0 - (a2 * b3 + a3 * b2) : ℤ) : A) * s ^ 3 := by
  push_cast
  linear_combination ((a1 : A) * (b3 : A) + (a2 : A) * (b2 : A) + (a3 : A) * (b1 : A) +
    ((a2 : A) * (b3 : A) + (a3 : A) * (b2 : A)) * s +
    (a3 : A) * (b3 : A) * (s ^ 2 - 1)) * hs

/-- The exact embedding of the golden integers into `ℚ[X] ⧸ (X⁴ + X² - 1)`. -/
noncomputable def GoldenInt.toAdjoin : GoldenInt →+* GoldenAdjoin where
  toFun x := (x.c0 : GoldenAdjoin) + (x.c1 : GoldenAdjoin) * adjoinSigma +
    (x.c2 : GoldenAdjoin) * adjoinSigma ^ 2 + (x.c3 : GoldenAdjoin) * adjoinSigma ^ 3
  map_one' := by simp [GoldenInt.one_def]
  map_mul' x y := by
    simp only [GoldenInt.mul_def]
    exact (goldenMulRule adjoinSigma_quartic x.c0 x.c1 x.c2 x.c3 y.c0 y.c1 y.c2 y.c3).symm
  map_zero' := by simp [GoldenInt.zero_def]
  map_add' x y := by simp only [GoldenInt.add_def]; push_cast; ring

/-- The real number `σ = φ^{-1/2} = √((√5 - 1)/2)`. -/
noncomputable def goldenSigmaReal : ℝ := Real.sqrt ((Real.sqrt 5 - 1) / 2)

theorem goldenSigmaReal_quartic : goldenSigmaReal ^ 4 + goldenSigmaReal ^ 2 - 1 = 0 := by
  have h5 : Real.sqrt 5 ^ 2 = 5 := Real.sq_sqrt (by norm_num)
  have h5' : (1 : ℝ) ≤ Real.sqrt 5 := by nlinarith [Real.sqrt_nonneg 5]
  have hsq : goldenSigmaReal ^ 2 = (Real.sqrt 5 - 1) / 2 :=
    Real.sq_sqrt (by linarith)
  have h4 : goldenSigmaReal ^ 4 = (goldenSigmaReal ^ 2) ^ 2 := by ring
  rw [h4, hsq]
  nlinarith [h5]

/-- `σ² = (√5 - 1)/2` is the inverse of the golden ratio. -/
theorem goldenSigmaReal_sq : goldenSigmaReal ^ 2 = Real.goldenRatio⁻¹ := by
  have h5 : (1 : ℝ) ≤ Real.sqrt 5 := by
    rw [show (1 : ℝ) = Real.sqrt 1 by simp]
    exact Real.sqrt_le_sqrt (by norm_num)
  rw [goldenSigmaReal, Real.sq_sqrt (by linarith), Real.inv_goldenRatio]
  ring

/-- `σ = 1/√φ` for the golden ratio `φ`. -/
theorem goldenSigmaReal_eq_inv_sqrt_goldenRatio :
    goldenSigmaReal = (Real.sqrt Real.goldenRatio)⁻¹ := by
  have h0 : 0 ≤ goldenSigmaReal := Real.sqrt_nonneg _
  rw [← Real.sqrt_inv, ← goldenSigmaReal_sq, Real.sqrt_sq h0]

/-- The number `σ = φ^{-1/2}` as a complex number. -/
noncomputable def goldenSigmaComplex : ℂ := (goldenSigmaReal : ℂ)

theorem goldenSigmaComplex_quartic :
    goldenSigmaComplex ^ 4 + goldenSigmaComplex ^ 2 - 1 = 0 := by
  have h := congrArg (fun t : ℝ => (t : ℂ)) goldenSigmaReal_quartic
  simpa [goldenSigmaComplex] using h

/-- The evaluation of `ℚ[X] ⧸ (X⁴ + X² - 1)` at the positive real root `√((√5 - 1)/2)`. -/
noncomputable def goldenAdjoinToComplex : GoldenAdjoin →+* ℂ :=
  AdjoinRoot.lift (algebraMap ℚ ℂ) goldenSigmaComplex (by
    simpa [goldenPoly] using goldenSigmaComplex_quartic)

/-- The exact embedding of the golden integers into the complex numbers, `σ ↦ √((√5 - 1)/2)`. -/
noncomputable def goldenToComplex : GoldenInt →+* ℂ :=
  goldenAdjoinToComplex.comp GoldenInt.toAdjoin

@[simp] theorem goldenToComplex_sigma :
    goldenToComplex GoldenInt.sigma = goldenSigmaComplex := by
  simp [goldenToComplex, GoldenInt.toAdjoin, GoldenInt.sigma, adjoinSigma,
    goldenAdjoinToComplex]

namespace MPSTensor

/-- The entrywise image of a matrix over the golden integers in the complex matrices. -/
noncomputable def complexOfGolden {m n : Type*} (X : Matrix m n GoldenInt) : Matrix m n ℂ :=
  X.map goldenToComplex

@[simp] theorem complexOfGolden_apply {m n : Type*} (X : Matrix m n GoldenInt) (i : m) (j : n) :
    complexOfGolden X i j = goldenToComplex (X i j) := rfl

theorem complexOfGolden_mul {m n o : Type*} [Fintype n] (X : Matrix m n GoldenInt)
    (Y : Matrix n o GoldenInt) :
    complexOfGolden (X * Y) = complexOfGolden X * complexOfGolden Y := by
  ext i j
  simp only [complexOfGolden_apply, Matrix.mul_apply, map_sum, map_mul]

theorem complexOfGolden_one {n : Type*} [DecidableEq n] :
    complexOfGolden (1 : Matrix n n GoldenInt) = 1 := by
  ext i j
  simp only [complexOfGolden_apply, Matrix.one_apply]
  split <;> simp

theorem complexOfGolden_zero {m n : Type*} :
    complexOfGolden (0 : Matrix m n GoldenInt) = 0 := by
  ext i j
  simp

theorem complexOfGolden_add {m n : Type*} (X Y : Matrix m n GoldenInt) :
    complexOfGolden (X + Y) = complexOfGolden X + complexOfGolden Y := by
  ext i j
  simp

theorem complexOfGolden_sum {m n κ : Type*} (t : Finset κ) (f : κ → Matrix m n GoldenInt) :
    complexOfGolden (∑ x ∈ t, f x) = ∑ x ∈ t, complexOfGolden (f x) := by
  ext i j
  simp [Matrix.sum_apply]

theorem complexOfGolden_single {m n : Type*} [DecidableEq m] [DecidableEq n] (i : m) (j : n) :
    complexOfGolden (Matrix.single i j (1 : GoldenInt)) = Matrix.single i j (1 : ℂ) := by
  ext a b
  simp only [complexOfGolden_apply, Matrix.single_apply]
  split <;> simp

theorem complexOfGolden_smul {m n : Type*} (c : GoldenInt) (X : Matrix m n GoldenInt) :
    complexOfGolden (c • X) = goldenToComplex c • complexOfGolden X := by
  ext i j
  simp [Matrix.smul_apply]

variable {d D D₁ D₂ : ℕ}

/-- Word evaluation of a tensor over the golden integers. -/
def evalWordGolden (A : Fin d → Matrix (Fin D) (Fin D) GoldenInt) :
    List (Fin d) → Matrix (Fin D) (Fin D) GoldenInt
  | [] => 1
  | i :: w => A i * evalWordGolden A w

/-- Word evaluation commutes with the entrywise embedding of the golden integers. -/
theorem evalWord_complexOfGolden (A : Fin d → Matrix (Fin D) (Fin D) GoldenInt)
    (w : List (Fin d)) :
    Kraus.evalWord (fun i => complexOfGolden (A i)) w = complexOfGolden (evalWordGolden A w) := by
  induction w with
  | nil => rw [Kraus.evalWord, evalWordGolden, complexOfGolden_one]
  | cons i w ih => rw [Kraus.evalWord, evalWordGolden, ih, complexOfGolden_mul]

/-- The bond-space product of two tensors over the golden integers,
`(M · N)^{ik} = ∑_j M^{ij} ⊗ N^{jk}`, in the bond order of `finProdFinEquiv`. -/
def mulGoldenTensor (M : Fin d → Fin d → Matrix (Fin D₁) (Fin D₁) GoldenInt)
    (N : Fin d → Fin d → Matrix (Fin D₂) (Fin D₂) GoldenInt) (i k : Fin d) :
    Matrix (Fin (D₁ * D₂)) (Fin (D₁ * D₂)) GoldenInt :=
  (∑ j : Fin d, (M i j) ⊗ₖ (N j k)).submatrix finProdFinEquiv.symm finProdFinEquiv.symm

/-- The bond-space product commutes with the entrywise embedding of the golden integers. -/
theorem mulTensor_complexOfGolden (M : Fin d → Fin d → Matrix (Fin D₁) (Fin D₁) GoldenInt)
    (N : Fin d → Fin d → Matrix (Fin D₂) (Fin D₂) GoldenInt) (i k : Fin d) :
    MPOTensor.mulTensor (fun i j => complexOfGolden (M i j))
        (fun i j => complexOfGolden (N i j)) i k =
      complexOfGolden (mulGoldenTensor M N i k) := by
  ext x y
  simp only [MPOTensor.mulTensor_apply, mulGoldenTensor, Matrix.submatrix_apply, Matrix.sum_apply,
    Matrix.kroneckerMap_apply, complexOfGolden_apply, map_sum, map_mul]

end MPSTensor
