/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.
-- Import architecture: docs/import_structure.md.
-- Generated aggregator module: TNLean.MPS.FundamentalTheorem.Reduction.Examples

import TNLean.MPS.FundamentalTheorem.Reduction.Examples.AnomalousCondensationZ2Z2
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.AnomalousCondensationZ2Z2Defect
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.AnomalousCondensationZ2Z2NonSplit
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.AnomalousCondensationZ2Z2Split
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.AnomalousCondensationZ2Z2Unitary
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.AssemblyLemmas
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.CZXAnomaly
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.CZXAnomalyClass
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.CZXDecoratedFusion
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.CZXDecoratedTensor
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.CZXPlusIdentity
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.CZXReviewCanonicalForm
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.CZXReviewTensor
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.CZXSquare
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.CZXTensor
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.CZXUnitary
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.EisensteinCertificates
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.EisensteinRing
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.ElementaryStates
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.ExplicitGauge
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.Fibonacci
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.FibonacciAction
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.FibonacciAnomaly
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.FibonacciFSymbol
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.FibonacciUnit
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.GHZSectors
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.GoldenCompression
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.GoldenRing
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.IsingGauge
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.IsingLetterSectorOne
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.IsingLetterSectorPsi
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.IsingLetterSectorSigmaAbelian
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.IsingLetterSectorSigmaSigma
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.IsingSectorAction
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.IsingTensors
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.IsingWeightedTwist
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.JordanBoundary
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.KramersWannier
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.KramersWannierAction
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.OneLabelCandidate
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.OneSlotGauge
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.ParityGraded
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.RepeatedBlock
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.RingEmbedding
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.StackedPairGauge
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.TwistedDimer
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.TwistedDimerPairOneOne
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.TwistedDimerPairOneZero
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.TwistedDimerPairZeroOne
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.TwistedDimerPairs
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.Z3AnomalousDefect
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.Z3AnomalousDefectCompression
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.Z3AnomalousFusion
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.Z3AnomalousInverseFusion
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.Z3AnomalousTensor
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.Z3AnomalousUnitary
import TNLean.MPS.FundamentalTheorem.Reduction.Examples.Zsqrt2Ring
