/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import Mathlib.LinearAlgebra.Projection
import Mathlib.Tactic
import QICLean.Kraus.Word

/-!
# Finite certificates for word compression

Let `B` be a `Fin n`-indexed family of matrices on `ℂ^D`, and let `A` be the
corresponding `Fin n`-indexed family on `ℂ^d`.
This file proves the finite-dimensional compression principle used in
`Notes/OpenProblemsTN/followup/asymmetric_mpoa/sections/boundary_equal_modules.tex`:
if rectangular matrices `V : ℂ^d → ℂ^D` and `W : ℂ^D → ℂ^d` satisfy
`W V = 1` and compress every nonempty word of length at most `D - d + 1`, then
they compress every word.  The proof uses the reachable spaces
`span {B^w Vx : |w| ≤ L}`.  Since the initial reachable space has dimension at
least `d`, the chain must stop by level `D - d`; the stopped space is invariant,
and the short word identities give an intertwining quotient map on it.

The second main result identifies this finite certificate with the intrinsic
condition that `A` occurs as an invariant subquotient of `B`: there is a
`B`-invariant subspace `R ⊆ ℂ^D` and a surjective map `q : R → ℂ^d` intertwining
all generators.  This is deliberately a subquotient statement; no invariant
ambient complement is asserted.

## Main declarations

* `Kraus.reachableSpan`: the span of vectors `B^w Vx` with `|w| ≤ L`.
* `Kraus.allWordCompression_of_finiteWordCompression`: the sharp finite
  certificate, with bound `D - d + 1`.
* `Kraus.HasInvariantSubquotient`: invariant-subquotient occurrence.
* `Kraus.finiteWordCompression_iff_hasInvariantSubquotient`: equivalence of the
  sharp finite certificate and invariant-subquotient occurrence.
-/

open scoped Matrix

namespace Kraus

variable {n d D : ℕ}

/-- The compression identity for all words. -/
def AllWordCompression (A : MPSTensor n d) (B : MPSTensor n D)
    (V : Matrix (Fin D) (Fin d) ℂ) (W : Matrix (Fin d) (Fin D) ℂ) : Prop :=
  ∀ w : List (Fin n), W * evalWord B w * V = evalWord A w

/-- A compression identity checked up to word length `N`, including the empty word through
`W V = 1`. -/
def WordCompressionUpTo (A : MPSTensor n d) (B : MPSTensor n D)
    (V : Matrix (Fin D) (Fin d) ℂ) (W : Matrix (Fin d) (Fin D) ℂ) (N : ℕ) : Prop :=
  W * V = 1 ∧
    ∀ w : List (Fin n), 1 ≤ w.length → w.length ≤ N →
      W * evalWord B w * V = evalWord A w

/-- Existence of a finite word-compression certificate up to length `N`. -/
def HasWordCompressionUpTo (A : MPSTensor n d) (B : MPSTensor n D) (N : ℕ) : Prop :=
  ∃ (V : Matrix (Fin D) (Fin d) ℂ) (W : Matrix (Fin d) (Fin D) ℂ),
    WordCompressionUpTo A B V W N

/-- The reachable space generated by `im V` under words of length at most `L`. -/
def reachableSpan (B : MPSTensor n D) (V : Matrix (Fin D) (Fin d) ℂ) (L : ℕ) :
    Submodule ℂ (Fin D → ℂ) :=
  Submodule.span ℂ
    { y | ∃ (w : List (Fin n)) (x : Fin d → ℂ),
        w.length ≤ L ∧ y = evalWord B w *ᵥ (V *ᵥ x) }

lemma reachableSpan_mono (B : MPSTensor n D) (V : Matrix (Fin D) (Fin d) ℂ)
    {m L : ℕ} (hmL : m ≤ L) :
    reachableSpan B V m ≤ reachableSpan B V L := by
  exact Submodule.span_mono fun y hy => by
    rcases hy with ⟨w, x, hw, rfl⟩
    exact ⟨w, x, hw.trans hmL, rfl⟩

lemma mem_reachableSpan (B : MPSTensor n D) (V : Matrix (Fin D) (Fin d) ℂ)
    {L : ℕ} {w : List (Fin n)} (hw : w.length ≤ L) (x : Fin d → ℂ) :
    evalWord B w *ᵥ (V *ᵥ x) ∈ reachableSpan B V L :=
  Submodule.subset_span ⟨w, x, hw, rfl⟩

lemma image_mem_reachableSpan (B : MPSTensor n D) (V : Matrix (Fin D) (Fin d) ℂ)
    (L : ℕ) (x : Fin d → ℂ) :
    V *ᵥ x ∈ reachableSpan B V L := by
  simpa using mem_reachableSpan B V (L := L) (w := []) (by simp) x

lemma mulVec_mem_reachableSpan_succ (B : MPSTensor n D) (V : Matrix (Fin D) (Fin d) ℂ)
    (i : Fin n) {L : ℕ} {y : Fin D → ℂ} (hy : y ∈ reachableSpan B V L) :
    B i *ᵥ y ∈ reachableSpan B V (L + 1) := by
  induction hy using Submodule.span_induction with
  | mem y hy =>
      rcases hy with ⟨w, x, hw, rfl⟩
      have hlen : (i :: w).length ≤ L + 1 := by simpa using Nat.succ_le_succ hw
      simpa [evalWord, Matrix.mulVec_mulVec, Matrix.mul_assoc] using
        mem_reachableSpan B V (L := L + 1) (w := i :: w) hlen x
  | zero =>
      simp
  | add y z _ _ hy hz =>
      simpa [Matrix.mulVec_add] using (Submodule.add_mem _ hy hz)
  | smul c y _ hy =>
      simpa [Matrix.mulVec_smul] using (Submodule.smul_mem _ c hy)

lemma invariant_of_reachableSpan_eq_succ (B : MPSTensor n D)
    (V : Matrix (Fin D) (Fin d) ℂ) {L : ℕ}
    (h : reachableSpan B V L = reachableSpan B V (L + 1)) :
    ∀ i : Fin n, ∀ y ∈ reachableSpan B V L, B i *ᵥ y ∈ reachableSpan B V L := by
  intro i y hy
  rw [h]
  exact mulVec_mem_reachableSpan_succ B V i hy

lemma exists_reachableSpan_eq_succ (B : MPSTensor n D)
    (V : Matrix (Fin D) (Fin d) ℂ) (W : Matrix (Fin d) (Fin D) ℂ)
    (hWV : W * V = 1) (hD : d ≤ D) :
    ∃ m ≤ D - d, reachableSpan B V m = reachableSpan B V (m + 1) := by
  by_contra hnone
  have hstrict : ∀ m ≤ D - d, reachableSpan B V m < reachableSpan B V (m + 1) := by
    intro m hm
    refine lt_of_le_of_ne (reachableSpan_mono B V (Nat.le_succ m)) ?_
    exact fun heq => hnone ⟨m, hm, heq⟩
  let Vlin : (Fin d → ℂ) →ₗ[ℂ] (Fin D → ℂ) := Matrix.toLin' V
  have hVinj : Function.Injective Vlin := by
    intro x y hxy
    have := congrArg (fun z => W *ᵥ z) hxy
    simpa [Vlin, Matrix.mulVec_mulVec, hWV] using this
  have hrange_le : LinearMap.range Vlin ≤ reachableSpan B V 0 := by
    intro y hy
    rcases hy with ⟨x, rfl⟩
    exact image_mem_reachableSpan B V 0 x
  have hd_le_R0 : d ≤ Module.finrank ℂ (reachableSpan B V 0) := by
    have hfin := LinearMap.finrank_range_of_inj hVinj
    have hmono := Submodule.finrank_mono hrange_le
    simpa [Vlin, hfin] using hmono
  have hdim : ∀ k ≤ D - d + 1,
      d + k ≤ Module.finrank ℂ (reachableSpan B V k) := by
    intro k hk
    induction k with
    | zero =>
        simpa using hd_le_R0
    | succ k ih =>
        have hk_le : k ≤ D - d := by omega
        have hk_bound : k ≤ D - d + 1 := by omega
        have hlt := Submodule.finrank_lt_finrank_of_lt (hstrict k hk_le)
        have hlt' : d + k < Module.finrank ℂ (reachableSpan B V (k + 1)) :=
          (ih hk_bound).trans_lt hlt
        omega
  have htoo_large :
      D + 1 ≤ Module.finrank ℂ (reachableSpan B V (D - d + 1)) := by
    have := hdim (D - d + 1) (le_rfl)
    have hsum : d + (D - d + 1) = D + 1 := by omega
    simpa [hsum] using this
  have hleD : Module.finrank ℂ (reachableSpan B V (D - d + 1)) ≤ D := by
    simpa [Module.finrank_fintype_fun_eq_card] using
      (Submodule.finrank_le (reachableSpan B V (D - d + 1)))
  omega

private noncomputable def stoppedIndex (B : MPSTensor n D)
    (V : Matrix (Fin D) (Fin d) ℂ) (W : Matrix (Fin d) (Fin D) ℂ)
    (hWV : W * V = 1) (hD : d ≤ D) : ℕ :=
  Classical.choose (exists_reachableSpan_eq_succ B V W hWV hD)

private lemma stoppedIndex_le (B : MPSTensor n D)
    (V : Matrix (Fin D) (Fin d) ℂ) (W : Matrix (Fin d) (Fin D) ℂ)
    (hWV : W * V = 1) (hD : d ≤ D) :
    stoppedIndex B V W hWV hD ≤ D - d :=
  (Classical.choose_spec (exists_reachableSpan_eq_succ B V W hWV hD)).1

private lemma stoppedIndex_eq_succ (B : MPSTensor n D)
    (V : Matrix (Fin D) (Fin d) ℂ) (W : Matrix (Fin d) (Fin D) ℂ)
    (hWV : W * V = 1) (hD : d ≤ D) :
    reachableSpan B V (stoppedIndex B V W hWV hD) =
      reachableSpan B V (stoppedIndex B V W hWV hD + 1) :=
  (Classical.choose_spec (exists_reachableSpan_eq_succ B V W hWV hD)).2

/-- Data saying that `A` occurs as an invariant subquotient of `B`.  The map `q` is defined only
on the invariant subspace `R`; the definition makes no choice of an invariant ambient
complement. -/
structure InvariantSubquotient (A : MPSTensor n d) (B : MPSTensor n D) where
  R : Submodule ℂ (Fin D → ℂ)
  invariant : ∀ i : Fin n, ∀ x ∈ R, B i *ᵥ x ∈ R
  q : R →ₗ[ℂ] (Fin d → ℂ)
  q_surjective : LinearMap.range q = ⊤
  intertwines : ∀ i : Fin n, ∀ x : R,
    q ⟨B i *ᵥ x, invariant i x x.property⟩ = A i *ᵥ q x

/-- Existence of an invariant subquotient carrying the word representation of `A`. -/
def HasInvariantSubquotient (A : MPSTensor n d) (B : MPSTensor n D) : Prop :=
  Nonempty (InvariantSubquotient A B)

namespace InvariantSubquotient

variable {A : MPSTensor n d} {B : MPSTensor n D} (Q : InvariantSubquotient A B)

lemma evalWord_mem (w : List (Fin n)) (x : Q.R) :
    evalWord B w *ᵥ x ∈ Q.R := by
  induction w with
  | nil =>
      simp
  | cons i w ih =>
      simpa [evalWord, Matrix.mulVec_mulVec] using Q.invariant i (evalWord B w *ᵥ x) ih

lemma q_evalWord (w : List (Fin n)) (x : Q.R) :
    Q.q ⟨evalWord B w *ᵥ x, Q.evalWord_mem w x⟩ = evalWord A w *ᵥ Q.q x := by
  induction w with
  | nil =>
      simp [evalWord]
  | cons i w ih =>
      have harg :
          (⟨evalWord B (i :: w) *ᵥ x, Q.evalWord_mem (i :: w) x⟩ : Q.R) =
            ⟨B i *ᵥ (evalWord B w *ᵥ x), Q.invariant i _ (Q.evalWord_mem w x)⟩ := by
        apply Subtype.ext
        simp [evalWord, Matrix.mulVec_mulVec]
      calc
        Q.q ⟨evalWord B (i :: w) *ᵥ x, Q.evalWord_mem (i :: w) x⟩
            = Q.q ⟨B i *ᵥ (evalWord B w *ᵥ x), Q.invariant i _ (Q.evalWord_mem w x)⟩ := by
                rw [harg]
        _ = A i *ᵥ Q.q ⟨evalWord B w *ᵥ x, Q.evalWord_mem w x⟩ := by
                simpa using
                  Q.intertwines i ⟨evalWord B w *ᵥ x, Q.evalWord_mem w x⟩
        _ = evalWord A (i :: w) *ᵥ Q.q x := by
                simp [evalWord, ih, Matrix.mulVec_mulVec]

end InvariantSubquotient

private lemma q_on_reachableSpan_generator
    {A : MPSTensor n d} {B : MPSTensor n D}
    {V : Matrix (Fin D) (Fin d) ℂ} {W : Matrix (Fin d) (Fin D) ℂ}
    {L N : ℕ}
    (hWV : W * V = 1)
    (hshort : ∀ w : List (Fin n), 1 ≤ w.length → w.length ≤ N →
      W * evalWord B w * V = evalWord A w)
    (hN : L ≤ N)
    {w : List (Fin n)} (hw : w.length ≤ L) (x : Fin d → ℂ) :
    W *ᵥ (evalWord B w *ᵥ (V *ᵥ x)) = evalWord A w *ᵥ x := by
  rcases w with _ | ⟨i, w⟩
  · simp [evalWord, hWV, Matrix.mulVec_mulVec]
  · have hlen_pos : 1 ≤ (i :: w).length := by simp
    have hlen_le : (i :: w).length ≤ N := by
      exact hw.trans hN
    have hmat := hshort (i :: w) hlen_pos hlen_le
    calc
      W *ᵥ (evalWord B (i :: w) *ᵥ (V *ᵥ x))
          = (W * evalWord B (i :: w) * V) *ᵥ x := by
              simp [Matrix.mulVec_mulVec, Matrix.mul_assoc]
      _ = evalWord A (i :: w) *ᵥ x := by rw [hmat]

private lemma reachable_q_intertwines
    {A : MPSTensor n d} {B : MPSTensor n D}
    {V : Matrix (Fin D) (Fin d) ℂ} {W : Matrix (Fin d) (Fin D) ℂ}
    {L N : ℕ}
    (hWV : W * V = 1)
    (hshort : ∀ w : List (Fin n), 1 ≤ w.length → w.length ≤ N →
      W * evalWord B w * V = evalWord A w)
    (hN : L + 1 ≤ N) :
    ∀ i : Fin n, ∀ y ∈ reachableSpan B V L,
      W *ᵥ (B i *ᵥ y) = A i *ᵥ (W *ᵥ y) := by
  intro i y hy
  induction hy using Submodule.span_induction with
  | mem y hy =>
      rcases hy with ⟨w, x, hw, rfl⟩
      have left_id := q_on_reachableSpan_generator
        (A := A) (B := B) (V := V) (W := W) (L := L + 1) hWV hshort hN
        (w := i :: w) (by simpa using Nat.succ_le_succ hw) x
      have right_id := q_on_reachableSpan_generator
        (A := A) (B := B) (V := V) (W := W) (L := L) hWV hshort (Nat.le_succ L |>.trans hN)
        (w := w) hw x
      have hright :
          (A i * (W * (evalWord B w * V))) *ᵥ x =
            (A i * evalWord A w) *ᵥ x := by
        calc
          (A i * (W * (evalWord B w * V))) *ᵥ x
              = A i *ᵥ (W *ᵥ (evalWord B w *ᵥ (V *ᵥ x))) := by
                  simp [Matrix.mulVec_mulVec]
          _ = A i *ᵥ (evalWord A w *ᵥ x) := by rw [right_id]
          _ = (A i * evalWord A w) *ᵥ x := by rw [Matrix.mulVec_mulVec]
      simpa [evalWord, Matrix.mul_assoc, Matrix.mulVec_mulVec] using left_id.trans hright.symm
  | zero =>
      simp
  | add y z _ _ hy hz =>
      simp [Matrix.mulVec_add, hy, hz]
  | smul c y _ hy =>
      simp [Matrix.mulVec_smul, hy]

/-- The stopped reachable space, with `W` restricted to it, is an invariant subquotient. -/
noncomputable def invariantSubquotient_of_finiteWordCompression
    {A : MPSTensor n d} {B : MPSTensor n D}
    {V : Matrix (Fin D) (Fin d) ℂ} {W : Matrix (Fin d) (Fin D) ℂ}
    (hD : d ≤ D) (hWV : W * V = 1)
    (hshort : ∀ w : List (Fin n), 1 ≤ w.length → w.length ≤ D - d + 1 →
      W * evalWord B w * V = evalWord A w) :
    InvariantSubquotient A B := by
  classical
  let m := stoppedIndex B V W hWV hD
  have hmle : m ≤ D - d := stoppedIndex_le B V W hWV hD
  have hm : reachableSpan B V m = reachableSpan B V (m + 1) :=
    stoppedIndex_eq_succ B V W hWV hD
  let R := reachableSpan B V m
  let q : R →ₗ[ℂ] (Fin d → ℂ) := (Matrix.toLin' W).domRestrict R
  refine
    { R := R
      invariant := invariant_of_reachableSpan_eq_succ B V hm
      q := q
      q_surjective := ?_
      intertwines := ?_ }
  · rw [LinearMap.range_eq_top]
    intro x
    refine ⟨⟨V *ᵥ x, image_mem_reachableSpan B V m x⟩, ?_⟩
    simp [q, Matrix.toLin'_apply, Matrix.mulVec_mulVec, hWV]
  · intro i x
    change W *ᵥ (B i *ᵥ x) = A i *ᵥ (W *ᵥ x)
    exact reachable_q_intertwines
      (A := A) (B := B) (V := V) (W := W) hWV hshort (by omega) i x x.property

/-- The sharp finite certificate implies compression of every word. -/
theorem allWordCompression_of_finiteWordCompression
    {A : MPSTensor n d} {B : MPSTensor n D}
    {V : Matrix (Fin D) (Fin d) ℂ} {W : Matrix (Fin d) (Fin D) ℂ}
    (hD : d ≤ D) (hcert : WordCompressionUpTo A B V W (D - d + 1)) :
    AllWordCompression A B V W := by
  classical
  rcases hcert with ⟨hWV, hshort⟩
  let m := stoppedIndex B V W hWV hD
  have hm : reachableSpan B V m = reachableSpan B V (m + 1) :=
    stoppedIndex_eq_succ B V W hWV hD
  have hmle : m ≤ D - d := stoppedIndex_le B V W hWV hD
  have hinv := invariant_of_reachableSpan_eq_succ B V hm
  have hinter : ∀ i : Fin n, ∀ y ∈ reachableSpan B V m,
      W *ᵥ (B i *ᵥ y) = A i *ᵥ (W *ᵥ y) :=
    reachable_q_intertwines (A := A) (B := B) (V := V) (W := W)
      hWV hshort (by omega)
  intro w
  ext a b
  have hpair : evalWord B w *ᵥ (V *ᵥ Pi.single b (1 : ℂ)) ∈ reachableSpan B V m ∧
      W *ᵥ (evalWord B w *ᵥ (V *ᵥ Pi.single b (1 : ℂ))) =
        evalWord A w *ᵥ Pi.single b (1 : ℂ) := by
    induction w with
    | nil =>
        constructor
        · simpa [evalWord] using
            image_mem_reachableSpan B V m (Pi.single b (1 : ℂ))
        · calc
            W *ᵥ (evalWord B [] *ᵥ (V *ᵥ Pi.single b (1 : ℂ)))
                = (W * V) *ᵥ Pi.single b (1 : ℂ) := by
                    rw [evalWord, Matrix.one_mulVec, Matrix.mulVec_mulVec]
            _ = evalWord A [] *ᵥ Pi.single b (1 : ℂ) := by
                    rw [hWV]
                    simp [evalWord]
    | cons i w ih =>
        rcases ih with ⟨hmem, hEq⟩
        constructor
        · simpa [evalWord, Matrix.mulVec_mulVec] using
            hinv i (evalWord B w *ᵥ (V *ᵥ Pi.single b (1 : ℂ))) hmem
        · have hstep := hinter i (evalWord B w *ᵥ (V *ᵥ Pi.single b (1 : ℂ))) hmem
          calc
            W *ᵥ (evalWord B (i :: w) *ᵥ (V *ᵥ Pi.single b (1 : ℂ)))
                = W *ᵥ (B i *ᵥ (evalWord B w *ᵥ (V *ᵥ Pi.single b (1 : ℂ)))) := by
                    simp [evalWord, Matrix.mulVec_mulVec]
            _ = A i *ᵥ (W *ᵥ (evalWord B w *ᵥ (V *ᵥ Pi.single b (1 : ℂ)))) := hstep
            _ = A i *ᵥ (evalWord A w *ᵥ Pi.single b (1 : ℂ)) := by rw [hEq]
            _ = evalWord A (i :: w) *ᵥ Pi.single b (1 : ℂ) := by
                    rw [evalWord, Matrix.mulVec_mulVec]
  have hvec := hpair.2
  change (((W * evalWord B w) *ᵥ V.col b) a) = (evalWord A w).col b a
  simpa [Matrix.mulVec_single_one] using congrFun hvec a

/-- A finite certificate gives an invariant subquotient. -/
theorem hasInvariantSubquotient_of_hasWordCompressionUpTo
    {A : MPSTensor n d} {B : MPSTensor n D} (hD : d ≤ D)
    (h : HasWordCompressionUpTo A B (D - d + 1)) :
    HasInvariantSubquotient A B := by
  rcases h with ⟨V, W, hcert⟩
  exact ⟨invariantSubquotient_of_finiteWordCompression
    (A := A) (B := B) (V := V) (W := W) hD hcert.1 hcert.2⟩

private noncomputable def matrixOf (f : (Fin d → ℂ) →ₗ[ℂ] (Fin D → ℂ)) :
    Matrix (Fin D) (Fin d) ℂ :=
  LinearMap.toMatrix' f

private noncomputable def matrixOf' (f : (Fin D → ℂ) →ₗ[ℂ] (Fin d → ℂ)) :
    Matrix (Fin d) (Fin D) ℂ :=
  LinearMap.toMatrix' f

/-- An invariant subquotient gives matrices `V,W` compressing every word.  The proof chooses a
linear section of `q` and an arbitrary linear extension of `q` from `R` to the ambient space by
projecting onto a complement of `R`; the complement is not asserted to be invariant. -/
theorem exists_allWordCompression_of_hasInvariantSubquotient
    {A : MPSTensor n d} {B : MPSTensor n D}
    (h : HasInvariantSubquotient A B) :
    ∃ (V : Matrix (Fin D) (Fin d) ℂ) (W : Matrix (Fin d) (Fin D) ℂ),
      W * V = 1 ∧ AllWordCompression A B V W := by
  classical
  rcases h with ⟨Q⟩
  obtain ⟨s, hs⟩ := Q.q.exists_rightInverse_of_surjective Q.q_surjective
  obtain ⟨C, hC⟩ := Submodule.exists_isCompl Q.R
  let p : (Fin D → ℂ) →ₗ[ℂ] Q.R := Q.R.projectionOnto C hC
  let Vlin : (Fin d → ℂ) →ₗ[ℂ] (Fin D → ℂ) := Q.R.subtype.comp s
  let Wlin : (Fin D → ℂ) →ₗ[ℂ] (Fin d → ℂ) := Q.q.comp p
  let V : Matrix (Fin D) (Fin d) ℂ := matrixOf Vlin
  let W : Matrix (Fin d) (Fin D) ℂ := matrixOf' Wlin
  refine ⟨V, W, ?_, ?_⟩
  · apply Matrix.toLin'.injective
    change Matrix.toLin' (LinearMap.toMatrix' Wlin * LinearMap.toMatrix' Vlin) =
      Matrix.toLin' (1 : Matrix (Fin d) (Fin d) ℂ)
    rw [Matrix.toLin'_mul, Matrix.toLin'_toMatrix', Matrix.toLin'_toMatrix', Matrix.toLin'_one]
    apply LinearMap.ext
    intro x
    change Wlin (Vlin x) = x
    have hx := congrArg (fun f : (Fin d → ℂ) →ₗ[ℂ] (Fin d → ℂ) => f x) hs
    simpa [Wlin, Vlin, p] using hx
  · intro w
    apply Matrix.toLin'.injective
    change Matrix.toLin'
        ((LinearMap.toMatrix' Wlin * evalWord B w) * LinearMap.toMatrix' Vlin) =
      Matrix.toLin' (evalWord A w)
    rw [Matrix.toLin'_mul, Matrix.toLin'_mul, Matrix.toLin'_toMatrix',
      Matrix.toLin'_toMatrix']
    apply LinearMap.ext
    intro x
    change Wlin ((Matrix.toLin' (evalWord B w)) (Vlin x)) =
      Matrix.toLin' (evalWord A w) x
    have hmem : evalWord B w *ᵥ (Vlin x) ∈ Q.R := by
      simpa [Vlin, Matrix.toLin'_apply] using Q.evalWord_mem w (s x)
    calc
      Wlin ((Matrix.toLin' (evalWord B w)) (Vlin x))
          = Q.q ⟨evalWord B w *ᵥ (s x), hmem⟩ := by
              have hp : p (evalWord B w *ᵥ (s x : Fin D → ℂ)) =
                  ⟨evalWord B w *ᵥ (s x : Fin D → ℂ), hmem⟩ :=
                Submodule.projectionOnto_apply_of_mem_left hC hmem
              simp [Wlin, Vlin, p, Matrix.toLin'_apply, hp]
      _ = evalWord A w *ᵥ Q.q (s x) := Q.q_evalWord w (s x)
      _ = Matrix.toLin' (evalWord A w) x := by
              have hx := congrArg (fun f : (Fin d → ℂ) →ₗ[ℂ] (Fin d → ℂ) => f x) hs
              simpa [Matrix.toLin'_apply] using congrArg (fun y => evalWord A w *ᵥ y) hx

/-- An invariant subquotient gives the sharp finite word-compression certificate. -/
theorem hasWordCompressionUpTo_of_hasInvariantSubquotient
    {A : MPSTensor n d} {B : MPSTensor n D} :
    HasInvariantSubquotient A B →
      HasWordCompressionUpTo A B (D - d + 1) := by
  intro h
  rcases exists_allWordCompression_of_hasInvariantSubquotient (A := A) (B := B) h with
    ⟨V, W, hWV, hall⟩
  exact ⟨V, W, hWV, fun w _ _ => hall w⟩

/-- Sharp finite word compression is equivalent to invariant-subquotient occurrence. -/
theorem finiteWordCompression_iff_hasInvariantSubquotient
    {A : MPSTensor n d} {B : MPSTensor n D} (hD : d ≤ D) :
    HasWordCompressionUpTo A B (D - d + 1) ↔ HasInvariantSubquotient A B :=
  ⟨hasInvariantSubquotient_of_hasWordCompressionUpTo hD,
    hasWordCompressionUpTo_of_hasInvariantSubquotient⟩

end Kraus
