/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import Mathlib.RepresentationTheory.AlgebraRepresentation.Basic
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.LinearAlgebra.Basis.VectorSpace
import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.Analysis.Complex.Polynomial.Basic
import TNLean.Algebra.WordAlgebra
import TNLean.MPS.FundamentalTheorem.Reduction.WordModule

/-!
# Separating simple word-algebra modules

For the multi-block asymmetric compression theorem
(`Notes/OpenProblemsTN/problems/p5_asymmetric_fundamental_theorem.tex`, §7.4–7.5) one needs to
tell a simple module `Q` apart from a finite family of simple modules not isomorphic to it, by an
element of the positive ideal `F₊` that acts as the identity on `Q` and as zero on the family.
This is the finite-dimensional content of the Jacobson density theorem combined with Schur's
lemma, and it replaces the Artin–Wedderburn bookkeeping of Lemma 7.5 in the note.

## Main results

* `WordAlgebra.exists_smul_eq_of_isSimpleModule`: Burnside's theorem at module level: every
  `ℂ`-linear endomorphism of a finite-dimensional simple module is the action of some element.
* `WordAlgebra.exists_aug_eq_zero_smul_eq_self`: on a simple module with a nonzero generator
  action, some element of `F₊` acts as the identity.
* `WordAlgebra.exists_aug_eq_zero_smul_eq_self_smul_eq_zero`: two non-isomorphic simple modules
  are separated by an element of `F₊`.
* `MPSTensor.exists_aug_eq_zero_of_forall_isEmpty_linearEquiv`: separation from a finite family
  of tensor modules.
-/

namespace WordAlgebra

variable {d : ℕ}

/-- A vector reached from a nonzero vector: there is a `ℂ`-linear map sending `x` to `y`
whenever `x ≠ 0`. -/
lemma exists_linearMap_apply_eq {Q : Type*} [AddCommGroup Q] [Module ℂ Q] {x : Q} (hx : x ≠ 0)
    (y : Q) : ∃ g : Q →ₗ[ℂ] Q, g x = y := by
  have hinj : LinearMap.ker (LinearMap.toSpanSingleton ℂ Q x) = ⊥ :=
    LinearMap.ker_toSpanSingleton ℂ hx
  obtain ⟨ℓ, hℓ⟩ := LinearMap.exists_leftInverse_of_injective _ hinj
  refine ⟨ℓ.smulRight y, ?_⟩
  have : ℓ x = 1 := by
    have := LinearMap.congr_fun hℓ 1
    simpa using this
  simp [this]

section Burnside

variable (Q : Type*) [AddCommGroup Q] [Module ℂ Q] [Module (WordAlgebra d) Q]
  [IsScalarTower ℂ (WordAlgebra d) Q] [FiniteDimensional ℂ Q] [IsSimpleModule (WordAlgebra d) Q]

/-- Burnside's theorem at module level: every `ℂ`-linear endomorphism of a finite-dimensional
simple module over the word algebra is the action of some element (Schur's lemma over an
algebraically closed field and the Jacobson density theorem). -/
theorem exists_smul_eq_of_isSimpleModule (g : Q →ₗ[ℂ] Q) :
    ∃ a : WordAlgebra d, ∀ q : Q, a • q = g q := by
  set R := WordAlgebra d
  have hSchur : Function.Bijective (algebraMap ℂ (Module.End R Q)) :=
    IsSimpleModule.algebraMap_end_bijective_of_isAlgClosed (k := ℂ) (A := R) (V := Q)
  -- `Q` is finite over its commutant, which consists of scalars.
  have : Module.Finite (Module.End R Q) Q := by
    have : RingHomSurjective (algebraMap ℂ (Module.End R Q)) := ⟨hSchur.2⟩
    let f : Q →ₛₗ[algebraMap ℂ (Module.End R Q)] Q :=
      LinearMap.mk (toAddHom := AddMonoidHom.id Q) (map_smul' := by
        intro c v
        simp [Algebra.algebraMap_eq_smul_one])
    exact Module.Finite.of_surjective (f := f) fun v => ⟨v, rfl⟩
  have : SMulCommClass R (Module.End R Q) Q := ⟨fun r f v => by simp [f.map_smul r v]⟩
  have hJD : Function.Surjective (Module.toModuleEnd (Module.End R Q) Q) :=
    Module.Finite.toModuleEnd_moduleEnd_surjective (R := R) (M := Q)
  -- Regard `g` as `Module.End R Q`-linear using surjectivity of `algebraMap`.
  let g' : Module.End (Module.End R Q) Q :=
    { toFun := fun v => g v
      map_add' := fun v w => g.map_add v w
      map_smul' := by
        intro φ v
        obtain ⟨c, rfl⟩ := hSchur.2 φ
        simp [Algebra.algebraMap_eq_smul_one] }
  obtain ⟨a, ha⟩ := hJD g'
  refine ⟨a, fun q => ?_⟩
  have := LinearMap.congr_fun ha q
  simpa [Module.toModuleEnd_apply, g'] using this

/-- On a simple module with some generator acting nonzero, an element of the positive ideal acts
as the identity: the two-sided ideal generated by a nonzero endomorphism of a finite-dimensional
space is everything, and every endomorphism is realized by Burnside. -/
theorem exists_aug_eq_zero_smul_eq_self
    (h : ∃ (i : Fin d) (q : Q), (ofWord [i] : WordAlgebra d) • q ≠ 0) :
    ∃ u : WordAlgebra d, aug u = 0 ∧ ∀ q : Q, u • q = q := by
  obtain ⟨i, q₀, hq₀⟩ := h
  classical
  let b := Module.finBasis ℂ Q
  -- `Y j` sends `x_i • q₀` to the basis vector `b j`; `Z j` sends `q` to `coord j q • q₀`.
  choose Y hY using fun j => exists_linearMap_apply_eq hq₀ (b j)
  let Z : Fin (Module.finrank ℂ Q) → Q →ₗ[ℂ] Q := fun j => (b.coord j).smulRight q₀
  choose α hα using fun j => exists_smul_eq_of_isSimpleModule (d := d) Q (Y j)
  choose β hβ using fun j => exists_smul_eq_of_isSimpleModule (d := d) Q (Z j)
  refine ⟨∑ j, α j * ofWord [i] * β j, ?_, fun q => ?_⟩
  · simp [map_sum, aug_ofWord]
  · calc (∑ j, α j * ofWord [i] * β j) • q = ∑ j, Y j (ofWord [i] • Z j q) := by
          rw [Finset.sum_smul]
          refine Finset.sum_congr rfl fun j _ => ?_
          rw [mul_smul, mul_smul, hα, hβ]
      _ = ∑ j, b.repr q j • b j := by
          refine Finset.sum_congr rfl fun j _ => ?_
          simp [Z, smul_comm (ofWord [i] : WordAlgebra d), hY j]
      _ = q := b.sum_repr q

end Burnside

section Separation

variable (Q T : Type*) [AddCommGroup Q] [Module ℂ Q] [Module (WordAlgebra d) Q]
  [IsScalarTower ℂ (WordAlgebra d) Q] [FiniteDimensional ℂ Q] [IsSimpleModule (WordAlgebra d) Q]
  [AddCommGroup T] [Module ℂ T] [Module (WordAlgebra d) T]
  [IsScalarTower ℂ (WordAlgebra d) T] [FiniteDimensional ℂ T] [IsSimpleModule (WordAlgebra d) T]

/-- A product of two simple modules is semisimple. -/
instance isSemisimpleModule_prod : IsSemisimpleModule (WordAlgebra d) (Q × T) := by
  have h1 : IsSemisimpleModule (WordAlgebra d) (Submodule.fst (WordAlgebra d) Q T) :=
    IsSemisimpleModule.congr (Submodule.fstEquiv (WordAlgebra d) Q T)
  have h2 : IsSemisimpleModule (WordAlgebra d) (Submodule.snd (WordAlgebra d) Q T) :=
    IsSemisimpleModule.congr (Submodule.sndEquiv (WordAlgebra d) Q T)
  have h3 : IsSemisimpleModule (WordAlgebra d)
      ↥(Submodule.fst (WordAlgebra d) Q T ⊔ Submodule.snd (WordAlgebra d) Q T) :=
    IsSemisimpleModule.sup h1 h2
  rw [Submodule.fst_sup_snd] at h3
  exact IsSemisimpleModule.congr (Submodule.topEquiv).symm

omit [Module ℂ Q] [IsScalarTower ℂ (WordAlgebra d) Q] [FiniteDimensional ℂ Q] [Module ℂ T]
  [IsScalarTower ℂ (WordAlgebra d) T] [FiniteDimensional ℂ T] in
/-- Every endomorphism of `Q × T` preserves the first factor when `Q` and `T` are non-isomorphic
simple modules (Schur's lemma). -/
lemma fst_comp_inr_eq_zero (hne : IsEmpty (Q ≃ₗ[WordAlgebra d] T))
    (φ : Module.End (WordAlgebra d) (Q × T)) :
    (LinearMap.fst (WordAlgebra d) Q T).comp (φ.comp (LinearMap.inr (WordAlgebra d) Q T)) = 0 := by
  rcases LinearMap.bijective_or_eq_zero
      ((LinearMap.fst (WordAlgebra d) Q T).comp (φ.comp (LinearMap.inr (WordAlgebra d) Q T)))
    with hbij | hzero
  · exact (hne.false (LinearEquiv.ofBijective _ hbij).symm).elim
  · exact hzero

omit [Module ℂ Q] [IsScalarTower ℂ (WordAlgebra d) Q] [FiniteDimensional ℂ Q] [Module ℂ T]
  [IsScalarTower ℂ (WordAlgebra d) T] [FiniteDimensional ℂ T] in
lemma snd_comp_inl_eq_zero (hne : IsEmpty (Q ≃ₗ[WordAlgebra d] T))
    (φ : Module.End (WordAlgebra d) (Q × T)) :
    (LinearMap.snd (WordAlgebra d) Q T).comp (φ.comp (LinearMap.inl (WordAlgebra d) Q T)) = 0 := by
  rcases LinearMap.bijective_or_eq_zero
      ((LinearMap.snd (WordAlgebra d) Q T).comp (φ.comp (LinearMap.inl (WordAlgebra d) Q T)))
    with hbij | hzero
  · exact (hne.false (LinearEquiv.ofBijective _ hbij)).elim
  · exact hzero

/-- Two non-isomorphic simple modules are separated by an element of the positive ideal acting as
the identity on the first and as zero on the second (Jacobson density on `Q × T`). -/
theorem exists_aug_eq_zero_smul_eq_self_smul_eq_zero
    (hQ : ∃ (i : Fin d) (q : Q), (ofWord [i] : WordAlgebra d) • q ≠ 0)
    (hne : IsEmpty (Q ≃ₗ[WordAlgebra d] T)) :
    ∃ p : WordAlgebra d, aug p = 0 ∧ (∀ q : Q, p • q = q) ∧ ∀ t : T, p • t = 0 := by
  -- `(Q × T)` is finite over its commutant.
  have : IsScalarTower ℂ (Module.End (WordAlgebra d) (Q × T)) (Q × T) :=
    ⟨fun c φ n => by change (c • φ) n = c • φ n; exact LinearMap.smul_apply c φ n⟩
  have : Module.Finite (Module.End (WordAlgebra d) (Q × T)) (Q × T) :=
    Module.Finite.of_restrictScalars_finite ℂ (Module.End (WordAlgebra d) (Q × T)) (Q × T)
  have : SMulCommClass (WordAlgebra d) (Module.End (WordAlgebra d) (Q × T)) (Q × T) :=
    ⟨fun r f v => by change r • f v = f (r • v); exact (f.map_smul r v).symm⟩
  have hJD :
      Function.Surjective (Module.toModuleEnd (Module.End (WordAlgebra d) (Q × T)) (Q × T)) :=
    Module.Finite.toModuleEnd_moduleEnd_surjective (R := WordAlgebra d) (M := Q × T)
  -- The projection onto the first factor commutes with every endomorphism.
  let g : Module.End (Module.End (WordAlgebra d) (Q × T)) (Q × T) :=
    { toFun := fun n => (n.1, 0)
      map_add' := fun n m => by rw [Prod.fst_add, Prod.mk_add_mk, add_zero]
      map_smul' := by
        intro φ n
        have h1 := LinearMap.congr_fun (fst_comp_inr_eq_zero Q T hne φ) n.2
        have h2 := LinearMap.congr_fun (snd_comp_inl_eq_zero Q T hne φ) n.1
        simp only [LinearMap.comp_apply, LinearMap.fst_apply, LinearMap.inr_apply,
          LinearMap.snd_apply, LinearMap.inl_apply, LinearMap.zero_apply] at h1 h2
        change ((φ n).1, 0) = φ (n.1, 0)
        have hn : (n.1, 0) + (0, n.2) = n := by rw [Prod.mk_add_mk, add_zero, zero_add]
        have hφn : φ n = φ (n.1, 0) + φ (0, n.2) := by rw [← map_add, hn]
        refine Prod.ext ?_ ?_
        · rw [hφn, Prod.fst_add, h1, add_zero]
        · exact h2.symm }
  obtain ⟨a, ha⟩ := hJD g
  obtain ⟨u, hu, hu'⟩ := exists_aug_eq_zero_smul_eq_self Q hQ
  refine ⟨a * u, aug_mul_left hu a, fun q => ?_, fun t => ?_⟩
  · have h : a • q = q := by
      simpa [Module.toModuleEnd_apply, g, Prod.smul_fst] using
        congrArg Prod.fst (LinearMap.congr_fun ha (q, 0))
    rw [mul_smul, hu', h]
  · have h : a • (u • t) = 0 := by
      simpa [Module.toModuleEnd_apply, g, Prod.smul_snd] using
        congrArg Prod.snd (LinearMap.congr_fun ha (0, u • t))
    rw [mul_smul, h]

end Separation

end WordAlgebra

namespace MPSTensor

open WordAlgebra

variable {d : ℕ} {ι : Type*}

/-- Separation of a simple module from a finite family of non-isomorphic tensor modules: an
element of the positive ideal acting as the identity on `Q` and as zero on every member. -/
theorem exists_aug_eq_zero_of_forall_isEmpty_linearEquiv
    (Q : Type*) [AddCommGroup Q] [Module ℂ Q] [Module (WordAlgebra d) Q]
    [IsScalarTower ℂ (WordAlgebra d) Q] [FiniteDimensional ℂ Q]
    [IsSimpleModule (WordAlgebra d) Q]
    (hQ : ∃ (i : Fin d) (q : Q), (ofWord [i] : WordAlgebra d) • q ≠ 0)
    (S : Finset ι) {D : ι → ℕ} (C : ∀ s, MPSTensor d (D s))
    (hC : ∀ s ∈ S, IsSimpleModule (WordAlgebra d) (C s).WordModule)
    (hne : ∀ s ∈ S, IsEmpty (Q ≃ₗ[WordAlgebra d] (C s).WordModule)) :
    ∃ p : WordAlgebra d, aug p = 0 ∧ (∀ q : Q, p • q = q) ∧
      ∀ s ∈ S, ∀ v : (C s).WordModule, p • v = 0 := by
  classical
  induction S using Finset.induction_on with
  | empty =>
    obtain ⟨u, hu, hu'⟩ := exists_aug_eq_zero_smul_eq_self Q hQ
    exact ⟨u, hu, hu', fun s hs => (Finset.notMem_empty s hs).elim⟩
  | insert t S ht ih =>
    obtain ⟨p₁, hp₁, hp₁Q, hp₁S⟩ := ih (fun s hs => hC s (Finset.mem_insert_of_mem hs))
      (fun s hs => hne s (Finset.mem_insert_of_mem hs))
    have := hC t (Finset.mem_insert_self t S)
    obtain ⟨p₂, hp₂, hp₂Q, hp₂T⟩ :=
      exists_aug_eq_zero_smul_eq_self_smul_eq_zero Q (C t).WordModule hQ
        (hne t (Finset.mem_insert_self t S))
    refine ⟨p₂ * p₁, aug_mul_right hp₂ p₁, fun q => by rw [mul_smul, hp₁Q, hp₂Q], ?_⟩
    intro s hs v
    rcases Finset.mem_insert.1 hs with rfl | hs
    · rw [mul_smul, hp₂T]
    · rw [mul_smul, hp₁S s hs, smul_zero]

end MPSTensor
