/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import TNLean.Algebra.StarClosedSemisimple
import TNLean.MPS.FundamentalTheorem.Reduction.WordModule

/-!
# Star closure of the virtual algebra makes the word module semisimple

The splitting criterion of the asymmetric compression theorem
(`Notes/OpenProblemsTN/strategies/final_resolution/p5_local_zipper_hypotheses.tex`): a fixed
occurrence of a block splits off the compression exactly when the corresponding step of the
invariant flag is a direct summand, and semisimplicity of the source module is a sufficient
condition. This file supplies the sufficient condition used for unitary and hermitian matrix
product operator symmetries: if the conjugate transpose of every one-site matrix of the tensor
lies in the algebra generated by the one-site matrices, the word module is semisimple.

## Main results

* `WordAlgebra.smul_mem_of_forall_ofWord_smul_mem`: a complex subspace invariant under every
  one-letter word is invariant under the whole word algebra.
* `WordAlgebra.submoduleOfLetterInvariant`: such a subspace as a word-algebra submodule.
* `MPSTensor.isSemisimpleModule_wordModule_of_conjTranspose_mem_adjoin`: semisimplicity of the
  word module of a tensor with star-closed virtual algebra.
-/

open scoped Matrix

namespace WordAlgebra

variable {d : ℕ} {M : Type*} [AddCommGroup M] [Module ℂ M] [Module (WordAlgebra d) M]
  [IsScalarTower ℂ (WordAlgebra d) M]

/-- A complex subspace invariant under the action of every one-letter word is invariant under the
action of the whole word algebra: the words span the algebra, and a word acts as the composite of
its letters. -/
theorem smul_mem_of_forall_ofWord_smul_mem {N : Submodule ℂ M}
    (hN : ∀ (i : Fin d), ∀ x ∈ N, (ofWord [i] : WordAlgebra d) • x ∈ N) (p : WordAlgebra d)
    {x : M} (hx : x ∈ N) : p • x ∈ N := by
  have hword : ∀ w : List (Fin d), ∀ y ∈ N, (ofWord w : WordAlgebra d) • y ∈ N := by
    intro w
    induction w with
    | nil => intro y hy; rwa [ofWord_nil, one_smul]
    | cons i w ih => intro y hy; rw [ofWord_cons, mul_smul]; exact hN i _ (ih y hy)
  induction p using MonoidAlgebra.induction_on with
  | of g =>
    change (ofWord (FreeMonoid.toList g) : WordAlgebra d) • x ∈ N
    exact hword _ x hx
  | add f g hf hg => rw [add_smul]; exact N.add_mem hf hg
  | smul r f hf => rw [smul_assoc]; exact N.smul_mem r hf

/-- A complex subspace invariant under every one-letter word, read as a word-algebra
submodule. -/
def submoduleOfLetterInvariant (N : Submodule ℂ M)
    (hN : ∀ (i : Fin d), ∀ x ∈ N, (ofWord [i] : WordAlgebra d) • x ∈ N) :
    Submodule (WordAlgebra d) M where
  carrier := N
  add_mem' := N.add_mem
  zero_mem' := N.zero_mem
  smul_mem' p _ hx := smul_mem_of_forall_ofWord_smul_mem hN p hx

@[simp] theorem mem_submoduleOfLetterInvariant {N : Submodule ℂ M}
    {hN : ∀ (i : Fin d), ∀ x ∈ N, (ofWord [i] : WordAlgebra d) • x ∈ N} {x : M} :
    x ∈ submoduleOfLetterInvariant N hN ↔ x ∈ N := Iff.rfl

end WordAlgebra

namespace MPSTensor

open WordAlgebra

variable {d D : ℕ}

/-- The action of a one-letter word on the word module is multiplication by the one-site
matrix. -/
theorem asModuleEquiv_letter_smul (B : MPSTensor d D) (i : Fin d) (v : B.WordModule) :
    B.wordRep.asModuleEquiv ((ofWord [i] : WordAlgebra d) • v) =
      B i *ᵥ B.wordRep.asModuleEquiv v := by
  rw [asModuleEquiv_ofWord_smul]
  simp [Kraus.evalWord]

/-- **Semisimplicity from star closure of the virtual algebra**. If the conjugate transpose of
every one-site matrix of a tensor lies in the algebra generated by the one-site matrices, then
the word module of the tensor is semisimple: every invariant subspace has an invariant
complement, namely its orthogonal complement. -/
theorem isSemisimpleModule_wordModule_of_conjTranspose_mem_adjoin (B : MPSTensor d D)
    (hstar : ∀ i, (B i)ᴴ ∈ Algebra.adjoin ℂ (Set.range B)) :
    IsSemisimpleModule (WordAlgebra d) B.WordModule := by
  rw [isSemisimpleModule_iff]
  refine ⟨fun K => ?_⟩
  set e : B.WordModule ≃ₗ[ℂ] (Fin D → ℂ) := B.wordRep.asModuleEquiv with he
  set W : Submodule ℂ (Fin D → ℂ) := (K.restrictScalars ℂ).map (e : _ →ₗ[ℂ] _) with hWdef
  have hmemW : ∀ x : B.WordModule, x ∈ K → e x ∈ W := fun x hx => ⟨x, hx, rfl⟩
  have hW : ∀ i, ∀ v ∈ W, B i *ᵥ v ∈ W := by
    rintro i _ ⟨x, hx, rfl⟩
    exact ⟨(ofWord [i] : WordAlgebra d) • x, K.smul_mem _ hx, B.asModuleEquiv_letter_smul i x⟩
  obtain ⟨W', hcompl, hW'⟩ := Matrix.exists_isCompl_forall_mulVec_mem B hstar W hW
  set N : Submodule ℂ B.WordModule := W'.comap (e : _ →ₗ[ℂ] _) with hNdef
  have hN : ∀ (i : Fin d), ∀ x ∈ N, (ofWord [i] : WordAlgebra d) • x ∈ N := by
    intro i x hx
    simp only [hNdef, Submodule.mem_comap, LinearEquiv.coe_coe] at hx ⊢
    rw [B.asModuleEquiv_letter_smul i x]
    exact hW' i _ hx
  refine ⟨submoduleOfLetterInvariant N hN, ?_, ?_⟩
  · refine Submodule.disjoint_def.2 fun x hx hx' => ?_
    have h0 : e x = 0 :=
      Submodule.disjoint_def.1 hcompl.disjoint _ (hmemW x hx) hx'
    simpa using congrArg e.symm h0
  · rw [codisjoint_iff, eq_top_iff]
    intro x _
    have hxmem : e x ∈ W ⊔ W' := by rw [codisjoint_iff.1 hcompl.codisjoint]; trivial
    obtain ⟨a, ha, b, hb, hab⟩ := Submodule.mem_sup.1 hxmem
    obtain ⟨y, hy, rfl⟩ := ha
    refine Submodule.mem_sup.2 ⟨y, hy, x - y, ?_, by abel⟩
    change e (x - y) ∈ W'
    rw [map_sub, ← hab]
    simpa using hb

end MPSTensor
