/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import TNLean.Algebra.StarClosedSemisimple
import TNLean.MPS.FundamentalTheorem.Reduction.WordModule

/-!
# Star closure of the virtual algebra makes the word module semisimple

The splitting criterion of the asymmetric compression theorem
(`Notes/OpenProblemsTN/strategies/final_resolution/p5_local_zipper_hypotheses.tex`): a fixed
occurrence of a block splits off the compression exactly when the corresponding step of the
invariant flag is a direct summand, and semisimplicity of the source module is a sufficient
condition. This file supplies the sufficient condition used for unitary and hermitian matrix
product operator symmetries: if the conjugate transpose of every one-site matrix of the tensor
lies in the algebra generated by the one-site matrices, the word module is semisimple.

## Main results

* `WordAlgebra.smul_mem_of_forall_ofWord_smul_mem`: a complex subspace invariant under every
  one-letter word is invariant under the whole word algebra.
* `WordAlgebra.submoduleOfLetterInvariant`: such a subspace as a word-algebra submodule.
* `MPSTensor.isSemisimpleModule_wordModule_of_conjTranspose_mem_adjoin`: semisimplicity of the
  word module of a tensor with star-closed virtual algebra.
-/

open scoped Matrix

namespace WordAlgebra

variable {d : ℕ} {M : Type*} [AddCommGroup M] [Module ℂ M] [Module (WordAlgebra d) M]
  [IsScalarTower ℂ (WordAlgebra d) M]

/-- A complex subspace invariant under the action of every one-letter word is invariant under the
action of the whole word algebra: the words span the algebra, and a word acts as the composite of
its letters. -/
theorem smul_mem_of_forall_ofWord_smul_mem {N : Submodule ℂ M}
    (hN : ∀ (i : Fin d), ∀ x ∈ N, (ofWord [i] : WordAlgebra d) • x ∈ N) (p : WordAlgebra d)
    {x : M} (hx : x ∈ N) : p • x ∈ N := by
  have hword : ∀ w : List (Fin d), ∀ y ∈ N, (ofWord w : WordAlgebra d) • y ∈ N := by
    intro w
    induction w with
    | nil => intro y hy; rwa [ofWord_nil, one_smul]
    | cons i w ih => intro y hy; rw [ofWord_cons, mul_smul]; exact hN i _ (ih y hy)
  induction p using MonoidAlgebra.induction_on with
  | of g =>
    change (ofWord (FreeMonoid.toList g) : WordAlgebra d) • x ∈ N
    exact hword _ x hx
  | add f g hf hg => rw [add_smul]; exact N.add_mem hf hg
  | smul r f hf => rw [smul_assoc]; exact N.smul_mem r hf

/-- A complex subspace invariant under every one-letter word, read as a word-algebra
submodule. -/
def submoduleOfLetterInvariant (N : Submodule ℂ M)
    (hN : ∀ (i : Fin d), ∀ x ∈ N, (ofWord [i] : WordAlgebra d) • x ∈ N) :
    Submodule (WordAlgebra d) M where
  carrier := N
  add_mem' := N.add_mem
  zero_mem' := N.zero_mem
  smul_mem' p _ hx := smul_mem_of_forall_ofWord_smul_mem hN p hx

@[simp] theorem mem_submoduleOfLetterInvariant {N : Submodule ℂ M}
    {hN : ∀ (i : Fin d), ∀ x ∈ N, (ofWord [i] : WordAlgebra d) • x ∈ N} {x : M} :
    x ∈ submoduleOfLetterInvariant N hN ↔ x ∈ N := Iff.rfl

end WordAlgebra

namespace MPSTensor

open WordAlgebra

variable {d D : ℕ}

/-- The action of a one-letter word on the word module is multiplication by the one-site
matrix. -/
theorem asModuleEquiv_letter_smul (B : MPSTensor d D) (i : Fin d) (v : B.WordModule) :
    B.wordRep.asModuleEquiv ((ofWord [i] : WordAlgebra d) • v) =
      B i *ᵥ B.wordRep.asModuleEquiv v := by
  rw [asModuleEquiv_ofWord_smul]
  simp [Kraus.evalWord]

/-- **Semisimplicity from star closure of the virtual algebra**. If the conjugate transpose of
every one-site matrix of a tensor lies in the algebra generated by the one-site matrices, then
the word module of the tensor is semisimple: every invariant subspace has an invariant
complement, namely its orthogonal complement. -/
theorem isSemisimpleModule_wordModule_of_conjTranspose_mem_adjoin (B : MPSTensor d D)
    (hstar : ∀ i, (B i)ᴴ ∈ Algebra.adjoin ℂ (Set.range B)) :
    IsSemisimpleModule (WordAlgebra d) B.WordModule := by
  -- The algebra generated by the one-site matrices is a star-subalgebra.
  have hstarA : ∀ X ∈ Algebra.adjoin ℂ (Set.range B), star X ∈ Algebra.adjoin ℂ (Set.range B) := by
    intro X hX
    refine Algebra.adjoin_le (s := star (Set.range B)) (S := Algebra.adjoin ℂ (Set.range B))
      (fun Y hY => ?_) ?_
    · obtain ⟨i, hi⟩ := Set.mem_star.1 hY
      rw [← star_star Y, ← hi]
      exact hstar i
    · rw [← Subalgebra.star_adjoin_comm, Subalgebra.star_mem_star_iff]
      exact hX
  let S : StarSubalgebra ℂ (Matrix (Fin D) (Fin D) ℂ) :=
    { Algebra.adjoin ℂ (Set.range B) with star_mem' := hstarA _ }
  have := S.isSemisimpleModule
  rw [isSemisimpleModule_iff]
  refine ⟨fun K => ?_⟩
  set e : B.WordModule ≃ₗ[ℂ] (Fin D → ℂ) := B.wordRep.asModuleEquiv with he
  set W : Submodule ℂ (Fin D → ℂ) := (K.restrictScalars ℂ).map (e : _ →ₗ[ℂ] _) with hWdef
  -- The image of `K` is invariant under the generated algebra.
  have hWinv : ∀ X ∈ Algebra.adjoin ℂ (Set.range B), ∀ v ∈ W, X *ᵥ v ∈ W := by
    intro X hX
    induction hX using Algebra.adjoin_induction with
    | mem X hX =>
      obtain ⟨i, rfl⟩ := hX
      rintro _ ⟨x, hx, rfl⟩
      exact ⟨(ofWord [i] : WordAlgebra d) • x, K.smul_mem _ hx, B.asModuleEquiv_letter_smul i x⟩
    | algebraMap c =>
      intro v hv
      rw [Algebra.algebraMap_eq_smul_one, Matrix.smul_mulVec, Matrix.one_mulVec]
      exact W.smul_mem c hv
    | add X Y _ _ hX hY =>
      intro v hv
      rw [Matrix.add_mulVec]
      exact W.add_mem (hX v hv) (hY v hv)
    | mul X Y _ _ hX hY =>
      intro v hv
      rw [← Matrix.mulVec_mulVec]
      exact hX _ (hY v hv)
  let WS : Submodule S.toSubalgebra (Fin D → ℂ) :=
    { W with smul_mem' := fun X v hv => hWinv X.1 X.2 v hv }
  obtain ⟨WS', hcompl⟩ := exists_isCompl WS
  set N : Submodule ℂ B.WordModule := (WS'.restrictScalars ℂ).comap (e : _ →ₗ[ℂ] _) with hNdef
  have hN : ∀ (i : Fin d), ∀ x ∈ N, (ofWord [i] : WordAlgebra d) • x ∈ N := by
    intro i x hx
    simp only [hNdef, Submodule.mem_comap, LinearEquiv.coe_coe] at hx ⊢
    rw [B.asModuleEquiv_letter_smul i x]
    exact WS'.smul_mem (⟨B i, Algebra.subset_adjoin ⟨i, rfl⟩⟩ : S.toSubalgebra) hx
  refine ⟨submoduleOfLetterInvariant N hN, ?_⟩
  rw [← Submodule.isCompl_restrictScalars_iff ℂ] at hcompl ⊢
  have hK : K.restrictScalars ℂ = W.comap (e : _ →ₗ[ℂ] _) :=
    (Submodule.comap_map_eq_of_injective e.injective _).symm
  rw [hK]
  exact (Submodule.orderIsoMapComap e).symm.isCompl hcompl

end MPSTensor
