#!/usr/bin/env bash
# Generate sanitized auxiliary files for external references from paper-gap notes.
#
# Usage:
#   ./scripts/generate_paper_aux.sh PAPER_DIR_OR_ID
# Example:
#   ./scripts/generate_paper_aux.sh 1606.00608
#
# Generated files are written under build/paper-aux/, mirroring Papers/.  Each
# *-tnlean.aux file contains only labels that occur exactly once in the source
# document, so xr cannot import an ambiguous duplicate label.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PAPERS_DIR="$ROOT_DIR/Papers"
BUILD_DIR="$ROOT_DIR/build/paper-aux"

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 PAPER_DIR_OR_ID" >&2
  exit 2
fi

if [ ! -d "$PAPERS_DIR" ]; then
  echo "::error::Papers directory $PAPERS_DIR not found"
  exit 1
fi

target="$1"
if [ -d "$target" ]; then
  target_dir="$(cd "$target" && pwd)"
elif [ -d "$PAPERS_DIR/$target" ]; then
  target_dir="$(cd "$PAPERS_DIR/$target" && pwd)"
else
  echo "::error::Paper target not found: $target"
  exit 1
fi

case "$target_dir/" in
  "$PAPERS_DIR"/*/) ;;
  *)
    echo "::error::Paper target must lie under $PAPERS_DIR: $target_dir"
    exit 1
    ;;
esac

relative_dir="${target_dir#"$PAPERS_DIR"/}"
output_dir="$BUILD_DIR/$relative_dir"
mkdir -p "$output_dir"

tex_files=()
while IFS= read -r -d '' file; do
  if grep -q '\\documentclass' "$file" 2>/dev/null; then
    tex_files+=("$(basename "$file")")
  fi
done < <(find "$target_dir" -maxdepth 1 -name '*.tex' -print0)

if [ "${#tex_files[@]}" -eq 0 ]; then
  echo "::error::No standalone LaTeX source found in $target_dir"
  exit 1
fi

echo "==> Generating paper source labels from $target_dir"
for tex in "${tex_files[@]}"; do
  base="${tex%.tex}"
  raw_aux="$output_dir/$base.aux"
  sanitized_aux="$output_dir/$base-tnlean.aux"
  echo "  -> Compiling $tex"
  if command -v latexmk >/dev/null 2>&1; then
    (
      cd "$target_dir"
      latexmk -pdf -interaction=nonstopmode -halt-on-error \
        -outdir="$output_dir" "$tex"
    )
  elif command -v pdflatex >/dev/null 2>&1; then
    (
      cd "$target_dir"
      pdflatex -interaction=nonstopmode -halt-on-error \
        -output-directory="$output_dir" "$tex"
      pdflatex -interaction=nonstopmode -halt-on-error \
        -output-directory="$output_dir" "$tex"
    )
  else
    echo "::error::Neither latexmk nor pdflatex is available"
    exit 1
  fi

  python3 - "$raw_aux" "$sanitized_aux" <<'PY'
from collections import Counter
from pathlib import Path
import re
import sys

source = Path(sys.argv[1])
target = Path(sys.argv[2])
label_re = re.compile(r"^\\newlabel\{([^}]*)\}")
records: list[tuple[str, str]] = []
for line in source.read_text().splitlines(keepends=True):
    match = label_re.match(line)
    if match:
        records.append((match.group(1), line))

if not records:
    raise SystemExit(f"no labels found in {source}")

counts = Counter(label for label, _ in records)
unique_records = [line for label, line in records if counts[label] == 1]
duplicates = sorted(label for label, count in counts.items() if count > 1)
target.write_text(
    "% Generated by scripts/generate_paper_aux.sh; do not edit.\n"
    "\\relax\n"
    + "".join(unique_records)
)
print(
    f"     wrote {target}: {len(unique_records)} unique labels; "
    f"excluded {len(duplicates)} duplicated names"
)
PY
done

echo "==> Paper source label generation complete."
