/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.Periodic.Overlap.Dichotomy

/-!
# Independence of the non-zero members of a basis of periodic vectors

The consequence of the periodic overlap dichotomy recorded in
arXiv:1708.00029, lines 604--608 asserts that beyond some chain length the
*non-zero* members of the family of matrix-product vectors generated by a basis
of periodic tensors are linearly independent. A member is non-zero exactly at
those chain lengths that its period divides, so the assertion is about the
subfamily indexed by the blocks whose period divides the length, and it holds at
every sufficiently large length rather than only at common multiples of all the
periods.

## Main declarations

* `MPSTensor.periodicBasis_nonzero_subfamily_eventuallyLinearlyIndependent`

## References

* De las Cuevas, Cirac, Schuch, Perez-Garcia,
  *Irreducible forms of Matrix Product States: Theory and Applications*,
  arXiv:1708.00029, proposition `equal-or-orthogonal-generalized`,
  lines 604--608, and its use in theorem `thm:bdequal`, lines 677--679.
-/

open scoped BigOperators

namespace MPSTensor

variable {d : ℕ}

/-- **Independence of the non-zero members of a basis of periodic vectors.**

For a pairwise non-repeated family of periodic tensors there is a chain length
beyond which, at every single length `N`, the matrix-product vectors of those
members whose period divides `N` are linearly independent.

This is the form of the independence consequence of proposition
`equal-or-orthogonal-generalized` that the proof of theorem `thm:bdequal` uses:
there the coefficient comparison is made at each large `N` separately, and only
the members with `m_j ∣ N` survive, the remaining ones generating the zero
vector.

The proof runs the common-multiple statement
`periodicFamily_eventuallyLinearlyIndependent_of_cross_overlap_tendsto_zero`
once for each of the finitely many subfamilies, at the least common multiple of
the periods occurring in that subfamily, and then takes the largest of the
finitely many thresholds obtained, scaled by the least common multiple of all
the periods. At a length `N` past that threshold the subfamily of members whose
period divides `N` has its own least common multiple dividing `N`, and the
quotient is past that subfamily's own threshold.

Source: arXiv:1708.00029, proposition `equal-or-orthogonal-generalized`,
lines 604--608; used at lines 677--679. -/
theorem periodicBasis_nonzero_subfamily_eventuallyLinearlyIndependent
    {g : ℕ} {dim : Fin g → ℕ}
    (A : (j : Fin g) → MPSTensor d (dim j))
    (period : Fin g → ℕ)
    (hPer : ∀ j, IsPeriodic (period j) (A j))
    (hNonrep : ∀ i j, i ≠ j →
      ∀ (hdim : dim i = dim j),
        ¬ RepeatedBlocks (cast (congr_arg (MPSTensor d) hdim) (A i)) (A j)) :
    ∃ N₀ : ℕ, ∀ N ≥ N₀,
      LinearIndependent ℂ
        (fun j : {j : Fin g // period j ∣ N} => mpvState (d := d) (A ↑j) N) := by
  classical
  -- Positive bond dimensions, needed as instances by the overlap dichotomy.
  have : ∀ j, NeZero (dim j) := fun j => ⟨(hPer j).bondDim_ne_zero⟩
  -- Every period is positive, so every least common multiple of periods is.
  have hlcmPos : ∀ S : Finset (Fin g), 0 < S.lcm period := by
    intro S
    refine Nat.pos_of_ne_zero fun h0 => ?_
    obtain ⟨x, _, hx⟩ := Finset.lcm_eq_zero_iff.mp h0
    exact (hPer x).period_pos.ne' hx
  -- One threshold per subfamily, from the common-multiple statement.
  have key : ∀ S : Finset (Fin g), ∃ M : ℕ, ∀ n ≥ M,
      LinearIndependent ℂ
        (fun k : {j : Fin g // j ∈ S} =>
          mpvState (d := d) (A ↑k) (S.lcm period * n)) := by
    intro S
    have : NeZero (S.lcm period) := ⟨(hlcmPos S).ne'⟩
    refine periodicFamily_eventuallyLinearlyIndependent_of_cross_overlap_tendsto_zero
      (fun k : {j : Fin g // j ∈ S} => A ↑k) (fun k => period ↑k)
      (fun k => hPer ↑k) (S.lcm period) (fun k => Finset.dvd_lcm k.2) ?_
    intro i j hij
    have hij' : (i : Fin g) ≠ (j : Fin g) := fun h => hij (Subtype.ext h)
    rcases periodicOverlapDichotomy (A ↑i) (A ↑j) (hPer ↑i) (hPer ↑j) with
      hdecay | ⟨hdim, hrep⟩
    · exact hdecay
    · exact absurd hrep (hNonrep ↑i ↑j hij' hdim)
  choose M hM using key
  have hLPos : 0 < (Finset.univ : Finset (Fin g)).lcm period := hlcmPos _
  refine ⟨(Finset.univ : Finset (Finset (Fin g))).sup
    (fun S => (Finset.univ : Finset (Fin g)).lcm period * M S), fun N hN => ?_⟩
  set S : Finset (Fin g) := {j | period j ∣ N} with hSdef
  have hmem : ∀ x : Fin g, x ∈ S ↔ period x ∣ N := by
    intro x; simp [hSdef]
  obtain ⟨n, hn⟩ : S.lcm period ∣ N := Finset.lcm_dvd fun b hb => (hmem b).mp hb
  have hple : S.lcm period ≤ (Finset.univ : Finset (Fin g)).lcm period :=
    Nat.le_of_dvd hLPos (Finset.lcm_mono (Finset.subset_univ S))
  have hMS : M S ≤ n := by
    have h1 : (Finset.univ : Finset (Fin g)).lcm period * M S ≤ N :=
      le_trans (Finset.le_sup (f := fun S : Finset (Fin g) =>
        (Finset.univ : Finset (Fin g)).lcm period * M S) (Finset.mem_univ S)) hN
    rw [hn] at h1
    exact Nat.le_of_mul_le_mul_left
      (le_trans h1 (Nat.mul_le_mul_right n hple)) hLPos
  have hLI := hM S n hMS
  rw [← hn] at hLI
  exact hLI.comp (Equiv.subtypeEquivRight fun x => (hmem x).symm)
    (Equiv.subtypeEquivRight fun x => (hmem x).symm).injective

end MPSTensor
