import TNLean.PEPS.AreaLaw.NestedCylinderOrthogonalization

set_option linter.hashCommand false

#print axioms TNLean.PEPS.dependentRegionCylinder
#print axioms TNLean.PEPS.mem_dependentRegionCylinder
#print axioms TNLean.PEPS.range_dependentRegionOperatorLift
#print axioms TNLean.PEPS.coordinateRangeProjector_dependentRegionCylinder
#print axioms TNLean.PEPS.dependentRegionCylinder_bot
#print axioms TNLean.PEPS.dependentRegionCylinder_sup
#print axioms TNLean.PEPS.dependentRegionCylinder_iSup
#print axioms TNLean.PEPS.dependentRegionCylinder_subregion
#print axioms TNLean.PEPS.dependentRegionCylinder_map
#print axioms TNLean.PEPS.nestedCylinderEarlierInside
#print axioms TNLean.PEPS.nestedCylinderInnovation
#print axioms TNLean.PEPS.dependentRegionCylinder_nestedCylinderEarlierInside
#print axioms TNLean.PEPS.dependentRegionCylinder_nestedCylinderInnovation
#print axioms TNLean.PEPS.finrank_nestedCylinderInnovation_le
#print axioms TNLean.PEPS.nestedCylinderInnovation_sup
#print axioms TNLean.PEPS.nestedCylinderInnovation_orthogonalEarlier
#print axioms TNLean.PEPS.nestedCylinderInnovation_prefix_span
#print axioms TNLean.PEPS.nestedCylinderInnovation_span
#print axioms TNLean.PEPS.nestedCylinderInnovation_pairwise_orthogonal
#print axioms TNLean.PEPS.nestedCylinderInnovation_projector_sum
#print axioms TNLean.PEPS.sum_finrank_nestedCylinderInnovation_le
#print axioms TNLean.PEPS.sum_int_finrank_nestedCylinderInnovation_le
#print axioms TNLean.PEPS.nestedCylinder_projector_supported
#print axioms TNLean.PEPS.nestedCylinderInnovation_eq_bot_of_le
