import TNLean.PEPS.Approximation.DistributedConstruction
#print axioms TNLean.PEPS.PairEffect.DistributedConstruction
#print axioms TNLean.PEPS.PairEffect.DistributedConstruction.input
#print axioms TNLean.PEPS.PairEffect.DistributedConstruction.physicalDensity
#print axioms TNLean.PEPS.PairEffect.DistributedConstruction.physicalDensity_posSemidef
#print axioms TNLean.PEPS.PairEffect.DistributedConstruction.trace_physicalDensity_le_one
