/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.
-- Import architecture: docs/import_structure.md.
-- Generated aggregator module: TNLean.PEPS.Approximation

import TNLean.PEPS.Approximation.ActualSourceGateDensity
import TNLean.PEPS.Approximation.AffectedOwners
import TNLean.PEPS.Approximation.CommonPairSources
import TNLean.PEPS.Approximation.CommonPartyMaps
import TNLean.PEPS.Approximation.CommonSourceGate
import TNLean.PEPS.Approximation.CommonSourcePreparation
import TNLean.PEPS.Approximation.CompletePartyMaps
import TNLean.PEPS.Approximation.DistributedSourceComposition
import TNLean.PEPS.Approximation.FinitePairSources
import TNLean.PEPS.Approximation.FiniteSourceGate
import TNLean.PEPS.Approximation.FiniteSourcePreparation
import TNLean.PEPS.Approximation.GroupedBlockMap
import TNLean.PEPS.Approximation.LayoutOwnerMap
import TNLean.PEPS.Approximation.LocalPairSource
import TNLean.PEPS.Approximation.PairEffectElimination
import TNLean.PEPS.Approximation.PairEffectSourcePreparation
import TNLean.PEPS.Approximation.PairSourceCompletion
import TNLean.PEPS.Approximation.PairSourceExpansion
import TNLean.PEPS.Approximation.PairSourceGrouping
import TNLean.PEPS.Approximation.PairSourceOrdering
import TNLean.PEPS.Approximation.PartialSourceDensity
import TNLean.PEPS.Approximation.PartialSourceEvaluation
import TNLean.PEPS.Approximation.PartialSourceInventory
import TNLean.PEPS.Approximation.PartyCoarseningFactorization
import TNLean.PEPS.Approximation.PartyFactorization
import TNLean.PEPS.Approximation.PartyGrouping
import TNLean.PEPS.Approximation.PartyLayout
import TNLean.PEPS.Approximation.PartyLocalMaps
import TNLean.PEPS.Approximation.PartyPartition
import TNLean.PEPS.Approximation.PartyTensorMaps
import TNLean.PEPS.Approximation.PartyWord
import TNLean.PEPS.Approximation.PreparedMatrixNorm
import TNLean.PEPS.Approximation.PreparedPartyMaps
import TNLean.PEPS.Approximation.PreparedSourceGate
import TNLean.PEPS.Approximation.SelectiveSourceFactorization
import TNLean.PEPS.Approximation.SelectiveSourcePreparation
import TNLean.PEPS.Approximation.SourceBlockMatrix
import TNLean.PEPS.Approximation.SourceChoiceCost
import TNLean.PEPS.Approximation.SourceCircuitChoiceProduct
import TNLean.PEPS.Approximation.SourceCircuitLocations
import TNLean.PEPS.Approximation.SourceCircuitSourceOrder
import TNLean.PEPS.Approximation.SourceFrameMatrix
import TNLean.PEPS.Approximation.SourceGateDensity
import TNLean.PEPS.Approximation.SourceOwnerMap
import TNLean.PEPS.Approximation.SourcePairIndex
import TNLean.PEPS.Approximation.SourcePairMaps
import TNLean.PEPS.Approximation.SourcePreparation
import TNLean.PEPS.Approximation.SourcePreparationCoordinates
import TNLean.PEPS.Approximation.SourceSlotBasis
import TNLean.PEPS.Approximation.SourceSlotMaps
import TNLean.PEPS.Approximation.UnitPairSource
import TNLean.PEPS.Approximation.WordAppendTail
import TNLean.PEPS.Approximation.WordOwnerMap
import TNLean.PEPS.Approximation.WordPermutation
import TNLean.PEPS.Approximation.WordRestriction
