/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.PEPS.GInjectiveMPSIntersection
import TNLean.PEPS.GInjectiveRangeEquivalence

/-!
# Intersection of local boundary spaces along an inhomogeneous strip

The three-block left-inverse argument remains valid when the two endpoint
blocks have different tensors and physical alphabets. The middle and right
blocks are G-injective; the left block need only be invariant. The resulting
intersection is an equality of the genuine spaces generated by arbitrary
virtual boundary operators, with the unused physical factor left free.

Source: SCP10, arXiv:1001.3807, Theorem 4.8, lines 1084–1123,
and the reduction in Theorem 5.4, lines 1373–1436. This is the matrix-valued
blocked-strip argument, not the intersection theorem for general PEPS graphs.
The latter also requires identifying the graph-regional open contractions
with the strip boundary maps.

## References

- [arXiv:1001.3807](https://arxiv.org/abs/1001.3807) -- N. Schuch, J. I. Cirac,
  D. Pérez-García, *PEPS as ground states: degeneracy and topology*
-/

open Module LinearMap Representation

namespace TNLean.PEPS

variable {G V ι κ ν : Type*} [Group G] [AddCommGroup V] [Module ℂ V]
variable {ρ : Representation ℂ G V}
variable {A : ι → Module.End ℂ V} {B : κ → Module.End ℂ V} {C : ν → Module.End ℂ V}

attribute [local instance] Representation.invertibleFintypeCardComplex

/-- The actual two-block boundary spaces intersect in the three-block boundary
space for arbitrary endpoint tensors and alphabets. The left block need only
be invariant. Source: the left-inverse proof of SCP10, Theorem 4.8,
lines 1098–1123, as used for strips in Theorem 5.4, lines 1413–1436. -/
theorem IsGInjective.strip_intersection_property_of_invariant_left
    [Finite G] [FiniteDimensional ℂ V] [Finite κ] [Finite ν]
    (hB : IsGInjective (linHom ρ ρ) (mpsSiteMap B))
    (hC : IsGInjective (linHom ρ ρ) (mpsSiteMap C))
    (hAi : ∀ g i, ρ g * A i * ρ g⁻¹ = A i) :
    {ψ : (ι × κ) × ν → ℂ | ∃ M : ν → Module.End ℂ V,
        ∀ i j k, ψ ((i, j), k) = LinearMap.trace ℂ V (A i * B j * M k)} ∩
      {ψ | ∃ N : ι → Module.End ℂ V,
        ∀ i j k, ψ ((i, j), k) = LinearMap.trace ℂ V (N i * B j * C k)} =
      Set.range (mpsSiteMap (concatTensor (concatTensor A B) C)) := by
  classical
  have := Fintype.ofFinite G
  have := Fintype.ofFinite ν
  have := Fintype.ofFinite κ
  obtain ⟨hCi, LC, hLC⟩ := hC.exists_mpsLeftInverse
  obtain ⟨hBi, LB, hLB⟩ := hB.exists_mpsLeftInverse
  ext ψ
  constructor
  · rintro ⟨⟨M, hM⟩, ⟨N, hN⟩⟩
    set X := (Fintype.card G : ℂ) • ∑ k, LC (Pi.single k 1) * deltaOperator ρ *
      (linHom ρ ρ).averageMap (M k) with hX
    refine ⟨X, funext fun ⟨⟨i, j⟩, k⟩ => ?_⟩
    -- Inverting the middle-right block gives `σ(N^i) = X A^i`.
    have hkey : (linHom ρ ρ).averageMap (N i) = X * A i := by
      have h1 := LinearMap.congr_fun (concatLeftInverse_comp_mpsSiteMap ρ hLB hLC) (N i)
      rw [LinearMap.comp_apply] at h1
      have h2 : mpsSiteMap (concatTensor B C) (N i) =
          fun p => LinearMap.trace ℂ V (B p.1 * (M p.2 * A i)) := by
        funext p
        have := (hN i p.1 p.2).symm.trans (hM i p.1 p.2)
        rw [mpsSiteMap_apply, concatTensor_apply, LinearMap.trace_mul_comm ℂ _ (N i),
          ← mul_assoc, this, mul_assoc, LinearMap.trace_mul_comm ℂ (A i), mul_assoc]
      rw [← h1, h2, concatLeftInverse_apply_trace_mul ρ LC hLB fun k => M k * A i, hX]
      simp only [averageMap_mul_of_conj_eq ρ (fun g => hAi g i), smul_mul_assoc,
        Finset.sum_mul, mul_assoc]
    have h3 := congr_fun (mpsSiteMap_averageMap (concatTensor_conj_eq hBi hCi) (N i)) (j, k)
    simp only [mpsSiteMap_apply, concatTensor_apply, hkey] at h3
    symm
    calc ψ ((i, j), k) = LinearMap.trace ℂ V (B j * C k * N i) := by
          rw [hN, mul_assoc, LinearMap.trace_mul_comm]
      _ = LinearMap.trace ℂ V (A i * B j * C k * X) := by
          rw [← h3, ← mul_assoc, LinearMap.trace_mul_comm]
          simp only [mul_assoc]
  · rintro ⟨X, rfl⟩
    refine ⟨⟨fun k => C k * X, fun i j k => by simp [mul_assoc]⟩,
      ⟨fun i => X * A i, fun i j k => ?_⟩⟩
    rw [mpsSiteMap_apply, LinearMap.trace_mul_comm]
    simp only [concatTensor_apply, mul_assoc]

/-- Fix the last physical index of a three-block vector. -/
def stripLeftSlice (k : ν) : (((ι × κ) × ν) → ℂ) →ₗ[ℂ] ((ι × κ) → ℂ) where
  toFun ψ p := ψ (p, k)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- Fix the first physical index of a three-block vector. -/
def stripRightSlice (i : ι) : (((ι × κ) × ν) → ℂ) →ₗ[ℂ] ((κ × ν) → ℂ) where
  toFun ψ p := ψ ((i, p.1), p.2)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- The actual left two-block boundary space with a free right physical factor.
Source: SCP10, Theorem 4.8, left-hand boundary family, lines 1084–1097;
the corresponding strip growth in Theorem 5.4, lines 1373–1412. -/
noncomputable def stripLeftGroundSpace (A : ι → Module.End ℂ V)
    (B : κ → Module.End ℂ V) : Submodule ℂ (((ι × κ) × ν) → ℂ) :=
  ⨅ k : ν, (mpsSiteMap (concatTensor A B)).range.comap (stripLeftSlice k)

/-- The actual right two-block boundary space with a free left physical factor.
Source: SCP10, Theorem 4.8, right-hand boundary family, lines 1084–1097;
the corresponding strip growth in Theorem 5.4, lines 1373–1412. -/
noncomputable def stripRightGroundSpace (B : κ → Module.End ℂ V)
    (C : ν → Module.End ℂ V) : Submodule ℂ (((ι × κ) × ν) → ℂ) :=
  ⨅ i : ι, (mpsSiteMap (concatTensor B C)).range.comap (stripRightSlice i)

/-- Membership in the left boundary space is an explicit family of virtual
boundary operators. Source: SCP10, Theorem 4.8, lines 1084–1097. -/
theorem mem_stripLeftGroundSpace_iff (ψ : (ι × κ) × ν → ℂ) :
    ψ ∈ stripLeftGroundSpace A B ↔ ∃ M : ν → Module.End ℂ V,
      ∀ i j k, ψ ((i, j), k) = LinearMap.trace ℂ V (A i * B j * M k) := by
  classical
  simp only [stripLeftGroundSpace, Submodule.mem_iInf, Submodule.mem_comap]
  change (∀ k, ∃ X, mpsSiteMap (concatTensor A B) X = fun p => ψ (p, k)) ↔ _
  constructor
  · intro h
    choose M hM using h
    exact ⟨M, fun i j k => (congr_fun (hM k) (i, j)).symm⟩
  · rintro ⟨M, hM⟩ k
    exact ⟨M k, funext fun ⟨i, j⟩ => (hM i j k).symm⟩

/-- Membership in the right boundary space is an explicit family of virtual
boundary operators. Source: SCP10, Theorem 4.8, lines 1084–1097. -/
theorem mem_stripRightGroundSpace_iff [FiniteDimensional ℂ V] (ψ : (ι × κ) × ν → ℂ) :
    ψ ∈ stripRightGroundSpace B C ↔ ∃ N : ι → Module.End ℂ V,
      ∀ i j k, ψ ((i, j), k) = LinearMap.trace ℂ V (N i * B j * C k) := by
  classical
  simp only [stripRightGroundSpace, Submodule.mem_iInf, Submodule.mem_comap]
  change (∀ i, ∃ X, mpsSiteMap (concatTensor B C) X = fun p => ψ ((i, p.1), p.2)) ↔ _
  constructor
  · intro h
    choose N hN using h
    refine ⟨N, fun i j k => ?_⟩
    rw [← congr_fun (hN i) (j, k), mpsSiteMap_apply, concatTensor_apply,
      LinearMap.trace_mul_comm]
    simp only [mul_assoc]
  · rintro ⟨N, hN⟩ i
    refine ⟨N i, funext fun ⟨j, k⟩ => ?_⟩
    rw [mpsSiteMap_apply, concatTensor_apply, LinearMap.trace_mul_comm, hN]
    simp only [mul_assoc]

/-- Intersection of the genuine lifted local boundary ranges for an
inhomogeneous strip. No equality of support spaces is assumed.
Source: the proof of SCP10, Theorem 4.8, lines 1098–1123, used for
strip growth in Theorem 5.4, lines 1413–1436. -/
theorem IsGInjective.strip_groundSpace_intersection_of_invariant_left
    [Finite G] [FiniteDimensional ℂ V] [Finite κ] [Finite ν]
    (hB : IsGInjective (linHom ρ ρ) (mpsSiteMap B))
    (hC : IsGInjective (linHom ρ ρ) (mpsSiteMap C))
    (hAi : ∀ g i, ρ g * A i * ρ g⁻¹ = A i) :
    stripLeftGroundSpace (ν := ν) A B ⊓ stripRightGroundSpace (ι := ι) B C =
      (mpsSiteMap (concatTensor (concatTensor A B) C)).range := by
  ext ψ
  rw [Submodule.mem_inf, mem_stripLeftGroundSpace_iff, mem_stripRightGroundSpace_iff]
  exact Set.ext_iff.mp (hB.strip_intersection_property_of_invariant_left hC hAi) ψ

/-- The local boundary-space intersection for three G-injective blocks with
independent endpoint tensors and physical alphabets.
Source: the inhomogeneous left-inverse argument of SCP10, Theorem 4.8,
lines 1098–1123, and Theorem 5.4, lines 1413–1436. -/
theorem IsGInjective.strip_groundSpace_intersection
    [Finite G] [FiniteDimensional ℂ V] [Finite κ] [Finite ν]
    (hA : IsGInjective (linHom ρ ρ) (mpsSiteMap A))
    (hB : IsGInjective (linHom ρ ρ) (mpsSiteMap B))
    (hC : IsGInjective (linHom ρ ρ) (mpsSiteMap C)) :
    stripLeftGroundSpace (ν := ν) A B ⊓ stripRightGroundSpace (ι := ι) B C =
      (mpsSiteMap (concatTensor (concatTensor A B) C)).range :=
  hB.strip_groundSpace_intersection_of_invariant_left hC
    ((mpsSiteMap_comp_linHom_eq_iff ρ A).mp hA.invariant)

/-- Every vector satisfying the two local strip conditions has a unique
invariant virtual boundary operator. Source: SCP10, Theorem 4.8,
lines 1098–1123, and G-injectivity in Definition 4.2, lines 893–910. -/
theorem IsGInjective.existsUnique_invariant_boundary_of_mem_strip_intersection
    [Finite G] [FiniteDimensional ℂ V] [Finite ι] [Finite κ] [Finite ν]
    (hA : IsGInjective (linHom ρ ρ) (mpsSiteMap A))
    (hB : IsGInjective (linHom ρ ρ) (mpsSiteMap B))
    (hC : IsGInjective (linHom ρ ρ) (mpsSiteMap C))
    {ψ : (ι × κ) × ν → ℂ}
    (hψ : ψ ∈ stripLeftGroundSpace A B ⊓ stripRightGroundSpace B C) :
    ∃! X : (linHom ρ ρ).invariants,
      mpsSiteMap (concatTensor (concatTensor A B) C) X = ψ := by
  have hT := (hA.mpsSiteMap_concatTensor hB).mpsSiteMap_concatTensor hC
  rw [hA.strip_groundSpace_intersection hB hC] at hψ
  obtain ⟨X, hX, huniq⟩ := hT.bijective_invariants_rangeRestrict.existsUnique ⟨ψ, hψ⟩
  exact ⟨X, congrArg Subtype.val hX, fun Y hY => huniq Y (Subtype.ext hY)⟩

/-- The intersection dimension is the dimension of the invariant virtual
operator space. Source: SCP10, Theorem 4.8, lines 1084–1123,
and G-injectivity in Definition 4.2, lines 893–910. -/
theorem IsGInjective.finrank_strip_groundSpace_intersection
    [Finite G] [FiniteDimensional ℂ V] [Finite ι] [Finite κ] [Finite ν]
    (hA : IsGInjective (linHom ρ ρ) (mpsSiteMap A))
    (hB : IsGInjective (linHom ρ ρ) (mpsSiteMap B))
    (hC : IsGInjective (linHom ρ ρ) (mpsSiteMap C)) :
    Module.finrank ℂ ↥(stripLeftGroundSpace (ν := ν) A B ⊓
        stripRightGroundSpace (ι := ι) B C) =
      Module.finrank ℂ (linHom ρ ρ).invariants := by
  rw [hA.strip_groundSpace_intersection hB hC]
  exact ((hA.mpsSiteMap_concatTensor hB).mpsSiteMap_concatTensor hC).finrank_range

end TNLean.PEPS
