/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TNLean.Channel.Peripheral.CyclicDecomposition
import Mathlib.RingTheory.RootsOfUnity.Basic

/-!
# Peripheral eigenvalue group structure (Wolf Theorem 6.6)

This file establishes that the peripheral eigenvalues of an irreducible
quantum channel form a **cyclic group** under multiplication, completing
the formalization of Wolf Theorem 6.6.

## Building blocks (already formalized elsewhere)

The proof combines three ingredients that already exist:

1. **Peripheral eigenvalues are roots of unity** — proved in
   `Channel/Peripheral/ClosureFixedPoint.lean` as
   `peripheral_isRootOfUnity_of_irreducible_unital_of_adjoint_fixedPoint`

2. **Finite subgroups of `ℂ*` consisting of roots of unity are cyclic** —
   Mathlib's `rootsOfUnity.isCyclic` in `RingTheory/RootsOfUnity/Basic.lean`

3. **Peripheral unitaries and cyclic projections** — proved in
   `Channel/Peripheral/CyclicDecomposition.lean` via
   `exists_peripheral_unitary_of_irreducible_schwarz` and
   `exists_cyclic_projections_of_peripheral_unitary`

## Main results

* `peripheral_eigenvalues_closed_under_mul` — closure under multiplication
* `peripheral_eigenvalues_closed_under_inv` — closure under inversion
* `peripheral_eigenvalues_form_cyclic_group` — the full cyclic group structure
* `peripheral_eigenvalue_multiplicity_one` — each eigenvalue has multiplicity 1
* `channel_period_divides_dim` — period divides bond dimension

## References

* [M. Wolf, *Quantum Channels & Operations: Guided Tour*, §6.2, Thm 6.6]
* [Evans, Høegh-Krohn, *Spectral properties of positive maps*, 1978]
-/

open scoped Matrix ComplexOrder MatrixOrder BigOperators
open Matrix Finset Complex

variable {D : ℕ}

namespace PeripheralSpectrum

/-! ### Summary

This namespace collects the key results on peripheral eigenvalues of irreducible
quantum channels:

* **Closure under multiplication and inversion** — the peripheral spectrum is a
  subgroup of `ℂˣ`.
* **Cyclic group structure** (Wolf Theorem 6.6) — that subgroup is cyclic,
  generated by a single root of unity.
* **Multiplicity-one result** — every peripheral eigenvalue has algebraic
  multiplicity one.
* **Period-divides-dimension bound** — the period (order of the cyclic group)
  divides the bond dimension `D`.
-/

/-! ## Closure under multiplication -/

/-- **Peripheral eigenvalues are closed under multiplication.**

Follows from `exists_peripheral_unitary_of_irreducible_schwarz`: peripheral
eigenvalues have unitary eigenvectors, and the multiplicative domain property
gives `E(U_α U_β) = E(U_α) E(U_β) = αβ · U_α U_β`. -/
theorem peripheral_eigenvalues_closed_under_mul
    {r : ℕ} [NeZero D]
    (K : Fin r → MatrixAlg D)
    (hUnital : KadisonSchwarz.IsUnitalKraus (d := r) (D := D) K)
    (ρ : MatrixAlg D) (hρ : ρ.PosDef)
    (hρfix : Kraus.adjointMap K ρ = ρ)
    (hIrr : IsIrreducibleMap (MPSTensor.transferMap (d := r) (D := D) K))
    {α β : ℂ}
    (hα : α ∈ peripheralEigenvalues (MPSTensor.transferMap (d := r) (D := D) K))
    (hβ : β ∈ peripheralEigenvalues (MPSTensor.transferMap (d := r) (D := D) K)) :
    (α * β) ∈ peripheralEigenvalues (MPSTensor.transferMap (d := r) (D := D) K) := by
  -- Get unitary eigenvectors U_α and U_β from CyclicDecomposition.
  obtain ⟨Uα, hUα⟩ := MPSTensor.exists_peripheral_unitary_of_irreducible_schwarz
    K hUnital ρ hρ hρfix hIrr hα
  obtain ⟨Uβ, hUβ⟩ := MPSTensor.exists_peripheral_unitary_of_irreducible_schwarz
    K hUnital ρ hρ hρfix hIrr hβ
  constructor
  · -- HasEigenvalue for α * β: product of unitaries is nonzero, and
    -- E(U_α U_β) = α β · U_α U_β by the multiplicative domain.
    have hUnital' : Kraus.IsUnital K := by
      simpa [Kraus.IsUnital, KadisonSchwarz.IsUnitalKraus] using hUnital
    -- Convert eigenvector eq for Uβ to Kraus.map, then get KS equality
    have hUβ_map : Kraus.map K (Uβ : MatrixAlg D) = β • (Uβ : MatrixAlg D) := by
      simpa [Kraus.map, MPSTensor.transferMap_apply] using hUβ
    have hKSβ_map :=
      Kraus.ks_equality_of_peripheral_eigenvector_of_fixedPoint
        K hUnital' hρ hρfix _ β hUβ_map hβ.2
    have hKSβ : KadisonSchwarz.krausMap K ((Uβ : MatrixAlg D)ᴴ * (Uβ : MatrixAlg D)) =
        (KadisonSchwarz.krausMap K (Uβ : MatrixAlg D))ᴴ *
          KadisonSchwarz.krausMap K (Uβ : MatrixAlg D) := by
      simpa [Kraus.map, KadisonSchwarz.krausMap] using hKSβ_map
    -- multiplicative_domain_right: E(Uα · Uβ) = E(Uα) · E(Uβ)
    have hprod_kraus : KadisonSchwarz.krausMap K ((Uα : MatrixAlg D) * (Uβ : MatrixAlg D)) =
        KadisonSchwarz.krausMap K (Uα : MatrixAlg D) *
          KadisonSchwarz.krausMap K (Uβ : MatrixAlg D) :=
      KadisonSchwarz.multiplicative_domain_right K hUnital
        (Uβ : MatrixAlg D) hKSβ (Uα : MatrixAlg D)
    -- Compute: E(Uα) · E(Uβ) = (α · Uα)(β · Uβ) = αβ · (Uα · Uβ)
    have hUα_kraus : KadisonSchwarz.krausMap K (Uα : MatrixAlg D) =
        α • (Uα : MatrixAlg D) := by
      simpa [KadisonSchwarz.krausMap, MPSTensor.transferMap_apply] using hUα
    have hUβ_kraus : KadisonSchwarz.krausMap K (Uβ : MatrixAlg D) =
        β • (Uβ : MatrixAlg D) := by
      simpa [KadisonSchwarz.krausMap, MPSTensor.transferMap_apply] using hUβ
    have hprod_transfer : MPSTensor.transferMap (d := r) (D := D) K
        ((Uα : MatrixAlg D) * (Uβ : MatrixAlg D)) =
        (α * β) • ((Uα : MatrixAlg D) * (Uβ : MatrixAlg D)) := by
      have : KadisonSchwarz.krausMap K ((Uα : MatrixAlg D) * (Uβ : MatrixAlg D)) =
          (α * β) • ((Uα : MatrixAlg D) * (Uβ : MatrixAlg D)) := by
        rw [hprod_kraus, hUα_kraus, hUβ_kraus, smul_mul_assoc, mul_smul_comm, smul_smul]
      simpa [KadisonSchwarz.krausMap, MPSTensor.transferMap_apply] using this
    -- Product of unitaries is nonzero (left-cancel by Uα†)
    have hprod_ne : (Uα : MatrixAlg D) * (Uβ : MatrixAlg D) ≠ 0 := by
      intro h
      have hUα_inv : (Uα : MatrixAlg D)ᴴ * (Uα : MatrixAlg D) = 1 := by
        have hstar_α := Matrix.UnitaryGroup.star_mul_self Uα
        rwa [star_eq_conjTranspose] at hstar_α
      have hUβ_inv : (Uβ : MatrixAlg D)ᴴ * (Uβ : MatrixAlg D) = 1 := by
        have hstar_β := Matrix.UnitaryGroup.star_mul_self Uβ
        rwa [star_eq_conjTranspose] at hstar_β
      have hUβ_zero : (Uβ : MatrixAlg D) = 0 := by
        calc (Uβ : MatrixAlg D)
            = 1 * (Uβ : MatrixAlg D) := (one_mul _).symm
          _ = (Uα : MatrixAlg D)ᴴ * (Uα : MatrixAlg D) * (Uβ : MatrixAlg D) := by
                rw [hUα_inv]
          _ = (Uα : MatrixAlg D)ᴴ * ((Uα : MatrixAlg D) * (Uβ : MatrixAlg D)) := by
                rw [mul_assoc]
          _ = 0 := by rw [h, mul_zero]
      exact one_ne_zero (by rw [← hUβ_inv, hUβ_zero, mul_zero])
    exact hasEigenvalue_of_eigenvector_eq _ _ _ hprod_transfer hprod_ne
  · rw [Complex.norm_mul, hα.2, hβ.2, mul_one]

/-- **Peripheral eigenvalues are closed under inversion.**

For `|α| = 1`, we have `α⁻¹ = ᾱ`, and `U_α†` is the eigenvector. -/
theorem peripheral_eigenvalues_closed_under_inv
    {r : ℕ} [NeZero D]
    (K : Fin r → MatrixAlg D)
    (hUnital : KadisonSchwarz.IsUnitalKraus (d := r) (D := D) K)
    (ρ : MatrixAlg D) (hρ : ρ.PosDef)
    (hρfix : Kraus.adjointMap K ρ = ρ)
    (hIrr : IsIrreducibleMap (MPSTensor.transferMap (d := r) (D := D) K))
    {α : ℂ}
    (hα : α ∈ peripheralEigenvalues (MPSTensor.transferMap (d := r) (D := D) K)) :
    α⁻¹ ∈ peripheralEigenvalues (MPSTensor.transferMap (d := r) (D := D) K) := by
  constructor
  · -- HasEigenvalue for α⁻¹: Uα† is the eigenvector
    obtain ⟨Uα, hUα⟩ := MPSTensor.exists_peripheral_unitary_of_irreducible_schwarz
      K hUnital ρ hρ hρfix hIrr hα
    -- E(Uα†) = (E(Uα))† = (α · Uα)† = ᾱ · Uα† = α⁻¹ · Uα†
    have hUα_map : Kraus.map K (Uα : MatrixAlg D) = α • (Uα : MatrixAlg D) := by
      simpa [Kraus.map, MPSTensor.transferMap_apply] using hUα
    -- ᾱ = α⁻¹ when |α| = 1
    have hα_ne : α ≠ 0 := norm_ne_zero_iff.mp (by rw [hα.2]; exact one_ne_zero)
    have hconj_eq_inv : starRingEnd ℂ α = α⁻¹ := by
      have hnormSq : Complex.normSq α = 1 := by
        rw [Complex.normSq_eq_norm_sq]; simp [hα.2]
      have hconj_mul : starRingEnd ℂ α * α = 1 := by
        calc starRingEnd ℂ α * α
            = (↑(Complex.normSq α) : ℂ) := by
              simpa using (Complex.normSq_eq_conj_mul_self (z := α)).symm
          _ = 1 := by simp [hnormSq]
      exact mul_right_cancel₀ hα_ne
        (by rw [hconj_mul, inv_mul_cancel₀ hα_ne])
    have hmap_conj : Kraus.map K (Uα : MatrixAlg D)ᴴ =
        α⁻¹ • (Uα : MatrixAlg D)ᴴ := by
      rw [← Kraus.map_conjTranspose, hUα_map, conjTranspose_smul]
      simp only [Complex.star_def, hconj_eq_inv]
    have hconj_transfer : MPSTensor.transferMap (d := r) (D := D) K (Uα : MatrixAlg D)ᴴ =
        α⁻¹ • (Uα : MatrixAlg D)ᴴ := by
      simpa [Kraus.map, MPSTensor.transferMap_apply] using hmap_conj
    -- Uα† is nonzero
    have hUα_conj_ne : (Uα : MatrixAlg D)ᴴ ≠ 0 := by
      intro h
      have h1 := Matrix.UnitaryGroup.star_mul_self Uα
      rw [star_eq_conjTranspose, h, zero_mul] at h1
      exact one_ne_zero h1.symm
    exact hasEigenvalue_of_eigenvector_eq _ _ _ hconj_transfer hUα_conj_ne
  · rw [norm_inv, hα.2, inv_one]

/-! ## Cyclic group structure

The proof strategy uses Mathlib's `rootsOfUnity.isCyclic`:

1. By `peripheral_isRootOfUnity_of_irreducible_unital_of_adjoint_fixedPoint`,
   every peripheral eigenvalue `μ` satisfies `μ^p = 1` for some `p > 0`.
2. Taking `m = lcm` of all such periods, every peripheral eigenvalue is an
   `m`-th root of unity.
3. The peripheral eigenvalues embed into `rootsOfUnity m ℂ`, which is cyclic
   by Mathlib's `rootsOfUnity.isCyclic`.
4. The period `m` divides `D` via the cyclic projections from
   `CyclicDecomposition.lean`.
-/

/-- **The peripheral eigenvalues form a cyclic group** (Wolf Thm 6.6).

Combines `peripheral_isRootOfUnity_of_irreducible_unital_of_adjoint_fixedPoint`
(peripheral eigenvalues are roots of unity) with Mathlib's
`rootsOfUnity.isCyclic` (finite subgroups of `ℂ*` are cyclic). -/
theorem peripheral_eigenvalues_form_cyclic_group
    {r : ℕ} [NeZero D]
    (K : Fin r → MatrixAlg D)
    (hUnital : KadisonSchwarz.IsUnitalKraus (d := r) (D := D) K)
    (ρ : MatrixAlg D) (hρ : ρ.PosDef)
    (hρfix : Kraus.adjointMap K ρ = ρ)
    (hIrr : IsIrreducibleMap (MPSTensor.transferMap (d := r) (D := D) K)) :
    ∃ (m : ℕ) (γ : ℂ),
      0 < m ∧
      IsPrimitiveRoot γ m ∧
      m ∣ D ∧
      peripheralEigenvalues (MPSTensor.transferMap (d := r) (D := D) K) =
        {z : ℂ | ∃ k : Fin m, z = γ ^ (k : ℕ)} := by
  -- Step 1: Each peripheral eigenvalue is a root of unity (ClosureFixedPoint.lean).
  -- Step 2: Embed into rootsOfUnity (lcm of periods) in ℂ.
  -- Step 3: Apply rootsOfUnity.isCyclic from Mathlib.
  -- Step 4: Extract primitive root and period.
  -- Step 5: Period divides D via cyclic projections (CyclicDecomposition.lean).
  sorry -- TODO (#22): connect ClosureFixedPoint + Mathlib rootsOfUnity.isCyclic

/-- **Each peripheral eigenvalue has multiplicity 1** (Wolf Thm 6.6).

Follows from `fixed_eq_scalar_of_irreducible_unital` in
`CyclicDecomposition.lean`: if `E(X) = X` with `E` irreducible and unital,
then `X = c · I`. Applied to `E^m` restricted to a cyclic sector, this
forces one-dimensional eigenspaces. -/
theorem peripheral_eigenvalue_multiplicity_one
    {r : ℕ} [NeZero D]
    (K : Fin r → MatrixAlg D)
    (hUnital : KadisonSchwarz.IsUnitalKraus (d := r) (D := D) K)
    (ρ : MatrixAlg D) (hρ : ρ.PosDef)
    (hρfix : Kraus.adjointMap K ρ = ρ)
    (hIrr : IsIrreducibleMap (MPSTensor.transferMap (d := r) (D := D) K))
    {γ : ℂ}
    (hγ : γ ∈ peripheralEigenvalues (MPSTensor.transferMap (d := r) (D := D) K)) :
    Module.finrank ℂ
      (Module.End.eigenspace (MPSTensor.transferMap (d := r) (D := D) K) γ) = 1 := by
  -- Use fixed_eq_scalar_of_irreducible_unital from CyclicDecomposition.lean
  sorry -- TODO (#22): restrict E^m to cyclic sector, apply scalar-fixed-point lemma

/-- The **period** of the channel divides `D` (the bond dimension).

Here `m` is the order of the peripheral eigenvalue group: `γ` is a primitive
`m`-th root of unity that generates **all** peripheral eigenvalues via `hgen`.
Without `hgen`, the statement would be trivially satisfiable with `m=1, γ=1`.

Follows from `exists_cyclic_projections_of_peripheral_unitary` in
`CyclicDecomposition.lean`: the `m` mutually orthogonal projections summing
to `I` force each to have rank `D/m`. -/
theorem channel_period_divides_dim
    {r : ℕ} [NeZero D]
    (K : Fin r → MatrixAlg D)
    (hUnital : KadisonSchwarz.IsUnitalKraus (d := r) (D := D) K)
    (ρ : MatrixAlg D) (hρ : ρ.PosDef)
    (hρfix : Kraus.adjointMap K ρ = ρ)
    (hIrr : IsIrreducibleMap (MPSTensor.transferMap (d := r) (D := D) K))
    {m : ℕ} {γ : ℂ} (hm : 0 < m)
    (hγprim : IsPrimitiveRoot γ m)
    (hγ : γ ∈ peripheralEigenvalues (MPSTensor.transferMap (d := r) (D := D) K))
    (hgen : peripheralEigenvalues (MPSTensor.transferMap (d := r) (D := D) K) =
      {z : ℂ | ∃ k : Fin m, z = γ ^ (k : ℕ)}) :
    m ∣ D := by
  -- Use exists_cyclic_projections_of_peripheral_unitary from CyclicDecomposition.lean
  sorry -- TODO (#22): m orthogonal projections summing to I force rank D/m each

end PeripheralSpectrum
