/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.Examples.Z3Anomalous.Z3AnomalyClass

/-!
# Anomalous `ℤ₃` symmetry: the representation `{1, U, U†}` against the cocycle construction

**Source.** Garre-Rubio, Lootens, Molnár 2023 (arXiv:2203.12563), subsubsection "Periodic
boundary condition case", `Papers/2203.12563/REsubmission.tex` lines 2202–2224: for a finite
group `G` and a three-cocycle `ω`, the operators `U_g` generated by the bond-`|G|` tensor
`T̂_g` form a periodic matrix product operator representation of `G`. Garre-Rubio, Schuch 2024
(arXiv:2405.00439), Section IV.D, `Papers/2405.00439/MPU-DW.tex` line 2040: the three-cocycles
`ω_j(a,b,c) = exp{2πi j a (b + c − [b + c]) / n²}` of `ℤ_n`. Neither source prints the
bond-two tensors of `{1, U, U†}` or relates them to the construction.

**Formalized here.** The two exact representations of `ℤ₃` on periodic qutrit chains, the
family `{1, U, U†}` of `Z3AnomalousRepresentation` and the construction of arXiv:2203.12563
for `ω_1`, are conjugate by one diagonal unitary `V_N`, the same for every group element: on
every nonempty chain, `U_g V_N = V_N U_g^{ω_1}`, hence `U_g = V_N U_g^{ω_1} V_N†`. The unitary
`V_N` multiplies `|t⟩` by `ω^{E(t)}` with `E(t) = ∑_k ([t_k = 2] + [t_k = 1][t_{k+1} = 2])`,
that is, `V_N = D^{⊗N} ∏_k C_{k,k+1}` with the on-site gate `D = diag(1, 1, ω)` and the
commuting two-site diagonal gates `C`, which multiply `|1, 2⟩` by `ω` and fix the other
basis states. The relation is a project result.

No purely on-site diagonal gauge suffices. Both generators shift every qutrit by one, `U` with
phase `ω^{F(t)}`, `F(t) = ∑_k [t_k ≠ 0] t_{k+1}`, and `U^{ω_1}` with phase `ω^{c(t)}`, where
`c(t)` counts the bonds with `t_k < t_{k+1}`. A diagonal conjugation by `∏_k ω^{w(t_k,t_{k+1})}`
changes the exponent of the shift by `∑_k (w(t_k + 1, t_{k+1} + 1) − w(t_k, t_{k+1}))`. For an
on-site gate `w(a, b) = α(a)` this is a sum of single-site terms, whereas the bond difference
`[a ≠ 0] b − [a < b]` of `F − c` is not, modulo three, a function of `a` plus a function of `b`,
as it would have to be for the exponents to agree on every chain. This remark is not
formalized.

Conjugation by the finite-depth circuit `V_N` preserves the anomaly class, so the class of the
construction for `ω_1` is the class computed for `{1, U, U†}` in `Z3AnomalyClass`; that
invariance is not formalized here.

## Main definitions

* `Z3Anomalous.gateExponent`, `Z3Anomalous.gaugeExponent`: the exponent `E(t)`.
* `Z3Anomalous.cocycleGauge`: the diagonal unitary `V_N`.

## Main results

* `Z3Anomalous.mpo_uTensor_mul_cocycleGauge`: `U V_N = V_N U_g^{ω_1}` for the generator.
* `Z3Anomalous.mpo_family_mul_cocycleGauge`: the same for every group element.
* `Z3Anomalous.cocycleGauge_mem_unitaryGroup`: `V_N` is unitary.
* `Z3Anomalous.mpo_family_eq_cocycleGauge_conj`: `U_g = V_N U_g^{ω_1} V_N†`.

## References
- [arXiv:2203.12563](https://arxiv.org/abs/2203.12563) -- Garre-Rubio, Lootens, Molnár,
  *Classifying phases protected by matrix product operator symmetries using matrix product
  states*
- [arXiv:2405.00439](https://arxiv.org/abs/2405.00439) -- Garre-Rubio, Schuch,
  *Fractional domain wall statistics in spin chains with anomalous symmetries*

## Provenance
The tensors `U` and `U†` are representatives constructed in this development, recorded in
`Notes/OpenProblemsTN/checks/asym_z3_anomalous_data.md`, §1–§2; that file is a verification
record, not the source.
-/

noncomputable section

open scoped BigOperators Matrix

namespace Z3Anomalous

open MPOTensor MPOTensor.GroupCocycle TNLean.Algebra.ScalarThreeCochain

/-- The exponent of the gauge on a neighboring pair `(a, b)`: `[b = 2] + [a = 1][b = 2]`. The
first term is the on-site gate `diag(1, 1, ω)` of the right site, the second the two-site gate
multiplying `|1, 2⟩` by `ω`. -/
def gateExponent (a b : Fin 3) : ℕ :=
  (if b = 2 then 1 else 0) + if a = 1 ∧ b = 2 then 1 else 0

variable {L : ℕ} [NeZero L]

/-- The periodic exponent `E(t) = ∑_k ([t_k = 2] + [t_k = 1][t_{k+1} = 2])`, including the
closing bond. -/
def gaugeExponent (t : Fin L → Fin 3) : ℕ :=
  ∑ k, gateExponent (t k) (t (k + 1))

variable (L) in
/-- The diagonal unitary `V_N |t⟩ = ω^{E(t)} |t⟩`, the product of the on-site gates
`diag(1, 1, ω)` and the two-site gates multiplying `|1, 2⟩` by `ω` on every bond. -/
def cocycleGauge : Matrix (Fin L → Fin 3) (Fin L → Fin 3) ℂ :=
  Matrix.diagonal fun t ↦ eisensteinOmega ^ gaugeExponent t

private theorem rootOfUnity_three : rootOfUnity (2 + 1) = eisensteinOmega := by
  rw [eisensteinOmega_eq_exp, rootOfUnity]
  norm_num

private theorem eisensteinOmega_pow_eq_pow_of_mod {A B : ℕ} (h : A % 3 = B % 3) :
    eisensteinOmega ^ A = eisensteinOmega ^ B := by
  have h3 : eisensteinOmega ^ 3 = 1 := by
    simpa using congrArg eisensteinToComplex EisensteinInt.omega_pow_three
  rw [pow_eq_pow_mod A h3, pow_eq_pow_mod B h3, h]

/-- The bondwise identity behind the conjugation: the phase of `U` on the pair `(a, b)` times
the gauge before the shift equals the gauge after the shift times the cocycle phase. -/
private theorem site_exponent (a b : Fin 3) :
    ((occupied a).val * b.val + gateExponent a b) % 3 =
      (gateExponent (a + 1) (b + 1) + 1 * 1 * ((b.val + (a - b).val) / (2 + 1))) % 3 := by
  revert a b
  decide

/-- **`U V_N = V_N U^{ω_1}` for the generator**: on every nonempty periodic chain, the
bond-two operator `U` and the operator of the construction of arXiv:2203.12563 for `ω_1` at
the generator are conjugate by the diagonal unitary `V_N`.

Project result: the construction is arXiv:2203.12563, lines 2204–2222, with the cocycle `ω_1`
of arXiv:2405.00439, line 2040. -/
theorem mpo_uTensor_mul_cocycleGauge :
    mpo uTensor L * cocycleGauge L =
      cocycleGauge L * mpo (tensor (residueEquiv 2) (cyclicCocycle (2 + 1) 1) z3Gen) L := by
  ext s t
  rw [cocycleGauge, Matrix.mul_diagonal, Matrix.diagonal_mul, mpo_uTensor_apply,
    mpo_tensor_cyclic_apply]
  have hg : residueEquiv 2 z3Gen = 1 := rfl
  have hs : (s = qutritShift L t) ↔ (s = fun i ↦ residueEquiv 2 z3Gen + t i) := by
    rw [hg]
    constructor <;> rintro rfl <;> funext i <;> simp [add_comm]
  by_cases h : s = qutritShift L t
  · rw [ite_eq_left h, ite_eq_left (hs.1 h)]
    subst h
    rw [hg, rootOfUnity_three, Finset.prod_pow_eq_pow_sum, ← pow_add, ← pow_add]
    apply eisensteinOmega_pow_eq_pow_of_mod
    rw [phaseExponent, gaugeExponent, gaugeExponent, ← Finset.sum_add_distrib,
      ← Finset.sum_add_distrib, Finset.sum_nat_mod]
    conv_rhs => rw [Finset.sum_nat_mod]
    congr 1
    refine Finset.sum_congr rfl fun k _ ↦ ?_
    simpa using site_exponent (t k) (t (k + 1))
  · rw [ite_eq_right h, ite_eq_right (mt hs.2 h),
      zero_mul, mul_zero]

/-- **The two representations of `ℤ₃` are conjugate by `V_N`**: for every group element `g`
and every nonempty periodic chain, `U_g V_N = V_N U_g^{ω_1}`, where `U_g` is the operator of
`{1, U, U†}` and `U_g^{ω_1}` that of the construction of arXiv:2203.12563 for `ω_1`.

Project result: the generator case is `mpo_uTensor_mul_cocycleGauge`; the identity and the
square follow from the operator laws of both families. -/
theorem mpo_family_mul_cocycleGauge (g : Multiplicative (ZMod 3)) :
    mpo (family.tensor g) L * cocycleGauge L =
      cocycleGauge L * mpo (cocycleFamily.tensor g) L := by
  have hL := NeZero.pos L
  have h1 : mpo (family.tensor z3Gen) L * cocycleGauge L =
      cocycleGauge L * mpo (cocycleFamily.tensor z3Gen) L :=
    mpo_uTensor_mul_cocycleGauge
  fin_cases g
  · change mpo (family.tensor 1) L * _ = _ * mpo (cocycleFamily.tensor 1) L
    rw [family_operator_laws.2.1 L hL, cocycleFamily_operator_laws.2.1 L hL, Matrix.one_mul,
      Matrix.mul_one]
  · exact h1
  · change mpo (family.tensor (z3Gen * z3Gen)) L * _ =
      _ * mpo (cocycleFamily.tensor (z3Gen * z3Gen)) L
    rw [← family_operator_laws.2.2.1 _ _ L hL, ← cocycleFamily_operator_laws.2.2.1 _ _ L hL,
      Matrix.mul_assoc, h1, ← Matrix.mul_assoc, h1, Matrix.mul_assoc]

/-- `V_N` is unitary: it is diagonal with entries that are powers of `ω`. -/
theorem cocycleGauge_mem_unitaryGroup :
    cocycleGauge L ∈ Matrix.unitaryGroup (Fin L → Fin 3) ℂ := by
  rw [Matrix.mem_unitaryGroup_iff', cocycleGauge, Matrix.star_eq_conjTranspose,
    Matrix.diagonal_conjTranspose, Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
  congr 1
  funext t
  rw [Pi.star_apply, star_pow, ← mul_pow, star_eisensteinOmega_mul, one_pow]

/-- **`U_g = V_N U_g^{ω_1} V_N†`** for every group element `g` and every nonempty periodic
chain: the representation `{1, U, U†}` is the construction of arXiv:2203.12563 for `ω_1`,
conjugated by the diagonal unitary `V_N`.

Project result: `mpo_family_mul_cocycleGauge` and `cocycleGauge_mem_unitaryGroup`. -/
theorem mpo_family_eq_cocycleGauge_conj (g : Multiplicative (ZMod 3)) :
    mpo (family.tensor g) L =
      cocycleGauge L * mpo (cocycleFamily.tensor g) L * star (cocycleGauge L) := by
  have hu := Matrix.mem_unitaryGroup_iff.mp (cocycleGauge_mem_unitaryGroup (L := L))
  rw [← mpo_family_mul_cocycleGauge, Matrix.mul_assoc, hu, Matrix.mul_one]

/-! ### Orientation of the anomaly class -/

/-- Project result: **the cyclic invariant of `ω_1` is `ω₃`.** At the generator `g` only the
factor `ω_1(g, g², g) = ζ` of `ω_1(g,1,g) ω_1(g,g,g) ω_1(g,g²,g)` is nontrivial
(arXiv:2405.00439, `Papers/2405.00439/MPU-DW.tex` line 2040), and `ζ = exp(2πi/3) = ω₃`. -/
theorem cyclicInvariant_cyclicCocycle_one :
    (cyclicInvariant (cyclicCocycle 3 1) z3Gen 3 : ℂ) = eisensteinOmega := by
  simp only [cyclicInvariant, Finset.prod_range_succ, Finset.prod_range_zero, one_mul,
    Units.val_mul, cyclicCocycle_val]
  have h0 : (Multiplicative.toAdd (z3Gen ^ 0)).val = 0 := by decide
  have h1 : (Multiplicative.toAdd (z3Gen ^ 1)).val = 1 := by decide
  have h2 : (Multiplicative.toAdd (z3Gen ^ 2)).val = 2 := by decide
  have hg : (Multiplicative.toAdd z3Gen).val = 1 := by decide
  rw [h0, h1, h2, hg, rootOfUnity, eisensteinOmega_eq_exp]
  norm_num

/-- Project result: **the construction for `ω_1` has the inverse class in the orientation of
arXiv:2502.20257.** For every choice of fusion tensors of `family`, the cyclic invariant of
its anomaly three-cochain is the inverse of the cyclic invariant of `ω_1`: `ω₃² = ω₃⁻¹`.
Since `family` is conjugate to `cocycleFamily` by the diagonal circuit `V_N`, and the class
is invariant under conjugation by such a circuit (not formalized here), the representation
constructed from `ω_1` by arXiv:2203.12563 carries the class `j = 2` for the three-cochain of arXiv:2502.20257 (`Papers/2502.20257/main.tex`, display preceding
`eq:3-cocycle`), which is defined by the same fusion-tree move as in arXiv:2405.00439
(lines 1745–1772). -/
theorem cyclicInvariant_omega_z3_mul_cyclicCocycle_one (fd : family.FusionData) :
    (cyclicInvariant fd.omega z3Gen 3 : ℂ) *
      (cyclicInvariant (cyclicCocycle 3 1) z3Gen 3 : ℂ) = 1 := by
  rw [cyclicInvariant_omega_z3, cyclicInvariant_cyclicCocycle_one, ← pow_succ]
  have h := eisensteinOmega_quadratic
  linear_combination (eisensteinOmega - 1) * h

end Z3Anomalous
