/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import Mathlib.Algebra.Star.Subalgebra
import Mathlib.LinearAlgebra.Basis.VectorSpace
import QICLean.Algebra.MatrixKroneckerEmbed
import QICLean.Algebra.OperatorBlock
import QICLean.Channel.OperatorSystem

/-!
# Bipartite support algebras

For a star-subalgebra of a bipartite complex matrix algebra, its left and right support algebras
are generated by all matrix coefficients on the corresponding tensor factor. This file proves the
matrix-unit reconstruction, leastness, and commutant characterizations used in the
Schumacher--Werner/GNVW index construction.

**Local fix (star-closed input):** The printed statement of GNVW Lemma 7 says only
"subalgebra", but its $C^*$-generated support and commutant clauses require involution closure.
The `StarSubalgebra` input records this necessary correction. Schumacher--Werner,
quant-ph/0405174, lines 1161--1171, instead derives adjoint closure of the support algebra
conditionally from adjoint closure of its observable-algebra input. The GNVW QCA application
supplies this hypothesis at arXiv:0910.3675v2, lines 1251--1265. The MPU application supplies it
through the local star-automorphism at arXiv:1703.09188, lines 2300--2306, for the support-algebra
input in lines 2313--2334.

**Scope restriction (full matrix factors):** After that correction, GNVW Lemma 7 permits
arbitrary finite-dimensional $C^*$-algebra factors, whereas this file takes full complex matrix
factors. Full matrix factors suffice for the MPU spin-chain application because the one-site
algebras are full matrix algebras; see arXiv:1703.09188, lines 2320--2334. The general-factor GNVW
theorem remains open in TNLean; see
`docs/paper-gaps/gnvw12_support_algebra_full_matrix_scope.tex`.

The results here stop before identifying support algebras as full matrix algebras, computing their
dimensions, constructing Margolus gates, or comparing the GNVW and MPU indices.

## Main definitions

* `Matrix.leftCoefficientSet` and `Matrix.rightCoefficientSet` are the two coefficient families.
* `Matrix.leftSupportAlgebra` and `Matrix.rightSupportAlgebra` are their generated
  star-subalgebras.
* `Matrix.kroneckerSubmodule` is the linear span of Kronecker products from two matrix
  submodules.

## Main results

* `Matrix.eq_sum_left_coefficient_kronecker_single` and
  `Matrix.eq_sum_single_kronecker_right_coefficient` reconstruct a bipartite matrix.
* `Matrix.left_support_algebra_le_iff` and `Matrix.right_support_algebra_le_iff` give leastness.
* `Matrix.mem_kroneckerSubmodule_iff` characterizes the two-factor tensor span by coefficients.
* `Matrix.le_support_kroneckerSubmodule` proves the literal two-sided support containment.
* `Matrix.left_kronecker_embed_mem_centralizer_iff` and
  `Matrix.right_kronecker_embed_mem_centralizer_iff` give the two commutant characterizations.
-/

open scoped BigOperators Kronecker

namespace Matrix

variable {m n : Type*} [Fintype m] [DecidableEq m] [Fintype n] [DecidableEq n]

omit [Fintype m] [DecidableEq m] [Fintype n] [DecidableEq n] in
/-- The right-factor coefficient of an adjoint bipartite matrix is the adjoint of the
oppositely indexed coefficient.

This is the second-factor counterpart of `Matrix.bipartiteSlice_conjTranspose`, used in the
coefficient construction of Schumacher--Werner, quant-ph/0405174, lines 1137--1169. -/
@[simp]
theorem operatorBlock_conjTranspose (X : Matrix (m × n) (m × n) ℂ) (i j : m) :
    operatorBlock Xᴴ i j = (operatorBlock X j i)ᴴ := by
  ext k l
  simp [operatorBlock, Matrix.conjTranspose_apply]

/-- The coefficients on the first tensor factor of a bipartite star-subalgebra.

These are the coefficients in the expansion used to define the support algebra in
Schumacher--Werner, quant-ph/0405174, lines 1137--1169. -/
def leftCoefficientSet
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) : Set (Matrix m m ℂ) :=
  {a | ∃ X ∈ A, ∃ i j : n, bipartiteSlice X i j = a}

/-- The coefficients on the second tensor factor of a bipartite star-subalgebra.

This is the symmetric coefficient family in Schumacher--Werner, quant-ph/0405174,
lines 1137--1169. -/
def rightCoefficientSet
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) : Set (Matrix n n ℂ) :=
  {b | ∃ X ∈ A, ∃ i j : m, operatorBlock X i j = b}

/-- The left support algebra of a bipartite star-subalgebra, generated by all first-factor
coefficients.

This is the complex matrix-algebra specialization of GNVW Lemma `lem:spp`,
arXiv:0910.3675v2, lines 1188--1191. The MPU application is arXiv:1703.09188, Appendix,
lines 2320--2334.

**Local fix (star-closed input):** `StarSubalgebra` records the necessary involution-closure
hypothesis omitted from the printed GNVW lemma; the QCA/MPU observable-algebra application
supplies it.

**Scope restriction (full matrix factors):** After that correction, GNVW Lemma 7 permits
arbitrary finite-dimensional $C^*$-algebra factors, whereas this definition uses full complex
matrix algebras. See
`docs/paper-gaps/gnvw12_support_algebra_full_matrix_scope.tex`. -/
noncomputable def leftSupportAlgebra
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) :
    StarSubalgebra ℂ (Matrix m m ℂ) :=
  StarAlgebra.adjoin ℂ (leftCoefficientSet A)

/-- The right support algebra of a bipartite star-subalgebra, generated by all second-factor
coefficients.

This is the symmetric construction in GNVW, arXiv:0910.3675v2, lines 1211--1219, and
Schumacher--Werner, quant-ph/0405174, lines 1137--1169. The MPU application is
arXiv:1703.09188, Appendix, lines 2320--2334.

**Local fix (star-closed input):** `StarSubalgebra` records the necessary involution-closure
hypothesis omitted from the printed GNVW lemma; the QCA/MPU observable-algebra application
supplies it.

**Scope restriction (full matrix factors):** After that correction, the GNVW construction permits
arbitrary finite-dimensional $C^*$-algebra factors, whereas this definition uses full complex
matrix algebras. See `docs/paper-gaps/gnvw12_support_algebra_full_matrix_scope.tex`. -/
noncomputable def rightSupportAlgebra
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) :
    StarSubalgebra ℂ (Matrix n n ℂ) :=
  StarAlgebra.adjoin ℂ (rightCoefficientSet A)

/-- Every first-factor coefficient belongs to the left support algebra.

This is the generator inclusion in GNVW Lemma `lem:spp`, arXiv:0910.3675v2,
lines 1188--1191, following the coefficient construction in Schumacher--Werner,
quant-ph/0405174, lines 1137--1169. -/
theorem bipartite_slice_mem_left_support_algebra
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) {X} (hX : X ∈ A) (i j : n) :
    bipartiteSlice X i j ∈ leftSupportAlgebra A := by
  apply StarAlgebra.subset_adjoin
  exact ⟨X, hX, i, j, rfl⟩

/-- Every second-factor coefficient belongs to the right support algebra.

This is the symmetric generator inclusion in GNVW, arXiv:0910.3675v2, lines 1211--1219,
following Schumacher--Werner, quant-ph/0405174, lines 1137--1169. -/
theorem operator_block_mem_right_support_algebra
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) {X} (hX : X ∈ A) (i j : m) :
    operatorBlock X i j ∈ rightSupportAlgebra A := by
  apply StarAlgebra.subset_adjoin
  exact ⟨X, hX, i, j, rfl⟩

omit [Fintype m] [DecidableEq m] in
/-- Matrix-unit reconstruction from the coefficients on the first tensor factor:
$X = \sum_{i,j} X_{ij} \otimes e_{ij}$.

This is the concrete matrix-basis expansion in GNVW Lemma `lem:spp`, arXiv:0910.3675v2,
lines 1188--1191, and Schumacher--Werner, quant-ph/0405174, lines 1141--1156. -/
theorem eq_sum_left_coefficient_kronecker_single (X : Matrix (m × n) (m × n) ℂ) :
    X = ∑ i : n, ∑ j : n, bipartiteSlice X i j ⊗ₖ Matrix.single i j 1 := by
  apply Matrix.ext
  intro x y
  rcases x with ⟨a, i⟩
  rcases y with ⟨b, j⟩
  simp only [Matrix.sum_apply, Matrix.kroneckerMap_apply, bipartiteSlice_apply,
    Matrix.single_apply]
  simp_rw [ite_and]
  simp

omit [Fintype n] [DecidableEq n] in
/-- Matrix-unit reconstruction from the coefficients on the second tensor factor:
$X = \sum_{i,j} e_{ij} \otimes X_{ij}$.

This is the symmetric expansion in GNVW, arXiv:0910.3675v2, lines 1211--1219, and
Schumacher--Werner, quant-ph/0405174, lines 1141--1156. -/
theorem eq_sum_single_kronecker_right_coefficient (X : Matrix (m × n) (m × n) ℂ) :
    X = ∑ i : m, ∑ j : m, Matrix.single i j 1 ⊗ₖ operatorBlock X i j := by
  apply Matrix.ext
  intro x y
  rcases x with ⟨i, a⟩
  rcases y with ⟨j, b⟩
  simp only [Matrix.sum_apply, Matrix.kroneckerMap_apply, operatorBlock_apply,
    Matrix.single_apply]
  simp_rw [ite_and]
  simp

/-- A candidate star-subalgebra contains the left support algebra exactly when it contains every
first-factor coefficient of every element of the bipartite algebra.

This is the least-support assertion of GNVW Lemma `lem:spp`, arXiv:0910.3675v2,
lines 1181--1191, specialized to the matrix coefficients of Schumacher--Werner,
quant-ph/0405174, lines 1137--1169.

**Local fix (star-closed input):** `StarSubalgebra` records the necessary involution-closure
hypothesis omitted from the printed GNVW lemma; the QCA/MPU observable-algebra application
supplies it.

**Scope restriction (full matrix factors):** After that correction, GNVW leastness permits
arbitrary finite-dimensional $C^*$-algebra factors, whereas this theorem assumes full complex
matrix factors. See
`docs/paper-gaps/gnvw12_support_algebra_full_matrix_scope.tex`. -/
theorem left_support_algebra_le_iff
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ))
    (B : StarSubalgebra ℂ (Matrix m m ℂ)) :
    leftSupportAlgebra A ≤ B ↔
      ∀ ⦃X⦄, X ∈ A → ∀ i j : n, bipartiteSlice X i j ∈ B := by
  rw [leftSupportAlgebra, StarAlgebra.adjoin_le_iff]
  constructor
  · intro h X hX i j
    exact h ⟨X, hX, i, j, rfl⟩
  · rintro h a ⟨X, hX, i, j, rfl⟩
    exact h hX i j

/-- A candidate star-subalgebra contains the right support algebra exactly when it contains every
second-factor coefficient of every element of the bipartite algebra.

This is the symmetric least-support assertion in GNVW, arXiv:0910.3675v2,
lines 1211--1219, specialized to Schumacher--Werner, quant-ph/0405174,
lines 1137--1169.

**Local fix (star-closed input):** `StarSubalgebra` records the necessary involution-closure
hypothesis omitted from the printed GNVW lemma; the QCA/MPU observable-algebra application
supplies it.

**Scope restriction (full matrix factors):** After that correction, the GNVW construction permits
arbitrary finite-dimensional $C^*$-algebra factors, whereas this theorem assumes full complex
matrix factors. See
`docs/paper-gaps/gnvw12_support_algebra_full_matrix_scope.tex`. -/
theorem right_support_algebra_le_iff
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ))
    (B : StarSubalgebra ℂ (Matrix n n ℂ)) :
    rightSupportAlgebra A ≤ B ↔
      ∀ ⦃X⦄, X ∈ A → ∀ i j : m, operatorBlock X i j ∈ B := by
  rw [rightSupportAlgebra, StarAlgebra.adjoin_le_iff]
  constructor
  · intro h X hX i j
    exact h ⟨X, hX, i, j, rfl⟩
  · rintro h b ⟨X, hX, i, j, rfl⟩
    exact h hX i j

/-- The `Matrix.tensorSubmodule` formulation of left-support leastness.

For finite matrix factors, containment in $B \otimes M_n(\mathbb C)$ is exactly containment of all
left coefficients in $B$. This is GNVW Lemma `lem:spp`, arXiv:0910.3675v2,
lines 1181--1191.

**Local fix (star-closed input):** `StarSubalgebra` records the necessary involution-closure
hypothesis omitted from the printed GNVW lemma; the QCA/MPU observable-algebra application
supplies it.

**Scope restriction (full matrix factors):** After that correction, GNVW Lemma 7 permits
arbitrary finite-dimensional $C^*$-algebra factors, whereas this theorem assumes full complex
matrix factors. See
`docs/paper-gaps/gnvw12_support_algebra_full_matrix_scope.tex`. -/
theorem left_support_algebra_le_iff_le_tensor_submodule {p q : ℕ}
    (A : StarSubalgebra ℂ (Matrix (Fin p × Fin q) (Fin p × Fin q) ℂ))
    (B : StarSubalgebra ℂ (Matrix (Fin p) (Fin p) ℂ)) :
    leftSupportAlgebra A ≤ B ↔ A.toSubmodule ≤ Matrix.tensorSubmodule B.toSubmodule q := by
  rw [left_support_algebra_le_iff]
  constructor
  · intro h X hX
    rw [Matrix.mem_tensorSubmodule_iff]
    exact h hX
  · intro h X hX
    exact Matrix.mem_tensorSubmodule_iff.mp (h hX)

/-- The linear span of Kronecker products whose two factors belong to prescribed matrix
submodules.

This is the tensor-product subspace used in Schumacher--Werner equation `a2Supp`,
quant-ph/0405174, lines 1154--1168, and in the full-matrix specialization of GNVW Lemma
`lem:spp`, arXiv:0910.3675v2, lines 1211--1219. -/
def kroneckerSubmodule (S : Submodule ℂ (Matrix m m ℂ))
    (T : Submodule ℂ (Matrix n n ℂ)) :
    Submodule ℂ (Matrix (m × n) (m × n) ℂ) :=
  Submodule.map₂ Matrix.kroneckerBilinear S T

private theorem eq_sum_smul_single (B : Matrix n n ℂ) :
    B = ∑ i : n, ∑ j : n, B i j • Matrix.single i j 1 := by
  apply Matrix.ext
  intro i j
  simp only [Matrix.sum_apply, Matrix.smul_apply, smul_eq_mul, Matrix.single_apply]
  simp_rw [ite_and]
  simp

omit [Fintype m] [DecidableEq m] [Fintype n] [DecidableEq n] in
private theorem matrix_of_operatorBlock_apply_mem [Finite n]
    (S : Submodule ℂ (Matrix m m ℂ)) (X : Matrix (m × n) (m × n) ℂ)
    (hX : ∀ i j : n, bipartiteSlice X i j ∈ S)
    (g : Matrix n n ℂ →ₗ[ℂ] ℂ) :
    (fun p q ↦ g (operatorBlock X p q)) ∈ S := by
  classical
  let _ := Fintype.ofFinite n
  let Y : Matrix m m ℂ := fun p q ↦ g (operatorBlock X p q)
  have hY : Y = ∑ i : n, ∑ j : n, g (Matrix.single i j 1) • bipartiteSlice X i j := by
    apply Matrix.ext
    intro p q
    change g (operatorBlock X p q) = _
    rw [eq_sum_smul_single (operatorBlock X p q), map_sum]
    simp only [map_sum, LinearMap.map_smul, Matrix.sum_apply, Matrix.smul_apply, smul_eq_mul]
    congr 1
    ext i
    simp [operatorBlock, bipartiteSlice, mul_comm]
  change Y ∈ S
  rw [hY]
  exact Submodule.sum_mem S fun i _ ↦ Submodule.sum_mem S fun j _ ↦ S.smul_mem _ (hX i j)

omit [Fintype m] [DecidableEq m] [Fintype n] [DecidableEq n] in
/-- Membership in the Kronecker-product span is equivalent to simultaneous membership of all
left slices and all right blocks in the corresponding factor submodules.

This is the full-matrix coefficient form of Schumacher--Werner equation `a2supp`,
quant-ph/0405174, lines 1137--1156, and GNVW equation `a2Supp`, arXiv:0910.3675v2,
lines 1211--1219. -/
theorem mem_kroneckerSubmodule_iff [Finite n]
    (S : Submodule ℂ (Matrix m m ℂ)) (T : Submodule ℂ (Matrix n n ℂ))
    (X : Matrix (m × n) (m × n) ℂ) :
    X ∈ kroneckerSubmodule S T ↔
      (∀ i j : n, bipartiteSlice X i j ∈ S) ∧
        ∀ p q : m, operatorBlock X p q ∈ T := by
  classical
  let _ := Fintype.ofFinite n
  constructor
  · intro hX
    rw [kroneckerSubmodule, Submodule.map₂_eq_span_image2] at hX
    constructor
    · intro i j
      refine Submodule.span_induction
        (p := fun Z _ ↦ bipartiteSlice Z i j ∈ S) ?_ S.zero_mem ?_ ?_ hX
      · rintro Z ⟨A, hA, B, hB, rfl⟩
        have hslice : bipartiteSlice (A ⊗ₖ B) i j = B i j • A := by
          ext p q
          simp [bipartiteSlice, Matrix.smul_apply, mul_comm]
        change bipartiteSlice (A ⊗ₖ B) i j ∈ S
        rw [hslice]
        exact S.smul_mem _ hA
      · intro A B _ _ hA hB
        simpa only [bipartiteSlice_add] using S.add_mem hA hB
      · intro c A _ hA
        simpa only [bipartiteSlice_smul] using S.smul_mem c hA
    · intro p q
      refine Submodule.span_induction
        (p := fun Z _ ↦ operatorBlock Z p q ∈ T) ?_ T.zero_mem ?_ ?_ hX
      · rintro Z ⟨A, hA, B, hB, rfl⟩
        have hblock : operatorBlock (A ⊗ₖ B) p q = A p q • B := by
          ext i j
          simp [operatorBlock, Matrix.smul_apply]
        change operatorBlock (A ⊗ₖ B) p q ∈ T
        rw [hblock]
        exact T.smul_mem _ hB
      · intro A B _ _ hA hB
        apply T.add_mem hA hB
      · intro c A _ hA
        exact T.smul_mem c hA
  · rintro ⟨hleft, hright⟩
    let b := Module.finBasis ℂ T
    let coord : (Fin (Module.finrank ℂ T)) → T →ₗ[ℂ] ℂ :=
      fun k ↦ Finsupp.lapply k ∘ₗ b.repr
    choose g hg using fun k ↦ LinearMap.exists_extend (coord k)
    let A : Fin (Module.finrank ℂ T) → Matrix m m ℂ :=
      fun k p q ↦ g k (operatorBlock X p q)
    have hA (k : Fin (Module.finrank ℂ T)) : A k ∈ S :=
      matrix_of_operatorBlock_apply_mem S X hleft (g k)
    have hdecomp : X = ∑ k, A k ⊗ₖ (b k : Matrix n n ℂ) := by
      apply Matrix.ext
      rintro ⟨p, i⟩ ⟨q, j⟩
      simp only [Matrix.sum_apply, Matrix.kroneckerMap_apply]
      have hgk (k : Fin (Module.finrank ℂ T)) :
          g k (operatorBlock X p q) = b.repr ⟨operatorBlock X p q, hright p q⟩ k := by
        have hk := LinearMap.congr_fun (hg k) ⟨operatorBlock X p q, hright p q⟩
        exact hk
      simp_rw [show A = fun k p q ↦ g k (operatorBlock X p q) from rfl, hgk]
      have hbmat :
          (∑ k, b.repr ⟨operatorBlock X p q, hright p q⟩ k •
            (b k : Matrix n n ℂ)) = operatorBlock X p q := by
        have hb := congrArg Subtype.val (b.sum_repr ⟨operatorBlock X p q, hright p q⟩)
        simpa only [Submodule.coe_sum, Submodule.coe_smul, Submodule.coe_mk] using hb
      have hbentry := congrArg (fun C : Matrix n n ℂ ↦ C i j) hbmat
      simpa only [Matrix.sum_apply, Matrix.smul_apply, smul_eq_mul, operatorBlock_apply]
        using hbentry.symm
    rw [hdecomp]
    exact Submodule.sum_mem _ fun k _ ↦
      Submodule.apply_mem_map₂ Matrix.kroneckerBilinear (hA k) (b k).property

/-- The Kronecker span with an unrestricted right factor is the existing one-sided
`Matrix.tensorSubmodule`.

Thus allowing every matrix in the right factor recovers the one-sided tensor submodule. This is
the first-factor containment in GNVW Lemma `lem:spp`, arXiv:0910.3675v2,
lines 1181--1191. -/
theorem kroneckerSubmodule_top_eq_tensorSubmodule {p q : ℕ}
    (S : Submodule ℂ (Matrix (Fin p) (Fin p) ℂ)) :
    kroneckerSubmodule S ⊤ = Matrix.tensorSubmodule S q := by
  ext X
  rw [mem_kroneckerSubmodule_iff, Matrix.mem_tensorSubmodule_iff]
  simp

/-- Right-support leastness is equivalently containment in the right-oriented Kronecker
span $M_m(\mathbb C) \otimes B$.

This is the symmetric one-sided containment of GNVW, arXiv:0910.3675v2, lines 1211--1219,
and uses the same Kronecker span whose left-oriented specialization is
`Matrix.tensorSubmodule`.

**Local fix (star-closed input):** `StarSubalgebra` records the necessary involution-closure
hypothesis omitted from the printed GNVW lemma; the QCA/MPU observable-algebra application
supplies it.

**Scope restriction (full matrix factors):** After that correction, the GNVW construction permits
arbitrary finite-dimensional $C^*$-algebra factors, whereas this theorem assumes full complex
matrix factors. See
`docs/paper-gaps/gnvw12_support_algebra_full_matrix_scope.tex`. -/
theorem right_support_algebra_le_iff_le_kronecker_submodule
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ))
    (B : StarSubalgebra ℂ (Matrix n n ℂ)) :
    rightSupportAlgebra A ≤ B ↔ A.toSubmodule ≤ kroneckerSubmodule ⊤ B.toSubmodule := by
  rw [right_support_algebra_le_iff]
  constructor
  · intro h X hX
    rw [mem_kroneckerSubmodule_iff]
    exact ⟨fun i j ↦ Submodule.mem_top, h hX⟩
  · intro h X hX
    exact (mem_kroneckerSubmodule_iff _ _ _).mp (h hX) |>.2

/-- Every element of a bipartite star-subalgebra lies in the Kronecker span of its left and right
support algebras:
$\mathcal A \subset \operatorname{Spp}_L(\mathcal A) \otimes
\operatorname{Spp}_R(\mathcal A)$.

This is the literal full-matrix specialization of equation `a2Supp` in Schumacher--Werner,
quant-ph/0405174, lines 1161--1168, and GNVW, arXiv:0910.3675v2, lines 1211--1219. The MPU
paper applies these support algebras to $\mathcal R_{2x}$ at arXiv:1703.09188, Appendix,
lines 2313--2334.

**Local fix (star-closed input):** `StarSubalgebra` records the necessary involution-closure
hypothesis omitted from the printed GNVW lemma; the QCA/MPU observable-algebra application
supplies it.

**Scope restriction (full matrix factors):** After that correction, GNVW equation (22) permits
arbitrary finite-dimensional $C^*$-algebra factors, whereas this theorem assumes full complex
matrix factors. See
`docs/paper-gaps/gnvw12_support_algebra_full_matrix_scope.tex`. -/
theorem le_support_kroneckerSubmodule
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) :
    A.toSubmodule ≤
      kroneckerSubmodule (leftSupportAlgebra A).toSubmodule
        (rightSupportAlgebra A).toSubmodule := by
  intro X hX
  rw [mem_kroneckerSubmodule_iff]
  exact ⟨bipartite_slice_mem_left_support_algebra A hX,
    operator_block_mem_right_support_algebra A hX⟩

/-- Left Kronecker commutation is equivalent to commutation with every first-factor coefficient.

This is the coefficientwise commutator expansion used in the proof of GNVW Lemma `lem:spp`,
arXiv:0910.3675v2, lines 1197--1208. Compare Schumacher--Werner Lemma `sppcomm`,
quant-ph/0405174, lines 1174--1194. -/
theorem commute_left_kronecker_embed_iff (B : Matrix m m ℂ)
    (X : Matrix (m × n) (m × n) ℂ) :
    Commute (leftKroneckerEmbed (n := n) B) X ↔
      ∀ i j : n, Commute B (bipartiteSlice X i j) := by
  constructor
  · intro h i j
    rw [commute_iff_eq]
    ext a b
    have hab := congrArg (fun Y : Matrix (m × n) (m × n) ℂ ↦ Y (a, i) (b, j)) h.eq
    simpa [leftKroneckerEmbed_apply, Matrix.mul_apply, bipartiteSlice,
      Fintype.sum_prod_type, Matrix.one_apply] using hab
  · intro h
    rw [commute_iff_eq]
    ext ⟨a, i⟩ ⟨b, j⟩
    have hab := congrArg (fun Y : Matrix m m ℂ ↦ Y a b) (h i j).eq
    simpa [leftKroneckerEmbed_apply, Matrix.mul_apply, bipartiteSlice,
      Fintype.sum_prod_type, Matrix.one_apply] using hab

/-- Right Kronecker commutation is equivalent to commutation with every second-factor coefficient.

This is the symmetric coefficientwise commutator expansion of GNVW Lemma `lem:spp`,
arXiv:0910.3675v2, lines 1197--1208. Compare Schumacher--Werner Lemma `sppcomm`,
quant-ph/0405174, lines 1174--1194. -/
theorem commute_right_kronecker_embed_iff (B : Matrix n n ℂ)
    (X : Matrix (m × n) (m × n) ℂ) :
    Commute (rightKroneckerEmbed (m := m) B) X ↔
      ∀ i j : m, Commute B (operatorBlock X i j) := by
  constructor
  · intro h i j
    rw [commute_iff_eq]
    ext a b
    have hab := congrArg (fun Y : Matrix (m × n) (m × n) ℂ ↦ Y (i, a) (j, b)) h.eq
    simpa [rightKroneckerEmbed_apply, Matrix.mul_apply, operatorBlock,
      Fintype.sum_prod_type, Matrix.one_apply] using hab
  · intro h
    rw [commute_iff_eq]
    ext ⟨i, a⟩ ⟨j, b⟩
    have hab := congrArg (fun Y : Matrix n n ℂ ↦ Y a b) (h i j).eq
    simpa [rightKroneckerEmbed_apply, Matrix.mul_apply, operatorBlock,
      Fintype.sum_prod_type, Matrix.one_apply] using hab

private theorem mem_left_support_algebra_centralizer_iff
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) (B : Matrix m m ℂ) :
    B ∈ (leftSupportAlgebra A : Set (Matrix m m ℂ)).centralizer ↔
      ∀ ⦃X⦄, X ∈ A → ∀ i j : n, Commute B (bipartiteSlice X i j) := by
  constructor
  · intro h X hX i j
    exact (Set.mem_centralizer_iff.mp h _ (bipartite_slice_mem_left_support_algebra A hX i j)).symm
  · intro h
    rw [Set.mem_centralizer_iff]
    intro C hC
    have hstar : star (leftCoefficientSet A) ⊆ leftCoefficientSet A := by
      intro D hD
      rw [Set.mem_star] at hD
      obtain ⟨X, hX, i, j, hDX⟩ := hD
      refine ⟨Xᴴ, A.star_mem' hX, j, i, ?_⟩
      rw [bipartiteSlice_conjTranspose, ← star_eq_conjTranspose, hDX, star_star]
    have hgenerators : leftCoefficientSet A ∪ star (leftCoefficientSet A) ⊆
        (Subalgebra.centralizer ℂ {B} : Set (Matrix m m ℂ)) := by
      intro D hD
      change D ∈ ({B} : Set (Matrix m m ℂ)).centralizer
      rw [Set.mem_centralizer_iff]
      intro E hE
      rw [Set.mem_singleton_iff.mp hE]
      have hcoeff : D ∈ leftCoefficientSet A :=
        (Set.mem_union _ _ _).mp hD |>.elim id (fun hDstar ↦ hstar hDstar)
      obtain ⟨X, hX, i, j, rfl⟩ := hcoeff
      exact (h hX i j).eq
    have hle : (leftSupportAlgebra A).toSubalgebra ≤ Subalgebra.centralizer ℂ {B} := by
      rw [leftSupportAlgebra, StarAlgebra.adjoin_toSubalgebra]
      exact Algebra.adjoin_le hgenerators
    have hCB : C ∈ ({B} : Set (Matrix m m ℂ)).centralizer := hle hC
    exact (Set.mem_centralizer_iff.mp hCB B (Set.mem_singleton B)).symm

private theorem mem_right_support_algebra_centralizer_iff
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) (B : Matrix n n ℂ) :
    B ∈ (rightSupportAlgebra A : Set (Matrix n n ℂ)).centralizer ↔
      ∀ ⦃X⦄, X ∈ A → ∀ i j : m, Commute B (operatorBlock X i j) := by
  constructor
  · intro h X hX i j
    exact (Set.mem_centralizer_iff.mp h _ (operator_block_mem_right_support_algebra A hX i j)).symm
  · intro h
    rw [Set.mem_centralizer_iff]
    intro C hC
    have hstar : star (rightCoefficientSet A) ⊆ rightCoefficientSet A := by
      intro D hD
      rw [Set.mem_star] at hD
      obtain ⟨X, hX, i, j, hDX⟩ := hD
      refine ⟨Xᴴ, A.star_mem' hX, j, i, ?_⟩
      rw [operatorBlock_conjTranspose, ← star_eq_conjTranspose, hDX, star_star]
    have hgenerators : rightCoefficientSet A ∪ star (rightCoefficientSet A) ⊆
        (Subalgebra.centralizer ℂ {B} : Set (Matrix n n ℂ)) := by
      intro D hD
      change D ∈ ({B} : Set (Matrix n n ℂ)).centralizer
      rw [Set.mem_centralizer_iff]
      intro E hE
      rw [Set.mem_singleton_iff.mp hE]
      have hcoeff : D ∈ rightCoefficientSet A :=
        (Set.mem_union _ _ _).mp hD |>.elim id (fun hDstar ↦ hstar hDstar)
      obtain ⟨X, hX, i, j, rfl⟩ := hcoeff
      exact (h hX i j).eq
    have hle : (rightSupportAlgebra A).toSubalgebra ≤ Subalgebra.centralizer ℂ {B} := by
      rw [rightSupportAlgebra, StarAlgebra.adjoin_toSubalgebra]
      exact Algebra.adjoin_le hgenerators
    have hCB : C ∈ ({B} : Set (Matrix n n ℂ)).centralizer := hle hC
    exact (Set.mem_centralizer_iff.mp hCB B (Set.mem_singleton B)).symm

/-- The left Kronecker embedding of a matrix commutes with the original bipartite algebra exactly
when the matrix commutes with the left support algebra.

This is the commutant characterization in GNVW Lemma `lem:spp`, arXiv:0910.3675v2,
lines 1192--1208. The proof is the source's coefficientwise commutator expansion; compare
Schumacher--Werner, quant-ph/0405174, lines 1174--1194.

**Local fix (star-closed input):** `StarSubalgebra` records the necessary involution-closure
hypothesis omitted from the printed GNVW lemma; the QCA/MPU observable-algebra application
supplies it.

**Scope restriction (full matrix factors):** After that correction, the GNVW commutant
characterization permits arbitrary finite-dimensional $C^*$-algebra factors, whereas this theorem
assumes full complex matrix factors. See
`docs/paper-gaps/gnvw12_support_algebra_full_matrix_scope.tex`. -/
theorem left_kronecker_embed_mem_centralizer_iff
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) (B : Matrix m m ℂ) :
    leftKroneckerEmbed (n := n) B ∈ (A : Set _).centralizer ↔
      B ∈ (leftSupportAlgebra A : Set _).centralizer := by
  rw [mem_left_support_algebra_centralizer_iff]
  constructor
  · intro h X hX
    have hcomm := (Set.mem_centralizer_iff.mp h X hX).symm
    exact (commute_left_kronecker_embed_iff B X).mp hcomm
  · intro h X hX
    exact ((commute_left_kronecker_embed_iff B X).mpr (h hX)).eq.symm

/-- The right Kronecker embedding of a matrix commutes with the original bipartite algebra
exactly when the matrix commutes with the right support algebra.

This is the symmetric commutant characterization of GNVW Lemma `lem:spp`,
arXiv:0910.3675v2, lines 1192--1208; compare Schumacher--Werner,
quant-ph/0405174, lines 1174--1194.

**Local fix (star-closed input):** `StarSubalgebra` records the necessary involution-closure
hypothesis omitted from the printed GNVW lemma; the QCA/MPU observable-algebra application
supplies it.

**Scope restriction (full matrix factors):** After that correction, the GNVW commutant
characterization permits arbitrary finite-dimensional $C^*$-algebra factors, whereas this theorem
assumes full complex matrix factors. See
`docs/paper-gaps/gnvw12_support_algebra_full_matrix_scope.tex`. -/
theorem right_kronecker_embed_mem_centralizer_iff
    (A : StarSubalgebra ℂ (Matrix (m × n) (m × n) ℂ)) (B : Matrix n n ℂ) :
    rightKroneckerEmbed (m := m) B ∈ (A : Set _).centralizer ↔
      B ∈ (rightSupportAlgebra A : Set _).centralizer := by
  rw [mem_right_support_algebra_centralizer_iff]
  constructor
  · intro h X hX
    have hcomm := (Set.mem_centralizer_iff.mp h X hX).symm
    exact (commute_right_kronecker_embed_iff B X).mp hcomm
  · intro h X hX
    exact ((commute_right_kronecker_embed_iff B X).mpr (h hX)).eq.symm

end Matrix
