/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import QICLean.Algebra.CommutingOverlappingDecomp
import TNLean.QCA.BipartiteSupportAlgebra

/-!
# Commutation of overlapping support algebras

Let `A₁` be a star-subalgebra on the first two factors and `A₂` a star-subalgebra on
the last two factors. If their natural lifts commute elementwise on the three-factor
space, then the right support algebra of `A₁` commutes with the left support algebra
of `A₂` on the common factor. The proof extracts the outer-factor coefficients and
then passes to the two generated star-subalgebras.

**Local fix (star-closed input):** Schumacher--Werner define the ordinary algebra
generated by the coefficient support and obtain adjoint closure from adjoint closure
of the observable input. GNVW instead define the generated C*-algebra but state the
input only as a subalgebra. For C*-generated supports, involution closure of the input
is necessary. The formal statement therefore takes star-subalgebras, as supplied by
the QCA and MPU applications. This correction is proved and documented in
`docs/paper-gaps/gnvw12_support_algebra_star_closure.tex`.

**Local fix (outer-factor basis):** The printed coefficient proofs in both
Schumacher--Werner and GNVW place the basis elements $e'_\nu$ in the middle factor.
The expansion of the second operator and the assertion that $e_\mu \otimes e'_\nu$ is a basis
of the two outer factors force $e'_\nu$ to belong to the third factor. The third-factor
indices in this module implement that correction. It is documented in
`docs/paper-gaps/gnvw12_support_algebra_outer_factor_basis.tex`.

**Scope restriction (full matrix factors):** The statement below treats full complex
matrix algebras. Schumacher--Werner and GNVW allow arbitrary finite-dimensional
C*-algebra factors. Full matrix factors suffice for the MPU application because its
one-site observable algebras are full matrix algebras. The general-factor extension
remains open and is documented in
`docs/paper-gaps/gnvw12_support_algebra_full_matrix_scope.tex`.

## Main statement

* `Matrix.supportAlgebras_commute_of_overlappingLifts_commute` proves pairwise
  commutation of the two support algebras on the common factor.

## References

* Schumacher--Werner, quant-ph/0405174, Section 4.3, Lemma `sppcomm`,
  lines 1174--1194.
* Gross--Nesme--Vogts--Werner, arXiv:0910.3675v2, Section 7.1, Lemma `sppcomm`,
  lines 1221--1246.
* Cirac--Pérez-García--Schuch--Verstraete, arXiv:1703.09188, Appendix,
  lines 2300--2306 and 2313--2334.
-/

namespace Matrix

variable {a b c : Type*}
variable [Fintype a] [Fintype b] [Fintype c]
variable [DecidableEq a] [DecidableEq b] [DecidableEq c]

/-- If star-subalgebras on two overlapping pairs of full complex matrix factors
commute after their natural three-factor lifts, then their support algebras on the
common factor commute elementwise.

This is the full-matrix, star-closed specialization of Schumacher--Werner Lemma
`sppcomm`, quant-ph/0405174, lines 1174--1194, and GNVW Lemma `sppcomm`,
arXiv:0910.3675v2, lines 1221--1246. The MPU application is
arXiv:1703.09188, lines 2300--2306 and 2313--2334. -/
theorem supportAlgebras_commute_of_overlappingLifts_commute
    (A₁ : StarSubalgebra ℂ (Matrix (a × b) (a × b) ℂ))
    (A₂ : StarSubalgebra ℂ (Matrix (b × c) (b × c) ℂ))
    (hComm : ∀ ⦃X⦄, X ∈ A₁ → ∀ ⦃Y⦄, Y ∈ A₂ →
      leftOverlappingLift X * rightOverlappingLift Y =
      rightOverlappingLift Y * leftOverlappingLift X) :
    ∀ R ∈ rightSupportAlgebra A₁, ∀ L ∈ leftSupportAlgebra A₂,
      R * L = L * R := by
  have hRight :
      rightSupportAlgebra A₁ ≤
        StarSubalgebra.centralizer ℂ (leftCoefficientSet A₂) := by
    rw [rightSupportAlgebra, StarAlgebra.adjoin_le_iff]
    rintro R ⟨X, hX, i, i', rfl⟩
    change operatorBlock X i i' ∈
      StarSubalgebra.centralizer ℂ (leftCoefficientSet A₂)
    rw [StarSubalgebra.mem_centralizer_iff]
    rintro L ⟨Y, hY, k, k', rfl⟩
    constructor
    · exact (middleSlices_commute_of_overlappingLifts_commute
        X Y (hComm hX hY) i i' k k').symm
    · have hAdjoint := (middleSlices_commute_of_overlappingLifts_commute
        X Yᴴ (hComm hX (A₂.star_mem' hY)) i i' k' k).symm
      exact hAdjoint
  have hLeft :
      leftSupportAlgebra A₂ ≤
        StarSubalgebra.centralizer ℂ (rightSupportAlgebra A₁ : Set (Matrix b b ℂ)) := by
    rw [leftSupportAlgebra, StarAlgebra.adjoin_le_iff]
    rintro L ⟨Y, hY, k, k', rfl⟩
    change bipartiteSlice Y k k' ∈
      StarSubalgebra.centralizer ℂ (rightSupportAlgebra A₁ : Set (Matrix b b ℂ))
    rw [StarSubalgebra.mem_centralizer_iff]
    intro R hR
    constructor
    · exact ((StarSubalgebra.mem_centralizer_iff ℂ).mp (hRight hR)
        (bipartiteSlice Y k k') ⟨Y, hY, k, k', rfl⟩).1.symm
    · exact ((StarSubalgebra.mem_centralizer_iff ℂ).mp
        (hRight ((rightSupportAlgebra A₁).star_mem' hR))
        (bipartiteSlice Y k k') ⟨Y, hY, k, k', rfl⟩).1.symm
  intro R hR L hL
  exact ((StarSubalgebra.mem_centralizer_iff ℂ).mp (hLeft hL) R hR).1

end Matrix
