/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import TNLean.MPS.Examples.CZX.CZXSquare
import TNLean.MPS.Examples.MultiBlock.StackedPairGauge
import TNLean.MPS.FundamentalTheorem.Reduction.Splitting

/-!
# Nonsplitting of the stacked CZX square

The undecorated CZX operator satisfies `U_L² = (-1)^L I` for `L > 0`.
Its stacked bond-four tensor therefore has the word traces of the weighted bond-one
identity tensor `-δ`. The explicit compression in
`Notes/OpenProblemsTN/strategies/p5_asymmetric_compression_theorem.tex`, `ex:p5ft-czx`,
realizes this equality for every nonempty word. Both sitewise intertwiner spaces with
`-δ` vanish, so the compression does not split into a biorthogonal sitewise pair.

The splitting criterion then shows that the virtual algebra generated by the stacked
letters is not closed under conjugate transposition in these coordinates. This is an
algebraic nonsplitting result, not an identification of star-closure failure with the
CZX anomaly. A three-cocycle anomaly requires a separate fusion-associator calculation;
no such calculation is performed here.

## Main results

* `CZXCompression.czxSquareTarget_isNormal`: the single target of Example D is normal.
* `CZXCompression.czxSquare_not_starClosed`: the virtual algebra of the stacked tensor is not
  closed under conjugate transposition.
-/

open scoped Matrix

namespace CZXCompression

open MPSTensor

private theorem negIdentityIntMPS_unit (x y : Fin 1) :
    negIdentityIntMPS ((fun _ _ => 0) x y) =
      ((fun _ _ => -1 : Fin 1 → Fin 1 → ℤ) x y) • Matrix.single x y 1 := by
  revert x y
  decide

/-- **The single target of Example D is normal**: its bond dimension is one and the letter `0`
acts by the nonzero scalar `-1`, so the one-site matrices already span the whole `1 x 1` matrix
algebra. -/
theorem czxSquareTarget_isNormal (s : Unit) : Kraus.IsNormal (czxSquareTarget s) :=
  P6Compression.isNormal_of_single_eq_smul negIdentityIntMPS (c := 1) one_ne_zero
    (fun a => by rw [czxSquareTarget_eq, one_smul]) (fun _ _ => 0) (fun _ _ => -1)
    (fun _ _ => by norm_num) negIdentityIntMPS_unit

/-- The virtual algebra of the stacked square is not star closed in these coordinates.
A star-closed algebra would give a nonzero sitewise right intertwiner with the normal
target `-δ`, contradicting `czxSquare_right_intertwiner_eq_zero`. -/
theorem czxSquare_not_starClosed :
    ¬ ∀ i, (czxSquare i)ᴴ ∈ Algebra.adjoin ℂ (Set.range czxSquare) := by
  refine MPSTensor.not_forall_conjTranspose_mem_adjoin_of_forall_right_intertwiner_eq_zero
    squareSlots czxSquareTarget (fun s _ => czxSquareTarget_isNormal s)
    (fun _ _ => Nat.one_pos) czxSquare
    (fun w hw => czxSquare_compression.trace_evalWord_eq_sum w hw) squareSlot ?_
  intro X hX
  have hv : ∀ i, czxSquare i *ᵥ (fun x => X x 0) =
      czxSquareTarget () i 0 0 • (fun x => X x 0) := by
    intro i
    funext x
    have h := congrFun (congrFun (hX i) x) 0
    simp only [Matrix.mul_apply, Fin.sum_univ_one] at h
    simp only [Matrix.mulVec, dotProduct, Pi.smul_apply, smul_eq_mul]
    exact h.trans (mul_comm _ _)
  have hX0 := czxSquare_right_intertwiner_eq_zero (fun x => X x 0) hv
  ext x j
  obtain rfl : j = 0 := Subsingleton.elim j 0
  exact congrFun hX0 x

end CZXCompression
