/-
Copyright (c) 2026 Sirui Lu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import TNLean.MPS.Examples.CZX.CZXTensor
import TNLean.MPS.FundamentalTheorem.Reduction.MultiBlockTrace

/-!
# CZX plus identity: a non-simple fusion with length-oscillating integer coefficients

**Source.** Construction of this development. The input is the CZX operator of the review,
arXiv:2011.12127, Appendix A, "The CZX MPU", `Papers/2011.12127/TN-Review-main.tex`
lines 2582–2601, whose square is `(-1)^N I`; the family `id + U_L` and its compression datum
do not occur in the review or in Chen–Liu–Wen (arXiv:1106.4752).

**Formalized here.** Adding the identity to the CZX symmetry gives the non-simple family
`O_L = id + U_L`, generated by the bond-three tensor `N = δ ⊕ M`. Its square is
`O_L² = (1 + (-1)^L) id + 2 U_L`: an operator family whose identity coefficient oscillates
with the length while remaining an integer. The stacked product tensor of bond dimension
nine compresses onto the four blocks `δ`, `-δ`, `M`, `M`, with three zero slots left over.
The oscillating coefficient is the length-`L` power sum of the weight multiset `{+1, -1}`,
and each weighted copy carries its own compression pair.

Because each letter of `N` is block diagonal for the splitting `ℂ³ = ℂ ⊕ ℂ²`, each letter of
the stacked tensor is block diagonal for the four-fold splitting of `ℂ³ ⊗ ℂ³`. Three of those
four summands are already simple, carrying `δ`, `M` and `M`; the fourth is the stacked
tensor of `CZXSquare`, whose flag contributes the weight `-1` together with the three zero
slots.

## Main results

* `CZXCompression.czxPlusIdentity_compression`: the multi-block compression datum of the
  multi-block trace theorem (`MultiBlockTrace`) with four target slots and three zero slots.
* `CZXCompression.czxPlusIdentity_trace_evalWord`: the word-trace identity
  `O_L² = (1 + (-1)^L) id + 2 U_L`.
* `CZXCompression.czxPlusIdentity_isReduction`: the biorthogonal compression pair of each of
  the four slots.
* `CZXCompression.czxPlusIdentity_dim_eq`: the dimension count `9 = 1 + 1 + 2 + 2 + 3`.
* `CZXCompression.czxPlusIdentity_evalWord_remainder_eq_zero`: the remainder of the
  compression is nilpotent of length seven.

## References

- [arXiv:2011.12127](https://arxiv.org/abs/2011.12127) -- J. I. Cirac, D. Pérez-García,
  N. Schuch, F. Verstraete, *Matrix product states and projected entangled pair states:
  Concepts, symmetries, theorems*
- [arXiv:1106.4752](https://arxiv.org/abs/1106.4752) -- X. Chen, Z.-X. Liu, X.-G. Wen,
  *2D symmetry protected topological orders and their protected gapless edge excitations*

## Provenance

The family, its compression datum and the exact-arithmetic certificates were first recorded
in `Notes/OpenProblemsTN/strategies/p5_asymmetric_compression_theorem.tex`, Example E
(`ex:p5ft-oscillating`, lines 1038–1075); they are verification records, not the source.
-/

noncomputable section

open scoped Matrix

namespace CZXCompression

open MPSTensor

/-! ### The bond-three tensor and its square -/

/-- The integer tensor `N^{ij} = δ^{ij} ⊕ M^{ij}` of bond dimension three, generating
`O_L = id + U_L` (P5 note, `ex:p5ft-oscillating`). -/
def plusIntTensor : Fin 2 → Fin 2 → Matrix (Fin 3) (Fin 3) ℤ
  | 0, 0 => !![1, 0, 0; 0, 0, 0; 0, 0, 0]
  | 0, 1 => !![0, 0, 0; 0, 0, 1; 0, 0, -1]
  | 1, 0 => !![0, 0, 0; 0, 1, 0; 0, 1, 0]
  | 1, 1 => !![1, 0, 0; 0, 0, 0; 0, 0, 0]

/-- The bond-three tensor generating `O_L = id + U_L`. -/
def plusTensor : MPOTensor 2 3 := fun i j => complexOfInt (plusIntTensor i j)

/-- The stacked product tensor of Example E, of bond dimension nine. -/
def czxPlusIdentity : MPSTensor 4 9 := (MPOTensor.mulTensor plusTensor plusTensor).toMPSTensor

/-- The integer matrices of the stacked product tensor of Example E. -/
def czxPlusIdentityInt : Fin 4 → Matrix (Fin 9) (Fin 9) ℤ
  | 0 =>
    !![1, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 1, 0;
       0, 0, 0, 0, 0, 0, 0, 1, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, -1, 0;
       0, 0, 0, 0, 0, 0, 0, -1, 0]
  | 1 =>
    !![0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 1, 0, 0, 0, 0, 0, 0;
       0, 0, -1, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 1, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, -1, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0]
  | 2 =>
    !![0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 1, 0, 0, 0, 0, 0, 0, 0;
       0, 1, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 1, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 1, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0]
  | 3 =>
    !![1, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 1, 0, 0, 0;
       0, 0, 0, 0, 0, -1, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 1, 0, 0, 0;
       0, 0, 0, 0, 0, -1, 0, 0, 0]

theorem czxPlusIdentity_eq (a : Fin 4) :
    czxPlusIdentity a = complexOfInt (czxPlusIdentityInt a) := by
  have h : czxPlusIdentity a = complexOfInt (mulIntTensor plusIntTensor plusIntTensor
      (Fin.divNat (m := 2) (n := 2) a) (Fin.modNat (m := 2) (n := 2) a)) :=
    mulTensor_complexOfRing _ plusIntTensor plusIntTensor _ _
  have hint : ∀ b : Fin 4, mulIntTensor plusIntTensor plusIntTensor
      (Fin.divNat (m := 2) (n := 2) b) (Fin.modNat (m := 2) (n := 2) b) =
        czxPlusIdentityInt b := by
    decide
  rw [h, hint]

/-! ### The four target blocks -/

/-- The bond dimensions of the four target slots of Example E. -/
def plusBlockDim : Fin 4 → ℕ
  | 0 => 1
  | 1 => 1
  | 2 => 2
  | 3 => 2

/-- The four target blocks of Example E: the bond-one identity tensor with weight `+1`, the
same tensor with weight `-1`, and the CZX block twice (P5 note, `ex:p5ft-oscillating`). -/
def plusTargets : (s : Fin 4) → MPSTensor 4 (plusBlockDim s)
  | 0 => identityMPS
  | 1 => (-1 : ℂ) • identityMPS
  | 2 => czxMPS
  | 3 => czxMPS

/-- The integer matrices of the four target blocks. -/
def plusTargetsInt :
    (s : Fin 4) → Fin 4 → Matrix (Fin (plusBlockDim s)) (Fin (plusBlockDim s)) ℤ
  | 0 => identityIntMPS
  | 1 => negIdentityIntMPS
  | 2 => czxIntMPS
  | 3 => czxIntMPS

theorem plusTargets_eq (s a : Fin 4) :
    plusTargets s a = complexOfInt (plusTargetsInt s a) := by
  fin_cases s
  exacts [identityMPS_eq a, negIdentityMPS_eq a, czxMPS_eq a, czxMPS_eq a]

/-! ### The flag -/

/-- The change of bond coordinates of Example E. -/
def plusGaugeInt : Matrix (Fin 9) (Fin 9) ℤ :=
  !![1, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 1, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 1, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 1, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 1, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 1, -1;
     0, 0, 0, 0, 0, 0, 0, -1, 0;
     0, 0, 0, 0, 1, 0, 0, 0, 1;
     0, 0, 0, 0, 0, 1, 0, 1, 0]

/-- The inverse change of bond coordinates of Example E; its columns are the basis adapted to
the flag. -/
def plusGaugeInvInt : Matrix (Fin 9) (Fin 9) ℤ :=
  !![1, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 1, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 1, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 1, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 1, 1, 1, 0;
     0, 0, 0, 0, 0, 0, 1, 0, 1;
     0, 0, 0, 0, 1, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, -1, 0, 0;
     0, 0, 0, 0, 0, -1, -1, 0, 0]

theorem plusGauge_mul_inv : plusGaugeInt * plusGaugeInvInt = 1 := by decide

theorem plusGaugeInv_mul : plusGaugeInvInt * plusGaugeInt = 1 := by decide

theorem plusGaugeComplex_mul_inv :
    complexOfInt plusGaugeInt * complexOfInt plusGaugeInvInt = 1 :=
  complexOfRing_mul_eq_one _ plusGauge_mul_inv

theorem plusGaugeComplex_inv_mul :
    complexOfInt plusGaugeInvInt * complexOfInt plusGaugeInt = 1 :=
  complexOfRing_mul_eq_one _ plusGaugeInv_mul

/-- The slots of Example E: all four target blocks. -/
abbrev plusSlots : Finset (Fin 4) := Finset.univ

/-- The block ordering of Example E: the identity block, the two CZX blocks, a zero slot, the
weighted identity block and two more zero slots. -/
def plusOrd : BlockIndex plusSlots 3 ≃ Fin 7 where
  toFun := Sum.elim (fun s => ![0, 4, 1, 2] s.1) ![3, 5, 6]
  invFun
    | 0 => Sum.inl ⟨0, Finset.mem_univ 0⟩
    | 1 => Sum.inl ⟨2, Finset.mem_univ 2⟩
    | 2 => Sum.inl ⟨3, Finset.mem_univ 3⟩
    | 3 => Sum.inr 0
    | 4 => Sum.inl ⟨1, Finset.mem_univ 1⟩
    | 5 => Sum.inr 1
    | 6 => Sum.inr 2
  left_inv := by decide
  right_inv := by decide

/-- The position in the flag of the first coordinate of each block of Example E. -/
def plusOffset : BlockIndex plusSlots 3 → ℕ :=
  Sum.elim (fun s => ![0, 6, 1, 3] s.1) ![5, 7, 8]

/-- The bond coordinate attached to a graded coordinate of Example E. -/
def plusCoordNat (x : BlockSpace plusBlockDim plusSlots 3) : ℕ := plusOffset x.1 + (x.2 : ℕ)

theorem plusCoordNat_lt (x : BlockSpace plusBlockDim plusSlots 3) : plusCoordNat x < 9 := by
  revert x
  decide

/-- The labelling of the nine bond coordinates of Example E by the graded block space. -/
def plusTau : BlockSpace plusBlockDim plusSlots 3 ≃ Fin 9 where
  toFun x := ⟨plusCoordNat x, plusCoordNat_lt x⟩
  invFun
    | 0 => ⟨Sum.inl ⟨0, Finset.mem_univ 0⟩, ⟨0, by decide⟩⟩
    | 1 => ⟨Sum.inl ⟨2, Finset.mem_univ 2⟩, ⟨0, by decide⟩⟩
    | 2 => ⟨Sum.inl ⟨2, Finset.mem_univ 2⟩, ⟨1, by decide⟩⟩
    | 3 => ⟨Sum.inl ⟨3, Finset.mem_univ 3⟩, ⟨0, by decide⟩⟩
    | 4 => ⟨Sum.inl ⟨3, Finset.mem_univ 3⟩, ⟨1, by decide⟩⟩
    | 5 => ⟨Sum.inr 0, ⟨0, by decide⟩⟩
    | 6 => ⟨Sum.inl ⟨1, Finset.mem_univ 1⟩, ⟨0, by decide⟩⟩
    | 7 => ⟨Sum.inr 1, ⟨0, by decide⟩⟩
    | 8 => ⟨Sum.inr 2, ⟨0, by decide⟩⟩
  left_inv := by decide
  right_inv := by decide

/-- The gauge of Example E. -/
def plusGauge : (Fin 9 → ℂ) ≃ₗ[ℂ] (BlockSpace plusBlockDim plusSlots 3 → ℂ) :=
  gaugeOfMatrix plusTau (complexOfInt plusGaugeInt) (complexOfInt plusGaugeInvInt)
    plusGaugeComplex_mul_inv plusGaugeComplex_inv_mul

/-- The letters of Example E in the block coordinates: block upper triangular, with the four
target blocks on the diagonal and zero on the three remaining slots. -/
def plusConjInt : Fin 4 → Matrix (Fin 9) (Fin 9) ℤ
  | 0 =>
    !![1, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, -1, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0]
  | 1 =>
    !![0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 1, 0, 0, 0, 0, 0, 0;
       0, 0, -1, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 1, 0, 0, 0, 0;
       0, 0, 0, 0, -1, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0]
  | 2 =>
    !![0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 1, 0, 0, 0, 0, 0, 0, 0;
       0, 1, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 1, 0, 0, 0, 0, 0;
       0, 0, 0, 1, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0]
  | 3 =>
    !![1, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 2, 0, 2;
       0, 0, 0, 0, 0, 0, -1, 0, -1;
       0, 0, 0, 0, 0, 0, 0, 0, 0;
       0, 0, 0, 0, 0, 0, 0, 0, 0]

theorem czxPlusIdentity_conj_int (i : Fin 4) :
    plusGaugeInt * czxPlusIdentityInt i * plusGaugeInvInt = plusConjInt i := by
  revert i
  decide

theorem czxPlusIdentity_conjMatrix (i : Fin 4) :
    conjMatrix plusGauge (czxPlusIdentity i) =
      (complexOfInt (plusConjInt i)).submatrix plusTau plusTau := by
  rw [plusGauge, conjMatrix_gaugeOfMatrix, czxPlusIdentity_eq, ← complexOfInt_mul,
    ← complexOfInt_mul, czxPlusIdentity_conj_int]

/-! ### The compression datum -/

private theorem czxPlusIdentity_triangular_int (i : Fin 4)
    (x y : BlockSpace plusBlockDim plusSlots 3) (h : plusOrd y.1 < plusOrd x.1) :
    plusConjInt i (plusTau x) (plusTau y) = 0 := by
  revert i x y
  decide

private theorem czxPlusIdentity_matched_int (i : Fin 4) (s : Fin 4)
    (p q : Fin (plusBlockDim s)) :
    plusConjInt i (plusTau ⟨Sum.inl ⟨s, Finset.mem_univ s⟩, p⟩)
        (plusTau ⟨Sum.inl ⟨s, Finset.mem_univ s⟩, q⟩) = plusTargetsInt s i p q := by
  revert i
  fin_cases s <;> revert p q <;> decide

private theorem czxPlusIdentity_unmatched_int (i : Fin 4) (t : Fin 3) (p q : Fin 1) :
    plusConjInt i (plusTau ⟨Sum.inr t, p⟩) (plusTau ⟨Sum.inr t, q⟩) = 0 := by
  revert i t p q
  decide

/-- **The multi-block asymmetric compression datum of Example E** (P5 note, Theorem 7.7,
clauses (i)–(iii), for `ex:p5ft-oscillating`). -/
def czxPlusIdentity_compression :
    MultiBlockCompression czxPlusIdentity plusSlots plusTargets :=
  MultiBlockCompression.ofRing (Int.castRingHom ℂ) plusOrd plusTau plusGauge plusConjInt
    czxPlusIdentity_conjMatrix plusTargetsInt plusTargets_eq czxPlusIdentity_triangular_int
    (fun i s p q => czxPlusIdentity_matched_int i s.1 p q) czxPlusIdentity_unmatched_int

/-! ### Consequences -/

/-- **The word-trace identity of Example E**: at every positive length the stacked tensor has
the word traces of `(1 + (-1)^L) id + 2 U_L` (P5 note, `ex:p5ft-oscillating`). -/
theorem czxPlusIdentity_trace_evalWord (w : List (Fin 4)) (hw : w ≠ []) :
    Matrix.trace (Kraus.evalWord czxPlusIdentity w) =
      (1 + (-1 : ℂ) ^ w.length) * Matrix.trace (Kraus.evalWord identityMPS w) +
        2 * Matrix.trace (Kraus.evalWord czxMPS w) := by
  have h := czxPlusIdentity_compression.trace_evalWord_eq_sum w hw
  rw [show plusSlots = Finset.univ from rfl, Fin.sum_univ_four] at h
  have h0 : Matrix.trace (Kraus.evalWord (plusTargets 0) w) =
      Matrix.trace (Kraus.evalWord identityMPS w) := rfl
  have h2 : Matrix.trace (Kraus.evalWord (plusTargets 2) w) =
      Matrix.trace (Kraus.evalWord czxMPS w) := rfl
  have h3 : Matrix.trace (Kraus.evalWord (plusTargets 3) w) =
      Matrix.trace (Kraus.evalWord czxMPS w) := rfl
  have hneg : ∀ T : MPSTensor 4 1, Matrix.trace (Kraus.evalWord (fun i => (-1 : ℂ) • T i) w) =
      (-1 : ℂ) ^ w.length * Matrix.trace (Kraus.evalWord T w) := by
    intro T
    rw [Kraus.evalWord_smul, Matrix.trace_smul, smul_eq_mul]
  have h1 : Matrix.trace (Kraus.evalWord (plusTargets 1) w) =
      (-1 : ℂ) ^ w.length * Matrix.trace (Kraus.evalWord identityMPS w) := hneg identityMPS
  rw [h, h0, h1, h2, h3]
  ring

/-- **Biorthogonal compression onto each of the four slots of Example E** (P5 note,
Theorem 7.7(iv)–(v), for `ex:p5ft-oscillating`). -/
theorem czxPlusIdentity_isReduction (s : {s // s ∈ plusSlots}) :
    IsReduction czxPlusIdentity (plusTargets s.1) (czxPlusIdentity_compression.left s)
      (czxPlusIdentity_compression.right s) :=
  czxPlusIdentity_compression.isReduction s

/-- Two distinct slots of Example E are biorthogonal (P5 note, Theorem 7.7(iv)). -/
theorem czxPlusIdentity_left_mul_right_of_ne {s t : {s // s ∈ plusSlots}} (h : s ≠ t) :
    czxPlusIdentity_compression.left s * czxPlusIdentity_compression.right t = 0 :=
  czxPlusIdentity_compression.left_mul_right_of_ne h

/-- **The dimension count of Example E**: `9 = 1 + 1 + 2 + 2 + 3` (P5 note,
Theorem 7.7(vii)). -/
theorem czxPlusIdentity_dim_eq : (9 : ℕ) = ∑ s ∈ plusSlots, plusBlockDim s + 3 :=
  czxPlusIdentity_compression.dim_eq

/-- **Nilpotency of the remainder of Example E** (P5 note, Theorem 7.7(vi)): a product of
seven remainder matrices vanishes. -/
theorem czxPlusIdentity_evalWord_remainder_eq_zero (w : List (Fin 4)) (hw : 7 ≤ w.length) :
    Kraus.evalWord czxPlusIdentity_compression.remainder w = 0 := by
  refine czxPlusIdentity_compression.evalWord_remainder_eq_zero w ?_
  change (4 : ℕ) + 3 ≤ w.length
  omega

end CZXCompression
