/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.

import TNLean.Wielandt.Primitivity.Definitions
import TNLean.Wielandt.Primitivity.EasyDirections
import TNLean.Wielandt.Primitivity.Equivalence
import TNLean.Wielandt.Primitivity.ImpliesIrreducible
import TNLean.Wielandt.Primitivity.ImpliesStronglyIrreducible
import TNLean.Wielandt.Primitivity.ImpliesStronglyIrreducibleAux
import TNLean.Wielandt.Primitivity.Normal
import TNLean.Wielandt.Primitivity.PrimitiveBridge
import TNLean.Wielandt.Primitivity.StronglyIrreducibleToFullRank
import TNLean.Wielandt.Primitivity.ToNormal
import TNLean.Wielandt.Primitivity.TracePairing
