/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.PEPS.AreaLaw.FiniteDomain
import TNLean.PEPS.AreaLaw.GraphLatticeDiamond
import Mathlib.Data.List.Chain
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Finset.Union

/-!
# Counting spatial charge-label paths

A reversed charge ancestry starts at its endpoint and follows successive
labelled anchors. Each step has graph length at most twice the charge radius.
The finite sets below enumerate all such labelled paths. A uniform bound `B`
on the number of nearby labels therefore gives at most `B^j` length-`j` paths.
Repeated labels at a common anchor remain distinct choices.

Source: OpenAI, *A two-dimensional area law from a global spectral gap*,
`08-scanner.tex`, lines 291–321, at `openai/math@adc7f124`.
-/

namespace TNLean.PEPS.AreaLaw.Scan

open scoped BigOperators

variable {V I : Type*} [Fintype I]

/-- All labels within twice the charge radius of a given endpoint. -/
noncomputable def nearbyChargeLabels (G : SimpleGraph V) (anchor : I → V)
    (r : ℕ) (x : V) : Finset I := by
  classical
  exact Finset.univ.filter fun i ↦ G.edist x (anchor i) ≤ ((2 * r : ℕ) : ℕ∞)

/-- Reversed labelled paths, generated by selecting a nearby label and continuing
from its anchor. Labels, including distinct labels at the same anchor, are retained. -/
noncomputable def chargeAnchorPaths (G : SimpleGraph V) (anchor : I → V)
    (r : ℕ) : V → ℕ → Finset (List I)
  | _, 0 => by classical exact {[]}
  | x, j + 1 => by
    classical
    exact (nearbyChargeLabels G anchor r x).biUnion fun i ↦
      (chargeAnchorPaths G anchor r (anchor i) j).image (List.cons i)

/-- Membership specifies exactly the length, the endpoint-to-first-anchor distance,
and all consecutive anchor distances. `08-scanner.tex`, lines 291–316. -/
theorem mem_chargeAnchorPaths_iff (G : SimpleGraph V) (anchor : I → V)
    (r : ℕ) (x : V) (j : ℕ) (labels : List I) :
    labels ∈ chargeAnchorPaths G anchor r x j ↔
      labels.length = j ∧
        (x :: labels.map anchor).IsChain
          (fun a b ↦ G.edist a b ≤ ((2 * r : ℕ) : ℕ∞)) := by
  classical
  induction j generalizing x labels with
  | zero => cases labels <;> simp [chargeAnchorPaths]
  | succ j ih =>
    cases labels with
    | nil => simp [chargeAnchorPaths]
    | cons i labels =>
      simp [chargeAnchorPaths, nearbyChargeLabels, ih, List.isChain_cons_cons,
        and_assoc, and_left_comm, and_comm]

/-- The actual recursive enumeration contains at most `B^j` paths if every anchor
step has at most `B` labelled choices. `08-scanner.tex`, lines 310–316. -/
theorem card_chargeAnchorPaths_le (G : SimpleGraph V) (anchor : I → V)
    (r B : ℕ) (hlabels : ∀ x, (nearbyChargeLabels G anchor r x).card ≤ B)
    (x : V) (j : ℕ) : (chargeAnchorPaths G anchor r x j).card ≤ B ^ j := by
  classical
  induction j generalizing x with
  | zero => simp [chargeAnchorPaths]
  | succ j ih =>
    calc
      _ ≤ ∑ i ∈ nearbyChargeLabels G anchor r x,
          ((chargeAnchorPaths G anchor r (anchor i) j).image (List.cons i)).card :=
        Finset.card_biUnion_le
      _ ≤ ∑ _i ∈ nearbyChargeLabels G anchor r x, B ^ j := by
        apply Finset.sum_le_sum
        intro i _
        exact Finset.card_image_le.trans (ih (anchor i))
      _ = (nearbyChargeLabels G anchor r x).card * B ^ j := by simp
      _ ≤ B * B ^ j := Nat.mul_le_mul_right _ (hlabels x)
      _ = B ^ (j + 1) := (pow_succ' B j).symm

/-- A vertex-ball bound and bounded label multiplicity bound the labels available
at one spatial step. `08-scanner.tex`, lines 310–316. -/
theorem card_nearbyChargeLabels_le_of_vertex_count [Fintype V] [DecidableEq V]
    (G : SimpleGraph V) (anchor : I → V) (r N μ : ℕ)
    (hball : ∀ x, (Finset.univ.filter fun y ↦ G.edist x y ≤ ((2 * r : ℕ) : ℕ∞)).card ≤ N)
    (hmult : ∀ y, (Finset.univ.filter fun i ↦ anchor i = y).card ≤ μ)
    (x : V) : (nearbyChargeLabels G anchor r x).card ≤ N * μ := by
  classical
  let ball := Finset.univ.filter fun z ↦ G.edist x z ≤ ((2 * r : ℕ) : ℕ∞)
  have hcount := Finset.sum_card_fiberwise_eq_card_filter Finset.univ ball anchor
  have heq : (Finset.univ.filter fun i ↦ anchor i ∈ ball) = nearbyChargeLabels G anchor r x := by
    ext i
    simp [ball, nearbyChargeLabels]
  rw [heq] at hcount
  rw [← hcount]
  calc
    _ ≤ ∑ _z ∈ ball, μ := Finset.sum_le_sum fun z _ ↦ hmult z
    _ = ball.card * μ := by simp
    _ ≤ N * μ := Nat.mul_le_mul_right μ (hball x)

/-- Actual induced square-lattice domains give an explicit polynomial spatial
factor, including repeated-anchor multiplicity. Holes and disconnected components
require no extra hypothesis. `08-scanner.tex`, lines 310–316, and the lattice
ball count `01-preliminaries.tex`, lines 81–87. -/
theorem card_nearbyChargeLabels_domainGraph_le (Λ : Finset (ℤ × ℤ))
    (anchor : I → Site Λ) (r μ : ℕ)
    (hmult : ∀ y, (Finset.univ.filter fun i ↦ anchor i = y).card ≤ μ)
    (x : Site Λ) :
    (nearbyChargeLabels (domainGraph Λ) anchor r x).card ≤
      (1 + 2 * (2 * r) * (2 * r + 1)) * μ := by
  apply card_nearbyChargeLabels_le_of_vertex_count _ _ _ _ _ _ hmult
  intro y
  apply card_le_diamond_of_edist_le Subtype.val _ Subtype.val_injective _ y (2 * r)
    (fun z hz ↦ (Finset.mem_filter.mp hz).2)
  intro a b hab
  simp only [domainGraph] at hab
  unfold latticeL1Distance
  rcases hab with ⟨h₁, h₂ | h₂⟩ | ⟨h₁, h₂ | h₂⟩ <;> omega


/-- The actual square-lattice bound for length-`j` labelled anchor paths, with
bounded label multiplicity and no supplied path-count hypothesis.
`08-scanner.tex`, lines 310–316. -/
theorem card_chargeAnchorPaths_domainGraph_le (Λ : Finset (ℤ × ℤ))
    (anchor : I → Site Λ) (r μ : ℕ)
    (hmult : ∀ y, (Finset.univ.filter fun i ↦ anchor i = y).card ≤ μ)
    (x : Site Λ) (j : ℕ) :
    (chargeAnchorPaths (domainGraph Λ) anchor r x j).card ≤
      ((1 + 2 * (2 * r) * (2 * r + 1)) * μ) ^ j :=
  card_chargeAnchorPaths_le _ _ _ _
    (card_nearbyChargeLabels_domainGraph_le Λ anchor r μ hmult) x j

end TNLean.PEPS.AreaLaw.Scan
