/-
Copyright (c) 2026 Sirui Lu and TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sirui Lu
-/
import TNLean.Channel.PartialTranspose
import TNLean.Channel.ReductionCriterion
import Mathlib.Analysis.Matrix.Order

/-!
# Bipartite separable states and the PPT criterion (forward direction)

Wolf's Chapter 3, Section 3.2 (the paragraph *Detecting entanglement*) recalls
that a bipartite state `ρ ∈ M_d ⊗ M_{d'}` is **separable** when it is a convex
combination of pure product states,
`ρ = Σ_i p_i |a_i⟩⟨a_i| ⊗ |b_i⟩⟨b_i|`,
and observes that a positive map applied to one factor of a separable state stays
positive semidefinite, since "tensor products and convex combinations of positive
operators are again positive".  Applied to the transposition this is the **PPT
(positive partial transpose) criterion** of Wolf Example 3.1: a separable state
has `ρ^{T₁} ≥ 0`, so a negative partial transpose certifies entanglement.

This file formalizes that separability foundation and the forward direction of the
PPT criterion.

## The separability predicate

A pure product state `|a⟩⟨a| ⊗ |b⟩⟨b|` is a Kronecker product of two rank-one
positive semidefinite matrices, and a positive coefficient `p_i` can be absorbed
into either factor.  Replacing each rank-one factor by a general positive
semidefinite matrix yields the equivalent "sum of positive semidefinite product
operators" form: a matrix is separable when it equals a finite sum
`Σ_i A_i ⊗ B_i` with every `A_i` and `B_i` positive semidefinite.  Up to
normalization this is Wolf's convex-combination-of-pure-product-states definition,
because a positive semidefinite matrix is itself a positive combination of rank-one
projectors and the spectral weights merge into the coefficients `p_i`.
`Matrix.IsSeparable` records this form, which is the cone generated by the product
positive semidefinite operators.

## Main definitions

* `Matrix.IsSeparable`: a bipartite matrix is a finite sum of Kronecker products of
  positive semidefinite matrices.

## Main results

* `Matrix.IsSeparable.posSemidef`: a separable matrix is positive semidefinite.
* `Matrix.isSeparable_kronecker`: a Kronecker product of two positive semidefinite
  matrices is separable.
* `Matrix.IsSeparable.add`: separable matrices are closed under addition.
* `Matrix.IsSeparable.smul`: separable matrices are closed under multiplication by
  a nonnegative real scalar.
* `Matrix.IsSeparable.isPPT`: **the PPT criterion, forward direction** — every
  separable matrix has the positive-partial-transpose property, `ρ^{T₁} ≥ 0`.
* `Matrix.IsSeparable.tensorMapId_tEta_one_posSemidef`: the reduction map at `n = 1`
  applied to the first factor of a separable matrix stays positive semidefinite,
  `(T₁ ⊗ id)(ρ) ≥ 0`, the separability instance of Wolf eq. (3.18) at `n = 1`.

## Scope

Only the *forward* direction of the PPT criterion is formalized: separable implies
positive partial transpose.  The converse is false in general (entangled states
with positive partial transpose exist once the dimension exceeds `ℂ² ⊗ ℂ²` and
`ℂ² ⊗ ℂ³`; Wolf Prop. 3.4, Horodecki), and is not part of this development.

The reduction-map positivity recorded here is the `n = 1` instance: a separable
state is exactly a state of Schmidt number one.  The Schmidt-number filtration for
general `n` — of which separability is the lowest level — and the resulting general
reduction criterion of Wolf eq. (3.18) with its Schmidt-number premise are a
further step built on the predicate introduced here; they are recorded in
`docs/paper-gaps/wolf_reduction_criterion_schmidt_premise.tex` and are not
formalized in this file.

## References

* [M. Wolf, *Quantum Channels & Operations: Guided Tour*, Chapter 3,
  Section 3.2, the *Detecting entanglement* paragraph and
  Example 3.1, equations (3.16)--(3.17)][Wolf2012QChannels]
-/

open scoped Matrix ComplexOrder Kronecker
open Matrix

namespace Matrix

variable {d d' : ℕ}

/-! ## The separability predicate -/

/-- **Separable bipartite matrix** (Wolf §3.2).  A bipartite matrix `ρ` on
`Fin d × Fin d'` is separable when it is a finite sum of Kronecker products of
positive semidefinite matrices,

  `ρ = Σ_i A_i ⊗ B_i`,   `A_i ≥ 0`,   `B_i ≥ 0`.

Up to normalization this is Wolf's convex combination of pure product states
`Σ_i p_i |a_i⟩⟨a_i| ⊗ |b_i⟩⟨b_i|`: each pure product state is a Kronecker product
of two rank-one positive semidefinite matrices, the coefficient `p_i ≥ 0` is
absorbed into a factor, and conversely a positive semidefinite matrix is a positive
combination of rank-one projectors. -/
def IsSeparable (ρ : Matrix (Fin d × Fin d') (Fin d × Fin d') ℂ) : Prop :=
  ∃ (ι : Type) (_ : Fintype ι) (A : ι → Matrix (Fin d) (Fin d) ℂ)
    (B : ι → Matrix (Fin d') (Fin d') ℂ),
    (∀ i, (A i).PosSemidef ∧ (B i).PosSemidef) ∧ ρ = ∑ i, A i ⊗ₖ B i

/-! ## Basic closure properties -/

/-- A Kronecker product of two positive semidefinite matrices is separable: it is
the one-term sum `Σ_i A_i ⊗ B_i` with a single index. -/
theorem isSeparable_kronecker {A : Matrix (Fin d) (Fin d) ℂ}
    {B : Matrix (Fin d') (Fin d') ℂ} (hA : A.PosSemidef) (hB : B.PosSemidef) :
    IsSeparable (A ⊗ₖ B) := by
  refine ⟨PUnit, inferInstance, fun _ => A, fun _ => B, fun _ => ⟨hA, hB⟩, ?_⟩
  simp

/-- **Separable matrices are closed under addition.** Concatenating the two index
families realizes the sum `ρ + σ` as a single sum of product operators. -/
theorem IsSeparable.add {ρ σ : Matrix (Fin d × Fin d') (Fin d × Fin d') ℂ}
    (hρ : IsSeparable ρ) (hσ : IsSeparable σ) : IsSeparable (ρ + σ) := by
  obtain ⟨ι, _, A, B, hAB, rfl⟩ := hρ
  obtain ⟨κ, _, C, D, hCD, rfl⟩ := hσ
  refine ⟨ι ⊕ κ, inferInstance, Sum.elim A C, Sum.elim B D, ?_, ?_⟩
  · rintro (i | j)
    · exact hAB i
    · exact hCD j
  · rw [Fintype.sum_sum_type]
    simp [Sum.elim_inl, Sum.elim_inr]

/-- **Separable matrices are closed under nonnegative scaling.** Absorbing the real
scalar `c ≥ 0` into the first factor of each product keeps every factor positive
semidefinite. -/
theorem IsSeparable.smul {ρ : Matrix (Fin d × Fin d') (Fin d × Fin d') ℂ}
    (hρ : IsSeparable ρ) {c : ℝ} (hc : 0 ≤ c) : IsSeparable ((c : ℂ) • ρ) := by
  obtain ⟨ι, _, A, B, hAB, rfl⟩ := hρ
  refine ⟨ι, inferInstance, fun i => (c : ℂ) • A i, B, fun i => ⟨?_, (hAB i).2⟩, ?_⟩
  · exact (hAB i).1.smul (by exact_mod_cast hc)
  · rw [Finset.smul_sum]
    exact Finset.sum_congr rfl fun i _ => (smul_kronecker (c : ℂ) (A i) (B i)).symm

/-! ## Separable matrices are positive semidefinite -/

/-- **A separable matrix is positive semidefinite** (Wolf §3.2).  Each summand
`A_i ⊗ B_i` is a Kronecker product of positive semidefinite matrices, hence
positive semidefinite, and a finite sum of positive semidefinite matrices is
positive semidefinite. -/
theorem IsSeparable.posSemidef {ρ : Matrix (Fin d × Fin d') (Fin d × Fin d') ℂ}
    (hρ : IsSeparable ρ) : ρ.PosSemidef := by
  obtain ⟨ι, _, A, B, hAB, rfl⟩ := hρ
  exact posSemidef_sum Finset.univ fun i _ => PosSemidef.kronecker (hAB i).1 (hAB i).2

/-! ## The PPT criterion (forward direction) -/

/-- The first-factor partial transpose is additive over a finite sum: it commutes
with `Finset.sum` because it is an entrywise reindexing of the matrix. -/
theorem partialTransposeLeft_sum {ι : Type*} (s : Finset ι)
    (f : ι → Matrix (Fin d × Fin d') (Fin d × Fin d') ℂ) :
    partialTransposeLeft (∑ i ∈ s, f i) = ∑ i ∈ s, partialTransposeLeft (f i) := by
  ext p q
  simp only [partialTransposeLeft_apply, Matrix.sum_apply]

/-- **PPT criterion, forward direction (Wolf §3.2, Example 3.1).** Every separable
matrix has the positive-partial-transpose property, `ρ^{T₁} ≥ 0`.

The partial transpose is linear and acts on a product by transposing the first
factor, `(A ⊗ B)^{T₁} = Aᵀ ⊗ B`.  Writing `ρ = Σ_i A_i ⊗ B_i` with each factor
positive semidefinite, the partial transpose is `Σ_i (A_i)ᵀ ⊗ B_i`; the transpose
of a positive semidefinite matrix is positive semidefinite, so each summand is a
Kronecker product of positive semidefinite matrices and the sum is positive
semidefinite.  Consequently a negative partial transpose certifies entanglement. -/
theorem IsSeparable.isPPT {ρ : Matrix (Fin d × Fin d') (Fin d × Fin d') ℂ}
    (hρ : IsSeparable ρ) : IsPPT ρ := by
  obtain ⟨ι, _, A, B, hAB, rfl⟩ := hρ
  rw [IsPPT, partialTransposeLeft_sum]
  refine posSemidef_sum Finset.univ fun i _ => ?_
  rw [partialTransposeLeft_kronecker]
  exact PosSemidef.kronecker (posSemidef_transpose_iff.mpr (hAB i).1) (hAB i).2

/-! ## The reduction map on a separable state (Wolf eq. (3.18) at `n = 1`) -/

/-- Applying a map to the first factor distributes over a finite sum of bipartite
matrices, because the ampliation `tensorMapId T` is linear. -/
theorem tensorMapId_sum {d'' : ℕ}
    (T : Matrix (Fin d) (Fin d) ℂ →ₗ[ℂ] Matrix (Fin d') (Fin d') ℂ) {ι : Type*}
    (s : Finset ι) (f : ι → Matrix (Fin d × Fin d'') (Fin d × Fin d'') ℂ) :
    tensorMapId T (∑ i ∈ s, f i) = ∑ i ∈ s, tensorMapId T (f i) :=
  map_sum (tensorMapIdLM T) f s

/-- **Reduction map at `n = 1` on a separable state (Wolf eq. (3.18), `n = 1`).**
For a separable matrix `ρ`, applying the reduction map `T₁(X) = tr(X) • 1 − X` to
the first tensor factor yields a positive semidefinite operator, `(T₁ ⊗ id)(ρ) ≥ 0`.

The reduction map at `n = 1` is positive, so it maps each positive semidefinite
first factor `A_i` of `ρ = Σ_i A_i ⊗ B_i` to a positive semidefinite matrix; the
ampliation acts by `(T₁ ⊗ id)(A_i ⊗ B_i) = T₁(A_i) ⊗ B_i`, each summand is a
Kronecker product of positive semidefinite matrices, and the sum is positive
semidefinite.  This is the separability instance of the operator inequality that
underlies the reduction criterion at `n = 1`. -/
theorem IsSeparable.tensorMapId_tEta_one_posSemidef [NeZero d]
    {ρ : Matrix (Fin d × Fin d') (Fin d × Fin d') ℂ} (hρ : IsSeparable ρ) :
    (tensorMapId (tEta d (1 : ℝ)) ρ).PosSemidef := by
  obtain ⟨ι, _, A, B, hAB, rfl⟩ := hρ
  have hpos : IsPositiveMap (tEta d (1 : ℝ)) := by
    have h := reductionMap_one_isPositiveMap (D := d)
    rwa [reductionMap_eq_tEta, Nat.cast_one] at h
  rw [tensorMapId_sum]
  refine posSemidef_sum Finset.univ fun i _ => ?_
  rw [tensorMapId_kronecker]
  exact PosSemidef.kronecker (hpos (A i) (hAB i).1) (hAB i).2

end Matrix
