/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.PEPS.AreaLaw
import TNLean.PEPS.Approximation

#print axioms TNLean.PEPS.AreaLaw.Site
#print axioms TNLean.PEPS.AreaLaw.Configuration
#print axioms TNLean.PEPS.AreaLaw.domainGraph
#print axioms TNLean.PEPS.AreaLaw.IsAdmissibleSupport
#print axioms TNLean.PEPS.AreaLaw.AdmissibleSupport
#print axioms TNLean.PEPS.AreaLaw.graphNeighborhood
#print axioms TNLean.PEPS.AreaLaw.edgeBoundary
#print axioms TNLean.PEPS.AreaLaw.ambientDilation
#print axioms TNLean.PEPS.AreaLaw.configurationSplit
#print axioms TNLean.PEPS.AreaLaw.card_configuration
#print axioms TNLean.PEPS.AreaLaw.edgeBoundary_empty
#print axioms TNLean.PEPS.AreaLaw.edgeBoundary_univ
#print axioms TNLean.PEPS.AreaLaw.isAdmissibleSupport_singleton
#print axioms TNLean.PEPS.AreaLaw.exists_walk_length_le_iff_edist_le
#print axioms TNLean.PEPS.AreaLaw.isAdmissibleSupport_zero_iff
#print axioms TNLean.PEPS.AreaLaw.isAdmissibleSupport_pair_of_adj
#print axioms TNLean.PEPS.AreaLaw.ambientDilation_zero
#print axioms TNLean.PEPS.AreaLaw.rectangleEmbedding
#print axioms TNLean.PEPS.AreaLaw.rectangleEmbedding_injective
#print axioms TNLean.PEPS.AreaLaw.rectangularDomain
#print axioms TNLean.PEPS.AreaLaw.rectangleSiteEquiv
#print axioms TNLean.PEPS.AreaLaw.rectangleSiteEquiv_val
#print axioms TNLean.PEPS.AreaLaw.rectangleGraphIso
#print axioms TNLean.PEPS.AreaLaw.rectangleConfigurationEquiv
#print axioms TNLean.PEPS.AreaLaw.isAdmissibleSupport_rectangle_pair_of_adj
#print axioms TNLean.PEPS.AreaLaw.StateSpace
#print axioms TNLean.PEPS.AreaLaw.LocalHamiltonian
#print axioms TNLean.PEPS.AreaLaw.LocalHamiltonian.operator
#print axioms TNLean.PEPS.AreaLaw.LocalHamiltonian.operator_isHermitian
#print axioms TNLean.PEPS.AreaLaw.LocalHamiltonian.zero
#print axioms TNLean.PEPS.AreaLaw.localLift
#print axioms TNLean.PEPS.AreaLaw.localLift_mem_supportedOperators
#print axioms TNLean.PEPS.AreaLaw.IsGappedGroundState
#print axioms TNLean.PEPS.AreaLaw.reducedState
#print axioms TNLean.PEPS.AreaLaw.reducedState_isHermitian
#print axioms TNLean.PEPS.AreaLaw.regionalEntropy
#print axioms TNLean.PEPS.AreaLaw.UniformAreaLaw
#print axioms TNLean.PEPS.AreaLaw.Exponents.boxError
#print axioms TNLean.PEPS.AreaLaw.Exponents.scannerMu
#print axioms TNLean.PEPS.AreaLaw.Exponents.scannerNu
#print axioms TNLean.PEPS.AreaLaw.Exponents.scannerEll
#print axioms TNLean.PEPS.AreaLaw.Exponents.scannerOmega
#print axioms TNLean.PEPS.AreaLaw.Exponents.scannerKappa
#print axioms TNLean.PEPS.AreaLaw.Exponents.amplificationEpsilon
#print axioms TNLean.PEPS.AreaLaw.Exponents.beta
#print axioms TNLean.PEPS.AreaLaw.Exponents.amplificationPower
#print axioms TNLean.PEPS.AreaLaw.Exponents.alpha
#print axioms TNLean.PEPS.AreaLaw.Exponents.geometryDelta
#print axioms TNLean.PEPS.AreaLaw.Exponents.zeta
#print axioms TNLean.PEPS.AreaLaw.Exponents.rho
#print axioms TNLean.PEPS.AreaLaw.Exponents.geometryEll
#print axioms TNLean.PEPS.AreaLaw.Exponents.alpha_gt
#print axioms TNLean.PEPS.AreaLaw.Exponents.geometry_gaps
#print axioms TNLean.PEPS.AreaLaw.Geometry.IsAllowedSlope
#print axioms TNLean.PEPS.AreaLaw.Geometry.TemplatePolygon
#print axioms TNLean.PEPS.AreaLaw.Geometry.TemplatePolygon.region
#print axioms TNLean.PEPS.AreaLaw.Geometry.integerPoint
#print axioms TNLean.PEPS.AreaLaw.Geometry.Template
#print axioms TNLean.PEPS.AreaLaw.Geometry.Template.IsSeparated
#print axioms TNLean.PEPS.AreaLaw.Geometry.Template.core
#print axioms TNLean.PEPS.AreaLaw.Geometry.Template.collar
#print axioms TNLean.PEPS.AreaLaw.Geometry.OrderedTwoFamilyPartition
#print axioms TNLean.PEPS.AreaLaw.Geometry.OrderedTwoFamilyPartition.earlierSameFamily
#print axioms TNLean.PEPS.Approximation.Configuration
#print axioms TNLean.PEPS.Approximation.StateSpace
#print axioms TNLean.PEPS.Approximation.SquareHamiltonian
#print axioms TNLean.PEPS.Approximation.SquareHamiltonian.operator
#print axioms TNLean.PEPS.Approximation.SquareHamiltonian.IsGappedGroundState
#print axioms TNLean.PEPS.Approximation.pepsVector
#print axioms TNLean.PEPS.Approximation.HasPEPSApproximation
#print axioms TNLean.PEPS.Approximation.PolynomialPEPSApproximation
