import TNLean.PEPS.AreaLaw.Geometry.InitialRegionInteriors
import TNLean.PEPS.AreaLaw.Geometry.InitialRegionBoundaries
import TNLean.PEPS.AreaLaw.Geometry.InitialLatticePartition

#print axioms TNLean.PEPS.AreaLaw.Geometry.cellFanRunRegions_disjoint_interiors
#print axioms TNLean.PEPS.AreaLaw.Geometry.initialOpenRegion_pairwise_disjoint
#print axioms TNLean.PEPS.AreaLaw.Geometry.initialBirthRegion_frontier_avoid_lattice
#print axioms TNLean.PEPS.AreaLaw.Geometry.initialOpenRegion_frontier_avoid_lattice
#print axioms TNLean.PEPS.AreaLaw.Geometry.initialBirthRegion_lattice_mem_iff_initialOpenRegion
#print axioms TNLean.PEPS.AreaLaw.Geometry.exists_unique_initialOpenRegion_integerPoint
